### ISSUE TITLE
R 3.1.3 is not supported

### ISSUE THREAD

**Issue by stenver** [jokergoo/ComplexHeatmap#1]
Hello, here is what i get when i try to install complex heap map for R 3.1.3

```
> source("http://bioconductor.org/biocLite.R")
Bioconductor version 3.0 (BiocInstaller 1.16.2), ?biocLite for help
> biocLite("ComplexHeatmap")
BioC_mirror: http://bioconductor.org
Using Bioconductor version 3.0 (BiocInstaller 1.16.2), R version 3.1.3.
Installing package(s) 'ComplexHeatmap'
Warning message:
package 'ComplexHeatmap' is not available (as a binary package for R version 3.1.3) 
```

**Comment by lgatto** [comment]
Ineed. `ComplexHeatmap` was added to Bioconductor 3.1, which requires a more recent version of `R`. If you install `R` 3.2 (which has just been released), you will have access to the Bioconductor 3.1 packages, including `ComplexHeatmap`.  (Actually, you might want to wait 24 hours for Bioconductor 3.1 to be released as non-devel version).

**Comment by stenver** [comment]
Thanks that worked!

Consider changing this line to avoid future confusion:
https://github.com/jokergoo/ComplexHeatmap/blob/master/DESCRIPTION#L8

**Comment by jokergoo** [comment]
`ComplexHeatmap` is now in the development version of bioconductor, so you can not install in the usually way. See following link (http://www.bioconductor.org/developers/how-to/useDevel/). It will be shifted to the release version of bioconductor this or next week (in bioconductor 3.1).

But you can still download the source code (ComplexHeatmap_*.tar.gz) and install it in the command line:

```
R CMD INSTALL ComplexHeatmap_*.tar.gz
```

However, you need to install other packages which `ComplexHeatmap` is dependent on by yourself.

**Comment by kcha** [comment]
Just to add, I was able to get around this issue by installing the package (and its dependencies) directly from GitHub using `devtools`:
```r
devtools::install_github("jokergoo/ComplexHeatmap")
```

BTW, this package looks great!
