### ISSUE TITLE
Error with plotDataFrame()

### ISSUE THREAD

**Issue by kassambara** [jokergoo/ComplexHeatmap#10]
I got an error using the R code below:
  
```
library("ComplexHeatmap")
plotDataFrame(as.data.frame(mtcars))
```

Error code:

Error in Heatmap(df[, ci, drop = FALSE], name = group_names[i], column_title = column_title,  : 
 can't find the object 'split2' 

Am I doing something wrong?

Thank you for your great work!

**Comment by jokergoo** [comment]
Thanks for report this. It is a bug. Now I fixed it.

**Comment by kassambara** [comment]
It works. Thank you!
