### ISSUE TITLE
distinctive random colors for annotions

### ISSUE THREAD

**Issue by jokergoo** [jokergoo/ComplexHeatmap#102]
https://github.com/ronammar/randomcoloR

**Comment by jokergoo** [comment]
`rand_color()` is re-implemented in [circlize](https://github.com/jokergoo/circlize) package.

**Comment by crazyhottommy** [comment]
is this implemented in the column annotation? I have too many annotations and do not want to specify manually for all of them, so I am depending on rand_color() to give me distinct colors.

Tommy

**Comment by jokergoo** [comment]
Yes, you can see some random generations:

![image](https://user-images.githubusercontent.com/449218/30933319-849e70ba-a3ca-11e7-9a29-161b57cb2b00.png)
