### ISSUE TITLE
put legend in one column

### ISSUE THREAD

**Issue by RNA-Ninja** [jokergoo/ComplexHeatmap#103]
This code produces figure in which legend **ht1** and legend **type2** are in one column but legend **type1** is next to legend **ht1** . I want to put legend **type1** bellow legend**type2**.
(code from https://bioconductor.org/packages/devel/bioc/vignettes/ComplexHeatmap/inst/doc/s5.legend.html)
> library(ComplexHeatmap)
> library(circlize)
> set.seed(123)
> mat = matrix(rnorm(80, 2), 8, 10)
> mat = rbind(mat, matrix(rnorm(40, -2), 4, 10))
> rownames(mat) = paste0("R", 1:12)
> colnames(mat) = paste0("C", 1:10)
> ha_column = HeatmapAnnotation(df = data.frame(type1 = c(rep("a", 5), rep("b", 5))), 
>                               col = list(type1 = c("a" =  "red", "b" = "blue")))
> ha_row = rowAnnotation(df = data.frame(type2 = c(rep("A", 6), rep("B", 6))), 
>                        col = list(type2 = c("A" =  "green", "B" = "orange")), width = unit(1, "cm"))
> ht1 = Heatmap(mat, name = "ht1", column_title = "Heatmap 1", top_annotation = ha_column)
> ht_list = ht1 + ha_row
> draw(ht_list)

**Comment by jokergoo** [comment]
Hi, you can have a look at this post:

http://zuguang.de/blog/html/merge_heatmap_and_annotation_legend.html

**Comment by RNA-Ninja** [comment]
I got 2 errors/issue,
1. `anno_legend_list`  gives error in ` invalid argument type ` although it gives desired plot.
2. However bigger problem is setting `annotation_legend_param` to  `"continuous"` do not produce continuous color legend!

```
library(ComplexHeatmap)
library(circlize)
df = data.frame(type = c(rep("a", 5), rep("b", 5)),
                age = sample(1:20, 10))
mat = matrix(rnorm(80, 2), 8, 10)
ha = HeatmapAnnotation(df = df,
                       col = list(type = c("a" = "red", "b" = "blue"),
                                  age = colorRamp2(c(0, 20), c("white", "red"))),
                       annotation_legend_param= list(age = list(color_bar = "continuous")),
                       show_legend = FALSE)

anno_legend_list = lapply(ha@anno_list[c("type", "age")], 
                          function(anno) color_mapping_legend(anno@color_mapping, plot = FALSE))
anno_legend_list ##gives Error

ht = Heatmap(mat, name = "ht", top_annotation = ha, show_heatmap_legend = FALSE)
heatmap_legend = color_mapping_legend(ht@matrix_color_mapping, plot = FALSE)
heatmap_legend  ##gives Error

## color-bar for age is not continuous
draw(ht, heatmap_legend_list = c(anno_legend_list, list(heatmap_legend)))
```

**Comment by jokergoo** [comment]
Then I would guess you are using an older version of the package.

I have tested it with version 0.12.0 and it works fine.

![snapshot8](https://user-images.githubusercontent.com/449218/27428173-884ff04c-5741-11e7-84b0-62a1be16fe5d.png)

**Comment by RNA-Ninja** [comment]
I am using latest version of ComplexHeatmap from github. `sessionInfo()` shows `ComplexHeatmap_1.13.2`

**Moreover I expected the `age` legend bar continuous as in this figure:**

![rplot](https://user-images.githubusercontent.com/28019759/27437462-4e37ead8-5730-11e7-98f3-bdbb988a0b75.png)

**Comment by jokergoo** [comment]
I have updated the package. Now it is easier to merge heatmap legends and annotation legends into one single column:

```
df = data.frame(type = c(rep("aaaaaaa", 5), rep("b", 5)),
                age = sample(1:20, 10))
mat = matrix(rnorm(80, 2), 8, 10)
ha = HeatmapAnnotation(df = df,
                       col = list(type = c("aaaaaaa" = "red", "b" = "blue"),
                                  age = colorRamp2(c(0, 20), c("white", "red"))),
                       annotation_legend_param= list(age = list(color_bar = "continuous")))

ht = Heatmap(mat, name = "ht", top_annotation = ha)
draw(ht, merge_legends = TRUE)
```

You need to install the newest version:

```
library(devtools)
install_github("jokergoo/ComplexHeatmap")
```
<img width="394" alt="screen shot 2017-06-23 at 21 56 05" src="https://user-images.githubusercontent.com/449218/27500343-72617594-5868-11e7-8726-5f21733dd39d.png">
