### ISSUE TITLE
Color scale goes further than specified

### ISSUE THREAD

**Issue by nickhir** [jokergoo/ComplexHeatmap#1038]
Hello,

I am specifying the color gradient manually using the colorRamp2 function. However, if I want the values to range between -3 and 3, the color gradient nonethless goes up to -4 and 4.

Here is a code to reproduce what I mean.
```r
library(circlize)
library(ComplexHeatmap)


m <- matrix(sample(-6:6, 25, replace = T),ncol=5)
cap_value=3
m[m>cap_value] = cap_value 

m[ m < -cap_value] = -cap_value 

col_fun = colorRamp2(c(-cap_value, 0, cap_value), c("blue", "white", "red"))

Heatmap(m, name = "mat", col = col_fun, cluster_rows = F, cluster_columns = F)
```
The resulting heatmap looks like this:

![image](https://user-images.githubusercontent.com/49643134/212336934-1f73378a-15c7-4894-96f4-cc7108611b99.png)

If I set `cap_value=2` everything works as intended. 

Is there a way to let the gradient only go up to the specified value?

Cheers!

**Comment by a-a-k** [comment]
Take a look here #659
