### ISSUE TITLE
cluster using all data in list of heatmaps

### ISSUE THREAD

**Issue by walter-eckalbar** [jokergoo/ComplexHeatmap#104]
Is it possible to cluster a list of heatmaps using the data from all the heat maps rather than just the main heatmap? I don't see that explained in the docs.

**Comment by jokergoo** [comment]
You can check #57 .

The basic idea is to merge all matrix into a big matrix and then perform clustering on rows, assign the clustering to a object, say `hc` and assign to `cluster_rows` argument. See following example:

```{r}
mat = rbind(mat1, mat2)
hc = hclust(dist(mat))
Heatmap(mat1, cluster_rows = hc) + Heatmap(mat2)
```

**Comment by walter-eckalbar** [comment]
Perfect, thanks.
