### ISSUE TITLE
Inconsistency between heatmap and legend color palettes

### ISSUE THREAD

**Issue by a-a-k** [jokergoo/ComplexHeatmap#1040]
[My data](https://drive.google.com/file/d/1VDYDPVxUl31SFUdN0kjmRekBmtHZ5Uo5/view?usp=sharing)

What am I trying is plotting heatmap with custom color palette, but when I'm adding a legend it seems to mismatch heatmap's palette. More precisely, as you can see from the picture below, the heatmap itself contains a lot of dark red colored cells for zero values, but the legend does not contain dark red at all. The legend starts from a bright red color, and I can't figure out why. Could you help me with that? Here is the code I use (3 single-column heatmaps are omitted for brevity):
```
col_fun_bact <- colorRamp2(c(0, 0.3, 0.6, 1, 3, 5, 10, 15, 20, 40, 60, 80), c("#771318", "#831419", "#A31116", "#FF0D0D", "#FF4E11", "#FF8E15", "#FAB733", "#ACB334", "#69B34C", "#026402", "#024818", "#033220"))
lgd <- list(col_fun = col_fun_bact, title = "", at = c(0, 0.3, 0.6, 1, 3, 5, 10, 15, 20, 40, 60, 80), legend_height = unit(26, "lines"))

column_split = rep("group1", 24)
column_split[9:16] = "group2"
column_split[17:24] = "group3"

row_split = rep("group1", 26)
row_split[21:26] = "group2"

hm_bact = Heatmap(
  bact_matrix,
  col = col_fun_bact,
  name = "Bacteria",
  heatmap_legend_param = lgd,
  cluster_columns = FALSE,
  cluster_rows = FALSE,
  show_row_names = TRUE,
  column_labels = c(15, 18, 50, 53, 55, 67, 69, 71, 15, 18, 50, 53, 55, 67, 69, 71, 15, 18, 50, 53, 55, 67, 69, 71),
  row_title = NULL,
  top_annotation = HeatmapAnnotation(foo = anno_block(gp = gpar(fill="grey"),
                                                      labels = c("R1", "R2", "R3"),
                                                      labels_gp = gpar(col = "white", fontsize = 14))),
  column_split = column_split,
  left_annotation = rowAnnotation(foo = anno_block(gp = gpar(fill="grey"),
                                                   labels = c("Bacteria", "Archaea"),
                                                   labels_gp = gpar(col = "white", fontsize = 14))),
  row_split = row_split,
  row_names_gp = gpar(fontface = "italic"))

hm_bact + rowAnnotation(rn = anno_text(rownames(bact_matrix), location = unit(0, "npc"), just = "left", gp = gpar(fontface = "italic")))
```
The heatmap:

![image](https://user-images.githubusercontent.com/5455861/212469573-d93e3d00-5947-4d1b-b229-f0ad3b308984.png)

Zoomed legend bottom:

![image](https://user-images.githubusercontent.com/5455861/212470128-31eceab0-eb6e-4417-80f5-4dbb5f2392de.png)

**Comment by blueskypie** [comment]
what's the min and max value of `bact_matrix`?

**Comment by a-a-k** [comment]
> what's the min and max value of `bact_matrix`?

![image](https://user-images.githubusercontent.com/5455861/215467017-b885d999-9a1c-4393-8b12-3ee905f4bed7.png)

**Comment by blueskypie** [comment]
I think it could be due to your setting in 
`col_fun_bact <- colorRamp2(c(0, 0.3, 0.6, 1, 3, 5, 10, 15, 20, 40, 60, 80), c("#771318", "#831419", "#A31116", "#FF0D0D", "#FF4E11", "#FF8E15", "#FAB733", "#ACB334", "#69B34C", "#026402", "#024818", "#033220"))`
that the red color values were too dense and there were errors mapping those values to the colors you set. As you can see, there is no color difference between 0 and 0.6 in the plotted legend. 

try removing 0.3, 0.6, and 1 from `colorRamp2`

**Comment by blueskypie** [comment]
Also, I think heatmap means to present an overall pattern, thus no need to set many breaks in the legend since it's difficult for human eyes to map colors to values precisely.

**Comment by blueskypie** [comment]
In addition, I just noticed that the largest value in your `colorRamp2` definition is 80 whereas 96 in the bact_matrix

**Comment by a-a-k** [comment]
thank you

**Comment by a-a-k** [comment]
@blueskypie good point, thank you! btw, could you advise something for legend height alignment according to heatmap height itself? I'm trying to get them with same height but can't achieve

**Comment by a-a-k** [comment]
@jokergoo can I manage dpi somehow?
