### ISSUE TITLE
Splitting heatmap causes row annotation axis problem

### ISSUE THREAD

**Issue by RNA-Ninja** [jokergoo/ComplexHeatmap#106]
Splitting heatmap is causing row annotation axis problem. Following code produces figure in which an extra line is present bellow the boxplot x-axis (between -4 and 4, very bottom left side) 
```
set.seed(123)
mat = matrix(rnorm(80, 2), 8, 10)
mat = rbind(mat, matrix(rnorm(40, -2), 4, 10))
rownames(mat) = paste0("R", 1:12)
colnames(mat) = paste0("C", 1:10)
df = data.frame(type = c(rep("a", 5), rep("b", 5)))
ht1 = Heatmap(mat, name = "ht1", km = 2)
ha = rowAnnotation(df = df, col = list(type = c("a" = "red", "b" = "blue")),
                   boxplot = row_anno_boxplot(mat, axis = TRUE), 
                   annotation_width = unit(c(1, 5), "cm"))
ha + ht1
```
![rplot2](https://user-images.githubusercontent.com/28019759/27597077-567a66e6-5b2f-11e7-9212-95689fb5fae5.png)

**Comment by jokergoo** [comment]
Hi, this was a bug and now it is fixed. Thanks!

**Comment by RNA-Ninja** [comment]
Thanks for fixing it!
