### ISSUE TITLE
how to show the color of row names in legend? 

### ISSUE THREAD

**Issue by min110** [jokergoo/ComplexHeatmap#108]
Hello, I am using something like:
> Heatmap(mat, name = "foo", row_names_gp = gpar(col = c(rep("red", 4), rep("blue", 8)))) 

but the colors were not reported in legend, did I miss something? 
Thanks!

**Comment by jokergoo** [comment]
`row_names_gp` only controls the graphical parameters for row names. To control the graphical parameters for legend labels, use `heatmap_legend_param` option:

```
Heatmap(m, heatmap_legend_param = list(labels_gp = gpar(col = "red")))
```

**Comment by min110** [comment]
Thank you very much! I was wondering if it was generated automatically.
