### ISSUE TITLE
Mathematical Expression Causes Error

### ISSUE THREAD

**Issue by DarioS** [jokergoo/ComplexHeatmap#113]
It'd be nice to be able to use `expression` to write subscripts. For example, `Heatmap(values, name = expression(log[2]~score)` currently results in an error.

**Comment by jokergoo** [comment]
It is supported in the package ,but not for the `name` argument. In your case, to change the default legend title, you can do as follows:

```{r}
Heatmap(m, heatmap_legend_param = list(title = expression(log[2]~score)))
```
