### ISSUE TITLE
Seamlessly integrate ggplot2 with ComplexHeatmap.

### ISSUE THREAD

**Issue by Yunuuuu** [jokergoo/ComplexHeatmap#1138]
HI, I have created a package to use ggplot2 in COmplexHeatmap. It was almost completed except the legends which is why I'm push this issue. We can do anything use ggplot2 in both heatmap body and heatmap annotations. The package was deposited in https://github.com/Yunuuuu/eheat

As the package is incomplete and certain functions are not exported, you can use `:::` to access those functions for specific examples. The main functions, ggheat and gganno, allow us to utilize all the features of `ComplexHeatmap` while leveraging the flexibility of `ggplot2` to achieve our desired outcomes. It is worth noting that the legends from `ggplot2` can be transferred into `ComplexHeatmap`. However, integrating this functionality seamlessly within the existing functions may require recommendations and suggestions tailored to the specific requirements of your project.
```
# `ggfn` accept a ggplot2 intial data created by `ggplot2::ggplot(data, ggplot2::aes(.data$.column, .data$.row))`.
# the data contain six columns: .slice_row: the slice number of row, .slice_column: the slice number of column, 
# .row and .column: the row and column coordinates, .row_index and .column_index: the row and column index of original matrix 
library(ggplot2)
library(ComplexHeatmap)
x <- sample(1:10, 10L)
m <- rbind(1:10, 11:20)
rownames(m) <- paste0("row ", seq_len(nrow(m)))
colnames(m) <- paste0("col ", seq_len(ncol(m)))
draw(eheat::ggheat(m, ggfn = function(p) {
    p + scale_fill_viridis_c() +
        ggplot2::geom_text(
            aes(label = sprintf("%s * %s", .row_index, .column_index))
        )
}, column_km = 2L))
```
![image](https://github.com/jokergoo/ComplexHeatmap/assets/19575010/330ecc01-122f-43a1-b75f-f9b4022bbba8)

```
draw(eheat::ggheat(t(m), function(p) {
  p + scale_fill_viridis_c() +
    ggplot2::geom_text(
      aes(label = sprintf("%s * %s", .row_index, .column_index))
    )
}, row_km = 2L))
```
![image](https://github.com/jokergoo/ComplexHeatmap/assets/19575010/b27853d2-ead1-4ff4-bab6-8917459bf163)

gganno was not exported yeat, it use the similar interface with `ggheat`, accepted a initial ggplot2 object. the data contain 3columns: `.slice`: the slice number of row, or column,  `x`: the coordinates (always regard coordinates parallely with heatmap as `x`), `.index`: the row  index of original matrix 
```
set.seed(1L)
draw(eheat::ggheat(m,
  top_annotation = HeatmapAnnotation(
    foo = eheat:::gganno(
      function(p) {
        p +
          geom_point(aes(x, ...1))
      },
      matrix = x,
      which = "column", height = unit(5, "cm")
    ), which = "column"
  ),
  bottom_annotation = ComplexHeatmap::HeatmapAnnotation(
    foo = eheat:::gganno(
      function(p) {
        p + aes(y = ...1) +
          geom_text(aes(label = index)) +
          scale_y_reverse()
      },
      matrix = x,
      which = "column", height = unit(5, "cm")
    ),
    which = "column"
  )
))
```
![image](https://github.com/jokergoo/ComplexHeatmap/assets/19575010/dafd962e-7ad3-46be-a16b-00f18dffa6d8)

I discovered that it is possible to extract guide legends from ggplot and incorporate them into ComplexHeatmap. 
```
gp <- ggplot(mtcars, aes(mpg, wt, shape = factor(cyl)))
gp <- gp +
  geom_point(aes(colour = factor(cyl)), size = 4)
gp$scales
gg <- eheat:::guide_from_gg(gp)
draw(eheat::ggheat(m),
  annotation_legend_list = list(gg),
  merge_legends = TRUE
)
```
![image](https://github.com/jokergoo/ComplexHeatmap/assets/19575010/d65c5ba9-316b-415f-8632-e013623fce3f)

The main issue arises when `eheat::ggheat` generates a ggplot object while executing `layer_fun` within the internal of ComplexHeamap `draw` function. Hence, it is not possible to directly extract the legend and reassign it to the `draw` function.  It appears that ComplexHeatmap first prepares the layout, utilizing the `annotation_legend_list` or `heatmap_legend_list` argument, and subsequently executes the `layer_fun`. Therefore, I am interested to know if it is possible to alter the internal process to run `layer_fun` before generating the layout. 

Another request is to allow the AnnotationFunction to incorporate a legend element, considering that `HeatmapAnnotation` only accepts the `AnnotationFunction` object in our interface (though vector for simple Annotation would also be okay, but it would be helpful). If `AnnotationFunction` can add a legend element, we can integrate annotation and legend as a whole and pass them into `draw` function but this would also rely on the first request. 

If above can be settled well, following code will generate all things we want, the heatmap  + annotation + legends.
```
draw(eheat::ggheat(m,
  top_annotation = HeatmapAnnotation(
    foo = eheat:::gganno(
      function(p) {
        p +
          geom_point(aes(x, ...1))
      },
      matrix = x,
      which = "column", height = unit(5, "cm")
    ), which = "column"
  ),
  bottom_annotation = ComplexHeatmap::HeatmapAnnotation(
    foo = eheat:::gganno(
      function(p) {
        print(p$data)
        p + aes(y = ...1) +
          geom_text(aes(label = index)) +
          scale_y_reverse()
      },
      matrix = x,
      which = "column", height = unit(5, "cm")
    ),
    which = "column"
  )
))
```

**Comment by Yunuuuu** [comment]
https://github.com/Yunuuuu/eheat/blob/main/R/ggheat.R#L232

The `env` in the context of the `draw` function refers to an environment object that contains all the data and ggplot object. However, when attempting to use the `heatmap_legend_list` argument with `draw(heat, ..., heatmap_legend_list = eheat:::guide_from_gg(env$p))`, it fails because the internal process evaluates `heatmap_legend_list` before executing `layer_fun`.

**Comment by Yunuuuu** [comment]
I attempted to modify all instances of heatmap_legend_param in the parent frames; however, the desired outcome was not achieved.
```
            has_fn <- function(env, name) {
                exists(name, envir = env, inherits = FALSE) &&
                    methods::.hasSlot(env[[name]], "heatmap_legend_param")
            }
            n <- sys.nframe()
            out <- integer(0L)
            pos <- 1L
            while (pos <= n) {
                if (has_fn(parent.frame(pos), "object")) {
                    out <- c(out, pos)
                }
                pos <- pos + 1L
            }
            for (frame in out) {
                frame_env <- parent.frame(frame)
                oo <- frame_env$object
                oo@heatmap_legend_param$list <- list(guide_from_gg(p))
                frame_env$object <- oo
            }
```

**Comment by Yunuuuu** [comment]
It might be more appropriate to integrate this functionality into the `ComplexHeatmap` package. However, due to my unfamiliarity with the internal structure of ComplexHeatmap, I face challenges in addressing this issue

**Comment by Yunuuuu** [comment]
is it possible to let `layer_fun` to add legend into the `heatmap_legend_list` and the `fun` of `AnnotationFunction` to add legends into `annnotation_legend_list`?

**Comment by Yunuuuu** [comment]
Fix by https://github.com/Yunuuuu/eheat

**Comment by crazyhottommy** [comment]
just FYI https://github.com/jokergoo/ComplexHeatmap/issues/110
