### ISSUE TITLE
row_names_offset, similar to annotation_name_offset

### ISSUE THREAD

**Issue by jenzopr** [jokergoo/ComplexHeatmap#116]
Dear Zuguang,

is it possible to define the row names by an offset, just like it is possible for the annotation name, by setting `annotation_name_offset = unit(0.8, "mm")`? Currently, row names are always 2 mm away from the heatmap.

I'm asking because we use ComplexHeatmap for a figure and as soon as the row names get really small (currently `row_names_gp = gpar(fontsize = 1.5)`), the rownames are horizontally (in relative terms) far away from the row they belong to.

Thanks!
Jens

**Comment by jokergoo** [comment]
You cannot set offsets for annotation names, but you can manually control it by `decorate_annotation()`:

```{r}

m = matrix(rnorm(100), 10)
Heatmap(m, top_annotation = HeatmapAnnotation(foo = runif(10)))
decorate_annotation("foo", {
	grid.text("foo1", unit(1, "npc") + unit(1, "mm"), just = "left")
	grid.text("foo2", unit(1, "npc") + unit(10, "mm"), just = "left")
})
```

**Comment by jenzopr** [comment]
Thanks a lot!
