### ISSUE TITLE
Heatmap with split tiles

### ISSUE THREAD

**Issue by saketkc** [jokergoo/ComplexHeatmap#1178]
Hi @jokergoo, thank you for developing and maintaining the wonderful package!

Is it possible to split the  individual tiles of ComplexHeatmap and have them take different colors? Something on the lines of [this figure](https://blog.originlab.com/wp-content/uploads/2023/10/SplitTileHeatMap1.png)

**Comment by Yunuuuu** [comment]
You can use `layer_fun` or `cell_fun` https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html?q=layer#layer-fun

**Comment by saketkc** [comment]
Wonderful, thanks @jokergoo and @Yunuuuu - exactly what I was looking for!
