### ISSUE TITLE
capture the random colors assigned by Heatmap

### ISSUE THREAD

**Issue by asalhab** [jokergoo/ComplexHeatmap#120]
Hi @jokergoo 
each time I run Heatmap function I get random color assignment for the annotation I provide (in case I don't set the colors manually). I need to use these colors to annotate a different plot (boxplots) so that samples in both have consistent colors.

Best,
Abdul

**Comment by jokergoo** [comment]
You can assign colors in the first place instead of using random colors.

```{r}
anno_col = c("a" = "red", "b" = "blue")
ha = HeatmapAnnotation(foo = sample(c("a", "b"), 10, replace = TRUE), col = list(foo = anno_col))
Heatmap(mat, top_annotation = ha)
```

**Comment by asalhab** [comment]
Hi @jokergoo I run Heatmap in a pipeline which has a sample_sheet as input. the header looks like (sample_ID, annot_1, annot_2, annot_3). which mean each sample_sheet could have different annotations. That's why I don't provide colors in advance. anyway I got what I was looking for 
```
assuming hc is a Heatmap object
hc@top_annotation@anno_list$annot_1@color_mapping@colors
```

Thanks
Abdul

**Comment by jokergoo** [comment]
Yes, it is coded very deep in the object.

**Comment by jokergoo** [comment]
Yes, it is coded very deep in the object.
