### ISSUE TITLE
legends interfere with top annotation names

### ISSUE THREAD

**Issue by RNA-Ninja** [jokergoo/ComplexHeatmap#121]
I am trying to create heatmap with several legends and top annotation names. The legends are not starting from the heatmap and crossing the top annotation names, as shown in this image. **There is clearly some space at the bottom of the legends** so if somehow I can shift the legend downwards and/or **make sure it starts where heatmap starts** that will solve the problem. How can I do this?

![rplot](https://user-images.githubusercontent.com/28019759/30762860-ae59b0da-9fb1-11e7-9e89-4557b3a44392.png)

Here is the code to reproduce,
```
library(ComplexHeatmap)
library(circlize)
df <- data.frame(matrix(rep(1:10, 5), nrow = 10))
df <- apply(df, 2, sample)
colnames(df) <- paste0("a long col name ", 1:ncol(df))
colx = sapply(colnames(df), function(x) {colorRamp2(c(0, 10), c("white", "red"))}, simplify = F)
ha = HeatmapAnnotation(df = df, col = colx, show_legend = FALSE )
anno_legend_list = lapply(ha@anno_list,
                          function(anno) color_mapping_legend(anno@color_mapping, plot = FALSE))
mat = matrix(rnorm(80, 2), 8, 10)
ht = Heatmap(mat, name = "ht", top_annotation = ha, show_heatmap_legend = FALSE)
heatmap_legend = color_mapping_legend(ht@matrix_color_mapping, plot = FALSE)

draw(ht, heatmap_legend_list = c(list(heatmap_legend), anno_legend_list ))
for(an in colnames(df))
{
  decorate_annotation(an, {txt = an
  grid.text(txt, unit(1, "npc") + unit(2, "mm"), 0.5,
            default.units = "npc", just = "left")} )
}

```

**Comment by jokergoo** [comment]
Unfortunately there is no solution for this overlapping, but you can put annotation names on the left of annotations.

**Comment by jokergoo** [comment]
add options to adjust the position of legends, moved to #187
