### ISSUE TITLE
How to control the unit size of oncoPrint?

### ISSUE THREAD

**Issue by YiweiNiu** [jokergoo/ComplexHeatmap#123]
Hi,

I'm using the oncoPrint function. It's cool and beautiful.
I have two gene lists. One contains 38 genes, and another contains 6 genes. The scale of two graphs was different. How can I control the size of units to make two graphs look similar? I want to put them together (not the "split"). 
The first one:
![image](https://user-images.githubusercontent.com/25263399/30806256-a0fa485a-a227-11e7-86e1-85f93863adf4.png)
The second one:
![image](https://user-images.githubusercontent.com/25263399/30806265-aa11b0fe-a227-11e7-9c97-23d16c1a3ffd.png)

It seems I can convert width and height to absolute values, but I don't know how to do it. Could you please give me some guidance? Thanks!

**Comment by jokergoo** [comment]
This is almost impossible because the height of the heatmap body itself is automatically adjusted to the total height of the plot.

**Comment by YiweiNiu** [comment]
Thank you for your reply! Yes, I added empty rows to make the numbers equal. It's not "so elegant", but it works :D
