### ISSUE TITLE
Clustering within subgroups of columns

### ISSUE THREAD

**Issue by CodeInTheSkies** [jokergoo/ComplexHeatmap#126]
Hi All,

I first posted this message as a comment to another message on the same topic, here:

https://github.com/jokergoo/ComplexHeatmap/issues/30

but that issue was closed.  So, I was not sure if my question got any attention.  

I have the same situation described by that poster, i.e.,

    "A more detailed question is:
    when I do a supervised-clustering, I want to first split the columns (samples) into say 3 pre-defined subgroups first, and then do clustering within each subgroup for columns and do a k-means for all rows. Is it possible?"

I went through the answers there, but I didn't clearly understand how to achieve clustering within the subgroups of columns, while having an overall clustering for the rows. Could anybody please explain?

I don't understand how the first answer in the above post fully achieves this. Specifically, the object "km" is computed, but then not used in the code after that.

Appreciate any responses!

Thanks.

**Comment by jokergoo** [comment]
Sorry for the late reply. I cannot get any notification from GitHub for unknown reasons.

Let's assume following matrix and a subgroup vector

```
mat = matrix(rnorm(100), 10)
subgroup = sample(c("a", "b"), 10, replace = TRUE)
```
We want to calculate column orders that only columns in subgroup a/subgroup b are clustered.

```
hc1 = hclust(dist(t(mat[, 1:5])))
od1 = hc1$order
hc2 = hclust(dist(t(mat[, 1:6])))
od2 = hc2$order
od = c(which(subgroup == "a")[od1], which(subgroup == "b")[od2]))
```

**Comment by CodeInTheSkies** [comment]
Sorry, couldn't get a chance to play around with this until now.  Thanks for the code chunk!  I think I understand what you mean, except that, I guess you meant `mat[, 6:10]`  in the line
`hc2 = hclust(dist(t(mat[, 1:6])))`,  correct?    That line should actually read, 
`hc2 = hclust(dist(t(mat[, 6:10])))`,  correct?

Thanks again!

**Comment by jokergoo** [comment]
Yes, you are right. That was a mistake.

**Comment by CodeInTheSkies** [comment]
Thanks!  I have closed the issue now.

**Comment by YingjieLiScience** [comment]
Hi @jokergoo I do not if there already have a solution to my question, but I did refer to a few questions posted and did not find one. Similar to the post here, I am thinking about how to do clustering within splits (subgroups) of rows. 

here is part of my code within `Heatmap()`, and I split the rows based on 'Region'
` row_split = df_ht$Region, 
cluster_row_slices = T,
        cluster_rows    = T, 
        row_order = order(df_ht$Region), ...`

however, I found a mismatch between the region name and the region split. For example, the two region names should be exchanged in the attached screenshot. If I set `cluster_rows    = F`, they match well. 
<img width="309" alt="2345截图20200702092120" src="https://user-images.githubusercontent.com/40079217/86364653-7717c300-bc46-11ea-99bd-3b857fa5c07a.png">

**Comment by jokergoo** [comment]
Please also attach the code and the data.

**Comment by YingjieLiScience** [comment]
Here is a simplified code and data. Thanks!

`load("data_ComplexHeatmap.RData")
ha_block <- rowAnnotation(
  Region = anno_block(
    gp = gpar(fill = col_regions, 
              col = NA, ## remove the border color
              fontsize = font_size), 
    width = unit(width_bar, "mm"),
    show_name = T, 
    labels = ls_regions,
    labels_gp = gpar(col = "black", fontsize = font_size)),
  annotation_name_gp = gpar(fontsize = font_size),
  width = unit(width_bar, "mm"))

Heatmap(matrix = mat1, 
        name = "Log(Number)",                   ## legend name
        col = (brewer.pal(n=9, name="YlGnBu")), ## heatmap color
        row_title = NULL,
        column_title = NULL,
        # bottom_annotation = ha_sdg,
        # top_annotation    = ha_boxplot,
        right_annotation  = ha_block,
        cluster_columns = T, 
        
        row_split = df_ht$Region, cluster_row_slices = T,
        cluster_rows    = T, ## F
        row_order = order(df_ht$Region),
        
        row_gap = unit(0.5, "mm"),
        column_dend_reorder = T,
        show_row_dend    = F, 
        show_column_dend = F, 
        show_row_names = F,
        show_column_names = T,
        row_names_gp    = gpar(fontsize = font_size),
        column_names_gp = gpar(fontsize = font_size), 
        raster_quality = 20,
        show_heatmap_legend = T)`



[data_ComplexHeatmap.zip](https://github.com/jokergoo/ComplexHeatmap/files/4864649/data_ComplexHeatmap.zip)
