### ISSUE TITLE
are values scaled ?

### ISSUE THREAD

**Issue by ebioman** [jokergoo/ComplexHeatmap#127]
Hello
A naive question, I am doing a simple heatmap and see from the legend that the color-code ranges from -4 to 6. If I check though the maximum and minimal values of the matrix I get -10 to 14.
So are the values being scaled by row or column by default ?

To my confusion, if I add manually a color this is not the case and I do get a legend which scales from the minimum to maximum value

**Comment by jokergoo** [comment]
Sorry for the late reply. I cannot get any notification from GitHub for unknown reasons.

The color range on the legend is not the range in your matrix.The range on legend is automatically calculated which tends not to be affected by outliers and to cover as much values as possible.

You can check `pretty()` and `grid.pretty()` functions for more information.

**Comment by ebioman** [comment]
Thank you very much, that fits my observations
