### ISSUE TITLE
cannot install ComplexHeatmap (Elementary OS)

### ISSUE THREAD

**Issue by nailufra** [jokergoo/ComplexHeatmap#128]
Hi all,
I'm running R Studio on Linux Elementary OS (Loki 0.4) and so far I've never had any problems installing biocLite packages (e.g. DESeq2). 

However, when I tried to install and load "ComplexHeatmap" by using:

source("https://bioconductor.org/biocLite.R")

> Bioconductor version 3.2 (BiocInstaller 1.20.3), ?biocLite for help
> A new version of Bioconductor is available after installing the most recent version of R; see
> http://bioconductor.org/install

biocLite("ComplexHeatmap")

library(ComplexHeatmap)

I got the following error:

> The downloaded source packages are in
> ‘/tmp/Rtmp2sghIT/downloaded_packages’
> Warning messages:
>   1: In install.packages(pkgs = doing, lib = lib, ...) :
>   installation of package ‘flexmix’ had non-zero exit status
> 2: In install.packages(pkgs = doing, lib = lib, ...) :
>   installation of package ‘fpc’ had non-zero exit status
> 3: In install.packages(pkgs = doing, lib = lib, ...) :
>   installation of package ‘dendextend’ had non-zero exit status
> 4: In install.packages(pkgs = doing, lib = lib, ...) :
>   installation of package ‘ComplexHeatmap’ had non-zero exit status

Anyone faced this problem before?

**Comment by jokergoo** [comment]
Do you have more information for this "non-zero exit" error?

Maybe you missed some C/C++ libraries for upstream packages.

**Comment by nailufra** [comment]
This is the only error appearing. 

I already searched for the "had non-zero exit status" and installed the recommended packages via terminal: curl, libssl-dev, libcurl, xml2

still the same problem after this installation step.

**Comment by jokergoo** [comment]
This is something I have never seen. Might it be there is not space on the disk? Or can you try:

```
devtools::install_github("jokergoo/ComplexHeatmap")
```

**Comment by nailufra** [comment]
It worked!

Thanks a lot!
