### ISSUE TITLE
Parallel hclust using amap

### ISSUE THREAD

**Issue by schelhorn** [jokergoo/ComplexHeatmap#13]
It seems as if the [amap](http://www.inside-r.org/packages/cran/amap/docs/hcluster) R package allows hclust computation using multiple compute cores and additional distance measures and link functions. Otherwise it is a drop-in replacement for hclust, I believe. I found the speed advantage worthwhile with large data sets, so maybe you would want to use it in ComplexHeatmap.

**Comment by jokergoo** [comment]
So sorry that I almost forgot to reply you. The amap package looks great and I think I will integrate it after I fully test it. Thanks for telling me this!

**Comment by jokergoo** [comment]
I am trying amap package these days. I found actually `hcluster()` does not improve the performance too much. And it seems it is even slower than `hclust(dist(..))`.

```{r}
> mat = matrix(rnorm(10000), nrow = 1000)
> microbenchmark(amap::hcluster(mat))
Unit: milliseconds
                expr      min       lq     mean   median       uq     max neval
 amap::hcluster(mat) 286.6541 429.1059 443.3019 462.3735 464.4711 470.595   100
> microbenchmark(hclust(dist(mat)))
Unit: milliseconds
              expr      min       lq     mean   median       uq      max neval
 hclust(dist(mat)) 135.1492 136.8577 142.8476 137.3423 139.3044 601.5945   100
> microbenchmark(amap::hcluster(mat, nbproc = 4))
Unit: milliseconds
                            expr      min       lq     mean   median       uq
 amap::hcluster(mat, nbproc = 4) 218.4079 298.1017 294.9429 299.4211 301.2363
      max neval
 304.9114   100
```
