### ISSUE TITLE
annotation_legend_param should allow you to order legend by row or column

### ISSUE THREAD

**Issue by kmace** [jokergoo/ComplexHeatmap#131]
when breaking a legend up into ncol, it would be nice to list the legend values by column, or row. currently it only does row. see the example below, I'd like for similar colors to be below each other.

<img width="247" alt="screen shot 2017-10-31 at 11 40 28 pm" src="https://user-images.githubusercontent.com/18296227/32263011-0ae5472c-be95-11e7-814d-2383a3d96253.png">

**Comment by kmace** [comment]
the `legend_direction` argument would be perfect for this. It has a distinct meaning in the continuous and discrete cases then!

**Comment by kmace** [comment]
I have implemented a fix to this. please review my pull request and let me know if you'd like any changes.

**Comment by jokergoo** [comment]
example code:

```{r}
mat = matrix(letters[1:20], nr = 4)
col = circlize::rand_color(20)
Heatmap(mat, name = "legends_by_col", col = col, heatmap_legend_param = list(nrow = 3)) + 
Heatmap(mat, name = "legends_by_row", col = col, heatmap_legend_param = list(nrow = 3, by_row = TRUE))
```

<img width="578" alt="screen shot 2017-11-09 at 23 06 27" src="https://user-images.githubusercontent.com/449218/32632092-92fa9022-c5a2-11e7-8c3a-36d139594a64.png">
