### ISSUE TITLE
Oncoprint=change scales barplot

### ISSUE THREAD

**Issue by nuriamt** [jokergoo/ComplexHeatmap#133]
Hi
with the oncoprint function manually adjust the scale of top and side barplots
Thanks
N

**Comment by jokergoo** [comment]
No currently you cannot change the scales on barplots. But why do you want to change it? Is there any specific scenario for doing this?

**Comment by nuriamt** [comment]
I wanted to split my oncoprint panel per patient group, want to emphasize the differences between the two groups in terms of number of mutations per patient and number of mutated patients per gene. 

I managed to do it by setting show_row_barplot = FALSE and defining new column barplots and row barplots, assigned to top_annotation and rowAnnotation() separately (http://zuguang.de/blog/html/Customize_barplots_for_the_oncoPrint.html)
