### ISSUE TITLE
Oncoprint - "closure' is not subsettable

### ISSUE THREAD

**Issue by anabbi** [jokergoo/ComplexHeatmap#135]
I am getting this error everytime I try to draw an oncoprint:

Error in col[intersect(names(col), all_type)] : 
  object of type 'closure' is not subsettable

Here is an example that does not work on my RStudio:

exlist = list(snv = matrix(c(1, 0, 1, 1, 1, 0, 0, 1, 1), nrow = 3),
                indel = matrix(c(1, 0, 0, 0, 1, 0, 1, 0, 0), nrow = 3))
rownames(exlist$snv) = rownames(exlist$indel) = c("g1", "g2", "g3")
colnames(exlist$snv) = colnames(exlist$indel) = c("s1", "s2", "s3")

oncoPrint(exlist,
          alter_fun = list(
            snv = function(x, y, w, h) grid.rect(x, y, w*0.9, h*0.9, gp = gpar(fill = col["SNV"], col = NA)),
            indel = function(x, y, w, h) grid.rect(x, y, w*0.9, h*0.4, gp = gpar(fill = col["indel"], col = NA))
          ), col = col)

Error in col[intersect(names(col), all_type)] : 
  object of type 'closure' is not subsettable

Thanks for your help

**Comment by jokergoo** [comment]
What is the value of `col`? It should be a named vector.

**Comment by anabbi** [comment]
Am I not defining it as matrix name here:
exlist = list(snv = matrix(c(1, 0, 1, 1, 1, 0, 0, 1, 1), nrow = 3), indel = matrix(c(1, 0, 0, 0, 1, 0, 1, 0, 0), nrow = 3))

I fixed the SNV to snv as it appears in the list but no success. Sorry for asking a simple question.

**Comment by jokergoo** [comment]
I think it is fine whether the first agument is a matrix or a list of binary matrices. I think the problem here is you need to define `col` before you use `oncoPrint()`, something like:

```
col = c(snv = "red", indel = "blue")
```

**Comment by anabbi** [comment]
Thanks for your help. Resolved!
