### ISSUE TITLE
Extracting kmeans clusters or dendrogram from heatmap

### ISSUE THREAD

**Issue by kmace** [jokergoo/ComplexHeatmap#136]
Once a heatmap is created, have the ability to pull out the cluster members from the Heatmap object.

**Comment by jokergoo** [comment]
```
ht = Heatmap(..., km = 2)
ht = draw(ht)
row_order(ht)
```

It will give you a list of two where each one corresponds to row index in one cluster.

**Comment by guidohooiveld** [comment]
I faced the same challenge. Triggered by [this post at BioStars](https://www.biostars.org/p/264268/#264303) I came up with these line of codes; maybe they are useful for others as well.

```
> library(ComplexHeatmap)
> library(circlize)
> 
> set.seed(123)  #For reproduciblity
> 
> #Generate some data
> mat = matrix(rnorm(80, 2), 8, 10)
> mat = rbind(mat, matrix(rnorm(40, -2), 4, 10))
> rownames(mat) = letters[1:12]
> colnames(mat) = letters[1:10]
>
> 
> HM <- Heatmap(mat, km=3)  #Make a heatmap, and have 3 clusters
> draw(HM)  #Show the heatmap
> r.dend <- row_dend(HM)  #Extract row dendrogram
> rcl.list <- row_order(HM)  #Extract clusters (output is a list)
> 
> lapply(row_order(HM), function(x) length(x))#check/confirm size clusters
[[1]]
[1] 2

[[2]]
[1] 8

[[3]]
[1] 2

> 
> #loop to extract genes for each cluster.
> for (i in 1:length(rcl.list)){
+ if (i == 1) {
+ clu <- t(t(row.names(mat[row_order(HM)[[i]],])))
+ out <- cbind(clu, paste("cluster", i, sep=""))
+ colnames(out) <- c("GeneID", "Cluster")
+ } else {
+ clu <- t(t(row.names(mat[row_order(HM)[[i]],])))
+ clu <- cbind(clu, paste("cluster", i, sep=""))
+ out <- rbind(out, clu)
+ }
+ }
> 
> 
> #check
> out
      GeneID Cluster   
 [1,] "e"    "cluster1"
 [2,] "b"    "cluster1"
 [3,] "d"    "cluster1"
 [4,] "a"    "cluster1"
 [5,] "g"    "cluster1"
 [6,] "h"    "cluster1"
 [7,] "j"    "cluster2"
 [8,] "i"    "cluster2"
 [9,] "k"    "cluster2"
[10,] "l"    "cluster2"
[11,] "k"    "cluster3"
[12,] "l"    "cluster3"
> 
>
> #export
> write.table(out, file= "gene_clusters.txt", sep="\t", quote=F, row.names=FALSE)
>
```

**Comment by qalid7** [comment]
@guidohooiveld you're a star!

**Comment by qicaibiology** [comment]
> row_order

Thank you so much for providing this code. It is what I want to learn. I can get the Heatmap step done so far. But when I run the last step I got an error:  

> > for (i in 1:length(row_order(HM))){
> +   if (i == 1) {
> +   clu <- t(t(row.names(mydat_2[row_order(HM)[[i]],])))
> +   out1 <- cbind(clu, paste("cluster", i, sep=""))
> +   colnames(out1) <- c("coordinates", "Cluster")
> +   } else {
> +   clu <- t(t(row.names(mydat_2[row_order(HM)[[i]],])))
> +   clu <- cbind(clu, paste("cluster", i, sep=""))
> +   out1 <- rbind(out1, clu)
> +   }
> + }
> Error in t.default(row.names(mydat_2[row_order(HM)[[i]], ])) : 
>   argument is not a matrix

Why the mydat2 [, ] is not a matrix how can I make it work?

**Comment by jokergoo** [comment]
The error comes from this line:

```r
clu <- t(t(row.names(mydat_2[row_order(HM)[[i]],])))
```

Why do you transpose row names? Maybe you should remove `row.names()`.

**Comment by qicaibiology** [comment]
> The error comes from this line:
> 
> ```r
> clu <- t(t(row.names(mydat_2[row_order(HM)[[i]],])))
> ```
> 
> Why do you transpose row names? Maybe you should remove `row.names()`.

if I remove row.names like:

> clu <- t(t(mydat_2[row_order(HM)[[i]],]))

I will get the first columns which is the reads instead of the genes;

> out1

>        coordinates    Cluster      
> E11    "0.593914"     "cluster1"   
> E14    "0.577216"     "cluster1"   
> E18    "0.706816"     "cluster1"   
> Adult  "0.540533"     "cluster1"   
> diffIR "0.112902"     "cluster1"

**Comment by qicaibiology** [comment]
> The error comes from this line:
> 
> ```r
> clu <- t(t(row.names(mydat_2[row_order(HM)[[i]],])))
> ```
> 
> Why do you transpose row names? Maybe you should remove `row.names()`.

E11, E14, E18, Adult, diffIR are the column names by the way. So it is not what I want to acquire

**Comment by hnthirim** [comment]
Hi, I am also getting the same error mentioned above. 

"Error in t.default(row.names(hclust_matrix[row_order(HM)[[i]], ])) : 
  argument is not a matrix" 

How did you solve this issue?

Thanks!

**Comment by guidohooiveld** [comment]
What does `class(hclust_matrix)` return? Is it a matrix?

**Comment by qicaibiology** [comment]
> Hi, I am also getting the same error mentioned above.
> 
> "Error in t.default(row.names(hclust_matrix[row_order(HM)[[i]], ])) :
> argument is not a matrix"
> 
> How did you solve this issue?
> 
> Thanks!

I found that even it works through. When you write out "out" you will find some genes in 2 clusters. It is very weird. I asked friends and they suggested me to assign  "row_order(ht)" to a variable because it will not produce consistent number each time. So I followed the advice and use the following command and it worked:
```
gene_cluster <- row_order(ht)

clu_df <- lapply(names(gene_cluster), function(i){
  out <- data.frame(coordinates = rownames(mydata3[gene_cluster[[i]],]),
                    Cluster = paste0("cluster", i), stringsAsFactors = FALSE)
  return(out)
}) %>%
  do.call(rbind, .)
```

Hope it helps

**Comment by guidohooiveld** [comment]
@qicaibiology:
Two remarks/questions:
- what did `class(mydata3)` return? Was it a matrix? I think this is important because the function `Heatmap` expects a matrix as input. See `?Heatmap`.
- in my opinion it is impossible to have genes in 2 (or more) clusters, except (of course) when the names of the input gene matrix (in your case `mydata3`) are not unique. Therefore: output from `sum(duplicated(rownames(mydata3)))` should be zero.

Your code to collapse the genes to the clusters is indeed more efficient than mine. For others: note that the pipe function `%>%` from the library `magrittr` is required!

My updated code incorporating your suggestions:

```
> library(ComplexHeatmap)
> library(circlize)
>  
> set.seed(123)  #For reproduciblity
>  
> # Generate some data
> mat = matrix(rnorm(80, 2), 8, 10)
> mat = rbind(mat, matrix(rnorm(40, -2), 4, 10))
> rownames(mat) = letters[1:12]
> colnames(mat) = letters[1:10]
> 
> # Check 'class' of input; this should be a matrix because
> # this is what the function 'Heatmap' below expects. See '?Heatmap'.
> class(mat)
[1] "matrix" "array" 
> 
> # Check whether names genes (=rows) are unique.
> # output should be 0.
> sum(duplicated(rownames(mat)))
[1] 0
> 
> 
> HM <- Heatmap(mat, km=3)  #Draw a heatmap with 3 clusters. Value of 'km' is key!
> HM <- draw(HM)  #Show the heatmap
> 
> r.dend <- row_dend(HM)  #If needed, extract row dendrogram
> rcl.list <- row_order(HM)  #Extract clusters (output is a list)
>  
> lapply(rcl.list, function(x) length(x))  #check/confirm size gene clusters
$`1`
[1] 4

$`2`
[1] 6

$`3`
[1] 2

> 
> 
> library(magrittr) # needed to load the pipe function '%>%'
> 
> clu_df <- lapply(names(rcl.list), function(i){
+   out <- data.frame(GeneID = rownames(mat[rcl.list[[i]],]),
+                     Cluster = paste0("cluster", i),
+                     stringsAsFactors = FALSE)
+   return(out)
+ }) %>%  #pipe (forward) the output 'out' to the function rbind to create 'clu_df'
+   do.call(rbind, .)
> 
> #check
> clu_df
   GeneID  Cluster
1       j cluster1
2       i cluster1
3       k cluster1
4       l cluster1
5       d cluster2
6       e cluster2
7       b cluster2
8       a cluster2
9       g cluster2
10      h cluster2
11      c cluster3
12      f cluster3
> 
> #export
> write.table(clu_df, file= "gene_clusters2.txt", sep="\t", quote=F, row.names=FALSE)
> 

```

**Comment by hermidalc** [comment]
I have a heatmap with two clusters, but when I do `row_order(ht)` I do not get a list but instead a vector with indices that are the same length as the number of rows in my input data matrix. Why am I not getting a list with two elements?

**Comment by hermidalc** [comment]
Nevermind I see you must set `row_km = n` or equivalent other settings in order to get a list with n elements

**Comment by hermidalc** [comment]
Thank you @jokergoo, once I set `row_km` it works as expected, and yes I agree with you that it should return a vector when it's not set

**Comment by tiagobrc** [comment]
For people that want to copy the code without output characters:

```R

 library(ComplexHeatmap)
 library(circlize)
  
 set.seed(123)  #For reproduciblity
  
 # Generate some data
 mat = matrix(rnorm(80, 2), 8, 10)
 mat = rbind(mat, matrix(rnorm(40, -2), 4, 10))
 rownames(mat) = letters[1:12]
 colnames(mat) = letters[1:10]
 
 # Check 'class' of input; this should be a matrix because
 # this is what the function 'Heatmap' below expects. See '?Heatmap'.
 class(mat)
 
 # Check whether names genes (=rows) are unique.
 # output should be 0.
 sum(duplicated(rownames(mat)))
 
 
 HM <- Heatmap(mat, km=3)  #Draw a heatmap with 3 clusters. Value of 'km' is key!
 HM <- draw(HM)  #Show the heatmap
 
 r.dend <- row_dend(HM)  #If needed, extract row dendrogram
 rcl.list <- row_order(HM)  #Extract clusters (output is a list)
  
 lapply(rcl.list, function(x) length(x))  #check/confirm size gene clusters

 library(magrittr) # needed to load the pipe function '%%'
 
 clu_df <- lapply(names(rcl.list), function(i){
   out <- data.frame(GeneID = rownames(mat[rcl.list[[i]],]),
                     Cluster = paste0("cluster", i),
                     stringsAsFactors = FALSE)
   return(out)
 }) %>%  #pipe (forward) the output 'out' to the function rbind to create 'clu_df'
   do.call(rbind, .)
 
 #export
 write.table(clu_df, file= "gene_clusters2.txt", sep="\t", quote=F, row.names=FALSE)
 
```
