### ISSUE TITLE
Split heatmap when using hclust results?

### ISSUE THREAD

**Issue by guidohooiveld** [jokergoo/ComplexHeatmap#137]
Hi, is it somehow possible to split a heatmap based on the clustering results that were generated 'outside' ComplexHeatmap?
I would like to perform hierarchical clustering using the library hclust, and then use these results to generate a nice heatmap, including 'splits'. I know how provide the clustering results as such, but I don't know how to indicate the splits as e.g. determined by cutree(). See pictures below. Any pointers would be appreciated.

```
#load libraries.
library(ComplexHeatmap)
library(circlize)
set.seed(123)  #For reproduciblity
 
# Generate some data
mat <- replicate(10, rnorm(100, sd=1)) 
mat = rbind(mat,  replicate(10, rnorm(25, mean=4)))
rownames(mat) = paste("gene", 1:dim(mat)[1])
colnames(mat) = letters[1:10]

# Perform kmeans clustering using ComplexHeatmap; define 5 clusters
HM <- Heatmap(mat, km = 5)
HM <- draw(HM)	

###################
# hierarchical clustering of genes (rows) and samples (columns)
# 'outside' ComplexHeatmap

hr <- hclust(dist(mat, method = "euclidean"), method="complete") 
hc <- hclust(dist(t(mat), method = "euclidean"), method="complete")

# define 5 gene clusters using cutree
mycl.r <- cutree(hr, k=5)

# using cutree results as split doesn't work...
HM <- Heatmap(mat, cluster_rows=hr, cluster_columns=hc, split=mycl.r)

HM <- Heatmap(mat, cluster_rows=hr, cluster_columns=hc)
HM <- draw(HM)	
```

Results clustering using ComplexHeatmap directly:
![clustering_by_complexheatmap](https://user-images.githubusercontent.com/22979991/33666445-4cf6329a-da9a-11e7-8980-051437f56c08.png)

Results clustering using hclust results, splitting NOT possible:
![clustering_using hclust_results](https://user-images.githubusercontent.com/22979991/33666477-5f5ebd26-da9a-11e7-9a25-00120df8bf99.png)

**Comment by jokergoo** [comment]
You may try to set `split = 4`. When the value of `split` is a number, `cutree()` is applied internally.

**Comment by guidohooiveld** [comment]
Hi, thanks for your feedback. However, I got things working through another way. By doing so I noticed that when performing kmeans clustering from within ComplexHeatmap gives different results than when doing it outside using hclust, even when using the same settngs. I don't understand why this is happening.... Would you mind explaining? So why heatmap1 is different than heatmap2 and heatmap3, while the same input is (should) be provided. See below for pictures/code. 

```
#load relevant libraries.
library(ComplexHeatmap)
library(circlize)
library(RColorBrewer)
library(pheatmap)

set.seed(123)  #For reproduciblity
 
# Generate some data
mat <- replicate(10, rnorm(100, sd=1)) 
mat = rbind(mat,  replicate(10, rnorm(25, mean=4)))
rownames(mat) = paste("gene", 1:dim(mat)[1])
colnames(mat) = letters[1:10]

# set color scale
col = colorRampPalette(rev(brewer.pal(n = 7, name ="RdYlBu")))(100)



# Perform kmeans clustering within ComplexHeatmap; define 5 clusters
HM <-	Heatmap(mat, km = 5,
	show_row_names = FALSE, col=col,
	column_title = "Clusters made within ComplexHeatmap clusters")

png(file="ComplexHeatmap_made.png")
HM <- draw(HM)	
dev.off()



# Perform kmeans clustering 'outside' ComplexHeatmap using hclust

hr <- hclust(dist(mat, method = "euclidean"), method="complete") 
hc <- hclust(dist(t(mat), method = "euclidean"), method="complete")

# define 5 row (gene) clusters using cutree outside ComplexHeatmap
mycl.r <- cutree(hr, k=5)

# using cutree results as split doesn't work...
HM <- Heatmap(mat, split= paste0("Cluster", mycl.r),
	show_row_names = FALSE, col=col,
	column_title = "Clusters made by hclust-cutree provided to ComplexHeatmap",
	row_title_gp=gpar(cex=0.8))


png(file="ComplexHeatmap_provided.png")
HM <- draw(HM)	
dev.off()




### Double-check: use pheatmap to generate the clustered heatmap.
# use the same 5 clusters defined before
annotation_row = data.frame(Cluster = factor(mycl.r))

png(file="pheatmap.png")
pheatmap(mat, scale = "none", show_rownames=FALSE, col=col,
	cluster_rows=hr, cluster_cols=hc, cutree_rows=5,
	annotation_row=annotation_row, main = "Clustered heatmap made by pheatmap")
dev.off()

```
**Heatmap with 5 clusters generated WITHIN ComplexHeatmap**

![complexheatmap_made](https://user-images.githubusercontent.com/22979991/33758296-f39cc60e-dbfd-11e7-9c2b-5edae95a8ab7.png)

**Heatmap with 5 clusters generated OUTSIDE ComplexHeatmap with hclust**

![complexheatmap_provided](https://user-images.githubusercontent.com/22979991/33758307-016130a4-dbfe-11e7-9eb3-ce4a4c6ca083.png)


**Heatmap with 5 clusters generated OUTSIDE ComplexHeatmap with hclust, but visualized using pheatmap**

![pheatmap](https://user-images.githubusercontent.com/22979991/33758322-153c8a56-dbfe-11e7-90e4-fab71b32da35.png)

**Comment by jokergoo** [comment]
Because the classification methods by `hclust()` and `kmeans()` themselves are different and they might give different results.  And on the other hand, `kmeans()` need random intializing center points and they are different every time you run `kmeans()` or functions that use `kmeans()` internally, unless you set the same random seed for them:

And for ComplexHeatmap, the dendrograms are reordered by the row means of the matrix while pheatmap does not (you can see the documentation of `help("reorder.dendrogram")`). Reordering sometimes can improve the visualization to move similar rows closer (the pattern is not that obvious in your data).

**Comment by guidohooiveld** [comment]
Ah, I got it.... Thanks! So it basically boils down to the fact that kmeans is not the same as hierarchical clustering, even if the same distance matrix is used (euclidean) and the number of clusters can be set by the parameter `km`). Also got to know about the reordering within clusters by row means.

**Comment by guidohooiveld** [comment]
Finally, just to close this thread: I now also appreciate the [1st comment](https://github.com/jokergoo/ComplexHeatmap/issues/137#issuecomment-349967608) you made in this thread: by using `split=5` I indeed essentially obtained the same Heatmap as when providing the output of hclust (=hr). Split is thus the value of the cutree argument, and when Heatmap is called with default settings    `clustering_distance_rows = "euclidean"` and `clustering_method_rows = "complete"`, which are the same as the input I provided for` hclust()`.

**Comment by jokergoo** [comment]
Yes, you are right
