### ISSUE TITLE
oncoprint only for the top altered genes

### ISSUE THREAD

**Issue by crazyhottommy** [jokergoo/ComplexHeatmap#140]
Hi Zuguang,

Is there a way to specify the number of genes plotted in the oncoprint function?
I have a list of matrix,  I want to plot the top most altered genes not all genes.

Thanks,
Tommy

**Comment by jokergoo** [comment]
Yes, you can directly subset the input matrix, something like:

```{r}
mat2 = mat[subset, ]
oncoPrint(mat2, ...)
```

But you need to know which are the most top altered genes first (which I think should be easy).

**Comment by crazyhottommy** [comment]
yes, that's what I think I can do. 

Thanks.
```r
altered_nums<- Reduce( "+" , lapply(mat_list, rowSums))

NUMBER_GENES<- 15

slice_indx<- order(altered_nums, decreasing = TRUE)[1:NUMBER_GENES]

mat_list_sub<-  lapply(mat_list, function(x) x[slice_indx,])

```

**Comment by Yunuuuu** [comment]
Hi,  Sorry to reopen this,  I came across a condition like this.

**Comment by Yunuuuu** [comment]
Hi, Sorry to disturb in this issue, the problem I met is something like this, If we want to create oncoprint with the top 20 altered genes but let the top bar annotation remain consider all genes in our data.

I think this is also common for displaying the schematic genomics? Is there any ways to do these in ComplexHeatmap?

**Comment by jokergoo** [comment]
The top annotation is just a simple barplot annotation, you can replace it with any other annotations.

```r
mat # the complete matrix
mat_top # the matrix that contains top 20 genes

tb # the frequency of mutations from mat

oncoPrint(mat_top, top_annotation = HeatmapAnnotation(barplot = anno_barplot(tb)))
```

**Comment by Yunuuuu** [comment]
Thanks for your reply, I have tried it, but it cannot make a stack barplot with different filled colors like anno_oncoprint_barplot do, but anno_barplot is sometimes enough.

Thanks you for your development of such great R package.

Thanks

**Comment by jokergoo** [comment]
Have checked the ComplexHeatmap book https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html#barplot_annotation?

You just need to assign a vector of colors to `gpar(fill = ...)` in `anno_barplot()`.

**Comment by Yunuuuu** [comment]
Oh, I read it,  I just mistook anno_barplot would automatically scale the matrix values to be unity. Thanks for your help!!

**Comment by jackkuipers** [comment]
Thanks for the great package. I don't quite get how to do this in practice - say I want to make a plot like at the end of chapter 7 with the TCGA data, where the annotations are coloured by the different alteration types, and we want to display the top annotation on all genes but the oncoprint only for a subset.

Can I somehow use the anno_oncoprint_barplot function, rather than anno_barplot, for example by extracting the top annotation from a different oncoprint?
