### ISSUE TITLE
top_annotation_height is not respected when joining two heatmap

### ISSUE THREAD

**Issue by RNA-Ninja** [jokergoo/ComplexHeatmap#141]
I am combining 2 heatmaps which have different height of top_annotation. I expected that top_annotation will have different height but this not the case. 
How can I force heatmaps to have different height of top_annotation?

```
mat = matrix(rnorm(80,2), 8, 10)
clBar <- columnAnnotation(col_barplot=anno_barplot(1:10))
ht <- Heatmap(mat,cluster_rows = FALSE, cluster_columns = FALSE,
              top_annotation = clBar, show_column_names = F, 
              top_annotation_height = unit(2, "cm"))
ht2 <- Heatmap(mat,cluster_rows = FALSE, cluster_columns = FALSE,
              top_annotation = clBar, show_column_names = F,
              top_annotation_height = unit(4, "cm"))
ht+ht2
```
![rplot](https://user-images.githubusercontent.com/28019759/34892603-e09beeac-f7a7-11e7-833b-e78a4ddbad3c.png)

**Comment by jokergoo** [comment]
I think I didn't explain it clear in the documentation. `top_annotation_height` actually will be adjusted to the maximum top annotation height if you have more than one heatmaps. To control the exact height of annotation, you need to set the height inside `HeatmapAnnotation()` or `columnAnnotation()` function:

```{r}
mat = matrix(rnorm(80,2), 8, 10)
clBar <- columnAnnotation(col_barplot=anno_barplot(1:10))
ht <- Heatmap(mat,cluster_rows = FALSE, cluster_columns = FALSE,
              top_annotation = clBar, show_column_names = F, 
              top_annotation_height = unit(2, "cm"))
ht2 <- Heatmap(mat,cluster_rows = FALSE, cluster_columns = FALSE,
              top_annotation = HeatmapAnnotation(col_barplot=anno_barplot(1:10), annotation_height = unit(1, "cm")), 
              show_column_names = F)
ht + ht2
```
