### ISSUE TITLE
Split heatmap without adding text

### ISSUE THREAD

**Issue by JauntyJJS** [jokergoo/ComplexHeatmap#144]
Hi,

I was plotting the heatmap as follows using the dataset aqw

```{r}
split = aqw$Protein_Class

ha = rowAnnotation(df = data.frame(Protein_Class = aqw$Protein_Class),
                   col = list(Protein_Class = c("Mitochondrial" = "#00AFBB", "Muscle" = "blue", "Ribosomal" = "#7570B3", "Vitellogenin" = "orange")),
                   width = unit(1, "cm")
                   )

#Remove the column Protein_Class
aqw <- subset(aqw, select =-c(Protein_Class))

f1 = colorRamp2(c(min(aqw), 0 ,max(aqw)), c("green", "#EEEEEE", "red"))
p <- Heatmap(aqw, col = f1,
             cell_fun = function(j, i, x, y, width, height, fill) {
                 grid.text(label = sprintf("%.2f", aqw[i, j]), x = x, y = y,
                           gp = gpar(fontsize = 7.5))
             },
             cluster_rows = FALSE, cluster_columns = FALSE,
             name = "Log10_Peak_Intensity", column_title = "Set 1", column_title_side = "top", gap = unit(5, "mm"),
             row_title = "", row_title_side = "left", row_names_gp = gpar(fontsize = 7), row_names_side = "left",
             show_row_names = FALSE
             )

draw(ha + p, split=split)
```
This gives the heatmap

![image](https://user-images.githubusercontent.com/9066508/35092039-288eceac-fc79-11e7-9910-0ed4183390c5.png)

It seems that split has automatically create the large text "Mitochondrial, Muscle,..." on the left.

Is it possible to have a split without adding these large text as putting these names in a legend is good enough ?

I need to split gap to show clearly how the different Protein_Class in the dataset behave. 

Thank you.

**Comment by jokergoo** [comment]
You can add `combined_name_fun = NULL` as the last argument of `Heatmap()`.

**Comment by JauntyJJS** [comment]
Thanks. It works.

**Comment by WT215** [comment]
Just to update the information, in current version, the parameter control that seem to be below:
```
              column_title=NULL,
              row_title=NULL
```

**Comment by raveancic** [comment]
> Just to update the information, in current version, the parameter control that seem to be below:
> 
> ```
>               column_title=NULL,
>               row_title=NULL
> ```


This is the best solution!

**Comment by jokergoo** [comment]
@WT215  Thanks for add this information!
