### ISSUE TITLE
improving quality concatenated heatmaps

### ISSUE THREAD

**Issue by guidohooiveld** [jokergoo/ComplexHeatmap#145]
Hi,
I would like to create a figure that displays for 2 matrices the correlation between the rows (genes) and columns (metabolites) as a heatmap. I would like to have the order for both rows and columns to be the same in both heatmaps. (The row and column names are the same for both matrices, only the correlation value is different).

Problems that I face:
-After clustering, the order of the rows in both heatmaps is the same (by default). Also a dendrogram is shown. Question: how can I do the same for the columns?
I saw this thread [here](https://github.com/jokergoo/ComplexHeatmap/issues/115) (i.e. reordering the columns), but when using that approach no dendrogram is generated... Is it somehow possible to also show the (same) clustering dendrogram for the columns?
-The quality of the concatenated figure is much lower compared to the individual figures, especially for the 2nd heatmap. Is there a way to improve this?

Code:
```
# matrix1 =the 'main' heatmap, so that one is used for clustering.
# The same clustering should be 'overlaid' with the content of matrix2.

# cluster columns for matrix1 to set the order.
hc = hclust(dist(t(matrix1), method="euclidean"), method = "complete")
column_order = colnames(matrix1)[hc$order]

ht1 = Heatmap(matrix1,
	column_order = column_order,
	cluster_columns = FALSE,
	show_row_names = FALSE,
	)

# use the same order of columns for matrix2
ht2 = Heatmap(matrix2,
	column_order = column_order,
	cluster_columns = FALSE,
	show_row_names = FALSE,
	)

# Concatenate the 2 heatmaps
ht_list = ht1 + ht2
draw(ht_list)


png(file="ht1.png")
HM <- draw(ht1)	
dev.off()

png(file="ht2.png")
HM <- draw(ht2)	
dev.off()


png(file="ht_list.png")
HM <- draw(ht_list)	
dev.off()
```

Heatmap1 looks like this:
Quality is OK, but unfortunately no dendrogram for columns...
![ht1](https://user-images.githubusercontent.com/22979991/35345865-0a5c614e-0131-11e8-8054-a2e614aa0c32.png)

Heatmap2 looks like this:
Again, quality is OK, unfortunately no dendrogram for columns... but order columns is the same as for Heatmap1. (Order rows is [likely] different than that for Heatmap1 above).
![ht2](https://user-images.githubusercontent.com/22979991/35345903-2c52a272-0131-11e8-93f5-6dcb28a2d5e5.png)

Comnbined heatmap looks like this:
Both heatmaps have same order of rows and columns, but quality of heatmap2 (right) seems to be bad (white stripes), also no dendrograms present for columns.
![ht_list](https://user-images.githubusercontent.com/22979991/35345947-463b3a1e-0131-11e8-80cf-e890f32e20f6.png)

**Comment by jokergoo** [comment]
Hi, you can do follows if you want to add column dendrogram:

```{r}
hc = hclust(dist(t(matrix1), method="euclidean"), method = "complete")

ht1 = Heatmap(matrix1,
	cluster_columns = hc,
	show_row_names = FALSE,
	)

# use the same order of columns for matrix2
ht2 = Heatmap(matrix2,
	cluster_columns = hc,
	show_row_names = FALSE,
	)
```

For the second question, are you sure the two matrix `matrix1` and `matrix2` have same row orders? The problem is not the low quality, it is because the original row order for the two matrices are different and in the heatmap, the row ordering is determined by the first matrix (by default).

Can you show `head(matrix1)` and `head(matrix2)`?

**Comment by guidohooiveld** [comment]
Thanks for your fast reply, much appreciated!

Regarding your 2nd question:
> matrix1[1:6,1:6]
               Alb        ApoB  ApoB.ApoA1         CLA     CLA.FA        DHA
A1BG    0.12475258 -0.03246572 -0.02930611  0.18634446  0.1976850 -0.2281773
AASDH  -0.46373174 -0.28288877 -0.28421996 -0.65279081 -0.6554895  0.6015576
ABCA1   0.03675638 -0.55892450 -0.54381789  0.10920491  0.1662565 -0.4029472
ABHD11  0.26575113  0.49262059  0.48485509  0.34142654  0.3106599 -0.1427603
ABHD15 -0.01943359  0.21237225  0.20653050 -0.04952025 -0.0715558  0.1622368
ABT1    0.12742723  0.10628143  0.10591059  0.17655634  0.1745068 -0.1478543
> matrix2[1:6,1:6]
              Alb       ApoB ApoB.ApoA1        CLA     CLA.FA        DHA
A1BG    0.5815046  0.7202759  0.6385510  0.6606524  0.6445366  0.6253806
AASDH  -0.5786916 -0.6600978 -0.5772364 -0.5080126 -0.5000626 -0.5668720
ABCA1  -0.3205266 -0.3756934 -0.3300702 -0.3079426 -0.3021016 -0.3238422
ABHD11  0.4543088  0.4907660  0.4249728  0.3264590  0.3241339  0.4181640
ABHD15 -0.5163447 -0.6249937 -0.5520327 -0.5482111 -0.5359800 -0.5410430
ABT1   -0.2164412 -0.3064329 -0.2770501 -0.3469637 -0.3354958 -0.2702935
>
> all.equal(rownames(matrix1), rownames(matrix2))
[1] TRUE
> 

The rownames are thus the same. I understood that the row ordering is determined by the first matrix (this is indeed what I want).

Regarding the manual specification of the hclust output: yes; this adds indeed the (same) dendrogram! However, as you can see, the dendrogram of matrix2 is the (partially?) mirrored one of matrix1. Can this be controlled as well? So that it is not mirrored?

![ht_list](https://user-images.githubusercontent.com/22979991/35384555-ec1fd5a4-01c5-11e8-9382-2ba58eba36a3.png)


Finally, related question: what is the best way of exporting a heatmap as picture for publication? Calling a graphical device with e.g. png() or pdf() (and dev.off()) like I did before?

**Comment by jokergoo** [comment]
Ah, I forgot to tell internally the dendrogram will be reordered. To avoid this:

```
ht1 = Heatmap(matrix1,
	cluster_columns = hc,  ## <=====  
        column_dend_reorder = FALSE,
	show_row_names = FALSE,
	)

# use the same order of columns for matrix2
ht2 = Heatmap(matrix2,
	cluster_columns = hc, ## <===== 
        column_dend_reorder = FALSE,
	show_row_names = FALSE,
	)
```

I am a little bit worried that you add the dendrogram to the second heatmap because it will mislead
people to think the dendrogram is directly calculated from the second matrix while actually not.

To generate a plot for publications, I suggest PDF format.

**Comment by guidohooiveld** [comment]
Yes, working fine now by including the argument `column_dend_reorder = FALSE`.

I got you point regarding the possibility of misleading people, but in this particular case I would like to (visually) show that the correlation matrices for the same genes and metabolites look rather different for the two treatments.

Thanks again for your help!
