### ISSUE TITLE
Color from Heatmap Annotation does not match what I input

### ISSUE THREAD

**Issue by KoHaku55** [jokergoo/ComplexHeatmap#148]
Hi, 

I have tried a ComplexHeatmap package. It is easy for multi-heatmap and also wonderful. 
But I got struck when I add more annotaion from  rowAnnotation. 
I asked in stackoverflow yesterday. [https://stackoverflow.com/questions/48501910/colors-from-heatmapannotations-of-complexheatmap-do-not-match-input-how-can-fix](url)
and just found this link.

My problem is that when I define color for rowAnnotation function. Color output is completely different from what I input. My code is here
`library(ComplexHeatmap)
activity=list(type=c("A"="Red","U"="Grey","C"="Black","D"="Purple","R"="Blue"))
ra<-rowAnnotation(Dframe, col = activity, width = unit(0.05, "cm"))
H1+ra
draw(ra,1:48)`

here is a output from draw [https://www.picz.in.th/image/7SuVEk](url)
Sometime when I run the code again , color also changed to other color which does not match Red, Black, Purple and Blue.

Could you please help me ?

**Comment by jokergoo** [comment]
Can you try

```{r}
ra<-rowAnnotation(df = Dframe, col = activity, width = unit(5, "cm"))
```

What's the value in `Dframe`?

**Comment by KoHaku55** [comment]
Dframe is from DD which is list of factor.
`Dframe<-as.data.frame(DD)`

Colors output from your code is still the same

**Comment by jokergoo** [comment]
Then what is the value from `print(Dframe)`?

**Comment by KoHaku55** [comment]
> print(Dframe)
   DD
1   C
2   A
3   A
4   D
5   R
6   A
7   D
8   A
9   A
10  A
11  D
12  A
13  A
14  U
15  D
16  C
17  A
18  D
19  R

**Comment by jokergoo** [comment]
OK. Here the column name in `Dframe` should correspond to names in `activity`.
So `activity` should be defined as:

```{r}
activity=list(DD=c("A"="Red","U"="Grey","C"="Black","D"="Purple","R"="Blue"))
```

**Comment by KoHaku55** [comment]
Oh ! that's work!  Thank you very much !

**Comment by arianccbasile** [comment]
I have the same problem. I tried sooo many things (including this one) but nothing seems to work. Here my code:

`ann <- read.table("labels_correlations.txt",sep="\t",header=TRUE)
ann <- data.frame(ann$Phylum)
colnames(ann)<- c("Phylum")
vip_colors = c("#875E4C","#BF5256","#787878","#F3B6C4","#BB9687","#F9CB4C","#5C78A7","#9FADCE","#755142")
colz=list(Phylum=c(nr_phylum=vip_colors))
colx = colorRamp2(c(1, 0.5,0, -1), c("green2","palegreen", "white","red2"))

nn <- rowAnnotation(df=ann, col=colz)
pp <- HeatmapAnnotation(df=ann, col=colz,which='col')
hmap <- Heatmap(otter_mat, show_column_names=FALSE, col=colx, show_row_names=FALSE,right_annotation=nn, top_annotation=pp, name="Correlations",heatmap_legend_param = list(title = "Correlations"))`

Here the result from `head(ann)`
          Phylum
1  Bacteroidetes
2 Proteobacteria
3   Spirochaetes
4     Firmicutes
5     Firmicutes
6   Spirochaetes


Thank you for any future help.

**Comment by jokergoo** [comment]
These lines:

```r
vip_colors = c("#875E4C","#BF5256","#787878","#F3B6C4","#BB9687","#F9CB4C","#5C78A7","#9FADCE","#755142")
nr_phylum=sort(unique(ann$Phylum))
colz=list(Phylum=c(nr_phylum=vip_colors))
```

`vip_colors` should be constructed as:

```r
vip_colors = c("#875E4C","#BF5256","#787878","#F3B6C4","#BB9687","#F9CB4C","#5C78A7","#9FADCE","#755142")
nr_phylum=sort(unique(ann$Phylum))
names(vip_colors) = nr_phylum
colz = list(Phylum = vip_colors)
```

**Comment by arianccbasile** [comment]
OMG! It's working! Thank you very much!

**Comment by xiaodfeng** [comment]
Thanks
