### ISSUE TITLE
change combined name font size and direction

### ISSUE THREAD

**Issue by zouw2** [jokergoo/ComplexHeatmap#153]
Borrowing a figure from an old poster here: is there a way to 1) change the font size 2) make them go horizontal for the split names like 'muscle','mitochondrial', etc?  I searched and could not find an answer.
thanks
wei
![35092039-288eceac-fc79-11e7-9910-0ed4183390c5](https://user-images.githubusercontent.com/28939040/36652108-5ad7b67a-1a61-11e8-8822-3da181bb4d5f.png)

**Comment by jokergoo** [comment]
If you can also attach the code, I can directly tell you where to modify.

**Comment by zouw2** [comment]
this is modified from the example code.
library(ComplexHeatmap)
library(circlize)

set.seed(123)
mat = cbind(rbind(matrix(rnorm(16, -1), 4), matrix(rnorm(32, 1), 8)),
            rbind(matrix(rnorm(24, 1), 4), matrix(rnorm(48, -1), 8)))

mat = mat[sample(nrow(mat), nrow(mat)), sample(ncol(mat), ncol(mat))]
rownames(mat) = paste0("R", 1:12)
colnames(mat) = paste0("C", 1:10)

Heatmap(mat, name = "foo", split = paste('long name', rep(1:6, each =2 )))

How do I make a plot like the following (Just rotate the text and maybe reduce the font size)
thanks
wei
![2018-02-26_9-22-19](https://user-images.githubusercontent.com/28939040/36684988-dc074132-1ad6-11e8-8ca1-c08458b6a301.jpg)

**Comment by jokergoo** [comment]
Set `row_title_rot = 0`.

```
Heatmap(mat, name = "foo", split = paste('long name', rep(1:6, each =2 )), row_title_rot = 0)
```

**Comment by zouw2** [comment]
thanks! It worked.
wei
