### ISSUE TITLE
Error with NA values in matrix

### ISSUE THREAD

**Issue by asgarhussain** [jokergoo/ComplexHeatmap#155]
Hi,

I have data matrix with 'NA' values, Heatmap  function giving following error : 
Error in hclust(get_dist(submat, distance), method = method) : 
  NA/NaN/Inf in foreign function call (arg 11)
In addition: Warning message:
In get_dist(submat, distance) :
  NA exists in the matrix, calculating distance by removing NA values.

**Comment by jokergoo** [comment]
Have you checked your matrix? Maybe there are some rows where the values are all NA?

**Comment by asgarhussain** [comment]
One row has 2 NA values out of 3 column.

**Comment by jokergoo** [comment]
Then what distance method did you use? Euclidean or Pearson distance?

Are you use for each pair of rows, after removing NA values, there are still data points left? I mean, for following two vectors:

```
c(1, NA, NA)
c(NA, 1, 1)
```
Since each position has a NA value in either vector, after removing NA values, there is no data points left, thus, the distance value would be NA.

**Comment by asgarhussain** [comment]
I used pearson. My matrix look like this :


Tef      4.0557458  3.8574576  4.7649225
Arntl    1.1760904  1.0572257  2.3175744
Rorb     2.4848326 -0.9716492  0.6913426
Rorc            NA -2.2569073  1.0355071
Clock    2.1207759  2.0897219  2.6859312
Per3    -1.0726867 -2.9372859  1.5278600
Eomes    2.3315367  5.8591228  7.8151706
Per1     2.6965872  2.2613400  1.6644847
Per2     1.0025686  0.6149322  1.6024436
Cry1     2.5405347  2.4167338  3.3498465
Hlf      0.7316688 -3.4250347         NA
Bhlhe40 -0.1021592         NA  3.4156338
Cry2     3.8545024  3.0673124  2.6191768
Csnk1e   7.8435317  8.1707693  7.1193333
Dbp      4.1374722  4.4255667  4.2963502
Rora    -3.3857745 -2.8016819 -2.5826918
Nfil3    4.6756906  3.4436759  0.6915234
Homer1   6.1517663  5.4721908  5.4194088
Npas2   -1.2253903         NA         NA
Sox2     3.2081689  3.7098014  7.0326849

**Comment by jokergoo** [comment]
OK. For example, when calculating Pearson distance between Homer1 and Npas2, after removing NA values, actually there are only one pair of points remains (6.1517663 for Homer1 and -1.2253903 for Npas2), which is not sufficient for calculating Pearson distance, thus it gives you NA. Later on it gives you error for clustering since your distance matrix contains NA.

I suggest you either remove all genes with NA values or use **impute** package to impute the NA values in the matrix.

**Comment by slagtermaarten** [comment]
I had the same problem but needed to cluster and wanted to maximize data retention. I wrote this function to identify the minimum amount of rows and columns to remove in order to get rid of problems. This version is not perfect, the column and row identifications are independent.

```
#' Hclust cannot handle matrices in which for some pairs of rows and columns,
#' only 1 or fewer shared values are non-NA. This function recurrently
#' identifies the most aggravating column/row, excludes that column/row and checks
#' whether more columns/rows need to be excluded
#'
#'
identify_problematic_combs <- function(mat, min_shared_fields = 1) {
  exclude_rows <- NULL
  exclude_cols <- NULL
  stopifnot(is.matrix(mat))
  for (k in 1:nrow(mat)) {
    candidate_rows <- setdiff(1:nrow(mat), exclude_rows)
    problem_row_combs <- NULL
    for (i in candidate_rows) {
      i_idx <- which(candidate_rows == i)
      for (j in candidate_rows[i_idx:length(candidate_rows)]) {
        if (sum(!is.na(mat[i, ]) & !is.na(mat[j, ])) <= min_shared_fields) {
          problem_row_combs <- rbind(problem_row_combs, c(i, j))
        }
      }
    }
    if (is.null(problem_row_combs)) break
    exclude_rows <- c(exclude_rows,
      as.integer(names(which.max(table(problem_row_combs)))))
  }
  for (k in 1:ncol(mat)) {
    candidate_cols <- setdiff(1:ncol(mat), exclude_cols)
    problem_row_combs <- NULL
    for (i in candidate_cols) {
      i_idx <- which(candidate_cols == i)
      for (j in candidate_cols[i_idx:length(candidate_cols)]) {
        if (sum(!is.na(mat[, i]) & !is.na(mat[, j])) <= min_shared_fields) {
          problem_row_combs <- rbind(problem_row_combs, c(i, j))
        }
      }
    }
    if (is.null(problem_row_combs)) break
    exclude_cols <- c(exclude_cols,
      as.integer(names(which.max(table(problem_row_combs)))))
  }
  return(list('row' = exclude_rows, 'column' = exclude_cols))
}


remove_problematic_combs <- function() {
  problematic_combs <- identify_problematic_combs(
    mat = mat, min_shared_fields = min_shared_fields)
  if (!is.null(problematic_combs$row)) {
    mat <- mat[-problematic_combs$row, ]
  }
  if (!is.null(problematic_combs$column)) {
    mat <- mat[, -problematic_combs$column]
  }
  return(mat)
}
formals(remove_problematic_combs) <- formals(identify_problematic_combs)
```

**Comment by BioDocPete** [comment]
Your functions solved my problem. Thank you, Maarten Slagter!

**Comment by klkanchi** [comment]
any luck using the above function?

How can I use the above function ?
