### ISSUE TITLE
Oncoprint - "Page not found"

### ISSUE THREAD

**Issue by apuhegde** [jokergoo/ComplexHeatmap#156]
Hello,

The link for the oncoprint sends you to a "Page not found" page:

https://github.com/jokergoo/ComplexHeatmap/blob/fcaccd8ac595eb41c5cb48efeda119daf5e02fef/vignettes/s8.oncoprint.html

Is there a link to the oncoprint source code and/or example code?

**Comment by jokergoo** [comment]
Where did you find this link? If you are looking for the vignette for oncoPrint, you can go to the page on bioconductor: http://bioconductor.org/packages/release/bioc/vignettes/ComplexHeatmap/inst/doc/s8.oncoprint.html.
