### ISSUE TITLE
Row annotation alignment not correct when using npc units in gap

### ISSUE THREAD

**Issue by Alanocallaghan** [jokergoo/ComplexHeatmap#157]
The alignment of the main heatmap with the row annotation gets quite a bit off when using a reasonably sized gap parameter. The top and bottom of the annotation are correct, but the gap is overestimated. I haven't quite gotten my head around the code that positions each part yet, sadly. Here's a minimal reprex:

![heatmap_bug](https://user-images.githubusercontent.com/10779688/36977489-3d8711c4-2079-11e8-8332-3e8b0bee99f9.png)

```r
library(ComplexHeatmap)
library(circlize)

set.seed(123)
mat = matrix(rnorm(80, 2), 8, 10)
mat = rbind(mat, matrix(rnorm(40, -2), 4, 10))
rownames(mat) = paste0("R", 1:12)
colnames(mat) = paste0("C", 1:10)

ha_row = rowAnnotation(df = data.frame(type2 = c(rep("A", 6), rep("B", 6))), 
    col = list(type2 = c("A" =  "green", "B" = "orange")), width = unit(1, "cm"))

ht = Heatmap(mat, 
    split = rep(c("A", "B"), length.out = nrow(mat)), 
    gap = unit(0.5, "npc"))

ht_list = ht + ha_row

draw(ht_list)
```

**Comment by Alanocallaghan** [comment]
This appears to only be an issue when `gap` is specified in units of `"npc"`; ie, the following works fine:
library(ComplexHeatmap)
library(circlize)

set.seed(123)
mat = matrix(rnorm(80, 2), 8, 10)
mat = rbind(mat, matrix(rnorm(40, -2), 4, 10))
rownames(mat) = paste0("R", 1:12)
colnames(mat) = paste0("C", 1:10)

ha_row = rowAnnotation(df = data.frame(type2 = c(rep("A", 6), rep("B", 6))), 
    col = list(type2 = c("A" =  "green", "B" = "orange")), width = unit(1, "cm"))

ht = Heatmap(mat, 
    split = rep(c("A", "B"), length.out = nrow(mat)), 
    gap = unit(2, "cm"))
ht_list = ht + ha_row
draw(ht_list)

**Comment by jokergoo** [comment]
`unit(0.5, "npc")` means half size of the `min(width, height)` of your plot? if I understand npc right.

**Comment by Alanocallaghan** [comment]
Yes; the issue happens with lower npc values too. I just used 0.5 to demonstrate

**Comment by Alanocallaghan** [comment]
For example, with a gap of 0.2, you can clearly see that the bottom of the upper annotation is not flush with the bottom of the upper heatmap. The top of the lower annotation is also not flush with the top of the lower heatmap. This becomes more of an issue when you have more rows.

![heatmap_bug](https://user-images.githubusercontent.com/10779688/36982034-a805e194-2086-11e8-9736-d1f6ede3acd4.png)

**Comment by Alanocallaghan** [comment]
Actually a height of `unit(0.5, "npc")` is simply half the height of the current viewport.

**Comment by jokergoo** [comment]
Ah, yes, npc is value relative to the height of current viewport! It's must because they are calculated in viewports with different height for heatmap and row annotations (I will check that).

**Comment by jokergoo** [comment]
moved to #187
