### ISSUE TITLE
Adding borders to HeatmapAnnotations

### ISSUE THREAD

**Issue by bsgilgi** [jokergoo/ComplexHeatmap#158]
Thanks for the great package.
I have a question regarding HeatmapAnnotations. Is it possible to draw a border around the colored annotation of each sample (so the number of colored "boxes" will be the same as the number of samples)?

**Comment by jokergoo** [comment]
I think it should be the `gp` argument:

```
..., HeatmapAnnotation(..., gp = gpar(col = "black")) # black border
```

**Comment by bsgilgi** [comment]
This works great. Thanks a lot!!
