### ISSUE TITLE
Error in oncoPrint You should define shape function for:MUT:

### ISSUE THREAD

**Issue by fromdputto** [jokergoo/ComplexHeatmap#16]
I try to fellow the "oncoplot" exapmple from https://github.com/jokergoo/ComplexHeatmap/blob/master/vignettes/s8.oncoprint.Rmd
but it gives me error.

Here is an example:
```
mat = read.table(textConnection(
    "	S1	S2	S3	S4
KRAS		MUT	  	  
HRAS	MUT	MUT	MUT	MUT
BRAF	HOMDEL	  	  	  
RAF1		  	  	  
MAP3K1		HOMDEL	  	  
MAP3K2		  	  	MUT:
MAP3K3	AMP	  	  	  
MAP3K4	AMP	  	  	  
MAP3K5		MUT	HOMDEL	"), row.names = 1, header = TRUE, sep = "\t", stringsAsFactors = FALSE)

mat=as.matrix(mat)
col = c("MUT" = "#008000", "AMP" = "red", "HOMDEL" = "blue")
oncoPrint(mat, alter_fun_list = alter_fun_list, col = col, heatmap_legend_param = list(title = "Alternations", at = c("AMP", "HOMDEL", "MUT"), labels = c("Amplification", "Deep deletion", "Mutation")))

```
It gives the error 
```
Error in oncoPrint(mat, ...
  You should define shape function for:MUT:
```

**Comment by jokergoo** [comment]
I think you should change

    MAP3K2              MUT:

to 

    MAP3K2              MUT

**Comment by fromdputto** [comment]
I am still getting error
```
Error in mat_list[[1]] : subscript out of bounds
In addition: Warning message:
In is.na(all_type) : is.na() applied to non-(list or vector) of type 'NULL'
```

Someone please post a short reproducible example!!!
Thanks

**Comment by jokergoo** [comment]
Try following code, it works for me.

    mat = read.table(textConnection(
	"\tS1\tS2\tS3\tS4
	KRAS\t\t\tMUT\t
	HRAS\tMUT\tMUT\tMUT\tMUT
	BRAF\t\tHOMDEL\t\t
	RAF1\t\t\t\t
	MAP3K1\t\tHOMDEL\t\t        
	MAP3K2\t\t\tMUT\t
	MAP3K3\tAMP\t\t\t
	MAP3K4\t\tAMP\t\t
	MAP3K5\t\tMUT\tHOMDEL\t"), row.names = 1, header = TRUE, sep = "\t", stringsAsFactors = FALSE)

	mat=as.matrix(mat)
    library(ComplexHeatmap)
	alter_fun_list = list(
	    background = function(x, y, w, h) {
	        grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), gp = gpar(fill = "#CCCCCC", col = NA))
	    },
	    HOMDEL = function(x, y, w, h) {
	        grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), gp = gpar(fill = "blue", col = NA))
	    },
	    AMP = function(x, y, w, h) {
	        grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), gp = gpar(fill = "red", col = NA))
	    },
	    MUT = function(x, y, w, h) {
	        grid.rect(x, y, w-unit(0.5, "mm"), h*0.33, gp = gpar(fill = "#008000", col = NA))
	    }
	)

	col = c("MUT" = "#008000", "AMP" = "red", "HOMDEL" = "blue")
	oncoPrint(mat, alter_fun_list = alter_fun_list, col = col, heatmap_legend_param = list(title = "Alternations", at = c("AMP", "HOMDEL", "MUT"), labels = c("Amplification", "Deep deletion", "Mutation")))

![rplot001](https://cloud.githubusercontent.com/assets/449218/10455928/98cbaae8-71be-11e5-963e-2e9c7c53377c.png)
