### ISSUE TITLE
GPL license or MIT

### ISSUE THREAD

**Issue by crazyhottommy** [jokergoo/ComplexHeatmap#160]
Hi Zuguang,

I like your package really well. I was reading http://ivory.idyll.org/blog/2015-on-licensing-in-bioinformatics.html

I am planning to write all my helper functions (extract cluster ids etc) working with `ComplexHeatmap` into a package. If I use your package, I will have to use GPL license as well? I tend to use MIT license. 

Hadely also writes http://r-pkgs.had.co.nz/description.html on the license section.

Thank you very much!
Tommy

**Comment by jokergoo** [comment]
I think I will change to MIT license.
