### ISSUE TITLE
draw lines to connect anno_points

### ISSUE THREAD

**Issue by chinanicole** [jokergoo/ComplexHeatmap#161]
Is there a way to either draw a line as an annotation layer or connect the points drawn using anno_points (similar to geom_smooth in ggplot2). I've attached a picture for reference, with the first half of the annotation as an example of what I'd like. Thanks!
<img width="1018" alt="screen shot 2018-03-26 at 7 22 09 pm" src="https://user-images.githubusercontent.com/28635178/37938298-204d8954-312b-11e8-8158-f241938be0da.png">

**Comment by jokergoo** [comment]
Hi, `anno_points()` only draws simple point plot, but you can self-define your own annotation function. You can check this link: http://www.bioconductor.org/packages/devel/bioc/vignettes/ComplexHeatmap/inst/doc/s4.heatmap_annotation.html#toc_3

Following example add a smoothed line.

```{r}

mat = matrix(rnorm(100), nr = 10)

value = rnorm(10)
anno_loess = function(index) {
    n = length(index)
    pushViewport(viewport(xscale = c(0.5, n + 0.5), yscale = range(value)))
    grid.rect()
    grid.points(index, value[index], pch = 16, default.unit = "native")

    od = order(index)
    loess.fit = loess(value[od] ~ seq_len(n))
    x = seq(0, n, by = 0.05)
    loess.predict = predict(loess.fit, x)
    
    grid.lines(x, loess.predict, default.unit = "native")

    upViewport() 
}
ha = HeatmapAnnotation(loess = anno_loess)

Heatmap(mat, top_annotation = ha, top_annotation_height = unit(4, "cm"))
```

![image](https://user-images.githubusercontent.com/449218/38252018-55cc569a-3753-11e8-813a-468b260a5303.png)

Or if only want to add the smoothed line on top of the points, you can add this smoothed line by using `decorate_annotation()`:

```{r}

ht = Heatmap(mat, top_annotation = HeatmapAnnotation(pt = anno_points(value)), 
	top_annotation_height = unit(4, "cm"))
ht = draw(ht)
col_od = column_order(ht)[[1]]
decorate_annotation("pt", {
	n = ncol(mat)
	loess.fit = loess(value[col_od] ~ seq_len(n))
    x = seq(0, n, by = 0.05)
    loess.predict = predict(loess.fit, x)
    
    grid.lines(x, loess.predict, default.unit = "native")

})
```

For more information of `decorate_*()` functions, you can check this link: http://www.bioconductor.org/packages/devel/bioc/vignettes/ComplexHeatmap/inst/doc/s6.heatmap_decoration.html

**Comment by jokergoo** [comment]
moved to #187
