### ISSUE TITLE
When move row names to left and dendrogram to right, dendrogram will stay with the main heatmap in a list

### ISSUE THREAD

**Issue by xsswang** [jokergoo/ComplexHeatmap#162]
This is the example in the vignette:

mat = cbind(rbind(matrix(rnorm(16, -1), 4), matrix(rnorm(32, 1), 8)),
            rbind(matrix(rnorm(24, 1), 4), matrix(rnorm(48, -1), 8)))

rownames(mat) = paste0("R", 1:12)
colnames(mat) = paste0("C", 1:10)

ha_column1 = HeatmapAnnotation(points = anno_points(rnorm(10)))
ht1 = Heatmap(mat, name = "ht1", km = 2, row_title = "Heatmap 1", column_title = "Heatmap 1", 
              top_annotation = ha_column1, row_names_side = "left", row_dend_side = "right")

ha_column2 = HeatmapAnnotation(df = data.frame(type = c(rep("a", 5), rep("b", 5))))
ht2 = Heatmap(mat, name = "ht2", row_title = "Heatmap 2", column_title = "Heatmap 2",
              bottom_annotation = ha_column2, row_names_side = "left", row_dend_side = "right")

ht_list = ht1 + ht2
draw(ht_list, row_title = "Heatmap list", column_title = "Heatmap list", 
     heatmap_legend_side = "right", annotation_legend_side = "left")

By default, the dendrogram should move to the right side of the second heatmap.

![ht](https://user-images.githubusercontent.com/9425438/37971844-f5a524c6-31a4-11e8-9332-0b698d62c30a.png)

**Comment by jokergoo** [comment]
Hi, you can set `row_dend_side` in the `draw()` function. It controls the position of row dendrograms for the list of heatmaps.

```{r}
draw(ht_list, row_title = "Heatmap list", column_title = "Heatmap list",
    heatmap_legend_side = "right", annotation_legend_side = "left",
    row_dend_side = "right")
```
