### ISSUE TITLE
How to color row label

### ISSUE THREAD

**Issue by sanjaysingh765** [jokergoo/ComplexHeatmap#163]
Hi,
Is there anyway to produce a plot with row label text in given colour. Generally I do this in heatmap.2  like this 
rowcol <- as.character(rpkm$color). Thanks.

**Comment by jokergoo** [comment]
You can control it by:

```
Heatmap(..., row_names_gp = gpar(col = your_color_vector))
```

**Comment by sanjaysingh765** [comment]
Thanks.
