### ISSUE TITLE
Add an annotation between the top annotation and the plot

### ISSUE THREAD

**Issue by mhuacc** [jokergoo/ComplexHeatmap#167]
Hi,

How can I add an annotation just below the top annotation (not on the bottom)?

Thanks,
mh

**Comment by jokergoo** [comment]
Do you mean you want multiple top annotations? You can add in the `HeatmapAnnotation()` function:

```{r}
ha = HeatmapAnnotation(
    anno1 = ...,
    anno2 = ...,
    anno3 = ...,
    ...
)
Heatmap(..., top_annotation = ha)
```

Here `...` is a vector you used as annotations.
