### ISSUE TITLE
Parallel processing for larger heatmaps?

### ISSUE THREAD

**Issue by jamesdalg** [jokergoo/ComplexHeatmap#169]
Is there a way to make ComplexHeatmap::Heatmap() utilize multiple cores? Currently, plotting a 15000x15000 heatmap (even without using hclust) takes a really long time, no matter how many cores I have available to me on my cluster, even with an abundance of RAM.

**Comment by jokergoo** [comment]
If you have such big matrix to visualize, I would suggest to random sample a subset of rows and columns. The heatmaps would look almost the same. 

And also set `use_raster = TRUE` to turn the heatmap body as a png internally to reduce the final file size.
