### ISSUE TITLE
Long column names getting cut off

### ISSUE THREAD

**Issue by kcha** [jokergoo/ComplexHeatmap#17]
I have some column names that are very long and get cut off in the heatmap. How can I adjust the margins so that they appear completely and without decreasing the font size? 

e.g.
```
df <- data.frame(A_very_long_column_title_1 = rnorm(10), Another_very_long_column_title_2 = rnorm(10))
Heatmap(df)
```

![rplot](https://cloud.githubusercontent.com/assets/194053/10560257/b88a306c-74d3-11e5-99b9-04bc89975604.png)

Thanks!

**Comment by jokergoo** [comment]
You can set `column_names_max_height` argument in `Heatmap()`.

**Comment by kcha** [comment]
Thanks! I missed this argument in the help file.
