### ISSUE TITLE
columnAnnotation not working? 

### ISSUE THREAD

**Issue by sophie2046** [jokergoo/ComplexHeatmap#170]
Hi there,

I am trying to use a customized column labels. It is very easy in tradition heatmap.2 with labCol but very frustrated here. 

I tried it on its own and seemed no problem. 
> columnAnnotation(labels=anno_text(shortName))
A HeatmapAnnotation object with 1 annotation.

An annotation with self-defined function
name: labels 
position: column 

I am trying to put it together with the heatmap: 
> hm + columnAnnotation(labels=anno_text(shortName))
Error in `+.AdditiveUnit`(hm, columnAnnotation(labels = anno_text(shortName))) : 
  You should specify `which` to `row` or use `rowAnnotation()` directly if you want to add row annotations.

Why did it ask me to use rowAnnotation when I am working with columnAnnotation?

**Comment by jokergoo** [comment]
Column annotation is a component of a heatmap, so you need to send it to `top_annotation` or `bottom_annotation` argument in `Heatmap()`:

```
Heatmap(..., top_annotation = columnAnnotation(labels=anno_text(shortName)))
```

**Comment by sophie2046** [comment]
Thank you for your prompt reply. But the results doesn't seem to be what I want. The long name  were still  displayed, with the short name below horizontally overlay together.  How can I "replace" the original column name instaead of adding a new column annotation?  Can I hide the original column and rotate the new name?

**Comment by jokergoo** [comment]
You need to first set `column_names = FALSE` and then add a text annotation by hand. You can attach  your complete code, then I can have a closer look.
