### ISSUE TITLE
Heatmap incompatible with shinyjs

### ISSUE THREAD

**Issue by alastaircrisp** [jokergoo/ComplexHeatmap#171]
When loading shinyjs Heatmap is not drawn in a shiny app. Here's some dummy code showing the issue:

library(shiny)
library(ComplexHeatmap)

#library(shinyjs)
#detach("package:shinyjs", unload=TRUE)

shinyApp(
ui = fluidPage(
sidebarLayout(
sidebarPanel(
actionButton("newplot", "New plot")
),
mainPanel(
plotOutput("plot")
)
)
),
server = function(input, output) {
output$plot <- renderPlot({
input$newplot
# Add a little noise to the cars data
cars2 <- cars + rnorm(nrow(cars))
#plot(cars2)
#Heatmap(cars2)
Heatmap(cars2,cluster_columns = F, show_column_dend = F, row_names_side="left",column_names_side="top",show_heatmap_legend=F,
show_row_dend = F,cluster_rows = T,
column_names_gp = gpar(fontsize = 10),rect_gp = gpar(col= "white"),column_names_max_height= unit(1000,"mm"),
row_names_gp = gpar(fontsize = 10))

})

}
)

The plot will only be drawn if shinyjs isn't loaded. I asked the shinyjs author (https://github.com/daattali/shinyjs/issues/165) and he has a suggestion of what the issue might be.

**Comment by jokergoo** [comment]
Because you are not making heatmap in an R interactive mode, you need to first assign Heatmap to an object and then use `draw()` explicitly:

```
ht = Heatmap(...)
draw(ht)
```
