### ISSUE TITLE
working with cell_fun and heatmap width

### ISSUE THREAD

**Issue by flomehl** [jokergoo/ComplexHeatmap#173]
I am currently trying to draw a list of heatmap with circles of different sizes depending on a parameter and height of cells but it doesn't work when modifying width. Do you have an advice?

cell_fun = function(j, i, x, y, width, height, fill) {
                       grid.rect(x = x, y = y, width = width, height = height, gp = gpar(col = "grey", fill = NA))
                       if(beta.coeff.PL$pval.BMI[i] <= 0.001) {
                         grid.circle(x = x, y = y,
                                     r = unit.c(height),
                                     gp = gpar(fill = colors(PL.HM.gender.data[i, j]), col=NA))
                       }

thanks a lot :-)

**Comment by jokergoo** [comment]
If you can calculate the total width of the heatmap, you can set `width` argument in `Heatmap()` function:

```
Heatmap(..., width = ...)
```

but you also need to manually adjust the width of your PDF/PNG file to completely contain the heatmap.

**Comment by flomehl** [comment]
thanks for your answer. I may have unclearly expressed myself. I think that there is a conflict between the width parameter in the Heatmap function and the r parameter in the grid.circle in the cell_fun. If I specify a width value the r is not adapting anymore according to the height. I hop this is clearer

**Comment by jokergoo** [comment]
Can you show me the code you use? Following is my example code：

```{r}
m = matrix(rnorm(100), 10)

Heatmap(m, cell_fun = function(j, i, x, y, w, h, fill) {
  if(m[i, j] > 0) {
    grid.circle(x, y, r = min(unit.c(w, h)*0.5))
  }
})
```

**Comment by jokergoo** [comment]
Maybe you should change e.g. `r = 0.1` to `r = 0.1*min(unit.c(width, height))`.

**Comment by flomehl** [comment]
Thanks! I did this but it doesn't work when I am changing the width
argument in the Heatmap() function.

best

2018-05-29 7:40 GMT+02:00 Zuguang Gu <notifications@github.com>:

**Comment by jokergoo** [comment]
Can you also attach `data` and `ttest.pval.data` so that I can have a test?

**Comment by flomehl** [comment]
files are attached

2018-05-29 10:42 GMT+02:00 Zuguang Gu <notifications@github.com>:

**Comment by jokergoo** [comment]
Where are the files? I cannot see it.

**Comment by flomehl** [comment]
Sorry, I've sent them in csv, now it should be OK

[data.txt](https://github.com/jokergoo/ComplexHeatmap/files/2047729/data.txt)
[ttest.pval.data.txt](https://github.com/jokergoo/ComplexHeatmap/files/2047731/ttest.pval.data.txt)

**Comment by jokergoo** [comment]
Hi, I've found the reason. You need to add `height = convertHeight(height, "mm")` after the `grid.rect(...)`. 

```
Heatmap(data, name = "t.test", cluster_rows = FALSE,
                          rect_gp = gpar(type = "none"),
                          cell_fun = function(j, i, x, y, width, height, fill) {
                            grid.rect(x = x, y = y, width = width, height = height, gp = gpar(col = NA, fill = NA))
                          height = convertHeight(height, "mm"),
      ...
```
The reason is in `cell_fun`, the values in `width` and `height` are percent relative to the width and height of the heatmap. It is called the `npc` unit which is calculated differently for width and height. However, for the radius and the circle drawn by `grid.circle()`, if the unit is `npc`, I suspect it uses the value of `width` and that is why  you found the circles have different radius when you change the width of the heatmap. To solve this problem, just convert the `npc` unit to an absolute unit such as `mm`.

![image](https://user-images.githubusercontent.com/449218/40776635-e7512a5a-64fd-11e8-9566-84f39708ba7c.png)

**Comment by flomehl** [comment]
Hi!
thank you so much for your time! it’s great that you found the solution!

best,

Florence
