### ISSUE TITLE
Heatmap does not account for length of annotation names when calculating padding

### ISSUE THREAD

**Issue by Alanocallaghan** [jokergoo/ComplexHeatmap#174]
This results in the labels being cut off, or overlapping legends, in some circumstances.
```r
library("ComplexHeatmap")

Heatmap(mtcars, 
    top_annotation = columnAnnotation(mtcars[, 1:4], 
        show_annotation_name = TRUE, 
        show_legend = FALSE,
        annotation_name_side = "left"), 
    show_heatmap_legend = FALSE,
    cluster_rows = FALSE)
```
![heatmap1](https://user-images.githubusercontent.com/10779688/40174542-61892872-59cd-11e8-828e-84fd4536da91.png)

or 

```r
Heatmap(mtcars, 
    top_annotation = columnAnnotation(mtcars[, 1:4], 
        show_annotation_name = TRUE, 
        show_legend = FALSE), 
    show_heatmap_legend = FALSE,
    row_names_side = "left",
    cluster_rows = FALSE)
```

![heatmap2](https://user-images.githubusercontent.com/10779688/40174555-6adf8f4c-59cd-11e8-9a9f-07189f607d61.png)

**Comment by jokergoo** [comment]
No, it won't take account for the annotation names because there are also complex annotations (which are points, barplots, boxplots, ...) which makes it difficult to control everything (annotation names, annotation axes, ...). But you can manually control it by setting the `padding` argument:

```
ht = Heatmap(...)
draw(ht, padding = unit(c(2, 2, 2, 20), "mm")) #bottom, left, top, right paddings
```
