### ISSUE TITLE
legend for stacked bar?

### ISSUE THREAD

**Issue by itsvenu** [jokergoo/ComplexHeatmap#175]
Hi Jokergoo,

I was trying to add stacked barplot to my heatmap. Everything is fine but I would like to add a legend for the stacked barplot data. I didn't find any example in the vignette section [here](https://bioconductor.org/packages/devel/bioc/vignettes/ComplexHeatmap/inst/doc/s4.heatmap_annotation.html#toc_11). Here is my code for column annotation

```
col.ha = columnAnnotation(bars = column_anno_barplot(all_in_one_mod[2:4], gp = gpar(fill = c("red", "blue", "green")), border=FALSE, axis=TRUE, bar_width = 0.8), show_annotation_name = TRUE)
```
Is it possible to add a legend or am I missing something from vignette?

Thank you.

**Comment by jokergoo** [comment]
No, the legend for the barplot annotations are not automatically generated. But you can generate on manually by the `Legend()` function. Check following link:

http://www.bioconductor.org/packages/devel/bioc/vignettes/ComplexHeatmap/inst/doc/s5.legend.html#toc_3
