### ISSUE TITLE
Change column width?

### ISSUE THREAD

**Issue by AndreaRP** [jokergoo/ComplexHeatmap#176]
Hi Jokergoo,

I wonder if there is a way to modify the width of the columns. I've seen you added "column_width" as an "enhancement" but I'm not sure if it can be done at the moment. I've seen other people asking to add a padding (done with the cell_fun parameter), but what I would need is just to make the columns thinner, with no gaps or blank spaces between them. 

Thanks a lot!

**Comment by jokergoo** [comment]
Can you give an example here? I guess you can do it by setting a proper heatmap width.
