### ISSUE TITLE
Inconsistency between dist() and clustering_distance_rows?

### ISSUE THREAD

**Issue by templyv** [jokergoo/ComplexHeatmap#177]
So I'm trying to generate a heatmap for my data , but I get slightly different results depending on whether I make the dendrogram myself, or tell Heatmap to make it.

Data:

    a=rnorm(400,1)
    b=as.matrix(a)
    dim(b)=c(80,5)

If I make the dendrogram myself:

    d=dist(b,method="euclidean")
    d=as.dist(d)
    h=hclust(d,method="ward.D")
    dend=as.dendrogram(h)

    Heatmap(b,
    cluster_columns=FALSE,
    cluster_rows = dend)

Versus having Heatmap do the clustering:

    Heatmap(b,
    cluster_columns=FALSE,
    clustering_distance_rows = "euclidean",
    clustering_method_rows = "ward.D") 

They tend to look very similar, but they'll be very slightly different.

And this matters a lot for my data. Heatmap's clustering ends up organizing my data way, way better, however, I also want to extract the list of clustered items via like cutree(), but I don't think I can extract it from Heatmap's clustering.

What's going on?

**Comment by jokergoo** [comment]
What if 

```
Heatmap(b,
cluster_columns=FALSE,
clustering_distance_rows = "euclidean",
clustering_method_rows = "ward.D",
row_dend_reorder = FALSE)   #<<-- here, by default it is TRUE
```
If clustering is done by `Heatmap()`, the dendrogram is additionally reordered by the row means of the matrix (rotate the branches in the dendrogram if necessary). Reordering dendrograms sometimes makes the heatmap look better.

**Comment by templyv** [comment]
Thank you very much!

That solved it perfectly, however, I'm still struggling with a related issue:

    d=dist(b,method="euclidean")
    d=as.dist(d)
    h=hclust(d,method="ward.D")
    dend=as.dendrogram(h)

    Heatmap(b,
    cluster_columns=FALSE,
    cluster_rows = dend,
    row_dend_reorder = FALSE,
    split=4)

Versus:

    Heatmap(b,
    cluster_columns=FALSE,
    clustering_distance_rows = "euclidean",
    clustering_method_rows = "ward.D",
    row_dend_reorder = FALSE,
    km=4) 

So it's km vs split.

They produce very, very different heatmaps for my data. Km provides a much nicer looking heatmap than split, but I'm not sure where the difference comes from.

**Comment by jokergoo** [comment]
These are two different settings. split = 4 means to apply cutree(dendrogram, 4) while km = 4 applies kmeans with 4 groups.

Get Outlook for iOS<https://aka.ms/o0ukef>



On Wed, Jun 13, 2018 at 7:53 PM +0200, "templyv" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you very much!

That solved it perfectly, however, I'm still struggling with a related issue:

d=dist(b,method="euclidean")
d=as.dist(d)
h=hclust(d,method="ward.D")
dend=as.dendrogram(h)

Heatmap(b,
cluster_columns=FALSE,
cluster_rows = dend,
row_dend_reorder = FALSE,
split=4)


Versus:

Heatmap(b,
cluster_columns=FALSE,
clustering_distance_rows = "euclidean",
clustering_method_rows = "ward.D",
row_dend_reorder = FALSE,
km=4)


So it's km vs split.

They produce very, very different heatmaps for my data. Km provides a much nicer looking heatmap than split, but I'm not sure where the difference comes from.

-

**Comment by templyv** [comment]
All right. I think I get it now. Thank you again.

I believe this is the final thing.

I seem to get different clustering based on whether I give the color scheme before or after km.

    Heatmap(b,
    cluster_columns=FALSE,
    clustering_distance_rows = "euclidean",
    clustering_method_rows = "ward.D",
    row_dend_reorder = FALSE,
    col=viridis(200),
    km=4,
       ) 

Versus:

    Heatmap(b,
    cluster_columns=FALSE,
    clustering_distance_rows = "euclidean",
    clustering_method_rows = "ward.D",
    row_dend_reorder = FALSE,
    km=4,
    col=viridis(200),
       )

**Comment by jokergoo** [comment]
Kmeans has random initialization. How about adding set.seed(123) before each Heatmap()?

Get Outlook for iOS<https://aka.ms/o0ukef>



On Wed, Jun 13, 2018 at 8:15 PM +0200, "templyv" <notifications@github.com<mailto:notifications@github.com>> wrote:


All right. I think I get it now. Thank you again.

I believe this is the final thing.

I seem to get different clustering based on whether I give the color scheme before or after km.

Heatmap(b,
cluster_columns=FALSE,
clustering_distance_rows = "euclidean",
clustering_method_rows = "ward.D",
row_dend_reorder = FALSE,
col=viridis(200),
km=4,
   )


Versus:

Heatmap(b,
cluster_columns=FALSE,
clustering_distance_rows = "euclidean",
clustering_method_rows = "ward.D",
row_dend_reorder = FALSE,
km=4,
col=viridis(200),
   )


-

**Comment by templyv** [comment]
Ah right. Gotcha.

Thank you very much for your help.

I think it's a great package and everyone in my lab loves it.

**Comment by templyv** [comment]
I get different results depending on whether I use split=4 or split=cutree(dendrogram,4)

Why is that?

    Heatmap(b,
    cluster_columns=FALSE,
    clustering_distance_rows = "euclidean",
    clustering_method_rows = "ward.D",
    row_dend_reorder = FALSE,
    split=4,
       ) 

Versus:

    d=dist(b,method="euclidean")
    d=as.dist(d)
    h=hclust(d,method="ward.D")
    dend=as.dendrogram(h)

    Heatmap(b,
    cluster_columns=FALSE,
    clustering_distance_rows = "euclidean",
    clustering_method_rows = "ward.D",
    row_dend_reorder = FALSE,
    split=cutree(dend,4)
       ) 

I guess I don't see the difference with the small, fake data. But it's very distinct with my real data.

**Comment by jokergoo** [comment]
Can you send me the matrix you are using?

The difference is for the first situation, a dendrogram is first generated based on all rows in the matrix, then the dendrogram is cut into four sub-dendrograms; while for the second situation, rows are firstly split into four groups and four dendrograms are generated for the four row groups separately.
