### ISSUE TITLE
row order after clustering

### ISSUE THREAD

**Issue by rpanero** [jokergoo/ComplexHeatmap#178]
Hello,
I would like to get the index of the row after the clustering, this is what I did:
`h = Heatmap(m_norm, top_annotation = ha, 
        show_row_dend = F, show_column_dend = F, 
        show_row_names = F, show_column_names = F,
        cluster_rows = T, cluster_columns = F)
r = row_dend(h)
r
[[1]]
'dendrogram' with 2 branches and 963 members total, at height 302.8551 
`
How can I get the index of the rows?
Thanks.

**Comment by crazyhottommy** [comment]
see this https://github.com/jokergoo/ComplexHeatmap/issues/136
