### ISSUE TITLE
Label possible germinal variants

### ISSUE THREAD

**Issue by Tato14** [jokergoo/ComplexHeatmap#179]
Hi!

I am working with targeted panel data. I got a HeatmapList from the oncoplot function of maftools (https://github.com/PoisonAlien/maftools) and I would like to use ComplexHeatmap to label the variants that could be germinal (let's say with an `AF` > 40 and < 60 or >90). 
I am using a MAF file with all the variants with the calculated `AF` but I am not sure how could I manage to apply the labelling.

Any idea?
Thanks!

**Comment by jokergoo** [comment]
I think you can add a row annotation which are text or a subset of text by `row_anno_text()` or `row_anno_link()`:

```{r}
ht_list + rowAnnotation(text = row_anno_text(...))  # check anno_text() function
```

or

```{r}
ht_list + rowAnnotation(text = row_anno_link(...))  # check anno_link() function
```
