### ISSUE TITLE
Control the colours for annotation

### ISSUE THREAD

**Issue by wenbostar** [jokergoo/ComplexHeatmap#182]
Is there any parameter to control using the same annotation color for the same group in different plots? I know I can manually set the colors, but sometimes I have more than 20 sample groups so I want to use the colors generated by Heatmap. Is it possible to add a parameter to control this?

**Comment by jokergoo** [comment]
Then why not saving the color settings in a variable and use it repeatedly?

If you want to use the color randomly generated by ComplexHeatmap and use it somewhere else, you can obtain the colors by:

```
ha = HeatmapAnnotation(foo = 1:10, bar = c(rep("a", 5), rep("b", 5)))
ha@anno_list[[1]]@color_mapping@col_fun
ha@anno_list[[2]]@color_mapping@colors
```

**Comment by wenbostar** [comment]
This is a good way. Thanks a lot.
