### ISSUE TITLE
Support seriation

### ISSUE THREAD

**Issue by wenbostar** [jokergoo/ComplexHeatmap#183]
Is it possible to add a parameter to function **Heatmap** to support using the seriation package to find an ‘optimal’ ordering of rows and columns? (similar to the function of parameter "seriate" in [**heatmaply**](https://github.com/talgalili/heatmaply/blob/master/R/heatmaply.R))

**Comment by jokergoo** [comment]
I heard of this package before. I think it is a very nice suggestion. Thanks!

**Comment by wenbostar** [comment]
Thanks. Looking forward to the new feature.

**Comment by jokergoo** [comment]
Moved to #187

**Comment by jokergoo** [comment]
I add a section of how to integrate seriation in the new vignette.

https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#heatmap-seriation
