### ISSUE TITLE
Rotate the entire Heatmap (used as annotations)

### ISSUE THREAD

**Issue by qalid7** [jokergoo/ComplexHeatmap#186]
Hi

I know this may sound unconventional (please bear with me, I've my reasons not to use the classic annotation style in this package) ... I'm unable to find a straight solution.. 

I've a completely different plot where the columns represent samples, I'm using Heatmap function to annotate/highlight a few measures for each sample to then align the two using multipanelfigure.. 

Naturally, an option like this will result in long columns right next to each other:

Heatmap(df$col1, name = "col1", width = unit(2.85, "mm"), 
        cluster_rows = F, cluster_columns = F, gap = unit(2, "mm"),
        col = colorRamp2(c(5, 15, 25), c("blue2", "red2", "#f4d5d5")))+
  Heatmap(df$col2, name = "col2", width = unit(2.85, "mm"), 
          cluster_rows = F, cluster_columns = F, gap = unit(2, "mm"),
          col = c("greenyellow", "hotpink"))+

How can I rotate the entire heatmap plot say -90, or even flip it if possible, to then align it with the other plot.. also change the position where the legends are.. 

Is this possible?

**Comment by qalid7** [comment]
Thanks that's a neat solution, but then remember I need to feed this into multipanelfigure, and it seems like that won't work because you're only changing the orientation at viewport, I don't think there's a way to save this updated output in a class acceptable to be used in multipanel (like the output of grid.grabExpr)

if that makes any sense at all?

**Comment by jokergoo** [comment]
In the new version of this package, it now allows concatenating heatmaps/anntations vertically. This might provide a way to solve your problem.

**Comment by qalid7** [comment]
Wonderful news! Do we've an example somewhere to do this?

**Comment by jokergoo** [comment]
Now the package is usable, but the documentation is not finished yet, also there might be some bugs. You can try it by `devtools::install_github("jokergoo/ComplexHeatmap")`.

The usage is:

```{r}
Heatmap(...) %v% Heatmap(...)
```

You use `%v%` instead of `+` for vertical alignment.

**Comment by Hasani2015** [comment]
I'm getting an error when using %v%: 

> Error: could not find function "%V%"

should I install some additional library?

thanks

**Comment by jokergoo** [comment]
Have you updated to 1.99.*?

**Comment by Hasani2015** [comment]
Yes, thank you.

**Comment by jokergoo** [comment]
1.17.1 is too low. The error you have mostly due to how you call `HeatmapAnnotation()` function. Can you attach the code here?
