### ISSUE TITLE
Rotate Heatmap Column Names by 45 degrees

### ISSUE THREAD

**Issue by JauntyJJS** [jokergoo/ComplexHeatmap#189]
Hi,

I understand that it is possible to adjust the size, colour and font of the column name of the heatmap using column_names_gp. 

May I ask if it is possible to rotate the column name by 45 degrees ?
Like the heatmap in 
https://stackoverflow.com/questions/15505607/diagonal-labels-orientation-on-x-axis-in-heatmaps

Thank you.

**Comment by jokergoo** [comment]
You cannot directly rotate the column names in the current version, but I am working on it to support it in the next version.

The solution for the current version is to use a text annotation instead:

```
cn = colnames(mat)
Heatmap(mat, show_column_names = FALSE, 
    bottom_annotation = HeatmapAnnotation(
        text = anno_text(cn, rot = 90, offset = unit(1, "npc"), just = "right"),
        annotation_height = max_text_width(cn)
    )
)
```

**Comment by JauntyJJS** [comment]
Ok Sure. Thank you for the help.

**Comment by orangebromeliad** [comment]
Hi @jokergoo , I'm having this problem with rowAnnotation names, which I'd like to rotate 45 degrees. Do you have a solution to this if it is not possible directly?

Many thanks for such a great package!

Tim

**Comment by jokergoo** [comment]
Hi @orangebromeliad , rotate text annotation, see https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html#text-annotation, rotate matrix row names, set `row_names_rot = 45` argument. Note you need to use version >= 2.0.0

**Comment by crazyhottommy** [comment]
it is not possible to rotate the title_column using `column_title_rot = 45`, only 90 or 0 is supported. my column_title (from anno_block) is too long and gets cut. is there a way to better accommodate it?

Thanks!

**Comment by jokergoo** [comment]
Don't you think a 45-degree title is strange? :)

Anyway, you can always use `decorate_*()` functions (e.g. `decorate_column_title()`) to do whatever you want.

And remember to set `draw(ht, ..., padding = ...)` to control the space around the heatmaps.

**Comment by ATpoint** [comment]
@jokergoo  Could you please give an example on how to do what you describe in the last post? I simply cannot get my head around it (yes I read the manual multiple times). Say one used `column_split` to split your columns into groups. What would I need to do now to rotate the chunk labels by 45°? Is there actually a way to change height of those titles, e.g. putting C7 a bit higher so it does not collide with C6? Due to the size of some heatmaps (single-cell) I can impossibly open them in something like Inkscape. Thank you for your time!

![Screenshot 2021-01-13 at 01 25 50](https://user-images.githubusercontent.com/21218078/104390588-58bc4980-553e-11eb-9cbc-77aefe301393.png)

**Comment by jokergoo** [comment]
I normally use a trick: change `C7` to `C7\n"` and other text to e.g. `"\nC1"`

**Comment by JesseRop** [comment]
Hi @jokergoo , thanks for the great package and the range of flexibility it offers.

Is there are an elegant way of rotating the labels in the image by @ATpoint .
I have the same problem.
![image](https://user-images.githubusercontent.com/18431376/168287020-39fc6b32-1d12-42cb-855d-ea7e2645dee7.png)

**Comment by jokergoo** [comment]
Now `column_title_rot` can be set with any degree value:

<img width="663" alt="image" src="https://user-images.githubusercontent.com/449218/171143756-b693c0d8-ded2-42a8-a2f0-c69b30d6cb1d.png">

**Comment by JesseRop** [comment]
Thanks @jokergoo !
