### ISSUE TITLE
Custom Legend Annotation labels

### ISSUE THREAD

**Issue by JauntyJJS** [jokergoo/ComplexHeatmap#191]
Hi,

I have created a heatmap with this color scale

color = colorRamp2(c(-6, -2, 0, 2, 6), c("#2c7bb6", "#abd9e9", "#000000", "#fdae61", "#d7191c"))

The heatmap legend annotation created by the Heatmap function gives the following

![image](https://user-images.githubusercontent.com/9066508/44413209-5d62ba80-a59d-11e8-8070-b24383142744.png)

I was wondering if it is possible for me to customize the (-10,5,0,5,10) to (-6,-2,0,2,6) or better still 
(-6 <=, -2 , 0, 2, >6 ) 

Similar to the example below 
![image](https://user-images.githubusercontent.com/9066508/44413264-87b47800-a59d-11e8-9b71-b1024006010d.png)

**Comment by jokergoo** [comment]
You can control the heatmap legend by `heatmap_legend_param` argument:

```
Heatmap(..., heatmap_legend_param = list(at = c(-6, -2, 0, 2, 6), labels = c("<=-6", "-2", "0", "2", ">=6"))
```

**Comment by JauntyJJS** [comment]
Thank you for the input
