### ISSUE TITLE
Heatmap annotation color issue

### ISSUE THREAD

**Issue by apaala** [jokergoo/ComplexHeatmap#193]
Hey, not sure why sometimes the heatmap annotation picks colors very close together. It does not happen for every dataset in my loop, just for 2, where it will pick very very close shades of the same color.

Command:
heatmap_a<-HeatmapAnnotation(df=data.frame(heatmp_a = heatmp_a), annotation_legend_param = list(title="Condition", title_gp = gpar(fontsize = 10, fontface=2, fontfamily="Helvetica")))

hmap_plot<- Heatmap(resort, show_row_names = FALSE,  name="DECounts", column_title_gp = gpar(fontsize=6), column_title_side = "bottom", top_annotation = heatmap_a, row_names_gp = gpar(fontsize = 2), cluster_rows = FALSE)

==============================
To elaborate: I am generating heatmaps in a loop and saving like so:

file_name = paste(DEOut,i, "_Hmap_images.png", sep="")
png(file_name,width = 4, height = 4, units = 'in', res = 300)
draw(htlistDE)
dev.off()

It is changing colors when saving to png, I dont understand why.

Thanks for your help!

**Comment by jokergoo** [comment]
Since you didn't specify the colors for the annotations, the colors are randomly generated, so it is possible the colors that are chosen are close to each other.

**Comment by apaala** [comment]
Hi

So it generated different colors when I run it, but when I save it as png it changes colors, would you know why that might be?

**Comment by jokergoo** [comment]
Can you attach the complete code or send to my email address?

The random color is fixed after `heatmap_a` and `hmap_plot` are generated.

**Comment by apaala** [comment]
Hey

Here is the attached code. Its in rmarkdown , but the heat maps are being generated in the r chunk called DEHeatmaps.

Thank you so much for your help!

Best
Apaala

**Comment by jokergoo** [comment]
Hi @apaala , I can see your reply in my email but without the attached code. I cannot either see your reply in this thread. Can you send me the code again?
