### ISSUE TITLE
Extracted dendrogram from heatmap not stable

### ISSUE THREAD

**Issue by lgillet** [jokergoo/ComplexHeatmap#194]
Hi, 
I was following the tips provided here (https://github.com/jokergoo/ComplexHeatmap/issues/136) to get the dendrogram out of my complexHeatmap, when I stumbled into the fact that those reported row_order(hm) are not stable: you can run it several times and you never get the same list of rows. 
Am I doing something wrong there? In principle, once the heatmap is drawn (and the clustering done), it should be "fixed", right? Why can't I get the clustered rows out properly?
Thanks a lot in advance for your help!!
Ludo 
platform: x86_64-w64-mingw32
R version 3.4.4 (2018-03-15)
complexHeatmap: 1.6.0

**Comment by jokergoo** [comment]
Did you apply k-means clustering on rows? If yes, set random seed before making heatmap:

```
set.seed(123)
ht = draw(Heatmap(..., km = 2))
row_order(ht)
```

**Comment by lgillet** [comment]
Hi, 
thanks for the reply. This indeed worked (partially). 
It seems that `set.seed` needs to be specified in front of `row_order` rather, and **each time** you call it. 

What I did not get is that, even though the heatmap results are supposedly stored in `hm`, the k-means clustering is redone each time you call `row_order(hm)`?!

In short, my "updated" code adapted from @guidohooiveld (https://github.com/jokergoo/ComplexHeatmap/issues/136) would be like this: 

```
hm = Heatmap(..., km = 2)
draw(hm)

for (i in 1:length(row_order(hm))){
  if (i == 1) {
    set.seed(123)
    clu <- row.names(m.stand[row_order(hm)[[i]],])
    out <- cbind(clu, paste("cluster", i, sep=""))
    colnames(out) <- c("PrecId", "Heatmap_Cluster")
    } else {
      set.seed(123)
      clu <- row.names(m.stand[row_order(hm)[[i]],])
      clu <- cbind(clu, paste("cluster", i, sep=""))
      out <- rbind(out, clu)
    }
}

out <- as.data.frame(out)
```

Many thanks for the help :)

**Comment by jokergoo** [comment]
Ah, I see. You should modify here:

```
hm = Heatmap(..., km = 2)
hm = draw(hm)
```

`hm` returned by `Heatmap()` actually just keeps all the configurations of the heatmap while not does clustering, reordering, blablabla. The rows and columns are clustered and reordered after calling `draw()` function explicitely or inexplicitely. So here you need to call `draw()` and re-assign to `hm`.
If you don't do this, in the `for` loop later in your code, every time you call `row_order(hm)`, `hm` is a "uninitialized" heatmap and it will perform clustering every time.

**Comment by lgillet** [comment]
Perfectly clear now!!
Thanks a lot :)

**Comment by analyze-eng** [comment]
I think this is still an issue.  The original point is that calling row_order seems to re-run the km even with a saved object.  

```
library(ComplexHeatmap)

set.seed(101);dat<-matrix(rnorm(10*10),10,10)

set.seed(102);row_order(HM<-Heatmap(dat,km=3))
row_order(HM) # not the same.
row_order(HM) # another not the same.

set.seed(102);row_order(HM) # probably the answer.

# Ask draw to evaluate it... still an issue
set.seed(102);draw(HM<-Heatmap(dat,km=3))
set.seed(102);row_order(HM)
row_order(HM)
```

**Comment by jokergoo** [comment]
I think it should be 

```r
HM = draw(Heatmap(dat,km=3))
row_order(HM)
row_order(HM)
```
