### ISSUE TITLE
recent plan, updated

### ISSUE THREAD

**Issue by jokergoo** [jokergoo/ComplexHeatmap#196]
- [x] anno_link() should be applied to the whole heatmap body while not one single row slice.
- [x] add a `layer_fun` argument to `Heatmap()` to make `cell_fun` vectorized, which also makes oncoprint vectorized.
- [x] think a better way to integrate seriation (https://cran.r-project.org/web/packages/seriation/index.html)
- [x] write more clear messages when there are mistakes. (all should be wrapped by `stop_wrap()` or `warning_wrap()`.
- [x] write the complete reference with bookdown (https://github.com/jokergoo/ComplexHeatmap-reference)
- [x] need to check whether annotation names overlap to titles and legends.
- [x] make `row_order(draw(Heatmap(...)))` consistent as `row_order(Heatmap(...))`
- [x] `tibble` as the input of `HeatmapAnnotation()` #197 
- [x] do `width`/`height` really need to be arguments for `HeatmapAnnotation()`?
- [x] support smoothing in `anno_lines()`.
- [x] apply more checks on `...` in `HeatmapAnnotation()`, e.g. whether the data frame is specified with no name.
- [x] support `GetoptLong::qq()` and `glue::glue()` as template for the row titles when rows are split.
- [x] for places where `row_gap` and `column_gap` are used, use `gap` if only `row_gap` or `column_gap` is specified. (also `packLegend()`)
- [ ] think about `annotation_offset`.
- [x] `anno_mark()` should have no annotation names drawn in the plot
- [x] think about an annotation that is not spilt by the splitting of the main matrix. (anno_mark() can be implemented in this way that it will never to split and the position of labels in each slice can be calculated in the whole heatmap.
- [x] check arguments which is from `draw,HeatmapList-method`. (e.g. `row_split` is not checked if it is called there)
- [x] may use `width` for the heatmap body and `heatmap_width` for the whole heatmap.
- [x] where annotation has names and no row names, the legend can be put besides the heatmap while leave some space on the very right.
- [x] check when slice = 2 and row_title = 1, how the viewport index is assigned,.
- [x] `subset.Heatmap()`: more things to be adjusted.
- [x] gap between the annotation and heatmap body (e.g. as `left_annotation`)
- [x] add `anno_summary()` to make barplot/boxplot for one-column or one-row heatmap
- [x] for the one-column heatmap, there is extra space between the heatmap and the legend. (maybe I forget the add or remove those "gaps" between heatmaps and components.)
- [x] how about a list of row annotations added but with not heatmap and the height is set to a fixed unit?
- [x] `width`, `heatmap_width` in `draw,HeatmapList-method()` have not been considered yet.
- [x] row names are not drawn when the most right is the row annotation
- [x] row titles are still drawn if `row_title = ""` when rows are split.
- [x] plots are shown on page 2 if save as pdf
- [x] give error when `heatmap_width`/`heatmap_height` is too small
- [x] `annotation_axis()`: adjust positions for the first axis label and the last axis label
- [x] when setting `ht_gap`, the legend is too close to the heatmap
- [x] `show_annotation_name` not work properly for annotation functions
- [x] think about how to implement `anno_oncoprint_barplot()`. Currently the implementation is difficult to find the values inside `oncoPrint()` function.
- [x] when `remove_empty_rows` and `remove_empty_columns` is set, also subset other heatmap components
- [x] `densityHeatmap()`: consider column split
- [x] space between row title and most left heatmap is too large (https://jokergoo.github.io/ComplexHeatmap-reference/book/more-examples-of-making-complex-heatmaps.html#visualize-methylation-profile-with-complex-annotations)
- [x] rename `width`/`height`/`size`/`resize` because they are also generic functions in other packages.
- [x] remove some of the quantile values when `ylim` is set.
- [x] check `width`/`height` setting when the annotation is a self-defined function (not `anno_*()`)
- [x] check when `heatmap_legend_list` or `annotation_legend_list` is set and put at bottom of the heatmap
- [ ]  `border_gp`?
- [x] default rotation of annotation name (row/column)
- [x] `oncoPrint()`: increase the space between row names and barplots.

**Comment by jokergoo** [comment]
`anno_mark()` works when the rows are split. Try following code:

```
m = matrix(rnorm(1000), nrow = 100)
ha = rowAnnotation(foo = anno_mark(at = c(1:4, 20, 60, 97:100), labels = month.name[1:10]))
Heatmap(m, name = "mat", cluster_rows = FALSE, right_annotation = ha, row_km = 2)
```
![image](https://user-images.githubusercontent.com/449218/51735208-0babe800-2087-11e9-80df-5962f5407299.png)

**Comment by tiagobrc** [comment]
Thanks for the suggestion!! It looks like the problem derives from cluster_columns, which put the text outside of the heatmap area. When removing cluster columns it works.
