### ISSUE TITLE
feature-request: allow `tibble`s as input to HeatmapAnnotation

### ISSUE THREAD

**Issue by russHyde** [jokergoo/ComplexHeatmap#197]
Hi. I have a slight issue whenever my row-annotation data is stored in a tidyverse `tibble` datastructure. Although I can run `HeatmapAnnotation(some_tibble)`, the resulting object can't be used in `draw`.

```
# works fine
draw(HeatmapAnnotation(data.frame(a = 1:3, b = TRUE)), 1:3)
```

```
# throws error
draw(HeatmapAnnotation(tibble(a = 1:3, b = TRUE)), 1:3)
Error : Column indexes must be at most 1 if positive, not 2, 3
Error when drawing annotation 'a'
Error in .local(object, ...) : 
  Error : Column indexes must be at most 1 if positive, not 2, 3
> traceback()
4: stop(oe)
3: .local(object, ...)
2: draw(HeatmapAnnotation(tibble(a = 1:3, b = TRUE)), 1:3)
1: draw(HeatmapAnnotation(tibble(a = 1:3, b = TRUE)), 1:3)
```

I appreciate that tibble's dont' inherit all of data.frame behaviour, so this is really a feature-request rather than a bug. I'm happy to work on a pull-request if you agree that data.frame-like data-structures should be allowable input to HeatmapAnnotation

**Comment by jokergoo** [comment]
Good suggestion! Since I don't use tidyverse too much in my daily analysis, I haven't considered to support the tibble format, but I think it is quite easy to support it. Thanks!

**Comment by jokergoo** [comment]
I have added support for all other formats that can be converted into the `data.frame` class.

Another thing is you need to specify the annotation with the argument name. If it is a data frame or something that can be converted as a data frame, you need to put with `df` argument:

```
HeatmapAnnotation(df = data.frame(a = 1:3, b = TRUE))
```
