### ISSUE TITLE
Does it accept NA value?

### ISSUE THREAD

**Issue by wenbostar** [jokergoo/ComplexHeatmap#2]
Hi,
Does it accept NA value for plot heatmap when I don't want to do cluster?
Best regards!
Bo

**Comment by jokergoo** [comment]
That is a good suggestion. I will support color mapping for NA values in the next version. Thanks!

**Comment by jokergoo** [comment]
Now the new version (1.1.4) supports color mapping to NA values. I also add examples in the **Color** section in the vignette to show how to deal with NA values in the heatmap. It may take several days for Bioconductor to update to the new version, but you can install it directly from GitHub.

**Comment by wenbostar** [comment]
Thanks a lot.
Best regards!
Bo
