### ISSUE TITLE
Oncoprint:  show_column_barplot = FALSE  and show_row_barplot = FALSE change the color of the Annotation

### ISSUE THREAD

**Issue by msquatrito** [jokergoo/ComplexHeatmap#20]
Hi,
with the `oncoPrint` function setting either show_column_barplot = FALSE  or show_row_barplot = FALSE mess up the colors and the label of the Annotation.
Best
Massimo

**Comment by jokergoo** [comment]
Sorry, it is because I forgot to copy the same settings for the condition of `show_column_barplot == FALSE`.
Now it is fixed and I have tested these two options:

![rplot001](https://cloud.githubusercontent.com/assets/449218/10996842/c73deb5c-8488-11e5-8947-b3dc6e284f20.png)

**Comment by msquatrito** [comment]
Perfect! Only one thing, I have to specify `column_title = " "` to avoid to hide the row bar plot scale when `show_column_barplot == FALSE`
Thanks

**Comment by jokergoo** [comment]
Yes, this is a limitation at least in current version, because the package doesn't allocate any space for the        axes of barplot annotations. 

Another solution to show the axes when there is no column title is to add top padding for the whole plot:

```{r}
ht = oncoPrint(...)
# four paddings correspond to bottom, left, top and right padding.
draw(ht, padding = unit(c(2, 2, 8, 2), "mm"))
```

**Comment by MGCarta** [comment]
Hi!
The issue is pretty old and closed. Are the parameters `show_column_barplot `and `show_row_barplot `still valid?
With the version of the package ComplexHeatmap_2.13.1 I get the error:
```
Error in oncoPrint(oncoprint_matrix, get_type = function(x) strsplit(x,  : 
  object 'show_row_barplot' not found
```
Thanks!
