### ISSUE TITLE
merge.dendrogram not updated in NAMESPACE

### ISSUE THREAD

**Issue by abasavan** [jokergoo/ComplexHeatmap#201]
It looks like `merge.dendrogram` was recently replaced with the `merge_dendrogram`, but the `NAMESPACE` file hasn't been updated to reflect this.

**Comment by jokergoo** [comment]
Yes, the `merge.dendrogram` conflicts with functions in other packages so I renamed it. I just pushed an update yesterday, not it is `merge_dendrogram` in NAMESPACE.
