### ISSUE TITLE
Suggestion: allow grouping factors for annotation plots 

### ISSUE THREAD

**Issue by yanxianl** [jokergoo/ComplexHeatmap#203]
Hi there,

Thank you for developing and maintaining the ComplexHeatmap package!

I found the annotation plots (anno_boxplot, anno_density_violin/heatmap, etc.) to be really useful for complementing the heatmap, in regard to providing data summary. However, it seems that we can only make annotation plots for all the data points within each column or row. I wonder if it's possible to draw an annotation plot panel showing summary statistics for different grouping factors. For example, there're 3 different experimental treatments within each column. Showing the data distribution using a violin plot for all the data points in each column is not very interesting to me. Rather, I'd like to plot a violin for each of the treatment, combine these 3 violin plots as a panel and use it as the column annotation. Of course, we can make the violin plot panel, say, using ggplot2, and combine it with the ComplexHeatmap vis functions such as gridExtra:grid.arrange or cowplot::plot_grid. However, it'd be really great if we can just do it within the ComplexHeatmap.

Again, thank you for your genius work for making this marvelous R package.

Yanxian

**Comment by jokergoo** [comment]
Hi Yanxian,

This is a very nice suggestion!

It is actually a little bit difficult because the samples in a same factor level should stay together (I mean
the rows or the columns should attach each other), but it it not always true when you apply clustering
on rows or columns to reorder them.

But Indeed, it is very useful and I will try to think out an optional solution for this.

Thanks!

**Comment by jokergoo** [comment]
Hi, I have some thoughts on how to implement this new functionality. See the following link:

https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html#zoom-annotation

**Comment by yanxianl** [comment]
Hi, the new reference manual and features are really cool! The zoom annotation is fantastic for heatmaps without obvious patterns. Thanks!
