### ISSUE TITLE
Set Stacking Order for top boxplot

### ISSUE THREAD

**Issue by WillDuke** [jokergoo/ComplexHeatmap#206]
Hi Jokergoo,

Thanks for putting together this package! A quick question for you: Is it possible to set the order in which colors (alteration types) are stacked in the top boxplot? 

I'm trying to create an oncoPrint with 3 mutation types, two of which always occur in the same gene. I'd like to have the green marks drawn at the bottom of the boxplot with the red above, just as it is with blue in the attached picture. 

<img width="463" alt="screen shot 2018-10-25 at 2 26 12 pm" src="https://user-images.githubusercontent.com/41601410/47521812-fc3bb980-d861-11e8-92a8-8c5190999fa0.png">

Thanks,

Will

**Comment by jokergoo** [comment]
How do you define `alter_fun`? The order of colors in the barplot is the same as the order in `alter_fun`.

**Comment by WillDuke** [comment]
Wow, thanks for the quick reply! I defined them in the following order: background, blue, green, and red, but that didn't change the output. Should I put background at the end?

**Comment by WillDuke** [comment]
Or could it be an issue that I specified the column and row orders?

**Comment by jokergoo** [comment]
Ah, I've checked that the order of colors in barplots are not always the same as the order defined in `alter_fun`... I will fix it tomorrow.

**Comment by WillDuke** [comment]
Great! Thanks so much for your help!

**Comment by jokergoo** [comment]
Hi, I have updated the package on github. This new version I am developing has big changes and I haven't check how much it is compatible with the old versions. If you have any problems that you cannot solve, please ask me.

**Comment by WillDuke** [comment]
Worked beautifully, thank you!
