### ISSUE TITLE
Ignore alteration in calculation of row percentage

### ISSUE THREAD

**Issue by mcewenrk** [jokergoo/ComplexHeatmap#207]
Hello,

I can't find any information but I was wondering about how the oncoPrint function handles samples which one would like to include in the view but haven't been sequenced /profiled. This is distinct from the "mutation not detected" grey rectangle of course. I have used a "not profiled" alteration as a white rectangle to show this but this is considered as an alteration and included in the row percentage calculation. For example if I have 20 samples; 15 of which are WT for a gene and 5 are "not profiled" the row percentage is shown as 25%. Is there a way of using this "not profiled" without it being considered in the row percentage calculation? 
I tried the "barplot_ignore" call but that's not quite the functionality but perhaps an "ignore_alteration" option would be a solution?
Thanks,
Rob

**Comment by jokergoo** [comment]
oncoPrint() cannot deal with the situation you mentioned automatically. This will increase the complexity of the function. I mean this functionality is too specific and not worth to add more parameters in the function to control it. But there are other ways for solving this problem.

The percent values are just text annotation which can be replaced by user's own settings. In the new version of ComplexHeatmap, if you have a vector of percent values you have already calculated, you can added to oncoprint as:

```{r}
oncoPrint(..., show_pct = FALSE, left_annotation = HeatmapAnnotation(new_pct = your_pct))
```

Also for the barplots put on top and right of the oncoPrint, they are also normal barplot annotations. If you can calculate the frequency of mutations in genes and in samples (by removing the nor sequenced samples, maybe?), you can manually construct a barplot anntoation:

```{r}
oncoPrint(..., top_annotation = HeatmapAnnotation(cbar = anno_barplot(freq_for_samples)),
    right_annotation = rowAnnotation(rbar= anno_barplot(freq_for_genes)))
```

I am still developing the new version of the package and I am testing the new `oncoPrint()` function these days. You can have a try with the new version, but there might be errors.

**Comment by mcewenrk** [comment]
Thanks for clarifying - that's a great workaround so I can work with that.
Thanks!

**Comment by prinkessbambi** [comment]
> Hi jokergoo, we have dealt with the same issue (wildtype vs not covered), especially as sequencing panels are updated. We edit the percentages in adobe illustrator so that we can have percentages and a barplot on the right hand side for the past 2-3 years, but is there a way to address it in the oncoprint function?
