### ISSUE TITLE
Logarithmic scale for legend

### ISSUE THREAD

**Issue by johanneswerner** [jokergoo/ComplexHeatmap#215]
Is it possible to make a logarithmic scale for a heatmap legend (for the legend, not for the values). 

I am looking for something like this [here](https://stackoverflow.com/questions/51335318/).

![](https://i.stack.imgur.com/rD2gc.png)

**Comment by jokergoo** [comment]
I think there are two ways.

1. Color mapped to the normal scale, like what pheatmap does:

```{r}
set.seed(1)
mat <- matrix(rexp(200, rate=.001), ncol=20)

Heatmap(mat, heatmap_legend_param = 
	list(at = c(100, 1000, 4000),
	     legend_height = unit(4, "cm"))
)
```

![image](https://user-images.githubusercontent.com/449218/48368998-89ca3680-e6b5-11e8-9d19-e54a9bcac1b3.png)


2. Color mapped to log10 scale:

```{r}

Heatmap(log10(mat), heatmap_legend_param = 
	list(at = log10(c(10, 100, 1000, 4000)),
	     labels = c(10, 100, 1000, 4000),
		 legend_height = unit(4, "cm"))
)
```

![image](https://user-images.githubusercontent.com/449218/48369027-a5354180-e6b5-11e8-91d6-689c61641b47.png)

**Comment by johanneswerner** [comment]
wonderful, thank you!
