### ISSUE TITLE
Remove rectangle but keep y-axis anno_lines

### ISSUE THREAD

**Issue by Cumol** [jokergoo/ComplexHeatmap#217]
I was wondering how to remove the rectangle but keep (or alter the scale).

I tried using the original anno_loess that was posted in issue #161, but whenever I removed the rectangle, the scale/y-axis also vanished.

Is there a way around this?

**Comment by jokergoo** [comment]
What do you mean by "remove the rectangle"? Can you also attach an example here?

**Comment by Cumol** [comment]
Problem solved. Done by the option `border = FALSE`
