### ISSUE TITLE
Creating colored annotation from column names

### ISSUE THREAD

**Issue by CrosserK** [jokergoo/ComplexHeatmap#219]
Hi,
Is there a way to make an annotation that shows a specific color when the column has a specific name? I have severeal columns with the same name and some with other names, and would like to differ them from each other with the annotation.

Also, is there a way to reverse the order of rows?

Thanks in advance

**Comment by jokergoo** [comment]
Hi, with the new version of the package (>=1.99.0), you can set duplicated column/row names to the heatmap (by setting `column_labels` or `row_labels` arguments https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#dimension-names). If you want to set an annotation to distinguish these columns, you can create a vector show gives different values for the uniqe columns and duplicated columns (say, a variable called `duplicated` with values 1 and 0) and set it as a normal heatmap annotation.

```{r}
# you can also set it as bottom annotation
Heatmap(..., top_annotation = HeatmapAnnotation(..., duplicated = duplicated, col = ...))
```

Or you can give different colors to column names by setting `column_names_gp = gpar(col = ...)`.

If you do clustering on rows and want to reverse the order, you can first exact the row dendrogram and reverse the dendrogram, later remake the heatmap by the newly reversed dendrogram.

```{r}
ht = Heatmap(...)
ht = draw(ht)
row_dend = row_dend(ht)
row_dend = reverse(row_dend)
Heatmap(..., cluster_rows = row_dend, row_dend_reorder = FALSE)
```

**Comment by CrosserK** [comment]
Thanks for the detailed answer. I don't seem to be able to update past version 1.20 though.
I have R 3.5.1, is this a problem? I tried:
library(devtools)
install_github("jokergoo/ComplexHeatmap")

**Comment by CrosserK** [comment]
I have version 1.99.2 now and the problem has been fixed. 

I would like to ask about the binary distance method in your package. Can it be described as the Jaccard, Exact or Hamming method? Is there a way to use Jaccard as the distance method? 
Thanks in advance.
