### ISSUE TITLE
Legend left, centering plot

### ISSUE THREAD

**Issue by drewleonard** [jokergoo/ComplexHeatmap#220]
Hi, I love what I've been able to make with ComplexHeatmap, but am wondering whether I can make a plot with a legend on the left that either:
a) is the same height as the heatmap, aligned exactly or
b) is centered vertically with the heatmap

I saw this was an issue before and you marked it as completed, but I wasn't sure if the functionality is in the package.

Thanks so much!

**Comment by jokergoo** [comment]
I think you can use `heatmap_legend_side` in `draw()` function.

```
draw(Heatmap(...), heatmap_legend_side = "left")
```
