### ISSUE TITLE
Column Order Not Effective on Annotation

### ISSUE THREAD

**Issue by DarioS** [jokergoo/ComplexHeatmap#221]
I'm executing examples from the vignette titled Heatmap Annotations. Ordering the columns by age doesn't appear to work as intended. To make it easier to get the age values, the modifications to the example are

```
ageTable <- data.frame(age = sample(20, 10))
ha2 = HeatmapAnnotation(df = ageTable,
                        col = list(age = colorRamp2(c(0, 20), c("white", "red"))))
Heatmap(mat, top_annotation = ha1, bottom_annotation = ha2,
        column_order = order(ageTable$age), cluster_columns = FALSE)
```

Note that the heatmap column annotation is not ordered by increasing age, although the column names and heatmap itself are. Might it be a bug?

**Comment by jokergoo** [comment]
Hi, can you also provide code where you define `ha1`? If I only test with `ha2`, it is fine.

```{r}
ageTable <- data.frame(age = sample(20, 10))
ha2 = HeatmapAnnotation(df = ageTable,
                        col = list(age = colorRamp2(c(0, 20), c("white", "red"))))
Heatmap(mat, top_annotation = ha2,
        column_order = order(ageTable$age), cluster_columns = FALSE)
```

![image](https://user-images.githubusercontent.com/449218/49635708-e85aaa00-fa00-11e8-90db-c0a61b5cc34e.png)

**Comment by DarioS** [comment]
I realise that I made a mistake when subsetting the matrix and column order to be plotted as the heatmap because one column of the matrix had all NA values. The heatmap annotation had information about all samples. A small example demonstrating my mistake is:

```
library(ComplexHeatmap)
library(circlize)

patientTable <- data.frame(age = sample(20, 10),
                           gender = sample(c('M', 'F'), 10, replace = TRUE)
                           )
annoBar = HeatmapAnnotation(df = patientTable) # Annotation has 10 rows.
mat = matrix(rnorm(80, 2), 8, 10)
mat[, 3] = NA
Heatmap(mat[, -3], top_annotation = annoBar,
        column_order = order(patientTable$age[-3]),
	cluster_columns = FALSE)
# But, data matrix and column ordering have 9 elements, not 10.
# No error or warning is emitted, though.
```

Do you think that adding some input checking code would be useful to stop other users making the same mistake as me?

**Comment by jokergoo** [comment]
Yes! It is always good to give informative messages to users when they get errors. I have put quite a lot of efforts to do this, but there are still quite a lot of other conditions that I have not considered. For example here, I have never expected there are NA values in `column_order`. 

And thanks for reporting this problem and I will check `column_order` add messages if the format of `column_order` is invalid.

**Comment by DarioS** [comment]
None of the inputs to `Heatmap` contain `NA` in the previous example. The problem is simply that the annotation table contains one more row than the number of columns of the matrix and the number of elements in the ordering vector. All three inputs do not have any missing values when the subsetting is done as above.

**Comment by jokergoo** [comment]
Ah, what version of ComplexHeatmap are you using? In the newest version, I have already checked this consistency between annotations and the matrix (but I haven't checked the length of `column_order`).

**Comment by DarioS** [comment]
Version 1.20.0, the Release variety.

**Comment by jokergoo** [comment]
You might have a try on the newest version of this package. 

```{r}
library(devtools)
install_github("jokergoo/ComplexHeamtap")
```

There are some changes and improments compared to the old versions.

**Comment by DarioS** [comment]
Indeed, the development version provides a clear error message about the user-made mistake which I described.
