### ISSUE TITLE
Define shape function error

### ISSUE THREAD

**Issue by dd427** [jokergoo/ComplexHeatmap#222]
I am trying to generate an OncoPrint but continuously have error for shape function, as following 

> oncoPrint(mat = matd, alter_fun = alter_fun, get_type = function(x) strsplit(x, ",") [[1]], col = col)
Error in oncoPrint(mat = matd, alter_fun = alter_fun, get_type = function(x) strsplit(x,  : 
  You should define shape function for:  HETLOSS,  Nonsense,  Inframe_Del,  GAIN

I have already define these alterations in the alter_fun but this error is still pleasant. I think these are for sample with multiple mutations for one gene. 

I would really appreciate any help. Thank you.

**Comment by jokergoo** [comment]
Can you attach e.g. the first several rows of `matd` and how you define `alter_fun`?

**Comment by jokergoo** [comment]
The way how `get_type` is defined (`get_type = function(x) strsplit(x, ",") [[1]]`) actually means the separator in the `matd` is `,`, while in your `matd`, it is separated by `|`. You need to modify `get_type` to `get_type = function(x) strsplit(x, "|") [[1]]`.

In the ongoing new version, I am trying to automatically recognize the separator in the matrix if the separator is a simple character (#226), so users won't be confused by the `get_type` argument.

**Comment by dd427** [comment]
I change (get_type = function(x) strsplit(x, ",") [[1]]) to (get_type = function(x) strsplit(x, "|") [[1]]). However, now I am asked to define the shape function for entries with multiple variants for one gene. I really appreciate your help on this.

**Comment by jokergoo** [comment]
For the data your have:

```
Sample | SMARCB1 | SMARCE1 | TP53 | SMARCA4 | ARID1B | ARID1A | PBRM1
1 | Frameshift, HETLOSS | NA | NA | NA | NA | NA | NA
2 | NA | NA | NA | NA | NA | NA | NA
3 | NA | NA | NA | NA | NA | NA | NA
4 | Missense | NA | NA | NA | NA | NA | NA
5 | HOMDEL | NA | NA | NA | NA | NA | NA
6 | NA | GAIN | GAIN | HETLOSS | GAIN | NA | NA
```

you need to set `|` as separator when you read the data.

```{r}
mat = read.table(..., sep = "|")
```

I can see the rows are samples and columns are genes, which means you need to transpose your matrix:

```{r}
mat = t(mat)
head(mat)
```

For each element in the matrix, to get the individual alteration types, you need to set `,` as separator,
also I removed the alterations which are NAs.

```{r}
oncoPrint(mat, ..., get_type = function(x) {
    x = gsub("\s", "", strsplit(x, ",\\s*")[[1]]
    x[x != "NA"]
})
```
