### ISSUE TITLE
How to adjust heigth in anno_barplot function?

### ISSUE THREAD

**Issue by Tim0thy1** [jokergoo/ComplexHeatmap#223]
Hi, 
My package version is 1.20.0 .  And how to adjust  the height of barplot annotation ?

I can't find the argument  in ?anno_barplot

Arguments:

       x: a vector of numeric values. If the value is a matrix, columns
          of the matrix will be represented as stacked barplots. Note
          for stacked barplots, each row in the matrix should only
          contain values with same sign (either all positive or all
          negative).

baseline: baseline for bars. The value should be "min" or "max", or a
          numeric value. It is enforced to be zero for stacked
          barplots.

   which: is the annotation a column annotation or a row annotation?

  border: whether show border of the annotation compoment

bar_width: relative width of the bars, should less than one

      gp: graphic parameters. If it is the stacked barplots, the length
          of the graphic parameter should be same as the number of
          stacks.

    ylim: data ranges.

    axis: whether add axis

axis_side: if it is placed as column annotation, value can only be
          "left" or "right". If it is placed as row annotation, value
          can only be "bottom" or "top".

 axis_gp: graphic parameters for axis

axis_direction: if the annotation is row annotation, should the axis be
          from left to right (default) or follow the reversed
          direction?

     ...: for future use.

**Comment by Tim0thy1** [comment]
There a example  in your "ComplexHeatmap Complete Reference" , but it's work in my code..

![image](https://user-images.githubusercontent.com/37064389/49684007-563dc900-fb08-11e8-98cd-759427fc548a.png)

**Comment by Tim0thy1** [comment]
I find this right now. 
                                          annotation_height = unit(1.5, "cm")  
It can solve my problem.

**Comment by jokergoo** [comment]
The way in the second post (by setting `height` in `anno_barplot()` only works in the version >= 1.99.0, but in the both old and new versions, you can still use `annotation_height` to set (if you only have one annotation in the `HeatmapAnnotation` object.

**Comment by Tim0thy1** [comment]
Thank you. I will update my package.
