### ISSUE TITLE
Putting column annotation below Column Names in heatmap

### ISSUE THREAD

**Issue by JauntyJJS** [jokergoo/ComplexHeatmap#224]
I apologize in advanced for asking this naive question but may I ask how do I put the column annotation below the column names.

In the older version 1.20.0, I did

```{r}
p3 <- Heatmap(heatmap_Proband$heatmap, bottom_annotation = ha_column,)
Together with three other heatmap and one row annotation

ht_list = draw(ha_row + p1 + p2 + p3, main_heatmap = "p1", gap = unit(c(1, 3, 3), "mm"), padding = unit(c(15, 2, 2, 2), "mm"), show_annotation_legend = FALSE)
```
It give me this 

![image](https://user-images.githubusercontent.com/9066508/49683998-360e0a00-fb08-11e8-857c-16eb59db394e.png)

Now in the 1.99.3 version

```{r}
draw(ha_row + p1 + p2 + p3, main_heatmap = "p1", auto_adjust = FALSE, gap = unit(c(1, 3, 3), "mm"), padding = unit(c(15, 2, 2, 2), "mm"), show_annotation_legend = FALSE)
```
Now give me

![image](https://user-images.githubusercontent.com/9066508/49684024-9dc45500-fb08-11e8-84ba-4c2f28dcdddc.png)

I appreciate the treatment title added but now the A and B are overlapping with the dates (heatmap column names).
I have to put the annotation at the bottom because the actual name of treatment A and B is very long and have inconsistent length unlike the dates. 

Is there a way to switch the two with this new version ?

Many thanks.

Regards,
Jeremy

**Comment by JauntyJJS** [comment]
I somehow managed to do the following

ha_column = columnAnnotation(
                   Date = anno_text(colnames(heatmap_Proband$heatmap), rot = 90, gp = gpar(fontsize = 7)),
                   df = data.frame(Treatment = heatmap_Proband$colAnnot),
                   col = list(Treatment = col_annot_col),
                   text = anno_text(heatmap_Proband$colAnnot, rot = 45, just = "right", location = unit(1, "mm"), gp = gpar(fontsize = 10))
                   )

and set show_column_names = FALSE in the Heatmap function

![image](https://user-images.githubusercontent.com/9066508/49684601-d8ca8680-fb10-11e8-98e1-d07c2ab0e97d.png)

May I know how do I increase the white space between the dates and the colorbar ?

**Comment by JauntyJJS** [comment]
Not sure if this is the best way to do things but I added three spaces to Date

```{r}
ha_column = columnAnnotation(
                   gpar(fontsize = 7)),
                   Date = anno_text(paste0("   ", colnames(heatmap_Proband$heatmap)), rot = 90, gp = gpar(fontsize = 7)),
                   df = data.frame(Treatment = heatmap_Proband$colAnnot),
                   col = list(Treatment = col_annot_col),
                   text = anno_text(heatmap_Proband$colAnnot, rot = 45, just = "right", location = unit(1, "mm"), gp = gpar(fontsize = 10))
                   )
```
which gives the following

![image](https://user-images.githubusercontent.com/9066508/49706999-3ae7d080-fc64-11e8-90af-d96c46a884bd.png)

**Comment by jokergoo** [comment]
Hi, what you did is in the correct way :)

To increase the space between the first (the date strings) and the second annotation (the treatment), you can also use `gap` in `HeatmapAnnotation()` function:

```
ha_column = columnAnnotation(
                   gpar(fontsize = 7)),
                   Date = anno_text(colnames(heatmap_Proband$heatmap), rot = 90, gp = gpar(fontsize = 7)),
                   df = data.frame(Treatment = heatmap_Proband$colAnnot),
                   col = list(Treatment = col_annot_col),
                   text = anno_text(heatmap_Proband$colAnnot, rot = 45, just = "right", location = unit(1, "mm"), gp = gpar(fontsize = 10)),
                   gap = unit(c(3, 1), "mm")
                   )
```
