### ISSUE TITLE
Column order error

### ISSUE THREAD

**Issue by dd427** [jokergoo/ComplexHeatmap#229]
Hello, I am hoping to get some help with column_order. I am using a list of sorted sample names to order the column. However, I am encountering the error 

Error in arr[i, j, ] : subscript out of bounds

I have checked and the number of samples is the same for the alteration matrix and the sample order list. I would really appreciate any help.

Thank you.

**Comment by jokergoo** [comment]
Can you attach the complete code?

**Comment by dd427** [comment]
data = as.data.frame(data)
library(splitstackshape)
df_s <- getanID(data, c("Gene", "Sample"))
df_r <- reshape(df_s, idvar = c("Sample", ".id"), timevar = c("Gene"), direction = "wide", drop = NULL)
df_r1 <- aggregate(df_r, by = list(df_r$Sample), function(x) toString(unique(x)))
#remove extraneous columns (.id, group, NA)
df_r1 = df_r1[, -c(1,3,5)]

df_r2 <- data.frame(lapply(df_r1, function(x) (gsub(",.(NA)|NA", "", x))))
colnames(df_r2) <- c("Sample", "SMARCB1", "SMARCA4", "SMARCE1", "TP53", "ARID1B", "ARID1A", "PBRM1")
#merge clinical data
dataset <- merge.data.frame(df_r2, ini1, by.x = "Sample")

mat = dataset
rownames(mat) = mat[ ,1]
mat = mat[ ,-1]
mat = t(as.matrix(mat, sep = "|"))

library(ComplexHeatmap)

alter_fun = list(
  background = function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), gp = gpar(fill = "#CCCCCC", col = NA))
  },
  "HETLOSS" = function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), gp = gpar(fill = "deepskyblue", col = NA))
  },
  "HOMDEL" = function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), gp = gpar(fill = "dodgerblue4", col = NA))
  },
  "GAIN" = function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), gp = gpar(fill = "firebrick1", col = NA))
  },
  "Missense" = function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h*0.33, gp = gpar(fill = "forestgreen", col = NA))
  },
  "Inframe_Del" = function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h*0.33, gp = gpar(fill = "darkslateblue", col = NA))
  },
  "Inframe_Ins" = function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h*0.33, gp = gpar(fill = "darkorange", col = NA))
  },
  "Nonsense" = function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h*0.33, gp = gpar(fill = "gray0", col = NA))
  },
  "Frameshift" = function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h*0.33, gp = gpar(fill = "purple", col = NA))
  },
  "Splice_Acceptor" = function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h*0.33, gp = gpar(fill = "gold", col = NA))
  },
  "Y" = function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.4, "mm"), gp = gpar(fill = "gray48" , col = NA))
  },
  "P" = function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.4, "mm"), gp = gpar(fill = "orange", col = NA))
  },
  "N" = function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.4, "mm"), gp = gpar(fill = "steelblue", col = NA))
  }
)
col <- c("HETLOSS" = "deepskyblue", "HOMDEL" = "dodgerblue4", 
         "GAIN" = "firebrick1", "Missense" = "forestgreen", 
         "Inframe_Del" = "darkslateblue", "Inframe_Ins"= "darkorange", 
         "Nonsense" = "gray0", "Frameshift" = "purple", 
         "Splice_Acceptor"= "gold", "Y" = "gray48", "P" = "orange", "N" = "steelblue")

#Define column order 
sample_order <- as.array(read.csv("C:/Users/dd427/Desktop/sample_order (ini1).csv", header = FALSE))
class(sample_order) <- append(class(sample_order), "character")

TMB <- as.data.frame(read_excel("C:/Users/dd427/Desktop/clinical data.xlsx", sheet = "TMB"))
TMB_anno = TMB
rownames(TMB_anno) = TMB_anno[,1]
TMB_anno = TMB_anno[,-1, drop = FALSE]

ComplexHeatmap::oncoPrint(mat, get_type = function(x) strsplit(x, ",\\s*")[[1]],
          alter_fun = alter_fun, col = col,
          top_annotation = HeatmapAnnotation(TMB_anno, show_legend = TRUE, show_annotation_name = TRUE, which = "column"),
          column_order = sample_order[,1], 
          column_title = "OncoPrint for SWI-SNF",
          heatmap_legend_param = list(
          title = "Alternations", 
          at = c("HETLOSS", "HOMDEL", "GAIN", 
                   "Missense","Inframe_Del", "Inframe_Ins", 
                   "Nonsense", "Frameshift","Splice_Acceptor"), 
          labels = c("Single copy deletion", "Two copy deletion", "Gain", 
                     "Missense", "Inframe Deletion", "Inframe Insertion", 
                     "Nonsense", "Frameshift", "Splice site alteration")))

**Comment by jokergoo** [comment]
Your code is a little bit long. It is difficult just by reading it. Can you also attach the input data files?

**Comment by dd427** [comment]
Thank you so much. I was able to figure out the discordant between the order list and the matrix and solve the issue. I really appreciate your help.
