### ISSUE TITLE
Order rows within a cluster (e.g. based on TSS dist)

### ISSUE THREAD

**Issue by PocketChangeJ** [jokergoo/ComplexHeatmap#231]
Hi,
Thank you so much for this amazing package! I'm slowly learning my way around, but hands down, this is my favorite for putting heatmaps together!

I'm wondering if there is a way to custom-order rows within a slice? Specifically, I have 2 heatmaps: one is gene expression data split into 4 clusters based on kmean, and second represents a TSS distance of related ChIP data. I'd like to sort genes inside the clusters based on assigned TSS distance value? Is this something doable? 
Thanks again!

**Comment by jokergoo** [comment]
You need to manually construct this object and later assign to `row_order`. You can calculate this customized order just by `order()` function:

```{r}
row_order = order(you-kmeans-classes, the-tss-distance)
```

It will first sort by the kmeans class IDs, for the elements with a same class ID, it sorts by the TSS distance as a secondary sorting.

**Comment by PocketChangeJ** [comment]
great, let me try that. thank you!!
