### ISSUE TITLE
Oncoprint: Error in HeatmapAnnotation(..., which = "row") :    annotations should have names.

### ISSUE THREAD

**Issue by YonkoBigMom** [jokergoo/ComplexHeatmap#233]
Hi,

I am trying to follow exactly the tutorial at https://bioconductor.org/packages/3.7/bioc/vignettes/ComplexHeatmap/inst/doc/s8.oncoprint.html

```
mat = read.table(textConnection(
",s1,s2,s3
g1,snv;indel,snv,indel
g2,,snv;indel,snv
g3,snv,,indel;snv"), row.names = 1, header = TRUE, sep = ",", stringsAsFactors = FALSE)
mat = as.matrix(mat)

library(ComplexHeatmap)
col = c(snv = "red", indel = "blue")
oncoPrint(mat, get_type = function(x) strsplit(x, ";")[[1]],
    alter_fun = list(
        snv = function(x, y, w, h) grid.rect(x, y, w*0.9, h*0.9, gp = gpar(fill = col["snv"], col = NA)),
        indel = function(x, y, w, h) grid.rect(x, y, w*0.9, h*0.4, gp = gpar(fill = col["indel"], col = NA))
    ), col = col)
```

Then I received the error

Error in HeatmapAnnotation(..., which = "row") : 
  annotations should have names.

Would you please let me know how to fix this?

Thanks

**Comment by jokergoo** [comment]
Hi, I don't have the error with the code. Can you upgrade the package?

```
library(devtools)
install_github("jokergoo/ComplexHeatmap)
```

**Comment by YonkoBigMom** [comment]
Hi, thanks for following up. Actually the error happened after I updated the packages. Oncoprint worked just fine in older version of ComplexHeatmap. .

**Comment by jokergoo** [comment]
What is your `sessionInfo()`? I ran the code under version 1.99.5 and there is no error.
