### ISSUE TITLE
complexheatmap oncoprint set column_order according to annotation information firstly, then according to default order

### ISSUE THREAD

**Issue by WortJohn** [jokergoo/ComplexHeatmap#234]
@jokergoo 
I have a need that i want to order the the figure plotted by oncoPrint , firstly according to one annotation information which is factor level, then according to the default value when i use the function **oncoPrint**.  Whether the **column_order** argument in function **oncoprint** can come true it or not ?

**Comment by jokergoo** [comment]
Can you try:

```
oncoPrint(..., column_split = your_factor)
```

**Comment by WortJohn** [comment]
There is not "column_split" argument in oncoPrint function.I find "split" argument ,but it only splits row. 

> split : a vector or a data frame by which the rows are split. But if cluster_rows is a
clustering object, split can be a single number indicating rows are to be split
according to the split on the tree

**Comment by jokergoo** [comment]
Are you using version >= 1.99.0?

**Comment by WortJohn** [comment]
Firstly, thanks for your advice. I update ComplexHeatmap from 1.20.0 to 1.99.5.  I try to use "row_split" argument  in "draw" function and it works , but it doesn't work when i try to "column_split". Following is my code.
> oncocol = c("Substitution/Indel" = "#228B22",
            "Gene Amplification" = "#EE0000",
            "Gene Homozygous Deletion" = "#0000EE",
            "Fusion/Rearrangement" = "#EEEE00",
            "Truncation" = "#8E388E")
> alter_fun = function(x,y,w,h,v){
  n=sum(v)
  h = h*0.8
  w = w*0.8
  grid.rect(x, y, w, h, gp = gpar(fill = "grey90", col = NA))
  if(n) grid.rect(x,y-h*0.5+1:n/n*h, w, 1/n*h, gp=gpar(fill=oncocol[names(which(v))], col=NA), just = "top")
}
> onco <- oncoPrint(mutant, get_type = function(x) unique(strsplit(x, ";")[[1]]),
                  alter_fun = alter_fun, col = oncocol,
                  heatmap_legend_param = list(title='', nrow=5, labels_gp=gpar(fontsize=7, fontface='bold')),
                  column_names_gp = gpar(fontsize = 6, fontface='bold'),
                  row_names_gp = gpar(fontsize = 7, fontface='bold'),
                  row_names_side='right',
                  show_pct = T,
                  pct_gp = gpar(fontsize=7, fontface='bold'))
> draw(onco , column_split = sample(c("a", "b"), ncol(mutant), replace = TRUE))

**Comment by jokergoo** [comment]
Hi, that was a bug in the package that I forgot to pass `column_split` and `row_split` to downstream functions.

Please update the package by `devtools::install_github("jokergoo/ComplexHeamtap")` or download it first and install it locally.

Note, you cannot put `column_split` in `draw()`, while you should put `column_split` in `oncoPrint()` and so as `row_split`.

```
oncoPrint(..., row_split = , column_split = )
```

If you really want to use `draw()`, in your example, `onco` contains one heatmap and it is treated as a horizontal heatmap list (with only one heatmap), and for horizontal heatmap list, all configurations for columns are ignored (only the row configuration is used). Similarly, all the column configuration set in `draw()` are only used for vertical heatmap list. If you want to set `column_split` in `draw()`, you need to explicitly convert the single heatmap to a vertical heatmap list:

```
draw(onco %v% NULL, column_split = ...)
```

Following is an example to prove `column_split` works:

![image](https://user-images.githubusercontent.com/449218/51837444-aa447d00-2303-11e9-9320-cdae327db627.png)

**Comment by WortJohn** [comment]
@jokergoo Thank you very much. I have solved my problem according to your advice. Thanks again.
