### ISSUE TITLE
Passing Jaccard distance method to ComplexHeatmap

### ISSUE THREAD

**Issue by CrosserK** [jokergoo/ComplexHeatmap#236]
Hi there,
I have a hard time understanding how to pass this method to your program.  I've only recenlty learned that the Jaccard distance is given by 
![image](https://user-images.githubusercontent.com/45485501/51472496-e57e0380-1d79-11e9-8c72-ef7a54ba7b23.png)
Where ![image](https://user-images.githubusercontent.com/45485501/51472930-3e01d080-1d7b-11e9-9e71-908e29e21974.png)  is intersection and ![image](https://user-images.githubusercontent.com/45485501/51472953-4b1ebf80-1d7b-11e9-9483-ab33c9714f30.png) is union. Getting from this information to using it, as the distance method on a matrix of 1's and 0's is a problem for me and Im also not familiar with generating a clustering/distance object. I mostly know how to use your program, but what im missing is what to put into clustering_distance_columns/clustering_distance_rows, to use a Jaccard distance method. 

Is it possible you can show me how to do it, if its not too complicated?
Thanks in advance. 
Kasper

**Comment by jokergoo** [comment]
Hi, you can find how to define a proper distance function for generating heatmaps from following link:

https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#distance-methods

For Jaccard distance, you can define as:

```
jaccard_dist = function(x, y) 1 - length(intersect(x, y))/length(union(x, y))
```

then send to `clustering_distance_rows`/`clustering_distance_columns` arguments.

For you binary matrix, I would guess x![image](https://user-images.githubusercontent.com/449218/51474750-84a5f980-1d80-11e9-86f5-38ca1e65f730.png)y is the the number of data points that are both 1 in the two vectors, if so, you can define the distance as:

```
jaccard_dist = function(x, y) 1 - sum(x & y)/sum(x | y)
```

**Comment by CrosserK** [comment]
Thank you very much for the quick reply.

Using "jaccard_dist = function(x, y) 1 - length(intersect(x, y))/length(union(x, y))", seems to work, but the tree is looking weird. Is this because the function is not part of your package? Im using ComplexHeatmap_1.99.3.
![image](https://user-images.githubusercontent.com/45485501/51477393-a5724d00-1d88-11e9-90c6-14d8cc108c85.png)

As for using
jaccard_dist = function(x, y) 1 - sum(x & y)/sum(x | y)
I get the error message: Error in hclust(get_dist(submat, distance), method = method) : 
  NA/NaN/Inf in foreign function call (arg 11)
 
The full code used is (the input is a binary matrix):

ha <- Heatmap(t_GliomDataInput_noMGMTmet, 
        name = "Match",
        col = c("grey","blue"), 
        rect_gp = gpar(col = "white", lwd=1.5), 
        cluster_rows = T,
        cluster_columns = T,
        clustering_distance_columns = jaccard_dist,
        clustering_distance_rows = jaccard_dist,
        clustering_method_columns = "ward.D",
        clustering_method_rows = "ward.D",
        row_dend_reorder = T,
        column_dend_reorder = T,
        row_dend_width = unit(20,"mm"),
        column_dend_height = unit(20,"mm"),
        width = unit(220,"mm"), 
        height = unit(120,"mm"),
        column_names_gp = gpar(fontsize = 6),
        top_annotation = HeatmapAnnotation(Histology = Hist_names,
          col = list(Histology = 
                   c("AA III" = "#FF0000",
                     "AA" = "#8B0000",
                     "PXA" = "#FF7F50",
                     "PA" = "#2F4F4F", 
                     "OA" = "#FFE4B5", 
                     "O" = "#BDB76B",
                     "NB" = "#FFD700", 
                     "MM" = "#7CFC00",
                     "MB" = "#32CD32",
                     "M" = "#008000",
                     "GC" = "#006400",
                     "GB" = "#FFFF00",
                     "EP" = "#556B2F",
                     "DA II" = "#7B68EE",
                     "DA" = "#00FFFF",
                     "BG" = "#FF00FF",
                     "AT/RT" = "#20B2AA",
                     "AO" = "#FFFAFA",
                     "AE" = "#0000FF",
                     "URF" = "#7B68EE")),
          border = F #gp = gpar(col = "black")
          )
        )

**Comment by jokergoo** [comment]
I think you might have NA values in the matrix. Can you send me all the objects you use to make the heatmap?

**Comment by jokergoo** [comment]
How about this version of `jaccard_dist`?

```
jaccard_dist = function(x, y) {
	s = 1 - sum(x & y)/sum(x | y)
	if(is.na(s)) {
		return(1)
	} else {
		return(s)
	}
}
```

**Comment by CrosserK** [comment]
Thanks you, that seems to be a great solution. 
I'm new to programming (and distance methods), so just asking to be sure: you are returning a 1, when the function detects an NA value. Does this result in the jaccard distance being 1, meaning no match? Does it make a difference in the distance when the NA value (should be 0) is compared to an equal value (of 0) vs an unequal (of 1)? 
Im not sure where the NA value is happening, though. There should be only 1's and 0's in the dataset. Is the function grabbing the row and coloumn names from the dataframe?

**Comment by jokergoo** [comment]
In the old definition of the distance:

```
1 - sum(x & y)/sum(x | y)
```

It is possible that `sum(x|y)` is zero, which results in a distance with a value of `1 - 0/0`, which gives `NA` or `NaN`. On the other hand, the maximal value of `1 - sum(x & y)/sum(x | y)` is 1. So when the vaule is NA, we enforce it to the maximal distance which is 1.

**Comment by CrosserK** [comment]
Makes sense. Thank you.

**Comment by krassowski** [comment]
I think that this function should be:

```R
jaccard_dist = function(x, y) {
    s = 1 - sum(x & y, na.rm=T)/sum(x | y, na.rm=T)
    if (is.na(s)) {
        return(1)
    } else {
        return(s)
    }
}
```

And it is actually it is not needed, you can just pass 'binary' since R has Jaccard distance built-in in `dist()`:

```R
    clustering_distance_columns = 'binary',
    clustering_distance_rows = 'binary',
```

Just in case if someone Googles this.
