### ISSUE TITLE
Simplify dendrogram

### ISSUE THREAD

**Issue by johanneswerner** [jokergoo/ComplexHeatmap#239]
Is it possible to _simplify_ the dendrograms if there are too many columns/rows and to cut it at a certain level?

I am searching for something like this: https://stackoverflow.com/a/7404518/5013084

**Comment by jokergoo** [comment]
Check the last heatmap in following section:

https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#clustering-methods

Example code is:

```r
group = kmeans(t(mat), centers = 3)$cluster # you can also use cutree to get groups
Heatmap(mat, name = "mat", cluster_columns = cluster_within_group(mat, group))
```

![image](https://user-images.githubusercontent.com/449218/51975631-07b30800-2483-11e9-9178-621c8dc3dfb9.png)

**Comment by johanneswerner** [comment]
Oh perfect. 

```R
cols_group = kmeans(t(mat), centers = 2)$cluster # you can also use cutree to get groups
rows_group = kmeans(mat, centers = 4)$cluster # you can also use cutree to get groups

Heatmap(mat,
               name = "mat",
               cluster_columns = cluster_within_group(mat, cols_group),
               cluster_rows = cluster_within_group(t(mat), rows_group),
               row_dend_reorder = TRUE,
               column_dend_reorder = TRUE)
```

Unfortunately, this leaves me with another problem. I applied reordering of the dendrograms before, but this gets lost with `cluster_within_groups`. Do you have any idea how to use the grouping and apply reordering of the dendrograms?

**Comment by jokergoo** [comment]
Can you send me `mat` or that I can see the problem?

**Comment by johanneswerner** [comment]
I cannot reproduce the issue. I restarted my session and now it looks as expected. Thank you.
