### ISSUE TITLE
how to defined types to visualize multiple mutation hit on one genes in one sample, like this plot ? 

### ISSUE THREAD

**Issue by ChengYunazhi** [jokergoo/ComplexHeatmap#240]
Hi @jokergoo , I found this oncoplot, which has strange types to visualize multiple types. You can see some hollow structures and some overlapping mutation types. These overlapping mutation types are not covered by each other. 
Thanks!!

<img width="1054" alt="2019-01-30 6 01 20" src="https://user-images.githubusercontent.com/13846735/51974483-fab20b00-24ba-11e9-91d3-3358e5f1017e.png">

**Comment by jokergoo** [comment]
Hi, you need to define a proper `alter_fun`,e.g. for a gene has mutation types `mut1` and `mut2` where `mut1` is a red grid and `mut2` is a diagonal line, you can define as:

```
alter_fun = list(
    mut1 = function(x, y, w, h) grid.rect(x, y, w, h, gp = gpar(fill = "red")),
    mut2 = function(x, y, w, h) grid.segmemnts(x-w*0.5, y - h*0.5, x+w * 0.5, y + h*0.5)
)
```

then the function of drawing `mut1` and `mut2` are both executed, which draws a red grid and a line.

You can check following link:

https://jokergoo.github.io/ComplexHeatmap-reference/book/oncoprint.html#define-the-alter-fun

**Comment by jokergoo** [comment]
If you have difficulty with making it, you can send me the data and I can help you.

**Comment by ChengYunazhi** [comment]
these types seem as combination of simple type, which can be plot by grid.* function. how to combine in oncoprint, I defined two function for one type (for example, indel=function1, indel=function2), oncoprint only read the first. 

<img width="1098" alt="wechat09fb43e527ece40b56fca4889d8f6ee6" src="https://user-images.githubusercontent.com/13846735/51981747-f7c11580-24ce-11e9-8909-4a44a5dc096d.png">

**Comment by jokergoo** [comment]
I also added a new section in vignette which might be helpful for you:

https://jokergoo.github.io/ComplexHeatmap-reference/book/oncoprint.html#complex-alteration-types

**Comment by ChengYunazhi** [comment]
Thank you, it is very useful to us, we have drawn the oncoprint we want.
