### ISSUE TITLE
Creating a list of heatmaps using a for loop

### ISSUE THREAD

**Issue by KatrionaGoldmann** [jokergoo/ComplexHeatmap#243]
Hey, I am trying to follow [this](https://jokergoo.github.io/ComplexHeatmap-reference/book/a-list-of-heatmaps.html) to create a list of heat maps in a for loop:

```
df1 <- data.frame(replicate(10,sample(0:1,1000,rep=TRUE)))
df2 <- data.frame(replicate(10,sample(0:1,1000,rep=TRUE)))
df3 <- data.frame(replicate(10,sample(0:1,1000,rep=TRUE)))

df.list <- list(df1, df2, df3)

ht_list = NULL  ## Heatmap(...) + NULL gives you a HeatmapList object
for(s in 1:3) {
  ht_list = ht_list + ComplexHeatmap::Heatmap(df.list[[s]])
}
```
 but I get the error `Error in ht_list + ComplexHeatmap::Heatmap(df.list[[s]]) : 
  non-numeric argument to binary operator`. I guess I am appending to this heatmap list object incorrectly. 

The heat maps work fine on their own:

`ComplexHeatmap::Heatmap(df1)`

any ideas?

**Comment by KatrionaGoldmann** [comment]
seem to have fixed it by reinstalling the package !

**Comment by jokergoo** [comment]
Yes, `NULL + Heatmap(...) + ...` was introduced in recent versions.
