### ISSUE TITLE
column_split usage

### ISSUE THREAD

**Issue by Rashesh7** [jokergoo/ComplexHeatmap#244]
Hi,

I want to split the columns unevenly. I have 34 samples and want to split it to 8-26 in the oncoPrint. I tried to search the wiki, but I am unable to find the proper usage for that. It always gives me the error 
that "the number of columns should be equal to the ncol of matirx" 

Also I am using, column_order and column)split both, so should I define a list of column orders since I am splitting the matrix? 

You help is much appreciated.

Thanks,
Rashesh

**Comment by jokergoo** [comment]
Hi, assume you have `n` columns in your oncoPrint, to split the columns, you need to provide:

 1. a categorical vector with length `n`, or
 2. a data frame with one or more categorical columns.

and give this variable to `column_split`.

**Comment by Rashesh7** [comment]
Awesome. Thank you!
Also will column_gap work for oncoprint, if I want to separate it more?

**Comment by jokergoo** [comment]
Yes, it works.

**Comment by Rashesh7** [comment]
Hi I am having couple of other issues.
1) Unable to change the column name size even after using "show_column_names=FALSE, column_names_gp = gpar(fontsize = 1),"

2) Bottom annotations are not showing up. When I add as 'bottom_annotation=ha' is does not show, but when I add the same as top annotation 'top_annotation=ha' it shows up. 

can you suggest what might be happening?  The command I am giving is

oncoPrint(mat,get_type = function(x) strsplit(x, ";")[[1]], alter_fun = alter_fun, col = col, row_names_side = "left", show_column_names=FALSE, column_names_gp = gpar(fontsize = 1), show_pct = FALSE, heatmap_legend_param=list(title ="Mutations", title_gp= gpar(fontsize = 6),labels_gp = gpar(fontsize = 4)), row_names_gp = gpar(fontsize = 3), pct_gp = gpar(fontsize = 0), row_title_gp= gpar(fontsize = 4), top_annotation = ha, bottom_annotation = ha)

**Comment by jokergoo** [comment]
Sorry I forgot to pass `column_names_gp` to `Heatmap()` internally. Now this bug is fixed. You can update the package from github.

**Comment by Rashesh7** [comment]
Thank you for the quick fix Zuguang. 

Did you get a chance to check about the bottom_annotation issue?

**Comment by jokergoo** [comment]
I think it is also fixed.

**Comment by Rashesh7** [comment]
Yup, it worked. Thank you for the quick responses.

**Comment by Rashesh7** [comment]
Hi @jokergoo ,

I am unable to change the height of the annotation using annotation_height. 

I have a bottom_annotation of 6 simple annotations. I am using annotation_height = unit(c(2,2,2,2,2,2), "mm") to set their height, but it is not changing. 

Can you please check that?

Thanks.

**Comment by Rashesh7** [comment]
Hi,
I was just wondering if you go a chance to look into this. Or is there another way of modifying the annotation_height?

Thank you.

**Comment by jokergoo** [comment]
In the new version, you need to set

```
HeatmapAnnotation(...,  anno_simple_size = unit(2, "mm"))
```

or

```
HeatmapAnnotation(...,  height = unit(2*6, "mm"))
```

See https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html#multiple-annotations

**Comment by Rashesh7** [comment]
Oh, I had tried height = unit(2*6, "mm") but it also did not work for me. Let me try anno_simple_size = unit(2, "mm").

Thanks

**Comment by jokergoo** [comment]
Can you show me how to set in `HeatmapAnnotation()`?

**Comment by Rashesh7** [comment]
I am reading the CSV file and setting up each annotation info.

`annotate = read.csv("Additional_info.cgc.csv", row.names = 1, sep=",", header = TRUE, stringsAsFactors = FALSE)
annotate=annotate[columnorder,]
site =annotate[, "Site"]
Hist = annotate[,"Histology"]
AR = annotate[,"AR_enhancer"]
Purity = annotate[,"Purity"]
BRCA = annotate[,"BRCA1.2_Germ"]
ATM = annotate[,"ATM_Germ"]`

Then I am using the following to generate the bottom_annotation.
`ha = HeatmapAnnotation(AR=AR, BRCA=BRCA, ATM=ATM, Purity=Purity, Hist=Hist, site=site, 
col = list(
ATM=col2, 
BRCA=col2,
AR=c("DEL"="blue3", "DUP"="red2"), 
site= sitecolor, 
Purity=purity_col_fun,
Hist=c("Adenocarcinoma"="deeppink", "NEPC"="yellow2")), na_col = "white", height = unit(12, "mm"), show_annotation_name=FALSE,
annotation_legend_param = list(ATM = list(title = "ATM Germline", title_gp = gpar(fontsize = 5), labels_gp = gpar(fontsize = 4)), BRCA = list(title = "BRCA Germline", title_gp = gpar(fontsize = 5), labels_gp = gpar(fontsize = 4)), AR = list(title = "AR Enhancer", title_gp = gpar(fontsize = 5), labels_gp = gpar(fontsize = 4)), Purity = list(title = "Purity", title_gp = gpar(fontsize = 5), labels_gp = gpar(fontsize = 4)), site = list(title = "Site", title_gp = gpar(fontsize = 5), labels_gp = gpar(fontsize = 4)), Hist = list(title = "Histology", title_gp = gpar(fontsize = 5), labels_gp = gpar(fontsize = 4))))
`

**Comment by jokergoo** [comment]
You are right, setting `height` does not work. The example in the vignette is wrong. I will try to fix it.

**Comment by jokergoo** [comment]
I've checked, currently only following works:

```
ht_opt$anno_simple_size = unit(2, "mm")
HeatmapAnnotation(...) # without height or annotation_height
```

**Comment by jokergoo** [comment]
Hi, I think I have fixed this bug. You can see all the examples in https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html#multiple-annotations have correct size now. Now you can use either `height` or `annotation_height` in `HeatmapAnnotation()`.

**Comment by Rashesh7** [comment]
Cool. Thank you again for the quick support as always. I will give it a try.
