### ISSUE TITLE
Relative position of row names with respect to row annotation - behaviour different in new version

### ISSUE THREAD

**Issue by eghorani** [jokergoo/ComplexHeatmap#247]
Hi Jokergoo,

Thank you for this immensely important package!

using the Heatmap() function in version 1.99.5 versus 1.17.1, I'm running into difficulties setting the relative position of the row names with respect to the row annotation. The aim is for both to be on the right of the heatmap, according to the following order from left to right:..........heatmap.......row name.............annotation

In the old version, specifying the main heatmap and the annotation then printing them with (heatmap)+(annotation) worked:

mat = matrix(rnorm(80, 2), 8, 10)
mat = rbind(mat, matrix(rnorm(40, -2), 4, 10))
rownames(mat) = paste0("R", 1:12)
colnames(mat) = paste0("C", 1:10)

h1=Heatmap(mat)

df = data.frame(type = c(rep("a", 6), rep("b", 6)))

ha = HeatmapAnnotation(df = df, col = list(type = c("a" = "red", "b" = "blue")),
    which = "row", width = unit(1, "cm"))

h1+ha

In the new version, this now concatenates the 2 objects and deletes the row names.

Setting "right_annotation" in the call to Heatmap() keeps the row names but puts them to the right of the annotation:

Heatmap(mat,right_annotation = ha)

How do I switch the positions of the row annotation and the row names, keeping both on the same side of the heatmap?

Thanks very much!

Ehsan

**Comment by jokergoo** [comment]
Yes, I have changed the default layout a little bit. If you want to insert row names between heatmaps and row annotations, you can

1. set `auto_adjust = FALSE` in `draw()`: `draw(ht_list, ..., auto_adjust = FALSE)`, or
2. set row names as text annotation:

```r
Heatmap(...) + rowAnnotation(rn = anno_text(rownames(mat))) + ...
```

**Comment by eghorani** [comment]
Thanks for your quick reply! That's clear now.

You've explained auto_adjust very well in the reference book and I missed this.

It may be worth considering adding a bit of similarly good description to the draw-HeatmapList-method documentation called from within R. At the moment, the description for the argument auto_adjust reads "whether auto adjust". Perhaps something like "whether remove intervening row/column names when drawing a heatmap list" could be more informative.

Thanks again for this brilliant work

**Comment by jokergoo** [comment]
Thanks for your suggestion! I was too lazy to write that...

**Comment by eghorani** [comment]
“Lazy” – don’t make me laugh!

Keep up the good work!

Ehsan

**Comment by Caizhengwen123** [comment]
Hi Jokergoo,
I used the first method set auto_adjust = FALSE in draw(): draw(ht_list, ..., auto_adjust = FALSE), but the text annotation was still between heatmap and rownames, here is my code:
draw(Heatmap(level_1_data, show_row_names = TRUE, cluster_rows = FALSE, cluster_columns = FALSE, name = "Z-Score",width = unit(4, "cm"),left_annotation = c(ha_list3,ha_list2,ha_list1), right_annotation = text_annotation),heatmap_legend_list = list(lgd1,lgd2,lgd3), auto_adjust=FALSE)
wish for your help!
thanks a lot!
Zhengwen Cai
