### ISSUE TITLE
two custom legend with one heatmap

### ISSUE THREAD

**Issue by ChengYunazhi** [jokergoo/ComplexHeatmap#248]
Hi, I tried to add two legend for one heatmap, but the legends were overlap on heatmap, it seems no space for placing the legends, we want draw heatmap like this:

<img width="832" alt="wechatf52a4123b2dcf8aad69640ff00d76f99" src="https://user-images.githubusercontent.com/13846735/52345183-80076380-2a57-11e9-9866-24d5966d7f1b.png">

what we drawn here:

![rplot](https://user-images.githubusercontent.com/13846735/52344922-f5beff80-2a56-11e9-89df-a29f0ddeec68.png)

All the best!

**Comment by jokergoo** [comment]
Hi, you only have one heatmap, but why do you have three legends?

**Comment by jokergoo** [comment]
If you want to draw the legends like in the first plot,  you can

```{r}
lgd1= Legend(title = "Positively correlated genes", at=  c(0, 2, 4, 6, 8, 10), 
    col = pos_col_fun, direction = "horizontal")
lgd2= Legend(title = "Positively correlated genes", at=  c(0, 2, 4, 6, 8, 10), 
    col = neg_col_fun, direction = "horizontal")
ht = Heatmap(...)
draw(ht, heatmap_legend_list = list(lgd1, lgd2), heatmap_legend_side = "bottom")
```
