### ISSUE TITLE
Row_order - unused argument.

### ISSUE THREAD

**Issue by fjrossello** [jokergoo/ComplexHeatmap#25]
Hi,

I am trying to manually order rows in a heat map but when run this example:
*set.seed(123)*

*mat = cbind(rbind(matrix(rnorm(16, -1), 4), matrix(rnorm(32, 1), 8)),
            rbind(matrix(rnorm(24, 1), 4), matrix(rnorm(48, -1), 8)))*

*permute the rows and columns*
&mat = mat[sample(nrow(mat), nrow(mat)), sample(ncol(mat), ncol(mat))]*

*rownames(mat) = paste0("R", 1:12)*
*colnames(mat) = paste0("C", 1:10)*

*Heatmap(mat, name = "foo", cluster_rows = FALSE, cluster_columns = FALSE,*
   *row_order = 12:1, column_order = 10:1)*

I get the following message:

*unused arguments (row_order = 12:1, column_order = 10:1)*

I tried several things, such as modifying the row_order_list within a heat map object without success. 

Any ideas?

Thanks in advance,

Fernando

**Comment by jokergoo** [comment]
It works fine for me. I think maybe the version of the package you are using is a little bit old.

**Comment by fjrossello** [comment]
Great, thanks for your prompt reply. I could only replicate it by using the github versions, *i.e.*, by installing through github, of both ComplexHeatmap and circlize. 
As an observation, neither the bioconductor (ComplexHeatmap) nor the CRAN (circlize) versions seem to be updated and have full functionality.
In any case, great package, really useful to compare conditions side by side, such as chromatin accessibility, expression, *etc*. Thanks for the effort.

Cheers,

Fernando

**Comment by jokergoo** [comment]
Yes, the version in the release branch on BIoconductor is always a little bit outdated.
