### ISSUE TITLE
Height scale for the dendrograms

### ISSUE THREAD

**Issue by johanneswerner** [jokergoo/ComplexHeatmap#252]
How can I add the height scale to the dendrograms on the height map (this is what I mean with height scale: http://stat.sys.i.kyoto-u.ac.jp/prog/pvclust/fig/boston.png)?

**Comment by jokergoo** [comment]
You need to use `decorate_row_dend()` or `decorate_column_dend()` to add the axes. See following examples:

```r
m = matrix(rnorm(100), 10)

ht = Heatmap(m, name = "foo", 
	row_dend_width = unit(4, "cm"),
	column_dend_height = unit(4, "cm")
)
draw(ht, padding = unit(c(15, 2, 2, 2), "mm"))
decorate_column_dend("foo", {
	grid.yaxis()
})
decorate_row_dend("foo", {
	vp = current.viewport()
	xscale = vp$xscale
	grid.xaxis(at = xscale[2] - 0:5, label = 0:5)
})
```

Note for the left row dendrogram, the x-axis is from right to right, you need to self-define `at`
and `label` in `grid.xaxis()` function.

You can also check `annotation_axis_grob()` function to draw a nicer axis.

![image](https://user-images.githubusercontent.com/449218/52726594-c6a71180-2fb3-11e9-8fa3-3434a42940b5.png)

**Comment by johanneswerner** [comment]
That's cool, thank you!
