### ISSUE TITLE
Doc small link change

### ISSUE THREAD

**Issue by bblodfon** [jokergoo/ComplexHeatmap#255]
Hi,

In this [doc link](https://jokergoo.github.io/ComplexHeatmap-reference/book/oncoprint.html) the "OncoPrint" link goes to [http://www.cbioportal.org/faq.jsp#what-are-oncoprints](http://www.cbioportal.org/faq.jsp#what-are-oncoprints), which does not exist anymore. It should be: [http://www.cbioportal.org/faq#what-are-oncoprints](http://www.cbioportal.org/faq#what-are-oncoprints).

BR, John

**Comment by jokergoo** [comment]
Thanks!

I have updated.
