### ISSUE TITLE
logarithmic scale for barplot ?

### ISSUE THREAD

**Issue by michoug** [jokergoo/ComplexHeatmap#257]
Hi, I have abundance data that I want to add to a barplot of a heatmap ranging from ~ 0.001 to 10.

I'm using this 

```
HeatmapAnnotation( foo = anno_barplot(matrixEnrich,axis = TRUE,
                                            axis_side = "right",
                                            bar_width = 0.5,
                                            gp = gpar(fill = col_bar)), which = "column", show_annotation_name = F)
```

and got this

![screen shot 2019-02-21 at 2 30 17 pm](https://user-images.githubusercontent.com/12357985/53166011-3b4a0380-35e5-11e9-972a-3d89ff1605d1.png)

Is there an easy way to change the scale to logarithm?
Thanks !

**Comment by jokergoo** [comment]
You need to manually convert your data and set `at`/`labels` for the axis:

```r
breaks = c(0.01, 0.1, 1, 10)
anno_barplot(log10(matrixEnrich), axis_param = list(at = log10(breaks), labels =breaks), ...)

```

**Comment by michoug** [comment]
Thank you for your help
I got this error message

```
Error in anno_barplot(log10(matrixEnrich), axis = TRUE, axis_side = "right",  : 
  Since `x` is a matrix, the sign of each row should be either all positive or all negative.
```

**Comment by jokergoo** [comment]
When it is a matrix, the barplot represents as stacked barplot, which means, all the values should be positive. In your data, after log10-transformation, there are negative values in it. You need to think about what is the proper way to visualize it.
