### ISSUE TITLE
column_split function in version 1.20?

### ISSUE THREAD

**Issue by anabbi** [jokergoo/ComplexHeatmap#262]
Hi Zuguang

It looks like row_split and column_split have been updated on 1.20. Could you please advise on how to use them now? row_split gives me error "unused argument".

Thanks

Arash

**Comment by jokergoo** [comment]
No, it is on the development branch on Bioconductor. Please install it by:

```r
library(devtools)
install_github("jokergoo/ComplexHeatmap")
```
