### ISSUE TITLE
pt_size doesn't work in anno_simple when pch is a vector of letters/numbers

### ISSUE THREAD

**Issue by jfoox** [jokergoo/ComplexHeatmap#266]
I am attempting to add single-number symbols on top of my annotation grid:

``HeatmapAnnotation(Sample = anno_simple(df[,1], pch=df[,2], pt_size=unit(0.5, "mm"))``

The track is colored and labeled correctly:

![image](https://user-images.githubusercontent.com/6341233/53699606-2ecd6400-3db8-11e9-8112-22c2cf4b32dc.png)

But I would like for the numbers to be smaller within each cell. Changing the value of `pt_size` does not change the size of the numbers.

I find this to be the case when `x` is a vector or a matrix.

**Comment by jokergoo** [comment]
Please set by `pt_gp`:

```r
HeatmapAnnotation(Sample = anno_simple(df[,1], pch=df[,2], pt_gp=gpar(fontsize = unit(5, "mm")))
```

**Comment by jfoox** [comment]
This worked, thank you!
