### ISSUE TITLE
Text overlay?

### ISSUE THREAD

**Issue by davemcg** [jokergoo/ComplexHeatmap#267]
Is it possible to print the values for each cell? I can't find an option for this. pheatmap has `display_numbers` https://stackoverflow.com/questions/54342274/pheatmap-display-numbers-argument

**Comment by jokergoo** [comment]
Yes, please check this section in the documentation:

https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#customize-the-heatmap-body

**Comment by davemcg** [comment]
Ah, I'm using a <1.99 version of ComplexHeatmap. Time to update, I suppose.
