### ISSUE TITLE
Unable to use ComplexHeatmap

### ISSUE THREAD

**Issue by PriyaMilne** [jokergoo/ComplexHeatmap#269]
Hi,

I am trying to run the example code from ComplexHeatmap as shown here:

set.seed(123)
lt = list(a = sample(letters, 10),
          b = sample(letters, 15),
          c = sample(letters, 20))
m1 = make_comb_mat(lt)
m1

However, it is saying that the function make_comb_mat() was not found. I am using R version 3.5.2 and the ComplexHeatmap version 1.20. I am also encountering many other errors when trying to plot the OncoPrint as well!
 

Thank you!

**Comment by jokergoo** [comment]
Please use version >= 1.99.*. The new version is not at Bioconductor release branch yet. You can update the package by:

```r
library(devtools)
install_github("jokergoo/ComplexHeatmap")
```
