### ISSUE TITLE
Annotation height

### ISSUE THREAD

**Issue by tiagochst** [jokergoo/ComplexHeatmap#272]
If I have two heatmaps, one with one annotation and other with 4, what should I do to keep the height of that one annotation the same size as one of the other 4 annotations ? 

I tried to use annotation_height, but it does not seem to be working in the newer version (github).  It was working with the Bioconductor one (release)

Here is an example:
http://rpubs.com/tiagochst/complexheatmap_annotation

**Comment by jokergoo** [comment]
Thanks for this example! The automatic adjustment of annotations across heatmaps is not very perfectly implemented. I will try to fix it soon.

**Comment by jokergoo** [comment]
Please update the package to 1.99.6 from GitHub. Now by default the height of heatmap-like annotations will not be adjusted.

![image](https://user-images.githubusercontent.com/449218/54435514-f3745300-4730-11e9-8696-e66ca371c559.png)

**Comment by tiagochst** [comment]
Thanks!
