### ISSUE TITLE
R fails to plot more than 2000 columns

### ISSUE THREAD

**Issue by sahilseth** [jokergoo/ComplexHeatmap#273]
It seems to be a weird error, but if I try to plot more than 2000 columns R crashes:

Have tried the following:
- saving using `pdf`
- saving using `Cairo::CairoPDF`
- `use_raster=T` fails regardless

```
> pdf(glue("{odir}/ht.pdf"), width = 16, height = 8)
> # Cairo::CairoPDF(glue("{odir}/ht.pdf"), width = 16, height = 8)
> draw(ht)
Error in .External2(C_X11, paste0("png::", filename), g$width, g$height,  :
  unable to start device PNG
In addition: Warning message:
In (function (filename = "Rplot%03d.png", width = 480, height = 480,  :
  unable to open connection to X11 display ''
> dev.off()
null device
          1
```

Appreciate your help!

**Comment by jokergoo** [comment]
I have no clue for this. I tried following code on a machine where there is no X11 display and it worked fine.

```
> m = matrix(rnorm(10*4000), nr = 10)
> pdf("~/test.pdf")
> draw(Heatmap(m))
Loading required namespace: png
> dev.off()
null device 
          1 
```

**Comment by sahilseth** [comment]
Tried a few more options and seems above a certain number of columns, its critical use raster, along with specifying a device. 

```
# this does is not sufficient
Cairo::CairoPDF() # instead of using pdf
ht <- Heatmap(...., use_raster=T, raster_device = "png") # default device
dev.off()

# in addition, need to ask complexheatmap to use cairo for rastering:
Cairo::CairoPDF()
ht <- Heatmap(...., use_raster=T, raster_device = "CairoPNG")
dev.off()
```

Also, I re-installed R (--with-tcktk), so it could have played a role as well, not sure....

```
capabilities()
       jpeg         png        tiff       tcltk         X11        aqua    http/ftp     sockets      libxml        fifo      cledit       iconv         NLS     profmem 
       TRUE        TRUE        TRUE        TRUE       FALSE       FALSE        TRUE        TRUE        TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
      cairo         ICU long.double     libcurl 
       TRUE        TRUE        TRUE        TRUE 
```

Thanks!!

**Comment by ebioman** [comment]
Hi
I just came across this as well and found in my case 2000 entries crashing my rstudio Heatmap function.
Looking into your code I believe that it is related to this in R/Heatmap-class.R:

```
use_raster = (nrow(matrix) > 2000 && ncol(matrix) > 1) || (ncol(matrix) > 2000 && nrow(matrix) > 1), 
raster_device = c("png", "jpeg", "tiff", "CairoPNG", "CairoJPEG", "CairoTIFF"),
raster_quality = 2,
raster_device_param = list(),
raster_resize = FALSE,


```

I managed to circumvent this by manually loading `library(png)`

**Comment by jokergoo** [comment]
@ebioman Thanks for reporting this. Since I don't use Rstudio too much, I did see this problem on my PC. I will try to test it on Rstudio!

**Comment by jokergoo** [comment]
En.... Are you using the new version of the package (> 1.99.0)? When `use_raster` is turned on, internally a device is opened (e.g. png()), then the plot is written into the png device, and then the png device is closed. On Rstudio, the device list is special compared to the normal R console (there is always a `RStuidioGD` device inserted into the device list:

```
> dev.list()
RStudioGD       png 
        2         3 
```
 In the new version, I have improved the code for closing the device under Rstudio. I am not sure whether is the reason, but I tried on Rstudio on my PC with ComplexHeatmap version  1.99.7, everthing is fine.

**Comment by ebioman** [comment]
@jokergoo I was using v1.99.7 but I have to admit this is the first time I experienced this issue (long time fan of ComplexHeatmap).

```
> test<-outer(1:2000,1:3)
> library(ComplexHeatmap)
Loading required package: grid
========================================
ComplexHeatmap version 1.99.7
Bioconductor page: http://bioconductor.org/packages/ComplexHeatmap/
Github page: https://github.com/jokergoo/ComplexHeatmap
Documentation: http://jokergoo.github.io/ComplexHeatmap-reference

If you use it in published research, please cite:
Gu, Z. Complex heatmaps reveal patterns and correlations in multidimensional 
  genomic data. Bioinformatics 2016.
========================================

> Heatmap((test))
```
works perfectly

```
test<-outer(1:2001,1:3)
> Heatmap((test))
Loading required namespace: png

```
This was still good. I tried as well to generate a small Rmarkdown script and knit it which works.
I only got this error so far once , when  I had a large complex analysis with many plot function and cant reproduce it currently anymore.

**Comment by ebioman** [comment]
Yes, indeed now I could verify that with a minimal example:

```

Loading required package: biomaRt
> remove.packages("png")
Removing package from ‘/home/eschmid/R/x86_64-redhat-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
> test<-outer(1:2000,1:3)
> library(ComplexHeatmap)
Loading required package: grid
========================================
ComplexHeatmap version 1.99.7
Bioconductor page: http://bioconductor.org/packages/ComplexHeatmap/
Github page: https://github.com/jokergoo/ComplexHeatmap
Documentation: http://jokergoo.github.io/ComplexHeatmap-reference

If you use it in published research, please cite:
Gu, Z. Complex heatmaps reveal patterns and correlations in multidimensional 
  genomic data. Bioinformatics 2016.
========================================
remove.packages("png")
Removing package from ‘/home/eschmid/R/x86_64-redhat-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
test<-outer(1:2003,1:3)
library(ComplexHeatmap)
Heatmap((test))
Loading required namespace: png
Failed with error:  ‘there is no package called ‘png’’
Error: Need png package to read image.

```
````

**Comment by jokergoo** [comment]
Ah ha Yes! I should do something when png is not installed.

Thanks!

**Comment by jokergoo** [comment]
Now I moved `png` to `Imports` in the DESCRIPTION file, which means if `ComplexHeatmap` is installed, `png` package is also installed as well.
