### ISSUE TITLE
Is there a way to use the upset feature to just count occurence

### ISSUE THREAD

**Issue by ahdee** [jokergoo/ComplexHeatmap#276]
Hi awesome package. I really like the features ( eg heatmap annotations ) of the upset plot however I'm wondering is there a way to plot per sample instead of set?  I ask because I have multiple samples eg. s1, s2, s3.   Some of these samples response to certain drugs and not others.  What I want is to simply display how many of those drugs is responsive to that sample, not count the intersections as per this example here. 
```
lt = list(drug1 = c ( "s1","s2","s3"),
          drug2 = c ( "s1","s2"),
          drug3 = c ( "s2")  )

m1 = make_comb_mat(lt) # the default mode is `distinct`

length ( unique ( unlist ( lt) ) ) # three samples

UpSet( m1)
```

here is an example. Is this possible? 

![3GNueoX](https://user-images.githubusercontent.com/9808122/54843815-8e6daf80-4c92-11e9-8225-92dbf62f91bd.png)

**Comment by jokergoo** [comment]
Then it is more like to make a heatmap-like plot, see the following example code:

```r

m = cbind(c(1, 1, 0), c(1, 1, 1), c(1, 0, 0))
rownames(m) = paste0("drug", 1:3)
colnames(m) = paste0("s", 1:3)

response = c(2, 4, 1)

layer_fun = function(j, i, x, y, w, h, fill) {
	nr = round(1/as.numeric(h[1]))
	nc = round(1/as.numeric(w[1]))
	subm = matrix(pindex(m, i, j), nrow = nr, byrow = FALSE)
	for(k in seq_len(nr)) {
		if(k %% 2) {
			grid.rect(y = k/nr, height = 1/nr, just = "top", gp = gpar(fill = "#F0F0F0", col = NA))
		}
	}
	grid.points(x, y, size = unit(4, "mm"), pch = 16, gp = gpar(col = ifelse(pindex(m, i, j), "black", "#CCCCCC")))
	jj = unique(j)
	for(k in seq_len(nc)) {
        if(sum(subm[, k]) >= 2) {
            i_min = min(which(subm[, k] > 0))
            i_max = max(which(subm[, k] > 0))
            grid.lines(c(k - 0.5, k - 0.5)/nc, (nr - c(i_min, i_max) + 0.5)/nr, gp = gpar(col = "black", lwd = 2))
        }
    }
}
Heatmap(m, rect_gp = gpar(type = "none"), show_heatmap_legend = FALSE,
	cluster_rows = FALSE, cluster_columns = FALSE,
	top_annotation = HeatmapAnnotation(response = anno_barplot(response, height = unit(3, "cm"), border = FALSE)),
	layer_fun = layer_fun)
```

Here you need to create a matrix which contains 0 and 1. The barplot is added by `anno_barplot()`. The `layer_fun` function draws the dots and lines and you can directly copy and paste for using it.

**Comment by ahdee** [comment]
@jokergoo thanks! I have to study this code!
