### ISSUE TITLE
retrieve row orders and clusters for k-means

### ISSUE THREAD

**Issue by crazyhottommy** [jokergoo/ComplexHeatmap#28]
Hi,
I can do kmeans first (I know orders of the rows, and the cluster for each row), and then draw the heatmap:

```{r}
km = kmeans(mat, 3)
Heatmap(mat, name = "foo", split = paste0("km", km$clustering))

```

How can I retrieve row orders and which cluster each row belongs to  after draw?

```{r}
Heatmap(mat, name = "foo", km=3)

```
I know `row_order` can get the row order, but how I can get the clusters?

Thanks,
Ming

**Comment by jokergoo** [comment]
You can use `row_dend()`:

```{r}
ht = Heatmap(mat, km = 3)
ht = draw(ht)
row_dend(ht)
```

The value returned by `row_dend()` is a list of `dendrogram` objects.

**Comment by crazyhottommy** [comment]
actually, I was doing k-means using Enrichedheatmap.

I got an error

```{r}
ht2<- EnrichedHeatmap(H3K27ac.promoters.mat, col= c("white","red"), name = "H3K27ac promoter",
                km=3,
                axis_name = c("-5kb", "TSS", "5kb"),
                axis_name_rot = 0,
                top_annotation = HeatmapAnnotation(lines = anno_enriched(gp=gpar(col=2:4))), 
                top_annotation_height = unit(2, "cm"))

row_dend(ht2)
Error in names(lt) = object@row_title : 
  'names' attribute [3] must be the same length as the vector [0]
```

**Comment by jokergoo** [comment]
I think you need to draw the heatmap first. Following code:

```{r}
ht2<- EnrichedHeatmap(H3K27ac.promoters.mat, col= c("white","red"), name = "H3K27ac promoter",
                km=3,
                axis_name = c("-5kb", "TSS", "5kb"),
                axis_name_rot = 0,
                top_annotation = HeatmapAnnotation(lines = anno_enriched(gp=gpar(col=2:4))), 
                top_annotation_height = unit(2, "cm"))
```

only initializes the `Heatmap` object (that is why we can concatenate  many heatmaps in parallel). The clustering will be applied after `draw()` is called (either explicitly or internally). So you need to draw the heatmaps before extracting the row dendrograms.

```{r}
ht2 = draw(ht2)
row_dend(ht2)
```

**Comment by jokergoo** [comment]
By default row clustering is suppressed in `EnrichedHeatmap()`, rows are ordered by the enrichment of the signal by default. If you want to cluster rows, you need to specify `cluster_rows = TRUE` explicitly, or else no dendrogram will be returned by `row_dend()`.

```{r}
ht2<- EnrichedHeatmap(H3K27ac.promoters.mat, col= c("white","red"), name = "H3K27ac promoter",
                km=3, cluster_rows = TRUE,
                axis_name = c("-5kb", "TSS", "5kb"),
                axis_name_rot = 0,
                top_annotation = HeatmapAnnotation(lines = anno_enriched(gp=gpar(col=2:4))), 
                top_annotation_height = unit(2, "cm"))
```

Also you need to call `draw()` explicitly as well:

```{r}
ht2 = draw(ht2)
row_dend(ht2)
```

**Comment by jokergoo** [comment]
Can you tell me which version of **EnrichedHeatmap** you are using? I would expect in your case `row_dend(ht2)` should return `list()` instead of throwing errors.

**Comment by crazyhottommy** [comment]
I did call draw() first.

```{r}
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.1 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
 [1] stats4    parallel  grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] readr_0.2.2                             org.Hs.eg.db_3.2.3                     
 [3] RSQLite_1.0.0                           DBI_0.3.1                              
 [5] dplyr_0.4.3                             TxDb.Hsapiens.UCSC.hg19.knownGene_3.2.2
 [7] GenomicFeatures_1.22.13                 AnnotationDbi_1.32.3                   
 [9] Biobase_2.30.0                          rtracklayer_1.30.2                     
[11] EnrichedHeatmap_1.0.0                   locfit_1.5-9.1                         
[13] GenomicRanges_1.22.4                    GenomeInfoDb_1.6.3                     
[15] IRanges_2.4.8                           S4Vectors_0.8.11                       
[17] BiocGenerics_0.16.1                     ComplexHeatmap_1.6.0                   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3                RColorBrewer_1.1-2         futile.logger_1.4.1        XVector_0.10.0            
 [5] bitops_1.0-6               futile.options_1.0.0       tools_3.2.3                zlibbioc_1.16.0           
 [9] dendextend_1.1.2           biomaRt_2.26.1             lattice_0.20-33            Biostrings_2.38.4         
[13] GlobalOptions_0.0.8        R6_2.1.1                   GetoptLong_0.1.1           XML_3.98-1.4              
[17] BiocParallel_1.4.3         lambda.r_1.1.7             magrittr_1.5               whisker_0.3-2             
[21] Rsamtools_1.22.0           matrixStats_0.50.1         GenomicAlignments_1.6.3    assertthat_0.1            
[25] SummarizedExperiment_1.0.2 shape_1.4.2                circlize_0.3.4             colorspace_1.2-6          
[29] lazyeval_0.1.10            RCurl_1.95-4.8             rjson_0.2.15     

```

**Comment by jokergoo** [comment]
Then you can just use `row_order()` because if you apply k-means clustering on rows, `row_order()` will return a list of row index so that you can know which rows belong to which row cluster. E.g. if you want to extract top 500 rows with strongest signals in every row cluster, you can do as:

```{r}
row_order_list = row_order(ht)
lapply(row_order_list, function(x) x[1:500])
```
 and by the way, I suggest you to install the newest version of ComplexHeatmap and EnrichedHeatmap. There are many bugs fixed in the recent half year:

```{r}
devtools::install_github("jokergoo/ComplexHeatmap")
devtools::install_github("jokergoo/EnrichedHeatmap")
```

**Comment by crazyhottommy** [comment]
Thanks. This works for me. I did not notice that `row_order()` returns a list, and I will use the most updated packages. They are very nice packages. Keep up the good work!

Ming

**Comment by crazyhottommy** [comment]
Hi, 

```{r}
set.seed(100)

ht<- EnrichedHeatmap(H3K27ac.promoters.mat, col= c("white","red"), name = "H3K27ac promoter",
                km=3,
                axis_name = c("-5kb", "TSS", "5kb"),
                axis_name_rot = 0,
                top_annotation = HeatmapAnnotation(lines = anno_enriched(gp=gpar(col=2:4))), 
                top_annotation_height = unit(2, "cm"))
draw(ht)

lapply(row_order(ht.list), function(x) length(x)
[[1]]
[1] 5676

[[2]]
[1] 4073

[[3]]
[1] 2336

```

From the output of `draw(ht)` it seems cluster1 is the group with the fewest rows, and cluster2 is the group with the most rows. This is not consistent with the length of each list returned by `lapply(row_order(ht.list), function(x) length(x)`

Am I missing something?

Thanks,
Ming

**Comment by jokergoo** [comment]
Current if you directly apply `row_order` to `ht` before calling `draw()`, sometimes the order is not stable.
This is something I need to check.

The inconsistency is due to row-clusters (e.g. 3 row-clusters in your example) will be re-ordered based on mean value in each row cluster to make similar row clusters close to each other.

But if you assign back the result generated by `draw()` to `ht`, I would expect the row order should be same as that in the heatmap.

```{r}
ht = draw(ht)
lapply(row_order(ht), function(x) length(x)
```

k-means called inside **ComplexHeatmap** uses random initial centers, so if you don't set the seed, the results may be different. If you want the result not to be affected by the random centers, you can do the k-means clustering in the beginning, and assign the row classification to `split` argument in `Heatmap`. (actually this is how it is implemented in **ComplexHeatmap**)

```{r}
km = kmeans(mat, centers = 3)
Heatmap(mat, split = 3)
```

**Comment by crazyhottommy** [comment]
Hi,

A question on k-means:

```{r}
set.seed(1)
kmeans.mat<- kmeans(combined.mat, 3)

table(kmeans.mat$cluster)

    1     2     3 
13646  1151  8259 
```

when plot a heatmap, the rows will be ordered as cluster 1, 2, 3 when pass `split=kmeans.mat$cluster`

If I want to order the heatmap as cluster 2,3,1. How should I do it?
I need to change the k-means cluster label for each group.

Thanks,
Ming

**Comment by crazyhottommy** [comment]
I just googled around, and found something like:

```{r}
library(Kmisc)
kmeans.cluster<- swap(kmeans.mat$cluster,c(1,2,3), c(2,3,1))
```
and then pass `split=kmeans.cluster`

It works, but want to know how you do it.

Ming

**Comment by jokergoo** [comment]
Yes, that is one solution. The default order is `unique(as.character(kmeans.cluster))`.

More generally, you can convert `kmeans.cluster` as a factor and the levels of the factor controls the order of groups:

```{r}
kmeans.cluster = as.character(kmeans.cluster)
kmeans.cluster = factor(kmeans,cluster, levels = c("2", "3", "1"))
```
