### ISSUE TITLE
Big perimeter frame

### ISSUE THREAD

**Issue by cxen** [jokergoo/ComplexHeatmap#282]
This happens when exporting a heatmap as a metafile. There is always a single point in heatmap scale that has an abnormally large perimeter frame that doesnt't match the rest of the scale. It is not an object group either.

This makes it so that you cannot easily select the whole scale in one.

![Perimeter frame](https://user-images.githubusercontent.com/46993334/55150800-3381ff80-514d-11e9-891b-108aec7238af.png)

**Comment by jokergoo** [comment]
How did you get this plot? Can you show me the code you use? 

And what is a metafile? Is it the pdf file? I haven't tested it in inkscape, but if you show me how you generate this plot and import to inkscape, I can have a test.

**Comment by cxen** [comment]
This is the code I use:

`library(ComplexHeatmap)
library(circlize)

Heatmap(as.matrix(irates.log),
        name = "Isolates EEA",
        heatmap_legend_param = list(title = "EEA (RFU)",
                                    labels_gp = gpar(col = "black", font = 2),
                                    title_position = "leftcenter-rot",
                                    legend_height = unit(5, "cm"),
                                    border = "black",
                                    color_bar = "continuous",
                                    at = c(0, 3.321928, 6.643856, 9.965784,
                                           13.28771, 16.60964, 18.417),
                                    labels = c("Not detected", "10", "100", "1 000",
                                               "10 000", "100 000", "")),
        cluster_rows = hclust(dist(irates.log),
                              method="ward.D"),
        # cluster_rows = color_branches(hclust(dist(irates.log),  # Same clustering as above but custom colours
        #                                      method="ward.D"),
        #                               k = 3),
        # cluster_rows =function(m) hclust(dist(m), # same clusering but different layout
        #                       method="ward.D"),
        cluster_columns = hclust(dist(t(irates.log)),
                                             method="ward.D"),
        # cluster_columns = function(m) hclust(dist(m),
        #                                      method="ward.D"), # same clusering but different layout
        right_annotation = rowAnnotation(bar = communities_row,
                                         col = list(bar = c("A" = "#f8766c",
                                                            "B" = "#92d050",
                                                            "C" = "#00b0f0",
                                                            "D" = "#7030a0",
                                                            "A/C" = "pink",
                                                            "B/C" = "brown",
                                                            "A/D" = "orange")),
                                         na_col = "white",
                                         gp = gpar(col = "black")),
        column_dend_height = unit(1.5, "cm"),
        row_dend_width = unit(2, "cm"),
        column_names_rot = 45,
        rect_gp = gpar(col = "black", lty = 1, lwd = 1),
        col = colorRamp2(c(0, 1, 5, 10, 15, 18.417),
                         # colorRampPalette(colors = c("#4575b4", "#91bfdb", "#fee090", "#fc8d59", "#d73027"))(6))
                         # colorRampPalette(rev(brewer.pal(n = 11, name = "RdYlBu")))(6))
                         colorRampPalette(colors = c("white",
                                                     "#4575b4", "#91bfdb", "#fee090", "#fc8d59", "#d73027"))(6))
        )`

A metafile is an .emf file export of the plot with RStudio.
It works better for me than exporting as .svg because it keeps the text editable and not as shapes.

What I'm showing in the screenshot is what happens if I try to move the scale. The scale is plotted perfectly. It's just when you try to move them together, that one point stays behind because its perimeter is very large.

**Comment by jokergoo** [comment]
OK, that is the version of ComplexHeatmap you are using?

**Comment by cxen** [comment]
1.99.6

I believe I pulled the version from github on Mar 24, 2019.

**Comment by jokergoo** [comment]
I cannt see there is an "emf" option on my RStudio, so I generated as a pdf file and I didn't see the thing happed on your plot. The both legends can be selected with as their size.

![image](https://user-images.githubusercontent.com/449218/55162215-9aacad80-5167-11e9-9e65-28cac22fbe2e.png)

![image](https://user-images.githubusercontent.com/449218/55162245-b2843180-5167-11e9-98d2-1c264c755710.png)

**Comment by cxen** [comment]
I use Rstudio 1.1463 and the option the export window dropdown menu is "Metafile".

Seems like your solution is a good compromise between .svg and .emf as the "issue" is gone and text remains as text. Still it's a weird issue to happen for only one point in the scale.
