### ISSUE TITLE
Errors / issues with recent updates

### ISSUE THREAD

**Issue by lmweber** [jokergoo/ComplexHeatmap#283]
Hi, I am getting a couple of errors and issues in my functions that depend on ComplexHeatmap, following recent updates in the devel version on Bioconductor.

(i) I am getting the error
```
`heatmap_width` and `width` should not all be the absolute units.
```
even after I have removed all `heatmap_width` or `width` references within my function. I previously had a hard-coded `width` argument for the row annotation in my function; I have removed this (it wasn't important), but I am still getting the error in my Travis CI builds.

The error is shown in Travis here: https://travis-ci.org/lmweber/diffcyt/builds/513044594

My function is here: https://github.com/lmweber/diffcyt/blob/master/R/plotHeatmap.R

I am trying to reproduce this error on my local system now (where it currently seems to be working, which is strange); possibly this has something to do with the new checks for `is_abs_unit(width)` and `is_abs_unit(heatmap_width)` in `Heatmap-class.R`.

---

(ii) When I add a row annotation bar to the right-hand-side of a heatmap that already contains text row labels on the right-hand-side, the text row labels disappear. (If the text labels are on the opposite side, this doesn't happen; so I think the row annotation bar is overwriting the text row labels if they are on the same side). Below are some figures illustrating this:

row text labels on left, with row annotation on right (i.e. this works correctly, since they are on opposite sides):

![row_labels_on_left](https://user-images.githubusercontent.com/8062417/55241941-7ff83880-523c-11e9-9629-b64d92a5d0e7.png)

row text labels on right:

![row_labels_on_right](https://user-images.githubusercontent.com/8062417/55241948-85ee1980-523c-11e9-807c-3ac986d41fce.png)

row text labels on right, with row annotation on right (i.e. this does not work correctly: the row text labels get overwritten by the annotation bar):

In the earlier version of ComplexHeatmap, it showed both the row text labels and the annotation bar in this case: e.g. see the final figure in my vignette here: http://bioconductor.org/packages/release/bioc/vignettes/diffcyt/inst/doc/diffcyt_workflow.html. Is it possible to change this back, so it still shows both? Thanks!

![row_labels_on_right_overwritten](https://user-images.githubusercontent.com/8062417/55241955-8b4b6400-523c-11e9-81dd-4c90a48caedb.png)

**Comment by lmweber** [comment]
I am using ComplexHeatmap version 1.99.7 (in both Travis and my local system).

**Comment by lmweber** [comment]
For (i), I think it may have something to do with the checks in the following lines of code in `Heatmap-class.R`. However I haven't been able to figure out yet why it gives an error in the Travis build (Linux) and not on my local system (Mac).

lines 814-839 in `Heatmap-class.R`:

```
    if(is.null(width)) {
        width = unit(ncol(matrix), "null")
    } else if(is.numeric(width) && !inherits(width, "unit")) {
        width = unit(width, "null")
    } else if(!inherits(width, "unit")) {
        stop_wrap("`width` should be a `unit` object or a single number.")
    }

    if(is.null(height)) {
        height = unit(nrow(matrix), "null")
    } else if(is.numeric(height) && !inherits(height, "unit")) {
        height = unit(height, "null")
    } else if(!inherits(height, "unit")) {
        stop_wrap("`height` should be a `unit` object or a single number.")
    }

    if(!is.null(width) && !is.null(heatmap_width)) {
        if(is_abs_unit(width) && is_abs_unit(heatmap_width)) {
            stop_wrap("`heatmap_width` and `width` should not all be the absolute units.")
        }
    }
    if(!is.null(height) && !is.null(heatmap_height)) {
        if(is_abs_unit(height) && is_abs_unit(heatmap_height)) {
            stop_wrap("`heatmap_height` and `width` should not all be the absolute units.")
        }
    }
```

**Comment by lmweber** [comment]
Issue (i) seems to be working now: my Travis builds are now passing. I made some additional changes to my package vignette today, but I don't know the reason why it is now suddenly working. Maybe it was a problem with Travis. Sorry for the confusion!

For issue (ii), I haven't found a solution yet.

**Comment by jokergoo** [comment]
Hi, 

(i): following error message 

```
`heatmap_width` and `width` should not all be the absolute units.
```

means that only one of `heatmap_width` and `width` can be absolute units. The reason is `heatmap_width` is the sum of the width of heatmap body and heatmap components and `width` is the width of the heatmap body only. All the heatmap components have fixed width (e.g. row names, row dendrograms), therefore, when e.g. `width` is in an absolute unit, the `heatmap_width` is determined. In the other way around, if `heatmap_width` is set as an absolute unit, `width` is also determined. Thus, only `width` or `heatmap_width` can be set as in absolute unit. They cannot set in the same time.

(ii) in the newest version of the package, by default, there is some automatic adjustment when there are heatmaps and row annotations. If there are multiple heatmaps, by default, only the row names for the most right heatmap is shown (https://jokergoo.github.io/ComplexHeatmap-reference/book/a-list-of-heatmaps.html#automatic-adjustment-to-the-main-heatmap).  You can set as:

```r
draw(ht_list, auto_adjust = FALSE)
```

to show row names for all heatmaps, or you can set the most right one-column heatmap as a right annotation for the left heatmap:

```r
Heatmap(..., right_annotation = rowAnnotation(...))
```

**Comment by lmweber** [comment]
Thanks a lot for the reply. For (ii), setting the `auto_adjust` argument with `draw(ht_list, auto_adjust = FALSE)` has worked fine.

Thanks also for creating this package; it has been extremely useful in our work!
