### ISSUE TITLE
Interaction between `cluster_rows` and `split`

### ISSUE THREAD

**Issue by kevinrue** [jokergoo/ComplexHeatmap#287]
Not sure whether this is a new feature or a bug :)

In previous versions, when heat maps were split by row, clustering could only happen within "block", as visible [here](https://www.bioconductor.org/packages/release/bioc/vignettes/ComplexHeatmap/inst/doc/s2.single_heatmap.html#toc_5).

Now, it looks like the blocks are clustered, as visible here
https://www.bioconductor.org/packages/devel/bioc/vignettes/ComplexHeatmap/inst/doc/most_probably_asked_questions.html

Is there still a way to provide a vector to `Heatmap(split=...)` and use `cluster_rows=TRUE` to cluster only _within_ each block of rows (i.e., not clustering "between" blocks of rows)?

**Comment by jokergoo** [comment]
Yes, this is a new feature that groups are clustered based on the group means.

You can turn it off by setting `cluster_row_slices = FALSE`.

See the third heatmap in this section:
https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#order-of-slices

**Comment by kevinrue** [comment]
Thanks, I missed that information !
