### ISSUE TITLE
When cluster with too many rows, the heatmap is too dense, and the file size is large.

### ISSUE THREAD

**Issue by crazyhottommy** [jokergoo/ComplexHeatmap#29]
Hi,

This is more like a general question. When making heatmap with too many rows, usually use EnrichedHeatmap with many (more than 10,000) genomic regions, the PDF size of the heatmap is very big (several MB). Computer becomes very slow when visualize it or when insert into powerpoint and Word. For other type of analysis, I usually use only top several hundred most variable rows to cluster.

I know it is more of a visualization than making any real quantitative comparisons.  Our eyes probably can not differentiate these many pixels. How to reduce the size of the PDF?

Some time ago, I got a tip from this [post](http://seqanswers.com/forums/showthread.php?p=114275&posted=1#post114275)

>Now for my heatmap power tip of the day, if you will: use the "useRaster=TRUE" parameter in your heatmap.2() call. Excellent extension by R developers since 2.13. But for some reason the R developers explicitly turn it off for interactive session windows, so you'll only see it in an exported file. (Unless you have a custom image() function which doesn't disable it, I did this.) It also makes the exported file hugely smaller, especially for PDFs.

>What it does is darn-near essential for nextgen coverage heatmaps -- it actually properly resamples the image as it down-sizes the image during export. Without useRaster=TRUE, image() creates a zillion tiny rectangles to represent the heatmap, all pieced together right next to each other. When the display is fewer pixels/points high than the number of rows of data, it discretizes the data -- that is, it uses integer values for the rectangles. In many cases, especially onscreen, many rectangles fully overlap others, randomly obscuring the real patterns, and often blunting your otherwise cool-looking signal.

`useRaster=TRUE` is only for heatmap.2 or internally `image()`. Is there a way to specify it in ComplexHeatmaps or how do you usually deal with this situation?

Thanks,
Ming

**Comment by jokergoo** [comment]
Yes, I also have this problem in my analysis. I always keep the original PDF file and convert to PNG by **convert** command afterwards. But it would be good idea to support something like `useRaster`!

**Comment by jokergoo** [comment]
Hi, I updated the package it should now support raster image if the number of rows are too huge. I added four options in `Heatmap()` to control how to generate raster images: `use_raster`, `raster_quality`, `raster_device` and `raster_device_param`. These four new options can also be used in `EnrichedHeatmap()`. 

Following is example code of how to use raster image. `mat1` is the matrix generated in **EnrichedHeatmap** vignette.

```
> pdf("heatmap.pdf", width = 6, height = 10)
> EnrichedHeatmap(mat1, col = c("white", "red")) +
+ EnrichedHeatmap(mat1, col = c("white", "red"))
> dev.off()
> file.size("heatmap.pdf")
[1] 959448
>
> pdf("heatmap_with_raster.pdf", width = 6, height = 10)
> EnrichedHeatmap(mat1, col = c("white", "red"), use_raster = TRUE) +
+ EnrichedHeatmap(mat1, col = c("white", "red"), use_raster = TRUE)
Loading required namespace: png
> dev.off()
> file.size("heatmap_with_raster.pdf")
[1] 48192
```

The two pdf files are here:

[heatmap.pdf](https://github.com/jokergoo/ComplexHeatmap/files/190956/heatmap.pdf)
[heatmap_with_raster.pdf](https://github.com/jokergoo/ComplexHeatmap/files/190955/heatmap_with_raster.pdf)

**Comment by crazyhottommy** [comment]
Great work! and kudos to the post comparing sizes!
Thanks again.

Ming

**Comment by crazyhottommy** [comment]
Sorry to open it again.  If there are too many rows you use raster. When you decide the number of rows when using K-means and one of the group only has say 100 rows, it seems only the clusters with too many rows are rastered. I want to raster all of them. see below, it seems the cluster in the middle look different to the other two clusters:

![screenshot 2016-04-12 22 27 26](https://cloud.githubusercontent.com/assets/4106146/14482021/c865cf94-00fd-11e6-979d-3ff648556997.png)

**Comment by jokergoo** [comment]
I have no idea why your heatmap looks so blur. I generated a heatmap with raster image in my computer and it looks good.

Can you send me your matrix (maybe as a `.RData` or `.rds` file) and your code to my email so that I can test on it?

```{r}
load(paste0(system.file("extdata", "chr21_test_data.RData", package = "EnrichedHeatmap")))
tss = promoters(genes, upstream = 0, downstream = 1)
mat1 = normalizeToMatrix(H3K4me3, tss, value_column = "coverage", 
    extend = 5000, mean_mode = "w0", w = 50)

col_fun = colorRamp2(quantile(mat1, c(0, 0.99)), c("white", "red"))
png("~/enriched_heatmap2.png", width = 300, height = 600)
EnrichedHeatmap(mat1, col = col_fun, name = "H3K4me3", use_raster = TRUE,  km = 3)
dev.off()
```

![enriched_heatmap](https://cloud.githubusercontent.com/assets/449218/14488402/6994e26e-0168-11e6-8924-3f58cc218da2.png)

**Comment by crazyhottommy** [comment]
Thanks Zuguang, I have sent you an email: z.gu@dkfz.de

**Comment by jokergoo** [comment]
Did you directly look at the plot in an interactive device (e.g. Rstudio)? By default the quality of the raster image is not that high, but it is not that bad as yours. The package generate a raster image according to the physical size of the graphic device (e.g. the interactive device or pdf, png, ...). Which means, if the output size of the device is small, the size of the raster image is also small and if you zoom the device, the image will not be adjusted and it will blur. 

So I just guess you are using RStudio because the size of the graphic device which locates at the right bottom of the IDE is small. Maybe you can directly save as a pdf file or a png file.

Actually, there is an option `raster_quality` which can control the quality of the raster image. Set a value larger than 1 to this option to get better resolution. Let's say the physical size of the heatmap body has a resolution of  `a x b`, the package will generate a figure in `a*raster_quality x b*raster_quality` resolution and use it as raster image.

I sent you figures which compare different `raster_quality` values by email.

**Comment by sudhirthakurela** [comment]
Hi,

I am trying to reduce the size by "use_raster", however, somehow it is not being recognized as a parameter:
```
pdf("test.pdf", width = 6, height = 10)
EnrichedHeatmap(mat1, col = col_fun, name = "Test", width = 1, cluster_rows=FALSE, show_row_dend=FALSE, use_raster = TRUE, column_title="At All Peaks", top_annotation = HeatmapAnnotation(lines = anno_enriched(gp = gpar(col = 2:4))), top_annotation_height = unit(2, "cm"), row_title_rot = 0)

I am getting following error:
```
Error in Heatmap(mat, row_order = od, cluster_columns = FALSE, cluster_rows = cluster_rows,  : 
  unused argument (use_raster = TRUE)
```
May I know what going wrong?

Sudhir

**Comment by jokergoo** [comment]
You need to install the recent version of the package. Try:

```{r}
library(devtools)
install_github("jokergoo/ComplexHeatmap")
install_github("jokergoo/EnrichedHeatmap")
```

**Comment by sudhirthakurela** [comment]
Hey thanks .. yes, I realized that I had installed from Bioconductor..

Sudhir

**Comment by lwebercoralgirl** [comment]
Hello!

This is a somewhat related question - Is there anyway to extract an ordered matrix from the plotted heatmap that has been clustered hierarchically? I generated a heatmap, but I can't see the rownames to identify which genes are up- or down-regulated.

Thanks!

**Comment by jokergoo** [comment]
Hi @lwebercoralgirl , 

You can do as follows:

```{r}
ht = EnrichedHeatmap(...)
ht = draw(ht)
row_order(ht)
```

**Comment by lwebercoralgirl** [comment]
Thanks for the suggestion- this works, but only gives me the row numbers, not the row names (or the row annotations). I need the row names because there are the KEGG orthology identifiers I am trying to relate back to the heatmap. Any more suggestions?

**Comment by jokergoo** [comment]
Since you already have the index of rows, you can easily get the row names by:

```{r}
rownames(mat)[index]
```

**Comment by crazyhottommy** [comment]
@jokergoo sorry to bug you again. recently I am dealing with heatmap with 20,000 rows, and Rstudio chokes on it and abort ungraciously...what do you do to deal with this situation?

Thanks,
Tommy

**Comment by crazyhottommy** [comment]
it has to do with https://github.com/jokergoo/ComplexHeatmap/issues/129  fixed. thanks!

**Comment by jokergoo** [comment]
It is very common that you have too many rows when dealing with genomic or epigenomic data.

I always randomly sample e.g. 5000 rows from them, and it perfectly keeps the original patterns.


________________________________

**Comment by apfuentes** [comment]
Hi @jokergoo 
I am making a heatmap plot for a file with 36 rows (samples) and 7002 columns (loci). I first generated a PDF file but the image has very poor resolution. Then I found this thread and tried using the raster option (generating a tiff file) but still the image quality is poor:

![test](https://user-images.githubusercontent.com/19496177/41628208-de906998-73f9-11e8-84c0-3dad3746a203.png)

- Any suggestion on how to improve image resolution? Would it be necessary to subset the data file? If so, how this could be done?

- Also, when I tried to set the color bar as 'discrete' and 'horizontal', the color bar is only displayed vertically, whereas if I set the color bar 'continous' and 'horizontal', the bar is actually placed horizontally, may this be a bug?

This is the code I am using:
```
# Set color palette.
col_fun = colorRamp2(c(2.0,20.0,40.0,60.0,80.0,100.0, 140.0), c('#C6DBEF', '#9ECAE1', '#6BAED6', '#4292C6', '#2171B5','#08519C', '#08306B'))

# Open pdf device.
pdf('heatmap_plot.pdf', width = 10, height = 20, paper = 'a4r')

# Obtain the heatmap plot.
ht = Heatmap(t(as.matrix(CNV.data)), col = col_fun, name = 'Normalized copy number',
     cluster_rows = FALSE, cluster_columns = FALSE,
     show_row_names = TRUE, show_column_names = FALSE,
     row_names_side = 'left', row_names_gp = gpar(fontsize = 14),
     width = unit(23, 'cm'),
     heatmap_legend_param = list(
       title_position = 'topcenter', color_bar = 'continuous', legend_direction = 'horizontal', border = TRUE, legend_width = unit(10, 'cm'),
       labels_gp = gpar(fontsize = 12), title_gp = gpar(fontsize = 14, fontface = 'bold'),
       at = c(2,20,40,60,80,100, 140), labels = c('2','20','40','60','80','100','140'))
     )

draw(ht, heatmap_legend_side = 'top')

dev.off()
```

Thanks for your help

**Comment by Muvunyi2020** [comment]
I'm facing a difficulty in obtaining  a high resolution image when running upset function with more than 20 sets. everything seems normal with 6 sets, the problem appears only when the number of gene sets is increased.
Attached are the t, codes and the image that I 'm getting.

Kindly help me to figure out where might be the problem

[script.txt](https://github.com/jokergoo/ComplexHeatmap/files/5101272/script.txt)
![upset_with_rasterR](https://user-images.githubusercontent.com/69953907/90728562-afa75500-e2f7-11ea-9ae7-4554e32e9a07.png)

**Comment by jokergoo** [comment]
Ha, I have already answered you on Research Gate. The following is my reply:

Hi, the number of sets is too big. You have 20 sets and the number of full combination sets will be 2^20 = 2048.

I suggest removing those combination sets with too few elements. E.g. if you set the minimal size of combination sets to 50, then there are only 24 left and you can see the details of the plot.

```r
UpSet(m[comb_size(m) > 50])
```

![image](https://user-images.githubusercontent.com/449218/90731476-072ecc00-e2ca-11ea-9a22-c3892989cd30.png)

**Comment by Muvunyi2020** [comment]
Thank you for your prompt reply!!

**Comment by Muvunyi2020** [comment]
Sorry to bother you again Dear Developer, 
![upset_with_rastersee](https://user-images.githubusercontent.com/69953907/90747793-ef743980-e303-11ea-8a5b-37404aea9080.png)
This the image that I'm getting when trying to tag gene number on the barchart of the intersection size. I have not seen a similar one in your tutorial and want to if what I did it the right way, and how interpret these vertical black bars

codes
ltm <- list_to_matrix(listinput)

m = make_comb_mat(ltm, mode = "intersect")

m <- m[comb_size(m) > 50]

###

ss = set_size(m)
cs = comb_size(m)
ht = UpSet(m, use_raster = TRUE,
           set_order = order(ss),
           comb_order = order(comb_degree(m), -cs),
           top_annotation = HeatmapAnnotation(
             "Genes Intersections" = anno_barplot(cs, 
                                                  ylim = c(0, max(cs)*1.1),
                                                  border = FALSE, 
                                                  gp = gpar(fill = "black"), 
                                                  height = unit(4, "cm")
             ), 
             annotation_name_side = "left", 
             annotation_name_rot = 90),
           left_annotation = rowAnnotation(
             "Genes per set" = anno_barplot(-ss, 
                                               baseline = 0,
                                               axis_param = list(
                                                 at = c(0,-100,-200,-300,-400,-500,-600),
                                                 labels = c(0,100,200,300,400,500,600),
                                                 labels_rot = 0),
                                               border = FALSE, 
                                               gp = gpar(fill = "black"), 
                                               width = unit(4, "cm")
             ),
             set_name = anno_text(set_name(m), 
                                  location = 0.5, 
                                  just = "center",
                                  width = max_text_width(set_name(m)) + unit(4, "mm"))
           ), 
           right_annotation = NULL,
           show_row_names = FALSE)




png("C:/Users/muvun/Desktop/myphoto/upset_with_rastersee.png", width = 1000, height = 600)


ht = draw(ht)
od = column_order(ht)
decorate_annotation("Genes Intersections", {
  grid.text(cs[od], x = seq_along(cs), y = unit(cs[od], "native") + unit(2, "pt"), 
            default.units = "native", just = c("left", "bottom"), 
            gp = gpar(fontsize = 6, col = "#404040"), rot = 45)
})
dev.off()

**Comment by Muvunyi2020** [comment]
I highly appreciate

**Comment by jokergoo** [comment]
Is this the plot made by the code you provided? It does not look like the default style of the `UpSet()` function. And you can create a new issue?

**Comment by Muvunyi2020** [comment]
It's from  UpSet() function.
I used the following codes from you tutorials.

ss = set_size(m)
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-2>cs
= comb_size(m) <https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-3>ht
= UpSet(m,  <https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-4>
   set_order = order(ss),
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-5>
   comb_order = order(comb_degree(m), -cs),
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-6>
   top_annotation = HeatmapAnnotation(
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-7>
       "Genre Intersections" = anno_barplot(cs,
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-8>
           ylim = c(0, max(cs)*1.1),
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-9>
           border = FALSE,
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-10>
           gp = gpar(fill = "black"),
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-11>
           height = unit(4, "cm")
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-12>
       ),  <https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-13>
       annotation_name_side = "left",
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-14>
       annotation_name_rot = 90),
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-15>
   left_annotation = rowAnnotation(
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-16>
       "Movies Per Genre" = anno_barplot(-ss,
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-17>
           baseline = 0,
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-18>
           axis_param = list(
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-19>
               at = c(0, -500, -1000, -1500),
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-20>
               labels = c(0, 500, 1000, 1500),
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-21>
               labels_rot = 0),
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-22>
           border = FALSE,
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-23>
           gp = gpar(fill = "black"),
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-24>
           width = unit(4, "cm")
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-25>
       ), <https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-26>
       set_name = anno_text(set_name(m),
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-27>
           location = 0.5,
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-28>
           just = "center",
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-29>
           width = max_text_width(set_name(m)) + unit(4, "mm"))
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-30>
   ),  <https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-31>
   right_annotation = NULL,
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-32>
   show_row_names = FALSE)
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-33>ht
= draw(ht) <https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-34>od
= column_order(ht)
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-35>decorate_annotation("Genre
Intersections", {
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-36>
   grid.text(cs[od], x = seq_along(cs), y = unit(cs[od], "native") +
unit(2, "pt"),
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-37>
       default.units = "native", just = c("left", "bottom"),
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-38>
       gp = gpar(fontsize = 6, col = "#404040"), rot = 45)
<https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#cb574-39>})
