### ISSUE TITLE
left_annotation for Oncoprint

### ISSUE THREAD

**Issue by Rashesh7** [jokergoo/ComplexHeatmap#291]
Hi Zuguang,

I wanted to move the barplot on the right_annotation to the left. But when I do it, the base of the bars is away from the oncoprint. Is there a way to flip that?

I don't know If I expressed my issue properly, let me know if you have questions. 

Thanks.

**Comment by jokergoo** [comment]
Can you show me the code and the version of the package? For version earlier than 1.99.0 and current versions, there are some differences for setting barplot annotations for the oncoPrint.

**Comment by Rashesh7** [comment]
I am using ComplexHeatmap_1.99.5
So I am making two separate oncoprint and merging them

ht_p=oncoPrint(pmat,get_type = function(x) strsplit(x, ";")[[1]], alter_fun = alter_fun, col = col, row_names_side = "right", show_column_names=TRUE, show_pct = FALSE, **left_annotation = rowAnnotation(rbar = anno_oncoprint_barplot()), right_annotation = NULL**, heatmap_legend_param=list(title ="Mutations", title_gp= gpar(fontsize = 6),labels_gp = gpar(fontsize = 4)), cluster_row_slices=FALSE, row_names_gp = gpar(fontsize = 2), pct_gp = gpar(fontsize = 2), column_order=columnorder_p,  row_split = factor(c(rep("Significantly\nDifferent", 7), rep("dN/dScv", 9), rep("Pathway", 44),rep("Other Significantly\nDifferent", 66), rep("Other drivers", 47)), levels=c("Significantly\nDifferent", "dN/dScv", "Pathway", "Other Significantly\nDifferent", "Other drivers")), remove_empty_rows = TRUE, column_gap = unit(8, "mm"), row_title_gp= gpar(fontsize = 5), column_title_gp = gpar(fontsize = 5), column_names_gp=gpar(fontsize = 4))


ht_np=oncoPrint(npmat,get_type = function(x) strsplit(x, ";")[[1]], alter_fun = alter_fun, col = col, row_names_side = "right", show_column_names=TRUE, show_pct = FALSE, heatmap_legend_param=list(title ="Mutations", title_gp= gpar(fontsize = 6),labels_gp = gpar(fontsize = 4)), cluster_row_slices=FALSE, row_names_gp = gpar(fontsize = 0), pct_gp = gpar(fontsize = 2), column_order=columnorder_np, row_split = factor(c(rep("Significantly\nDifferent", 7), rep("dN/dScv", 9), rep("Pathway", 44),rep("Other Significantly\nDifferent", 66), rep("Other drivers", 47)), levels=c("Significantly\nDifferent", "dN/dScv", "Pathway", "Other Significantly\nDifferent", "Other  drivers")), remove_empty_rows = TRUE, column_gap = unit(8, "mm"), row_title_gp= gpar(fontsize = 5), column_title_gp = gpar(fontsize = 5), column_names_gp=gpar(fontsize = 4), show_heatmap_legend = FALSE)


ht_list=ht_p+ht_np

**Comment by jokergoo** [comment]
Emmm... It is not supported to reverse the direction of axis if it is put to the left of the oncoprint...

**Comment by jokergoo** [comment]
#294

**Comment by Rashesh7** [comment]
Cool. Thank you.
I had another question.
When I split the columns in the oncoprint, it automatically re-orders the samples within each slice. Is there a way to turn it off?
I am already using column_order=NULL and cluster_column_slices = FALSE

Thanks.

**Comment by Rashesh7** [comment]
I found a way, I am just giving it column_order, Thanks.

**Comment by jokergoo** [comment]
Hi, I just updated the package. To reverse the axis, set as following:

```r
mat = read.table(textConnection(
"s1,s2,s3
g1,snv;indel,snv,indel
g2,,snv;indel,snv
g3,snv,,indel;snv"), row.names = 1, header = TRUE, sep = ",", stringsAsFactors = FALSE)
mat = as.matrix(mat)

col = c(snv = "red", indel = "blue")

alter_fun = list(
    snv = function(x, y, w, h) grid.rect(x, y, w*0.9, h*0.9, 
        gp = gpar(fill = col["snv"], col = NA)),
    indel = function(x, y, w, h) grid.rect(x, y, w*0.9, h*0.4, 
        gp = gpar(fill = col["indel"], col = NA))
)

oncoPrint(mat, alter_fun = alter_fun, col = col, 
	left_annotation =  rowAnnotation(
		rbar = anno_oncoprint_barplot(
			axis_param = list(direction = "reverse")
	)),
	right_annotation = NULL)
```
![image](https://user-images.githubusercontent.com/449218/56356663-c86e9a80-61d9-11e9-94d0-e5cbcc21be20.png)

**Comment by Rashesh7** [comment]
Awesome Zuguang! Thank you.
