### ISSUE TITLE
Dividing by Columns & Rows Doesn't Work - Even Using Example from the e-Booklet

### ISSUE THREAD

**Issue by SolebaySharp** [jokergoo/ComplexHeatmap#292]
Summary: Dividing by rows and columns doesn't work even when using the example command and data from the booklet. Instead of an 'unused arguments' error is returned. Everything is up to date, is it a bug or am I not understanding something?

When I try to run the split rows and columns command:

```
Heatmap(mat, name = "mat", 
        row_split = rep(c("A", "B"), 9), column_split = rep(c("C", "D"), 12))
```

I get the following error:

```
Error in Heatmap(mat, name = "mat", row_split = rep(c("A", "B"), 9), column_split = rep(c("C",  : 
  unused arguments (row_split = rep(c("A", "B"), 9), column_split = rep(c("C", "D"), 12))
```

Despite the fact that the command and the matrix I am using comes straight from the booklet.

**Comment by crazyhottommy** [comment]
you should update your package to the latest version.

**Comment by SolebaySharp** [comment]
I am using version 1.99.7,

If I try to update further using

```
> library(devtools)
> install_github("jokergoo/ComplexHeatmap")
```
I get the message:

`Skipping install of 'ComplexHeatmap' from a github remote, the SHA1 (c79aaf9e) has not changed since last install.`

I'm not sure of the syntax around using

`force = TRUE`

But even if I could get that command to work surely I am up to date. My version of R is also the most recent.

**Comment by SolebaySharp** [comment]
Blimey, all this time and using 

`install_github("jokergoo/ComplexHeatmap", force = TRUE)`

Was all I needed. Apolagies @crazyhottommy , I didn't undertsand the importance of playing it safe and forcing another install. Cheers for the prompt.

**Comment by jokergoo** [comment]
The current documentation book corresponds to the development version of this package. It will be released to the Bioconductor released branch at the end of this month (I think). So currently you can only install it from github.
