### ISSUE TITLE
Ordering rows within split heat map portions the same way automatically

### ISSUE THREAD

**Issue by ceesu** [jokergoo/ComplexHeatmap#293]
Hi, thanks for this great package! 

I'm wondering if it's possible if when we make a split heatmap such as in section 2.7.2, and have clustering on each portion, that we could set an option such that the individual portions could be the same way (e.g. from most divergent to least divergent or something like this).

For example, in this image I made using ComplexHeatmap, there is row clustering of individual sections, and two groups of columns. I've drawn arrows pointing to two sections; in the top indicated section the rows seem to be ordered from most divergent to least divergent between the groups of columns, whereas in the bottom indicated section it seems to have happened the opposite way.

<img width="873" alt="ex" src="https://user-images.githubusercontent.com/13499799/56220550-9ffa6b00-6036-11e9-8531-057f02288ce8.png">

To my understanding you can manually set the order of the rows but if possible it would be nice for this to happen automatically when you cluster. I looked through the issues but I believe that what I'm looking for has not been exactly mentioned -- apologies if I missed something, though.

**Comment by jokergoo** [comment]
Hi, this relates to [the reordering of the dendrograms](https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#reorder-dendrograms). The thing for your question is how to define "the same way". By default the dendrograms are reordered by the mean of each row. For your case, a simple solution is to reorder based on the mean of the last two columns:

```r
Heatmap(..., row_dend_reorder = rowMeans(m[, 3:4]))
```

**Comment by ceesu** [comment]
Thanks for your response, this worked for me!
