### ISSUE TITLE
control ordering of discrete legend

### ISSUE THREAD

**Issue by janstrauss1** [jokergoo/ComplexHeatmap#296]
Dear @jokergoo,

I am trying to change the order of a discrete heatmap legend but could not find a solution.

Please see below for an example from the [ComplexHeatmap vignette](https://bioconductor.org/packages/release/bioc/vignettes/ComplexHeatmap/inst/doc/s5.legend.html#toc_2) to explain what I would like to do.

```
set.seed(123)
mat = matrix(rnorm(80, 2), 8, 10)
mat = rbind(mat, matrix(rnorm(40, -2), 4, 10))
rownames(mat) = paste0("R", 1:12)
colnames(mat) = paste0("C", 1:10)

ha_chr = rowAnnotation(chr = sample(paste0("chr", 1:20), nrow(mat), replace = TRUE),
                       annotation_legend_param = list(chr = list(ncol = 2, title = "chromosome", title_position = "topcenter")),
                       width = unit(5, "mm"))
ht1 = Heatmap(mat, name = "ht1")
ht1 + ha_chr
```
![ComplexHeatmap](https://user-images.githubusercontent.com/28350852/56294500-6e170080-612b-11e9-8542-c79dca50cd45.png)

What I would like to achieve is to set a custom ordering of the discrete legend for chromosomes (e.g. in chronological order from chr4, chr5, chr6 ... chr20).

Is there maybe way to control this by `annotation_legend_param` or `heatmap_legend_param` (in case of a discrete heatmap legend)?

Many thanks in advance for your help!

**Comment by jokergoo** [comment]
You need to manually set the order of the labels either by `at` or `labels`, or else it takes `unique(your-chr-vector)`.

```r
set.seed(123)
mat = matrix(rnorm(80, 2), 8, 10)
mat = rbind(mat, matrix(rnorm(40, -2), 4, 10))
rownames(mat) = paste0("R", 1:12)
colnames(mat) = paste0("C", 1:10)

chr = sample(paste0("chr", 1:20), nrow(mat), replace = TRUE)
chr_level = intersect(paste0("chr", 1:20), chr)
ha_chr = rowAnnotation(chr = chr,
                       annotation_legend_param = list(chr = list(
                       	ncol = 2, 
                       	title = "chromosome", 
                       	title_position = "topcenter",
                       	labels = chr_level)),
                       width = unit(5, "mm"))
ht1 = Heatmap(mat, name = "ht1")
ht1 + ha_chr
```

![image](https://user-images.githubusercontent.com/449218/56297063-ebdd0b00-612f-11e9-9df5-d19048f003bf.png)

**Comment by guanxn90** [comment]
@jokergoo Hi Jokergoo, I came across a similar question and found this thread on github. However, one problem is that after ordering the legend using labels = chr_level, the color in the heatmap body row annotation does not match the color in the legend. Thanks a lot for your help

Thanks,
Guan

Please see codes to reproduce the problem:

set.seed(123)
rownames(mat) = paste0("R", c(1,4,10,12))
colnames(mat) = paste0("C", 1:5)

chr = c('chr1', 'chr4', 'chr10', 'chr12')
chr_level = intersect(paste0("chr", 1:20), chr)


# the color does not match
ha_chr = rowAnnotation(chr = chr,
                       col = list(chr = c('chr1' = 'red', 'chr4' = 'green', 'chr10' = 'grey', 'chr12' = 'blue')),
                       annotation_legend_param = list(chr = list(
                         ncol = 2, 
                         title = "chromosome", 
                         title_position = "topcenter",
                         labels = chr_level)),
                       width = unit(5, "mm"))

 no cluster so that the order matches
 the color does not match
ht1 = Heatmap(mat, name = "ht1", cluster_rows = F, cluster_columns = F, right_annotation = ha_chr)
ht1

e.g. R4 should corresponds to chr4 and has grey color
<img width="751" alt="image" src="https://user-images.githubusercontent.com/43798417/159957711-20b5da9d-7f42-42e2-bb1b-8a0551ff23b3.png">


# the color matches
ha_chr_2 = rowAnnotation(chr = chr,
                         col = list(chr = c('chr1' = 'red', 'chr4' = 'green', 'chr10' = 'grey', 'chr12' = 'blue')),
                         annotation_legend_param = list(chr = list(
                           ncol = 2, 
                           title = "chromosome", 
                           title_position = "topcenter"
                           )),
                         width = unit(5, "mm"))

no cluster so that the order matches
the color does not match
ht2 = Heatmap(mat, name = "ht1", cluster_rows = F, cluster_columns = F, right_annotation = ha_chr_2)
ht2 

color matches well, but now the legend order is not as chromosome order
<img width="748" alt="image" src="https://user-images.githubusercontent.com/43798417/159958121-ca1cdb6f-5f6c-4bf8-8300-923042f38848.png">

**Comment by jokergoo** [comment]
The order of `labels` always correspond to the order of `at`, without specifying `at`, `at` is by default taken as `unique(chr)`.

```r
ha_chr = rowAnnotation(chr = chr,
                       col = list(chr = c('chr1' = 'red', 'chr4' = 'green', 'chr10' = 'grey', 'chr12' = 'blue')),
                       annotation_legend_param = list(chr = list(
                         ncol = 2, 
                         title = "chromosome", 
                         title_position = "topcenter",
                         labels = chr_level)),
                       width = unit(5, "mm"))
```

I would suggest to set `at` and `labels` at the same time, or simply set `at` while not `labels`:

```r
ha_chr = rowAnnotation(chr = chr,
                       col = list(chr = c('chr1' = 'red', 'chr4' = 'green', 'chr10' = 'grey', 'chr12' = 'blue')),
                       annotation_legend_param = list(chr = list(
                         ncol = 2, 
                         title = "chromosome", 
                         title_position = "topcenter",
                         at = chr_level)),
                       width = unit(5, "mm"))
```

**Comment by guanxn90** [comment]
@jokergoo Thank you so much. Setting `at` works perfectly. Now I understand that `at` is like the factor level, and `label` is like factor label. 

Thanks,
Guan

**Comment by ddressman91** [comment]
Hello, I am trying to fix a similar problem to others in this thread.  I have a heatmap with three nested rows of column annotations above it.  The color coding of all three rows matches as needed, but the annotation legends are shown in alphabetical order.  Please forgive my formatting, as I am new to Github and have only barely used R Markdown.

Code for setting the color code and labels for the annotations is below:

ann_colors = list(Cell.Type = c("CD4+CD45RO-" = "#e41a1c", "CD4+CD45RO+" = "#4daf4a",
                                "CD8+CD45RO-" = "#377eb8", "CD8+CD45RO+" = "#984ea3"), 
                  Trait.Type = c("Immunity and Inflammation" = "#66c2a5", "Autoimmune Disease" = "#fc8d62",
                                 "Neurological Disease" = "#8da0cb", "Psychiatric Disorders" = "#e78ac3"),
                  Trait = c("Lymphocyte counts" = "dodgerblue2", "WBC counts"  = "#E31A1C", "C-reactive protein" = "green4",
                            "Ulcerative colitis" = "#6A3D9A", "Crohn's disease" = "#FF7F00", "Multiple sclerosis" = "black",
                            "Rheumatoid arthritis" = "gold1", "Systemic lupus erythematosus" = "skyblue2",
                            "Type 1 diabetes" = "#FB9A99", "Alzheimer's disease" = "palegreen2",
                            "Parkinson's disease" = "#CAB2D6", "Amyotrophic lateral sclerosis" = "#FDBF6F", "Epilepsy" = "gray70",
                            "Stroke" = "khaki2", "Bipolar disorder" = "maroon", "Major depressive disorder" = "orchid1",
                            "Schizophrenia" = "deeppink1", "Anxiety disorder" = "blue1",
                            "Post-traumatic stress disorder" = "steelblue4"))
ann_labels = list(Cell.Type = c("CD4+CD45RO-", "CD4+CD45RO+",
                                "CD8+CD45RO-", "CD8+CD45RO+" ), 
                  Trait.Type = c("Immunity and Inflammation", "Autoimmune Disease",
                                 "Neurological Disease", "Psychiatric Disorders"),
                  Trait = c("Lymphocyte counts", "WBC counts", "C-reactive protein",
                            "Ulcerative colitis", "Crohn's disease", "Multiple sclerosis",
                            "Rheumatoid arthritis", "Systemic lupus erythematosus",
                            "Type 1 diabetes", "Alzheimer's disease",
                            "Parkinson's disease", "Amyotrophic lateral sclerosis", "Epilepsy",
                            "Stroke", "Bipolar disorder", "Major depressive disorder",
                            "Schizophrenia", "Anxiety disorder",
                            "Post-traumatic stress disorder"))

I also have the variable "col_annotations", which is the attached .csv file, that matches the annotations to the heatmap columns.

[Column annotations for all sig genes.csv](https://github.com/jokergoo/ComplexHeatmap/files/10788782/Column.annotations.for.all.sig.genes.csv)

Here is my code for creating the Heatmap Annotation object:

ha<-HeatmapAnnotation(df = col_annotations, col = ann_colors, which = "column",
                      annotation_legend_param = list(labels = ann_labels))

When I run it without the annotation_legend_param argument, it works just fine, it just puts the labels in alphabetical order in the legend.  When I run it with the annotation_legend_param call, it gives the following error:

Error: Some names in 'annotation_legend_param' are not in names of simple annotations.

Even though the names in ann_labels match those in ann_colors and col_annotations.  Is the problem something to do with the fact that I have three nested annotation rows up top?  How do I change my code to get the labels to run in the order I provide?

Thanks in advance!

**Comment by ddressman91** [comment]
I figured it out.  I used nested lists with the same arguments for "at" and "labels" for each legend, and it output the legend with the traits in the order I gave, rather than coerced to alphabetical order.  Updated code to set ann_labels is below:

ann_labels = list(
  Cell.Type = list(
    title = "Cell type",
    at = c("CD4+CD45RO-", "CD4+CD45RO+", "CD8+CD45RO-", "CD8+CD45RO+"),
    labels = c("CD4+CD45RO-", "CD4+CD45RO+", "CD8+CD45RO-", "CD8+CD45RO+")),
  Trait.Type = list(
    title = "Trait type",
    at = c("Immunity and Inflammation", "Autoimmune Disease",
           "Neurological Disease", "Psychiatric Disorders"),
    labels = c("Immunity and Inflammation", "Autoimmune Disease",
               "Neurological Disease", "Psychiatric Disorders")),
  Trait = list(
    title = "Trait",
    at = c("Lymphocyte counts", "White blood cell counts", "C-reactive protein",
           "Ulcerative colitis", "Crohn's disease", "Multiple sclerosis",
           "Rheumatoid arthritis", "Systemic lupus erythematosus",
           "Type 1 diabetes", "Alzheimer's disease",
           "Parkinson's disease", "Amyotrophic lateral sclerosis", "Epilepsy",
           "Stroke", "Bipolar disorder", "Major depressive disorder",
           "Schizophrenia", "Anxiety disorder",
           "Post-traumatic stress disorder"),
    labels = c("Lymphocyte counts", "White blood cell counts", "C-reactive protein",
               "Ulcerative colitis", "Crohn's disease", "Multiple sclerosis",
               "Rheumatoid arthritis", "Systemic lupus erythematosus",
               "Type 1 diabetes", "Alzheimer's disease",
               "Parkinson's disease", "Amyotrophic lateral sclerosis", "Epilepsy",
               "Stroke", "Bipolar disorder", "Major depressive disorder",
               "Schizophrenia", "Anxiety disorder",
               "Post-traumatic stress disorder")))

**Comment by mainharryHR** [comment]
Dear everyone, I still do not know how to integrate the above discussion into my pipeline. Please help!

`desired_order_of_categories <- c(
   "B naïve", "B Memory",  "IgG",
   "IgA1", "IgA2","IgA3"
  )`
`BcellsControltrunc <- BcellsControlAggregate %>%
  
  filter(aggregate_rank <= 0.01) # note that these pvals are already corrected

 heat_freq(BcellsControltrunc)`
