### ISSUE TITLE
Extraneous dotted line when splitting heatmap

### ISSUE THREAD

**Issue by erikor** [jokergoo/ComplexHeatmap#298]
When I split a heatmap, I get an extra dotted line between the plot and the split category labels.

```
library(ComplexHeatmap)
dat <- matrix(rnorm(100), ncol=10, nrow=10)
type <- c(rep("ONE", 5), rep("TWO", 5))
Heatmap(dat, split=type)

```
![image](https://user-images.githubusercontent.com/835980/56438096-c5de7480-62af-11e9-8f1d-b90db80d7b34.png)

Some session details:
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

other attached packages:
 [1] ComplexHeatmap_1.99.7

```

**Comment by jokergoo** [comment]
Please see the last paragraph in section 2.7.2. https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#split-by-categorical-variables

**Comment by erikor** [comment]
Ah...now I get it.  Thank you.
