### ISSUE TITLE
Change the size of legend text?

### ISSUE THREAD

**Issue by slowkow** [jokergoo/ComplexHeatmap#3]
Thanks for the excellent package!

I see that the legend title font size can be changed like this:

```r
draw(...,  legend_title_gp = gpar(fontsize = 18, fontface = "bold") )
```

However, I don't see any examples showing how to change the font size of the legend text. Could you please advise?

Ideally, I would like to simply pass an argument called `legend_gp` or `legend_text_gp` but I can't seem to find an easy way to do this.

Alternatively, is there a way to do this by creating a [custom legend][1]?

[1]: https://github.com/jokergoo/ComplexHeatmap/blob/master/vignettes/ComplexHeatmap.Rmd#legends

**Comment by jokergoo** [comment]
The option for setting legend text graphical parameters is `legend_label_gp`. 

You can create a custom legend, but it should be a `grob` object and it is always not easy.

**Comment by slowkow** [comment]
Thanks!

**Comment by zillurbmb51** [comment]
Hello there, I wanted to increase the legend size but failed. my codes are:
```
colAnn <- HeatmapAnnotation(df=anndata, which="col", col=colours, gap=unit(1, "mm"),gp = gpar(fontsize = 88))
rowAnn=HeatmapAnnotation(df=anndata2,which = 'row',col=color2, gap=unit(1, "mm"),gp = gpar(fontsize = 88))
boxplotcol2 <- HeatmapAnnotation(
  boxplot=anno_boxplot(data.matrix(cpm8),
                       border=TRUE,
                       gp=gpar(fill="#CCCCCC"),
                       pch=".",
                       size=unit(4, "mm"),
                       axis=TRUE,
                       axis_param = list(side = "left"),
                       annotation_width=unit(c(1, 9.0), "cm"),
                       which="col"))

png('../results/heatmap_dna_repair3.png',width = 1331,height = 2772)
ht2=Heatmap(data.matrix(cpm8),top_annotation = colAnn, left_annotation = rowAnn,
        bottom_annotation = boxplotcol2,
        name = "logCPM",
        col = rainbow(7), 
        show_row_names = T,
        show_column_names = FALSE,
        cluster_rows = F,
        cluster_columns = F,row_names_gp = gpar(fontsize = 88), 
        width = unit(300, "mm"))+rowAnnotation(rn = anno_text(rownames(cpm8)))

draw(ht2, heatmap_legend_side = "left", annotation_legend_side = "right",legend_label_gp=gpar(fontsize=12))
dev.off()

```
I am getting the attached figure. How can I increase all text size in this figure? Thanks in advance. Best, Zillur
![heatmap_dna_repair3](https://user-images.githubusercontent.com/12833907/71526606-0e721700-28ae-11ea-8afb-398297c2b3c6.png)
I am trying for todays but hopeless. I tried legend_label_gp but no success.

**Comment by iiitdmadhu** [comment]
I also faced the same problem.

**Comment by aleonti** [comment]
For anyone finding this issue via Google (like I did), I found the solution to the unanswered questions above: draw the heatmap and use the parameters `legend_labels_gp` and/or `legend_title_gp` to increase the font size of the legend. Example:

```
draw(..., legend_labels_gp = gpar(fontsize = 15)
```

It would seem that, in newer versions of the package, the original answer to this issue no longer works. There needs to be an "s" in labels. I found these parameters by looking at the help page for "draw-HeatmapList-method {ComplexHeatmap}"

**Comment by jokergoo** [comment]
@zillurbmb51 I am sorry I missed your message. 

@iiitdmadhu 

You should set inside `Heatmap()`:

```r
Heatmap(..., heatmap_legend_param = list(legend_gp = gpar(fontsize = 12)))
```

**Comment by krejciadam** [comment]
> @zillurbmb51 I am sorry I missed your message.
> 
> @iiitdmadhu
> 
> You should set inside `Heatmap()`:
> 
> ```r
> Heatmap(..., heatmap_legend_param = list(legend_gp = gpar(fontsize = 12)))
> ```

Hi! I'm trying and this does not seem to work: 

```r
Heatmap(matrix(c(1:4), ncol=2), heatmap_legend_param = list(legend_gp = gpar(fontsize = 20)))
```

`fontsize` used like this has no effect on actual legend font size. 
(ComplexHeatmap v. 2.12.0)

Thanks!

**Comment by BertramLoong** [comment]
> Oh I see! not ~`legend_gp`~ but `labels_gp` that does the trick!
Sorry, could you please be more detailed?

**Comment by hridoy04** [comment]
heatmap_legend_param = list(labels_gp = gpar(fontsize = 16, fontface = 'bold'), 
                                    title_gp = gpar(fontsize=28, fontface = 'bold'))
title_gp = gpar(fontsize=28, fontface = 'bold') changes legend title/name
