### ISSUE TITLE
save dendrogram & annotation track (without heatmap)

### ISSUE THREAD

**Issue by itsvenu** [jokergoo/ComplexHeatmap#301]
Hi Zuguang,

As title says, I would like to save column dendrogram and annotation to pdf. I didn't find any info in the manual regarding this (or did I miss anything?). Is it possible yet all?

Thanks a lot for the awesome package.

**Comment by jokergoo** [comment]
What do you mean by "to save column dendrogram and annotation to pdf"? Do you mean to save the whole plot as a PDF? If so, just put pdf() in front of your heatmap calls:

```r
pdf(...)
Heatmap(...)
dev.off()
```

**Comment by itsvenu** [comment]
Thanks for the reply. I would like to save only dendrogram and annotation track without heatmap.
Somethings like this: [this, `adding colored bars`](https://cran.r-project.org/web/packages/dendextend/vignettes/introduction.html#adding-extra-bars-and-rectangles)

Thank you.

**Comment by itsvenu** [comment]
aw, alright then.
Thank you.

**Comment by jokergoo** [comment]
Or you can treat the heatmap annotations as heatmaps. Compare following two heatmaps:

```r

m = matrix(rnorm(100), 10)
dend = as.dendrogram(hclust(dist(t(m))))

Heatmap(m, cluster_columns = dend, 
	top_annotation = HeatmapAnnotation(foo = 1:10, bar = anno_barplot(1:10)))

# take the first heatmap annotation as a normal heatmap (one-row heatmap)
Heatmap(rbind(1:10), cluster_columns = dend, height = unit(5, "mm"), 
	top_annotation = HeatmapAnnotation(bar = anno_barplot(1:10)))
```

**Comment by itsvenu** [comment]
That trick seems to do what I want. Thanks a lot.

**Comment by jokergoo** [comment]
I've updated the package. Now you just set a zero-row or zero-column matrix to the heatmap. See the following example:

```r
hc = hclust(dist(matrix(rnorm(100), 10)))
Heatmap(matrix(nc = 0, nr = 10), cluster_rows = hc, 
	right_annotation = rowAnnotation(
		foo = anno_points(1:10),
		sth = 1:10,
		bar = anno_barplot(1:10)),
	row_split = 2)
```

<img src="https://user-images.githubusercontent.com/449218/56882485-008c9d80-6a64-11e9-8de7-655a8d5a4194.png" height=500/>

**Comment by itsvenu** [comment]
Hi Zuguang,

this is really awesome. Thanks a lot. Should I install directly from github?

**Comment by jokergoo** [comment]
Yes.

**Comment by jokergoo** [comment]
Hi @iranmdl , can you post it in a new issue and also add code and plot there? Then I will have a look.
