### ISSUE TITLE
Error when row_sub_title_side is used in draw() function for rowAnnotation + Heatmap

### ISSUE THREAD

**Issue by lakhanp1** [jokergoo/ComplexHeatmap#303]
Hi Zuguang,

I am using `ComplexHeatmap v1.99.6`.
When I try to use `row_sub_title_side = "left"` inside `draw()` function for a heatmap list of rowAnnotation + Heatmap, the `draw()` method fails with error. `row_sub_title_side = "left"` argument works fine for a heatmap list of Heatmap + Heatmap.

Please refer below for the reproducible example generated from your documentation book.
In the code below, a `rowAnnotation` (htAn) as well as `Heatmap` (ht2) is generated for same one column data. `ht1` is the main heatmap in which `split` argument is used to split the rows into three groups.
```R

library(ComplexHeatmap)

set.seed(123)
mat1 <- matrix(rnorm(80, 2), 8, 10)
mat1 <- rbind(mat1, matrix(rnorm(40, -2), 4, 10))
rownames(mat1) <- paste0("R", 1:12)
colnames(mat1) <- paste0("C", 1:10)

le <- sample(letters[1:3], 12, replace = TRUE)
names(le) <- paste0("R", 1:12)

ind <- sample(12, 12)
mat1 <- mat1[ind, ]

le <- le[ind]

## main heatmap
ht1 <- Heatmap(mat1, name = "rnorm", split = le)

## row group as rowAnnotation
htAn <- rowAnnotation(grp = le,
                      col = list(grp = c("a" = "red", "b" = "green", "c" = "blue")))

## row group as Heatmap
ht2 <- Heatmap(matrix = le,
               name = "letters",
               col = c("a" = "red", "b" = "green", "c" = "blue"))

## Heatmap + Heatmap combination
htList1 <- ht2 + ht1

## rowAnnotation + Heatmap combination
htList2 <- htAn + ht1

```

Now when I use Heatmap + Heatamp combination, everything works fine, even when I use `row_sub_title_side = "left"` inside `draw()` function.
```R
## this works in case of Heatmap + Heatmap
draw(object = htList1,
     column_title = "Heatmap + Heatmap combination",
     main_heatmap = "rnorm", row_sub_title_side = "left", row_dend_side = "left")
```

When I use rowAnnotation + Heatmap combination, `draw()` methods generate plot where row sub titles are between rowAnnotation and main heatmap. 
```R
## this works but row sub titles are between row annotation and main heatmap
draw(htList2, column_title = "rowAnnotation + Heatmap combination")
```
This does not look good and  `row_sub_title_side = "left"` inside `draw()` function is the solution to shift row subtitles to left. Now when I try to use `row_sub_title_side = "left"` inside `draw()` function, it gives error.
```R
## Do not run
draw(htList2,
     column_title = "rowAnnotation + Heatmap combination",
     row_sub_title_side = "left")
```

Error message:
Error in seq_len(nrow(ht_layout_index)) : 
  argument must be coercible to non-negative integer
In addition: Warning message:
In seq_len(nrow(ht_layout_index)) :
  first element used of 'length.out' argument

Can you please look into this. Thank you for developing ComplexHeatmap.

Regards,
Lakhan.

**Comment by jokergoo** [comment]
It seems there will be errors when the first or the last element in the heatmap list is an independent  `HeatmapAnnotation()` object (e.g. `rowAnnotation() + Heatmap() + ...` or `Heatmap() + ... + rowAnnotation()`). I will try to fix it soon.

Currently, the workaround is to set `htAn` as a component of the heatmap as a left annotation or a right annotation:

```r
ht1 <- Heatmap(mat1, name = "rnorm", split = le,
	left_annotation = htAn)

draw(ht1 + ht2, main_heatmap = "rnorm",
     column_title = "rowAnnotation + Heatmap combination",
     row_sub_title_side = "left")
```

**Comment by jokergoo** [comment]
Hi, I've updated the package. Now it works as you expect:

```r
## main heatmap
ht1 <- Heatmap(mat1, name = "rnorm", split = le)

## row group as rowAnnotation
htAn <- rowAnnotation(grp = le,
                      col = list(grp = c("a" = "red", "b" = "green", "c" = "blue")))

draw(htAn + ht1, 
     column_title = "rowAnnotation + Heatmap combination",
     row_sub_title_side = "left",
     row_dend_side = "left")
```

![image](https://user-images.githubusercontent.com/449218/56882276-72181c00-6a63-11e9-94ee-2b5ea9ad2ae2.png)

**Comment by lakhanp1** [comment]
Thank you very much Zuguang.
