### ISSUE TITLE
Apply customized dendrogram to heatmap

### ISSUE THREAD

**Issue by stingo93** [jokergoo/ComplexHeatmap#305]
Hey, 
I was wondering how to apply my customized dendrogram to the heatmap. I first generated a heatmap with specified clustering method in Heatmap commend: 

`Heatmap(matrix_new, 
              cluster_columns =T,
              cluster_rows=F,
              clustering_distance_columns = "pearson",
              clustering_method_columns = "ward.D")`

Then, I customized the dendrogram using the following codes 

`hc <- hclust(as.dist(1-cor(t(sample.norm[,1:18]),method="pearson")),method="ward.D")`
`dd <- as.dendrogram(hc)`
`dd.reorder = reorder(dd, c(rep(10, 22),rep(9,27),rep(1,49)), agglo.FUN = mean)`

When I plot the customized dendrogram, it did changed into the way I want. And I assigned the customized dendrogram to the heatmap I created at the first: 

`Heatmap(matrix_new, 
        cluster_columns = dd.reorder,
        cluster_rows=F)`

However, the dendrograms in two heatmaps did not change. I am not sure what went wrong, and come here for some help. Any advise?

Thanks,
Stingo

**Comment by jokergoo** [comment]
Hi, can you send me all these R objects that you use in your code (e.g. `matrix_new`, `matrix_norm`, ...) so that I can have a test?

**Comment by GScala** [comment]
Hi, I'm experiencing a similiar (if not the same) problem here.
When I pass a custom dendrogram using the ### cluster_columns arguments to the ### Heatmap function, the ordering of the columns does not change at all.
Here is some code tath reproduce my issue:

`
mat <- matrix(c(5, 2.28, 2.06, -3.53,-3.53,-3.53, -5,-3,-2.3,3,3.82, 3.82,-5,-2.36,-3.23,3.82,-3.53,-3.53, -5,-1.15,-2,0, 0.92,-0.92, -5,-2.54,-2.30,0, -3.53,-3.53,5,3, 2.37, -3.53, -3.53,-3.53), nrow = 6, ncol = 6, byrow = T, dimnames = list(paste0("row_",c("A","B","C","D","E","F")), paste0("col_",c("A","B","C","D","E","F"))))

# reorder the dendrogram with rotate from dendextend package
col_order = 1:6
column_dend = as.dendrogram(hclust(dist(t(mat))))
column_dend = dendextend::rotate(column_dend,col_order)

plot(column_dend)

cluster_columns = column_dend
# cluster_columns is of class dendrogram as required by the function
class(cluster_columns)

ht1 <- Heatmap(mat, cluster_rows = F, cluster_columns = cluster_columns, show_heatmap_legend = TRUE)

draw(ht1, heatmap_legend_side = "top")
`
Here I was expecting in the heatmap the same column order as in ### plot(column_dend).
Do you have any suggestion?

Thanks very much for the help.
Giovanni.

**Comment by jokergoo** [comment]
@GScala I tried your code and they look the same:

![image](https://user-images.githubusercontent.com/449218/59260513-06b59280-8c3c-11e9-8ce1-60e8d195bcd3.png)

Maybe you need to try the newest version of the package, or at least >= 1.99.0

**Comment by GScala** [comment]
Hi,
it was actually a package version problem. 
I upgraded the package to the latest version and now it works.
Thank you very  much for your help!

**Comment by alimayy** [comment]
hi @jokergoo , I cannot get this to work. My situation:

I have a matrix composed of m rows (assume they're strains) and n columns (assume they're genes). Assume I have gene presence absence data for samples (m x n matrix). Assume also that I have a clustering (dendrogram) of strains (m) based on another dataset than the gene absence/presence matrix. Assume that for the genes (n) I have a separate clustering (dendrogram) too, generated using by a third, separate dataset (e.g. gene similarity).

The gene presence/absence data where the rows and columns sorted with respect to the order in the dendrograms mentioned above looks like this 
```
ComplexHeatmap::Heatmap(as.matrix(mat_to_plot),
                           show_row_names = F,
                           show_column_names = F,
                           cluster_rows = F,
                           cluster_columns = F,
                           name="Phage-host interactions",
                           col = colorRampPalette(c('black', 'green'))(2),
                           show_column_dend = F,
                           show_row_dend = F )

```
![image](https://user-images.githubusercontent.com/22055534/175666448-3a1c9e98-abef-42df-8963-706fbe94673e.png)
Note that it starts with sample ST-21 and ends with ST-139, which is the correct order given the sample dendrogram mentioned above.

When I include the dendrograms in the plot:

```
ComplexHeatmap::Heatmap(as.matrix(mat_to_plot),
                        show_row_names = T,
                        show_column_names = F,
                        cluster_columns = as.dendrogram(gene_clustering_based_on_prank_alignment),
                        cluster_rows = as.dendrogram(sample_hclust_clustering),
                        name="Phage-host interactions",
                        col = colorRampPalette(c('black', 'green'))(2),
                        show_column_dend = T,
                        show_row_dend = T )
```

I get
![image](https://user-images.githubusercontent.com/22055534/175666944-4c08cacb-d2a5-4b4f-97f6-c62b0f1cc39c.png)

so the dendrograms are correctly plotted, but the order of rows and columns are totally wrong, resulting in a totally different heatmap than the first one. 

Is there a way I can plot the dendrograms and still get the first heatmap?

**Comment by alimayy** [comment]
@jokergoo I don't get it. In the first heatmap above, the rows and columns are pre-sorted based on the order of labels of the dendrograms plotted in the second heatmap (see the variables `strain_order` and `gene_order` first code block). That's why the unclustered heatmap of `mat_to_plot ` (the first heatmap) shows some clustering (green blocks). 

In the second heatmap where the dendrograms are plotted, although the dendrograms themselves are plotted correctly, the order of rows and columns shown don't match the order obtained by 

```
strain_order <- row.names(t(sample_dataframe))[rev(order.hclust(samples.dist.clus))]
gene_order <- labels(gene_clustering)
```

and therefore the clusters in the first heatmap aren't observed anymore. I don't think this is expected behavior?

**Comment by metalichen** [comment]
Same problem. The dendrogram is plotted correctly, but the row order doesn't match it. On the screen grab, the left part is the same dendrogram plotted via `plot(as.phylo(as.hclust(row_clust)))`, and the right part is the heatmap. The dendrogram topology is the same, but the row labels are off. The command I used was 
```
Heatmap(M2, show_row_names = T, show_column_names = T, name = " ",
                      column_order = column_order_vector,
                     cluster_rows = row_clust,
                      right_annotation = ra)
```
<img width="1121" alt="Screen Shot 2022-08-24 at 10 33 57 PM" src="https://user-images.githubusercontent.com/29495034/186575754-cb31c2a2-daf4-4e95-bf95-4f60e09f42e3.png">

**Comment by metalichen** [comment]
@jokergoo I used 
```
row_clust = DECIPHER::ReadDendrogram("~/Downloads/dendrogram.txt",keepRoot = T)
```

**Comment by metalichen** [comment]
makes sense! thanks

**Comment by alimayy** [comment]
> @alimayy sorry I didn't read your replies carefully.
> 
> In your code:
> 
> ```r
> ComplexHeatmap::Heatmap(as.matrix(mat_to_plot),
>                         show_row_names = T,
>                         show_column_names = F,
>                         cluster_columns = as.dendrogram(gene_clustering_based_on_prank_alignment),
>                         cluster_rows = as.dendrogram(sample_hclust_clustering),
>                         name="Phage-host interactions",
>                         col = colorRampPalette(c('black', 'green'))(2),
>                         show_column_dend = T,
>                         show_row_dend = T )
> ```
> 
> `mat_to_plot` has already been sorted, but you also provide `gene_clustering_based_on_prank_alignment` and `sample_hclust_clustering` again. And actually the `mat_to_plot` will be sorted again.
> 
> If you want the same plot as the first one, you need to use the original `mydataframe` and suppress reordering of dendrograms:
> 
> ```r
> Heamtap(mydataframe, ..., row_dend_reorder = FALSE, column_dend_reorder = FALSE)
> ```

That worked, thanks @jokergoo !
