### ISSUE TITLE
cell_fun for HeatmapAnnotation

### ISSUE THREAD

**Issue by luimucar** [jokergoo/ComplexHeatmap#306]
Can I modify the cells of the annotation in the same way I can modify the heatmap body cell by using the cell_fun?

I made some width modifications to the heatmap body cells and I would like to replicate these in the annotations.

Thank you in advance

**Comment by jokergoo** [comment]
Unfortunately no. You can only modify heatmap annotations by `decorate_annotation()` function.

**Comment by luimucar** [comment]
Thank you! By the way, very useful package!
