### ISSUE TITLE
How can I change the fontsize of the axis labels in in anno_oncoprint_barplot?

### ISSUE THREAD

**Issue by nfarnoud** [jokergoo/ComplexHeatmap#307]
Hello, 
I would like to increase the axis-tickmarks for barplot annotation. I had no problem in the old version but it is no longer compatible in the latest version.
I tried a few variations and for example tried to add it via **axis_param** but that is not correct.          
```
 top_annotation = HeatmapAnnotation(column_bar = anno_oncoprint_barplot(type= NULL, 
                                                                  bar_width = 0.6, axis = TRUE,
                                                                  border= TRUE,
                                                                  **axis_param= gpar(fontsize = 10)),**
                                                       annotation_height = unit(top.w, "cm")), .........
```

Appreciate your help.     
NF

**Comment by jokergoo** [comment]
Please update the package. In some old versions, the `axis_param` was not correctly processed.

![image](https://user-images.githubusercontent.com/449218/57126913-04376180-6d8f-11e9-82d2-bbd7e3e19d56.png)

**Comment by nfarnoud** [comment]
I am using the latest package. Can you please provide the code that you used to increase the font size? I want to see if you are using it inside * anno_oncoprint_barplot()* function and how you are calling it?
Many Thanks!

**Comment by nfarnoud** [comment]
Actually I found what the issue was. The *axis_param* had to be defined as a list. The following works just fine:

```
column_bar = anno_oncoprint_barplot(type= NULL, border= TRUE,
                                    axis_param = list(side = "right", 
                                                      gp= gpar(fontsize= 18)))
```
Thanks!
