### ISSUE TITLE
To add plotly-like features?

### ISSUE THREAD

**Issue by pliu55** [jokergoo/ComplexHeatmap#308]
Hi @jokergoo,

First of all, thank you for developing this extremely useful package.  I used it a lot for my data analysis.  

I am wondering if there is any plan to add plotly-like feature for this package, where user can hover mouse onto any part of a heatmap and get a value displayed, such as in [this example](https://plot.ly/r/heatmaps/#categorical-axes)? Plotly has implemented such function, but it does not have all the great row/column annotation features as in your package.  Thanks. 

Best,
Peng

**Comment by jokergoo** [comment]
No, ComplexHeatmap package only produces static heatmaps. If you want interactive heatmaps, you can check [heatmaply](https://github.com/talgalili/heatmaply), [iheatmapr](https://github.com/ropensci/iheatmapr) or [d3heatmap](https://github.com/rstudio/d3heatmap)

**Comment by pliu55** [comment]
Thanks for your prompt reply.  I will try the packages you suggested.
