### ISSUE TITLE
Rotate a part of the dendrogram

### ISSUE THREAD

**Issue by NicolasHipp** [jokergoo/ComplexHeatmap#31]
Hello, 
I'm a newbie in R utilisation and I try to use ComplexHeatmap to visualize my data. I work on single cell qPCR analysis and i would like to rotate a part of the dendrogram. 
I try to change the order with a vector in the "column_dend_reorder" command, but I don't understand how it works.

Does anybody performed this before?
Thks,
Nicolas :)
![change order](https://cloud.githubusercontent.com/assets/18481923/14558890/6861a672-0305-11e6-8a7b-e5819bfa9fb8.png)

**Comment by jokergoo** [comment]
Hi,

Maybe you can check the dendextend package:

https://cran.r-project.org/web/packages/dendextend/vignettes/introduction.html#changing-a-dendrograms-structure

There is a `rotate()` function which can adjust the order of branches in a dendrogram.

In your case, you should generate a dendrogram for columns first:

```{r}
column_dend = as.dendrogram(hclust(t(mat)))
column_dend = rotate(column_dend, ...)  # define how you rotate the branches
```

In the vignette I mentioned above, the author use "pipe-style syntax", so:

```{r}
dend15 %>% 
   set("labels_colors") %>% 
   rotate(5:1)
```

is identical to 

```{r}
rotate(set(dend15, "labels_colors"), 5:1)
```
 
and sent it to `Heatmap()`:

```{r}
Heatmap(mat, cluster_columns = column_dend, ...)
```

**Comment by NicolasHipp** [comment]
Hi,

I tried this solution and it works perfectly ::)

Thks for the help ! :)

Nicolas
