### ISSUE TITLE
right_annotation does not exist

### ISSUE THREAD

**Issue by kopardev** [jokergoo/ComplexHeatmap#310]
right_annotation (from https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html#simple-annotation) is not found in version 1.99.8. I only find options for top_annotation and bottom_annotation.

**Comment by jokergoo** [comment]
Have you reloaded the package after you updated it? Or you can first exit R and reopen it. `right_annotation` should be there.

**Comment by kopardev** [comment]
That work... Thanks.
