### ISSUE TITLE
Row scaling

### ISSUE THREAD

**Issue by kopardev** [jokergoo/ComplexHeatmap#313]
Does Heatmap function have an option to scale rows (or columns) and then plot z-scores?

**Comment by jokergoo** [comment]
No, there is no such option, but it can be very easily done by:

```r
scaled_mat = t(scale(t(mat)))
Heatmap(scaled_mat, ...)
```

**Comment by crazyhottommy** [comment]
it is good to leave the scaling to the user before using Heatmap.

**Comment by margotcj** [comment]
> No, there is no such option, but it can be very easily done by:
> 
> ```r
> scaled_mat = t(scale(t(mat)))
> Heatmap(scaled_mat, ...)
> ```

Hi! I was wondering why there is the "t" in front of the code. I thought this was for transposing the data, is this needed?

**Comment by jokergoo** [comment]
`scale()` applies by columns, so if you want to scale by rows, you need to

1. transpose the matrix `t(mat)`
2. scale the transposed matrix `scale(t(mat))`. 
3. transpose it back `t(scale(t(mat)))`.
