### ISSUE TITLE
accept a phylo object as the row clusters?

### ISSUE THREAD

**Issue by fionarhuang** [jokergoo/ComplexHeatmap#316]
Hi,
Thank you for writing this fancy package. Would it be possible for `cluster_rows` to accept a `phylo` object?
There are functions, e.g. `as.dendrogram` to convert the `phylo` object to `hclust` or `dendrogram`. However, the conversion changes the order of leaves that is hoped to keep.

```
set.seed(1)
# an example phylo tree
exTree <- ape::rtree(10)

# visualize the tree
ggtree(exTree, branch.length = "none") + geom_tiplab() 

# an example matrix
count <- matrix(1:30, ncol = 3)
rownames(count) <- exTree$tip.label

# create the heatmap: the row order is different to the original tree
newTree <- as.dendrogram(phytools::force.ultrametric(exTree))
Heatmap(count, cluster_rows = newTree)

# order the rows of matrix based on the leaf labels of the original tree but can't combine with the original tree.
d <- fortify(exTree)
td <- subset(d, isTip)
leafLab <- with(td, label[order(y, decreasing=T)])
Heatmap(count, row_order = leafLab)
```
Thank you!

**Comment by jokergoo** [comment]
Hi, the thing is **ggtree** changes the order of the original `phylo` project. 

```r
set.seed(1)
# an example phylo tree
exTree <- ape::rtree(10)
plot(exTree)
```
![image](https://user-images.githubusercontent.com/449218/57767748-6470c080-770a-11e9-9523-50c6f58c66af.png)

```r
ggtree::ggtree(exTree, branch.length = "none") + geom_tiplab() 
```

![image](https://user-images.githubusercontent.com/449218/57767785-78b4bd80-770a-11e9-8686-b9f6b2551a3f.png)

And ComplexHeatmap uses the original dendrogram structure (just reverse it):

```r
newTree <- as.hclust(phangorn::nnls.tree(ape::cophenetic.phylo(exTree), exTree, rooted = TRUE, trace = 0))
newTree = as.dendrogram(newTree)

count <- matrix(1:30, ncol = 3)
rownames(count) <- exTree$tip.label
library(ComplexHeatmap)
Heatmap(count, cluster_rows = newTree)
```
![image](https://user-images.githubusercontent.com/449218/57767843-a26de480-770a-11e9-9be2-89e63035213c.png)

**Comment by GuangchuangYu** [comment]
![image](https://user-images.githubusercontent.com/626539/57843991-c6602180-7801-11e9-9835-007854d232e3.png)

ggtree ladderizes the tree by default, which can be disable by setting `ladderize = F`.

**Comment by fionarhuang** [comment]
@jokergoo @GuangchuangYu Thanks for the help!

**Comment by fionarhuang** [comment]
Hi @jokergoo,

Sorry to reopen this issue because of a related question.  Is it possible to allow the output from ggtree to annotate the rows or columns of the heatmap? Below is a toy example to show what I tried. The issue is the tree and the (2nd) heatmap can't match with each other because of the column annotation. Would you mind giving me some suggestion?

```
library(ComplexHeatmap)
library(ggtree)
library(ape)
library(cowplot)

# ------------------ example data ------------------------------
# an example tree
set.seed(123)
treeX <- rtree(10)
ggtree(treeX, branch.length = "none") + 
    geom_text2(aes(label = node), color = "blue", vjust = 1) + 
    geom_text2(aes(label = label), color = "red", vjust = 0)


# an example count table
p1 <- c(0.2, 0.2, 0.2, rep(0.02, 5), 0.15, 0.15)
p2 <- c(0.1, 0.1, 0.1, rep(0.02, 5), 0.3, 0.3)
n <- 10
dat1 <- rmultinom(n = n, size = 100, prob = p1)
dat2 <- rmultinom(n = n, size = 100, prob = p2)
dat <- cbind(dat1, dat2)
rownames(dat) <- transNode(tree = treeX, node = 1:10)

# -----------------  a figure from ggtree ----------------------------
# color two branches
treeY <- groupClade(treeX, c(12, 19))
treeFig <- ggtree(treeY, branch.length = "none", 
                  aes(color = group, size = group)) +
    scale_color_manual(values = c("grey", "blue", "orange"))
treeFig

# ----------------- 2 heatmaps from ComplexHeatmap ----------------------------
# heatmap 1
ht1 <- Heatmap(dat, 
               cluster_rows = FALSE, 
               cluster_columns = FALSE, 
               show_column_names = FALSE,
               rect_gp = gpar(col = "white"))
gb1 <- grid.grabExpr(draw(ht1))
gb1
plot_grid(treeFig, gb1)


# heatmap2
ht2 <- Heatmap(dat, 
               cluster_rows = FALSE, 
               cluster_columns = FALSE, 
               show_column_names = FALSE,
               rect_gp = gpar(col = "white"),
               column_split = rep(LETTERS[1:2], each = 10))
gb2 <- grid.grabExpr(draw(ht2))
gb2
plot_grid(treeFig, gb2)
```
Thanks!
Ruizhu

**Comment by GuangchuangYu** [comment]
1. it seems that you forgot to load some library for `transNode` function

I use the following command instead:

```
rownames(dat) <- with(tidytree::as_tibble(treeX), label[match(1:10, node)]) 
```

2. the rowname of the input matrix is not match with tip labels.

```
dd <- treeFig$data
dd <- dd[dd$isTip,]
lab <- dd$label[order(dd$y, decreasing = T)]

## make sure the order of the input matrix is consistent with the tree
dat <- dat[lab,]
```

3. quick and dirty solution

is to employ empty space

```
space <- ggdraw()
plot_grid(plot_grid(space,treeFig, rel_heights = c(.05, 1), ncol = 1), gb2)
```

![image](https://user-images.githubusercontent.com/626539/62508801-7fe7f500-b83b-11e9-9006-fbcaf8651f7a.png)

4. I think the solution is to use `ggplotGrob` to transform the `ggtree` output to a `grob` object and incorporated to `ComplexHeatmap`.

**Comment by jokergoo** [comment]
@GuangchuangYu Hmmm. I think it would be very nice if I can support ggtree in ComplexHeatmap. I don't have too much experience with ggplot2, but I will put it as a long-term plan in my to-do list.

**Comment by limrp** [comment]
> And ComplexHeatmap uses the original dendrogram structure (just reverse it):
> 
> # following line is the same as `phytools::force.ultrametric(...)`
> # it is just because I cannot install phytools package on my machine
> newTree <- as.hclust(phangorn::nnls.tree(ape::cophenetic.phylo(exTree), exTree, rooted = TRUE, trace = 0))
> newTree = as.dendrogram(newTree)
> 
> count <- matrix(1:30, ncol = 3)
> rownames(count) <- exTree$tip.label
> library(ComplexHeatmap)
> Heatmap(count, cluster_rows = newTree)

Hi!

Sorry for reopening the issue.

I'm having problems using the phylogenetic tree generated by IQtree besides my ComplexHeatmap giving it as input to the cluster_rows parameter. The issue is that the individuals appear to be grouped in a different way than in the original tree.

My tree is rooted at midpoint using the midpoint function from the phangorn library. Is perhaps that an issue?

This is the code I have been running:

```
library(ape)
library(circlize)
library(phangorn)  # For midpoint rooting and other phylogenetic analyses
library(phytools)
library(dendextend)
library(ComplexHeatmap)

tree_file <- "/path/to/test.treefile"

# cargar el archivo parsnp.tree y asignar a un objeto "tree"
tree <- read.tree(tree_file)
# Enforce minimum length
tree_simplified <- tree
tree_simplified$edge.length <- pmax(tree_simplified$edge.length, 0.0001) 
# "Mid point" rooting
treeMP <- midpoint(tree_simplified)
plot(treeMP)
```


Until here, all the individuals are grouped in the correct way.

```
# Make the tree ultrametric with minimal alterations
tree_ultrametric <- phytools::force.ultrametric(treeMP)
tree_dend <- as.dendrogram(as.hclust(tree_ultrametric))
plot(tree_dend)

Until here, all the individuals are still grouped in the correct way.

# Extract Leaf Order and Align Data
leaf_order <- labels(tree_dend)
leaf_order

Then I load the data for the heatmap:
data <- read.table(
    "/path/to/test_heatmap_data.Rtab",
    sep = "\t",
    header = T,
    row.names = 1, 
    check.names = F, 
    )
# Check if all leaf_order elements exist in row names of the data
all(leaf_order %in% rownames(data_t))  # Should return TRUE

# Reorder rows based on leaf_order
data_t <- t(data)
data_t <- data_t[leaf_order, ]
rownames(data_t)
# Compare the row names of the reordered data with leaf_order
all(rownames(data_t) == leaf_order)  # Should return TRUE
```

Everything seems ok until here.

```
# Define output file
pdf("/path/to/plots/heatmap.pdf", width = 40, height = 20)  

Heatmap(
    as.matrix(data_t),  # Input data matrix,
    col = colorRamp2(c(0, 1), c("gray95", "steelblue")),  # Map 0 to gray95 and 1 to steelblue
    name = "Presence/Absence",  # Legend title
    cluster_rows = tree_dend,
    show_row_dend = TRUE,   # Show dendrogram for rows
    # show_column_dend = TRUE, # Show dendrogram for columns
    show_column_names = FALSE, # DO NOT Show dendrogram for columns
    row_names_side = "left", # , # c("right", "left")
    # row_dend_side = c("left", "right"),
    row_dend_width = unit(200, "mm"),
)

# hm

# Close the device
dev.off()
```

But when I check the dendogram beside the heatmap, the individuals are grouped in the wrong way (with other individuals, not following the original phylogenetic tree). For instance, U4 and U2 should be grouped together, but in the dendogram, besides the heatmap, U4 and U1 are together.

I tried to use:

```
newTree <- as.hclust(phangorn::nnls.tree(ape::cophenetic.phylo(treeMP), treeMP, rooted = FALSE, trace = 0))
newTree = as.dendrogram(newTree)
```

But I got this error message:

```
Error in as.hclust.phylo(phangorn::nnls.tree(ape::cophenetic.phylo(treeMP), : the tree is not ultrametric
Traceback:

1. as.hclust.phylo(phangorn::nnls.tree(ape::cophenetic.phylo(treeMP), 
 .     treeMP, rooted = FALSE, trace = 0))
2. stop("the tree is not ultrametric")
3. .handleSimpleError(function (cnd) 
 . {
 .     watcher$capture_plot_and_output()
 .     cnd <- sanitize_call(cnd)
 .     watcher$push(cnd)
 .     switch(on_error, continue = invokeRestart("eval_continue"), 
 .         stop = invokeRestart("eval_stop"), error = NULL)
 . }, "the tree is not ultrametric", base::quote(as.hclust.phylo(phangorn::nnls.tree(ape::cophenetic.phylo(treeMP), 
 .     treeMP, rooted = FALSE, trace = 0))))
```

The test files are attached to this message.

I would really be grateful if someone could help me with this, please.

Test data for heatmap:

[test.txt](https://github.com/user-attachments/files/18499901/test.txt)

Test tree:

[test_treefile.txt](https://github.com/user-attachments/files/18499906/test_treefile.txt)
