### ISSUE TITLE
UpSet with 31 sets requires 496.0 Gb

### ISSUE THREAD

**Issue by karl616** [jokergoo/ComplexHeatmap#319]
Hi,
with 31 different sets, this line:

https://github.com/jokergoo/ComplexHeatmap/blob/c79aaf9e7e119a529db419310fae9b365e52d05a/R/Upset.R#L134

fails with the following error:

`Error: cannot allocate vector of size 496.0 Gb`

Out of all those combinations, my particular data set only contains ~9k different combinations. I haven't gotten all the way through the code, but perhaps it could be possible to use a sparse matrix here...

**Comment by karl616** [comment]
sparseMatrix will not work either...

As I understand it, this is only adding empty sets. Perhaps, there could be a limitation based on `n` for when this happens. Something like:

```
if (n<14){
  # add empty sets
}else{
  Warning("Will not add empty sets due to combinatorial explosion")
}
```

**Comment by jokergoo** [comment]
Thanks for your feedback! I also had this problem when I had a lot of sets to compare recently. The initial design has not considered that many sets. I will optimize it in the future.

**Comment by jokergoo** [comment]
#320
