### ISSUE TITLE
How do I add gene expression to oncoPrint

### ISSUE THREAD

**Issue by patidarr** [jokergoo/ComplexHeatmap#322]
Hi,

Thank you for putting soo much efforts in this tool, this is the best thing happened into heatmap space across languages.

I want to add expression/RPPA data to a oncoPrint/ or any other matrix heatmap, but I can not find an example so far. I thought following should work
```
  bottom_anno<-HeatmapAnnotation(
    PIK3=clinical_input$PI3K.AKT,
    rppa=cbind(clinical_input[1],clinical_input[6:16]),
    ONCOTREE=clinical_input$ONCOTREE_CODE,
    col = list(
      PIK3=colorRamp2(c(-15, 0, 15), c("blue", "white", "red")),
      ONCOTREE=c( 
        "COAD"="#E64B35FF",
        "BLCA"="#4DBBD5FF",
        "MEL"="#00A087FF",
        "LUSC"="#3C5488FF",
        "HNSC"="#F39B7FFF",
        "OCSC"="#8491B4FF",
        "LUAD"="#91D1C2FF",
        "PAAD"="#DC0000FF",
        "SARCNOS"="#7E6148FF",
        "RARE"= "#B09C85FF")
      
    ),
    na_col = "black"
  )
```
but I am getting following error:
```
Error in HeatmapAnnotation(PIK3 = clinical_input$PI3K.AKT, rppa = cbind(clinical_input[1],  : 
  additional arguments should be annotation vectors or annotation functions.
```

my clinical_input is a list of annotations I want to add to the plot and there are expression/RPPA data in the same file which I can plot one gene at a time but I want to make a heatmap so that the scale is normalized instead of different min and max for every gene.
I am using ComplexHeatmap_1.20.0

Thanks,
Rajesh

**Comment by jokergoo** [comment]
Please update the package to version 2.0.0 or higher. I guess the annotaiton

```r
    rppa=cbind(clinical_input[1],clinical_input[6:16]),
```

is a matrix which was not supported and in supported in current versions.
