### ISSUE TITLE
make_comb_mat not recognized as function

### ISSUE THREAD

**Issue by ytakemon** [jokergoo/ComplexHeatmap#323]
Hi @jokergoo,

I recently installed ComplexHeatmap from bioconductor to make the Upset plots from your tutorial. However, on my R version, 3.5.1, make_comb_mat() doesn't seem to be recognized

I have ComplexHeatmap, but when I run the following I get this error message:
```
ComplexHeatmap::make_comb_mat()
Error: 'make_comb_mat' is not an exported object from 'namespace:ComplexHeatmap'
```
It seems to be isolated to the make_comb_mat function, as I am able to see other functions within ComplexHeatmap such as make_column_cluster

```
make_column_cluster
standardGeneric for "make_column_cluster" defined from package "ComplexHeatmap"

function (object, ...)
standardGeneric("make_column_cluster")
<bytecode: 0x3dd84d8>
<environment: 0x3e79298>
Methods may be defined for arguments: object
Use  showMethods("make_column_cluster")  for currently available ones.
```

Was this function recently renamed or removed? Apologies if I am missing something fundamental that I may have overlooked.
Best,
Yuka

**Comment by jokergoo** [comment]
Hi, I think you should update the package to version 2.0.0 or higher. This function was newly added.

```r
library(devtools)
install_github("jokergoo/ComplexHeatmap")
```

**Comment by ytakemon** [comment]
Hi @jokergoo, 
Thanks for getting back to me so quickly. The update worked!
Thanks!
