### ISSUE TITLE
Manual: incorrect file names when saving plots

### ISSUE THREAD

**Issue by pistacliffcho** [jokergoo/ComplexHeatmap#324]
Small bug in manual; in the [section describing how to save](https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#heatmap-as-raster-image) a plot, for all types of plots, the file name always ends with ".pdf", when it should end with the correct file type.

**Comment by jokergoo** [comment]
Hi, they should be in pdf format. In these plots, only the heatmap bodies are filled by rasterized graphs, while other parts like dendrograms, row/column names are still vectorized graphs.

See https://journal.r-project.org/archive/2011-1/RJournal_2011-1_Murrell.pdf

**Comment by pistacliffcho** [comment]
Oh, I see! Yes, that makes sense.
