### ISSUE TITLE
add examples of triangles graph in oncoprint

### ISSUE THREAD

**Issue by jokergoo** [jokergoo/ComplexHeatmap#325]
https://ascopubs.org/doi/full/10.1200/JCO.2017.76.0033

![image](https://user-images.githubusercontent.com/449218/58415716-a6d9bc00-807f-11e9-8237-303e40f1735a.png)

**Comment by jokergoo** [comment]
```r
oncoPrint(mat,
    alter_fun = list(
    	background = function(x, y, w, h) {
    		grid.polygon(
	        	unit.c(x - 0.5*w, x - 0.5*w, x + 0.5*w), 
	        	unit.c(y - 0.5*h, y + 0.5*h, y - 0.5*h),
	            gp = gpar(fill = "grey", col = "white"))
        	grid.polygon(
	        	unit.c(x + 0.5*w, x + 0.5*w, x - 0.5*w), 
	        	unit.c(y + 0.5*h, y - 0.5*h, y + 0.5*h),
	            gp = gpar(fill = "grey", col = "white"))
    	},
        snv = function(x, y, w, h) {
        	grid.polygon(
	        	unit.c(x - 0.5*w, x - 0.5*w, x + 0.5*w), 
	        	unit.c(y - 0.5*h, y + 0.5*h, y - 0.5*h),
	            gp = gpar(fill = col["snv"], col = "white"))
        },
        indel = function(x, y, w, h) {
        	grid.polygon(
	        	unit.c(x + 0.5*w, x + 0.5*w, x - 0.5*w), 
	        	unit.c(y + 0.5*h, y - 0.5*h, y + 0.5*h),
	            gp = gpar(fill = col["indel"], col = "white"))
        }
    ), col = col)
```

![image](https://user-images.githubusercontent.com/449218/60585346-cefbbf80-9d8f-11e9-9024-2a7ea8605960.png)

**Comment by Tina9** [comment]
Hi Jokergoo,

Could you please tell me how to make labels being triangles?

Thanks

**Comment by jokergoo** [comment]
Hi @Tina9 , what do you mean by "make labels being triangles"?

**Comment by Tina9** [comment]
I want to use triangles as the label, such as the image.
![image](https://user-images.githubusercontent.com/16876314/64140075-bd896f00-ce35-11e9-846c-a97837864871.png)

**Comment by jokergoo** [comment]
I see, unfortunately it is not supported. I think a legend with rectangles should be enough.

**Comment by Tina9** [comment]
Thanks for your answer.

**Comment by TnakaNY** [comment]
Hi,
Could you also add a example code of alt_fun that divide a cell into 4 triangles?

**Comment by jokergoo** [comment]
@TnakaNY You can find examples in https://jokergoo.github.io/ComplexHeatmap-reference/book/oncoprint.html#define-the-alter-fun

**Comment by TnakaNY** [comment]
Thank you very much!!
