### ISSUE TITLE
Can you add support to ylim parameter in Oncoprint 

### ISSUE THREAD

**Issue by Rashesh7** [jokergoo/ComplexHeatmap#328]
Hi, 
I am plotting two sets side by side using 
ht_list=htsig_p+htsig_np
So I want the top annotation barplot and the row annotation barplots to have the same y-axis, so it is visually comparable. 

Thank you.

**Comment by jokergoo** [comment]
You can set:

```r
oncoPrint(...,
    top_annotation = HeatmapAnnotation(cbar = anno_oncoprint_barplot(axis_param = list(ylim = c(...))),
    right_annotation = rowAnnotation(rbar = anno_oncoprint_barplot(axis_param = list(ylim = c(...))),
    ...
)
```

**Comment by Rashesh7** [comment]
I tried that but, it gives me the following error

Error in (function (at = NULL, labels = at, labels_rot = 0, gp = gpar(),  : 
  unused argument (ylim = c(0, 12))
Calls: oncoPrint ... anno_oncoprint_barplot -> construct_axis_grob -> do.call
Execution halted


My command is:

htsig_p=oncoPrint(pmat_sig,get_type = function(x) strsplit(x, ";")[[1]], alter_fun = alter_fun, col = col, row_names_side = "right", show_column_names=TRUE, row_order=gene_order_sig, show_pct = TRUE, **top_annotation = HeatmapAnnotation(cbar = anno_oncoprint_barplot(height = unit(10, "mm"), axis_param = list(ylim = c(0, 12))))**, bottom_annotation= wgd_p, l**eft_annotation = rowAnnotation(rbar = anno_oncoprint_barplot(axis_param = list(direction = "reverse", ylim = c(0,70)), width = unit(10, "mm")))** , right_annotation = NULL, cluster_row_slices=FALSE, row_names_gp = gpar(fontsize = 4), pct_gp = gpar(fontsize = 0), column_gap = unit(1, "mm"), row_title_gp= gpar(fontsize = 5), column_title_gp = gpar(fontsize = 5), column_names_gp=gpar(fontsize = 4), show_heatmap_legend = FALSE)

**Comment by Rashesh7** [comment]
@jokergoo ,
Did you get a chance to check if it is actually not working, or am I giving an incorrect command?

Thank you!

**Comment by jokergoo** [comment]
Sorry, my previous answer was wrong. There is no `ylim` parameter for `axis_param`.

I checked that `anno_oncoprint_barplot()` did not support `ylim`. Now I've updated the package and the function supports `ylim` parameter.

So you can set `ylim` as follows:

```r
oncoPrint(.,..
    top_annotation = HeatmapAnnotation(cbar = anno_oncoprint_barplot(ylim = c(0, 10))),
    right_annotation = rowAnnotation(rbar = anno_oncoprint_barplot(ylim = c(0, 10)))
)
```

**Comment by Rashesh7** [comment]
Awesome Thank you!
