### ISSUE TITLE
Display values in legend that are not part of the heatmap

### ISSUE THREAD

**Issue by leachim** [jokergoo/ComplexHeatmap#329]
I would like to display a heatmap of discrete values, containing possible values 0:7, with a corresponding legend. However, there are cases when not all possible values are realised, for example, I only observe values 1, 3, 4 in the heatmap. How can I still display the whole range of values in the legend? 
I run into this error: 
`Error: Length of 'at' should be same as length of 'labels'.`

**Comment by jokergoo** [comment]
If it is a heatmap legend:

```r
Heatmap(..., heatmap_legend_param = list(at = 0:7))
```

**Comment by leachim** [comment]
Apologies, I should have been more precise. This is a mwe: 
> x = matrix(c(1, 2, 4, 4, 5, 5), ncol=2)
  labels = c("1", "2", "3", "4", "5", "6")
  h = Heatmap(x, heatmap_legend_param = list(title = "Copy number", 
                                             labels = labels))

**Comment by jokergoo** [comment]
Because `x` is numeric, you should do like:

```r
Heatmap(x,
    heatmap_legend_param = list(
        title = "Copy number",
        at = 1:6
))
```

If you want labels to be different from breaks values:

```r
Heatmap(x,
    heatmap_legend_param = list(
        title = "Copy number",
        at = 1:6,
        labels = c("one", "two", "three", "four", "five", "six")
))
```

**Comment by tiagochst** [comment]
I have a related question. 

What if I have two heatmaps with the same annotation (i.e. subtype)
and my heatmap 1 has two levels ("Her2","Basal") and the other one has "Normal"

Is it possible to have like a merged annotation ? Or to force in the first heatmap to show "Normal" legend with a specific color ?

Something like: 
```
library(ComplexHeatmap)
x = matrix(c(1, 2, 4, 4, 5, 5), ncol=2)
h1 <- HeatmapAnnotation("Subtype" = c("Basal","Her2"))
h2 <- HeatmapAnnotation("Subtype" = c("Normal","Normal"))

Heatmap(x,top_annotation = h1) + Heatmap(x,top_annotation = h2)
```

**Comment by jokergoo** [comment]
Good suggestion! I will try to implement it.

**Comment by jokergoo** [comment]
@tiagochst I have updated the package. Legends for annotations with the same names are merged (only for discrete annotations):

You must set `col` for both annotations.

```r
x = matrix(rnorm(6), ncol=3)
subtype_col = c("Basal" = "purple","Her2" = "black","Normal" = "blue")
h1 <- HeatmapAnnotation("Subtype" = c("Basal","Her2", "Normal"),
                        col = list("Subtype" = subtype_col))
h2 <- HeatmapAnnotation("Subtype" = c("Normal","Normal", "Basal"),
                        col = list("Subtype" = subtype_col))

Heatmap(x,top_annotation = h1) + Heatmap(x,top_annotation = h2)
```
![image](https://user-images.githubusercontent.com/449218/62521273-98eaa900-b82f-11e9-83ed-d54b21936119.png)

**Comment by tiagochst** [comment]
Thanks! It worked. 

The only problem, is that the label name should be **Subtype** in the example, instead all annotation are **color_mapping_x**.

**Comment by jokergoo** [comment]
@tiagochst Now fixed!

**Comment by tiagochst** [comment]
Thanks! It is working perfectly
