### ISSUE TITLE
what does row_dend_reorder	do?

### ISSUE THREAD

**Issue by crazyhottommy** [jokergoo/ComplexHeatmap#33]
Hi,
I saw in the help page:

>row_dend_reorder
>apply reordering on rows. The value can be a logical value or a vector which contains weight which is used to reorder rows

what does it do exactly?

I found  [dendsort](https://cran.r-project.org/web/packages/dendsort/vignettes/example_figures.html)
Is it doing something similar?

Thanks,
Ming

**Comment by jokergoo** [comment]
Yes, also you can refer to `reorder.dendrogram` function.

Generally, two branches in dendrogram can be rotated while still keep the dendrogram identical. E.g. in following dendrogram, branch A and B can be rotated:

```
   +-- A
 +-|
 | +-- B
 +---- C
```

to 

```
   +-- B
 +-|
 | +-- A
 +---- C
```

So, adjusting the two branches in every node sometimes can improve the visualization of the matrix.
E.g., let's assume A, B, C are three groups of differentially expressed genes, Expression in A and B are more similar than in C, and the default dendrogram looks like the first one above. However, if the similarity of the three groups of genes are B > A > C, changing order of A and B which is shown in the second dendrogram also shows the trend of expression in the three groups.

**Comment by crazyhottommy** [comment]
Thanks for clarifying it.  A side question is that how can one color the dendrogram like [dendextend](https://cran.r-project.org/web/packages/dendextend/vignettes/introduction.html)?
I saw in this [issue](https://github.com/jokergoo/ComplexHeatmap/issues/32), you showed an example to highlight the dendrogram in color (this works). Just want to know if  it is possible to color the dendrogram itself rather than using `grid.rect`?

**Comment by jokergoo** [comment]
That is more easy. You can just render the dendrogram by **dendextend** package. There is an example in the following vignette: http://www.bioconductor.org/packages/devel/bioc/vignettes/ComplexHeatmap/inst/doc/s2.single_heatmap.html#toc_3

The example code is:

```{r}
library(dendextend)
dend = hclust(dist(mat))
dend = color_branches(dend, k = 2)
Heatmap(mat, name = "foo", cluster_rows = dend)
```

![image](https://cloud.githubusercontent.com/assets/449218/14760245/a98c437a-093e-11e6-9aa9-7f326e16ce26.png)

**Comment by crazyhottommy** [comment]
Thanks for the tip! I should have read the tutorial more carefully.
