### ISSUE TITLE
Retrieve order of matrix after setting cluster_rows=T

### ISSUE THREAD

**Issue by kin182** [jokergoo/ComplexHeatmap#330]
Hi,

I would like to retrieve the rownames of the matrix after setting `cluster_rows=T`. How to do it?  

Ultimately, I would like to add custom genes to the heatmap by `anno_mark` using `rowAnnotation`, so I have to get the position of the genes. Something like:

`ha_row = rowAnnotation(Annotation = anno_mark(at = c(1:4, 20, 60, 97:100), labels = month.name[1:10]))`

Or is there any way to do the annotation? Thanks!

**Comment by jokergoo** [comment]
You can get the order by 

```r
ht = Heatmap(...)
ht = draw(ht)
row_order(ht)
```

If you use `anno_mark()`, actually you don't need to care about the reordering by row clustering. The orders are automatically adjusted, which means, in `anno_mark()`, values in `at` argument corresponds to the order of the original matrix (or the input matrix you send to `Heatmap()` that clustering has not been applied).

**Comment by kin182** [comment]
Thank you for pointing it out `anno_mark()` uses the order of the original matrix. I had a side question: How do we change font size and colors when using `anno_mark()` for annotation?

**Comment by kin182** [comment]
Thank you for pointing it out `anno_mark()` uses the order of the original matrix. I have one side question. How do we change font size and colors with `anno_mark()`?

**Comment by jokergoo** [comment]
```r
anno_mark(..., labels_gp = gpar(col = )))
```

**Comment by kin182** [comment]
Thanks so much! It was helpful!

**Comment by lixin4306ren** [comment]
Hi, I use `row_km=4` to split the heatmap, after that, I tried to label some marker genes to he heatmap by `anno_mark`. I found that the row order (genes) isn't the original one. It's also not the one I extract from `unlist(row_order(ht))`. What exactly index numbers should I provide for `at` argument in `anno_mark` after kmeans split and row clustering? Thanks.

**Comment by jokergoo** [comment]
`at` is the row indices from the original matrix. E.g. if you want to mark gene 1, 4, 10, then you set `at = c(1, 4, 10)`. You don't need to care whether rows are clustered or split, the positions of gene 1, 4, 10 are automatically adjusted.

**Comment by lixin4306ren** [comment]
It worked without `row_km=4` , but didn't work with heatmap split. See below two screenshots:

Clearly, you can see that all four genes labels in plot2 indicated the wrong positions compared to the first plot.

1. without `row_km=4`
![image](https://user-images.githubusercontent.com/14223132/64859636-65384580-d65d-11e9-8855-38536934c29f.png)

2. with `row_km=4`
![image](https://user-images.githubusercontent.com/14223132/64859636-65384580-d65d-11e9-8855-38536934c29f.png)

**Comment by jokergoo** [comment]
En... I guess you are using an older version of the package. I tried with version >= 2.0.0 and it works well:

```r
m = matrix(rnorm(100), 10)
rownames(m) = letters[1:10]

ha = rowAnnotation(foo = anno_mark(at = 1:4, labels = letters[1:4]))
Heatmap(m, name = "mat",right_annotation = ha)
```

![image](https://user-images.githubusercontent.com/449218/64918631-332ffc00-d7a1-11e9-978f-6061aaab68a7.png)

```r
Heatmap(m, name = "mat",right_annotation = ha, row_km = 2)
```

![image](https://user-images.githubusercontent.com/449218/64918636-3f1bbe00-d7a1-11e9-8936-360bf3283ee8.png)

```r
Heatmap(m, name = "mat",right_annotation = ha, row_split = rep(c("a", "b"), each = 5))
```

![image](https://user-images.githubusercontent.com/449218/64918639-522e8e00-d7a1-11e9-8474-6619d948abbd.png)

**Comment by lixin4306ren** [comment]
I was using V2.0.0. I updated the complexheatmap and it did solve the problem. Thanks a lot.
