### ISSUE TITLE
decorate_annotation function does not work with r shiny renderPlot

### ISSUE THREAD

**Issue by juechenyang** [jokergoo/ComplexHeatmap#331]
Hi,

I encountered a tricky question when using complex heatmap. It's like the "decorate_annotation ()" only works when output heatmap as pdf but it does not work with r shiny renderPlot function. Would you mind to help me with this? Thanks

Jason

**Comment by jokergoo** [comment]
I haven't tested it with the shiny app and I don't have too much experience with shiny. One solution I can think of is to wrap the plotting part into a function and call this function in shiny:

```r
plot_fun = function() {
    ht = Heatmap(...)
    draw(ht)
    decorate_anotation(...)
}
```

**Comment by juechenyang** [comment]
Hi,

I tried that like this:

plot_fun(){
feature <- 'Disease'
heat_map <- Heatmap(data, name = "Expression",
        cluster_rows = TRUE,
        cluster_columns = FALSE,
        show_column_names = FALSE,
        show_column_dend = FALSE,
        width = unit(32, "cm"),
        height = unit(20, "cm"),
        top_annotation = top_anno
    )
    ht <- draw(heat_map, column_title = "Complex Heatmap", heatmap_legend_side = "right", annotation_legend_side = "right")
    decorate_annotation("clinical_feature",
        {grid.text(feature, x = unit(-5, "mm"),just = "right")}
    )
    return(ht)
}

When I call the method above in the main function like this:

renderPlot({plot_func()})

It only returns the results of the obj "ht" without decoration. But if I output this plot_fun() using pdf:
           
            pdf('example.pdf', width=32, height=20)
            plot_func()
            dev.off()

I got the right things.So that is what I am confusing

**Comment by jokergoo** [comment]
How about change this line

```r
return(ht)
```

to 

```r
return(invisible(NULL))
```

?

**Comment by juechenyang** [comment]
Yes! it works. Thank you so much! BTW, is there any reference for adjusting size of the legend?

**Comment by jokergoo** [comment]
You can find information here : https://jokergoo.github.io/ComplexHeatmap-reference/book/legends.html

Basically the `legend_width`/`legend_height` and `grid_width`/`grid_height` parameters.

**Comment by juechenyang** [comment]
Thanks! Appreciate your help!

**Comment by RussBainer** [comment]
Hi, I absolutely love your stuff but I have a similar problem to the one described here; I believe is related to problems identifying the correct viewport within a function call, but it's also possible that I am not specifying the secondary annotation properly. 

My code (based on the above and my reading of the manual) looks like:

```
moreUpSet <- function(m, tests, ...){
  
 ha <- ComplexHeatmap::HeatmapAnnotation("Intersection size" = anno_barplot(comb_size(m), 
                                                                            border = FALSE, 
                                                                            gp = gpar(fill = "black"),
                                                                            height = unit(3, "cm"),
                                                                            axis_param = list(side = "right")),
                                         'Overlap Z' = anno_empty(border = TRUE, 
                                                                  height = unit(2, "cm")),
                                         annotation_name_side = rep("right",2),
                                         annotation_name_rot = rep(0,2))  

  ComplexHeatmap::UpSet(m, 
      top_annotation = ha, ...) 
 
    decorate_annotation('Overlap Z', {
    exes <- c(0.5, (length(comb_size(m)) + 0.5))
    whys <- cm2z(m, tests)$Z
    whys[!is.finite(whys)] <- 0
    maximus <- max(abs(round(whys)))
    cols <- colorRampPalette(c('blue', 'grey', 'red'))(2 * maximus) 

    pushViewport(viewport(xscale = exes, yscale = range(round(value)), name = 'Overlap Z'))
    grid.lines(exes, c(0, 0), gp = gpar(lty = 2),
        default.units = "native")
    grid.points(1:length(comb_size(m)), value, pch = 16, size = unit(2, "mm"),
        gp = gpar(col = cols[round(whys) + maximus]), default.units = "native")
    grid.yaxis(at = range(round(value)))
    popViewport()
}) 
   
  return(invisible(NULL))
}

```
When I remove the function wrapper, everything appears to work correctly. Running the function I get the following error: 

```
Error in grid.Call.graphics(C_downviewport, name$name, strict) : 
  Viewport 'annotation_Overlap Z_1' was not found
```

If I place the following statement between the UpSet call and the decorate_annotation call: 

```
print(list_components())
print(current.viewport()$name)
```

I see the following: 

```
character(0)
[1] "ROOT"
```

Any help you might have would be very much appreciated.
