### ISSUE TITLE
Legend title and position

### ISSUE THREAD

**Issue by juechenyang** [jokergoo/ComplexHeatmap#332]
Hi,

Thank you for the help previously. I have a new question about legend. Do you know if I can adjust the margin between legend title and its body just like legend "disease" in this graph. the title and body of that legend is too close. Meanwhile, I want position the "disease" legend in this pic right beside the top bar annotation. Would mind to give me some ideas? Thanks!

![image](https://user-images.githubusercontent.com/18729321/59778434-1bb5a580-927c-11e9-99d2-bba481ca364b.png)

**Comment by jokergoo** [comment]
To control the space between legend title and legend body, you can set `title_gap` parameter:

```r
Heatmap(..., heatmap_legend_param = list(title_gap = unit(3, "mm")))
```

Currently, you cannot change the default positioning of legends. It is always located by the center of the plot. I am trying to make positioning of legends more flexible, but it is difficult at the moment. I would suggest you to manually edit by e.g. Inkscape.

**Comment by juechenyang** [comment]
Thanks! Appreciate your help

**Comment by juechenyang** [comment]
Sorry. I just found that it doesn't work. I also checked the color mapping legend reference

https://rdrr.io/github/eilslabs/ComplexHeatmap/man/color_mapping_legend-ColorMapping-method.html

and it appears that no "title_gap" parameter is defined in the color_mapping_legend function. Any other solutions for this? Thanks for your time!

**Comment by jokergoo** [comment]
Then you need to update the package to >= 2.0.0.
