### ISSUE TITLE
feature request: anno_mark label rotation

### ISSUE THREAD

**Issue by funnell** [jokergoo/ComplexHeatmap#333]
Hello,

I think it would be nice to be able set the label rotation for anno_mark.

Thanks!

**Comment by jokergoo** [comment]
Now there is a new `labels_rot` argument that you can use to control the rotation of labels:

![image](https://user-images.githubusercontent.com/449218/60544478-26127d80-9d19-11e9-9c08-0fdaead6fc0e.png)

**Comment by funnell** [comment]
Hi @jokergoo, thanks for the quick implementation!

When I tried it out by setting `labels_rot=0`, I got the following result
![SA1052_corrupt-tree_cell_normalized_copynumber_heatmap_pdf](https://user-images.githubusercontent.com/381464/60604872-7f64c600-9d86-11e9-861e-34c3d7319512.png)
But I was hoping for
![SA1052_corrupt-tree_cell_normalized_copynumber_heatmap_pdf](https://user-images.githubusercontent.com/381464/60604941-a28f7580-9d86-11e9-9a25-1c75a80478da.png)

Is there another parameter I need to set?

**Comment by jokergoo** [comment]
Hi, Can you try it now? The positions of text were not correctly calculated when anno_mark() is used as bottom anntation.

**Comment by funnell** [comment]
Hello,

It's definitely an improvement! But I'm still not quite able to get what I'd like.
![SA1049_raw-copy_cell_copynumber_heatmap_pdf](https://user-images.githubusercontent.com/381464/66773520-2cbe9e00-ee8d-11e9-8ba6-ec19283f8029.png)

To get what I was after, I had to hack the `annot_mark` function to use the grob width instead of height for layout (and maybe something else, I can't remember now). For an arbitrary labels_rot value, this might get a little complicated. Perhaps something like what `ggrepel` does might be worth looking at?

**Comment by jokergoo** [comment]
Eh... The anchor point for the rotation is not properly selected. You can see following plot for different `labels_rot` values:

![image](https://user-images.githubusercontent.com/449218/67078755-35b3b600-f192-11e9-99fb-3266e0e4b092.png)

I will try to improve it. Also it might affect other functions which support text rotation. I look at them as well.

**Comment by funnell** [comment]
Thanks @jokergoo! I imagine you'd need to calculate the bounding box of the rotated grob.

**Comment by jokergoo** [comment]
Now I have fixed this problem. See following validations:

![image](https://user-images.githubusercontent.com/449218/67150632-5840ee80-f2ba-11e9-8088-3c0d635e3ae5.png)

**Comment by funnell** [comment]
That's awesome!
I just went to try it out but got this error on installation:
```
> install_github("jokergoo/ComplexHeatmap")
Downloading GitHub repo jokergoo/ComplexHeatmap@master
   checking for file ‘/tmp/RtmpJ6s7zc/remotes2ab63fb04fd0/jokergoo-ComplexHeatmap-0ed4893/DESCRIPTION’ .✔  checking for file ‘/tmp/RtmpJ6s7zc/remotes2ab63fb04fd0/jokergoo-ComplexHeatmap-0ed4893/DESCRIPTION’ (355ms)
─  preparing ‘ComplexHeatmap’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘ComplexHeatmap/tests_not_run’
─  building ‘ComplexHeatmap_2.1.1.tar.gz’

Installing package into ‘/home/tyler/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘ComplexHeatmap’ ...
** using staged installation
** R
Error in parse(outFile) :
  /tmp/RtmpNC7FGr/R.INSTALL1bf9611b29f3/ComplexHeatmap/R/Upset.R:583:17: unexpected symbol
582:                 }
583:                 nm
                     ^
ERROR: unable to collate and parse R files for package ‘ComplexHeatmap’
* removing ‘/home/tyler/R/x86_64-pc-linux-gnu-library/3.6/ComplexHeatmap’
* restoring previous ‘/home/tyler/R/x86_64-pc-linux-gnu-library/3.6/ComplexHeatmap’
Error: Failed to install 'ComplexHeatmap' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpJ6s7zc/file2ab65cd99fb8/ComplexHeatmap_2.1.1.tar.gz’ had non-zero exit status
```

**Comment by jokergoo** [comment]
I forgot to update to GitHub. Now you can try again.

**Comment by funnell** [comment]
Looks great, thanks so much! Fantastic package 👍
