### ISSUE TITLE
Output of comb_size to include set names

### ISSUE THREAD

**Issue by kamclean** [jokergoo/ComplexHeatmap#334]
Hi - really appreciate the package but feel like there might be a small gap in functionality. I want "comb_size" to produced named sets instead of / in addition to binary named output (e.g. "c(set_1, set_2, set_1&set_2)" instead of "c(10, 01, 11)"). 

Using purely the output from "comb_size" and "set_name", I've made a function for my own use (below). I'm sure lots of ways this could be more efficiently coded (and produces tibble instead of dataframe), but I think useful functionality to include either as a separate function or optional output for comb_size? (apologies if the package has this functionality that I've just missed).

comb_size_name <- function(comb_mat){
  
  out_comb_size <- ComplexHeatmap::comb_size(comb_mat)

  out_set_name <- ComplexHeatmap::set_name(comb_mat)
  
  name_binary <- names(out_comb_size) %>%
    tibble::as_tibble() %$%
    stringr::str_split_fixed(value, "", length(out_set_name)) %>%
    tibble::as_tibble()
  
  for(i in c(1:length(out_set_name))){
    name_binary <- name_binary %>% dplyr::mutate_if(names(.)==names(.)[i],
                                                    function(x){ifelse(x=="1",paste0(out_set_name[i], "&", ""),"")})}
  
  name_new <- name_binary %>%
    tidyr::unite(col = "name", sep = "") %>%
    dplyr::mutate(name = substr(name, 1, nchar(name)-1)) %>% pull(name)
  
  out <- out_comb_size %>% setNames(name_new) %>% 
    as.data.frame() %>%
    tibble::rownames_to_column(var = "combination") %>% tibble::as_tibble() %>%
    setNames(c("combination", "n")) %>%
    dplyr::mutate(degree = stringr::str_count(combination, pattern = "&")+1) %>%
    dplyr::select(combination, degree, n)
  
  return(out)}

**Comment by jokergoo** [comment]
Thanks for this suggestion! Ehnnn... I found `c(10, 01, 11)` is more clear to represent the combination of intersections, while `c(set_1, set_2, set_1&set_2)` is not. E.g. for `set_1`", it is not very clear whether it represents just `set_1` or `set_diff(set_1, set_2)` just by reading the text. I think it would be more difficult when the number of sets becomes large. On the other hand, converting `c(10, 01, 11)` to the real set names is very easy, as what you did, or:

```r
> comb_name(m1)
[1] "100" "010" "001" "110" "101" "011" "111"
> paste(sapply(strsplit(comb_name(m1), ""), function(x) paste(set_name(m1)[x == 1], collapse = "&")))
[1] "a"     "b"     "c"     "a&b"   "a&c"   "b&c"   "a&b&c"
```
