### ISSUE TITLE
change order of hclustering

### ISSUE THREAD

**Issue by gulergul** [jokergoo/ComplexHeatmap#335]
I used pearson as a distance method and average as a linkage method with complexHeatmap. I splitted cluster of rows nicely. However, I want to change these cluster's order. "row_dend_reorder = TRUE" and  "split <- factor(hc$clusters, levels =c(2,1,3,4))" do not make any difference in the heatmap

**Comment by jokergoo** [comment]
I think you need to set `row_dend_reorder = FALSE`.

**Comment by gulergul** [comment]
Sorry, I tried it but still same

**Comment by jokergoo** [comment]
Sorry for the previous reply. What is the version you use? It seems you are still using the old version (< 1.99.0)? We need to set `cluster_row_slices = FALSE`.

**Comment by gulergul** [comment]
The version I use is 2.1.0. Ahh , thanks so much, it works now
