### ISSUE TITLE
Label the exact number of elements in both set size and intersection size bar plots

### ISSUE THREAD

**Issue by guodudou** [jokergoo/ComplexHeatmap#337]
Hi, thank you very much for this great package. I really like its flexibility for users to customize graphs. I use it for all my heatmaps and am so excited that you implemented different modes of intersections in upset plot which is a great improvement. 

I would like to label the exact number of elements on top of both set size and intersection size bar plots, do you have any suggestion about how to do it?

Thank you very much!

**Comment by jokergoo** [comment]
There is no option you can directly control the labels on the bars, but you can manually add it by `decorate_annotation()`:

```r

set.seed(123)
lt = list(a = sample(letters, 5),
          b = sample(letters, 10),
          c = sample(letters, 15))
m = make_comb_mat(lt)
col_size = comb_size(m)
row_size = set_size(m)
ht = UpSet(m, 
	top_annotation = upset_top_annotation(m, ylim = c(0, max(col_size)*1.1)),
	right_annotation = upset_right_annotation(m, ylim = c(0, max(row_size)*1.1)))
ht = draw(ht)

col_od = column_order(ht)
row_od = row_order(ht)

decorate_annotation("Intersection\nsize", {
	grid.text(col_size[col_od], 
		seq_len(length(col_size)), 
		unit(col_size[col_od], "native") + unit(2, "mm"), 
		default.units = "native", just = "bottom",
		gp = gpar(fontsize = 8))
})
decorate_annotation("Set size", {
	grid.text(row_size[row_od], 
		unit(row_size[row_od], "native") + unit(2, "mm"), 
		rev(seq_len(length(row_size))), 
		default.units = "native", just = "bottom", rot = -90,
		gp = gpar(fontsize = 8))
})
```

![image](https://user-images.githubusercontent.com/449218/61124615-95216c00-a4a7-11e9-9165-50c7424cf258.png)

**Comment by guodudou** [comment]
This is exactly what I am looking for. Thank you very much for the demo! I will test it out.
