### ISSUE TITLE
k-means clustering

### ISSUE THREAD

**Issue by Siacm** [jokergoo/ComplexHeatmap#338]
Hi, I'm trying out the tutorial on your github page- and I'm up to the heatmap split section, but these arguments aren't working for me even after restarting R

row_km
row_km_repeats
column_km
column_km_repeats
column_split
row_km_split

These are the packages I've downloaded. Have I missed something?

library(ComplexHeatmap)
library(circlize)
library(cluster)
library(dendextend)
library(dendsort)
library(seriation)

Thank you.

**Comment by jokergoo** [comment]
I think you might need to update the ComplexHeatmap to a version >= 2.0.0

**Comment by Siacm** [comment]
It worked. Thank you!
