### ISSUE TITLE
Oncoprint: Arrange top annotation from highest to lowest bar chart? Decimal points in percentages?

### ISSUE THREAD

**Issue by Siacm** [jokergoo/ComplexHeatmap#339]
Hi! I finished the tutorial on github. Using oncoprint, I was just wondering if there was a way to arrange the top annotation from highest bar to lowest just the like left annotation of stacked bar graphs?

Also, is there a way to display two decimal points on the percentage annotation? Its confusing to see 0% but a coloured bar.

**Comment by jokergoo** [comment]
1. the order of columns is controlled by `column_order` argument. You can set it as a self-defined order which is from the highest occurrence to the lowest.

2. The digit of the percent values is controlled by `pct_digits` argument.

**Comment by Siacm** [comment]
It worked! This is a really great R tool. I have another question - sorry, I'm new to all this. Is it possible to apply dendrogram branches and split them into clusters using oncoprint?

**Comment by jokergoo** [comment]
You can first generate a dendrogram (a hclust object) and split by cutree, something like:

```r
hc = hclust(dist(...))
groups = cutree(hc, ...)
```

Now `groups` is a categorical vector and you can assign to `row_split` argument in `oncoPrint()` to split rows:

```r
oncoPrint(..., row_split = groups)
```

**Comment by Siacm** [comment]
Awesome. Thank you!
