### ISSUE TITLE
heatmap_legend_side does not moves the annotation legends 

### ISSUE THREAD

**Issue by tiagochst** [jokergoo/ComplexHeatmap#34]
Hi, 

When we use the parameter heatmap_legend_side to move the legends to the bottom
`draw(ht, heatmap_legend_side = "bottom"), `
it only moves the legends from the onconprint, but not for annatations to the bottom.

How can I do that? I would like to have all legends in the bottom. 
Thanks.

![image](https://cloud.githubusercontent.com/assets/145529/14893235/ef1ec160-0d44-11e6-9f3c-fa5f12dd6c24.png)

**Comment by jokergoo** [comment]
There are actually two types of annotations: heatmap annotation and annotation annotations. The package put them independently. In your case, you should:

```{r}
draw(ht, heatmap_legend_side = "bottom", annotation_legend_side = "bottom")
```

If you install the newest version of ComplexHeatmap, the package provides more flexible tyles for legends, especially useful when you put legends at the bottom of the heatmap. Check this link:

http://jokergoo.github.io/blog/html/dde69a9cf5a606a9486b19eb91ba6f4e.html

In this updated vignette, I also show how to put legend at the bottom and horizontal for one oncoprint (the last third plot):

http://www.bioconductor.org/packages/devel/bioc/vignettes/ComplexHeatmap/inst/doc/s8.oncoprint.html

**Comment by crazyhottommy** [comment]
Hi, I found this is very useful, have you integrate this into EnrichedHeatmap?

Thanks,
Ming

**Comment by jokergoo** [comment]
How do integrate this specific form of heatmap (oncoprint) to enriched heatmaps? In principle, yes, because they are all inherited from the `Heatmap` class and `HeatmapList` class and can be used mixed.

**Comment by crazyhottommy** [comment]
In enrichedHeatmap, when there are multiple heatmaps, how to adjust the legend position to match each legend to each heatmap when put the legend in the bottom? `draw(ht, heatmap_legend_side = "bottom")`. Thx!

**Comment by jokergoo** [comment]
I just updated the package last several weeks to provide a more flexible control of legends. You can find the documentation here: http://www.bioconductor.org/packages/devel/bioc/vignettes/ComplexHeatmap/inst/doc/s5.legend.html and here: http://jokergoo.github.io/blog/html/dde69a9cf5a606a9486b19eb91ba6f4e.html

Because EnrichedHeatmap is inherited from by ComplexHeatmap, the configuration of legends are the same. So, in your case, it would be something like:

```
draw(ht, heatmap_legend_side = "bottom")
```

You can have more settings for each legend by `heatmap_legend_param` argument.

**Comment by crazyhottommy** [comment]
Let me clarify a bit.

When there are a few heatmaps in EnrichedHeatmap, setting `heatmap_legend_side = "bottom"` will
put all the heatmap legends  in the middle bottom of all the heatmaps. but  the legend does not align well with each of the corresponding heatmap.  How to set the position of the legend? Before, I used to save the PDF and move the legend using [inkscape](https://inkscape.org/en/), but I think it is good now to have flexibility to specify the position when making the heatmaps.

I checked the tutorial, but did not find a parameter for position:

```
title: title of the legend
title_gp: graphic parameters for the legend title
title_position: position of title relative to the legend, possible values are topcenter, topleft, leftcenter, lefttop.
color_bar: style of the color bar, i.e. continuous or discrete
grid_height: height of the small grid in the color bar, only works for discrete color bar
grid_width: width of the color bar
grid_border: border of the color bar
at: break values shown on the legend
labels: labels which correspond to the breaks values
labels_gp: graphic parameters for legend labels
nrow and ncol: if there are too many legends, they can be put into an array. These two parameters controls number of rows or columns
legend_direction: when color_bar is set to continuous, it controls the direction of the legend, possible values are vertical and horizontal
legend_width and legend_height: when color_bar is continuous, the width or height of the legend
```

**Comment by jokergoo** [comment]
What do you mean "**the legend does not align well with each of the corresponding heatmap**"? Do you mean each legend should be put directly under each heatmap while not arrange them compactly?

**Comment by crazyhottommy** [comment]
correct. That's what I am saying, because for enrichedHeatmap, I want to put the histone mark name and the legend under each heatmap.

**Comment by jokergoo** [comment]
Em... I don't think currently I will add this functionality. I have several reasons not doing this:

1. If putting all legends compactly, from my point of view, it actually gives a very consistent visual effect.
2. The width of each legend always change, which means, it is not always true that the width of the legend is smaller than the width of the heatmap (e.g. a heatmap with only one column). If enforce to put legend directly under each heatmap, it would be possible that two legends will overlap.
3. Sometimes not all heatmaps need a legend, some heatmaps showing same measurement can share one legend. E.g. in following heatmap list, last four heatmaps are showing methylation data and there is only one legend needed.

I think there are some simple ways that help to correspond legend to the heatmap, like using different color palette, adding column titles...

![image](https://cloud.githubusercontent.com/assets/449218/14939812/16ea2ecc-0f8a-11e6-9159-f0d80bce5354.png)

**Comment by crazyhottommy** [comment]
fair enough and I agree with all the points you have made. I will need to use different color for each heatmap as suggested. Thanks!

**Comment by tiagochst** [comment]
Thanks!

**Comment by Tommaso12** [comment]
Hi! "annotation_legend_side" and "heatmap_legend_side" support also something like "up-righ corner"?

**Comment by Tommaso12** [comment]
Ok perfect thank you!
