### ISSUE TITLE
Oncoprints with different dimensions but same cell size

### ISSUE THREAD

**Issue by RaqManzano** [jokergoo/ComplexHeatmap#342]
Hi,

I am a big fan on ComplexHeatmaps. The flexibility that provides is great, however I am not able to generate oncoprints with same cell size independently of the number of rows and columns. In the docs I see this can be achieved when the number of columns is the same with a very easy to follow example (https://jokergoo.github.io/ComplexHeatmap-reference/book/other-tricks.html#set-the-same-cell-size-for-different-heatmaps-with-different-dimensions).

Do you have a similar example where the number of rows and columns differ from plot to plot? E.g. how could I plot a matrix that is 30x15 and 40x20 with same cell size.

Thanks a lot for your help.

**Comment by jokergoo** [comment]
The easiest solution is to set `width` and `height` arguments to fixed units, e.g. for the 30x15 matrix, set to 30cmx15cm and for the 40x20 matrix, set to 40cmx20cm. When saving the plot as e.g. PDF, set the PDF image size to very large values (e.g. 80cmx80cm). Then in the PDF, you will see the surrounding big white borders, but the cell size for the two oncoprint will be the same.

**Comment by RaqManzano** [comment]
Thanks a lot for the easy fix! This is certainly working for me.
