### ISSUE TITLE
Example on Complex alteration types no longer working?

### ISSUE THREAD

**Issue by RaqManzano** [jokergoo/ComplexHeatmap#344]
The example in the manual on the section "7.1.4 Complex alteration types" is no longer working as it is asking for the definition of exonic and intronic in the colors vector.
Any other way we can avoid adding to the oncoprint barplot specific alterations?

This line:
`ht = oncoPrint(m, 
               alter_fun = alter_fun, 
               get_type = function(x) strsplit(x, ";")[[1]],
               col = c(snv = "red", indel = "blue"))`

gives this error:
`You should define colors for:intronic, exonic`

Thanks.

**Comment by jokergoo** [comment]
Are you using version >= 2.0.0? According to the error message, it seems you are still using the older version.

**Comment by RaqManzano** [comment]
Hi,
Yes that solved it! Thanks a lot.
