### ISSUE TITLE
Upset bar color

### ISSUE THREAD

**Issue by aderzelle** [jokergoo/ComplexHeatmap#345]
Hello,
that's probably a very basic question but I am not sure to understand why my code doesn't produce the colors I want. 
`UpSet(m1,  comb_col = c("blue", "black")[comb_degree(m1)])`
Here is the combination degree of my matrix
```
comb_degree(m1)
10000000 01000000 00100000 00010000 00001000 00000100 00000010 00000001 11111111 
       1        1        1        1        1        1        1        1        8 
```
The resulting plot doesn't show the set comprised of all intersections. This is what I get
![RplotWrong](https://user-images.githubusercontent.com/23341393/62550856-3e6f3e00-b86b-11e9-8ccb-4cef5f2a446a.png)

But I would like those intersections, with the first bar in blue and all others in black
![RplotRight](https://user-images.githubusercontent.com/23341393/62551038-8ee69b80-b86b-11e9-8dab-dfec17726346.png)

I do not understand how my case is different from the one of the doc. In the doc, 3 colors are passed for a combination degree 
```
100 010 001 110 101 011 111 
  1   1   1   2   2   2   3 

```
Thanks a lot.

EDIT: actually, is it also possible to control colors like in the following example, taken from the doc

```UpSet(m, top_annotation = HeatmapAnnotation(
    degree = as.character(comb_degree(m)),
    "Intersection\nsize" = anno_barplot(comb_size(m), 
        border = FALSE, 
        gp = gpar(fill = "black"), 
        height = unit(2, "cm")
    ), 
    annotation_name_side = "left", 
    annotation_name_rot = 0))

```
I noticed the colors are different every time, how do I get something similar to

`degree= c("color1", "color2", "color3")`

**Comment by jokergoo** [comment]
In your example:

```
UpSet(m1, comb_col = c("blue", "black")[comb_degree(m1)])
comb_degree(m1)
10000000 01000000 00100000 00010000 00001000 00000100 00000010 00000001 11111111 
       1        1        1        1        1        1        1        1        8 
```

The maximal degree is 8, while there are only two values in `comb_col`. Then `c("blue", "black")[8]` will give you `NA` and that is why you don't see the first bar in your plot.

You can adjust your code to:

```r
comb_col = ifelse(comb_degree(m1) > 1, "blue", "black")
UpSet(m1, comb_col = comb_col)
```

In the example in the book :

```
100 010 001 110 101 011 111 
  1   1   1   2   2   2   3 
```

The degree of the combination is the number of sets that are selected, which is, the number of 1 in each of the three-digit code, or the number of black dots in each vertical lines.

**Comment by aderzelle** [comment]
Ohh ok :) perferctly clear now. 
Thanks for the explanations and the cool package.

**Comment by aderzelle** [comment]
Actually,  one last question 

```
UpSet(m, comb_col = comb_col, top_annotation = HeatmapAnnotation(
    degree = (comb_col),
    "Intersection\nsize" = anno_barplot(comb_size(m), 
        border = FALSE, 
        gp = gpar(fill = comb_col), 
        height = unit(2, "cm")
    ), 
    annotation_name_side = "left", 
    annotation_name_rot = 0))
```
degree is ignoring my colour settings.

**Comment by jokergoo** [comment]
What do you use `degree = (comb_col)` for? For setting colors? If you want to set colors, you should set in `gp = gpar()`:

```r
UpSet(m, comb_col = comb_col, top_annotation = HeatmapAnnotation(
    "Intersection\nsize" = anno_barplot(comb_size(m), 
        border = FALSE, 
        gp = gpar(fill = comb_col, col = comb_col),   # <- here
        height = unit(2, "cm")
    ), 
    annotation_name_side = "left", 
    annotation_name_rot = 0))
```

**Comment by aderzelle** [comment]
Sorry, my example was not clear indeed. What I want to do is emulate the following example from the doc

```
UpSet(m, top_annotation = HeatmapAnnotation(
    degree = as.character(comb_degree(m)),
    "Intersection\nsize" = anno_barplot(comb_size(m), 
        border = FALSE, 
        gp = gpar(fill = "black"), 
        height = unit(2, "cm")
    ), 
    annotation_name_side = "left", 
    annotation_name_rot = 0))
```
I would like to control the colors of the "degree bar". 
If I understand well the `degree = as.character(comb_degree(m))` is used for the legend annotation.
How do I control the color of the "degree bar"?
In the following example
```
comb_col = ifelse(comb_degree(m) > 1, "blue", "red")
UpSet(m, comb_col = comb_col,
      top_annotation = HeatmapAnnotation(
        degree = as.character(comb_degree(m)),
         "Intersection\nsize" = anno_barplot(comb_size(m), 
         border = FALSE, 
         gp = gpar(fill = comb_col), 
         height = unit(2, "cm")
    ), 
    annotation_name_side = "left", 
    annotation_name_rot = 0))
```
```
how do I control the color of the degree bar, so that it's not light blue and salmon? 
![example](https://user-images.githubusercontent.com/23341393/62768636-8e324d00-ba97-11e9-96ca-d97240817756.png)
thank you

**Comment by jokergoo** [comment]
OK, I see, then you need to define the colors for "degree" annoation by `col` argument:

```
comb_col = ifelse(comb_degree(m) > 1, "blue", "red")
UpSet(m, comb_col = comb_col,
      top_annotation = HeatmapAnnotation(
        degree = as.character(comb_degree(m)),
        col = list(degree = c("1" = "red", "8" = "blue")),
         "Intersection\nsize" = anno_barplot(comb_size(m), 
         border = FALSE, 
         gp = gpar(fill = comb_col), 
         height = unit(2, "cm")
    ), 
    annotation_name_side = "left", 
    annotation_name_rot = 0))
```

**Comment by jokergoo** [comment]
It should be after the `anno_barplot()`, i.e., after

```
"Intersection\nsize" = anno_barplot(comb_size(m)) # <- notice the proper closing bracket
```

**Comment by aderzelle** [comment]
Ok, thanks for having taken the time for the explanation.
