### ISSUE TITLE
Rotate column title

### ISSUE THREAD

**Issue by ecpierce** [jokergoo/ComplexHeatmap#346]
Hi, 
Is there any way to rotate the column titles?  I saw your answer about column names, but it is really the titles that I need help with.

Thanks!
Emily

**Comment by jokergoo** [comment]
Can you give me a user case of the need to rotating titles? or can you show me some example plots?

**Comment by ecpierce** [comment]
Yes, here is an example.  You can see how the column titles at the top are overlapping each other.  I can make the text smaller to fix this , but then it is hard to see...It would be nice to be able to rotate the titles so that they will not run into each other.  Or if you have another idea how to solve this, that would be great.

**Comment by ecpierce** [comment]
Yes, here is an example.  You can see that the column titles are running into each other on top. 
 I can fix this by making the font smaller, but then they are hard to see.  It would be nice to be able to rotate them, or if you have any other suggestions of how to fix this, that would be great
[Doc3.pdf](https://github.com/jokergoo/ComplexHeatmap/files/3487272/Doc3.pdf)

**Comment by ecpierce** [comment]
I think I can solve it by just using block annotations instead of column titles and rotating the block annotations

**Comment by jokergoo** [comment]
Sorry for the late reply. I was on vocation.

En... If it is a one-column heatmap, I think the column name should be enough while you don't actually need the column title for that.
