### ISSUE TITLE
Reording of pch matrix in anno_simple

### ISSUE THREAD

**Issue by mbdabrowska1** [jokergoo/ComplexHeatmap#347]
Adding character annotations to a matrix annotation using `anno_simple(..., pch=my_matrix)`, it seems like the `pch` matrix isn't reordered accoring to the dendrogram for a row annotation, and is done incorrectly for a column annotation (the colours are reordered fine). See the following example:

Create a matrix as in the tutorial:

```
set.seed(123)
mat = matrix(rnorm(100), 10)
rownames(mat) = paste0("R", 1:10)
colnames(mat) = paste0("C", 1:10)
```

Create an annotation matrix with character labels:
```
textanno = cbind(c(rep(" ", times=5), rep("*", times=5)), c(rep("*", times=5), rep(" ", times=5)) )
row_anno = rowAnnotation(test=anno_simple(textanno, pch = textanno))
col_anno = HeatmapAnnotation(test2=anno_simple(textanno, pch=textanno), which ="col")
```

If I plot this without any clustering then we get:
```
Heatmap(mat , right_annotation = row_anno, bottom_annotation = col_anno , cluster_rows = F, cluster_columns = F)
```
![image](https://user-images.githubusercontent.com/26898140/62780017-a6609700-baac-11e9-9ee5-aa2bfcb29fde.png)

You can see that the annotation is five blanks then five *s in the first column and vice-versa in the second. 

If we now cluster:
```
Heatmap(mat , right_annotation = row_anno, bottom_annotation = col_anno)
```
![image](https://user-images.githubusercontent.com/26898140/62780109-d4de7200-baac-11e9-82c7-d2742e119ac1.png)

You can see that the colour fill on the annotations has been reordered and looks right. However the text annotations on the row annotation has not been rearranged, and those on the columns have been re-arragned but are in the wrong place: you can see this as in some cases there are `*` in both "rows"(or columns depending on how you see it), when there shouldn't be. 

In the `anno_simple` code, there is a line that re-orders the `pch` matrix in the column case:

https://github.com/jokergoo/ComplexHeatmap/blob/0d85dd1e82f1b829cd59c158993b2c91248e4c36/R/AnnotationFunction-function.R#L259-L270

but there is no equivalent code in the row case:
https://github.com/jokergoo/ComplexHeatmap/blob/0d85dd1e82f1b829cd59c158993b2c91248e4c36/R/AnnotationFunction-function.R#L233-L237

I would drop a PR with equivalent code in the `row_function` as there was in the `col_function`, but the `col_function` code doesn't quite seem to be working. I will send one over if I work it out. 

sessionInfo:

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS
Matrix products: default
BLAS:   /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0
locale:
[1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8
[5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C
[9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C
attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base
other attached packages:
[1] ComplexHeatmap_2.0.0
loaded via a namespace (and not attached):
[1] colorspace_1.4-1    compiler_3.6.1      rjson_0.2.20        circlize_0.4.6      parallel_3.6.1      tools_3.6.1
[7] GlobalOptions_0.1.0 RColorBrewer_1.1-2  clue_0.3-57         GetoptLong_0.1.7    shape_1.4.4         packrat_0.5.0
[13] cluster_2.1.0       png_0.1-7
```

**Comment by jokergoo** [comment]
Thanks!
