### ISSUE TITLE
long annotation names have been cut

### ISSUE THREAD

**Issue by weiliuyuan** [jokergoo/ComplexHeatmap#350]
Hi, 

Fantastic package. 
I've got a question about the annotation names length. I have a couple of very long annotation names which have been cut when i generated the heatmap. 
Is there anything similar to `row_names_max_width ` that i can adjust the margins for annotation names?  
Many thanks! 

Best,
Wei

**Comment by jokergoo** [comment]
You need to control the margins of the whole plot by setting `padding` argument in `draw()`, similar as in the following link:

https://jokergoo.github.io/ComplexHeatmap-reference/book/a-list-of-heatmaps.html#manually-increase-space-around-the-plot
