### ISSUE TITLE
support more sets in make_comb_mat()

### ISSUE THREAD

**Issue by jokergoo** [jokergoo/ComplexHeatmap#351]
```r
lt = lapply(letters, function(x) sample(letters, 10))
names(lt) = letters
mat = make_comb_mat(lt)
```

**Comment by songeric1107** [comment]
although I install the library(complexHeatmap), this function (make_comb_mat) is still not working

**Comment by jokergoo** [comment]
@songeric1107 Do you mean the function `make_comb_mat` is not found? You need to use ComplexHeatmap higher than 2.0.0.

**Comment by songeric1107** [comment]
Thank you, I download the new version from GitHub, it works, thank you
