### ISSUE TITLE
How to creat legend for a barplot without knowing which levels of a variable correspond to which color

### ISSUE THREAD

**Issue by lykosherdshep** [jokergoo/ComplexHeatmap#353]
I want to creat a barplot with two color bar annotation(here is only one variable for color bar annotation), but I have some questions about the legend. I don't know which level of test$values correspond to which color, is there any way to creat legend in this circumstance? Here is my code.

test <- data.frame(sample = paste0("sample", 1:100), tumor = rep(c("breast", "lung", "bladder", "colorectal", "prostate"), 20), allele = rep(c("exon1", "exon2", "exon3", "exon4", "exon5", "exon6", "exon7", "exon8", "exon9", "exon10"), 10), values = rnorm(100))
ha_list <- HeatmapAnnotation(bar = anno_barplot(test$values, 
                                     gp = gpar(fill = test$allele), 
                                     height = unit(6, "cm"))) %v% 
  HeatmapAnnotation(tumor = anno_simple(test$tumor))

**Comment by jokergoo** [comment]
Because the colors for the barplots cannot be captured by the package,  you need to manually create a legend:

```r
test <- data.frame(sample = paste0("sample", 1:100), 
	tumor = rep(c("breast", "lung", "bladder", "colorectal", "prostate"), 20), 
	allele = rep(c("exon1", "exon2", "exon3", "exon4", "exon5", "exon6", "exon7", "exon8", "exon9", "exon10"), 10), values = rnorm(100))

allele_col = structure(1:10, names = paste0("exon", 1:10))
ha_list <- HeatmapAnnotation(bar = anno_barplot(test$values,
	gp = gpar(fill = allele_col[test$allele]),
	height = unit(6, "cm"))) %v%
HeatmapAnnotation(tumor = anno_simple(test$tumor))
draw(ha_list, heatmap_legend_list = Legend(title = "Allele", labels = names(allele_col), legend_gp = gpar(fill = allele_col)))
```
![image](https://user-images.githubusercontent.com/449218/64319845-952c7c80-cfbd-11e9-9a30-4cccd45a1fac.png)

**Comment by lykosherdshep** [comment]
Thanks for your help!!!
