### ISSUE TITLE
col_fun not recognized in `annotation_legend_params`

### ISSUE THREAD

**Issue by endrebak** [jokergoo/ComplexHeatmap#354]
I have the following color function which works:

```
col_fun = colorRamp2(c(0, 1), c("white", "black"))
print(col_fun(0))
print(col_fun(1))
# [1] "#FFFFFFFF"
# [1] "#000000FF"
```

However, when I try to use it in my `heatmap_legend_params`, it is not recognized, as it uses a blue-white-red instead of a white-black scale:

```
Heatmap(m, name="Expression", cluster_columns=FALSE, use_raster=FALSE, right_annotation=annotation,
        heatmap_legend_param=list(col_fun=col_fun, title="Hooooo", at=c(0, 1), labels = c(0, 1)))
```

![Screenshot 2019-09-05 at 13 15 08](https://user-images.githubusercontent.com/17778898/64337221-37109100-cfdf-11e9-813c-0e43251fb043.png)

According to the docs, my code should work:

> The parameters introduced later can be directly used to customize the legends by heatmap_legend_param argument in Heatmap() and annotation_legend_param argument in HeatmapAnnotation()

Do you have any idea how to fix this?

Ps.

```
circlize version 0.4.7
ComplexHeatmap version 2.0.0
```

**Comment by jokergoo** [comment]
`col_fun` cannot be used in `heatmap_legend_param` because the color mapping should be controlled by the heatmap itself. You should control the color mapping in `Heatmap()` function:

```r
Heatmap(m, col = col_fun, ...)
```

**Comment by endrebak** [comment]
Thanks for the prompt reply :)
