### ISSUE TITLE
More examples for anno_zoom?

### ISSUE THREAD

**Issue by endrebak** [jokergoo/ComplexHeatmap#355]
I am wondering what `anno_zoom` is capable of. I guess it is one of the killer features of ComplexHeatmap and that it is capable of many things, but unfortunately, so far, I have only been able to find one example (the one with boxplots).

I do not have much experience with R plotting so the example leaves me wondering

- whether (and how) I can use ggplot2 with `anno_zoom`
- whether (and how) I can use other libraries' plotting functions (ChIPseeker for example)

Also, it would be good with some more examples. Some thoughts from the top of my head:

- barplots showing the number of protein and ncRNA genes in each `align_to`
- plots only showing the 10, 25, 50, 75, 90 percentile lines for each `align_to` (my data has too many columns so the boxplots become weird.)

I am also wondering how the size parameter works with some examples. Should the fractional size be from 0-1? 0-100?

Thanks for reading :)

**Comment by jokergoo** [comment]
Hi, basically, you can define any type of graphics in `panel_fun`.

1. add ggplot2:

```r
set.seed(123)
m = matrix(rnorm(100*10), nrow = 100)
subgroup = sample(letters[1:3], 100, replace = TRUE, prob = c(1, 5, 10))

panel_fun_ggplot2 = function(index, nm) {
    df = melt(m[index, , drop = FALSE], varnames = c("row_index", "col_index"))
    g = ggplot(df, aes(x = factor(col_index), y = value)) + geom_boxplot()
    g = grid.grabExpr(print(g))
    pushViewport(viewport())
    grid.rect()
    grid.draw(g)
    popViewport()
}
anno = anno_zoom(align_to = subgroup, which = "row", panel_fun = panel_fun_ggplot2, 
    size = unit(4, "cm"), gap = unit(1, "cm"), width = unit(6, "cm"))
Heatmap(m, name = "mat", right_annotation = rowAnnotation(foo = anno), row_split = subgroup)
```

![image](https://user-images.githubusercontent.com/449218/64523053-b4981200-d2fb-11e9-936e-76c3cfff8c59.png)


2. draw heatmap:

```r
panel_fun_ht = function(index, nm) {
    ht = Heatmap(m[index, , drop = FALSE], show_heatmap_legend = FALSE,
    	cluster_rows = FALSE, cluster_columns = FALSE)
    g = grid.grabExpr(draw(ht))
    grid.draw(g)
}
anno = anno_zoom(align_to = subgroup, which = "row", panel_fun = panel_fun_ht, 
    size = as.numeric(table(subgroup)), gap = unit(1, "cm"), width = unit(6, "cm"))
Heatmap(m, name = "mat", right_annotation = rowAnnotation(foo = anno), row_split = subgroup)
```

![image](https://user-images.githubusercontent.com/449218/64523092-d0031d00-d2fb-11e9-8c6e-41a15b18b3ab.png)


3. The density distribution with 5 quantiles:

```r

panel_fun_density = function(index, nm) {
    ht = densityHeatmap(m[index, , drop = FALSE], column_title = "")
    g = grid.grabExpr(draw(ht))
    grid.draw(g)
}
anno = anno_zoom(align_to = subgroup, which = "row", panel_fun = panel_fun_density, 
    size = c(1, 1, 1), gap = unit(1, "cm"), width = unit(10, "cm"))
Heatmap(m, name = "mat", right_annotation = rowAnnotation(foo = anno), row_split = subgroup)
```
![image](https://user-images.githubusercontent.com/449218/64523131-ea3cfb00-d2fb-11e9-8e43-a86513593f16.png)

The sub-matrix can be obtained by `mat[index, , drop = FALSE]` in the `panel.fun()`. If the plot which is going to be added is based on **grid** graphic system, it can be captured by `grid.grabExpr()`. If it is made by the base graphic system, there must be some way to capture it as well.

The value for `anno_size` can be in `unit` class, e.g. `unit(4, "cm")`, or a vector of numeric values that will be scaled to make the sum to be 1.

**Comment by endrebak** [comment]
This is absolutely incredible. Thanks!

**Comment by Chessrein** [comment]
I'm a amateur and learning this package for a few week.
As the same, I try a different plot by anno_zoom().
I want to draw a historgram to show the range of row in each row_cluster by each group.
So, Where is the parameter 'index', in the function 'panel_fun? How does it generated?
> panel_fun_ggplot2 = function(**index**, nm) {
>     **df = melt(m[**index**, column_hclust$order, drop = FALSE], varnames = c("row_index", "col_index"))**
>     g = ggplot(df, aes(x = factor(col_index), y = value)) + geom_boxplot() ###use ggplot2 grammar
>     g = grid.grabExpr(print(g))
>     pushViewport(viewport())
>     grid.rect()
>     grid.draw(g)
>     popViewport()
> }

Can I save this parameter ‘df’ in .csv file? 
> df = melt(m[index, column_hclust$order, drop = FALSE], varnames = c("row_index", "col_index"))
Thanks for reading.
