### ISSUE TITLE
grouped anno_barplot, broken axis

### ISSUE THREAD

**Issue by GayathriRajan** [jokergoo/ComplexHeatmap#356]
Thanks to you for developing a great package for heatmap analysis. I would also like to know if there is a way to do the following:
    1. Draw a grouped anno_barplot where the bars are placed side to side instead of being 
    stacked.
    2. Break the x axis in anno_barplot to show far placed values.
    3. Place the heatmap legend in the topright.

Thanks!

**Comment by jokergoo** [comment]
Hi,

1. the function does not support to put bars side by side. Basically the space  for each heatmap column is not big enough to do so.
2. No, I suggest you can apply a log-transformation on the original data.
3.  There is an API which is not public yet but you can use:

```r
ht = Heatmap(...) + NULL # to enforce it to be a HeatmapList object
ht@heatmap_legend_param$offset = "annotation_top" # to set the legend to be topright
draw(ht)
```

**Comment by GayathriRajan** [comment]
Thanks for the suggestions. Can i make the plots separately and add it to the heatmap as annotation?

**Comment by jokergoo** [comment]
You can check #261

**Comment by GayathriRajan** [comment]
Will check it, Thanks

**Comment by GayathriRajan** [comment]
Dr. Gu,
I tried this code to move the legend, but it doesn't work

Regards,
Gayathri Rajan
