### ISSUE TITLE
Dendrograms on Oncoprint and tooltips

### ISSUE THREAD

**Issue by suraykar** [jokergoo/ComplexHeatmap#357]
I am really enjoying using ComplexHeatmap to visualize genomic data. Two questions that I could not resolve referring to the manual:

1. Why are dendrograms not allowed on OncoPrint? I saw [this thread](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=7&cad=rja&uact=8&ved=2ahUKEwj48fre_MnkAhUqmuAKHUCLDfwQFjAGegQIBxAB&url=https%3A%2F%2Fgithub.com%2Fjokergoo%2FComplexHeatmap%2Fissues%2F339&usg=AOvVaw2WkqPtQKleInQ0eypXWZsf) which talks about kind of doing this but not all-out showing dendrograms.

2. Is there a way to add tool-tips on the heatmap/annotations? There is a lot of genomic data that cannot be visualized in a heatmap/annotations or would be rather easily shown in a tooltip.

Thank you!

**Comment by jokergoo** [comment]
Normally if there is a dendrogram, it should have close correspondence to the heatmap it attaches to. Let's say, if there is a dendrogram for an oncoPrint, what does the dendrogram show for the oncoPrint? Does it show the mutation similarity for two genes or two samples? If there is only one single mutation type, there are many measurements for the similarity for two genes, but when there are sevaral mutation types, will you count an indel as same as a snv when you calculate the similarity? And also what does the hierarchy of the dendrogram mean for an oncoPrint? 

Nevertheless, if you really have a method to cluster the oncoPrint, you can first obtain the ordering from the hierarchical clustering and then assign to `row_order` argument.

If you have a good example to show adding dendrogram to oncoPrint makes sense, I will modify `oncoPrint()` to allow it to perform row/column clustering.

For the second question, I cannot give any advice without seeing what your genomic data look like.

**Comment by jokergoo** [comment]
OK, now `oncoPrint()` supports `cluster_rows` and `cluster_columns` arguments. Note values for these two arguments should be `dendrogram`/`hclust` objects. You can update the package from GitHub.

```r

mat = read.table(textConnection(
"s1,s2,s3
g1,snv;indel,snv,indel
g2,,snv;indel,snv
g3,snv,,indel;snv"), row.names = 1, header = TRUE, sep = ",", stringsAsFactors = FALSE)
mat = as.matrix(mat)

col = c(snv = "red", indel = "blue")

col_hclust = hclust(dist(matrix(rnorm(9), 3)))
row_hclust = hclust(dist(matrix(rnorm(9), 3)))

oncoPrint(mat,
    alter_fun = list(
        snv = function(x, y, w, h) grid.rect(x, y, w*0.9, h*0.9, 
            gp = gpar(fill = col["snv"], col = NA)),
        indel = function(x, y, w, h) grid.rect(x, y, w*0.9, h*0.4, 
            gp = gpar(fill = col["indel"], col = NA))
    ), col = col, cluster_rows = row_hclust, cluster_columns = col_hclust)
```

![image](https://user-images.githubusercontent.com/449218/64919862-58783680-d7b0-11e9-92e9-730ca5758034.png)

**Comment by suraykar** [comment]
Thanks SO much! This is awesome.

Any chance of also adding tool-tips?

Thanks a ton!

**Comment by suraykar** [comment]
Hi @jokergoo, just wanted to see if tooltips was on your list of enhancements. That would seal the deal for me on what is by far the best package for heatmaps out there. Thank you so much!

**Comment by suraykar** [comment]
By tooltip, I meant something like the attached, where you can get more information about the sample/gene or annotation.

![image](https://user-images.githubusercontent.com/55218232/65877506-d5331500-e359-11e9-809f-e74d97812b49.png)

**Comment by jokergoo** [comment]
Ah, that kind of tooltip. Unfortunately, ComplexHeatmap only generates static heatmaps. There is no functionality for hovering above the plot and showing more information. You might need to use other interactive heatmap packages such as heatmaply, d3heatmap, iheatmapr, but I don't know how easy to make oncoPrint with them.

**Comment by suraykar** [comment]
Thank you!
