### ISSUE TITLE
Adding a graphic without affecting the final clustering

### ISSUE THREAD

**Issue by nfarnoud** [jokergoo/ComplexHeatmap#363]
Hello, 

I would like to add a **dot** to Oncoprint body for cases where a GENE has more than one mutation in the sample. I tried using a similar approach as in the example below by adding a rule to  **alter_fun** for cases that were tagged as "multis". However, I noticed that it does in fact affect the clustering, which I don't want to (I only am interested to add a feature to the visualization). 

Let me explain it by following an example in Section 7.1.4 in  [https://jokergoo.github.io/ComplexHeatmap-reference/book/oncoprint.html](https://jokergoo.github.io/ComplexHeatmap-reference/book/oncoprint.html)

```
set.seed(123)
x1 = sample(c("", "snv"), 100, replace = TRUE, prob = c(8, 2))
x2 = sample(c("", "indel"), 100, replace = TRUE, prob = c(8, 2))
x2[x1 == "snv"] = ""
x3 = sample(c("", "intronic"), 100, replace = TRUE, prob = c(5, 5))
x4 = sample(c("", "exonic"), 100, replace = TRUE, prob = c(5, 5))
x3[x1 == "" & x2 == ""] = ""
x4[x1 == "" & x2 == ""] = ""
x4[x3 == "intronic"] = ""
x = apply(cbind(x1, x2, x3, x4), 1, function(x) {
    x = x[x != ""]
    paste(x, collapse = ";")
})
m = matrix(x, nrow = 10, ncol = 10, dimnames = list(paste0("g", 1:10), paste0("s", 1:10)))
m[1:4, 1:4]
```
defining alter_fun:
```
alter_fun = list(
    background = function(x, y, w, h) 
        grid.rect(x, y, w*0.9, h*0.9, gp = gpar(fill = "#CCCCCC", col = NA)),
    # red rectangles
    snv = function(x, y, w, h) 
        grid.rect(x, y, w*0.9, h*0.9, gp = gpar(fill = "red", col = NA)),
    # blue rectangles
    indel = function(x, y, w, h) 
        grid.rect(x, y, w*0.9, h*0.9, gp = gpar(fill = "blue", col = NA)),
    # dots
    intronic = function(x, y, w, h) 
        grid.points(x, y, pch = 16),
    # crossed lines
    exonic = function(x, y, w, h) {
        grid.segments(x - w*0.4, y - h*0.4, x + w*0.4, y + h*0.4, gp = gpar(lwd = 2))
        grid.segments(x + w*0.4, y - h*0.4, x - w*0.4, y + h*0.4, gp = gpar(lwd = 2))
    }
)

```
drawing the oncoprint: 
```
ht = oncoPrint(m, alter_fun = alter_fun, col = c(snv = "red", indel = "blue"))
draw(ht, heatmap_legend_list = list(
    Legend(labels = c("intronic", "exonic"), type = "points", pch = c(16, 28))
))
```

Now, let's see assume I just added exonic and intronic as added info, and did not have that in the first place: 

```
m = gsub(";intronic","",m)
m = gsub(";exonic","",m)

alter_fun = list(
  background = function(x, y, w, h) 
    grid.rect(x, y, w*0.9, h*0.9, gp = gpar(fill = "#CCCCCC", col = NA)),
  # red rectangles
  snv = function(x, y, w, h) 
    grid.rect(x, y, w*0.9, h*0.9, gp = gpar(fill = "red", col = NA)),
  # blue rectangles
  indel = function(x, y, w, h) 
    grid.rect(x, y, w*0.9, h*0.9, gp = gpar(fill = "blue", col = NA))
)
jpeg("./Figure2.jpg")
ht = oncoPrint(m, alter_fun = alter_fun, col = c(snv = "red", indel = "blue"))
draw(ht)
dev.off()
```
As you can see these are 2 results in completely different clustering results, which completely makes sense since it is using exonic/intronic as variants types in the first example. But that's not what I want. I tried to add dots as **cell_fun** but Oncoprint does not accept that feature. 

Can you please help me with a way to include graphics without affecting the clustering?

Many Thanks,
Noushin

![Figure1](https://user-images.githubusercontent.com/29715882/65358373-64f0fa80-dbc7-11e9-8f92-98d0720908d2.jpg)
![Figure2](https://user-images.githubusercontent.com/29715882/65358741-5c4cf400-dbc8-11e9-95ff-6f7133ccae3c.jpg)

**Comment by jokergoo** [comment]
I see...

The ordering is different because the first one takes account of four mutation types (snv, indel, intronic and exonic) while the second one only takes account of two mutation types.

A quick fix is if you can obtain the row orders and column orders in advance, then you can set them
to `row_order` and `column_order` arguments to precisely control them. For this oncoprint problem, you can first make an oncoprint with only snv and indel:

```r
pdf(NULL)
ht = oncoPrint(m2, ...) # let call it m2 which only contains snv and indel
ht = draw(ht)
dev.off()

ro = row_order(ht)
co = column_order(ht)
```

and then use `ro` and `co` in the oncoprint with four mutation types:

```r
oncoPrint(m4, ..., row_order = ro, column_order = co)
```
