### ISSUE TITLE
Greek symbols in legend?

### ISSUE THREAD

**Issue by emccarthy23** [jokergoo/ComplexHeatmap#364]
It is possible to plot greek symbols in a legend (in general but showing a specific example with a row annotation legend)? Using expression() doesn't seem to work:

```
library(ComplexHeatmap)
mat = matrix(rnorm(100), 2)
rownames(mat) = c("Row1", "Row2")
ha = rowAnnotation(
  label = c(expression(alpha), expression(beta)),
  col = list(label = c(expression(alpha) = "grey", expression(beta) = "black")))
Heatmap(mat, right_annotation = ha)

Error: unexpected '=' in:
"  label = c(expression(alpha), expression(beta)),
  col = list(label = c(expression(alpha) ="
```

**Comment by jokergoo** [comment]
First, please update the package from GitHub:

```r
devtools::install_github("jokergoo/ComplexHeatmap")
```

and run the following example:

```r
mat = matrix(rnorm(100), 10)
ha = rowAnnotation(label = rep(c("a", "b"), each = 5),
    annotation_legend_param = list(label = 
        list(at = c("a", "b"), 
             labels = c(expression(alpha, beta)))))
Heatmap(mat, right_annotatio = ha)
```

![image](https://user-images.githubusercontent.com/449218/65580439-e7880a00-df79-11e9-8d5e-a47510cb37ff.png)

**Comment by matushiq** [comment]
Would it be possible to do this for grid.text() within the cell_fun function?
I would like to add Greek symbols into the squares
![image](https://user-images.githubusercontent.com/1014580/65958891-ce3afe00-e450-11e9-8b38-f81b517bab4f.png)
Thank you!

**Comment by matushiq** [comment]
Actually, it works.
If combined with text, just whole variable needs to be passed as an expression:
expression(paste("**", ",", psi)) works.

**Comment by jokergoo** [comment]
Yes, `grid.text()` supports math expression natively.
