### ISSUE TITLE
Exporting Oncoprint plot as pdf

### ISSUE THREAD

**Issue by bynjh007** [jokergoo/ComplexHeatmap#365]
Hi,
I am really enjoying the complexheatmap / oncoprint for my research. Thanks!

For OncoPrint, if I export the figure as pdf format and open it with illustrator, the main heatmap is not editable (not editable type). How can I edit the main body of the plot?

Thanks!

**Comment by jokergoo** [comment]
I don't have experience with Illustrator, but I tested it with Inkscape, and it is editable.
