### ISSUE TITLE
 'cluster_column_slices = FALSE' does not work?

### ISSUE THREAD

**Issue by micecanfly** [jokergoo/ComplexHeatmap#369]
I do splitting by both columns and the rows, or by either of them. Despite having `cluster_row_slices = FALSE ` and ` cluster_column_slices = FALSE`, I still get both slices of columns and slices of rows reordered. Can that be helped? Below is the command for a split heatmap where I do not want to rearrange the slices of columns 
```
Heatmap(z_dheat, 
            cluster_columns=FALSE, 
            show_row_dend = FALSE, 
            show_row_names = TRUE, 
            show_column_names = FALSE,
            column_split=samples$Group,
            cluster_column_slices = FALSE,
            top_annotation = colAnn,
            column_title = "Exp1", col=col_fun)
```

If I do not do splitting, the columns are in correct order (see below)

```
Heatmap(z_dheat, 
        cluster_columns=FALSE, 
        show_row_dend = FALSE, 
        show_row_names = TRUE, 
        show_column_names = FALSE,
        top_annotation = colAnn,
        column_title = "Exp1", col=col_fun)
```

**Comment by jokergoo** [comment]
Is `samples$Group` a factor? If it is a factor, the order of column slices is controlled by `levels(samples$Group)`. You can reset the levels to control the slice order.

**Comment by micecanfly** [comment]
thanks! `samples$Group` was a df column from imported .csv. It helped now to specify it as a factor, and to order the levels. Slices of rows are still being reordered despite `cluster_row_slices = FALSE`, and fail to specify it as factors because `row_split` should be equal to the number or rows in a heat map, right? How can I turn off reordering of row slices then? I thought it would be the same as ordering of slices of columns, and therefore I left it out for simplicity in the first question, sorry.

```
#Splitting and ordering of slices
row_split <- sig_results 
samples <- read.csv('samples.csv') 
samples$Group <- factor(samples$Group, levels(samples$Group)[c(2,1,4,3)])
```
`row_split$class` looks like the following `"Inter" "Inter" "Inter" "Inter" "Gene" "Gene" "Gene" "Type" "Type" "Type" ` , and row slices seem to by adjusted in alphabet order

```
Heatmap(z_dheat, 
        cluster_columns=FALSE, 
        show_row_dend = FALSE, 
        border=TRUE, 
        name = "z-score", 
        show_row_names = TRUE, 
        show_column_names = FALSE,
        row_labels = dheat[rownames(dheat),2],
        split=row_split$class, 
        column_split=samples$Group,
        cluster_row_slices = FALSE,
        cluster_column_slices = FALSE,
        top_annotation = colAnn,
        column_title = "Exp", col=col_fun)
```

PS Absolutely amazing tool and documentation, thank you SO much!
