### ISSUE TITLE
How to manually change the column annotation color under anno_block

### ISSUE THREAD

**Issue by gundalav** [jokergoo/ComplexHeatmap#370]
I have the following code  to make the heatmap:

    library(ComplexHeatmap)
    
    nof_elem <- 4
    
    set.seed(123)
    mat <- matrix(rnorm(nof_elem * nof_elem), nof_elem)
    rownames(mat) <- paste0("R", 1:nof_elem)
    colnames(mat) <- paste0("C", 1:nof_elem)
    mat
    
    
    
    column_ha <- HeatmapAnnotation(cluster = anno_block(
      gp = gpar(fill = 2:15),
      labels = c("group1", "group2", "group3"),
      labels_gp = gpar(col = "white", fontsize = 10),

      # Tried this but didn't work
      # col = list(cluster = c("group1" = "red", "group2" = "blue", "group3" = "black"))
    ))
    
    Heatmap(mat,
      cluster_columns = FALSE,
      cluster_rows = FALSE,
      top_annotation = column_ha,
      column_split = c(1, 2, 2, 3),
      show_column_names = FALSE
    )

It produces the following figure:

[![enter image description here][3]][3]

As shown in the figure above. There are actually two tasks I need to do:

 1. How can I manually change the group block color? (group1 = red; group2 = blue, group3 = black)
 2. How can I remove the number at the very top?

  [1]: https://github.com/jokergoo/ComplexHeatmap
  [2]: https://jokergoo.github.io/ComplexHeatmap-reference/book/introduction.html#general-design
  [3]: https://i.stack.imgur.com/d0r8K.jpg

**Comment by jokergoo** [comment]
```r

column_ha <- HeatmapAnnotation(cluster = anno_block(
  gp = gpar(fill = c("black", "grey", "yellow")), # <- here controls the filled color
  labels = c("group1", "group2", "group3"),
  labels_gp = gpar(col = "white", fontsize = 10),
))

Heatmap(mat,
  cluster_columns = FALSE,
  cluster_rows = FALSE,
  top_annotation = column_ha,
  column_split = c(1, 2, 2, 3),
  column_title = NULL,  # <- this removed 1, 2, 3
  show_column_names = FALSE
)
```

![image](https://user-images.githubusercontent.com/449218/66396214-8fb9bc00-e9d9-11e9-8af0-fc9e4aa20b49.png)

**Comment by crazyhottommy** [comment]
Hi @jokergoo 

gp = gpar(fill = c("black", "grey", "yellow")
is the color mapped to the factor level of column_split = c(1, 2, 2, 3) ?

if I have column_split = c("a", "c", "c", "b")
I will need to relevel it as  column_split = factor(("a", "c", "c", "b"), levels = c("a", "c", "b") ?
Thanks!

**Comment by crazyhottommy** [comment]
it seems the block color is always the same order as c("black", "grey", "yellow") even if I apply column clustering.

**Comment by jokergoo** [comment]
Good point... I will think about it.

Current design is `anno_block()` has nothing to do with the levels in the heatmap. It always corresponds to the order of what you see in the heatmap.
