### ISSUE TITLE
Coerce HeatmapList object to gtable/TableGrob class?

### ISSUE THREAD

**Issue by slagtermaarten** [jokergoo/ComplexHeatmap#372]
Hi,
Is this possible? 
Many thanks, Maarten

**Comment by jokergoo** [comment]
Yes, since ComplexHeatmap is implemented by `grid` graphic system, you can use `grid.grabExpr()` to wrap the output as a `grob` object:

```r
gb = grid.grabExpr({
    ht_list = Heatmap(...) + Heatmap(...) + ...
    draw(ht_list)
})
```

then you can use `gb` in gtable.

**Comment by slagtermaarten** [comment]
Awesome, many thanks!
