### ISSUE TITLE
NA in oncoPlot

### ISSUE THREAD

**Issue by romagnolid** [jokergoo/ComplexHeatmap#373]
Hi @jokergoo, first of all thanks for this amazing tool.
I've had some difficulties in using NA with oncoPrint. It seems that by default it doesn't accept NA values.
So I tried to circumvent the issue by changing all NA cells of my matrix to character "NA". 
The problem is that the function seems to ignore both "NA" and "na".
Not a big problem, after I realized the issue I just used "N/A" but I would suggest to add a warning in the tutorial.

**Comment by jokergoo** [comment]
`NA` is automatically removed by `oncoPrint()` function (as well as the string `'NA'` or `'na'`). For your case `"N/A"` is a normal string and `oncoPrint()` treat it as a code for a mutation type (maybe it means `neutral/amplification`?).

In current version (>= 2.0.0), there will be an error if you have `N/A` in your matrix:

```
> oncoPrint(mat,
+     alter_fun = list(
+         snv = function(x, y, w, h) grid.rect(x, y, w*0.9, h*0.9, 
+             gp = gpar(fill = col["snv"], col = NA)),
+         indel = function(x, y, w, h) grid.rect(x, y, w*0.9, h*0.4, 
+             gp = gpar(fill = col["indel"], col = NA))
+     ), col = col)
All mutation types: snv, indel, N/A
Error: You should define graphic function for: N/A
```

You can replace all `"N/A"` to `""`, or you can define a `get_type_fun` as:

```r
get_type_fun = function(x) {
	x = strsplit(x, "\\s*[;:,|]\\s*")[[1]]
	x[!x %in% c("na", "NA", "N/A", "n/a")]
}
```

and assign to the `get_type` argument:

```r
oncoPrint(mat, get_type = get_type_fun, ...)
```

**Comment by romagnolid** [comment]
But if I define the function for "N/A" it works.
```
> oncoPrint(mat,
+     alter_fun = list(
+         "N/A" = function(x, y, w, h) grid.rect(x, y, w*0.9, h*0.9, 
+             gp = gpar(fill = col["N/A"], col = NA)),
+         snv = function(x, y, w, h) grid.rect(x, y, w*0.9, h*0.8, 
+             gp = gpar(fill = col["snv"], col = NA)),
+         indel = function(x, y, w, h) grid.rect(x, y, w*0.9, h*0.4, 
+             gp = gpar(fill = col["indel"], col = NA))
+     ), col = col)
```
I wanted to distinguish NA from "" because I would associate the empty string with a wild-type gene but I may have no information about a gene in a given sample.

**Comment by jokergoo** [comment]
Then, as you did, `N/A` has special meaning and you need to define a graphic for that.

**Comment by romagnolid** [comment]
Right, but when I used the strings "NA" and "na" (which have no special meaning in R, contrary to `NA`)
`oncoPrint` just ignored them without errors or warnings and it took me some time to figure out the problem. That's why I would suggest to specify that neither "NA" nor "na" would work.

**Comment by jokergoo** [comment]
Ah, I see, now I get your point. I will add warnings if there is na in the matrix. Thanks!

**Comment by romagnolid** [comment]
Great, thank you!

**Comment by romagnolid** [comment]
#374
