### ISSUE TITLE
"anno_block" is not found

### ISSUE THREAD

**Issue by dhwani2410** [jokergoo/ComplexHeatmap#377]
library(ComplexHeatmap)
Loading required package: grid

ComplexHeatmap version 1.20.0
Bioconductor page: http://bioconductor.org/packages/ComplexHeatmap/
Github page: https://github.com/jokergoo/ComplexHeatmap
Documentation: http://bioconductor.org/packages/ComplexHeatmap/

If you use it in published research, please cite:
Gu, Z. Complex heatmaps reveal patterns and correlations in multidimensional 
  genomic data. Bioinformatics 2016.

Warning message:
package ‘ComplexHeatmap’ was built under R version 3.5.1 

```
ha = HeatmapAnnotation(anno_block(gp = gpar(fill = 2:8),
+                                     labels = paste0("LA",1:7), 
+                                     labels_gp = gpar(col = "white", fontsize = 10)))

Error in anno_block(gp = gpar(fill = 2:8), labels = paste0("LA", 1:7),  : 
  could not find function "anno_block"
```
I have loaded complex heat map package still it is saying "anno_block" not found.

**Comment by jokergoo** [comment]
You need to use version >= 2.0.0

**Comment by agammage** [comment]
I've had the same issue, but cannot install a version of ComplexHeatmap >=2.0.0. 
For some reason upon installing, the BiocManager defaults to installing ComplexHeatmap v1.2.0 despite this not being the current version (and using previous BiocManager versions does not help). I am currently running BiocManager v1.30.16, R v3.5.1 and Mac OS Mojave, all of which *should* be compatible. Is there something I'm missing?
