### ISSUE TITLE
UpSet gives incorrect groups with matrix input for intersect and union mode 

### ISSUE THREAD

**Issue by DennisGoldfarb** [jokergoo/ComplexHeatmap#382]
Hi, 

It seems that make_comb_mat gives different output if the input is in a list format vs matrix. The results appear incorrect when using matrix mode. Here is a simple example to illustrate the issue. 

list_to_matrix gives the correct result:

```
library(ComplexHeatmap)

m.list <- list(set1 = c("a","b"), set2 = c("a"), set3 = c("c"))
m.matrix <- list_to_matrix(m.list)

print(m.list)
$set1
[1] "a" "b"

$set2
[1] "a"

$set3
[1] "c"

print(m.matrix)
  set1 set2 set3
a    1    1    0
b    1    0    0
c    0    0    1

```

The UpSet plot in distinct mode is identical for both inputs:

```
m.list.distinct = make_comb_mat(m.list, mode = "distinct", remove_empty_comb_set = F)
UpSet(m.list.distinct, set_order = c(1,2,3), row_title = "list distinct")
```

![list_distinct](https://user-images.githubusercontent.com/8868522/67582131-c8160580-f70e-11e9-9b62-89f83e115576.png)

```
m.matrix.distinct = make_comb_mat(m.matrix, mode = "distinct", remove_empty_comb_set = F)
UpSet(m.matrix.distinct, set_order = c(1,2,3), row_title = "matrix distinct")
```

![matrix_distinct](https://user-images.githubusercontent.com/8868522/67582137-cb10f600-f70e-11e9-9c33-2f57636f63e4.png)

However it gives different results for intersect and union. The results look correct for the list input:

```
m.list.intersect = make_comb_mat(m.list, mode = "intersect", remove_empty_comb_set = F)
UpSet(m.list.intersect, set_order = c(1,2,3), row_title = "list intersect")
```

![list_intersect](https://user-images.githubusercontent.com/8868522/67582141-cd735000-f70e-11e9-82e0-1c72242964be.png)

```
m.matrix.intersect = make_comb_mat(m.matrix, mode = "intersect", remove_empty_comb_set = F)
UpSet(m.matrix.intersect, set_order = c(1,2,3), row_title = "matrix intersect")
```

![matrix_intersect](https://user-images.githubusercontent.com/8868522/67582151-d19f6d80-f70e-11e9-8380-b8407a719691.png)

```
m.list.union = make_comb_mat(m.list, mode = "union", remove_empty_comb_set = F)
UpSet(m.list.union, set_order = c(1,2,3), row_title = "list union")
```

![list_union](https://user-images.githubusercontent.com/8868522/67582162-d49a5e00-f70e-11e9-9697-9e6efb006d80.png)

```
m.matrix.union = make_comb_mat(m.matrix, mode = "union", remove_empty_comb_set = F)
UpSet(m.matrix.union, set_order = c(1,2,3), row_title = "matrix union")
```

![matrix_union](https://user-images.githubusercontent.com/8868522/67582167-d7954e80-f70e-11e9-8ac5-b20c3f63559b.png)

**Comment by jokergoo** [comment]
Yes, that might be a bug, because I mainly test under the "distinct" mode.

Current implementation of UpSet is slow and memory inefficient. I am extensively improving the code and will fix this bug as well.

**Comment by jokergoo** [comment]
Hi, just an update. I have fixed this bug and now the "intersect" and "union" modes are correctly calculated.

```
> m.list <- list(set1 = c("a","b"), set2 = c("a"), set3 = c("c"))
> m.matrix <- list_to_matrix(m.list)
> 
> 
> cm1 = make_comb_mat(m.list, mode = "distinct")
> cm2 = make_comb_mat(m.matrix, mode = "distinct")
> comb_size(cm1)
001 100 110 
  1   1   1 
> identical(comb_size(cm1), 
+           comb_size(cm2))
[1] TRUE
> 
> 
> cm1 = make_comb_mat(m.list, mode = "intersect")
> cm2 = make_comb_mat(m.matrix, mode = "intersect")
> comb_size(cm1)
001 010 100 110 
  1   1   2   1 
> identical(comb_size(cm1), 
+           comb_size(cm2))
[1] TRUE
> 
> cm1 = make_comb_mat(m.list, mode = "union")
> cm2 = make_comb_mat(m.matrix, mode = "union")
> comb_size(cm1)
001 010 011 100 101 110 111 
  1   1   2   2   3   2   3 
> identical(comb_size(cm1), 
+           comb_size(cm2))
[1] TRUE
```
