### ISSUE TITLE
Merging OTU table and metadata files resulted in conversion of numbers into NA 

### ISSUE THREAD

**Issue by emankhalaf** [jokergoo/ComplexHeatmap#384]
Hi all,
I try to generate a heatmap displayed by metadata info using the steps in this link (https://www.r-bloggers.com/from-otu-table-to-heatmap/). When I merged metadata and OTU table data. frames the resultant table contained NA  values instead of OTU reads/relative abundance values. I extracted the relative abundance of top50 OTUs displayed by sample_ID. So, I have an OTU table (50 rows by 42 samples). Then I already have the metadata file 42 samples by 7 variables. I saved both files as CSV file, then uploaded in R. I transposed the OTU table, so rows in OTU table and metadata are matching by sample_ID. I merged both tables by row.names, but I found numbers were displayed in the merged table as NA.  

```{r}
library(RColorBrewer)
library(gplots)
library(vegan)
```

#import files
```{r}
dat1 <- read.csv("taxonomy.csv", header=TRUE,row.names=1, sep=",") 
meta <- read.csv("meta.csv", header=TRUE,row.names=1, sep=",")
```

```{r}
str(dat1)
```

'data.frame':	50 obs. of  42 variables:
 $ X16T1 : num  0 0 0 0 0.00174 ...
 $ X16T10: num  0 0 0 0 0 0 0 0 0 0 ...
 $ X16T13: num  0.00124 0 0.04363 0 0 ...
 $ X16T14: num  0 0 0.03 0 0 0 0 0 0 0 ...
 $ X16T16: num  0 0.01054 0.00609 0.03121 0.00658 ...

```{r}
dat2 <- as.data.frame(dat1)
```

```{r}
meta1 <- as.data.frame(meta)
```

```{r}
meta1$Year <- as.factor(meta1$Year)
```

```{r}
dat3 <- t(dat2)
```

```{r}
merge <- merge(meta1, dat3, by="row.names", all.x = TRUE)
```

```{r}
dim(meta1)
```
[1] 42  7

```{r}
dim(dat3)
```
[1] 42 50

```{r}
dim(merge)
```

[1] 42 58

So, when I proceeded to make a heatmap using the following code:

```{r}
OTUcol1<-ncol(meta1)+2
```

```{r}
OTUcol2<-ncol(merge)
```

```{r}
justOTU<-merge[,OTUcol1:OTUcol2]
justOTU[1:5,1:5]
rownames(justOTU[1:10,])
rownames(justOTU)<-merge$Row.names
rownames(justOTU[1:10,])
justOTU2<-as.matrix(t(justOTU))
justOTU2[1:5,1:5]
```

#Heatmap
```{r}
heatmap.2(justOTU2,Rowv=TRUE, Colv=FALSE, scale="column", trace="none", col=redgreen, xlab="Sample", ylab="OTUs", margins=c(10,15))
```

So, as the merged table cOntains NA values the code eventually returned an error 
(Error in hclustfun(distr) : NA/NaN/Inf in foreign function call (arg 11)2.hclustfun(distr) 1.heatmap.2(justOTU2, Rowv = TRUE, Colv = FALSE, scale = "column", trace = "none", col = redgreen, xlab = "Sample", ylab = "OTUs", margins = c(10, 15)). 
I do not know what is wrong in my code?

**Comment by jokergoo** [comment]
Hi, I think the package you refer to is `heatmap.2()` from **gplots** package.

**Comment by emankhalaf** [comment]
Yes, it is!
