### ISSUE TITLE
Customize cells size and shape

### ISSUE THREAD

**Issue by dvespasiani** [jokergoo/ComplexHeatmap#385]
Hi, 
Is it possible to change the cell grid shape into dots of variable sizes depending on a vector of values?

I have a matrix of proportion of SNPs across multiple categories but I would like to adjust the size of the cell based on the actual number of SNPs I have for each corresponding cell.

Thank you so much for your help
Davide

**Comment by jokergoo** [comment]
You cannot change the cell size, but you can change the size of the rectangles that are drawn in the cells. See the following examples:

```r
plot_grid(group1, group2, group3, group4, nrow = 2, ncol = 2)


m = matrix(runif(100), 10)

Heatmap(m, rect_gp = gpar(type = "none"),
    cell_fun = function(j, i, x, y, w, h, fill) {
        p = m[i, j]
        grid.rect(x, y, width = p*w, height = p*h)
    })
```

![image](https://user-images.githubusercontent.com/449218/67671400-2b55a100-f976-11e9-90b6-6bb1418b35ad.png)
