### ISSUE TITLE
Feature request: Add support for titles (and subtitles?) in upsetplots

### ISSUE THREAD

**Issue by endrebak** [jokergoo/ComplexHeatmap#388]
This is something the original upsetplot package is missing.

**Comment by jokergoo** [comment]
Title is supported by setting `column_title` or `row_title`:

```r
set.seed(123)
lt = list(a = sample(letters, 5),
          b = sample(letters, 10),
          c = sample(letters, 15))
m1 = make_comb_mat(lt)
UpSet(m1, row_title = "row title", column_title = "column title")
```

![image](https://user-images.githubusercontent.com/449218/68120224-0ed0e000-ff05-11e9-8485-24997ca864be.png)
