### ISSUE TITLE
Feature request: add title to annotion group

### ISSUE THREAD

**Issue by ccwang002** [jokergoo/ComplexHeatmap#390]
I was wondering how to add title to annotation group. My case is I'd like to plot CNV and gene expression of a few genes, but i want to show the CNV and expression side by side per gene. 

For example, I made a toy example of two genes and 10 samples:
![current_output](https://user-images.githubusercontent.com/1544283/67964095-ae246900-fbcd-11e9-8154-18c181e71c00.png)

I'd like to add the gene name on the left, like the following:
![desired_output](https://user-images.githubusercontent.com/1544283/67964313-12472d00-fbce-11e9-8e56-6c9cdf6e9007.png)

I tried a few decorate functions but they don't seem to work because there isn't any 'real' heatmap here. What's the best way to add the gene names (or title) to the each `HeatmapAnnotation` here?

Thanks!

```
library(tidyverse)
library(ComplexHeatmap)

# Generate data for 2 genes x 10 samples
set.seed(201911)
samples = str_c('S', sample(LETTERS[1:10]))
genes = c('GX', 'GY') %>% set_names()
cnv = genes %>% map(~ set_names(rnorm(length(samples), sd = 2), samples)) 
rna = genes %>% map(~ set_names(rnorm(length(samples), sd = 1)), samples)

# Make column annotation
col_fun = circlize::colorRamp2(c(-2, 0, 2), c('blue', 'gray90', 'red'))
col_ha_per_gene = genes %>% map(function(gene) {
    columnAnnotation(
        cnv = cnv[[gene]],
        rna = rna[[gene]],
        name = gene,
        col = list(rna = col_fun, cnv = col_fun)
    )
})

# Create an empty heatmap to show row names
ht_empty = Heatmap(
    matrix(NA_integer_, nrow = 0, ncol = length(samples), 
           dimnames = list(NULL, samples)), 
    name = 'empty',
    cluster_columns = FALSE,
    cluster_rows = FALSE
)

draw(
    col_ha_per_gene$GX %v% col_ha_per_gene$GY %v% ht_empty,
    ht_gap = unit(5, 'mm'),
    padding = unit(c(2, 20, 2, 2), "mm")
)
```

**Comment by jokergoo** [comment]
Supporting titles for annotations is a little bit difficult for the current implement of the package. I usually use `decoration_annotation()` to add text outsize the annotation region as titles. See example in https://jokergoo.github.io/ComplexHeatmap-reference/book/other-high-level-plots.html#stacked-summary-plot

**Comment by ccwang002** [comment]
Thanks for your reply!  My problem is that because heatmaps here are all empty without any slices, `decorate_heatmap_body()` will fail:

```
> list_components()
 [1] "ROOT"                       "global"                    
 [3] "global_layout"              "global-heatmaplist"        
 [5] "main_heatmap_list"          "heatmap_GX"                
 [7] "annotation_cnv_1"           "annotation_rna_1"          
 [9] "heatmap_GY"                 "annotation_cnv_1"          
[11] "annotation_rna_1"           "heatmap_empty"             
[13] "empty_column_names_1"       "global-heamap_legend_right"
[15] "heatmap_legend"
> decorate_heatmap_body('GX', {grid.text('GX', x = unit(0, 'npc'), y = unit(0.5, 'npc'))})
Error in grid.Call.graphics(C_downviewport, name$name, strict) : 
  Viewport 'GX_heatmap_body_1_1' was not found
```

However, by reading how you implement the `decorate_*` functions, I was able to get the corresponding viewports and decorate the heatmaps:

```
ht_list = draw(
    col_ha_per_gene$GX %v% col_ha_per_gene$GY %v% ht_empty,
    ht_gap = unit(5, 'mm'),
    padding = unit(c(2, 20, 2, 2), "mm")
)
current_vp = "global"
seekViewport('heatmap_GX')
grid.text('GX', x = unit(0, 'npc') - unit(2, 'mm'), y = unit(0.5, 'npc'), hjust = 1)
seekViewport('heatmap_GY')
grid.text('GY', x = unit(0, 'npc') - unit(2, 'mm'), y = unit(0.5, 'npc'), hjust = 1)
seekViewport(current_vp)
```

![0000a7](https://user-images.githubusercontent.com/1544283/68149907-4ee39300-ff04-11e9-96fe-5eedad30143d.png)

I think the solution to my question is more about getting familiar with grid graphics. Thanks for making this great tool!
