### ISSUE TITLE
One legend for a list of heatmaps

### ISSUE THREAD

**Issue by underbais** [jokergoo/ComplexHeatmap#391]
Hello,

I have a list of heatmaps but all values in them are in range of 0-1. How do I make just one legend for all heatmaps in the list? Default is showing separate legend for each heatmap in the list.

Any advice?
Thanks

**Comment by jokergoo** [comment]
From the second heatmap, set `show_heatmap_legend = FALSE` in `Heatmap()` function.

**Comment by underbais** [comment]
The thing is I have 15 heatmaps in the list and I'd like to make them all the same scale with a single legend. Now they all have their own legends with different ranges of values. Is it possible to put them in the same range with one shared legend? Thanks in advance

**Comment by jokergoo** [comment]
Yes, you set a color mapping function and assign to all heatmaps:

```r
col_fun = colorRamp2(...)
Heatmap(mat1, col = col_fun, ...) +
Heatmap(mat2, col = col_fun, show_heatmap_legend = FALSE, ...) +
Heatmap(mat3, col = col_fun, show_heatmap_legend = FALSE, ...) +
...
```

**Comment by underbais** [comment]
Nice, it works. Thanks a lot!
