### ISSUE TITLE
Extract legends from heatmap?

### ISSUE THREAD

**Issue by slagtermaarten** [jokergoo/ComplexHeatmap#393]
Hi,
Is it possible to extract the automatically generated legends from a heatmap so I don't have to remake them? I'm asking because I'd like to add two legends to a heatmap that already has ten legends and would like to coordinate the placement of all 12 legends.
Many thanks,
Maarten

**Comment by jokergoo** [comment]
You can manually generate the legend by `Legend()` function, or extract it as:

```r
m = matrix(rnorm(100), 10)
library(ComplexHeatmap)
ht = Heatmap(m)
ht = draw(ht)
foo = color_mapping_legend(ht@ht_list[[1]]@matrix_color_mapping, plot = FALSE)
foo
```
