### ISSUE TITLE
Cotrol distance between heatmap and legend

### ISSUE THREAD

**Issue by tiagochst** [jokergoo/ComplexHeatmap#394]
Hello,

Please, is there any way to add a gap between the heatmap and the legend. 
I am adding decoration text to th rows and the legend is overlapping. I wish to leave 1cm between legend and heatmap.

Thanks!

**Comment by jokergoo** [comment]
I have added two options `HEATMAP_LEGEND_PADDING` and `ANNOTATION_LEGEND_PADDING` in `ht_opt`. See following example:

```r
ht_opt$HEATMAP_LEGEND_PADDING = unit(1, "cm")
ht_opt$ANNOTATION_LEGEND_PADDING = unit(1, "cm")
Heatmap(matrix(rnorm(100), 10), top_annotation = HeatmapAnnotation(foo = 1:10))
```

Please update from GitHub.

![image](https://user-images.githubusercontent.com/449218/68526309-a1dd9180-02da-11ea-9bbf-436a3d66e405.png)

**Comment by tiagochst** [comment]
Thanks! It worked perfectly.
And many thanks for making ComplexHeatmap, it is an amazing tool. You should be very proud of it.

**Comment by tiagochst** [comment]
Another question, row can I control the vertical gap between legends using `HeatmapAnnotation`

I saw you can do it with this code:
`pd = packLegend(lgd1, lgd2, lgd3, lgd1, lgd2, lgd3, max_width = unit(10, "cm"), 
    direction = "horizontal", column_gap = unit(5, "mm"), row_gap = unit(1, "cm"))`

**Comment by Tina9** [comment]
Hi, 

I just use command line as follows, but it doesn't work.
```R
ht_opt(HEATMAP_LEGEND_PADDING = unit(8, "cm"), ADD = T)
ht_opt(ANNOTATION_LEGEND_PADDING = unit(3, "cm"), ADD = T)
Heatmap(matrix(rnorm(100), 10), top_annotation = HeatmapAnnotation(foo = 1:10))
```

If I use the command line you provided, it will report error:
`Error: No such option: 'HEATMAP_LEGEND_PADDING'. If you want to add this
new option, please use your_opt_fun(HEATMAP_LEGEND_PADDING = ...,
ADD = TRUE)`.

So what happened?

**Comment by jokergoo** [comment]
Currently it is not easy. I need to make big changes with the code, but I will put it in my to-do list.

**Comment by jokergoo** [comment]
#387

**Comment by tiagochst** [comment]
If it requires a big change of the code, I don’t believe you should do it. It is not worthy it. I thought it could be easy. Please close #387

**Comment by tiagochst** [comment]
And many thanks for the effort on complexheatmap!! It is an amazing package.

**Comment by jokergoo** [comment]
Hi, just an update. Following is how you can control the space between legends:

you can also set it globally:

```r
m = matrix(rnorm(100), 10)
ht_opt$legend_gap = unit(1, "cm")
ht_list = Heatmap(m) + Heatmap(m)
ht_list
```

or set it temporally:

```r
ht_opt(RESET = TRUE)
draw(ht_list, legend_gap = unit(1, "cm"))
```

![image](https://user-images.githubusercontent.com/449218/77247978-534fe480-6c36-11ea-9307-cc1ffcdddee4.png)
