### ISSUE TITLE
Programmatically set colors for column annotations

### ISSUE THREAD

**Issue by federicomarini** [jokergoo/ComplexHeatmap#397]
Hello, 

I was wondering if it is possible to have the possibility to programmatically set colors for column annotations, _in a case where it is not known what the columns of interest would be_.

Use case for this would be a function that wraps the call of Heatmap in a way where the user simply selects the `colData` covariate of interest, and then Heatmap handles these "sensibly enough".

I know it is possible to pass the data frame directly, but I was checking whether it is possible to have the output reproducible (apart from setting the seed), and at best, with a set of palettes that could handle nicely most cases.

If you need a MRE for showcasing this, I can try to put it together - it is tightly related to a package I am currently developing, https://github.com/federicomarini/GeneTonic (the function would be `gs_heatmap` in there).

I would appreciate any feedback on this! Thanks again for the care you put in writing your packages!
Federico

**Comment by jokergoo** [comment]
The thing I can think of is you first construct a `HeatmapAnnotation` object with all annotations,e.g.

```r
df = data.frame(a = 1:10, b = 11:20, c = 21:30)
ha = HeatmapAnnotation(df = df, col = list(a = ..., b = ..., c = ...)
```

and you can subset the columns just by:

```
> ha[, "a"]
A HeatmapAnnotation object with 1 annotation
  name: heatmap_annotation_45 
  position: column 
  items: 10 
  width: 1npc 
  height: 5mm 
  this object is subsetable
  3.35373333333333mm extension on the right 

 name   annotation_type color_mapping height
    a continuous vector        random    5mm
> ha[, c("a", "b")]
A HeatmapAnnotation object with 2 annotations
  name: heatmap_annotation_45 
  position: column 
  items: 10 
  width: 1npc 
  height: 10.3514598035146mm 
  this object is subsetable
  3.35373333333333mm extension on the right 

 name   annotation_type color_mapping height
    a continuous vector        random    5mm
    b continuous vector        random    5mm
```

**Comment by federicomarini** [comment]
Hi @jokergoo, in this case the problem is (probably) more complex:
I can not really know in advance what the column names (and how many) will be - the data frame is pretty much depending on what is provided by the user as a `colData`.

I am confident an automated solution is possible, only I can not get there yet :D

**Comment by jokergoo** [comment]
The `colData` provided by users is a data frame. You can directly pass it to the `df` argument of `HeatmapAnnotation()` function. I think the more difficult thing is how users set the colors for their `colData`. Once it is set, you can pass it to `col` argument.

**Comment by federicomarini** [comment]
I'm revamping this as I finally managed to think about it in a cleaner way.
I was not able to parse your latest comment, I'm sorry about that - and then let it slide away.

The way I'd go in this case:
- defining the decoration data frame (via the selection in shiny)
- parsing its columns, one by one
  - if numeric, use the `colorRamp2` in a sensible way (min-mid-max defined based on the values at hand)
  - if character, convert to factor
  - if factor, use a consistent `hcl_rainbow` based on the number of levels
- then I'd combine these things in the `col` list in the format required
- call the `HeatmapAnnotation(df = sample_decoration, col = col_list)`...
- and have that passed to `top_annotation`

Quite convoluted, I have no problem in admitting it.
But it should do what I plan, at least in principle.

Happy to link to the implementation once it is translated into code 😉
