### ISSUE TITLE
old version

### ISSUE THREAD

**Issue by juechenyang** [jokergoo/ComplexHeatmap#398]
Hi,

Thanks for providing this amazing tool. Would you mind to help me install a old version 2.0.0 of this package? Thank you!

**Comment by jokergoo** [comment]
Is there any specific reason that you need to use this lower version?

Following is basically almost 2.0.0

[ComplexHeatmap_1.99.8.tar.gz](https://github.com/jokergoo/ComplexHeatmap/files/3935527/ComplexHeatmap_1.99.8.tar.gz)

**Comment by juechenyang** [comment]
Thanks for your help
