### ISSUE TITLE
Can cluster Tree of columns export to ggtree object?

### ISSUE THREAD

**Issue by pangxueyu233** [jokergoo/ComplexHeatmap#399]
Hi, 
It's an awsome tool to visulize a 'complex heatmap'. Recently, I got in trouble in converting the columns cluster tree into dendrogram/phylo object, and I want to get more information in the tree structure, So can you show me how to achieve it? 
Appreciated your kindness and Working.
Thanks!

**Comment by pangxueyu233** [comment]
Also, I met an another question that, I first cluster the datasets by follwing codes:
`row_dend = as.dendrogram(hclust(parallelDist(as.matrix(t(hvMut_Mut))),method="single"))
row_dend = color_branches(row_dend, k = 5) # `color_branches()` returns a dendrogram object
hc <- hclust(parallelDist(as.matrix(hvMut_Mut)),method="complete")
columns_dend <- as.dendrogram(hc)
columns_dend = color_branches(columns_dend, k = 12) # `color_branches()` returns a dendrogram object
`
and then, I print a heatmap as following :
`

ph <- Heatmap(t(hvMut_Mut),
	cluster_rows = row_dend,
	cluster_columns = columns_dend,
	show_column_names = FALSE,
	show_row_names = TRUE,
	col = col_sel,
	column_title_rot = 90,
	clustering_method_rows = "single",
	clustering_method_column = "complete",
	top_annotation = HeatmapAnnotation(foo = anno_block(gp = gpar(fill = 1:15)))
	 )
ph
`
![image](https://user-images.githubusercontent.com/40414477/69044811-9273ec00-0a30-11ea-98b2-17f58e7dca6c.png)

But I tried use the Heatmap order codes like following:
`
ph <- Heatmap(t(hvMut_Mut),
	cluster_rows = TRUE,
	cluster_columns = TRUE,
	show_column_names = FALSE,
	show_row_names = TRUE,
	col = col_sel,
	column_title_rot = 90,
	clustering_method_rows = "single",
	clustering_method_column = "complete",
	top_annotation = HeatmapAnnotation(foo = anno_block(gp = gpar(fill = 1:15)))
	 )
ph
`
![image](https://user-images.githubusercontent.com/40414477/69044939-cb13c580-0a30-11ea-866d-31b994c4ee2d.png)

the two pictures are different, and I didn't know the reason. Can you show me how to fix it up?

Thanks again !

**Comment by jokergoo** [comment]
The second one applies dendrogram reordering by default (https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#reorder-dendrograms).

The two column clustering are basically identical.
