### ISSUE TITLE
Colorbar

### ISSUE THREAD

**Issue by slowkow** [jokergoo/ComplexHeatmap#4]
Is it possible to plot a colorbar instead of the current legend? For example, using this code?

I suppose there is a way to use `grid.layout` or some other function to accomplish this, but my attempts have been unsuccessful.

```r
# Function to plot color bar
color.bar <- function(lut, min, max=-min, nticks=11, ticks=seq(min, max, len=nticks), title='') {
    scale = (length(lut)-1)/(max-min)
 
    dev.new(width=1.75, height=5)
    plot(c(0,10), c(min,max), type='n', bty='n', xaxt='n', xlab='', yaxt='n', ylab='', main=title)
    axis(2, ticks, las=1)
    for (i in 1:(length(lut)-1)) {
    	y = (i-1)/scale + min
    	rect(0,y,10,y+1/scale, col=lut[i], border=NA)
    }	
}
```

http://www.colbyimaging.com/wiki/statistics/color-bars

**Comment by jokergoo** [comment]
Yes, sure. That's more straightforward for continuous values. I will add this feature in the next version.

**Comment by jokergoo** [comment]
Now from version 1.2.4, continuous color bar is supported for both heatmap legends and annotation legends.

```(r)
library(ComplexHeatmap)
mat = matrix(rnorm(100), 10)
Heatmap(mat, heatmap_legend_color_bar = "continuous")
```

![rplot001](https://cloud.githubusercontent.com/assets/449218/8647581/84603022-2959-11e5-8123-09518228939d.png)
