### ISSUE TITLE
Autofit values in heatmap by adjusting cell/heatmap width

### ISSUE THREAD

**Issue by mknafl** [jokergoo/ComplexHeatmap#408]
I would like to able to use cell_fun to print the values of my cells.  When I try to do what you do at
https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#customize-the-heatmap-body
in section 2.9.1, but skip the font size, I get something unreadable.  If I set the font size it is more readable, but I still can't see individual cell values.  This is partly because I have around 130 columns.  I would like to be able to make one heatmap that is readable with values.  I am also interested on if I can split my heatmap into multiple pieces, by column, but not lose the coloring being determined by the whole row(for the purpose of printing out the charts).  Please let me know if this is possible!  Thanks for such an amazing piece of software!
Mark

**Comment by jokergoo** [comment]
I think you need to calculate the row width (from the matrix values/text) and set the heatmap width manually, e.g.

```r
m = matrix(sample(100000, 10*30), nc = 30)
# each text has 2mm padding on left and right
sum_text_width = function(text, gp = gpar(), padding = unit(0, "mm")) {
	sum(do.call("unit.c", lapply(text, function(t) grobWidth(textGrob(t, gp = gp)) + padding*2)))
}

w = max(do.call("unit.c", apply(m, 1, function(x) {
	sum_text_width(x, padding = unit(2, "mm"))
})))
w = convertWidth(w, "mm")

Heatmap(m, cell_fun = function(j, i, x, y, w, h, fill) {
	grid.text(m[i, j], x, y)
}, heatmap_width = w)
```

![image](https://user-images.githubusercontent.com/449218/72246398-e515f280-35f2-11ea-8917-605b2f492a48.png)


Since now the heatmap width is in absolute unit, you also need to manually set the width of the PDF to properly see the complete plot.
