### ISSUE TITLE
Changing column order of oncoprint

### ISSUE THREAD

**Issue by TnakaNY** [jokergoo/ComplexHeatmap#412]
Hi,
I have some questions about oncoprint function.
In instruction manual, i can reorder column by "column_order = sample_order (user defined list)".

Is it possible to automatically reorder in subgroup define by user?
Let's say we have two distinct tumor group, how can we reorder sample column in each subgroup?

![Oncoprint_sample](https://user-images.githubusercontent.com/40367441/72581994-4964da80-38af-11ea-92d2-6d470a725365.PNG)

**Comment by jokergoo** [comment]
Let's say your subgroups (A and B) are storted in a variable `subgroup`, then you just do similar as `column_order = order(subgroup)`, or you can split your oncoPrint by the subgroups by setting `column_split = subgroup`.
