### ISSUE TITLE
how to change specify font type in the row names?

### ISSUE THREAD

**Issue by rxiangr** [jokergoo/ComplexHeatmap#414]
Hi, there,

How can I change to font type of the row names of the heatmap? say I would like a specific font tpye 'Crimson Text' that is available in my system. 

I have tried row_names_gp = gpar(fontsize = 8,family='Crimson Text'), but it did not seem to make any difference.

many thanks.

**Comment by jokergoo** [comment]
I think the name of the parameter should be `fontfamily`:

```r
Heatmap(m, row_names_gp = gpar(fontfamily = "mono"))
```

![image](https://user-images.githubusercontent.com/449218/73832935-6be07880-4809-11ea-9266-b4f256a91647.png)
