### ISSUE TITLE
Row titles are incorrect when row_split and row_title are used together when cluster_row_slices =T

### ISSUE THREAD

**Issue by mettejoe** [jokergoo/ComplexHeatmap#416]
The below code shows the problem

```r
test_matrix<-matrix(c(rep(20,5),rep(10,5),rep(5,5),rep(0,5)),nrow=4,byrow = T)
annotation<-data.frame(group=c(rep("group1",2),rep("group2",2)), treatment=c("T1","T2","T1","T2"))

#Intiutively the following two lines of code should produce the exact the same plot but they don't 
Heatmap(test_matrix, row_split = annotation, border=T,row_title = "%s,%s" )
Heatmap(test_matrix, row_split = annotation, border=T)
```

It looks like the Heatmap function clusters the row_slices_for_the_data but not for the labels when row_title is used.

When `cluster_row_slices =F` the two pieces of code do produce the same plot :-)

**Comment by jokergoo** [comment]
Yes, that is a bug for `row_title`.

Normally when `row_title` is set NOT as a template, e.g. something like title1, title2, title3, title4, it is assumed the order of `row_title` corresponds to the row slices from top to bottom. But when `row_title` is set as a template, e.g."%s,%s", the order needs to be adjusted according to the clustering of the row slices.

I will fix it soon. Thanks!

**Comment by jokergoo** [comment]
Hi, just an update. I have fixed this bug. Now row titles are in the correct order if they are set as "template":

```r
test_matrix<-matrix(c(rep(20,5),rep(10,5),rep(5,5),rep(0,5)),nrow=4,byrow = T)
annotation<-data.frame(group=c(rep("group1",2),rep("group2",2)), treatment=c("T1","T2","T1","T2"))

rownames(test_matrix) = paste(annotation[, 1], annotation[, 2], sep = ",")

#Intiutively the following two lines of code should produce the exact the same plot but they don't 
ht1 = Heatmap(test_matrix, row_split = annotation, border=T,row_title = "%s,%s", column_title = "set `row_title` as template")
p1 = grid.grabExpr(draw(ht1))
ht2 = Heatmap(test_matrix, row_split = annotation, border=T, column_title = "no `row_title` is set")
p2 = grid.grabExpr(draw(ht2))

library(cowplot)
plot_grid(p1, p2, nrow = 1)
```

![image](https://user-images.githubusercontent.com/449218/77205351-fd275800-6af4-11ea-9f3a-c715468fda70.png)
