### ISSUE TITLE
Error if there is 'no' dendrogram to be drawn

### ISSUE THREAD

**Issue by ringprince** [jokergoo/ComplexHeatmap#42]
To reproduce with an artificial example, I insert a duplicate row and put the two duplicate rows in one cluster to split by.  As a use case this might happen if one shows variables that are normalize onto (and if one clusters by correlation).

    library(ComplexHeatmap)
    library(circlize)
    
    set.seed(123)
    
    mat = cbind(rbind(matrix(rnorm(16, -1), 4), matrix(rnorm(32, 1), 8)),
                rbind(matrix(rnorm(24, 1), 4), matrix(rnorm(48, -1), 8)))
    
    # permute the rows and columns
    mat = mat[sample(nrow(mat), nrow(mat)), sample(ncol(mat), ncol(mat))]
    
    rownames(mat) = paste0("R", 1:12)
    colnames(mat) = paste0("C", 1:10)
    
    ## add duplicate row
    mat <- rbind(mat, R13=mat["R12",])
    
    Heatmap(mat, name = "foo", split = c(rep("B", 11), "A", "A"))
    ## Error in valid.viewport(x, y, width, height, just, gp, clip, xscale, yscale,  (from utils.R#267) : 
    ##  invalid 'xscale' in viewport

**Comment by jokergoo** [comment]
Thanks! I have fixed this bug. Now no dendrogram will be plotted if the height of the dendrogram is zero.

**Comment by ringprince** [comment]
Fix confirmed.  Thanks!
