### ISSUE TITLE
remove label from HeatmapAnnotation

### ISSUE THREAD

**Issue by ahdee** [jokergoo/ComplexHeatmap#423]
Hi in you example, 
ha = HeatmapAnnotation(foo = 1:10, col = list(foo = col_fun))
when plotted there is a label that prints "foo" next to the plot. Is there anyway to remove this or change the color to white so that it does not show up? thanks. sorry for the trivial question.

**Comment by jokergoo** [comment]
`foo` is the name of the annotation. Without the name, how can you know what the annotation stands for?

I guess you can replace `foo` to ` `  to hide the name.

**Comment by ahdee** [comment]
thanks; how would I replace or change the color of the` foo`?

**Comment by jokergoo** [comment]
Set `annotation_name_side = "left"` in `HeatmapAnnotation()` function.
