### ISSUE TITLE
Remove top bar plot above oncoprint

### ISSUE THREAD

**Issue by underbais** [jokergoo/ComplexHeatmap#424]
Hi,

Any way to NOT show that top element in oncoprint?

![oncoprint_top](https://user-images.githubusercontent.com/31751877/73979944-34eb8f00-48fd-11ea-8434-e87f384d8f4e.png)

Thanks!

**Comment by jokergoo** [comment]
You can set the argument `top_annotation = NULL`.

**Comment by underbais** [comment]
Perfect, thanks!
