### ISSUE TITLE
Combining ComplexHeatmap with other plots in R

### ISSUE THREAD

**Issue by MikhaelManurung** [jokergoo/ComplexHeatmap#425]
Thank you for such a wonderful package and support that you have provided for the users!

I wonder, is there a way to combine plots generated with ComplexHeatmap and other plots made by ggplot2 or base R? `cowplot` or `patchwork` could not work.

Best regards,
Mikhael

**Comment by jokergoo** [comment]
**packwork** is mainly for ggplot2 plots? I haven't tried.

**cowplot** definitely works. I have been using it for quite some time:

```r
figure_a = ~plot(1:10)
figure_b = ggplot(data=iris, aes(x = Sepal.Length, y = Sepal.Width)) + geom_point()
figure_c = grid.grabExpr(draw(Heatmap(matrix(rnorm(100), 10))))

plot_grid(figure_a, figure_b, figure_c,nrow = 1, labels = c("A", "B", "C"))
```

![image](https://user-images.githubusercontent.com/449218/74230414-9ed0b380-4cc4-11ea-91b6-4bce3010c6d3.png)

**Comment by jokergoo** [comment]
Ha, patchwork also works for base R graphics. Similar usage as cowplot.
