### ISSUE TITLE
Change ratio between bar plot and the intersection matrix plot in UpSet function

### ISSUE THREAD

**Issue by felippelazar** [jokergoo/ComplexHeatmap#426]
Hi,

First of all, congratulations for the wonderful package for R. 

There is a parameter in the **upset function** from **UpSet package** called **mb.ratio** which does the following: _"to change the proportions of the plot heights assigned to the matrix and intersection size bar plot, use the mb.ratio parameter entered as percentages"_

I would like to know if its possible to add this parameter to the UpSet function in ComplexHeatMap Package. If not, I would like to know if there's any alternative for re-scaling the proportions for the bar plot and the matrix and intersection plot (I feel the bar plots are much lower than the intersection matrix plot)

Thanks in advance,

Felippe

**Comment by jokergoo** [comment]
You can set the height of the barplot by:

```r
UpSet(m, top_annotation = upset_top_annotation(m, height = unit(4, "cm")))
```

**Comment by felippelazar** [comment]
Thanks,

It works like a charm,

Sincerely,

Felippe
