### ISSUE TITLE
legend_gp Ignored for heatmap_legend_param List

### ISSUE THREAD

**Issue by DarioS** [jokergoo/ComplexHeatmap#427]
It remains unchanged and there is no warning about parameters being ignored.

```r
 M <- matrix(1:9, ncol = 3)
Heatmap(M, heatmap_legend_param = list(at = 1:9, color_bar = "discrete", legend_gp = gpar(fill = 1:9)))
```

**Comment by jokergoo** [comment]
What is going wrong with the code? Following plot was generated with your code.

![image](https://user-images.githubusercontent.com/449218/74740100-82032580-525a-11ea-9fdd-2a32a24d2573.png)

**Comment by DarioS** [comment]
My expectation is that the colour palette should be the same as for `plot(1:10, col = 1:10, pch = 19)`. I get the desired result if I use `col = colors` but not if I use `heatmap_legend_param` and specify `legend_gp`.

**Comment by jokergoo** [comment]
The colors in the legend should fit the color in the heatmap, so the legend filled color set in `legend_gp` will be ignored.
