### ISSUE TITLE
fail to detect viewports when wrapping decorate_annotation() in functions

### ISSUE THREAD

**Issue by RussBainer** [jokergoo/ComplexHeatmap#429]
Hi, I absolutely love your stuff but I have a similar problem to the one described in [https://github.com/jokergoo/ComplexHeatmap/issues/331](#331). I believe it is related to problems identifying the correct viewport within a function call, but it's also possible that I am not specifying the secondary annotation properly. 

My code (based on the above and my reading of the manual) looks like:

```
moreUpSet <- function(m, tests, ...){
  
 ha <- ComplexHeatmap::HeatmapAnnotation("Intersection size" = anno_barplot(comb_size(m), 
                                                                            border = FALSE, 
                                                                            gp = gpar(fill = "black"),
                                                                            height = unit(3, "cm"),
                                                                            axis_param = list(side = "right")),
                                         'Overlap Z' = anno_empty(border = TRUE, 
                                                                  height = unit(2, "cm")),
                                         annotation_name_side = rep("right",2),
                                         annotation_name_rot = rep(0,2))  

  ComplexHeatmap::UpSet(m, 
      top_annotation = ha, ...) 
 
    decorate_annotation('Overlap Z', {
    exes <- c(0.5, (length(comb_size(m)) + 0.5))
    whys <- cm2z(m, tests)$Z
    whys[!is.finite(whys)] <- 0
    maximus <- max(abs(round(whys)))
    cols <- colorRampPalette(c('blue', 'grey', 'red'))(2 * maximus) 

    pushViewport(viewport(xscale = exes, yscale = range(round(value)), name = 'Overlap Z'))
    grid.lines(exes, c(0, 0), gp = gpar(lty = 2),
        default.units = "native")
    grid.points(1:length(comb_size(m)), value, pch = 16, size = unit(2, "mm"),
        gp = gpar(col = cols[round(whys) + maximus]), default.units = "native")
    grid.yaxis(at = range(round(value)))
    popViewport()
}) 
   
  return(invisible(NULL))
}

```
When I remove the function wrapper, everything appears to work correctly. Running the function I get the following error: 

```
Error in grid.Call.graphics(C_downviewport, name$name, strict) : 
  Viewport 'annotation_Overlap Z_1' was not found
```

If I place the following statement between the UpSet call and the decorate_annotation call: 

```
print(list_components())
print(current.viewport()$name)
```

I see the following: 

```
character(0)
[1] "ROOT"
```

Any help you might have would be very much appreciated.

_Originally posted by @RussBainer in https://github.com/jokergoo/ComplexHeatmap/issues/331#issuecomment-589402501_

**Comment by jokergoo** [comment]
Can you change `popViewport()` to `upViewport()`?

**Comment by xpan1** [comment]
I had the same problem, how did you fix it?
Error in grid.Call.graphics(C_downviewport, name$name, strict) : 
  Viewport 'annotation_intersection_size_1' was not found

**Comment by jokergoo** [comment]
Maybe you can try a newer version. The annotation name has been changed in recent versions.

**Comment by yashcrux** [comment]
I have the same issue and for me its a series of heat maps on a single file with ggplot annotation specific to that heatmap
