### ISSUE TITLE
Is there a way to vary the width of certain columns but not all?

### ISSUE THREAD

**Issue by ahdee** [jokergoo/ComplexHeatmap#430]
Hi so sometimes I need to highlight a particular sample ( column ) because its literally comparing 1:to many.  However what I need then is to have the one column be 3-5x bigger then the rest so that the color pattern can show up more.  Is this possible?  thanks.

**Comment by jokergoo** [comment]
Unfortunately no. Columns have the same size in a same heatmap. For your case, maybe you can split the column into several heatmaps, e.g. one heatmap (`ht1`) with the normal columns and the other heatmap with the wider columns (`ht2`). Different heatmaps can have different width for columns. Let's say, you split your original matrix into two matrices, `m1` and `m2`, and you want the columns in `m2` 5 times wider than in `m1`:

```r
ht1 = Heatmap(m1, width = unit(5, "mm")*ncol(m1))
ht2 = Heatmap(m2, width = unit(25, "mm")*ncol(m2))
ht1 + ht2
```

Or if you don't want to set the column with absolute widths, you can do:

```r
ht1 = Heatmap(m1, width = ncol(m1))
ht2 = Heatmap(m2, width = 5*ncol(m2))
ht1 + ht2
```

You can find how to adjust heatmap width from the following link:

https://jokergoo.github.io/ComplexHeatmap-reference/book/a-list-of-heatmaps.html#size-of-heatmaps

**Comment by ahdee** [comment]
thanks that is a neat idea; one issue I can see is that gradient will be different?

**Comment by jokergoo** [comment]
Can you add a plot here and also the code you used?
