### ISSUE TITLE
Many rows in heatmap makes the plot into nonsense

### ISSUE THREAD

**Issue by mknafl** [jokergoo/ComplexHeatmap#431]
I am using complex heatmaps to represent features of individuals.  The features are the rows and the columns are the individuals.  I have about 1000 features.  I would like to be able to display them all on one "screen".  If I do more then 200 I get nonsense.  Is there a workaround for this?  In order to support coloring each row on its own color scale, each row is its own heatmap item and they are all vertically appended to one another.  Any suggestions are welcome!  Thanks!

**Comment by jokergoo** [comment]
I don't know how your features look like. Maybe you can apply a z-score scaling on rows? Basically, heatmap is a way to visualize patterns shared by groups of rows or columns. If all your rows are so different, then maybe heatmap is not a proper way to visualize your data.

If you really want to assign different color scales for rows, you can construct heatmaps for each row, and append them vertically:

```r
ht_list = NULL
for(i in 1:nrow(mat)) {
    ht_list = ht_list %v% Heatmap(mat[i, , drop = FALSE])
}
ht_list
```

**Comment by mknafl** [comment]
Here is an example.  I commented on the reason for different colors for different rows in my other open issue, but I can summarize here.  Each feature has a different scale, which could be made the same per row based on a z score, BUT the coloring function works off the max and min of the matrix, not the row.  So, a row may not have the max or min color if the max or min was an outlier of the matrix.  I also don't care so much about relationships between features, but I do care about relationships within a feature to the response variable(shown in the annotation).  Please let me know if there is anyway I can make the output not look like this with many rows.

[ExampleManyRows.pdf](https://github.com/jokergoo/ComplexHeatmap/files/4282649/ExampleManyRows.pdf)

[ExampleManyRows.xlsx](https://github.com/jokergoo/ComplexHeatmap/files/4282652/ExampleManyRows.xlsx)

`
library(ComplexHeatmap)
library(circlize)
library(oce)
WaterfallPlusFeatures <- function(DataFilename,WaterfallVar,FeatureVars,PlotHeight,RowNameFontSize,HeatmapAsFile)
{
	dRead<-read.csv(DataFilename)
	dSorted <- as.data.frame(dRead)
	WaterfallColumn <- grep(WaterfallVar,colnames(dSorted))
	dSorted <- dSorted[with(dSorted,order(-dSorted[,WaterfallColumn])),]
	dSmaller <- as.data.frame(t(dSorted[FeatureVars]))
	dSmaller[dSmaller==1.79769e+308]<-NA
	d <- as.matrix(dSmaller)
	dRespID <- as.matrix(dSorted[c("JustSlideID")])
	uRespID <- unique(dRespID)
	MyColorIndices <- data.frame(MyIndex = numeric(length(dRespID)))
	for(Index in seq(1,length(dRespID),by = 1))
	{
	  MyColorIndices$MyIndex[Index] <- grep(dRespID[Index],uRespID)
	}
	dResponse <- as.data.frame(dSorted[c(WaterfallVar)])
	BarChart = anno_barplot(dResponse, height = unit(PlotHeight, "cm"), gp = gpar(fill = MyColorIndices$MyIndex))
	BarChartAsAnnotation = HeatmapAnnotation(WaterfallVar = BarChart, height = unit(1,"in"), width = unit(20,"in"))
	NumCols = ncol(d)
	ht = NULL
	for(Index in seq(1,length(FeatureVars),by = 1))
	{
	  GrepTerm <- paste0("^",FeatureVars[Index],"$")
	  CurrentFeatureIndex <- grep(GrepTerm,rownames(d))
		CurrentData <- d[CurrentFeatureIndex:CurrentFeatureIndex,1:NumCols,drop = FALSE]
		if(is.na(min(CurrentData,na.rm = TRUE)))
		{
		  MinValue = 0
		  MaxValue = 1
		}
		else
		{
		  MinValue = min(CurrentData,na.rm = TRUE)
		  MaxValue = max(CurrentData,na.rm = TRUE)
		  if(MinValue == MaxValue)
		  {
		    MaxValue = MinValue + 1
		  }
		}
		col_fun = colorRamp2(seq(MinValue, MaxValue, length = 2),c("green", "red"))
		CurrentHeatmap = Heatmap(width = unit(20, "in"),col = col_fun,rect_gp = gpar(col = "white", lty = "solid", lwd = 1, fontsize = 16),d[CurrentFeatureIndex:CurrentFeatureIndex,1:NumCols,drop = FALSE], row_names_gp = gpar(fontsize = RowNameFontSize),row_names_side = "left",show_heatmap_legend = FALSE, show_column_names = FALSE, cluster_rows = FALSE, cluster_columns = FALSE)
		ht = ht %v% CurrentHeatmap
	}
	ht = BarChartAsAnnotation %v% ht
	pdf(file = sprintf("%s",HeatmapAsFile),width = unit(24,"in"))
	draw(ht)
	dev.off()	
}

setwd("C:/Users/mknafl/Documents/R_Scripts")
WaterfallPlusFeatures("C:\\Users\\mknafl\\Desktop\\ExampleManyRows.csv", "BestResponse_n", c("Feature1",	"Feature2",	"Feature3",	"Feature4",	"Feature5",	"Feature6",	"Feature7",	"Feature8",	"Feature9",	"Feature10",	"Feature11",	"Feature12",	"Feature13",	"Feature14",	"Feature15",	"Feature16",	"Feature17",	"Feature18",	"Feature19",	"Feature20",	"Feature21",	"Feature22",	"Feature23",	"Feature24",	"Feature25",	"Feature26",	"Feature27",	"Feature28",	"Feature29",	"Feature30",	"Feature31",	"Feature32",	"Feature33",	"Feature34",	"Feature35",	"Feature36",	"Feature37",	"Feature38",	"Feature39",	"Feature40",	"Feature41",	"Feature42",	"Feature43",	"Feature44",	"Feature45",	"Feature46",	"Feature47",	"Feature48",	"Feature49",	"Feature50",	"Feature51",	"Feature52",	"Feature53",	"Feature54",	"Feature55",	"Feature56",	"Feature57",	"Feature58",	"Feature59",	"Feature60",	"Feature61",	"Feature62",	"Feature63",	"Feature64",	"Feature65",	"Feature66",	"Feature67",	"Feature68",	"Feature69",	"Feature70",	"Feature71",	"Feature72",	"Feature73",	"Feature74",	"Feature75",	"Feature76",	"Feature77",	"Feature78",	"Feature79"), 10, 8,"C:\\Users\\mknafl\\Desktop\\ExampleManyRows.pdf")
`
