### ISSUE TITLE
Vertical concatenation causes grid.text annotations to all be the same

### ISSUE THREAD

**Issue by mknafl** [jokergoo/ComplexHeatmap#432]
If I use the matrix d, and I create a heatmap for every row, in order to colorize only the scale of the row, and I choose to use cell_fun to write the value to each cell, all the cells get d[1,] or d[n,] values.  Any ideas why?  Thanks!

**Comment by jokergoo** [comment]
I don't really understand the issue. Can you add an example code here?

**Comment by mknafl** [comment]
I will attach the input scripts and the output.  If you look, each row's text is the values of Feature 5.  This seems to mean the grid text is being cached or something.  Any idea on how to fix it is appreciated.  As far as why I colorize each row rather than the whole chart, it is because the scales of the features are different.  I know you can z score everything and then share a scale, but I really care more about the within a feature variation and using the z score to create one heatmap means I get the min and max z score of the whole table, rather than the min and fax of the feature.  I am looking at within feature relationships to the response variable shown in the annotation.  Thanks for any help you can provide!

[Example.pdf](https://github.com/jokergoo/ComplexHeatmap/files/4282526/Example.pdf)


`
library(ComplexHeatmap)
library(circlize)
library(oce)
WaterfallPlusFeatures <- function(DataFilename,WaterfallVar,FeatureVars,PlotHeight,RowNameFontSize,HeatmapAsFile)
{
        dRead<-read.csv(DataFilename)
	dSorted <- as.data.frame(dRead)
	WaterfallColumn <- grep(WaterfallVar,colnames(dSorted))
	dSorted <- dSorted[with(dSorted,order(-dSorted[,WaterfallColumn])),]
	dSmaller <- as.data.frame(t(dSorted[FeatureVars]))
	dSmaller[dSmaller==1.79769e+308]<-NA
	d <- as.matrix(dSmaller)
	dRespID <- as.matrix(dSorted[c("JustSlideID")])
	uRespID <- unique(dRespID)
	MyColorIndices <- data.frame(MyIndex = numeric(length(dRespID)))
	for(Index in seq(1,length(dRespID),by = 1))
	{
	  MyColorIndices$MyIndex[Index] <- grep(dRespID[Index],uRespID)
	}
	dResponse <- as.data.frame(dSorted[c(WaterfallVar)])
	BarChart = anno_barplot(dResponse, height = unit(PlotHeight, "cm"), gp = gpar(fill = MyColorIndices$MyIndex))
	BarChartAsAnnotation = HeatmapAnnotation(WaterfallVar = BarChart, height = unit(1,"in"), width = unit(20,"in"))
	NumCols = ncol(d)
	ht = NULL
	for(Index in seq(1,length(FeatureVars),by = 1))
	{
	  GrepTerm <- paste0("^",FeatureVars[Index],"$")
	  CurrentFeatureIndex <- grep(GrepTerm,rownames(d))
		CurrentData <- d[CurrentFeatureIndex:CurrentFeatureIndex,1:NumCols,drop = FALSE]
		if(is.na(min(CurrentData,na.rm = TRUE)))
		{
		  MinValue = 0
		  MaxValue = 1
		}
		else
		{
		  MinValue = min(CurrentData,na.rm = TRUE)
		  MaxValue = max(CurrentData,na.rm = TRUE)
		  if(MinValue == MaxValue)
		  {
		    MaxValue = MinValue + 1
		  }
		}
		col_fun = colorRamp2(seq(MinValue, MaxValue, length = 2),c("green", "red"))
		CurrentHeatmap = Heatmap(width = unit(20, "in"),col = col_fun,rect_gp = gpar(col = "white", lty = "solid", lwd = 1, fontsize = 16),d[CurrentFeatureIndex:CurrentFeatureIndex,1:NumCols,drop = FALSE], row_names_gp = gpar(fontsize = RowNameFontSize),row_names_side = "left",show_heatmap_legend = FALSE, show_column_names = FALSE, cluster_rows = FALSE, cluster_columns = FALSE,cell_fun = function(j, i, x, y, width, height, fill) {
		  grid.text(if(is.na(CurrentData[i, j])) "" else sprintf("%.1f", CurrentData[i, j]), x, y, gp = gpar(fontsize = 5))})
		ht = ht %v% CurrentHeatmap
	}
	ht = BarChartAsAnnotation %v% ht
	pdf(file = sprintf("%s",HeatmapAsFile),width = unit(24,"in"))
	draw(ht)
	dev.off()	
}

getwd()
setwd("C:/Users/mknafl/Documents/R_Scripts")
WaterfallPlusFeatures("C:\\Users\\mknafl\\Desktop\\Example.csv", "BestResponse_n", c("Feature1","Feature2","Feature3","Feature4","Feature5"), 10, 8,"C:\\Users\\mknafl\\Desktop\\Example.pdf")
`

**Comment by jokergoo** [comment]
Hi, this is something not easy to debug :)

You generate `CurrentData` in every iteration in the for loop, let's make the code shorter:

```r
# This is your for loop
for(Index in seq(1,length(FeatureVars),by = 1)) {
    # you dynamically generate the variable `CurrentData`
    CurrentData <- d[CurrentFeatureIndex:CurrentFeatureIndex,1:NumCols,drop = FALSE]
    ...
    # and later you put `CurrentData` in `cell_fun` function
    CurrentHeatmap = Heatmap(..., cell_fun = function(...) {
        # here you use `CurrentData`
    })
    ht = ht %v% CurrentHeatmap
}
# the heatmap is draw outside of the for loop
draw(ht)
```

In this code, `cell_fun` is using some values outside the `cell_fun` function and it changes. When `CurrentHeatmap` is defined in each for loop, the `cell_fun` is no executed, which means the value of `CurrentData` is not recorded for each for loop. `cell_fun` will be executed when `draw()` function is executed, when the value of `CurrentData` is only to be found. At that time, the for loop is finished, and `CurrentData` is the last row in your table and the value used is the same for all `cell_fun` in all vertical heatmaps.

To solve this problem, we need to have a local copy of `CurrentData` for each heatmap and correspond to each heatmap. Here we can use `local()` function to put a copy to the lcoal environment:

```r
# This is your for loop
for(Index in seq(1,length(FeatureVars),by = 1)) {
    # you dynamically generate the variable `CurrentData`
    CurrentData <- d[CurrentFeatureIndex:CurrentFeatureIndex,1:NumCols,drop = FALSE]
    ...
    # and later you put `CurrentData` in `cell_fun` function
    CurrentHeatmap = Heatmap(..., cell_fun = local({
        CurrentData = CurrentData
        function(...) {
            # here you use `CurrentData`
        }
    })
    ht = ht %v% CurrentHeatmap
}
# the heatmap is draw outside of the for loop
draw(ht)
```

In this line: `CurrentData = CurrentData`, the right `CurrentData` is the one you created in the for loop. The left `CurrentData` is a new variable saved in the local environment where the `cell_fun` will first look for variables. `local()` will assign different environment for `cell_fun` in different heatmaps, so they always find the correct `CurrentData`.

Following is the adjusted version of your code for making the heatmap:

```r
ht = NULL
	for(Index in seq(1,length(FeatureVars),by = 1))
	{
	  GrepTerm <- paste0("^",FeatureVars[Index],"$")
	  CurrentFeatureIndex <- grep(GrepTerm,rownames(d))
		CurrentData <- d[CurrentFeatureIndex:CurrentFeatureIndex,1:NumCols,drop = FALSE]
		if(is.na(min(CurrentData,na.rm = TRUE)))
		{
		  MinValue = 0
		  MaxValue = 1
		}
		else
		{
		  MinValue = min(CurrentData,na.rm = TRUE)
		  MaxValue = max(CurrentData,na.rm = TRUE)
		  if(MinValue == MaxValue)
		  {
		    MaxValue = MinValue + 1
		  }
		}
		col_fun = colorRamp2(seq(MinValue, MaxValue, length = 2),c("green", "red"))
		CurrentHeatmap = Heatmap(col = col_fun,rect_gp = gpar(col = "white", lty = "solid", lwd = 1, fontsize = 16),
			d[CurrentFeatureIndex:CurrentFeatureIndex,1:NumCols,drop = FALSE], 
			row_names_gp = gpar(fontsize = RowNameFontSize),
			row_names_side = "left",show_heatmap_legend = FALSE, 
			show_column_names = FALSE, cluster_rows = FALSE, cluster_columns = FALSE,
			cell_fun = local({
				CurrentData = CurrentData
				function(j, i, x, y, width, height, fill) {
			  		grid.text(if(is.na(CurrentData[i, j])) "" else sprintf("%.1f", CurrentData[i, j]), x, y, gp = gpar(fontsize = 5))
			  	}
			})
		)
		ht = ht %v% CurrentHeatmap
	}
	ht = BarChartAsAnnotation %v% ht
	draw(ht)
```

 
![image](https://user-images.githubusercontent.com/449218/76417114-8e335c00-639c-11ea-893b-d4b6d8773f8c.png)

**Comment by mknafl** [comment]
Thanks!  I will try this!  I could tell that R was doing some kind of caching or delayed evaluation, but I am still not clear on why cell_fun() is not evaluated until we call draw().  I am new to R so maybe this is an obviously answered question.  How can I tell that evaluation or execution will be delayed?  In this example, we are constructing through Heatmap() then using the constructed heatmap to vertically concatenate.  I would have thought all evaluation would be done at this point.  I am going to research this as well, but any guidance on this is appreciated!  Also, thanks for creating such a great class and for helping me to use it!

**Comment by jokergoo** [comment]
Only when the arguments accept functions as values and the functions are not executed immediately.

e.g. for `sapply()` function that accepts a function as an argument:

```r
sapply(letters, function(x) print(x))
```

This function `function(x) print(x)` is executed when `sapply()` is executed, so you don't need to worry anyting.

However, `Heatmap()` function is only a construction function where `cell_fun` is not executed and is only stored as a member of the `Heatmap` object, and it is run only when `draw()` is executed, so you need to be careful where `cell_fun` looks for the variables it uses.
