### ISSUE TITLE
anno_zoom(): position wrongly calculated

### ISSUE THREAD

**Issue by jokergoo** [jokergoo/ComplexHeatmap#433]
When `cluster_row_slices = FALSE` and `row_split` is a factor with levels,

<img width="764" alt="Screenshot 2020-02-24 at 20 36 26" src="https://user-images.githubusercontent.com/449218/75184845-55ad4480-5745-11ea-86d4-c3c47ea78095.png">

**Comment by jokergoo** [comment]
```r

set.seed(12345)
mat = matrix(rnorm(30*10), nr = 30)
row_split = c(rep("a", 10), rep("b", 5), rep("c", 2), rep("d", 3), 
	          rep("e", 2), letters[10:17])
row_split = factor(row_split)

panel_fun = function(index, name) {
	pushViewport(viewport())
	grid.rect()
	grid.text(name)
	popViewport()
}

anno = anno_zoom(align_to = row_split, which = "row", panel_fun = panel_fun, 
	size = unit(0.5, "cm"), width = unit(4, "cm"))

# > dev.size()
# [1] 3.938326 4.502203
draw(Heatmap(mat, right_annotation = rowAnnotation(foo = anno), 
	row_split = row_split))
```

![image](https://user-images.githubusercontent.com/449218/77147412-725f4280-6a8d-11ea-99cf-3707b0579767.png)

**Comment by nfancy** [comment]
Hi, thanks for this wonderful package. I manage to generate the second plot, but how can we add more than one text labels within each of the box from another vector? So, instead of the names inside the box, say I want to add multiple pathways. Many thanks in advance.

**Comment by jokergoo** [comment]
You need to manually calculate the size of box based on the text in it.

I have answered your question in https://github.com/jokergoo/jokergoo.github.io/issues/2#issuecomment-980038705
