### ISSUE TITLE
Unable to Change Axis Title Size of anno_barplot

### ISSUE THREAD

**Issue by DarioS** [jokergoo/ComplexHeatmap#434]
If specifying `gp = gpar(fontsize = 20)` to `axis_param` it only applies to the tick labels not to the axis label. Could this be documented or implemented if not yet possible? Bigger sizes are useful for posters.

![image](https://user-images.githubusercontent.com/631218/75207385-a9af3c00-57cc-11ea-8ae3-3213e3c3c20e.png)

Perhaps "... Other arguments" needs more explanation in the function documentation. What other arguments could these be? I was also hoping to find details in the help page about if background grids are possible, similar to `panel.grid.major` of ggplot2.

**Comment by jokergoo** [comment]
I think these are not the title for axes, they are the titles/names of the annotations. You can control it by `annotation_name_gp` argument in `HeatmapAnnotation()` function. 

There is no direct argument to add the background grid. You can go to these annotation regions after the heatmap is drawn and add self-defined graphics there by `decorate_annotation()` function, but the new graphics (e.g. the bachground grid) will be drawn above the graphics already in the annotation region.

```r
decorate_annotation("foo", {
    grid.segments(...)
    # or
    grid.lines(...)
})
```
