### ISSUE TITLE
change fontsize annotation names

### ISSUE THREAD

**Issue by jml96** [jokergoo/ComplexHeatmap#438]
Hi,
Thank you for the nice tool.
Is there a way to change the font size of the annotation titles?
I could not find any example showing how to change them.
Thank you.

Regards,
João

**Comment by jokergoo** [comment]
Do you mean the annotation name (`foo1` and `bar1` in following plot)?

![image](https://user-images.githubusercontent.com/449218/76417262-deaab980-639c-11ea-9b7e-63abb30dc1ef.png)

They can be controlled by `annotation_name_gp` parameter in `HeatmapAnnotation()` function.
