### ISSUE TITLE
dyanamic alter_fun but with shape as well as color?

### ISSUE THREAD

**Issue by ahdee** [jokergoo/ComplexHeatmap#439]
Hi the function example was awesome , however is there a way to also add static features like background and in some cases with defined shapes.  For example below, I besides the color defined in all.u I also wanted to customize a few values like cna1 and cna2, however when I put this in everything is ignored including background, cna1 and cna2.  

thanks! 

```
 function(x, y, w, h, v) {
    
    background = function(x, y, w, h) 
        grid.rect(x, y, w*1, h*1, gp = gpar(fill = "black", col = NA))
    
    
    # make shapes 
    cna1 = function(x, y, w, h) 
        grid.points(x, y, pch = 16)
    
    # crossed lines
    cna2 = function(x, y, w, h) 
        grid.segments(x - w*0.5, y - h*0.5, x + w*0.5, y + h*0.5, gp = gpar(lwd = 2))
    
    n = sum(v)  # how many alterations for current gene in current sample
    h = h*0.9
    # use `names(which(v))` to correctly map between `v` and `col`
    if(n) grid.rect(x, y - h*0.5 + 1:n/n*h, w*0.9, 1/n*h, 
                    gp = gpar(fill = all.u[names(which(v))], all.u = NA), just = "top")
}
```

I also tried adding in something like this. 

```
if ( grepl ( "cna1", v )){
            grid.points(x, y, pch = 16)
    }

```

**Comment by jokergoo** [comment]
Hi, I think you misunderstand the use of `alter_fun`. The value of it can be two types of values.

1. a list of functions where each function corresponds to one mutation type or background. For your case, it should be:

```r
alter_fun = list(
 background = function(x, y, w, h) 
        grid.rect(x, y, w*1, h*1, gp = gpar(fill = "black", col = NA)),
    
    # make shapes 
    cna1 = function(x, y, w, h) 
        grid.points(x, y, pch = 16),
    
    # crossed lines
    cna2 = function(x, y, w, h) 
        grid.segments(x - w*0.5, y - h*0.5, x + w*0.5, y + h*0.5, gp = gpar(lwd = 2))
)
```

In this case, self-defined functions e.g. `background`, `cna1` or `cna2` will be applied for the gene in the sample if there is such mutation there.

2. a single function with FIVE arguments. Now you can find the value of "current mutation" from the fifth argument. Note this function is applied to every gene in every sample:

```r
function(x, y, w, h, v) {
    
    if("background" %in% v)
        grid.rect(x, y, w*1, h*1, gp = gpar(fill = "black", col = NA))
    
    
    # make shapes 
    if("cna1" %in% v)
        grid.points(x, y, pch = 16)
    
    # crossed lines
   if("cna2" %in% v)
        grid.segments(x - w*0.5, y - h*0.5, x + w*0.5, y + h*0.5, gp = gpar(lwd = 2))
}
```

You can find more explanation from https://jokergoo.github.io/ComplexHeatmap-reference/book/oncoprint.html#define-the-alter-fun

**Comment by ahdee** [comment]
great thank you
