### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by xuebaliang** [jokergoo/ComplexHeatmap#440]
hello, recently I failed to install the ComplexHeatmap package on the linux server. Thus can you supply it using offline form ".tar.gz"??? Thanks.

**Comment by xuebaliang** [comment]
In this way I can use "R CMD INSTALL" to install it.

**Comment by jokergoo** [comment]
You can try to install from Bioconductor development branch. 

http://bioconductor.org/packages/devel/bioc/html/ComplexHeatmap.html
