### ISSUE TITLE
UpSetR - Intersect mode - one variable is empty, but it is not

### ISSUE THREAD

**Issue by buccimtpc** [jokergoo/ComplexHeatmap#441]
UpSetR in intersection mode has a weird behaviour (read below).

This is the code that generates the figure below:

```
library(ComplexHeatmap)
library(UpSetR)

names(df) <- c("RID","foo 1","foo 2","foo 3","foo 4")

m2 = make_comb_mat(df, mode = "intersect", remove_empty_comb_set = FALSE)
m <- m2
cs = comb_size(m)
ss = set_size(m)
so = order(set_size(m), decreasing = TRUE)
co = order(comb_size(m), decreasing = TRUE)
ht = UpSet(m,pt_size = unit(5, "mm"),lwd = 3,
           comb_order = co,
           comb_col = c("red", "blue", "black","green","yellow")[comb_degree(m)]
 )
ht = draw(ht,adjust_annotation_extension = FALSE,padding = unit(c(20, 20, 20, 20), "mm"),column_title = "Intersect (Full intersection between sets)", column_title_gp = gpar(fontsize = 16))
co = column_order(ht)
ro = row_order(ht)
nr =nrow(m)
nc = ncol(m)
decorate_annotation("Intersection\nsize", {
  grid.text(cs[co], 
            x = 1:nc, 
            y = unit(cs[co], "native") + unit(2, "mm"), 
            gp = gpar(fontsize = 10), 
            just = "bottom",
            default.units = "native")
})
decorate_annotation("Set size", {
  grid.text(ss[so],
            y = nr:1,
            x = unit(ss[so], "native") + unit(10, "mm"),
            gp = gpar(fontsize = 10),
            just = "bottom",
            default.units = "native")
})
```

<img width="992" alt="Screenshot 2020-03-06 at 11 17 55" src="https://user-images.githubusercontent.com/35525053/76075048-9bb3a500-5f9c-11ea-8c69-8885d31ea9c2.png">

**Why foo2 has intersection size 0 when the combination includes only foo2 set (10th column)? Shouldn't the Intersection size be 1249 (full size), like for the other three sets (columns 1,2,7)? 
What am I missing?**

Below another visualisation of the data with the package Vennerable:

<img width="516" alt="Screenshot 2020-03-06 at 11 12 45" src="https://user-images.githubusercontent.com/35525053/76075238-f0572000-5f9c-11ea-995c-534f4e30f8db.png">

Thanks in advance for your time!

**Comment by jokergoo** [comment]
Hi, thanks for reporting! `UpSet()` function has some issues. I will work on it in the next few days.

**Comment by jokergoo** [comment]
Hi, in the old version, 'intersection" mode was not correctly calculated. I have fixed this bug in the new version.
