### ISSUE TITLE
UpSet nset? 

### ISSUE THREAD

**Issue by aderzelle** [jokergoo/ComplexHeatmap#443]
Hello, 

What is the equivalent of the original UpsetR "nset" function? 

From the same matrix, with the original UpsetR function I get this 
![original](https://user-images.githubusercontent.com/23341393/77077360-69229700-69f5-11ea-9af6-dd3905b41fe0.png)

And with ComplexHeatmap implementation I get this
![heatmap](https://user-images.githubusercontent.com/23341393/77077332-5a3be480-69f5-11ea-97b6-573822aef8f7.png)

It is not clear to me exactly why:
here is the code:
```
DT3 = na.omit(DT2)
m = make_comb_mat(DT3)
UpSet(m)
upset(DT3, nsets = 11)
```
```
t(m)
A combination matrix with 11 sets and 2048 combinations.
  ranges of combination set size: c(3, 1458278).
  mode for the combination size: distinct.
  sets are on columns
  universal set is set.

```
Thank you

**Comment by aderzelle** [comment]
Okay it was easy, the original upset has a default nintersect = 40. 

I guess with so many intersections a "classical" heatmap might be more appropriate

**Comment by jokergoo** [comment]
Hi, I have been working on an improved version of the `UpSet()` function.

In the new version, only the non-empty combination sets will be saved, thus, you will not have 2048 combinations.

Also for the n_set, you can simply subset the combination matrix by:

```r
m[order(comb_size(m), decreasing = TRUE)[1:n]]
```
