### ISSUE TITLE
anno_mark: multiple labels per index

### ISSUE THREAD

**Issue by funnell** [jokergoo/ComplexHeatmap#444]
Hello,

I would like to be able to have multiple labels per heatmap index using anno_mark. For example, annotating genes within a set of predefined genomic regions which are represented in the heatmap.

Thank you!

**Comment by jokergoo** [comment]
Then maybe you can try `anno_zoom()` annotation function:

https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html#zoom-annotation

where you can put the text of multiple regions in the box (of course not drawing the axes).

This function seems to have bugs in some cases. If you use it and see something going wrong, please tell me.

**Comment by jokergoo** [comment]
And you can find an example here (https://github.com/jokergoo/ComplexHeatmap/issues/433), and in your case, the connection comes from one single row. 

That plot has some problems to arrange the orders of the "block of text". I am working on it currently.
