### ISSUE TITLE
HeatmapAnnotation question help please

### ISSUE THREAD

**Issue by davidlyon3** [jokergoo/ComplexHeatmap#445]
Hi

I have the following question that I can't figure out.
please help.

Thanks in advance

If I use this dataset:
<pre>
library(shiny)
library(ComplexHeatmap)
set.seed(123)
myData2 = matrix(rnorm(80, 2), 8, 10)
</pre>

How can I generate the following code by a foreach loop or map instead of hardcoding eg:

<pre>
HeatmapAnnotation(df=data.frame(myData2),
   points1 = anno_lines(myData2[,1], axis=TRUE),points2 = anno_lines(myData2[,2], axis=TRUE),
 points3 = anno_lines(myData2[,3], axis=TRUE),points4 = anno_lines(myData2[,4], axis=TRUE)
                  )
</pre>

something like this, I tried but can't get it to work:

<pre>
 1:4 %>% map(~ paste0("points", .x, ' =  anno_points(myData2[,', .x ,'] )' ))

</pre>

**Comment by jokergoo** [comment]
You can use `do.call()`:

```r
anno_list = list(df = data.frame(myData2))
for(i in 1:4) {
    anno_list[[ paste0("points", i) ]] = anno_lines(myData2[, i], axis = TRUE)
}
ha = do.call(HeatmapAnnotation, anno_list)
```

```

**Comment by davidlyon3** [comment]
Thank you very much
