### ISSUE TITLE
Add additional labels on the annotation bars

### ISSUE THREAD

**Issue by ZWanBing** [jokergoo/ComplexHeatmap#446]
![image](https://user-images.githubusercontent.com/33241734/77734755-3f482080-7044-11ea-9b6f-ee2833aaf460.png)
Could I add additional labels on the annotation bars? Just like the p-value on the right of the figure above.
I have only achieved this:
![image](https://user-images.githubusercontent.com/33241734/77735506-a61a0980-7045-11ea-8c90-bfdb4ca16d46.png)
Many thanks for your help!

**Comment by jokergoo** [comment]
You can use `decorate_annotation()` function, e.g. to add the text for "Gender" annotation：

```r
decorate_annotation("Gender", {
    grid.text("P = 0.411", x = unit(1, "npc") + unit(1, "mm"))
})
```

**Comment by ZWanBing** [comment]
Thank you😁
