### ISSUE TITLE
Subsetting comb matrix for UpSet plot

### ISSUE THREAD

**Issue by lauradmartens** [jokergoo/ComplexHeatmap#448]
I am trying to use UpSet to plot only combination sets that have a size bigger than a certain threshold. From the manual that should work like:
`UpSet(m[comb_size(m) >= 4])`

However, I then get the error:
`Error: length of `column_order` should be same as the number of matrix columns`

Any ideas, what could be happening? 
Thanks a lot!

**Comment by jokergoo** [comment]
What is the value of `comb_size(m)` ?

**Comment by lauradmartens** [comment]
This is `comb_size(m)`: 
<img width="262" alt="Bildschirmfoto 2020-03-30 um 14 57 49" src="https://user-images.githubusercontent.com/25029058/77914973-005dd900-7297-11ea-9370-19b08fa13b22.png">

And I am trying to do `UpSet(m[comb_size(m)>1500])`

**Comment by jokergoo** [comment]
This is strange. Can you try with the newest version from github, or can you attach the object `m` here?
