### ISSUE TITLE
anno_block not showing title/name

### ISSUE THREAD

**Issue by Hrovatin** [jokergoo/ComplexHeatmap#449]
When making heatmap annotation with anno_block the 'Name' of the annotation is not displayed (e.g. HeatmapAnnotation(Name=anno_block(...)). This does not happen even after setting  show_annotation_name=TRUE and name='Name'.

**Comment by jokergoo** [comment]
`anno_block()` internally disables the annotation name. `anno_block()` basically adds row-slice-level annotations for the heatmap, thus the name for this annotation is of no sense. Can you give me an example of why you need the annotation name for `anno_block()`? Maybe you can use the "simple annotation" instead (https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html#simple-annotation).

**Comment by Hrovatin** [comment]
We have a case where we have multiple strains  of an organism - each is a column slice. However, strains are further classified to belong to one of the strain groups. For the strain group annotation I currently use anno_block, as it was requested that group is annotated with text (not only a colour). 
The below image shows from top to bottom: strain, strain group, time, (and gene expression, which is here omitted). I would like to add a name 'Group' besides the group annotation, as is done for time. 

Ideally, I would split part of the heatmap by strain (e.g. time and expression that will be shown below the heatmap annotations) and part of it by group (e.g. the group annotation). I could then use text+border around a larger block to show strain groups. However, i did not find a relatively straightforward way to do so. 

![Rplot06](https://user-images.githubusercontent.com/47607471/78136603-367c9380-7424-11ea-9d26-ba382cd5b53e.png)

**Comment by jokergoo** [comment]
I have updated the package. Now you can add `show_name = TRUE` in `anno_block()` function. You can update it from GitHub.

```r
Heatmap(matrix(rnorm(100), 10), 
    top_annotation = HeatmapAnnotation(foo = anno_block(gp = gpar(fill = 2:4),
        labels = c("group1", "group2", "group3"), labels_gp = gpar(col = "white"), show_name = TRUE)),
    column_km = 3,
    left_annotation = rowAnnotation(foo = anno_block(gp = gpar(fill = 2:4),
        labels = c("group1", "group2", "group3"), labels_gp = gpar(col = "white"), show_name = TRUE)),
    row_km = 3)
```

![image](https://user-images.githubusercontent.com/449218/78139071-354d6580-7428-11ea-8022-6ed3ec2dee08.png)

**Comment by Hrovatin** [comment]
Thank you. Now it works as expected.
