### ISSUE TITLE
alter_graphic() function not found

### ISSUE THREAD

**Issue by alevax** [jokergoo/ComplexHeatmap#458]
`Error in alter_graphic("rect", fill = "#CCCCCC") : 
  could not find function "alter_graphic"`

I am running the 2.3.4 version from github, and got the above error. It seems the function is not exported, it is not visible in the R environment.

**Comment by jokergoo** [comment]
You can re-install from GitHub or restart your R session.

The function is there:

https://github.com/jokergoo/ComplexHeatmap/blob/eb684e19efc1f57f06306bf3d01708e23c484ef9/NAMESPACE#L131
