### ISSUE TITLE
when there are too many legends, should we put them into multiple colums/rows?

### ISSUE THREAD

**Issue by jokergoo** [jokergoo/ComplexHeatmap#46]

**Comment by funnell** [comment]
Hi @jokergoo,

I'm having this problem now (too many annotation legends). Is there a way to fit them into separate columns?

**Comment by jokergoo** [comment]
Currently I don't have time for this because I only develop my software in my spare time.

How many legends do you have? Maybe you can put them at the bottom of heatmaps where there can
be more legends to be there. On the other hand, when there are really too many legends, I think it might not be a good idea to plot them all.

**Comment by funnell** [comment]
Okay, thanks for the advice!

**Comment by crazyhottommy** [comment]
I have 20 legend for annotation columns, and I put the legend in the bottom, but still it is too many.
it will be helpful to have them placed into multiple rows just like `nrow` in the legend_parms for each single legend. thanks!

**Comment by jokergoo** [comment]
Yeah, I will think about it. To be honest, I don't want to make legends too complex because the main message from the plot should directly come from the heatmaps.

**Comment by bioinfomagician** [comment]
Also want to chime in that being able to split up set of annotation legends into multiple columns would be really useful.

**Comment by Alanocallaghan** [comment]
The code for legend alignment is here I think: https://github.com/jokergoo/ComplexHeatmap/blob/master/R/HeatmapList-class.R#L1419

**Comment by jokergoo** [comment]
moved to #187

**Comment by sahilseth** [comment]
Hi is there a solution for this?

multi-row legend (when they are at the bottom of the heatmap).

Thanks!

**Comment by jokergoo** [comment]
If you use the version > 1.99.*, it is automatically arranged into multi-rows.

![image](https://user-images.githubusercontent.com/449218/53524353-76fe3500-3adf-11e9-843a-cd8d656b0f89.png)

**Comment by sarpiens** [comment]
Hello, is there a way to do the opposite? Force all the legends to be in a single row, or a way to tell it how many rows of legends you want ? In my case I still have space at the top, but it generates the legends in two rows instead of a single row.  Thanks
