### ISSUE TITLE
Change of default clustering method in new version?

### ISSUE THREAD

**Issue by hjc0818** [jokergoo/ComplexHeatmap#460]
Thanks for providing such an amazing software. 

Recently I am doing a copy-number heatmap, and I was using R 3.5.2 with complexHeatmap 1.8.2 or 1.8.0. Then I found some bug in row_annotation in that version. Another issue pushed me to update to R 3.6 then I re-installed the complexHeatmap 2.2.0. However, I found with the same code and matrix, the order of row changed and I can do nothing about it even I set row_dend_reorder = T. But I don't like the new clustering, and there's little solution online.

`
ha = rowAnnotation(foo = anno_barplot(crc_est_score_order$Immune_score, which = 'row'))
Heatmap(t(as.matrix(df_num[,4:269])),
               show_row_names = F,
               show_column_names = F,
               column_title = "TCGA COAD copy number",
               row_title = "ESTIMATE immune score",
               cluster_rows = T,
               cluster_columns = F,
               top_annotation = chr_bar,
               use_raster = TRUE,
               col = col_fun,
               heatmap_legend_param = list(legend_direction = "vertical", title = "Color Key", at = c(-1,-0.3,0.3,1))) + ha
`

This is the previous one with older version.

![image](https://user-images.githubusercontent.com/45670154/78950533-a7f7ba00-7a94-11ea-86e1-84a5f5e7f70e.png)

This is the result in new version with exact same code and data:

![image](https://user-images.githubusercontent.com/45670154/78950707-353b0e80-7a95-11ea-9556-e488e7c6c0e5.png)

Please help, thank you.

Han.

**Comment by jokergoo** [comment]
Can you send me the matrix? The second plot looks strange. The dendrogram should be reordered by default.

**Comment by hjc0818** [comment]
Sure, by entering this code I write down the data frame df_num.

`write.table(df_num, "df_num.txt", quote = F, sep = '\t')`

Note, I used the exact same matrix since I am using R notebook, that's why I still have the original heatmap. The environment has been saved as RData using R 3.5 and I reloaded them into R 3.6. Now I remember that both figure should be plotted under complexHeatmap 2.2.0 since thats why my row_annotation worked. Probably it's affected by R 3.6? 


[df_num.txt](https://github.com/jokergoo/ComplexHeatmap/files/4462513/df_num.txt)

**Comment by hjc0818** [comment]
I tried another dataset, and the clustering is the same trend.

![image](https://user-images.githubusercontent.com/45670154/79017268-89e29600-7b36-11ea-82b7-092467d88f4e.png)

**Comment by jokergoo** [comment]
You were using a very old version of ComplexHeatmap and I don't remember how I set the clustering there.

For the heatmaps, by default, the dendrograms are reordered by the row means, which for your case, since you have both positive and negative values in the matrix, rows which are almost zeros are more likely to be put in the middle of the heatmap.

I cannot reproduce a plot like the one you made with the old version, but following code produces a one which is very similar as yours:

```r
Heatmap(mat2, 
    show_row_names = FALSE, 
    show_column_names = FALSE, 
    show_row_dend = TRUE, 
    show_column_dend = FALSE, 
    clustering_method_rows="ward.D2", 
    row_dend_reorder=rowSums(abs(mat2)
)
```

![image](https://user-images.githubusercontent.com/449218/79730611-5ef40100-82f1-11ea-90fd-223e9c4fe945.png)
