### ISSUE TITLE
margins

### ISSUE THREAD

**Issue by Brawni** [jokergoo/ComplexHeatmap#462]
Hi jokergoo!

Great package I have used it a lot recently...However i'm failing to understand how to set heat map margins? I have the row names which overlap with the legend..

Thank you!

**Comment by jokergoo** [comment]
You can set `row_names_max_width` argument in `Heatmap()` function:

```r
Heatmap(mat, ..., 
    row_names_max_width = max_text_width(rownames(mat), gp = gpar(fontsize = 12))
```

`max_text_width()` returns the maximal width of the row names with specific fontsizes (12 is the default size).
