### ISSUE TITLE
Problem with anno_mark

### ISSUE THREAD

**Issue by storgatan** [jokergoo/ComplexHeatmap#467]
Hi,
thanks for this great heatmap package.
I have run into an issue with anno_mark annotations. It works nicely but when I zoom the plot or export it as pdf the labels are not correctly aligned anymore.

Image 1 shows the output within R-Studio

![img1](https://user-images.githubusercontent.com/60403378/80735468-b9097900-8ade-11ea-8357-70ad94d2ea65.png)

Image 2 shows the corresponding image as exported pdf

![img2](https://user-images.githubusercontent.com/60403378/80735471-b9a20f80-8ade-11ea-8082-de9dee696742.png)

How can I solve this issue?

**Comment by jokergoo** [comment]
The calculation of the positions of the text is affected by the physical size of the graphic device. If you zoom the device, e.g. the plot panel in Rstudio, you need to rerun the code, or you directly use `pdf()` function to save the plot.

**Comment by storgatan** [comment]
Great, thank you!
`pdf()` did the trick.
Thanks again.
