### ISSUE TITLE
Change font family

### ISSUE THREAD

**Issue by email-lhe** [jokergoo/ComplexHeatmap#469]
Hi Zuguang,

Thanks for developing the ComplexHeatmap packages, it helps a lot. I met a problem of altering font family in my heatmap recently. I prefer the font "Times New Roman", and I've tried setting the family = "Times New Roman", but it doesn't work. Also, I tried copying the files relative to font-family in your repository, but it was written in .css, so I can't change the font family by altering the code. Can you help me out? Thanks in advance.

Best,
Liyuan

**Comment by jokergoo** [comment]
The value should be `gpar(fontfamily  = "Times")`?

see link: http://www.cookbook-r.com/Graphs/Fonts/

**Comment by jokergoo** [comment]
or `fontfamily = "serif"`? I don't know much of how to set other font families with R. I always use the default one. You need to search on the internet.

https://www.statmethods.net/advgraphs/parameters.html

**Comment by email-lhe** [comment]
gpar(fontfamily = "Times") works, thanks.
