### ISSUE TITLE
Upset plot margins

### ISSUE THREAD

**Issue by MatDal** [jokergoo/ComplexHeatmap#474]
Hi
very nice tool!
how can I set the external margins of the Upset plot? 
and please the best way to save the plot in pdf file?

Thanks

**Comment by jokergoo** [comment]
You can do:

```r
ht = UpSet(...)
draw(ht, padding = unit(c(1, 1, 1, 1), "cm"))  # 1cm margin on each side
```

**Comment by MatDal** [comment]
Thanks!!!
