### ISSUE TITLE
Aesthetic questions about left_annotation

### ISSUE THREAD

**Issue by kin182** [jokergoo/ComplexHeatmap#476]
I would like to add a barplot as a left row annotation so I used the `left_annotation` function. It went through but I have three aesthetic questions:

Using this example in the vignette,
 
1) How to flip the barplot (bar1) horizontally so 0 is near the heatmap and the barplot looks pointing out instead of pointing in?

2) Mine is a stack barplot instead with three colors in it. How to enable the legends for the colors on the stack barplot ?

3) Is there a way to remove the box around the barplot and just to keep the scale?

![image](https://user-images.githubusercontent.com/25874665/81484441-5872ee00-91fa-11ea-923b-950d56c2e7c2.png)

Thank you so much.

**Comment by jokergoo** [comment]
1. in `anno_barplot()`, set `axis_param = list(direction = "reverse")`.

2. you can refer to #480 

3. in `anno_barplot()` set `border = FALSE`.

**Comment by kin182** [comment]
Wonderful! It works well. Thanks!
