### ISSUE TITLE
How to select and extract submatrix from heatmap?

### ISSUE THREAD

**Issue by CSBioAzim** [jokergoo/ComplexHeatmap#479]
Hi,

I would like to extract the submatrix from the heatmap. Unfortunately, I couldn't find an interactive way of doing that. I was wondering whether can you help me with this?
Looks that in the past there was function selectArea(), but it's not available in the current version of the ComplexHeatmap.

**Comment by jokergoo** [comment]
I've put it back to my to-do list.

#481

**Comment by jokergoo** [comment]
Hi, it is implemented, please install the version 2.5.3 from GitHub.
