### ISSUE TITLE
How to add label key for stacked bar plot

### ISSUE THREAD

**Issue by ajitjohnson** [jokergoo/ComplexHeatmap#480]
Hi

I have a heatmap and I have attached a stacked bar plot to each row of the heatmap as below. I have colored the stacked bar plot however how do I add a key to explain what each color represents?

```
# pheno_prop is a matrix
cols <- brewer.pal(length(colnames(pheno_prop)),"BrBG") 
pheno_p <- rowAnnotation(axis_reverse = anno_barplot(pheno_prop, 
                                                   gp = gpar(fill = cols),
                                                   axis_param = list(direction = "reverse"),
                                                   ))

h1 <- Heatmap(as.matrix(median_expression), col = h1_col, 
             left_annotation = pheno_p,
             show_row_dend = FALSE)
```

Thank you,

Best,
Ajit.

**Comment by jokergoo** [comment]
Legends for the barplot annotations are not automatically generated, you need to manually construct one by `Legend()` function. Check following example:

```r
ha = HeatmapAnnotation(foo = anno_barplot(cbind(1:10, 10:1), 
    gp = gpar(fill = 2:3, col = 2:3)))
m = matrix(rnorm(100), 10)

lgd = Legend(title = "barplot", labels = c("red", "green"), legend_gp = gpar(fill = 2:3))
draw(Heatmap(m, top_annotation = ha), heatmap_legend_list = list(lgd))
```

![image](https://user-images.githubusercontent.com/449218/81650527-54311580-9432-11ea-9a1e-f05a98961134.png)

**Comment by ajitjohnson** [comment]
That works perfect. Thanks a lot, @jokergoo for your quick response.
