### ISSUE TITLE
adding boxplots with expression values to a heatmap

### ISSUE THREAD

**Issue by justannwska** [jokergoo/ComplexHeatmap#482]
I would like to add boxplots (mutation vs no mutation) with expression values to the Heatmap, sort of similar to here  https://jokergoo.github.io/ComplexHeatmap-reference/book/more-examples.html#add-multiple-boxplots-for-single-row

The issue I have while preparing the expression matrices is that the number of mutated vs. not-mutated samples will always defer. Therefore, although I have the same rows (genes), I wouldn't have equal number of columns in the two matrices (mutated vs. not-mutated). Is there a way that ComplexHeatmap can accept NA entries? I wouldn't like to add artificial zero values as then the distribution of the expression values wouldn't be real.

Thanks a lot for help

**Comment by jokergoo** [comment]
Hi, you don't need the two matrices to have the same number of columns. In the following example from the manual:

```r
anno_multiple_boxplot = function(index) {
    pushViewport(viewport(xscale = rg, yscale = c(0.5, nr + 0.5)))
    for(i in seq_along(index)) {
        grid.rect(y = nr-i+1, height = 1, default.units = "native")
        grid.boxplot(m1[ index[i], ], pos = nr-i+1 + 0.2, box_width = 0.3, 
            gp = gpar(fill = "red"), direction = "horizontal")
        grid.boxplot(m2[ index[i], ], pos = nr-i+1 - 0.2, box_width = 0.3, 
            gp = gpar(fill = "green"), direction = "horizontal")
    }
    grid.xaxis()
    popViewport()
}
```

The code inside `for` which is:

```r
        grid.rect(y = nr-i+1, height = 1, default.units = "native")
        grid.boxplot(m1[ index[i], ], pos = nr-i+1 + 0.2, box_width = 0.3, 
            gp = gpar(fill = "red"), direction = "horizontal")
        grid.boxplot(m2[ index[i], ], pos = nr-i+1 - 0.2, box_width = 0.3, 
            gp = gpar(fill = "green"), direction = "horizontal")
```

runs for every rows in the matrix where `m1[ index[i], ]` is the vector for one box and `m2[ index[i], ]` is for the second box, and they don't need to have the same length. You just need to
construct the corect vector for them.
