### ISSUE TITLE
space name of the y-axis and plot

### ISSUE THREAD

**Issue by MatDal** [jokergoo/ComplexHeatmap#483]
How we can increase the space between the name of the y-axis and the plot in Upset barplot?
Thanks

**Comment by jokergoo** [comment]
No, you cannot, but you can first turn off the barplot label by `show_annotation_name = FALSE` and add whatever you want with `decorate_annotation()` function.

**Comment by jokergoo** [comment]
I will give you the example. First you need to update the package from GitHub:

```r
devtools::install_github("jokergoo/ComplexHeatmap")
```

Next code is basically what I mentioned in the last reply:

```r
set.seed(123)
lt = list(a = sample(letters, 5),
          b = sample(letters, 10),
          c = sample(letters, 15))
m = make_comb_mat(lt)
ht = UpSet(m, top_annotation = upset_top_annotation(m, show_annotation_name = FALSE))
draw(ht, padding = unit(c(2, 20, 2, 2), "mm"))
decorate_annotation("intersection_size", {
	grid.text("foo", x = unit(-15, "mm"), rot = 90)
})
```

Note the annotation name for the "Intersection sets" is `intersection_size` and the name for the "Sets" is `set_size`.

![image](https://user-images.githubusercontent.com/449218/81789867-df7adb80-9504-11ea-8a16-3ee66404c0b4.png)
