### ISSUE TITLE
how to match column variables with image annotation?

### ISSUE THREAD

**Issue by YingjieLiScience** [jokergoo/ComplexHeatmap#490]
I referred to examples here https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html#image-annotation, but find there seems no function to match column variables with each image in the image annotation. (the order of the images is fixed but does not change with the column names after clustering). Could you give me a hint? Thanks!

**Comment by jokergoo** [comment]
That was a bug. Now I have fixed it. Thanks for reporting!

```r
# from https://github.com/Keyamoon/IcoMoon-Free
image = sample(dir("~/Downloads/IcoMoon-Free-master/PNG/64px", full.names = TRUE), 10)

m = matrix(rnorm(100), 10)
colnames(m) = paste0("C", 1:10)

Heatmap(m, top_annotation = HeatmapAnnotation(image = anno_image(image))) +

Heatmap(m, top_annotation = HeatmapAnnotation(image = anno_image(image)),
	cluster_columns = FALSE)
```
![image](https://user-images.githubusercontent.com/449218/82607274-d353e580-9bb8-11ea-9b3a-7e1c807c475b.png)

**Comment by YingjieLiScience** [comment]
This works perfectly! Thanks!!
