### ISSUE TITLE
Strsplit error message

### ISSUE THREAD

**Issue by jdriver509** [jokergoo/ComplexHeatmap#491]
Hello, 
I am trying to make an oncoprint, but keep getting an error message "Error in strsplit(x, "\\s*[;:,|]\\s*") : non-character argument". What is odd is that I am able to make an oncoprint for another dataset, and here I am replicating the exact same code, but get the error message when using this dataset. 
Thank you!

**Comment by jokergoo** [comment]
Please also provide some test dataset and the code.

What is your input matrix? The regular expression is applied on the input matrix.
