### ISSUE TITLE
reorder rows within each split portion

### ISSUE THREAD

**Issue by YingjieLiScience** [jokergoo/ComplexHeatmap#493]
Hi, thanks again for this great package. I was wondering if there is a way to re-order the rows within each portion after row_split. 

For example, in the attached plot, how can I re-order "Industry" within each "Region" following the same order of the Industry legend? For now, it is not clear to me how the industries within each region were ordered.  

I read several previous posts, such as #293, but I have not found a solution. 

Thank you for your time and I am looking forward to your advice.

![heatmap_8](https://user-images.githubusercontent.com/40079217/82944021-81b8ab80-9f68-11ea-97bf-f7c7fb03cc79.jpg)

**Comment by jokergoo** [comment]
It is because the rows are clustered.

You can first convert `Industry` as a factor:

```r
Industry = factor(Industry, levels = "Aerospace ... to ... Utilities")
```

Then order the rows in the heatmap

```r
Heatmap(mat, ... row_split = Region, row_order = order(Region, Industry))
```

**Comment by YingjieLiScience** [comment]
Thank you so much, @jokergoo ! This works perfectly.
