### ISSUE TITLE
How to use circular color bar and add summary annotations?

### ISSUE THREAD

**Issue by YiweiNiu** [jokergoo/ComplexHeatmap#495]
Hi Zuguang,

Thank you for developing such a useful tool!

I wonder if I can get a heatmap like the following one using ComplexHeatmap:

![图片](https://user-images.githubusercontent.com/25263399/83120958-4e128880-a104-11ea-8bee-7e5510cef10e.png)

The top color bar is circular, and both rows and columns contain summary information.

Thank you in advance!

Best,
Yiwei

**Comment by jokergoo** [comment]
Hi, sorry I don't quite understand your question. What do you mean by "summary information"? What kind of graphics do you want to draw?

Is it that you want to draw the top annotation by circles? If so, you simply use points annotation (https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html#points-annotation) by turning off the axis and draw the points in big size (`unit(1, "snpc")`).

**Comment by YiweiNiu** [comment]
Thank you for your reply!

Sorry I did not make myself clear. I wanted to generate a plot like this one:

![图片](https://user-images.githubusercontent.com/25263399/83137000-f6cbe280-a11a-11ea-8224-ac932a2db6f8.png)

It is the Figure 2B from this paper: <https://www.cell.com/cancer-cell/fulltext/S1535-6108(19)30571-9>

**Comment by jokergoo** [comment]
The left annotation can be implemented by `anno_block()` by removing the borders and filled colors.

https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html#block-annotation

**Comment by YiweiNiu** [comment]
Thank you for your reply! I would try this.
