### ISSUE TITLE
How to directly color the branches on the cluster of heatmap without dendextend 

### ISSUE THREAD

**Issue by tenlives** [jokergoo/ComplexHeatmap#496]
hi,
 I want to use the methods "clustering_distance_rows,clustering_method_rows", and set  customized colors on the branches of  cluster  ,do not want to use the package  dendextend with hclust, could to tell me how to do it? Thakn you very much !

**Comment by jokergoo** [comment]
`clustering_distance_rows` and `clustering_method_rows` are only for generating the dendrograms, while not for rendering dendrogram like color the edges. You need to use `dendextend` package.

If you are familiar with the structure of a `dendrogram` object, you can manually color every edge by setting the `edgePar` attribute.

**Comment by tenlives** [comment]
> `clustering_distance_rows` and `clustering_method_rows` are only for generating the dendrograms, while not for rendering dendrogram like color the edges. You need to use `dendextend` package.
> 
> If you are familiar with the structure of a `dendrogram` object, you can manually color every edge by setting the `edgePar` attribute.

**Comment by tenlives** [comment]
I want to set the  clustering_distance_rows="spearman",clustering_method_rows="mcquitty",How can I get  the the dendrogram and use dendextend package to color the edges ? Can hclust do it ?

**Comment by jokergoo** [comment]
```r
dend = as.dendrogram(hclust(dist(mat)))
dend = color_branches(dend, ...)
Heatmap(mat, cluster_rows = dend, ...)
```

https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#render-dendrograms

**Comment by tenlives** [comment]
Thank you, while  how to set the  parameter of `hclust `and `dist` to  get  the same result by setting `clustering_distance_rows="spearman",clustering_method_rows="mcquitty" `?

**Comment by jokergoo** [comment]
```r
# I cannot remember whether you need to transport the matrix to calculate the correlation, 
# you need to check
dist_m = as.dist(1 - cor(mat, method = "Spearman"))
dend = as.dendrogram(hclust(dist_m), method = "mcquitty")
```

**Comment by tenlives** [comment]
Thank you very much, there is a another question that  can  the `cell_fun`  contorl the width and height of each cell ?  I want to set each cell with same customized width and height. Can you give me  a simple example ? I am excited to use the package ComplexHeatmap .
