### ISSUE TITLE
anno_mark: "Error in labels2index[labels] : invalid subscript type 'expression'"

### ISSUE THREAD

**Issue by Zepeng-Mu** [jokergoo/ComplexHeatmap#497]
Hi, I am trying to add anno_mark to my heatmap where the labels are expressions.
I can do this by the following code:
```
cellAnno <- rowAnnotation(Gene = anno_mark(at = annoIdx, labels = cell.name))
```
But I got the error message `Error in labels2index[labels] : invalid subscript type 'expression'` when I try to set `labels_gp = gpar(fontsize = 1)` in anno_mark.

Thanks

**Comment by jokergoo** [comment]
Please also attach the test datasets and the code.

**Comment by Zepeng-Mu** [comment]
Just a very simple toy example:

```
m <- matrix(c(log2(1:3), log10(1:3)), nrow = 2, byrow = T)
rowAnno <- rowAnnotation(lab = anno_mark(at = 1:2, labels = c(expression(log[2]), expression(log[10]))))
Heatmap(m, right_annotation = rowAnno)
```

[![Screen-Shot-2020-05-28-at-14-04-27.png](https://i.postimg.cc/13b41V0B/Screen-Shot-2020-05-28-at-14-04-27.png)](https://postimg.cc/fVjMxLrS)

```
rowAnno <- rowAnnotation(lab = anno_mark(at = 1:2,
                                         labels = c(expression(log[2]), expression(log[10])),
                                         labels_gp = gpar(fontsize = 1)))

Heatmap(m, right_annotation = rowAnno)
```
Then I got `Error in labels2index[labels] : invalid subscript type 'expression'` and the heatmap looks like
[![Screen-Shot-2020-05-28-at-14-03-13.png](https://i.postimg.cc/nzJzC8PQ/Screen-Shot-2020-05-28-at-14-03-13.png)](https://postimg.cc/d75vxfvq)

**Comment by jokergoo** [comment]
Hi, that was a bug and now I have fixed it.

By the way, you can also use the following code (which uses **gridtext** package for rendering) for adding simple math symbols:

```r
rowAnno <- rowAnnotation(lab = anno_mark(at = 1:2,
                                         labels = gt_render(c("_log_<sub>2</sub>", "_log_<sub>10</sub>")),
                                         labels_gp = gpar(fontsize = 16)))

Heatmap(m, right_annotation = rowAnno)
```

![image](https://user-images.githubusercontent.com/449218/83507411-ce503980-a4c8-11ea-94d3-4d078b711fe1.png)

**Comment by Zepeng-Mu** [comment]
Thanks!
