### ISSUE TITLE
anno_zoom() with word cloud

### ISSUE THREAD

**Issue by lucolotto** [jokergoo/ComplexHeatmap#498]
Hi there. 
I have an heat map which has been divided in 8 clusters and I have performed over-representation analysis on each cluster. I would like to add an `anno_zoom()` on the right of the heat map with the word cloud derived from enrichment analyses. 
The annotation I would like to make is exactly as the one showed at the bottom of this page: https://github.com/jokergoo/simplifyEnrichment

I am not able to find the code/understand how to make the annotation... Any help will be mostly welcome!
Thanks in advance
All the best 
Luca

**Comment by jokergoo** [comment]
You can check the following functions:

https://github.com/jokergoo/simplifyEnrichment/blob/4af412406eb6538d27e6261ca2d82da1816fac11/R/word_count.R#L113

https://github.com/jokergoo/simplifyEnrichment/blob/4af412406eb6538d27e6261ca2d82da1816fac11/R/plot.R#L32

**Comment by lucolotto** [comment]
Thanks for the reply @jokergoo! Your library is amazing! 
I had a look at the functions but I do not understand how to integrate them in the final plot... I mean, I got the first one that produces the world cloud, but how can I then integrate the word cloud in the heat map? 
Could you please write down some code with an example of how to do it?

Thanks 
Luca

**Comment by jokergoo** [comment]
I just wrote a post on it. You can check https://jokergoo.github.io/2020/05/31/word-cloud-as-heatmap-annotation/

**Comment by lucolotto** [comment]
Thanks jokergoo! Amazing post and very detailed, much appreciated!

Luca
