### ISSUE TITLE
simpleUnit requires R-4.0.0?

### ISSUE THREAD

**Issue by jmw86069** [jokergoo/ComplexHeatmap#499]
I was excited to try the interactive ComplexHeatmap, but it fails on R-3.6.2, with ComplexHeatmap version 2.5.3, and grid version 3.6.1.

```Error: `pos` should be a simpleUnit.```

From what I can tell (brief digging) the new class in grid `"simpleUnit"` is available only for R-4.0.0.

I was able to find the source of the issue in `selectPosition()`, which will be similar in `selectArea()`.

This code is from your blog post:
```r
library(ComplexHeatmap);

set.seed(123)
mat1 <- matrix(rnorm(100), 10)
rownames(mat1) <- colnames(mat1) = paste0("a", 1:10)
mat2 <- matrix(sample(letters[1:10], 100, replace = TRUE), 10)
rownames(mat2) <- colnames(mat2) = paste0("b", 1:10)

ht_list <- Heatmap(mat1, name = "mat_a", row_km = 2, column_km = 2) +
   Heatmap(mat2, name = "mat_b")
ht_list <- draw(ht_list);
```

This code fails for `selectPosition()`:
```r
# Calling selectPosition() with pos defined tests for simpleUnit
pos_test <- grid::unit(c(3, 3), "mm");
# if testing on R-4.0.0 you can force the issue
# by removing simpleUnit class attribute
# attr(pos_test, "class") <- c("unit");
class(pos_test);
# "unit"
selectPosition(ht_list, pos=pos_test); # Error
```

This code succeeds for `selectPosition()`:
```r
# add simpleUnit to the class attribute so it passes this test
pos_test_su <- pos_test;
attr(pos_test_su, "class") <- c("unit", "simpleUnit");
class(pos_test_su);
# "unit" "simpleUnit"
selectPosition(ht_list, pos=pos_test_su); # No error
```
The question is whether you want to allow R-3.6.2, or require R-4.0.0 for this feature. :) I defer to you. If you want to allow R-3.6.2, there may be workarounds you have thought of, again I defer to you.

Thanks so much for this feature, looking forward to using it!

**Comment by jokergoo** [comment]
Hi, it is because I was working on R-4.0 when I implement these functions.

And yes, now I only test them with "unit" class for R < 4.0.

You can update on GitHub.

**Comment by jmw86069** [comment]
I updated from Github and it works great! Thanks so much!

I'll close the thread as it is resolved for me, I hope that's okay.
