### ISSUE TITLE
Set custom row labels?

### ISSUE THREAD

**Issue by kcha** [jokergoo/ComplexHeatmap#5]
Instead of setting the row labels using `rownames()`, is it possible to supply a custom list of row labels to `Heatmap()`? In other words, I am looking for something similar to the `labRow` argument in `heatmap.2()`. The reason is that my row labels have duplicate names and consequently I cannot use `rownames()` on my data frame.

**Comment by jokergoo** [comment]
Then you can add a row annotation which only contains text.

```
mat = matrix(rnorm(100), 10)
labels = rep(c("A", "B"), 5)

ht_list = Heatmap(mat) + 
rowAnnotation(labels = anno_text(labels, which = "row"), 
	width = max(grobWidth(textGrob(labels)))) # you need to calculate the width by hand

ht_list
draw(ht_list, gap = unit(1, "cm"))  # or increase gap between heatmap and text annotation
```

**Comment by kcha** [comment]
Thanks!
