### ISSUE TITLE
Rotating the title of a vertical annot_point

### ISSUE THREAD

**Issue by stemangiola** [jokergoo/ComplexHeatmap#500]
Hello, I would like to rotate the title of a vertical annot_point of 90 degrees (yellow highlight)

<img src="https://user-images.githubusercontent.com/7232890/83474877-6ef62780-a4d0-11ea-8825-1d3781905b12.png" height="500">

**Comment by jokergoo** [comment]
Currently there is no argument that directly rotate the labels. But you first turn off the label and later add whatever you want by `decorate_annotation()` function:

```r
rowAnnotationi(foo = anno_points(...), show_annotation_name = FALSE) + ...
# after the plot is drawn
decorate_annotation("foo", {
    grid.text("foo", x = 0.5, y = unit(-1, "cm"), rot = 90, just = "right")
})
```
If the label is too long and is out of the page, you need to manually adjust the padding of the whole plot:

```r
ht = rowAnnotationi(foo = anno_points(...), show_annotation_name = FALSE) + ...
draw(ht, padding = unit(c(10, 2, 2, 2), "mm")) # bottom with 10 mm padding
# after the plot is drawn
decorate_annotation("foo", {
    grid.text("foo", x = 0.5, y = unit(-1, "cm"), rot = 90, just = "right")
})
```

**Comment by stemangiola** [comment]
Please update issue if anything more straightforward comes out.
