### ISSUE TITLE
How to use a mathematical expression as a name of HeatmapAnnotation

### ISSUE THREAD

**Issue by junghoon-shin** [jokergoo/ComplexHeatmap#501]
Currently it doesn't seem to be supported. Is there any way to do it?

**Comment by jokergoo** [comment]
If you install version 2.5.3, there is a new argument `annotation_label` that you can set with a **gridtext** rendered text where you can set simple math symbols:

```r
m = matrix(rnorm(100), 10)
Heatmap(m, top_annotation = HeatmapAnnotation(foo = 1:10, 
	annotation_label = gt_render("_x_<sub>1</sub> + _y_<sup>2</sup>")))
```

![image](https://user-images.githubusercontent.com/449218/83507789-533b5300-a4c9-11ea-9a98-a238e6e5b7af.png)

**Comment by jokergoo** [comment]
For more detailed explanation, you can refer to https://jokergoo.github.io/ComplexHeatmap-reference/book/other-tricks.html#integrate-with-gridtext-package
