### ISSUE TITLE
How to zoom in a certain portion of the axis of anno_density()

### ISSUE THREAD

**Issue by junghoon-shin** [jokergoo/ComplexHeatmap#502]
Hi @jokergoo , Thank you for this great package. Is there any way to zoom in to a certain portion of the axis of `anno_density()` plots? For example in the figure below,
![image](https://user-images.githubusercontent.com/34851941/83595292-8b5f9600-a59c-11ea-9fc6-2af05ab8c51a.png)
I want to restrict the range of the x-axis of the row annotation plots to [0, 0.05] without affecting the actual shape of the density distribution curve (like coord_cartesian(xlim=c(0,0.05)) in ggplot2 package). Can I do this?

**Comment by jokergoo** [comment]
Good suggestion! I will support it.

**Comment by jokergoo** [comment]
Now you can set `xlim` argument in `anno_density()`.

When `xlim` is not set:

![image](https://user-images.githubusercontent.com/449218/84016964-55485a80-a97e-11ea-8754-f7a09afcf22b.png)

And when `xlim` is set:

![image](https://user-images.githubusercontent.com/449218/84016987-5f6a5900-a97e-11ea-9064-a79e0d4c4cba.png)

**Comment by junghoon-shin** [comment]
Great! Thank you very much!
