### ISSUE TITLE
changing font size of legend tick labels

### ISSUE THREAD

**Issue by fedshyvana** [jokergoo/ComplexHeatmap#505]
Hi, what is the currently supported method for changing the font size of the heatmap legend?
I tried passing  heatmap_legend_param to Heatmap, and while I was able to change the font size of the legend title through title_gp = gpar(fontsize = 15), I did not find a viable way to change the font size of the text under the colorbar (tick labels). Thanks!

**Comment by jokergoo** [comment]
It is in `legend_gp = gpar(fontsize = 15)`.

**Comment by fedshyvana** [comment]
Thanks for the quick reply! 
This is what I entered:
`heatmap_legend_param = list(title = 'Expression Level', 
                                         at = seq(0, 1, 0.1), direction = 'horizontal', 
                                         labels = c(0, '', '', '', '',0.5,'','','','', 1),
                                         color_bar = 'continuous',
                                         title_gp = gpar(fontsize = 15),
                                         legend_gp = gpar(fontsize = 20),
                                         legend_height = unit(2, 'in'),
                                         legend_width = unit(2, 'in'),
                                         title_position="topcenter")`

and as a result i got:
<img width="410" alt="Screen Shot 2020-06-07 at 11 51 17 AM" src="https://user-images.githubusercontent.com/39780468/83973561-421d8800-a8b5-11ea-90dc-b956642d16e7.png">

As you can see the fontsize on the colorbar ticks is smaller than the legend title and adjusting legend_gp does not seem to have a visible effect. Thoughts? Thanks a lot once again!

**Comment by jokergoo** [comment]
Ah, I am sorry that I remembered wrong. 

It should be the `labels_gp` argument.

**Comment by fedshyvana** [comment]
that worked! thanks!
