### ISSUE TITLE
Custom Heatmap Row Labels

### ISSUE THREAD

**Issue by FireBorn123** [jokergoo/ComplexHeatmap#506]
Greetings! 

I was wondering if it is possible to add a table along the height of the heatmap to depict multiple pieces of information about the column? For instance, I want to show the gene locus number in one column, the gene name in a second, and what it is identified as in a different organism in a third column. I have gone through the how to web pages for the ComplexHeatmap package, and I saw nothing. Is what I am suggesting possible for your package? If not, do you have any suggestions as to how I might be able to implement this?

Thank you very much for your time!

**Comment by jokergoo** [comment]
This is an interesting comment!

It can be implemented by setting multiple `anno_text()` where each `anno_text()` corresponds to one column in your table. 

Let me see how easy it is to implement it (let's call it `anno_table()`) or is there any other packages that draw tables I can directly use.

**Comment by FireBorn123** [comment]
Thanks for the very quick response! The following is my current code. Where should I be inserting the anno_text/anno_table containers?

```{r}
InCellTextSize = 7.75
RowLabelTextCell = 9

NameDataFrame = data.frame(TnT_List_Analysis_Shrunk2$locus, TnT_List_Analysis_Shrunk2$Gene)
NameDataArray = array(data = c(TnT_List_Analysis_Shrunk2$locus, TnT_List_Analysis_Shrunk2$Gene), dim = c(10, 2))


HeatmapTest <- Heatmap(
        matrix = mat, 
        cluster_rows = color_branches(as.dendrogram(hclust(dist(mat, method = "canberra")), method = "complete"), k = 5),
        row_split = 5,
        row_gap = unit(1.75, 'mm'),
        border = FALSE, 
        
        row_labels = TnT_List_Analysis_Shrunk2$locus,
        row_title = "Transcribed Gene Loci", 
        row_names_gp = gpar(fontsize = RowLabelTextCell),
        
        
        cell_fun = function(j, i, x, y, width, height, fill) {
          if(mat[i, j] < 0 || mat[i, j] > 0)
            grid.text(sprintf("%.1f", mat[i, j]), x, y, gp = gpar(fontsize = InCellTextSize))},
        
        
        column_dend_reorder = FALSE, 
        column_order = ColOrder, 
        column_names_rot = 45,
        
        
        column_title = "Conditions tested (CF39S vs CF39)", 
        column_title_side = "bottom",
        
        
      #  left_annotation = rowAnnotation(anno_text(TnT_List_Analysis_Shrunk2$locus), anno_text(TnT_List_Analysis_Shrunk2$Gene)),
        row_dend_width = unit(3.1, "cm"),
        
        
        col = colorSetRedBlue,
        height = unit(10, 'cm')
        , raster_quality = 10
        )
```

Alternatively, did you figure out any way to work with a table directly? 

Thanks again for all your help!

**Comment by jokergoo** [comment]
```r
  left_annotation = rowAnnotation(anno_text(TnT_List_Analysis_Shrunk2$locus), anno_text(TnT_List_Analysis_Shrunk2$Gene)),
        row_dend_width = unit(3.1, "cm"),
```

This is basically what I thought, but there are no borders for the cells in the table, but is can easily solved by add support in `anno_text()`. 

To make this `anno_table()` more flexible, it should allow more styles, such as in https://cran.r-project.org/web/packages/gridExtra/vignettes/tableGrob.html

**Comment by FireBorn123** [comment]
Thanks! Unfortunately I am getting this error...

Error: It seems you are putting only one argument to the function. If it is a simple vector annotation or a function annotation
(e.g. anno_*()), specify it as HeatmapAnnotation(name = value). If it is a data frame annotation, specify it as
HeatmapAnnotation(df = value)

Sorry about all the questions.... I did just check my version (and reinstalled from github), so my version of complex heatmap is 2.5.3. Thanks again

**Comment by jokergoo** [comment]
You should give argument names to the two anno_text(), any name is ok.

**Comment by FireBorn123** [comment]
Thank you very much, that almost works.... The last issue that i am trying to work out is that although I am now able to have multiple columns, the second and third column are overlapping with the legend if on the right side, or the actual heatmap if on the left... Is there any way to manually alter the spacing for the legend? I would love to move it out a little and move the legend to be more central to the heatmap... 

![image](https://user-images.githubusercontent.com/25887201/84087019-78870000-a9a6-11ea-8637-c4e238086fc4.png)

Thanks for all your help today, and I think this is the last issue that I am having!

**Comment by jokergoo** [comment]
Are these row names? You can set the argument `row_names_max_width = max_text_width(rownames(mat), gp = gpar(fontsize = ...))`

**Comment by FireBorn123** [comment]
This is my current code...
```R
HeatmapTest <- Heatmap(
        matrix = mat, 
        cluster_rows = color_branches(as.dendrogram(hclust(dist(mat, method = "canberra")), method = "complete"), k = 5),
        row_split = 5,
        row_gap = unit(1.75, 'mm'),
        border = FALSE, 
        
        show_row_names = TRUE,
        row_labels = TnT_List_Analysis_Shrunk2$PAO1_ID,
        
        
       row_names_max_width = unit(50, "mm"), #Does not appear to be doing anything
        right_annotation = rowAnnotation(
                                        Col1 = anno_text(TnT_List_Analysis_Shrunk2$locus, location = unit(2, "mm"), gp = gpar(fontsize = RowLabelTextCell)), 
                                        Col2 = anno_text(TnT_List_Analysis_Shrunk2$Gene, location = unit(7, "mm"), gp = gpar(fontsize = RowLabelTextCell))#,
                                        #Col3 = anno_text(TnT_List_Analysis_Shrunk2$PAO1_ID, location = unit(9, "mm"), gp = gpar(fontsize = RowLabelTextCell))#,
                                        ),
        
        
        row_title = "Transcribed Gene Loci", 
        row_names_gp = gpar(fontsize = RowLabelTextCell),
        
        
        cell_fun = function(j, i, x, y, width, height, fill) {
          if(mat[i, j] < 0 || mat[i, j] > 0)
            grid.text(sprintf("%.1f", mat[i, j]), x, y, gp = gpar(fontsize = InCellTextSize))},
        
        
        column_dend_reorder = FALSE, 
        column_order = ColOrder, 
        column_names_rot = 45,
        
        
        column_title = "Conditions tested (CF39S vs CF39)", 
        column_title_side = "bottom",
        
        
        row_dend_width = unit(3.1, "cm"),

        
        col = colorSetRedBlue,
        height = unit(10, 'cm')
        , raster_quality = 10
        )
```
I do want to have the one lane as the first.... I have tried eliminating row_labels entirely and just go off of the right_annotation option, and the best I can have is most of the annotations overlapping the second column of textof the annotations being covered by the legend.... Additionally, I attempted various combinations of right_annotation  and row names, and the code above is what will give the column order that i want, but it apparently at the cost of overlapping with the second column... Below is what i currently have with this code... row_names_max_width = unit(50, "mm") does not appear to be doing anything in my code, an I can change the width to unreasonably large numbers and not see any change...

![image](https://user-images.githubusercontent.com/25887201/84177911-d36d3580-aa40-11ea-985e-e8acc8f74691.png)

Any thoughts? Thanks!

**Comment by jokergoo** [comment]
Can you also attach the two objects `mat` and `TnT_List_Analysis_Shrunk2`?

I guess it is due to the value of `location` in `anno_text()`.

**Comment by FireBorn123** [comment]
Attach them to what?

**Comment by jokergoo** [comment]
I need the values of `mat` and `TnT_List_Analysis_Shrunk2` so that I can run your code. You can paste the output of 

```r
dump("mat", "")
```

and

```r
dump("TnT_List_Analysis_Shrunk2", "")
```

**Comment by FireBorn123** [comment]
dump("mat", "") gives the following:

mat <-
structure(c(0, -2.105652506, 1.366560024, 1.320418416, 1.6138994, 
0, 1.557287018, 1.847775948, 0, 0, 0, 0, 1.738802882, 0, 0, 3.359076905, 
1.712704704, 2.140210451, 0, 0, 1.488370416, 0, 1.421003191, 
0, 0, 0, 0, 2.338665471, 1.384923723, 1.43250211, 1.607907451, 
0, 2.478870309, 2.21533843, 0, 0, 0, 3.877744448, 0, 1.658365519
), .Dim = c(10L, 4L), .Dimnames = list(c("PROKKA_06325_sense", 
"PROKKA_06328_antis", "PROKKA_06333_sense", "PROKKA_06334_sense", 
"PROKKA_06338_sense", "PROKKA_06339_antis", "PROKKA_06339_sense", 
"PROKKA_06340_sense", "PROKKA_06342_sense", "PROKKA_06345_sense"
), c("FoldChange_25vs29", "FoldChange_25vs33", "FoldChange_25vs37", 
"FoldChange_25vs41")))

And dump("TnT_List_Analysis_Shrunk2", "") gives:
TnT_List_Analysis_Shrunk2 <-
structure(list(locus = c("PROKKA_06325_sense", "PROKKA_06328_antis", 
"PROKKA_06333_sense", "PROKKA_06334_sense", "PROKKA_06338_sense", 
"PROKKA_06339_antis", "PROKKA_06339_sense", "PROKKA_06340_sense", 
"PROKKA_06342_sense", "PROKKA_06345_sense"), FoldChange_25vs29 = c(NA, 
-2.105652506, 1.366560024, 1.320418416, 1.6138994, NA, 1.557287018, 
1.847775948, NA, NA), FoldChange_25vs33 = c(NA, NA, 1.738802882, 
NA, NA, 3.359076905, 1.712704704, 2.140210451, NA, NA), FoldChange_25vs37 = c(1.488370416, 
NA, 1.421003191, NA, NA, NA, NA, 2.338665471, 1.384923723, 1.43250211
), FoldChange_25vs41 = c(1.607907451, NA, 2.478870309, 2.21533843, 
NA, NA, NA, 3.877744448, NA, 1.658365519), Gene = c("mucD_2", 
"wspR_8", "n/a", "n/a", "clpB_5", "n/a", "n/a", "n/a", "n/a", 
"n/a"), Product = c("serine protease MucD precursor", "TdcA", 
"YfdX protein", "YfdX protein", "ClpB protein", "molecular chaperone", 
"molecular chaperone", "putative helicase", "hypothetical protein", 
"integrase core domain-containing protein"), PAO1_ID = c("N/A", 
"N/A", "N/A", "N/A", "PA0459 like protein", "N/A", "N/A", "N/A", 
"N/A", "N/A"), `Protein Description` = c("N/A", "N/A", "N/A", 
"N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A")), class = c("spec_tbl_df", 
"tbl_df", "tbl", "data.frame"), row.names = c(NA, -10L), spec = structure(list(
    cols = list(locus = structure(list(), class = c("collector_character", 
    "collector")), `CF39 FC 25vs29` = structure(list(), class = c("collector_double", 
    "collector")), `CF39 FC 25vs33` = structure(list(), class = c("collector_double", 
    "collector")), `CF39 FC 25vs37` = structure(list(), class = c("collector_double", 
    "collector")), `CF39 FC 25vs41` = structure(list(), class = c("collector_double", 
    "collector")), gene = structure(list(), class = c("collector_character", 
    "collector")), product = structure(list(), class = c("collector_character", 
    "collector")), `PAO1 ID (Pseudomonas DB Protein search)` = structure(list(), class = c("collector_character", 
    "collector")), `Protein Description` = structure(list(), class = c("collector_character", 
    "collector"))), default = structure(list(), class = c("collector_guess", 
    "collector")), skip = 1), class = "col_spec"))

Thank you soo much for all you help!

An additional snippit of code that I have above the heatmap function is the following:

```R
```{r}
colorSetRedBlue <- colorRamp2(c(-10, 0, 10), c(rgb(0, 114/255, 178/255), "white", rgb(213/255, 94/255, 0))) #First color is Blue and second is Vermillion from the Nature Colorblind palette
ColOrder = order(as.numeric(gsub("FoldChange_", "", colnames(mat))))

row_dend = as.dendrogram(hclust(dist(mat, method = "maximum")), method = "complete")
row_dend = color_branches(row_dend, k = 4) # `color_branches()` returns a dendrogram object

split = data.frame(cutree(hclust(dist(mat, method = "maximum")), h=4))

```

**Comment by jokergoo** [comment]
I think it is better to put the row labels also as a text annotation:

```r
Heatmap(
        matrix = mat, 
        cluster_rows = color_branches(as.dendrogram(hclust(dist(mat, method = "canberra")), method = "complete"), k = 5),
        row_split = 5,
        row_gap = unit(1.75, 'mm'),
        border = FALSE, 
        
        show_row_names = FALSE,
        
        right_annotation = rowAnnotation(
        	label = anno_text(TnT_List_Analysis_Shrunk2$PAO1_ID, gp = gpar(fontsize = RowLabelTextCell)),
            Col1 = anno_text(TnT_List_Analysis_Shrunk2$locus,  gp = gpar(fontsize = RowLabelTextCell)), 
            Col2 = anno_text(TnT_List_Analysis_Shrunk2$Gene, gp = gpar(fontsize = RowLabelTextCell)),
            gap = unit(2, "mm")

            )
        
)
```
![image](https://user-images.githubusercontent.com/449218/84379776-a9557800-abe6-11ea-92be-ae47510fbcd3.png)

**Comment by jokergoo** [comment]
The problem of your code is the setting of `location`

```r
Col1 = anno_text(TnT_List_Analysis_Shrunk2$locus, location = unit(2, "mm"), gp = gpar(fontsize = RowLabelTextCell)), 
Col2 = anno_text(TnT_List_Analysis_Shrunk2$Gene, location = unit(7, "mm"), gp = gpar(fontsize = RowLabelTextCell))#,
```

If the location is set to `unit(7, "mm")`, the width should also be added with 7mm.

Normally `location` is not set like that. It is normally used with `just`, e.g.

```r
location = unit(1, "npc"), just = "right"  #align to the right
```

or 

```r
location = unit(0, "npc"), just = "left"  # align to the left
```

**Comment by FireBorn123** [comment]
Perfect! Thank you very much for all the help with your package! That looks perfect! And thank you for the explanation, it makes sense (I think)!
