### ISSUE TITLE
Using annotations_decorations from a function

### ISSUE THREAD

**Issue by faustovrz** [jokergoo/ComplexHeatmap#508]
HI,
I am not well versed in grid, so I could not fix this problem by myself.  I am doing an UpSet plot and I wanted to add bar numbers to the top annotation.   I used a decorate_annotation with grid_text:

```
set.seed(1234567)
lt = list(a = sample(letters, 5),
          b = sample(letters, 10),
          c = sample(letters, 15),
          d = sample(letters, 20))
m = make_comb_mat(lt, mode = "intersect")

sorter <-  data_frame(name   = comb_name(m),
            degree = comb_degree(m),
            size   = comb_size(m))
sorted <- with(sorter, sorter$name[order(-degree,-size)])

# quartz()
UpSet(m)
decorate_annotation("intersection_size", {
  grid.text(label = comb_size(m)[sorted],
            x= 1:dim(m)[2],
            y = comb_size(m)[sorted] + 1,
            default.units = "native",
            draw= TRUE)})
Sys.sleep(5)
dev.off()

add_numbers <- function(m, s){
  decorate_annotation("intersection_size", {
    grid.text(label = comb_size(m)[s],
              x= 1:dim(m)[2],
              y = comb_size(m)[s] + 1,
              default.units = "native",
              gp = gpar(col = "red"),
              draw= TRUE)})              
}

UpSet(m)
add_numbers(m,sorted)
Sys.sleep(5)
dev.off()

upset_numbers <- function(m,s){
    UpSet(m)
    add_numbers(m,s)
  }

upset_numbers(m,sorted)
```

It works well while I use it in the body of an R script. However, if I put the decorate_annotation inside a function (add_numbers) and call it from a second function (upset_numbers) it will stop the plot from being made. It does not find the Viewport for the annotation with the following error:

` Error in grid.Call.graphics(C_downviewport, name$name, strict) : 
  Viewport 'annotation_intersection_size_1' was not found `

How could I make `upset_numbers(m,sorted)` to work?

**Comment by jokergoo** [comment]
Hi, change to 

```r
upset_numbers <- function(m,s){
    draw(UpSet(m)) ### <-- Here
    add_numbers(m,s)
  }
```

The thing is since `UpSet()` is called not in an interactive environment, you need to use `draw()` to explicitly make the plot.

**Comment by faustovrz** [comment]
Thank you so much!! That fixed it.
