### ISSUE TITLE
Plot Margin Insufficient If Axis Labels Rotated

### ISSUE THREAD

**Issue by DarioS** [jokergoo/ComplexHeatmap#509]
Could the default width be calculated to include the axis labels if they are at 45 degrees?

![image](https://user-images.githubusercontent.com/631218/84349812-75388200-abfb-11ea-9d94-49c6d77a29f7.png)
OSCC_1-P is cut off the plot area and tinkering with `width` is necessary and there's no single value of it that works nicely if you shrink the width of the plot area.

**Comment by jokergoo** [comment]
No, it cannot be calculated automatically, but you can control the space on the left side by:

```r
ht = Heatmap(...)
draw(ht, padding = unit(c(2, 10, 2, 2), "cm"))  # order is bottom, left, top and right
```
