### ISSUE TITLE
Keeping rowAnnotations in place after row_km

### ISSUE THREAD

**Issue by jackbibby1** [jokergoo/ComplexHeatmap#512]
Hi.

Thanks for a great package. 

I'm struggling to figure out how to keep rowAnnotations in the correct place when using row_km. For example, using:
```
row_an <- HeatmapAnnotation(Genes = anno_mark(at = ex_mat[rownames(ex_mat) %in% genes, ]$num,
                                          labels = rownames(ex_mat[rownames(ex_mat) %in% genes, ]),
                                          labels_gp = gpar(fontsize = 7),
                                          link_width = unit(2.5, "mm"),
                                          padding = unit(0.5, "mm")),
                        which = "row")
ht <- Heatmap(df_all_scaled, name = "Z-score",
              border = T, 
              show_row_names = F, show_column_names = F,
              rect_gp = gpar(col = "white", lwd = 0.01),
              right_annotation = row_an)
ht <- draw(ht)
```
Gives correct labelling of the Heatmap:
![image](https://user-images.githubusercontent.com/59352321/84599928-838dd480-ae6d-11ea-94e6-3cdbd511fde0.png)

However, if I call row_km in the Heatmap like this:
```
row_an <- HeatmapAnnotation(Genes = anno_mark(at = ex_mat[rownames(ex_mat) %in% genes, ]$num,
                                          labels = rownames(ex_mat[rownames(ex_mat) %in% genes, ]),
                                          labels_gp = gpar(fontsize = 7),
                                          link_width = unit(2.5, "mm"),
                                          padding = unit(0.5, "mm")),
                        which = "row")
ht <- Heatmap(df_all_scaled, name = "Z-score",
              border = T, 
              show_row_names = F, show_column_names = F,
              rect_gp = gpar(col = "white", lwd = 0.01),
              right_annotation = row_an,
              row_km = 11)
ht <- draw(ht)
```
The labels are there, but in the incorrect place:
![image](https://user-images.githubusercontent.com/59352321/84600002-1e86ae80-ae6e-11ea-9045-55551fe06dcc.png)

I am assuming this is because the row_km call alters the row ordering? Would you know a way to get around this?

Thanks a lot
Jack

**Comment by jokergoo** [comment]
Hi, I saw the rows for the labels are different for the two plots. When you specify `anno_mark`:

```r
anno_mark(at = ex_mat[rownames(ex_mat) %in% genes, ]$num,
    labels = rownames(ex_mat[rownames(ex_mat) %in% genes, ]),
```

does `ex_mat` have the same row order as `df_all_scaled`? What is in `num`? Note the value in `at` should correspond to the original order in `df_all_scaled`, which is, if `at` has a value of 10, it corresponds to the 10th row in `df_all_scaled`.

**Comment by jackbibby1** [comment]
Hi. Apologies, `ex_mat` is exactly the same as `df_all_scaled`, but with an extra column called "num" that is created by `1:nrow(ex_mat)`, which is what I'm extracting in the `at =` call. I'll use `ex_mat` for all examples here now, so it's more clear. The number given to `at` from `$num` corresponds to the gene that I want to extract in the data, in order of row -- e.g. if I run:

```
ex_mat[ex_mat$num %in% ex_mat[rownames(ex_mat) %in% genes, ]$num, ]
```
I get:
```
Gene   Sample1    Sample2     Sample3     Sample4     num
TCF7  -0.70050965 -0.3069709 -0.96422456 -0.402919679  80
IRF4   0.96879204 -1.2541580  0.36439640 -0.308349820  83
BACH2  0.06171544 -0.6480214 -0.53064860 -1.101001089  94
PRDM1  0.60340748  0.5274568  1.10903355  0.901855408  95
FOXP3 -0.27977616 -0.4014279 -0.10655058 -0.344344024 118
MYC    1.10316518 -1.2085590  0.06698918 -1.175987261 126
GATA3  2.18608119 -0.1105755  0.11120083 -0.164688145 156
FOXO1 -0.39417048 -0.7709534 -1.07506376 -0.313628836 184
IRF8  -0.39000885 -0.5151953 -0.44754725 -0.523034476 220
IRF3  -0.69488776 -0.1354414 -1.14978294  0.859474238 303
TBX21  0.29856367 -0.8585906  0.13646421 -0.001598893 325
```

So, in a tidier way... If I use the `ex_mat` in the Heatmap, it also gives the incorrect labelling when `row_km` is used:
```
row_an <- HeatmapAnnotation(Genes = anno_mark(at = ex_mat[rownames(ex_mat) %in% genes, ]$num,
                                          labels = rownames(ex_mat[rownames(ex_mat) %in% genes, ]),
                                          labels_gp = gpar(fontsize = 7),
                                          link_width = unit(2.5, "mm"),
                                          padding = unit(0.5, "mm")),
                        which = "row")
ht <- Heatmap(ex_mat[,-ncol(ex_mat)], name = "Z-score",
              border = T, 
              show_row_names = F, show_column_names = F,
              rect_gp = gpar(col = "white", lwd = 0.01),
              right_annotation = row_an,
              row_km = 11)
ht <- draw(ht)
```

There may be an easier way to specify `at` and `labels`? I just haven't figure it out yet.

Thanks a lot

**Comment by jackbibby1** [comment]
Or as a simpler example using a subset of the data:

```
head(mat)
          Sample1     Sample2    Sample3 num
CAMTA1 -1.9976747 -0.05094395  0.7325155   1
PRDM2   0.4239053 -1.65249652 -0.9733542   2
SPEN   -2.0846656 -0.81096573  0.4647131   3
RUNX3  -1.6477824 -1.06481430 -1.4967173   4
GMEB1  -1.4885431 -0.64282476  1.5206949   5
RLF    -0.6797766 -1.72551607  0.1829867   6
```
If I run:
```
row_an <- HeatmapAnnotation(Genes = anno_mark(at = mat[rownames(mat) %in% genes, ]$num,
                                              labels = rownames(mat[rownames(mat) %in% genes, ]),
                                              labels_gp = gpar(fontsize = 7),
                                              link_width = unit(2.5, "mm"),
                                              padding = unit(0.5, "mm")),
                            which = "row")
ht <- Heatmap(mat[,-ncol(mat)], name = "Z-score",
              border = T, 
              show_row_names = T, show_column_names = T,
              rect_gp = gpar(col = "white", lwd = 0.01), row_names_gp = gpar(fontsize = 7),
              right_annotation = row_an,
              row_km = 3)
ht <- draw(ht)
```
It's correct in the labels:
![image](https://user-images.githubusercontent.com/59352321/84602408-15eaa400-ae7f-11ea-801c-2dba52bf92c1.png)

But if I add `row_km`, the labels are in the incorrect position:
```
row_an <- HeatmapAnnotation(Genes = anno_mark(at = mat[rownames(mat) %in% genes, ]$num,
                                              labels = rownames(mat[rownames(mat) %in% genes, ]),
                                              labels_gp = gpar(fontsize = 7),
                                              link_width = unit(2.5, "mm"),
                                              padding = unit(0.5, "mm")),
                            which = "row")
ht <- Heatmap(mat[,-ncol(mat)], name = "Z-score",
              border = T, 
              show_row_names = T, show_column_names = T,
              rect_gp = gpar(col = "white", lwd = 0.01), row_names_gp = gpar(fontsize = 7),
              right_annotation = row_an,
              row_km = 3)
ht <- draw(ht)
```
Leads to:
![image](https://user-images.githubusercontent.com/59352321/84602390-f2275e00-ae7e-11ea-8c90-4bceba929171.png)

**Comment by jokergoo** [comment]
This is strange. Can you send me the objects `mat` and `genes`?

**Comment by jokergoo** [comment]
And what is the version of ComplexHeatmap you are using?

**Comment by jackbibby1** [comment]
Sure -- here are the objects.

[Objects.zip](https://github.com/jokergoo/ComplexHeatmap/files/4777110/Objects.zip)

I'm currently using v2.2.0

**Comment by jokergoo** [comment]
For me, it works as expected:

![image](https://user-images.githubusercontent.com/449218/84602838-6ddad800-ae8a-11ea-9880-3bf50fa3c657.png)

I am using version 2.5.3. I am not very sure whether it is the problem of the version, but you can try to use the newest version of ComplexHeatmap.

And for getting `at`, actually you can simply use:

```r

ind = which(rownames(mat) %in% genes)
row_an <- HeatmapAnnotation(Genes = anno_mark(at = ind,
                                              labels = rownames(mat)[ind],
```

**Comment by jokergoo** [comment]
And if you change the size of the graphic window, e.g. by dragging, you need to regenerate the plot.

**Comment by jokergoo** [comment]
Are you using Rstudio by clicking the icon "zoom"? The plot is only correct in the figure panel while not in the zoomed window. Or you can save it as a pdf file.

**Comment by jackbibby1** [comment]
Thanks a lot for the suggestions. Yup, I've upgraded to 2.5.3, but that itself didn't change anything. Saving the plot as a PDF seems to have worked when using `row_km`, as follows:

```
ind <- which(rownames(mat) %in% genes)
row_an <- HeatmapAnnotation(Genes = anno_mark(at = which(rownames(mat) %in% genes),
                                              labels = rownames(mat)[ind],
                                              labels_gp = gpar(fontsize = 7),
                                              link_width = unit(2.5, "mm"),
                                              padding = unit(0.5, "mm")),
                            which = "row")

ht <- Heatmap(mat, name = "Z-score",
              border = T, 
              show_row_names = T, show_column_names = F,
              row_names_gp = gpar(fontsize = 8),
              rect_gp = gpar(col = "white", lwd = 0.01),
              right_annotation = row_an,
              row_km = 3)

pdf(file = "Test.pdf")
ht <- draw(ht)
dev.off()
```

Just as a side question then -- when viewing the `ht <- draw(ht)` call in the RStudio plot window (and in the 'zoom' window) without using `row_km`, it shows correctly. You can also resize this in the zoom window and it automatically regenerates with the correct label positions. E.g. in plot window:

<img width="593" alt="No_row_km" src="https://user-images.githubusercontent.com/59352321/84603438-5e599000-ae86-11ea-9a3e-c677bdef58e3.png">

Or zoom and resize:
![image](https://user-images.githubusercontent.com/59352321/84603694-46830b80-ae88-11ea-83f7-81c147e42a3c.png)

But when using `row_km`, it isn't correct in the RStudio plot window or zoom window. Also, if you resize in the zoom window, the labels move position.

<img width="594" alt="Row_km" src="https://user-images.githubusercontent.com/59352321/84603451-77624100-ae86-11ea-8fdf-63ab455bdebb.png">

Zoom and resize:
![image](https://user-images.githubusercontent.com/59352321/84603721-6dd9d880-ae88-11ea-9d2c-004d3c42ecf2.png)

So it seems that calling `row_km` you get different behaviours in the plot window? Is this an RStudio thing, or is it something on the CompleHeatmap side? It means you just have to view the plot as a PDF every time you want to view labels when calling `row_km`?

Thanks again

**Comment by jokergoo** [comment]
This is a problem of RStudio.

For your case, when `row_km` is not set, it seems the plots in the figure panel, the zoomed plot and the exported plots are all correct. It is just because you have very few labels and there is no position adjustment (i.e. the connection line is horizontal). But if you have thousands of rows and you have many labels to add (e.g. 50 labels), the positions of labels are adjusted and zooming the figure or exporting them will affect the label positions.

When `row_km` is set, I don't know why the plot in the figure panel is wrong in your side. Maybe you need to regenerate it? Following is the figure panel on my side and it is correct.

<img width="652" alt="Screenshot 2020-06-14 at 23 04 22" src="https://user-images.githubusercontent.com/449218/84604006-5e13c180-ae93-11ea-91ad-d951c786c3f5.png">

Now I have updated the package a little bit that `anno_mark()` and `anno_zoom()` will give warnings and hints if users are working under RStudio.

**Comment by jokergoo** [comment]
When `row_km` is not set and when the plot is very short that the label positions are adjusted, the zoomed figure will be wrong:

![image](https://user-images.githubusercontent.com/449218/84604237-cca54f00-ae94-11ea-8e8a-15eaaf8b82e9.png)

You can try to shorten the height of the figure panel.

**Comment by jackbibby1** [comment]
OK, great, thanks. 

Hmm, it is odd -- I've restarted RStudio and replotted the data, but it all still seems to be the same with `row_km`. The labels are even completely out of the heatmap dimensions (I have blanked out the column names here)...

```
row_an <- HeatmapAnnotation(Genes = anno_mark(at = which(rownames(df_all_scaled) %in% genes),
                                              labels = rownames(df_all_scaled)[ind],
                                              labels_gp = gpar(fontsize = 7),
                                              link_width = unit(2.5, "mm"),
                                              padding = unit(1, "mm")),
                            which = "row")

hm <- Heatmap(df_all_scaled, name = "Z-score",
              border = T, 
              show_row_names = F,
              right_annotation = row_an,
              top_annotation = col_an,
              row_km = 11)

hm <- draw(hm)
```

<img width="511" alt="Screenshot 2020-06-14 at 22 37 05" src="https://user-images.githubusercontent.com/59352321/84604716-e55f3600-ae8f-11ea-8171-6aafdd05691a.png">

...Guess I'll just go ahead with the PDF option

Thanks for all your help
