### ISSUE TITLE
how to remove row annotation text

### ISSUE THREAD

**Issue by taojinsheng** [jokergoo/ComplexHeatmap#516]
Hi Zuguang,

I used ComplexHeatmap to plot a heatmap and added row annotation.I wonder how to remove the annotation text on the left side pointed by red arrows.I enclosed the plot.Thanks a lot.
![image](https://user-images.githubusercontent.com/23255364/84863641-d3f07680-b0a7-11ea-8915-7c0aa0e90dad.png)

**Comment by jokergoo** [comment]
You can set `row_title = NULL`.

**Comment by taojinsheng** [comment]
Thank you very much for your prompt reply.Here is another plot showing the same problem.I tried set row_title = NULL,but the text didn't appear. I enclosed my code and data. My command line is "Rscript /home/jinsheng_tao/code/R/complex_heatmap_for_matrix_epic_add_row_annotation.R /Src_Data3/analysis/Ironman/0.taojinsheng/Work/LC_new_panel/LC024/count/beta_matrix_benign_vs_other_pathway_sorted_rm_rank_rm_pathway.txt /Src_Data3/analysis/Ironman/0.taojinsheng/Work/LC_new_panel/LC024/LC024_info_2column.txt /Src_Data3/analysis/Ironman/0.taojinsheng/Work/LC_new_panel/LC024/count/beta_matrix_benign_vs_other_pathway.txt /Src_Data3/analysis/Ironman/0.taojinsheng/Work/LC_new_panel/LC024/count/beta_matrix_benign_vs_other_pathway_sorted_rm_rank_rm_pathway_heatmap.png".
[code_and_data.zip](https://github.com/jokergoo/ComplexHeatmap/files/4792509/code_and_data.zip)
Many thanks!

**Comment by jokergoo** [comment]
I think you are using an old version of the package. Can you update to 2.5.3?

![image](https://user-images.githubusercontent.com/449218/85854538-dc863280-b7b4-11ea-9346-e03ca45faaf9.png)

**Comment by YingjieLiScience** [comment]
> You can set `row_title = NULL`.

I have a follow-up question: how to overlap the row_title and the left color bar? or how to add a label to the color bar? Take the plot here, I intend to label the pink and orange bars on the left. 

I also tried anno_block, but I can't control the width of the block, even I added 
`# right_annotation = rowAnnotation(
        #   foo = anno_block(
        #     labels = c("group1", "group2"),
        #     width = unit(2, "mm"),
        #     height = unit(2, "mm"))),`

**Comment by jokergoo** [comment]
The current setting is if `labels` is specified, the width is the height of the text plus 5mm.

**Comment by jokergoo** [comment]
OK, I have updated the package a little bit. Now you can set `height` and `width` in `anno_block()`. Please update the package from GitHub.

**Comment by YingjieLiScience** [comment]
Thank you @jokergoo ! I notice if I place the width argument outside of `anno_block()`, but within `rowAnnotation()`, it also works. 

rowAnnotation(
  Region = anno_block(),  
  width = unit(3, "mm")
)

May I also ask how to change the font size of `anno_block()`. For my case here, I tried to change the font size of "Region" and I tried `gp = gpar(fontsize = 6)` and 'labels_gp = gpar(fontsize = 6)', neither worked. PLease see attached my screenshot. 
<img width="215" alt="20200629121342" src="https://user-images.githubusercontent.com/40079217/86030140-15ffad80-ba02-11ea-85c4-8c5907fbe8a7.png">

**Comment by jokergoo** [comment]
Try `annotation_name_gp` in `rowAnnotation()`? How are the font size of "Region" and "industry" different? I think the default font size for both are the same.

**Comment by YingjieLiScience** [comment]
Yes!! You are right. I got the expected result after using `annotation_name_gp`. 

I used a different way to add industry color bar `+ Heatmap(expr1$ind, 
          name = "Industry", 
          width = unit(width_bar, "mm"), 
          row_names_gp    = gpar(fontsize = font_size),
          column_names_gp = gpar(fontsize = font_size),
          column_names_side = 'bottom', 
          heatmap_legend_param = legend_hmap,
          col = col_industry) ` 

That is probably why I was struggling...

Thanks so much, again!!

**Comment by amkhasawneh** [comment]
![ND heatmap](https://user-images.githubusercontent.com/57086613/144973206-218525d9-c6d2-4cfd-9f8e-5ed006f26737.jpeg)
Hello, Zuguang!

Thank you very much for all the effort you put into the beautiful ComplexHeatmap package.
I am trying to make a gene expression heat map, and I would like to remove the names of the individual genes, as they clutter the plot. How can I do that?

[Thanks!]()
