### ISSUE TITLE
A better way to show raster heatmap

### ISSUE THREAD

**Issue by jokergoo** [jokergoo/ComplexHeatmap#518]
https://gdevailly.netlify.app/post/plotting-big-matrices-in-r/

**Comment by jokergoo** [comment]
https://cran.r-project.org/web/packages/magick/vignettes/intro.html#kernel_convolution

**Comment by Cumol** [comment]
Having the same issue plotting a 200x20000 heatmap.

![Screenshot 2020-06-23 at 10 52 28](https://user-images.githubusercontent.com/4943380/85382879-af7d1a00-b53f-11ea-9713-adcb6ffaf656.png)

**Comment by jokergoo** [comment]
https://en.wikipedia.org/wiki/Image_scaling
