### ISSUE TITLE
Side of row annotation legend cannot be controlled independently of heatmap legend

### ISSUE THREAD

**Issue by plger** [jokergoo/ComplexHeatmap#520]
**Reproducible example:**
  
```
library(ComplexHeatmap)
# random annotation data.frame
ra <- data.frame( var1=sample(LETTERS[1:3],10,replace=TRUE), 
                  var2=sample(letters[1:3],10,replace=TRUE))
ra <- HeatmapAnnotation(which="row", df=ra)
# heatmap
H <- Heatmap(matrix(rnorm(100), nrow=10), right_annotation=ra,
             heatmap_legend_param=list(direction="horizontal", side="bottom"))
# try to reposition the legend
draw(H, merge_legends=FALSE, heatmap_legend_side="bottom", 
     annotation_legend_side="right")
```

**Expected behavior:** the annotation legend on the right, and the heatmap legend at the bottom
**Observed behavior:** both legends at the bottom

Note: it works with column annotation, just not with row annotation.

Observed with both R 3.6.1 and R 4, and both ComplexHeatmap 2.5.1 and 2.5.3.

(Awesome package, BTW)

**Comment by plger** [comment]
In case others are encountering the issue, a possible workaround is to define colors, disable plotting the annotation legends, creating those manually, and then adding them at the end:

```
# random annotation data.frame
d <- data.frame( var1=sample(LETTERS[1:3],10,replace=TRUE), 
                           var2=sample(letters[1:3],10,replace=TRUE))
# we have to assign colors, so that they match between annotation and legend
cols <- lapply(d, FUN=function(x){
  x <- sort(unique(x))
  y <- randomcoloR::randomColor(length(x))
  names(y) <- x
  y
})
legends <- lapply(names(cols), FUN=function(f){
  Legend( labels=sort(unique(d[[f]])), title=f,
          legend_gp=gpar(fill=cols[[f]]) )
})
ra <- HeatmapAnnotation(which="row", df=d, col=cols, show_legend=FALSE)

# heatmap
H <- Heatmap(matrix(rnorm(100), nrow=10), right_annotation=ra,
             heatmap_legend_param=list(direction="horizontal"))
draw(H, merge_legends=FALSE, heatmap_legend_side="bottom", 
     annotation_legend_side="right", annotation_legend_list=legends)
```

**Comment by jokergoo** [comment]
Then it must be a bug : )

**Comment by jokergoo** [comment]
Ah, I know the reason. In the horizontal heatmap list, the heatmap legends are treated the same as the row annotation legends and are both controlled by `heatmap_legend_side`, while the column annotation legends are controlled by `annotation_legend_side`. Em, this is a little bit confusing...

**Comment by yeswzc** [comment]
Hi, I found a similar issue that it is not able to set rowAnnotation legend as horizontal. I tried the code below to set both heatmap legend and rowAnnotation legend at bottom which worked. **But I when set both legend as horizontal, the rowAnnotation is still vertical.** Is this a bug?

Thanks!

```

x = matrix(rnorm(100), nrow = 10)
p = Heatmap(x, cluster_columns = F, cluster_rows = F,
            left_annotation = rowAnnotation(cluster = factor(rep(c(1,2),5)), 
                                            annotation_legend_param = list(cluster = list(direction = "horizontal"))),
            name = " ", 
            heatmap_legend_param = list(direction = "horizontal"))

draw(p, heatmap_legend_side = "top", merge_legend = TRUE, annotation_legend_side = "top")

```

**Comment by jokergoo** [comment]
Please see my reply on bioc support website: https://support.bioconductor.org/p/132059/#132147

**Comment by plger** [comment]
Good to know about the vertical trick!
From a user perspective, it feels like the most intuitive would be to split `annotation_legend_side` into `row_annotation_legend_side` and `column_annotation_legend_side`. Is there a reason for not implementing it in this way?

**Comment by jokergoo** [comment]
Em... I will think about it. 

"If the heatmaps are concatenated horizontally, all heatmap and row annotation legends are grouped and all column annotation legends ae grouped. The reason we assume the horizontal direction passes the main message of the plot, while the vertical direction provides secondary information." This is the reason for the current setting.

For a horizontal heatmap list, grouping heatmap legends and row annotation legends together seems quite natural.

![image](https://user-images.githubusercontent.com/449218/85957657-68ec4d00-b98f-11ea-9b80-92e93dc7758c.png)

But, indeed, for a single heatmap, it would be quite confusing to merge heatmap legends and row annotation legends.
