### ISSUE TITLE
Heatmap slices border color

### ISSUE THREAD

**Issue by asmagen** [jokergoo/ComplexHeatmap#521]
Is there any way to change the heatmap slices (cluster_column_slices) border color?
![Screen Shot 2020-06-19 at 11 53 25 AM](https://user-images.githubusercontent.com/11299568/85152853-7e40d900-b223-11ea-8d25-e4cf16aa17be.png)
Thanks

**Comment by jokergoo** [comment]
Try `border` argument in `Heatmap()`.
