### ISSUE TITLE
How to generate 100 colors from a list of 5 colors?

### ISSUE THREAD

**Issue by Cumol** [jokergoo/ComplexHeatmap#523]
I trying to set colors for a heatmap of continuous data (columns are time and rows are samples). Below is my current approach for setting colors:
```
quantile.range <- quantile(data, probs = seq(0, 1, 0.001))

palette.breaks <- seq(quantile.range["5.0%"], quantile.range["99.0%"], length.out = 11)

col_fun = circlize::colorRamp2(palette.breaks, c("#5e4fa2","#3288bd","#66c2a5","#abdda4","#e6f598","#ffffbf","#fee08b","#fdae61","#f46d43","#d53e4f","#9e0142"), space = "RGB")
```
The problem here is that small changes in the data lead to strong jumps in color, visually, as seen in the example below:

![Screenshot 2020-06-23 at 10 52 28](https://user-images.githubusercontent.com/4943380/85401935-1f4cce00-b55b-11ea-929e-5968b7fc14a7.png)

How do I generate much more colors in between so these jumps in colors are less extreme?

**Comment by jokergoo** [comment]
What is the distribution of your data? `colorRamp2()` basically linearly interpolates in `palette.breaks`. Maybe you should transform your data (a log-transformation)?
