### ISSUE TITLE
Border gpar and hierarchical labels

### ISSUE THREAD

**Issue by v715** [jokergoo/ComplexHeatmap#524]
**Example**
```R
library(ComplexHeatmap)
library(circlize)

n1 = 4; n2 = 8; n3 = 6; n = n1 + n2 + n3
mat = matrix(rnorm(4 * n * n), 2 * n, 2 * n)
labels = c(rep("A", n1), rep("B", n2), rep("C", n3))
labels <- c(labels, tolower(labels))
labels <- factor(labels, levels = unique(labels))


Heatmap(
  mat,
  border = TRUE,
  name = "mat",
  column_split = labels, column_title = NULL,
  row_split = labels, row_title = NULL,
  cluster_row_slices = FALSE, cluster_column_slices = FALSE,
  top_annotation = HeatmapAnnotation(foo = anno_block(gp = gpar(fill = 2:4, col = 0), labels = unique(labels))),
  left_annotation = rowAnnotation(foo = anno_block(gp = gpar(fill = 2:4, col = 0), labels = unique(labels)))
)
```
<img width="531" alt="Screen Shot 2020-06-25 at 1 50 45 AM" src="https://user-images.githubusercontent.com/29757116/85662761-4ce26600-b686-11ea-92ff-8fa6932f9819.png">

1. How can I change the parameters for the border? For example, change the color, linestyle, and alpha of the border?
2. Is it possible to add hierarchical labels to the heatmaps? I have labeled the blocks (A, B, C, a, b, c). Is it possible to label the uppercase blocks as being from one group and the lowercase blocks as being from another group?

Thank you for your help!

**Comment by jokergoo** [comment]
OK, I will add a `border_gp` argument in `Heatmap()`. Currently you can do:

```r
Heatmap(...)
for(i in 1:6) {
    for(j in 1:6) {
        decorate_heatmap_body("mat", row_slice = i, column_slice = j, {
            grid.rect(gp = gpar(lty = ..., fill = NA, col = ...))
        }
    }
}
```

For the second question, sorry I don't quite understand. Can you give an example?

**Comment by v715** [comment]
`border_gp` would be great, thank you!

For the second one, I'm looking to do something like this:
<img width="219" alt="Screen Shot 2020-06-28 at 9 57 15 AM" src="https://user-images.githubusercontent.com/29757116/85949612-ca77d180-b925-11ea-87d2-5fb63988dc28.png">

I can already add the first level of labels with `anno_block`, but I'm not sure how to add the second level of labels.

**Comment by jokergoo** [comment]
That actually crosses several slices, and currently difficult to draw it. I will think of a way to support it in `anno_block` to add a "block" annotation over several slices.

Currently, I have a hard way to implement it. 1. create an empty annotation and later we add the cross-slice block annotation in it:

```r
Heatmap(
  mat,
  border = TRUE,
  name = "mat",
  column_split = labels, column_title = NULL,
  row_split = labels, row_title = NULL,
  cluster_row_slices = FALSE, cluster_column_slices = FALSE,
  top_annotation = HeatmapAnnotation(
  	empty = anno_empty(border = FALSE),  ## <<-- here
  	foo = anno_block(gp = gpar(fill = 2:4, col = 0), labels = unique(labels))),
  left_annotation = rowAnnotation(foo = anno_block(gp = gpar(fill = 2:4, col = 0), labels = unique(labels)))
)
```

To draw such blocks, basically, we need to know the positions of block A and C. The easiest way is to go the corresponding viewports and obtain their positions measured in the ROOT device (e.g. the position relative to the size of the interactive graphics device or the in-file device such as PDF).

The name of the viewport can be found in `list_components()` function.

```r
seekViewport("annotation_empty_1")
loc1 = deviceLoc(x = unit(0, "npc"), y = unit(0, "npc"))
seekViewport("annotation_empty_3")
loc2 = deviceLoc(x = unit(1, "npc"), y = unit(1, "npc"))
```

We go to the ROOT viewport and draw the rectangles and text:

```r
seekViewport("global")
grid.rect(loc1$x, loc1$y, width = loc2$x - loc1$x, height = loc2$y - loc1$y, 
	just = c("left", "bottom"), gp = gpar(fill = "red"))
grid.text("UPPER", x = (loc1$x + loc2$x)*0.5, y = (loc1$y + loc2$y)*0.5)
```

![image](https://user-images.githubusercontent.com/449218/85951250-409a2980-b962-11ea-8010-b168753940cc.png)

Similarly, you can add other blocks.

**Comment by v715** [comment]
I see thank you for the suggestion! I think it might be easier to add the hierarchical label ("UPPER") via a secondary application.

A `border_gp` parameter will certainly be useful, thank you very much.

**Comment by jokergoo** [comment]
`border_gp` is added in the newest version from GitHub.
