### ISSUE TITLE
package ‘ComplexHeatmap’ is not available (for R version 4.0.1)

### ISSUE THREAD

**Issue by ericalou** [jokergoo/ComplexHeatmap#525]
I recently upgraded my R version and note that complexHeatmap is not available. Are there plans to make it available for v4.01 of R?  Thanks

**Comment by jokergoo** [comment]
I think this is no corresponding bioc version for R 4.0.1, but you can install it by:

```r
library(devtools)
install_github("jokergoo/ComplexHeatmap")
```

**Comment by ericalou** [comment]
Yes you're right.  Thanks so much!
