### ISSUE TITLE
add row_slice_reorder argument

### ISSUE THREAD

**Issue by jokergoo** [jokergoo/ComplexHeatmap#526]
and also check default reordering

It seems there is or dendrogram reordering on slices:

![image](https://user-images.githubusercontent.com/449218/85835659-b8ffbf80-b795-11ea-93b7-e20f9d117571.png)

**Comment by Cumol** [comment]
Do you have a current workaround for this until it is implemented?

**Comment by jokergoo** [comment]
It is implemented in the GitHub version. 

```r
> m = matrix(1:100, nrow = 10, byrow = T)
> Heatmap(m, row_km = 3)
```

![image](https://user-images.githubusercontent.com/449218/86904981-bc8a3380-c111-11ea-8266-2015058a437e.png)
