### ISSUE TITLE
`set.seed()` is ignored. How to get reproducible clustering?

### ISSUE THREAD

**Issue by romanhaa** [jokergoo/ComplexHeatmap#528]
Hi!

Do you have an advice on how to get reproducible clustering of rows and columns? See the example below. I set the seed but get different clustering with the same command.

```r
library(tidyverse)
library(ComplexHeatmap)
library(circlize)

set.seed(42)

Heatmap(
  as.matrix(iris[,1:4]),
  row_km = 5,
  cluster_rows = TRUE,
  show_row_names = TRUE,
  cluster_columns = TRUE,
  show_column_dend = TRUE,
  rect_gp = gpar(col = 'white', lwd = 1),
  border = TRUE
)
```

![image](https://user-images.githubusercontent.com/18103560/85952865-77753d00-b96c-11ea-80fb-909331bc0080.png)

```r
Heatmap(
  as.matrix(iris[,1:4]),
  row_km = 5,
  cluster_rows = TRUE,
  show_row_names = TRUE,
  cluster_columns = TRUE,
  show_column_dend = TRUE,
  rect_gp = gpar(col = 'white', lwd = 1),
  border = TRUE
)
```

![image](https://user-images.githubusercontent.com/18103560/85952868-7fcd7800-b96c-11ea-896f-89f0b91cbfcf.png)

Any help is appreciated!

Cheers,
Roman

**Comment by jokergoo** [comment]
Everytime when you remake the heatmap, you need to specify `set.seed()` with the same seed:

```r
set.seed(42)
Heatmap(...)

set.seed(42)
Heatmap(...)
```

**Comment by romanhaa** [comment]
Ha, I obviously didn't know that. Thanks!

**Comment by jokergoo** [comment]
I recommend to add it before `Heatmap()`, although the internal `kmeans()` is executed when `draw()` is executed.

**Comment by romanhaa** [comment]
Got it. Thanks again!
