### ISSUE TITLE
Split row titles angle

### ISSUE THREAD

**Issue by asmagen** [jokergoo/ComplexHeatmap#530]
How do I rotate the row names for the heat map split blocks such that they are horizontal?
Using row_title_gp = gpar(fontsize = 7, fontface = "italic") I get to control only the font.

Thanks

**Comment by jokergoo** [comment]
Do you mean this?

```r
> m = matrix(rnorm(100), 10)
> Heatmap(m, row_km = 3, row_title_rot = 0, row_title_gp = gpar(fill = 2:4))
```

![image](https://user-images.githubusercontent.com/449218/86048970-9a2d5180-ba51-11ea-873a-75f1909d49ee.png)

**Comment by asmagen** [comment]
Yes, thank you!
 
Also if we’re already at it, how do I make a name with spaces for the titles as in the following example?

**Comment by asmagen** [comment]
Yes, thank you!
 Also if we’re already at it, how do I make a name with spaces for the titles as in the following example?

<img width="450" alt="Screen Shot 2020-06-29 at 3 53 17 PM" src="https://user-images.githubusercontent.com/11299568/86049825-d6948980-ba20-11ea-9f24-734daff10f24.png">
<img width="110" alt="Screen Shot 2020-06-29 at 3 53 22 PM" src="https://user-images.githubusercontent.com/11299568/86049830-d7c5b680-ba20-11ea-90d7-445d2f24e93f.png">

**Comment by jokergoo** [comment]
Do you want "1 2 3" to be more far away from the dendrogram? or "N_patient" more far away from the axis?

**Comment by asmagen** [comment]
I want to have the label say 'N patients' instead of 'N_patients' but I don't see anywhere to set the label other than the variable name which can't have spaces

**Comment by jokergoo** [comment]
You can set `annotation_label` to define a new name:

```r

m = matrix(rnorm(100), 10)
ha = rowAnnotation(f_oo = anno_block(show_name = TRUE),   ## f_oo is taken as the default label
	annotation_name_gp = gpar(fontsize = 20),
	annotation_label = "F OO")
Heatmap(m, right_annotation = ha)
```

![image](https://user-images.githubusercontent.com/449218/86134350-cc8a8d80-bae9-11ea-8d34-f8f6300496e6.png)

**Comment by asmagen** [comment]
I get:
```
> anno_block(cluster_group_annotation,show_name = F)
Error in anno_block(cluster_group_annotation, show_name = F) : 
  unused argument (show_name = F)
> anno_block(show_name = F)
Error in anno_block(show_name = F) : unused argument (show_name = F)
```
Thanks

**Comment by jokergoo** [comment]
Update to the newest version. It was recently added.
