### ISSUE TITLE
Tilt and relabel row annot with spaces

### ISSUE THREAD

**Issue by asmagen** [jokergoo/ComplexHeatmap#532]
How do I tilt the labels of the row annots as I do for the matrix column labels, as well as rename the row annot title with spaces similarly to what I mentioned in the other thread?

Thank you
![Screen Shot 2020-07-02 at 4 33 33 PM](https://user-images.githubusercontent.com/11299568/86406799-c6c7b000-bc81-11ea-9b5c-5aea6f9b6eee.png)

**Comment by jokergoo** [comment]
Current you cannot rotate the annotation labels, but there are two ways to solve it:

1. The three annotations you have are heatmap-like annotations, actually you can use three `Heatmap()` where each is a one-column matrix. With this, annotation labels become the heatmap column names and you can set the rotation for that.

2. Turn off annotation labels in `rowAnnotation()` function, and later add labels by `decorate_annotation()` function.
