### ISSUE TITLE
Assign colors to categorical variables in HeatmapAnnotation

### ISSUE THREAD

**Issue by EmilyB17** [jokergoo/ComplexHeatmap#536]
Hi there,
I am creating a heatmap with a column annotation to show which observations (columns) correspond to which experimental treatment. The heatmap data is stored in a matrix, and the treatment data is stored in an identical dataframe with an extra column with the categorical (factor) treatment code. I added the column annotation as a HeatmapAnnotation(), but cannot set the colors of the treatment. I tried this code: 

```
Heatmap(t(submat), top_annotation = HeatmapAnnotation(Treatment = sub$treatmentID, 
                                                      col = c("EX-AL" = "#FDBF6F", "EX-ER" = "#FF7F00", "SED-AL" = "#CAB2D6", "SED-ER" = "#6A3D9A" )))
```

But got this error: `Error: elements in `col` should be named vectors.`

I'm attaching a jpeg of the plot with the default colors; this is exactly what I'm looking for, except I'd like to control the colors of the column annotation. Any suggestions?

![heatmap](https://user-images.githubusercontent.com/31933406/86624181-e1a36880-bf90-11ea-93c1-18f5a50c2297.jpeg)

Thank you!

**Comment by jokergoo** [comment]
Try:

```r
Heatmap(t(submat), top_annotation = HeatmapAnnotation(Treatment = sub$treatmentID, 
    col = list(Treatment = c("EX-AL" = "#FDBF6F", "EX-ER" = "#FF7F00", "SED-AL" = "#CAB2D6", "SED-ER" = "#6A3D9A" ))))
```

`col` should be a named list so that `col` can be correctly mapped to the annotations.

**Comment by EmilyB17** [comment]
Great, thank you!
