### ISSUE TITLE
HeatmapList Documentation Contradictory About Constructor Function

### ISSUE THREAD

**Issue by DarioS** [jokergoo/ComplexHeatmap#537]
Firstly, it says

**Usage**
`HeatmapList(...)`

but, immediately below, I read "There is no public constructor method for the `HeatmapList-class`." If I try to do it, I get an error

```r
> HeatmapList(aHeatmap)
Error in initialize(value, ...) : 
  'initialize' method returned an object of class “Heatmap” instead of the required class “HeatmapList”
```

I want to put a big main title above the plot of one heatmap, as well as having an x-axis title below the heatmap. To get two column titles, I thought I could convert one heatmap into a heatmap list, so I could use the second column title. However, it seems like `heatmap1 + heatmap2` is the only way to create a heatmap list, but I only have one heatmap and don't need to concatenate.

**Comment by jokergoo** [comment]
You can use `heatmap1 + NULL`.

**Comment by DarioS** [comment]
Weird and undocumented - but it works.

**Comment by jokergoo** [comment]
It is mentioned in the documentation, but I think people normally ignore it because it is very rarely used.

![image](https://user-images.githubusercontent.com/449218/86904216-a8920200-c110-11ea-9495-7157d2261d06.png)
