### ISSUE TITLE
Show Legend Groups of Unused Legend Groups

### ISSUE THREAD

**Issue by DarioS** [jokergoo/ComplexHeatmap#538]
I specified all of the categories to `at` but one is not plotted (i.e. (0.8,1] in the red legend) because there is no data which has that value. For example:

![image](https://user-images.githubusercontent.com/631218/86722045-e5ef8480-c069-11ea-89ba-646b43ab0e37.png)

The specification is `col = gainColours` and  `heatmap_legend_param = list(title = " ", at = proportionsLevels)` and

```r
> gainColours
          0     (0,0.2]   (0.2,0.4]   (0.4,0.6]   (0.6,0.8]     (0.8,1] 
"#FFFFFFFF" "#FFD9CBFF" "#FFB299FF" "#FF8969FF" "#FF5B3AFF" "#FF0000FF"
> proportionsLevels # Created by R's cut function.
[1] "0"         "(0,0.2]"   "(0.2,0.4]" "(0.4,0.6]" "(0.6,0.8]" "(0.8,1]"
```

How can the red legend be forced to show the same categories as the blue legend?

**Comment by jokergoo** [comment]
What version of ComplexHeatmap are you using? And can you show me the full code?

**Comment by DarioS** [comment]
I use version 2.4.2. I made a smaller, self-contained example. If, instead of a matrix, I pass in a factor, it's O.K. because it gets the factor's levels. But, I have multiple columns of data, so it must be a matrix. Compare the legend shown for `Hboth` to `HfactorBoth`.

```r
library(ComplexHeatmap)
library(circlize)
set.seed(4444)

X <- matrix(runif(10, 0, 0.8)) # No data values recorded between 0.8 and 1.
Y <- matrix(seq(0.05, 0.95, 0.1)) # Data values recorded in all groups.
Xfactor <- cut(X, breaks = seq(0, 1, 0.2))
Yfactor <- cut(Y, breaks = seq(0, 1, 0.2))
X <- apply(X, 2, function(x) cut(x, breaks = seq(0, 1, 0.2))) # Remains a matrix.
Y <- apply(Y, 2, function(y) cut(y, breaks = seq(0, 1, 0.2))) # Remains a matrix.
proportionsLevels <- proportionsLevels <- levels(cut(seq(0, 1, 0.01), breaks = seq(0, 1, 0.2)))
lossColourFuncton <- colorRamp2(0:1, c("white", "blue"))
lossColours <- structure(lossColourFuncton(seq(0, 1, 0.25)), names = proportionsLevels)
gainColourFunction <- colorRamp2(0:1, c("white", "red"))
gainColours <- structure(gainColourFunction(seq(0, 1, 0.25)), names = proportionsLevels)
H1 <- Heatmap(X, show_row_dend = FALSE, show_column_dend = FALSE,
              column_title = "Loss", column_title_side = "bottom", col = lossColours,
              heatmap_legend_param = list(title = "Proportion of\nSamples", at = proportionsLevels)
)
H2 <- Heatmap(Y, show_row_dend = FALSE, show_column_dend = FALSE,
              column_title = "Loss", column_title_side = "bottom", col = gainColours,
              heatmap_legend_param = list(title = "Proportion of\nSamples", at = proportionsLevels)
)
Hboth <- H1 + H2
Hboth # Some groups missing in first legend.

H1F <- Heatmap(Xfactor, show_row_dend = FALSE, show_column_dend = FALSE,
               column_title = "Loss", column_title_side = "bottom", col = lossColours,
               heatmap_legend_param = list(title = "Proportion of\nSamples", at = proportionsLevels)
)
H2F <- Heatmap(Yfactor, show_row_dend = FALSE, show_column_dend = FALSE,
               column_title = "Loss", column_title_side = "bottom", col = gainColours,
               heatmap_legend_param = list(title = "Proportion of\nSamples", at = proportionsLevels)
)
HfactorBoth <- H1F + H2F
HfactorBoth # All groups shown.
```

I thought that by specifying `at = proportionsLevels` I could force all groups to show in legend, even if not in data values.

**Comment by jokergoo** [comment]
Sorry, I completely lost this issue.

Yes, I agree this is a confusing case. The following heatmap:

```r
Heatmap(X, show_row_dend = FALSE, show_column_dend = FALSE,
              column_title = "Loss", column_title_side = "bottom", col = lossColours,
              heatmap_legend_param = list(title = "Proportion of\nSamples", at = proportionsLevels)
)
```

![image](https://user-images.githubusercontent.com/449218/96442221-0ef7e780-120b-11eb-88ab-202f38291ccb.png)

just removes the values from the legend which are not existed in the heatmap, even if you specified in the colors.

The design is that everything in `Heatmap()` is the "main matrix"-centric, if a value is not in the matrix, it will be removed, as well as corresponding settings. So, the values `(0.2, 0.4]` and `(0.8, 1]` in `lossColours` are removed. Later when you set `at` in `heamtap_legend_param`, the values for `(0.2, 0.4]` and `(0.8, 1]` are also removed because they do not exist in the matrix.

However, when you set it as a factor where all intervals are saved as the levels of the factor, `Heatmap()` function actually also look at the factor levels and it knows all the intervals are used, then all intervals are kept for the legend.

**Comment by jokergoo** [comment]
Hi, I made some changes of the package, now the first case (without setting them as factors) also generates legends with the same set of labels:

```r
H1 <- Heatmap(X, show_row_dend = FALSE, show_column_dend = FALSE,
              column_title = "Loss", column_title_side = "bottom", col = lossColours,
              heatmap_legend_param = list(title = "Proportion of\nSamples", at = proportionsLevels)
)
H2 <- Heatmap(Y, show_row_dend = FALSE, show_column_dend = FALSE,
              column_title = "Loss", column_title_side = "bottom", col = gainColours,
              heatmap_legend_param = list(title = "Proportion of\nSamples", at = proportionsLevels)
)
H1 + H2
```

![image](https://user-images.githubusercontent.com/449218/96634405-b879ce80-131a-11eb-958f-564d94a6d5b6.png)
