### ISSUE TITLE
Vertical concatenation failed when using anno_mark()

### ISSUE THREAD

**Issue by xlucpu** [jokergoo/ComplexHeatmap#542]
Hi, I met a problem when I tried to vertically concatenate two heatmap with specific row annotation.

The code was derived and modified from the example of ComplexHeatmap (2.5.4):
```
set.seed(123)
mat1 = matrix(rnorm(80, 2), 8, 10)
mat1 = rbind(mat1, matrix(rnorm(40, -2), 4, 10))
rownames(mat1) = paste0("R", 1:12)
colnames(mat1) = paste0("C", 1:10)

mat2 = matrix(runif(60, max = 3, min = 1), 6, 10)
mat2 = rbind(mat2, matrix(runif(60, max = 2, min = 0), 6, 10))
rownames(mat2) = paste0("R", 1:12)
colnames(mat2) = paste0("C", 1:10)

mat1t = t(mat1)
mat2t = t(mat2)
ht1 = Heatmap(mat1t, name = "rnorm", row_title = "rnorm", show_row_names = F) + rowAnnotation(link = anno_mark(at = c(3,6),
                                                                                                               labels = c("A","B"),
                                                                                                               which = "row"))
ht2 = Heatmap(mat2t, name = "runif", row_title = "runif", show_row_names = F)
ht_list = ht1 %v% ht2
draw(ht_list)
```

And it got me this error:
`Error: The heatmap list should only be all horizontal or vertical.`

Actually it is totally fine to draw ht1 and ht2 seperately but they cannot be vertical concatenated.
How to fix this?

Many thanks advanced!

**Comment by jokergoo** [comment]
`ht1` is actually a horizontal list because you used "+", you can move the row annotation as a right annotation of the heatmap:

```r
ht1 = Heatmap(mat1t, name = "rnorm", row_title = "rnorm", show_row_names = F, 
    right_annotation =  rowAnnotation(link = anno_mark(at = c(3,6), labels = c("A","B"),...)

```

**Comment by xlucpu** [comment]
> `ht1` is actually a horizontal list because you used "+", you can move the row annotation as a right annotation of the heatmap:
> 
> ```r
> ht1 = Heatmap(mat1t, name = "rnorm", row_title = "rnorm", show_row_names = F, 
>     right_annotation =  rowAnnotation(link = anno_mark(at = c(3,6), labels = c("A","B"),...)
> ```

It works, thank you so much.
