### ISSUE TITLE
Viewport 'annotation_Intersection size_1' was not found

### ISSUE THREAD

**Issue by binlu1981** [jokergoo/ComplexHeatmap#544]
Hi, 

I used the sample data in the Chapter 8 and want to add the combination set size to the plot. But it report errors:

`ht = draw(UpSet(m))`
`od = column_order(ht)`
`cs = comb_size(m)`
```
decorate_annotation("Intersection\nsize", {
+     grid.text(cs[od], x = seq_along(cs), y = unit(cs[od], "native") + unit(2, "pt"), 
+               default.units = "native", just = "bottom", gp = gpar(fontsize = 8))
+ })
```
Error in grid.Call.graphics(C_downviewport, name$name, strict) : 
  Viewport 'annotation_Intersection
size_1' was not found

Any suggestions?

Thanks!

**Comment by jokergoo** [comment]
Hi, sorry I haven't updated the documentation yet. In the newest version of ComplexHeatmap, I've changed the name of that annotation. Now it should be:

```r
decorate_annotation("intersection_size", {
    grid.text(cs[od], x = seq_along(cs), y = unit(cs[od], "native") + unit(2, "pt"), 
        default.units = "native", just = "bottom", gp = gpar(fontsize = 8))
})
```
