### ISSUE TITLE
Set labels for Heatmap annotation when using dataframe 

### ISSUE THREAD

**Issue by asgarhussain** [jokergoo/ComplexHeatmap#545]
I want to set the labels from the data frame which passed to the HeatmapAnnotation function. 

Can you give me some examples?

**Comment by jokergoo** [comment]
Do you mean your annotation labels are dynamic and depend on upstream?

**Comment by asgarhussain** [comment]
Yes.

**Comment by jokergoo** [comment]
let's say the annotation data is in `df`, the annotation labels is in `anno_labels`, then you can construct the heatmap annotation by:

```r
ha = do.call("Heatmap", list(df = df, annotation_label = anno_labels))
```
