### ISSUE TITLE
Extracting gene names in each cluster from the heatmap

### ISSUE THREAD

**Issue by hnthirim** [jokergoo/ComplexHeatmap#546]
Please provide example datasets and the code you use. It will help me to understand your problem and help you!
I want to extract the genes that belong to each cluster in the heatmap that is generated using ComplexHeatmap. Below is the code that i used to generate the heatmap:

```
mydata <- data.frame(HctJunDelWTfcpos0.01_HctRNAseq)
hclust_matrix <- mydata %>% 
  select(-Gene_name) %>%
  as.matrix()
rownames(hclust_matrix) <- mydata$Gene_name

hclust_matrix <- hclust_matrix %>%
  t() %>%
  scale() %>%
  t()

library(ComplexHeatmap)
library(circlize)
col_fun = colorRamp2(c(-2, 0, 2), c("blue", "white", "red"))
HM <- Heatmap(hclust_matrix, col = col_fun,  na_col = "black", show_row_names = FALSE, show_column_dend = TRUE, row_dend_side = "right", row_dend_width = unit(6, "cm"), use_raster = FALSE)
HM <- draw(HM)
```

Then to extract clusters I used a code that was mentioned in one of the previous posts: 

```
r.dend <- row_dend(HM) #Extract row dendogram
rcl.list <- row_order(HM) #Extract clusters (output is a list)
lapply(rcl.list, function(x) length(x)) #check/confirm size clusters
for (i in 1:length(row_order(HM))){
  if (i==1) {
    clu <- t(t(row.names(hclust_matrix[row_order(HM)[[i]],])))
out <- cbind(clu, paste("cluster", i, sep=""))
colnames(out) <- c("Gene_name", "Cluster")
            } else {
  clu <- t(t(row.names(hclust_matrix[row_order(HM)[[i]],])))
  clu <- cbind(clu, paste("cluster", i, sep=""))
  out <- rbind(out, clu)
  }
}

out
```
However, this is giving an error as "Error in t.default(row.names(hclust_matrix[row_order(HM)[[i]], ])) : 
  argument is not a matrix" 

I cannot figure out how to fix this. Appreciate your help. 
Thanks!

**Comment by jokergoo** [comment]
You can simply check the value of `row_order(HM)` for which I think is not a list, so you don't need to use a `for` loop here.

`row_order()` returns a list only when the heatmap is split.

**Comment by hnthirim** [comment]
So do the following instead of the for loop?

clu <- t(t(row.names(hclust_matrix[row_order(HM)])))

It still gives the same error "Error in t.default(row.names(hclust_matrix[row_order(HM)])) : 
  argument is not a matrix" 

row_order(HM) returned this: 
> row_order(HM)
  [1] 104 177  83  59  45  51  12  33 151  88  28 182  69 170 141 171 102 159 134 185 137  84  60 179  61 160 122 152  93 105  36   1
 [33]  54  21   5   8  34  10 155 146  24   2 184 173 108 127   7 147 128 157  68 117 162 158 119 110 150  47  46  50  35  73 116 142
 [65] 131 163  14  57 107  62 180 121 114 183 175  53  38  40  27 153  75 187 174 161 115 156 100 148 181  20  43  52 124  71 120  90
 [97] 130  87  15 111  26  82 167  97 143 149  56  91 176  64  65  44   6  11 135  23  41  92  39  58  79  32  80  95  78  94  96 186
[129]  30 138  17 113  63  76  98 106  42 144 165  66  72  18 154  16 139 172 109 178 112  48 101  49 132 145  25 164  99 168   3  74
[161]  89   4  77 129  31  67  37  22  70 169  13 118 140 126  81 133  86  19   9  85 103 123 136 125 166  29  55

**Comment by jokergoo** [comment]
Still, why do you transpose the row names?

```r
 t(t(row.names(hclust_matrix[row_order(HM)])))
```

Also `hclust_matrix[row_order(HM)]` won't return a matrix, `hclust_matrix[row_order(HM), ]` returns.
