### ISSUE TITLE
Blank oncoplot using oncoPrint

### ISSUE THREAD

**Issue by dongjoban17** [jokergoo/ComplexHeatmap#547]
I'm running into a following error when trying to create an oncoplot using `oncoprint()` function:
`Error in valid.viewport(x, y, width, height, just, gp, clip, xscale, yscale, : invalid 'yscale' in viewport`

I've been able to generate desired plots with no issues with same snippet of code. After going through my data, I noticed that the matrix for the problematic figure consisted only of 0's (currently using binary values to indicate presence of mutation). Is it possible to generate an empty oncoplot? Or is this issue caused by something entirely different?

Thanks!

**Comment by jokergoo** [comment]
Sounds interesting! Can you provide some example dataset and code?

**Comment by dongjoban17** [comment]
I ended up rewriting some of the code using the oncoprint() after going through the manual (ended up changing a couple of lines for annotations which fixed the above error). Thanks for following up with the issue though.
