### ISSUE TITLE
ggplot as heatmap Annotation

### ISSUE THREAD

**Issue by oh111** [jokergoo/ComplexHeatmap#548]
Hi there, 

I know this question has been asked previously (#261 ), but is there another way to add ggplot objects into a heatmap annotation? 
The suggested way uses viewports, that makes aligning them very hard. For instance, possible integration with Seurat's DotPlot?

Thanks

**Comment by jokergoo** [comment]
Do you mean this kind of annotation? E.g. in https://github.com/jokergoo/ComplexHeatmap/issues/355

**Comment by oh111** [comment]
My apologies, I should have added more context. 
Please see the figure attached before-- attaching ggplot with the solution from #261, doesn't align the dotplot with the heatmap. I can't think of a way to do it either because the ggplot is from a dataframe separate from the matrix that the heatmap is from. 

<img width="695" alt="Screen Shot 2020-07-20 at 4 45 48 PM" src="https://user-images.githubusercontent.com/57680851/87984772-7b4a3a00-caa8-11ea-8593-a5fc65363248.png">

Here, the intensity is the magnitude of gene expression and size, the percentage of cells positive.

**Comment by oh111** [comment]
Edit: I think I have may have figured it out. I removed all theme, with theme_void (for ggplot), and it aligned perfectly. Now to just make the labels.

**Comment by smk5g5** [comment]
> My apologies, I should have added more context. Please see the figure attached before-- attaching ggplot with the solution from #261, doesn't align the dotplot with the heatmap. I can't think of a way to do it either because the ggplot is from a dataframe separate from the matrix that the heatmap is from.
> 
> <img alt="Screen Shot 2020-07-20 at 4 45 48 PM" width="695" src="https://user-images.githubusercontent.com/57680851/87984772-7b4a3a00-caa8-11ea-8593-a5fc65363248.png">
> 
> Here, the intensity is the magnitude of gene expression and size, the percentage of cells positive.



> My apologies, I should have added more context. Please see the figure attached before-- attaching ggplot with the solution from #261, doesn't align the dotplot with the heatmap. I can't think of a way to do it either because the ggplot is from a dataframe separate from the matrix that the heatmap is from.
> 
> <img alt="Screen Shot 2020-07-20 at 4 45 48 PM" width="695" src="https://user-images.githubusercontent.com/57680851/87984772-7b4a3a00-caa8-11ea-8593-a5fc65363248.png">
> 
> Here, the intensity is the magnitude of gene expression and size, the percentage of cells positive.

Hi can you please share the code of how you did this?

Thank you!
