### ISSUE TITLE
Rotate labels of row annotation 

### ISSUE THREAD

**Issue by komalsrathi** [jokergoo/ComplexHeatmap#549]
Please provide example datasets and the code you use. It will help me to understand your problem and help you!

In the below code, how do I set the angle of rowAnnotation labels?  For e.g. I can rotate the x-axis labels using `column_names_rot = 45` but I also want to rotate the annotation label at the bottom `PCA_HCPC` by 45 degrees.

Reproducible example:

```
library(ComplexHeatmap)

# reproducible df of 20 rows and 10 columns
set.seed(100)
tmp <- matrix(rnorm(10000), nrow = 20, ncol = 10)
tmp <- as.data.frame(tmp)
colnames(tmp) <- paste0('col_', seq(1:ncol(tmp)))
rownames(tmp) <- paste0('row_', seq(1:nrow(tmp)))

# 1. test with ComplexHeatmap and dendsort
ha1 = rowAnnotation(PCA_HCPC = seq(1:10))
mat_scaled = apply(tmp, MARGIN = 1, scale) # scale rows
rownames(mat_scaled) <- colnames(tmp)
Heatmap(matrix = as.matrix(mat_scaled), 
        column_names_rot = 45,
        left_annotation = ha1)

```

![image](https://user-images.githubusercontent.com/7000615/88054035-b1c89900-cb2a-11ea-9ade-e5f4dfde5eeb.png)

**Comment by jokergoo** [comment]
Currently, you cannot set rotation for annotation names, but for you case, you can turn your row annotation to a one-column heatmap:

```r
ht1 = Heatmap(cbind(PCA_HCPC = 1:10), name = "PCA_HCPC", column_names_rot = 45)
ht_list = ht1 + Heatmap(matrix = as.matrix(mat_scaled), name = "main",
        column_names_rot = 45)
draw(ht_list, main_heatmap = "main", row_dend_side = "left")
```

![image](https://user-images.githubusercontent.com/449218/88094829-7a8ed200-cb94-11ea-80fa-22c31f264039.png)

**Comment by komalsrathi** [comment]
That would be an issue if I have categorical annotations, right?

**Comment by jokergoo** [comment]
You can also draw heatmap for the categorical values.

```r
ht1 = Heatmap(cbind(PCA_HCPC = letters[1:10]), name = "PCA_HCPC", column_names_rot = 45)
ht_list = ht1 + Heatmap(matrix = as.matrix(mat_scaled), name = "main",
        column_names_rot = 45)
draw(ht_list, main_heatmap = "main", row_dend_side = "left")
```

**Comment by jokergoo** [comment]
Rotating the annotation labels is already in my to-do list #489 (see the last one)
