### ISSUE TITLE
ggplot, annotation alignment and anno_blank

### ISSUE THREAD

**Issue by oh111** [jokergoo/ComplexHeatmap#550]
Hello, 

This is a follow-up post to the one I made yesterday and a continuation from #261. 
I have a ggplot that has no theme (void) that allows for the plot to align with the heatmap within the annotation. However, if I add a label to the ggplot, it mis-aligns with the heatmap. 
From my understanding, there is no way to add a label to the `anno_empty` category like there is for the other annotations. Is there anyway to add labels that align with the heatmap labels with either `anno_empty`  or with ggplot? 

Code for reference: 
```
g<-ggplot(ERKTargetExpression, aes(x=features.plot, y=id,col=avg.exp.scaled, size=pct.exp))+
  geom_point()+theme_void()+ theme (legend.position="none")+  scale_color_continuous(RColorBrewer::brewer.pal(name = "Blues", n = 9))

g

ha<-HeatmapAnnotation(ggplot = anno_empty(height = unit(2, "cm")))

Heatmap(vis_ligand_target,
        col=RColorBrewer::brewer.pal(name = "Blues", n = 9),
        border="black",
        cluster_rows = FALSE, 
        row_title="Ligands from T4 Exosomes",
        row_names_side = "left",
        row_title_gp = gpar(fontsize = 10),
        row_names_gp = gpar(fontsize = 8),
        cluster_columns = FALSE,
        column_title = "ERK-Target genes in S1 cells",
        column_title_side = c("top"),
        column_title_gp = gpar(fontsize = 10),
        column_names_gp = gpar(fontsize = 8),
        column_names_side = c("top"),
        width = unit(15, "cm"), 
        height = unit(8, "cm"), 
        gap=unit(100, "mm"),
        rect_gp = gpar(col= "white"),
        show_heatmap_legend = FALSE,
        bottom_annotation = ha)


decorate_annotation("ggplot", {
	vp = current.viewport()$name
	print(g, vp = vp)
	
})
```
Heatmap where it is aligned without labels 
![image](https://user-images.githubusercontent.com/57680851/88106141-faa44000-cb72-11ea-95b0-2d4892083a2f.png)

Heatmap where it is mis-aligned with labels added to the ggplot. 
![image](https://user-images.githubusercontent.com/57680851/88106223-2293a380-cb73-11ea-9020-935564c8cc70.png)

**Comment by jokergoo** [comment]
ComplexHeatmap and ggplot2 are two completely different things, and I think it is difficult to combine them perfectly. For your case, actually you can implement the plot from ggplot2 also by ComplexHeatmap. The ggplot doplot can be converted to a "dotted heatmap":

```r
m1 = matrix(rnorm(100), ncol = 10); rownames(m1) = letters[1:10]
m2 = matrix(runif(40), ncol = 10); rownames(m2) = LETTERS[1:4]

Heatmap(m1) %v%
Heatmap(m2, rect_gp = gpar(type = "none"),
	cell_fun = function(j, i, x, y, w, h, f) {
                 # you can use other ways to set `size`
		grid.points(x, y, size = unit(m2[i, j], "char"), gp = gpar(col = f), pch = 16)
	})
```

![image](https://user-images.githubusercontent.com/449218/88152277-14da2e80-cc04-11ea-8aa4-841dab0c8c86.png)

You can go to https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#customize-the-heatmap-body for the explanation of `cell_fun`.

**Comment by oh111** [comment]
Got it! thank you so much!
