### ISSUE TITLE
Error: Length or nrow of `row_split` should be same as nrow of `matrix`.

### ISSUE THREAD

**Issue by CRazyTims** [jokergoo/ComplexHeatmap#552]
Hi, 
   Here are my code. I can't split the heatmap using row_split, and column_split

    Heatmap(D1,show_row_names = FALSE,show_column_names = FALSE, col = col_fun,
        rect_gp = gpar(col = "white", lwd = 1), 
        column_title = "CD11b",column_title_gp = gpar(fontsize = 20, fontface = "bold"),
        row_split = factor(rep(c("A", "B"), 9)),
        column_split = factor(rep(c("C", "D"), 12)),
        heatmap_legend_param = list(title=NULL, at = c(-2, 0, 2),labels = c("-2", "0", "2")),
        top_annotation = HeatmapAnnotation(foo = anno_block(gp = gpar(fill = 2:3),        
                                           labels = c("Naive", "CPG"), 
                                           labels_gp = gpar(col = "white", fontsize = 15)))
        )

I put D1 dataset in attachemnt.  Row1 is row.names, and column one is col.names. 
[D1.xlsx](https://github.com/jokergoo/ComplexHeatmap/files/4978778/D1.xlsx)

Thanks!

**Comment by jokergoo** [comment]
You have 114 rows in the matrix, while the value set to `row_split` only has length of 18. It should be also length 114.

Also there are only 4 columns in the matrix, and the value for `column_split` is with length 24?

**Comment by CRazyTims** [comment]
> You have 114 rows in the matrix, while the value set to `row_split` only has length of 18. It should be also length 114.
> 
> Also there are only 4 columns in the matrix, and the value for `column_split` is with length 24?

**Comment by CRazyTims** [comment]
Thank you! Now I see the problem. Manual split might not work for me. I have to use row_km. Can I manage to reorder the split if I am using row_km and column_km? I would like the upregulated genes(red) in CPG/EaQ11 group are on the top section of the heatmap, and the upregulated genes in Naive on the bottom of the heatmap.

**Comment by CRazyTims** [comment]
> You have 114 rows in the matrix, while the value set to `row_split` only has length of 18. It should be also length 114.
> 
> Also there are only 4 columns in the matrix, and the value for `column_split` is with length 24?

Thank you! Now I see the problem. Manual split might not work for me. I have to use row_km. Can I manage to reorder the split if I am using row_km and column_km? I would like the upregulated genes(red) in CPG/EaQ11 group are on the top section of the heatmap, and the upregulated genes in Naive on the bottom of the heatmap.

**Comment by jokergoo** [comment]
If you want to manually adjusted the order, you should first generate a clustering by k-means:

```r
km = kmeans(mat, centers = ...)$cluster
```

Then control the order by converting `km` to a factor where the order is controlled by the "levels":

```r
km = factor(km, levels = ...)
Heatmap(mat, row_split = km)
```
