### ISSUE TITLE
Upset plot displaying both "intersect" and "distinct" results?

### ISSUE THREAD

**Issue by charlesfoster** [jokergoo/ComplexHeatmap#553]
Hi,

Thanks for the great package - very useful. I've successfully been using ComplexHeatmap to draw upset plots based on either a "distinct" combination matrix or an "intersect" combination matrix. Both results are useful for interpreting the patterns in my data.

I was just wondering, is it currently possible to generate an upset plot displaying both results simultaneously? Two possibilities come to mind:

(1) For each combination set, two columns next to one another: one column with the total intersection based on "intersect" mode, the other column with the total intersection based on "distinct" mode.

(2) For each combination set, one column with the total intersection height based on "intersect" mode, but with internal shading to a certain height based on "distinct mode".

If this is not currently possible, is it a feature that might be able to be implemented in the future?

Thanks,
Charles

**Comment by jokergoo** [comment]
Well, yes this is a nice suggestion!

I don't know, it seems it will make the plot difficult to read. On the other hand, it changes the internal data structure (now it will be a mixed of intersect and distinct, which also needs to change the API of `make_comb_mat()`?)

But anyway, I mark it as "enhancement" and I will work on it once I have time :)

**Comment by charlesfoster** [comment]
Great! And thanks for the hard work you put into developing these tools.

Charles
