### ISSUE TITLE
Add rectangle in specific columns in a heatmap [Question]

### ISSUE THREAD

**Issue by bblodfon** [jokergoo/ComplexHeatmap#554]
Hi @jokergoo,

In the following example, I create a simple heatmap:
```
set.seed(123)
mat = matrix(rnorm(80, 2), 8, 10)
mat = rbind(mat, matrix(rnorm(40, -2), 4, 10))
rownames(mat) = paste0("R", 1:12)
colnames(mat) = paste0("C", 1:10)

ht1 = Heatmap(mat, name = "ht1")
draw(ht1)
```

Is there a (simple) way to **add a rectangle to a specific column(s)** (let's say the 3rd or the one corresponding to a specific value, i.e. `C7`)? I was playing around with `decorate_heatmap_body` and `grid.rect` but it's more like **manually** placing the rectangle there:

```
decorate_heatmap_body(heatmap = "ht1", code = {
    grid.rect(x = 0.25, width = 0.1, gp=gpar(col="black", fill = NA, lwd = 2))
})
```

**Comment by jokergoo** [comment]
Maybe this code to make it automatic?

```r
set.seed(123)
mat = matrix(rnorm(80, 2), 8, 10)
mat = rbind(mat, matrix(rnorm(40, -2), 4, 10))
rownames(mat) = paste0("R", 1:12)
colnames(mat) = paste0("C", 1:10)

ht1 = Heatmap(mat, name = "ht1")
ht1 = draw(ht1)


co = column_order(ht1)
nc = ncol(mat)

col = "C7"
decorate_heatmap_body(heatmap = "ht1", code = {
    i = which(colnames(mat)[co] == col)
    grid.rect(x = (i-0.5)/nc, width = 1/nc, gp=gpar(col="black", fill = NA, lwd = 2))
})
```

**Comment by bblodfon** [comment]
Yes, a nice suggestion, thanks!

**Comment by FilipeFerreiraMOCHSL** [comment]
Thank you for this amazing package! This is exactly the answer I was looking for.

The reason why I'm commenting after this issue closed is because this answer doesn't work as smoothly if we create a heatmap with splits. Is there any workaround in this case? Right now what I'm doing is just removing my splits and adding rectangles as borders.

Thank you very much!
