### ISSUE TITLE
Add values to heatmap legend that don't appear in heatmap itself

### ISSUE THREAD

**Issue by leachim** [jokergoo/ComplexHeatmap#555]
Here is a simple example, I want to create a heatmap with discrete integer values, but some of the integers might not appear in the heatmap. However, I would like to have the legend go over the sequence of integers from 1:n. A little example: 

```
 Y_plot = matrix(c(0, 0, 2, 3, 4, 4, 3, 2, 2, 0), nrow=2)
  colo = c("#3182BD", "#9ECAE1", "#CCCCCC", "#FDCC8A", "#FC8D59", "#E34A33")
  names(colo) = c("0", "1", "2", "3", "4")
  labels = c("0", "1", "2", "3", "4")
  at = as.character(seq(0, 4))
  
  ht = Heatmap(Y_plot, col = colo, heatmap_legend_param = list(
    title = "Integers", title_position = "lefttop-rot",
    at=at, labels=labels)) #, legend_gp = gpar(fill = colors[names])))
  ht
```

If I change Y_plot to 
`Y_plot = matrix(c(1, 0, 2, 3, 4, 4, 3, 2, 2, 0), nrow=2)`
I observe the legend the way I would like it to be in the first example. 

Any way to get the desired behavior? I am using ComplexHeatmap, version 2.2.0. Many thanks for your help!

**Comment by jokergoo** [comment]
Then you can set like:

```r
Heatmap(Y_plot, heatmap_legend_param = list(at = 1:10))
```

**Comment by jokergoo** [comment]
OK, then I will adjust the package not to remove those break values.

**Comment by marcjwilliams1** [comment]
Thanks! Much appreciated.

**Comment by jokergoo** [comment]
I made some improvement on it. In the following example, both matrix and `foo` annotation only contain `a, b, c, d`, but the colors are defined for `a, b, c, d, e, f, g, h`. In this case, specifying `at` with `a:h` will draw all colors in the legends. Without specifying `at` will only draw colors for `a:d`.

```r
m = matrix(sample(letters[1:4], 100, replace = TRUE), 10)

ha = HeatmapAnnotation(foo = sample(letters[1:4], 10, replace = TRUE),
	col = list(foo = structure(1:8, names = letters[1:8])),
	annotation_legend_param = list(foo = list(at = letters[1:8])))

Heatmap(m, col = structure(1:8, names = letters[1:8]),
	top_annotation = ha,
	heatmap_legend_param = list(at = letters[1:8])
)
```

![image](https://user-images.githubusercontent.com/449218/96634935-80bf5680-131b-11eb-8bd3-be31f024606d.png)

**Comment by marcjwilliams1** [comment]
This is great, thanks for taking a look at this.
