### ISSUE TITLE
How to make a legend of grid.circle 

### ISSUE THREAD

**Issue by Ivy-ops** [jokergoo/ComplexHeatmap#560]
Hi Developer, 
I am using below code making heatmap. I want to add a legend by the circle size. 
`Heatmap(spr1, name = "Correlation",

        heatmap_legend_param = list(direction = "horizontal"),
        col = colorRampPalette(brewer.pal(10, "RdBu"))(256),

        top_annotation = ha,

        rect_gp = gpar(col= "white"),

        column_order= c(1:33),

        show_row_dend = FALSE,

        cell_fun = function(j, i, x, y, width, height, fill) {
          grid.circle(x = x, y = y, r = abs(mat[i, j]) * min(unit.c(width, height)), 
                      gp = gpar(fill = 'white', col = 'white'))
          if(qval$Q[i] < 0.1) {
            grid.circle(x = x, y = y, r = 0.1 * min(unit.c(width, height)), 
                        gp = gpar(fill = 'black', col = 'black'))}
          })`

The circle is added by the value size in the mat matrix.  
May I please know how to create a legend by the circle size added?

Thanks!!

**Comment by jokergoo** [comment]
You need to manually create a "circle" legend and add to the heatmap legends by `heatmap_legend_list` argument in `draw()`. See examples in https://jokergoo.github.io/ComplexHeatmap-reference/book/legends.html#add-customized-legends.

**Comment by Ivy-ops** [comment]
@jokergoo  Thanks!!

**Comment by micdonato** [comment]
Sorry to reopen this: I managed to get my legend but I have not been able to set the point size.

I tried the arguments `size` and `cex` both in the `Legend` function and in the `gpar` function inside, but nothing seems to work. 

What am I missing?

**Comment by jokergoo** [comment]
Please show me your complete code.

**Comment by micdonato** [comment]
Sorry, I edited my previous message: I used `size = unit(1:2, 'mm')` and it worked.

I would like to put it horizontal now, but the `direction = 'horizontal'` directive in the `Legend` function does not work.

Following is the code:

```
lgd_list = list(
    Legend(labels = c("higher variance"," "," "," ", "lower variance"),
           title = "\n(inverse variance)",
           type = "points",
           # ncol = 5,
           pch = 16,
           size = unit(1:5, 'mm'),
           direction = 'horizontal',
           legend_gp = gpar(
             col = rep(col_fun(1),5)
           ),
           background = 'white'
    )
  )
```

I am working on having a complete executable example.

**Comment by jokergoo** [comment]
OK, I think that is a bug. I try to fix it.

**Comment by jokergoo** [comment]
Now I fixed it.

![image](https://user-images.githubusercontent.com/449218/97357539-3a797280-189a-11eb-87fd-4de0cc6063a2.png)

Now `size` argument should work. Please update it from GitHub.

Thanks for reporting!

**Comment by micdonato** [comment]
Thanks for fixing it!

I was wondering if there was a way to have the labels of the points under the points instead of to the left.

**Comment by jokergoo** [comment]
I think currently, no.

**Comment by micdonato** [comment]
Thanks!
