### ISSUE TITLE
Slice order 

### ISSUE THREAD

**Issue by sophie2046** [jokergoo/ComplexHeatmap#561]
In the documentation, 2.7.4 Order of slices, we saw an example that turning off the cluster_column_slices, and the annotation vector got arranged in the order of the factor levels of column_split. However, when I tried it with a data frame of two factors, I got an error with 

ht<-Heatmap(mat,top_annotation = ha,show_column_names = F,**column_split = cellinfo[,c("cell.type","diagnosis")]**,column_title = "%s\n%s",name="score",row_names_gp = gpar(fontsize = 8),column_title_gp = gpar(fontsize = 8),**cluster_column_slices = FALSE**) 
 ```
>draw(ht,column_title = "Score clustering in all samples")
Error in make_cluster(object, "column") : object 'slice_od' not found
```
slice_od seemed to be an internal variable that cannot work with more than 1 factor. Is this a bug? Do we have any quick workaround?

**Comment by jokergoo** [comment]
Looks like it is a bug. Can you also attach the `mat` and `cellinfo` here?

**Comment by karagorman** [comment]
@jokergoo Has there been any update on this? I am getting the same error when trying to specify row_split to a single variable.  This issue only happens when using R version 4.0

Error: "Error in make_cluster(object, "row") : object 'slice_od' not found"

**Comment by karagorman** [comment]
It looks like the issue was caused by having row_title = "%s" in my case.  removing that argument fixed the problem

**Comment by jokergoo** [comment]
@karagorman Can you give me an example that causes the error? I cannot generate one. Thanks!

**Comment by jokergoo** [comment]
Hi, I just found this was a bug also reported by another user. Now it is fixed.
