### ISSUE TITLE
Adding side box plot for RPKM of two groups to oncoplot

### ISSUE THREAD

**Issue by beginner984** [jokergoo/ComplexHeatmap#562]
Hi

I have a complexheatmap like this save in object `hm`

![enter image description here][1]

I have `RPKM values` for these `11 genes` for `Responders (n=9)` and `Non responders(n=24)` groups

I want to show `the difference of RPKM` between two groups as a side box plot (or violin)

I have tried this

    head(df[1:5,1:5])
             1        2        3         4        5
    1 2.863344 1.898928 3.478697 2.3757564 2.135660
    2 4.212727 2.463784 7.684164 1.9982669 4.112562
    3 2.272057 1.066807 1.308542 0.7091228 4.606245
    4 3.225457 1.358011 2.204351 2.1995727 5.025283
    5 2.766198 1.628747 2.806077 1.4850733 3.077352
    > 

    > dim(df)
    [1] 11 33
    > class(df)
    [1] "data.frame"
    > 

    .boxplot = anno_boxplot(df, which = "row")
    ha_mix_right = HeatmapAnnotation(violin = .violin, bxplt = .boxplot,
                                  which = "row", width = unit(4, "cm"))

    hm+ha_mix_right

Which gives this

![enter image description here][2]

  [1]: https://i.ibb.co/7tJxZFB/Picture1.png
  [2]: https://i.ibb.co/QcyG4Mf/Rplot81.png

But by this we can not say if for instance `RPKM` values in `CCND1` is higher in non-responders (I have already checked the differences between groups for these genes so I know the direction of expression level)

I also tried this but no success

https://jokergoo.github.io/ComplexHeatmap-reference/book/more-examples.html#add-multiple-boxplots-for-single-row

Is these any way to show that here?

Thank you for any help to achieve this

**Comment by jokergoo** [comment]
How about drawing two boxplot annotations, with the same limit on x-axes?

**Comment by beginner984** [comment]
Sorry how I can do that?

I am very bad in R and what I have provided here comes from extensive googling

**Comment by jokergoo** [comment]
No problem! Then please also provide me with the code and the data you use.

**Comment by beginner984** [comment]
Hello

I have attached my whole R object + whole R code

https://www.dropbox.com/s/iw49x2xlyaoh0cz/data.RData?dl=0

https://www.dropbox.com/s/km8h7yalrdshx0z/Fresh.R?dl=0

Without trying to show RPKM values between genes I get this plot

![Rplot03](https://user-images.githubusercontent.com/43682980/90300082-c893ae80-de90-11ea-8488-69c0bbbfbfa4.png)


Sorry in this plot there are some points which whatever I try to solve the rest of plot gets disturbed

My boss says:

1- q value should not be continuous rather 0.05 0.01 or ns
2- The percentage in both group should be scaled in a way that the length of percentage box for both group is the same
3- color of top annotation is not clear enough

I then tried to add the difference of RPKM values for each gene between to groups by whisker of whatever shows this differences but I got this

![Rplot02](https://user-images.githubusercontent.com/43682980/90300199-4f488b80-de91-11ea-9f62-08cd64f762da.png)

**Comment by jokergoo** [comment]
This is what I mean. Make two boxplot annotations, one for responders group and the other one for the non-responder group:

Note, you need to take the log-transformed RPKM.

```r

 m1 = as.matrix(RPKM[, grepl("^Responders", colnames(RPKM))])
 m1 = log2(m1+1)

 m2 = as.matrix(RPKM[, grepl("^Non.?responders", colnames(RPKM))])
 m2 = log2(m2+1)

 Hm + rowAnnotation(Responders = anno_boxplot(m1, ylim = c(0, 10)), width = unit(3, "cm")) +
  rowAnnotation("Non Responders" = anno_boxplot(m2, ylim = c(0, 10)), width = unit(3, "cm"))

decorate_annotation("Responders", {
	for(at in c(0, 2.5, 5, 7.5, 10)) {
		grid.lines(c(at, at), unit(c(0, 1), "npc"), default.units = "native", gp = gpar(col = "#00000040", lty = 2))
	}
})

decorate_annotation("Non Responders", {
	for(at in c(0, 2.5, 5, 7.5, 10)) {
		grid.lines(c(at, at), unit(c(0, 1), "npc"), default.units = "native", gp = gpar(col = "#00000040", lty = 2))
	}
})
```

![image](https://user-images.githubusercontent.com/449218/90370833-54aefd00-e06e-11ea-94a1-fe172e2549aa.png)

**Comment by jokergoo** [comment]
And for the main heatmap, since the values are discrete (0 and 1), you can simply set the color as a named vector:

```r
c("-2" = "blue", "0" = "lightgrey", "1" = "red")
```

**Comment by beginner984** [comment]
Sorry when I put 

l```
gd_qvalue = Legend(title = "q-value", col = pvalue_col_fun, at = c(0, 1, 2, 3), 
                    labels = c("-2" = "blue", "0" = "lightgrey", "1" = "red"))
```
For q value I got this

![Rplot01](https://user-images.githubusercontent.com/43682980/90410899-dde02700-e0a2-11ea-9264-d840d0547bc5.png)

Is there any way to show q values as `< 0.05 ,  < 0.01 and n.s.` only instead of a range colours?
