### ISSUE TITLE
error: You should have at least two distinct break values in complexheatmap

### ISSUE THREAD

**Issue by honghh2018** [jokergoo/ComplexHeatmap#564]
Hi @jokergoo,
   Thanks to develop this greate tools,
    The matrix i put in Heatmap sparked the error like below,
     error: You should have at least two distinct break values in complexheatmap 
    Why the error occurred when using the matrix to plot heatmap using complexheatmap R package.
    the original code showing below,

    Heatmap(as.matrix(m))
   The matrix displaying below,
   
![image](https://user-images.githubusercontent.com/41668708/90485848-af2d8380-e16a-11ea-975e-57b8e727d408.png)

 Any advice would be appricated

**Comment by jokergoo** [comment]
Please explicitly set the color mapping variable:

```r
library(circlize)
col_fun = colorRamp2(c(min(mat), mean(mat), max(mat)), c("blue", "white", "red"))
Heatmap(mat, col = col_fun)
```

**Comment by honghh2018** [comment]
Appreciated the reply, the problem had be solved, thanks again,
  The eventual picture showing below,
![image](https://user-images.githubusercontent.com/41668708/90493121-8ad6a480-e174-11ea-94c7-d9f9da0384bf.png)

 the code showing below,
 I using the code posted below arrange the ht_normal and ht_tumor object with vertical position, but there are existing small 
 pictures indicating at red arrow. how can i set the proper size on the ht_normal  and ht_tumor ?
 Bothering again and hope can be solved the problem.

draw(ht_normal %v% ht_tumor)

**Comment by jokergoo** [comment]
OK, then please attach the full code that you used to draw the heatmap.

**Comment by honghh2018** [comment]
the full code posted below,
###step01 
# library(infercnv)
# library(ComplexHeatmap)
# library(circlize)
# library(data.table)



### step04 

gn <- rownames(c@expr.data[,tumor_loc])
expr<-c1@expr.data[,tumor_loc]  ###
geneFile <- read.table('./CNV2/geneOrderingFile.txt')
length(geneFile$V1);length(gn)


sub_geneFile <-  geneFile[geneFile$V1%in%gn,]
dim(sub_geneFile)

identical(rownames(expr),as.character(sub_geneFile$V1)) # 

# 
expr1<-expr[as.character(sub_geneFile$V1),]


### step05 
expr2<-as.data.frame(expr1)
expr2$chr <- as.character(sub_geneFile$V2) 


expr3<-expr2[!grepl("^[A-Z]",expr2$chr,perl = T),]

### step07 
sub_geneFile1<-sub_geneFile[!grepl("^[A-Z]",sub_geneFile$V2,perl = T),]


### step08 

new_cluster <-as.factor(expr3$chr)
table(expr3$chr)
length(new_cluster)
# 
get_group_color_palette <- function () {
  return(colorRampPalette(RColorBrewer::brewer.pal(12, "Set3")))
}
color <- get_group_color_palette()(length(unique(expr3$chr)))
# 

### step08 

top_color <- HeatmapAnnotation(
  cluster = anno_block(gp = gpar(fill = color), 
                       labels = levels(new_cluster), 
                       labels_gp = gpar(cex = 0.9, col = "black")))


### step09 
expr3$chr<-NULL
n=t(expr3)


### step10 

ht_tumor = Heatmap(as.matrix(n),
                   cluster_rows = T,
                   cluster_columns = F,
                   show_column_names = F,
                   show_row_names = F,
                   column_split = new_cluster, 
                   heatmap_legend_param = list(
                     title = "Modified Expression",
                     title_position = "leftcenter-rot", 
                     at=c(0.4,1.6), 
                     legend_height = unit(3, "cm") 
                   ),
                   top_annotation = top_color,
                   row_title = "Observations (Cells)",
                   row_title_side = c("right"),
                   column_title = "Genomic Region",
                   column_title_side = c("bottom"))

draw(ht_tumor, heatmap_legend_side = "left") # 
### 

(normal_loc <- c168@reference_grouped_cell_indices)
normal_loc <- normal_loc$`Endothelial cells` 

gn1 <- rownames(c168@expr.data[,normal_loc])

expr_normal<-c168@expr.data[,normal_loc]  


dim(sub_geneFile1)
expr_normal1 <-expr_normal[rownames(expr_normal)%in%sub_geneFile1$V1,]




expr_normal2<-expr_normal1[as.character(sub_geneFile1$V1),]



expr_normal2<-data.frame(expr_normal2)
expr_normal2$chr<-as.character(sub_geneFile1$V2) 
table(as.character(sub_geneFile1$V2))
View(expr_normal2[,ncol(expr_normal2)])

new_cluster<-as.factor(expr_normal2$chr)

expr_normal2$chr<-NULL
m<-t(expr_normal2)

  
plot(m)
dim(m)
is.na(m)
m1<-log(m)
View(m1[1:10,1:10])
Heatmap(as.matrix(m1))
fwrite(data.frame(m),file = 'c168_matrix.tsv',sep = '\t',col.names = T,row.names = T)
table(colnames(m)%in%colnames(n))
identical(colnames(m),colnames(n))
tt<-matrix(rep(1,10),ncol=2)


ht_normal = Heatmap(as.matrix(m1),
                    col = color, 
                    cluster_rows = T,
                    cluster_columns = F,
                    show_column_names = F,
                    show_row_names = F,
                    column_split = new_cluster,
                    row_title = "References (Cells)",
                    row_title_side = c("right"),
                    row_title_rot = 90,
                    row_title_gp = gpar(fontsize = 25),
                    column_title = NULL, 
                    heatmap_legend_param = list(
                      title = "Modified Expression",
                      title_position = "leftcenter-rot",
                      title_gp = gpar(fontsize = 20),#
                      at=c(0.4,1.6), #
                      legend_height = unit(6, "cm")),#
                    width = 20, height = 5)

**Comment by honghh2018** [comment]
draw(ht_normal %v% ht_tumor)

**Comment by jokergoo** [comment]
In `ht_normal = Heatmap(as.matrix(m1), ...)`, delete the arguments `width = 20, height = 5`.

**Comment by honghh2018** [comment]
@jokergoo  thanks very much for those help, the problems had solved, based on your above tips.
 But i get the another question regarding the legend range showing different between ht_normal and ht_tumor,
![image](https://user-images.githubusercontent.com/41668708/90500253-3a177980-e17d-11ea-8504-68d7a713fff4.png)
  I hope the ht_normal legend range same as ht_tumor legend. because of the ht_normal value aready processed with cutoff 
between 0.4 and 1.5
 so i hope can be solved this issue with your help.
 Best,
hanhuihong

**Comment by jokergoo** [comment]
Then you can set the same color mapping function/variable to both heatmaps.

**Comment by honghh2018** [comment]
Hi @jokergoo,
   The  same legend range had been done with your help.
    But i encounter another issue when there was big matrix including 8900 cells on rows and 11401 genes on column to draw big heatmap.
    The error showing below,
     `use_raster` is automatically set to TRUE for a matrix with more than
2000 rows. You can control `use_raster` arugment by explicitly setting
TRUE/FALSE to it. Set `ht_opt$message = FALSE` to turn off this
message.
    the code showing below,
    png("all_tumor_merge_heatmap.png",width = 1800,height = 2500)
Heatmap(as.matrix(n),
                   cluster_rows = T,  
                   cluster_columns = F,
                   show_column_names = F,
                   show_row_names = F,
                   column_split = new_cluster,
                   heatmap_legend_param = list(
                     title = "Modified Expression",
                     title_position = "leftcenter-rot", 
                     at=c(0.4,1.6), 
                     legend_height = unit(3, "cm") 
                   ),
                   top_annotation = top_color,
                   left_annotation = left_annotation,
                   row_title = "Observations (Cells)",
                   row_title_side = c("right"),
                   column_title = "Genomic Region",
                   column_title_side = c("bottom"))

dev.off()

**Comment by honghh2018** [comment]
The error supplement.
error The width or height of the raster image is zero, maybe you forget to
turn off the previous graphic device or it was corrupted. Run
`dev.off()` to close it.
stop

**Comment by jokergoo** [comment]
Can you try to run `dev.off()` several times and rerun your code again? Maybe some graphics devices are not turned off in the previous fails? If the error still comes, please send me the matrix object `n`, then I can have a check.

**Comment by honghh2018** [comment]
Hi @jokergoo ,
     i get the result png picture showing below,
    
![image](https://user-images.githubusercontent.com/41668708/90706056-e87b0600-e2c6-11ea-9487-8df79f241c88.png)
  
     `use_raster` is automatically set to TRUE for a matrix with more than
2000 rows. You can control `use_raster` arugment by explicitly setting
TRUE/FALSE to it. Set `ht_opt$message = FALSE` to turn off this
message.
error: Length of `labels` should be as same as number of slices.
 how can i fix the row annotation when the error -Length of `labels` should be as same as number of slices.-occurred.
 how can i send the data to you and solved this problem?
  Best,
  hanhuihong

**Comment by jokergoo** [comment]
You can send the data and the code you used to my email address, or you can put the data to any online storage and send me the link.

**Comment by honghh2018** [comment]
Hi @jokergoo , thanks all those help. it would be good for me.
     I encounter the line drawed with chromosome region problem.
      the line among chromosomes just on above one sample not extent along with below samples. how can i fix this problem?  
     As to draw black line for each chromosome region since I would send the data to you through email with your mention above.
       the wrong line drawed pciture showing below,
      
![image](https://user-images.githubusercontent.com/41668708/90767264-7be02580-e31f-11ea-8911-d3aaabe6dd49.png)
       i hope the line can be draw like below picture at red line ,
![image](https://user-images.githubusercontent.com/41668708/90767536-f9a43100-e31f-11ea-8d96-3984f15ae7ae.png)
     Best,
     hanhuihong

**Comment by honghh2018** [comment]
Hi @jokergoo , where your email address can be sent ?

**Comment by jokergoo** [comment]
Here: 

https://github.com/jokergoo/ComplexHeatmap/blob/master/DESCRIPTION#L7

**Comment by honghh2018** [comment]
Hi @jokergoo  It is mailed to already.

**Comment by honghh2018** [comment]
Hi @jokergoo ,
     Mailed error with z.gu@dkfz.de from Tencent QQ email.
      There was  question about data delivery? so what should i do for sending the data to your email?
Best,
hanhuihong

**Comment by jokergoo** [comment]
Then send to zuguang.gu@gmail.com

**Comment by honghh2018** [comment]
Hi @jokergoo ,
   i send the data from @gmail, Could you receive the email from gmail server ?
   The emailing picture showing below,
![image](https://user-images.githubusercontent.com/41668708/91010542-44ba8e80-e615-11ea-8d38-190a253927f2.png)
 Best,
 hanhui

**Comment by honghh2018** [comment]
Hi @jokergoo,

the picture arrow showing the white line on it,   why the white line exists on the picture ? how can i remove this white line ?
![image](https://user-images.githubusercontent.com/41668708/91040102-3fbf0480-e640-11ea-9655-830a033de992.png)
Best,
hanhuihong

**Comment by jokergoo** [comment]
I think this is due to the png output. I also saw it several times. Can you directly save as a pdf? or slightly change the size of the png, these lines might disappear.

**Comment by jokergoo** [comment]
I cannot access the .7z file from your mail. 

I checked your code and I think the problem is in the `decoration_heatmap_body()` use or the `draw_x_line()` you've defined. I noticed you actually split the rows and columns of the heatmap, then when you use `decoration_heatmap_body()`, you should also specify `row_slice` and `column_slice` argument. By default, it is the first slice and that is why you always see the lines are only added in the first slice.

**Comment by honghh2018** [comment]
@jokergoo ,
  Thanks, i aware now that issue when you remind me of the function your posted above.
   even though i follow your advices, i still did not solved this problem.
   my code showing below,
    draw_x_line=function(x,ht1,color){
  decorate_heatmap_body(ht1, 
   {
      grid.lines(c(x, x), c(0, 1), gp = gpar(lty = 2, lwd = 2, col=color))
   },
      column_slice = 23
   )
}


#gray91
Heatmap(as.matrix(n),
        name = "ht_normal",
        col = c("blue","#EEEEEE","red"),
        cluster_rows = F,  ##
        cluster_columns = F,
        show_column_names = F,
        show_row_names = F,
        column_split = new_cluster, 
        heatmap_legend_param = list(
          title = "Modified Expression",
          title_position = "leftcenter-rot", 
          #at=c(0.4,1.6), 
          at=c(-1,1),
          legend_height = unit(3, "cm") #
        ),
        top_annotation = top_color,
        left_annotation = left_color,
        row_split = row_split,
        row_title = "Observations (Cells)",
        row_title_side = c("right"),
        column_title = "Genomic Region",
        column_title_side = c("bottom"))
sapply(x, function(x)draw_x_line(x,ht1="ht_normal",color="black")) 

dev.off()  
  I want to draw black line similiar to below picture, the red arrow,
![image](https://user-images.githubusercontent.com/41668708/91694619-7399ad00-eb9f-11ea-8a06-c0e1f8ff97f0.png)

   
 sorry to bother you again.
  I hope can be solved this problem through your help
  Regards,
   hanhuihong

**Comment by honghh2018** [comment]
I set the decorate_heatmap_body like below, but it just add black line on last slice 
draw_x_line=function(x,ht1,color){
  decorate_heatmap_body(ht1,
   {
      grid.lines(c(x, x), c(0, 1), gp = gpar(lty = 2, lwd = 2, col=color))
   },
      row_slice = 8
   )
}


![image](https://user-images.githubusercontent.com/41668708/91709433-58d23300-ebb5-11ea-917a-2d3612750942.png)
