### ISSUE TITLE
how to save the heatmap to a high resolution tiff

### ISSUE THREAD

**Issue by Ivy-ops** [jokergoo/ComplexHeatmap#567]
Hi Developer, 

May I know how to save the heatmap to a high resolution tiff? Enclosed please see my code, which produce a bad pdf file, which can not be opened. It is not tiff either. Thanks!!

> list <- 
> Heatmap(spr$r, name = "correlation", col = pvalue_col_fun, show_row_dend = FALSE,border = TRUE,
>         heatmap_legend_param = list(direction = "horizontal")) +
> Heatmap(mat, name = "sqrt(proportion)", heatmap_legend_param = list(direction = "horizontal"),
>         col = colorRamp2(c(0, 0.2, max(mat)), brewer.pal(9, 'Purples')[c(1,5,9)]),
>         top_annotation = ha, column_gap = unit(1, "mm"), 
>         border = TRUE,
>         cell_fun = function(j, i, x, y, width, height, fill) {
>           if(qval$Qvalue.perm[i] < 0.1) {
>             grid.circle(x = x, y = y, r = unit(1/20,'cm'), gp = gpar(fill = 'black', col = 'black'))
>             }
>         },
>         column_split = factor(c(rep("a",21), rep("b", 12))),
>         rect_gp = gpar(col= "white"),
>         column_order= c(1:33),
>         show_row_dend = FALSE,
>         row_names_gp = gpar(col = spr$grp),
>         row_names_max_width = max_text_width(rownames(spr1), gp = gpar(fontsize = 18))
>         ) 
> 
> lgd_list = list(
>   Legend(labels = c(''), title = "q < 0.1", type = "points", pch = 16, 
>          legend_gp = gpar(col = 'black'))
> )
> 
> pdf('Fig1f.pdf', width = 8, height = 8)
> draw(list, merge_legend = TRUE, 
>      heatmap_legend_side = "bottom", annotation_legend_side = "bottom", 
>      annotation_legend_list = lgd_list, use_raster = TRUE, 
>      raster_device = "tiff")

**Comment by jokergoo** [comment]
PDF should not look bad. Can you send me the pdf file you created?

**Comment by Ivy-ops** [comment]
Hi @jokergoo,
The image is a bad broken file, which can not be opened. Any suggestions?
![image](https://user-images.githubusercontent.com/61573164/90785807-655aaf80-e2c8-11ea-8368-28c6c0307e0e.png)

**Comment by jokergoo** [comment]
This is weird. This error is mainly because of an empty pdf output. Can you make sure something is written into the PDF? Or can you do:

```r
pdf(...)
ht = Heatmap(...)
draw(ht)
dev.off()
```

**Comment by Ivy-ops** [comment]
Hi @jokergoo 
It works now. Yes, I missed dev.off(), which caused the error file. OvO
Tons of thanks!!
