### ISSUE TITLE
Annotations not matching with clustered rows

### ISSUE THREAD

**Issue by ryanmboileau** [jokergoo/ComplexHeatmap#568]
Hello,

I have been running into many issues with correctly mapping annotations to rows in my heatmap and I am hoping someone may be able to help.

I have the following vectors where I would like to annotate genesofinterest with genename.state which is matched to genesofinterest in the same order. My heatmap is a matrix containing gene expression data for genes of interest which become clustered by row in an order that is different than my vector genesofinterest. However, the annotation does not carry over to my heatmap as shown below.  For example, Nanog should be annotated as "Naive". Heatmap also does not seem to be recognizing my color scheme. I have tried rearranging the order of genesofinterest, and setting levels of genename.state, but the results are generally the same. Though laborious I have tried to manually set each annotation, but Heatmap does not follow my input. Thoughts or suggestions are welcome thank you! 

```r
genesofinterest <- c("Nanog", "Esrrb", "Nr0b1", "Nr5a2", "Tfcp2l1", "Tbx3", "Klf2", "Klf4", "Klf5", "Dppa3", "Prdm14", "Zfp42", "Otx2", "Zic2", "Pou3f1", "Sox11", "Dnmt3a", "Dnmt3b", "Lin28a", "Mir302b", "Fgf5", "Foxa2", "T","Dnmt3l")
genename.state <- c("Naive", "Naive", "Naive", "Naive", "Naive", "Naive", "Naive", "Naive", "Naive", "Naive", "Naive", "Naive", "Formative", "Formative", "Formative", "Formative", "Formative", "Formative", "Formative", "Formative", "Formative", "Formative", "Formative","Formative")

genename.state <- as.data.frame((genename.state))
rownames(genename.state) <- genesofinterest
colours <- list("genename.state" = c("Naive" = "gray", "Formative" = "gray45"))
ha <- rowAnnotation(df = genename.state, col = colours)

Heatmap(annotlcpmselectWT,
        column_order = c("NWT", "FWT"),
        show_column_dend = FALSE,
        col = col_fun,
        heatmap_legend_param = list(title = "Normalized Log2CPM"),
        right_annotation = ha)
```

![image](https://user-images.githubusercontent.com/40179753/90943937-ff0d8400-e3d0-11ea-8975-5cb37d4c667a.png)

**Comment by jokergoo** [comment]
Can you check whether the row names of `annotlcpmselectWT` have the same order as `genesofinterest`?
