### ISSUE TITLE
Kmeans clustering for multiple ChIPSeq

### ISSUE THREAD

**Issue by ckuenne** [jokergoo/ComplexHeatmap#57]
Hi,

is it possible to do the kmeans clustering based on multiple normalized matrices? In your examples the clustering is strictly based on only one matrix (http://bioconductor.org/packages/devel/bioc/vignettes/EnrichedHeatmap/inst/doc/EnrichedHeatmap.html#toc_12). I am trying to plot two conditions of the same histone modification and would like to clearly separate the more/less modified regions by conditions.

the effect i hope for looks something like this using deeptools:
![deeptools](https://cloud.githubusercontent.com/assets/5773626/17735494/c43431ca-6482-11e6-8098-3607162a36c7.png)

Best,
Carsten

**Comment by jokergoo** [comment]
Hi, the package only allows k-means clustering by one matrix, but actually you can perform clustering on the combined matrix and pass the group classification to the `EnrichedHeatmap()` function:

```{r}
mat1 = normalizeToMatrix(peak1, tss)
mat2 = normalizeToMatrix(peak2, tss)
mat = cbind(mat1, mat2)
km = kmeans(mat)$cluster

EnrichedHeatmap(mat1, split = km, cluster_rows = TRUE) + EnrichedHeatmap(mat2)
# or
ht_list = EnrichedHeamtap(mat1) + EnrichedHeatmap(mat2)
draw(ht_list, main_heatmap = 1, split = km, cluster_rows = TRUE)
```

If the hierarchical clustering is also applied on the combined matrix:

 ```{r}
mat1 = normalizeToMatrix(peak1, tss)
mat2 = normalizeToMatrix(peak2, tss)
mat = cbind(mat1, mat2)
km = kmeans(mat)$cluster

library(dendextend)
l1 = km == 1
dend1 = as.dendrogram(hclust(dist(mat[l1, ])))
row_od1 = order.dendrogram(dend1)
l2 = km == 2
dend2 = as.dendrogram(hclust(dist(mat[l2, ])))
row_od2 = order.dendrogram(dend2)
row_order = c(which(l1)[row_od1], 
		      which(l2)[row_od2])

ht_list = EnrichedHeamtap(mat1) + EnrichedHeatmap(mat2)
draw(ht_list, main_heatmap = 1, split = km, row_order = row_order)
```

In above code, we applied row clustering for group 1 and group2 separately, and then construct the row order based on the order of the two clusterings.

**Comment by ckuenne** [comment]
Looks promising, thanks for helping out!

**Comment by crazyhottommy** [comment]
Hi Zuguang,

a very close related question. I just found this python package to do similar thing.
please see [Identify dynamic patterns part of the documentation](http://fluff.readthedocs.io/en/latest/usage.html).

Is it the same to what your code did? (cbind matrix together and do a kmeans on the combined matrix and use split=km to order the rows)
 I prefer to use R as I can take full advantage of `ComplexHeatmap`.

Thanks,
Ming

**Comment by jokergoo** [comment]
Yes, you are total right : p
