### ISSUE TITLE
Repel row labels while plotting them partially

### ISSUE THREAD

**Issue by parveendabas** [jokergoo/ComplexHeatmap#570]
Hi

Thanks for the great package. 

Is it possible to repel the row labels in the heatmap?

![Screen Shot 2020-08-24 at 10 35 19 AM](https://user-images.githubusercontent.com/7768607/91057773-a834c400-e5f5-11ea-8b9d-a662c3603c7d.png)

**Comment by jokergoo** [comment]
Check https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html#mark-annotation
