### ISSUE TITLE
how to combine HeatmapList and ggplot?

### ISSUE THREAD

**Issue by lizhaozhi** [jokergoo/ComplexHeatmap#571]
How can I combine a HeatmapList and a ggplot object use function like ggarrange?

**Comment by jokergoo** [comment]
You can use packages like cowplot:

```r
p1 = grid.grabExpr(draw(Heatmap(...)))
p2 = ggplot(...) + ...
plot_grid(p1, p2, ...)
```

**Comment by imbaterry11** [comment]
I don't know why, but on my end, grid.grabExpr() seems not work for a HeatmapList. If works fine for a single heatmap though.
