### ISSUE TITLE
Cryptic error message if color list is not a vector

### ISSUE THREAD

**Issue by asalt** [jokergoo/ComplexHeatmap#572]
This is the proper way to make a simple annotation.
`ha = columnAnnotation(foo=c('1', '2', '3'), col=list(foo=c('1'='red', '2'='blue', '3'='purple')))`

But if the color mapping itself is a list and not a vector like this:

`ha = columnAnnotation(foo=c('1', '2', '3'), col=list(foo=list('1'='red', '2'='blue', '3'='purple')))`

we get:

`
Error in (function (name, value, col, fun, label = NULL, na_col = "grey",  : 
  object 'color_mapping' not found`

This has happened to me more than once in instances where I am passing variables around from function to function and pass in the wrong object.

Despite my limited understanding of R, it appears that this check is false (as a list is not atomic, like the vector is).
In effect, `color_mapping` never gets defined, resulting in the error message. 
https://github.com/jokergoo/ComplexHeatmap/blob/eb684e19efc1f57f06306bf3d01708e23c484ef9/R/SingleAnnotation-class.R#L456

Trying to accommodate all sorts of different inputs is probably not worthwhile. Instead, a simple error message of "invalid color mapping format! must be a vector" might be helpful when the user is debugging their code.

**Comment by jokergoo** [comment]
Thanks for looking into it! Now it is improved.
