### ISSUE TITLE
Question about annot_zoom() ?

### ISSUE THREAD

**Issue by lizhaozhi** [jokergoo/ComplexHeatmap#573]
Hi, 

how can I create following plot with annot_zoom()?
Thanks for your idea.

<img width="586" alt="Picture1" src="https://user-images.githubusercontent.com/46610946/91498160-48584a80-e88d-11ea-9222-75d808905096.png">

**Comment by jokergoo** [comment]
Have you checked the documentation? It is here:

https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html#zoom-annotation

**Comment by lizhaozhi** [comment]
> Have you checked the documentation? It is here:
> 
> https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html#zoom-annotation

Thanks.
