### ISSUE TITLE
Getting q-value discontinuous

### ISSUE THREAD

**Issue by beginner984** [jokergoo/ComplexHeatmap#574]
Hello

I have been trying to:

1- Make q-value on this plot `discontinuous`
2- Scaling percentage box in a way in which the length of box for both groups be the same (in both groups be 60% not in one group max is 60% and in one group max is 40%)

But I really don't know how to do this

For q value I got this

![Rplot01](https://user-images.githubusercontent.com/43682980/90411292-74144d00-e0a3-11ea-9a63-53a052580073.png)

This is my whole code and data

https://www.dropbox.com/s/iw49x2xlyaoh0cz/data.RData?dl=0
https://www.dropbox.com/s/km8h7yalrdshx0z/Fresh.R?dl=0

Help me please

**Comment by jokergoo** [comment]
> 1- Make q-value on this plot discontinuous

This is a task of data transformation. I assume you want to categorize the p-values into "not significant" and "significant", then you can do:

```r
p2 = matrix("", nrow = nrow(p), ncol = ncol(p))
p2[p < 0.05] = "sig"
```

Now `p2` is a character and discrete matrix.

> 2- Scaling percentage box in a way in which the length of box for both groups be the same (in both groups be 60% not in one group max is 60% and in one group max is 40%)

You can set the ranges on x-axes by:

```r
HeatmapAnnotation(foo = anno_barplot(..., axis_param(xlim = c(0, 0.6))))
```

**Comment by beginner984** [comment]
Sorry

When I put 

`pvalue_col_fun = colorRamp2(c("ns", "ns", "*","**"), c("blue","green", "grey", "darkred"))

I got this error

`Error in rg[2] - rg[1] : non-numeric argument to binary operator
``

and for second point when I put 

> column_ha = HeatmapAnnotation(Gender = ```
d2$Gender,pT.Stagt=d2$pT.Stage,pN.Stagt=d2$pN.Stage,pM.Stagt=d2$pM.Stage,Signature=d1$Subtype,axis_param(xlim = c(0, 0.6)))
Error: annotations should have names.
> 
```
I really don't know how together this work

**Comment by jokergoo** [comment]
`colorRamp2()` is only used for making a continuous color mapping. You should construct a named vector:

```r
pvalue_col_fun = structure(names = c("ns", "ns", "*","**"), c("blue","green", "grey", "darkred"))
```

**Comment by beginner984** [comment]
Sorry how I can make the percentage box at the same length? You can see one box gets 60 as max and another one get 40 as max

**Comment by jokergoo** [comment]
Ah... Sorry, it should be set as:

```
anno_barplot(..., ylim = c(0, 0.6))
``

**Comment by beginner984** [comment]
Thank you by adding `ylim = c(0, 0.6)` , I obtain this

![Rplot](https://user-images.githubusercontent.com/43682980/91634783-f3cae180-e9ea-11ea-9ace-6015aae4ec40.png)

**Comment by beginner984** [comment]
Sorry for q value when I put 

`pvalue_col = structure(names = c("ns", "ns", "*","**"), c("blue","green", "grey", "darkred"))
`

Here I get this error

```
> Heatmap(mat, border = T, show_column_names = F,
+         rect_gp = gpar(col = "white", lwd = 1),
+         column_split = response$response, 
+         col = col_fun,
+         show_column_dend = F,
+         show_row_dend = F,
+         left_annotation = left_annotation,
+         right_annotation = right_annotation)
Error: foo: cannot map colors to some of the levels: 2.79588001734408,
-0.000434077479318593, 2.97469413473523, 1.95860731484178, 2.99913227846877,
1.09151498112135, 1.67778070526608, 3
```

**Comment by jokergoo** [comment]
As I have answered for your first question:

> 1- Make q-value on this plot discontinuous

This is a task of data transformation. I assume you want to categorize the p-values into "not significant" and "significant", then you can do:

```r
p2 = matrix("", nrow = nrow(p), ncol = ncol(p))
p2[p < 0.05] = "sig"
```

You need to convert your p-value matrix to a discrete character matrix.

**Comment by beginner984** [comment]
Thank you so much worked as you advised but color of legend is not changing 

![Rplot01](https://user-images.githubusercontent.com/43682980/91661514-7da2a980-ead4-11ea-8fc7-c8628ae2836a.png)
