### ISSUE TITLE
make_comb_mat fails for lists with greater than 31 items

### ISSUE THREAD

**Issue by docmanny** [jokergoo/ComplexHeatmap#575]
Hi, 

There's a problem with the implementation of `make_comb_mat`, specificially with its use of the `intToBits` function. Whenever its given a list with more than 31 items, it raises the warning `In intToBits(x) : NAs introduced by coercion to integer range`. When its a 32-item list, it doesn't seem to show any additional issues, but a list longer than 32 items will have NA's in the combination name, and fail to graph. 

## Code To Reproduce the Issue
```
library(magrittr)
library(ComplexHeatmap)
library(stringi)
# A list with 31 random names and a random subset of 5 LETTERS
list.work <- replicate(31, LETTERS[sample(1:26, size = 5)], simplify = F) %>% set_names(stringi::stri_rand_strings(31, 10))

# A list with 32 random names and a random subset of 5 LETTERS
list.work.warning<- replicate(32, LETTERS[sample(1:26, size = 5)], simplify = F) %>% set_names(stringi::stri_rand_strings(32, 10))

# A list with 33 random names and a random subset of 5 LETTERS
list.will.fail<- replicate(33, LETTERS[sample(1:26, size = 5)], simplify = F) %>% set_names(stringi::stri_rand_strings(33, 10))

# no problems
list.work %>% 
  make_comb_mat() %>% 
  Upset()

# Throws warnings, but doesn't fail
list.work.warning %>% 
  make_comb_mat() %>%
  Upset()

# Throws warnings, fails to plot bar graphs
list.will.fail %>% 
  make_comb_mat() %>% 
  Upset()

```

This makes sense, since the `intToBits` function maxes out at a 32-bits. I did see that there's a `make_comb_mat_from_matrix` function called internally in `make_comb_mat` which has a custom `intToBinary` function with the guilty function.

**Comment by jokergoo** [comment]
Thanks! I will have a check.

Can you tell me the version of the package you are using?

**Comment by docmanny** [comment]
It was version 2.4.3, but I also tried it using the Github master at the time!

**Comment by jokergoo** [comment]
Yes, that was a bug. I haven't considered the scenario with more than 31 sets.

**Comment by jokergoo** [comment]
Emm. currently, it is difficult to support a number of sets larger than 31. It is not only a problem of `intToBinary()` function, but also a problem of internally initializing a matrix with `2^n - 1` rows. Maybe we need a better algorithm for solving this problem. Now I mark it as a long-term plan.
