### ISSUE TITLE
offset OncoPrint and top_annotation

### ISSUE THREAD

**Issue by chris-kreitzer** [jokergoo/ComplexHeatmap#577]
Hi all :)
Firstly, I have to emphasise my joy about your package ~ it's indeed amazing. Thanks :)

However, lately I came across a (maybe easy to solve) issue:
I am creating a `oncoPrint()` with `top_annotation` coming from a HeatmapAnnotation object.
the HeatmapAnnotation object itself obtain its values from a meta data.frame(). Basically, works just fine.

However, I can't figure a way how to control the gap between the top_annotation and the oncoPrint itself (I know how to change the gap between the top_annotation elements with `gap = unit(c(2.5, 5, 10), "mm")` but not how to change to the oncoprint...

Moreover, I am struggling with the column_titles. I don't know why (and how to turn off) but I would like to turn off the column titles (groups) in top_annotation ... 

many many thanks in advance :)

Best,
chris

**Comment by jokergoo** [comment]
To change the space between top annotation and the heatmap, set, e.g.

```r
 ht_opt$COLUMN_ANNO_PADDING = unit(4, "mm")
```

For the second question, can you just set `column_title = NULL`?

**Comment by chris-kreitzer** [comment]
Many many thanks,
Worked just perfectly 👍 

Best,
chris.
