### ISSUE TITLE
How to put autogenerated legends to one column?

### ISSUE THREAD

**Issue by gorgitko** [jokergoo/ComplexHeatmap#578]
Hello,

is there some way to put the autogenerated legends like this to one column? Actually, annotation legends are not the problem, but I don't know how to control the color one. I went through the examples in the reference book, looked at `heatmap_legend_param` etc.

Thanks in advance for a reply :slightly_smiling_face: 

```
library(ComplexHeatmap)
m <- matrix(rexp(200, rate = .1), ncol = 20)
Heatmap(m, top_annotation = HeatmapAnnotation(ann = rep(c("A", "B"), each = 10)))
```
![complexheatmap](https://user-images.githubusercontent.com/15315342/92253665-15870580-eed0-11ea-84fe-69e8e2b3be21.png)

**Comment by jokergoo** [comment]
Yes,

```r
ht = Heatmap(...)
draw(ht, merge_legend = TRUE)
```

**Comment by gorgitko** [comment]
Thanks a lot!
