### ISSUE TITLE
White vertical lines appearing across plot

### ISSUE THREAD

**Issue by dn-ra** [jokergoo/ComplexHeatmap#586]
Hello,

Great work on this package. I'm finding it very useful.
I'm preparing some plots for submission and there is an artifact in the image that is very distracting. There are vertical white lines appearing across the whole plot, which don't match heatmap values or NA values. Please see image attached.

As you can also see from the attached code, the na values are set to black, and there is no white in palette I have used which has the central zero value represented by a beige colour. It's also crossing a part of the plot where there are only NA values.

Rows are split just once by the two experiments and there is no column splitting. I don't see where those white lines are coming from and I'm hoping you might be able to shed some light on it?

Thanks so much!

![complexheatmapwhitelines](https://user-images.githubusercontent.com/47837238/93418958-e53b6000-f8ee-11ea-9333-9d741a695cfe.png)

```
ma <- nrow(all_heatmap[[1]])
mi <- ma-5000
s <- seq.int(mi, ma)
lab <- seq(25000,30000,250)
lab_c <- which(s %in% lab == TRUE)
lab <- s[lab_c]

annot_cols <- as.character(c( '#FFFFB3', '#BEBADA', '#FB8072', '#80B1D3', '#FDB462', '#B3DE69'))
names(annot_cols) <- names(meth_matrix)
transcript_annot <- rowAnnotation('transcript' = rep(names(all_heatmap), each = expected_experiments),col = list(transcript = annot_cols) )
experiment_annot <- rowAnnotation('experiment' = rep(as.character(a) , times=length(all_heatmap)))
coord_annot <- HeatmapAnnotation('Genome Position' = anno_mark(at = lab_c, labels= lab, which = 'column', side = 'bottom'))


cols <- brewer.pal(n = 11, name = "RdYlBu")
#cols <- viridisLite::viridis(21, option = "A")
col_fun <- colorRamp2(c(-1,0,1), c('blue','antiquewhite','red'))
#col_fun <- colorRamp2(c(-1,0,1), rev(cols[c(2,6,10)]))
b_tail <- t(tail(b, n=5000)) 
b_square <- b_tail^2
b_sign <- sign(b_tail)
  
hm_complete <- Heatmap(b_square * b_sign, na_col = 'black', cluster_rows=FALSE,cluster_columns = FALSE, row_labels = a,  show_column_names = FALSE, show_row_names = FALSE,
row_split = rep(as.character(a) , times=length(all_heatmap)) , col=col_fun,
row_gap = unit(1, 'mm'), bottom_annotation = coord_annot, width = unit(30, 'cm'), height = unit(20, 'cm'))  +  #right_annotation = transcript_annot,
#name = 'Methylated fraction', row_title_rot = 0,
#row_title_gp = gpar(cex=0.9)) +
transcript_annot + experiment_annot

draw(hm_complete)
```

**Comment by jokergoo** [comment]
I guess you saved the plot in PNG? I also saw this several times and I believe this is due to the `png()` function. You can either save it as a pdf, or sightly change the size of the png file, or change other png device such as `Cairo::CairoPNG`.

**Comment by dn-ra** [comment]
Unfortunately not. I saved this one with `pdf()`. I just tried it with `CairoPNG` and `CairoPDF` and it gives the same issue

Dan

**Comment by jokergoo** [comment]
How about changing another pdf viewer. I think it is an image rendering problem, not a ComplexHeatmap problem. E.g. if you save it in SVG, I guess the white lines will disappear.

**Comment by dn-ra** [comment]
Solved it! It is indeed a rendering problem but saving it in different file formats didn't fix it. 
In the end I switched `use_raster` to `F` and now it's perfect.

Thanks for your help, and once again great work on an awesome package.

**Comment by jokergoo** [comment]
Ah, I forgot that. Then if you want to reduce the final image by setting `use_raster = TRUE`, then you can also set e.g. `raster_device = "jpeg"` to change to another device.
