### ISSUE TITLE
draw(..., silent=TRUE)

### ISSUE THREAD

**Issue by idavydov** [jokergoo/ComplexHeatmap#587]
It is very easy to save a heatmap to a variable without plotting. But many aesthetics can be only adjusted in the `draw` method.

It would be great if I could prevent `draw()` from actually drawing and only get an object, which can be later plotted using `print()`.

```
library(ComplexHeatmap)

x <- matrix(rnorm(100), nrow=10)

my_plot <- draw(Heatmap(x))
# this will plot for the second time
print(my_plot)
```

It is in principle possible to use `grid.grabExpr`, as suggested in the manual of `draw()`. But it is quite fragile and not handy.

- `grid::grid.grabExpr` is quite fragile. It doesn't work in `magrittr` pipes. It often breaks if generated in the context of a data.fram.
- Drawing requires extra steps: `grid.grabExpr()`, `grid.newpage()` and `grid.draw()`.

P.S. ComplexHeatmap is an excellent library, thank you very much for supporting it.

**Comment by jokergoo** [comment]
In the current implementation, it is difficult to execute `draw()` with plotting anything. `draw()` function internally uses a lot of `grid.*()` functions such as `grid.points`, `grid.rect()`, so it really "draws" something.

I don't know why you prefer saving the "drawing" procedure as a variable. Can you give me a use case? Currently I think there are two ways:

1. use `make_layout()` function. All arguments for `draw()` actually go to `make_layout()` function:

```r
ht = Heatmap(...) + NULL # not sure  whether "+ NULL" is necessary here
ht = make_layout(ht, ...)
# later you can draw by
draw(ht) # all the arguments in make_layou are all saved in `ht` now
```

2. draw the heatmap in a null device.

```r
pdf(NULL)
ht = draw(ht, ...)
dev.off()
# later
draw(ht)
```

**Comment by idavydov** [comment]
My use case usually looks like this. I first generate a set of parameters in tibble and assign the plot as a column to this tibble. Then for every set of parameters I generate a plot. Finally, I create a section in Rmarkdown for every plot.

```r
df_with_plots = tibble(u=c(-1,0,1), sd=1:3) %>%
  rowwise() %>%
  mutate(
    header=str_glue("mu={u}, sd={sd}"),
    data=list(rnorm(100, u, sd)),
    plot=list(qplot(data, geom='histogram'))
  )

# # A tibble: 3 x 5
# # Rowwise: 
#       u    sd header      data        plot  
#   <dbl> <int> <glue>      <list>      <list>
# 1    -1     1 mu=-1, sd=1 <dbl [100]> <gg>  
# 2     0     2 mu=0, sd=2  <dbl [100]> <gg>  
# 3     1     3 mu=1, sd=3  <dbl [100]> <gg>
```

Now plotting
````
## Section {.tabset .tabset-pills}
```{r results='asis'}
for (i in 1:nrow(df_with_plots)) {
  cat("\n\n###", df_with_plot$header[i], "\n\n")
  print(df_with_plots$plot[[i]])
}
```
````

This second part doesn't actually work, but I hope it illustrates the idea.

I think `make_layout` could be a solution for my use-case. I will try it out.

Thanks for your quick response.

**Comment by jokergoo** [comment]
OK, now I understand what you want to do. I don't use tidyverse very much but I understand you want to first save heatmaps as objects and later plot them together. I think you can do as follows:

```r
ht_list = list(
    Heatmap(...),
    Heatmap(...)
)
```

Here `ht_list` stores a list of `Heatmap` objects without drawing anything, later you can use `draw()` function to draw all of them:

```r
for(i in seq_along(ht_list)) {
    draw(ht_list[[i]])
}
```

I think you can do similar under your tidyverse framework.

**Comment by idavydov** [comment]
Hi @jokergoo ,

What I had in mind actually looks like this:
```r
library(ComplexHeatmap)

x <- matrix(rnorm(100), nrow=10)
h1 <- Heatmap(x)
h2 <- Heatmap(x)

my_plots <- list(
  # different plots I am interested in
  make_layout(h1 + h2, heatmap_legend_side = "left"),
  make_layout(h1 + h2, heatmap_legend_side = "bottom")
)

for (i in 1:length(my_plots))
  draw(my_plots[[i]])
```

So I think `make_layout` + `draw` solves my issue. Given that you can control all the `draw` parameters in `make_layout`.

Thanks for your help!

**Comment by jokergoo** [comment]
Glad you found the solution!
