### ISSUE TITLE
Draw separate right annotation plot for each column split section in oncoPrint

### ISSUE THREAD

**Issue by kotliary** [jokergoo/ComplexHeatmap#588]
Thanks for the amazing package.

In section 7.2.4 of the documentation you show how to split the rows in oncoPrint. If I do the same example but use column_split, I get only one right annotation plot for the whole heatmap. 

What would be the best way to draw such annotation plots for each column split?
The same question can be as asked about top annotation in case of row split.

Another related question: is it possible to show frequencies instead of counts on the right/top annotation? I understand that for rows one may get frequency higher than 100% due to multiple mutation types within a sample.

**Comment by jokergoo** [comment]
1. column_split should work, see the following example. Maybe you can give me an example on which you had problem.

![image](https://user-images.githubusercontent.com/449218/95177292-52d7ff00-07be-11eb-9221-bd75b5f0acae.png)

2. Actually that is a good suggestion. I will support it.

**Comment by jokergoo** [comment]
Done, I added a new `show_fraction` argument in `anno_oncoprint_barplot()` function.

see the following example:

```r

oncoPrint(mat,
    alter_fun = alter_fun, col = col,
    remove_empty_columns = TRUE, remove_empty_rows = TRUE,
    top_annotation = HeatmapAnnotation(cbar = anno_oncoprint_barplot(show_fraction = TRUE)),
    right_annotation = rowAnnotation(rbar = anno_oncoprint_barplot(show_fraction = TRUE)))
```

![image](https://user-images.githubusercontent.com/449218/95179108-7dc35280-07c0-11eb-84d6-c3abf33e7c43.png)

**Comment by kotliary** [comment]
Thank you for answering this and for the frequency feature. It's great.

As for the 1st question, I had no problem to do column_split, but I wanted to have two bar plots on the right, each for sample group determined by the split. Is it possible?

**Comment by jokergoo** [comment]
The barplots for what? Do you mean one row-barplots for the mutation frequencies of genes in column group1 and another row-barplots for column group2?

**Comment by kotliary** [comment]
> Do you mean one row-barplots for the mutation frequencies of genes in column group1 and another row-barplots for column group2?

Exactly

**Comment by jokergoo** [comment]
Then you can do oncoPrint + oncoPrint:

```r
oncoPrint(mat[, 1:86],
    alter_fun = alter_fun, col = col,
    remove_empty_columns = TRUE) +
oncoPrint(mat[, 87:172],
    alter_fun = alter_fun, col = col,
    remove_empty_columns = TRUE)
```

![image](https://user-images.githubusercontent.com/449218/95377502-eefb2680-08e2-11eb-9910-495e0424fbac.png)

If you don't like it, you can always construct the barplot annotation by `anno_barplot()` and attach them to the oncoPrint.

**Comment by kotliary** [comment]
Yes, but in this case the mutation frequencies (by genes) are separated. I thought about putting these two bar plots together for easier comparison. 
Also, you can see that the top plots have different scale now (different max counts). Is it possible to unify them?
Thanks again for your responses.

**Comment by jokergoo** [comment]
I don't have an existing code, but I think it is rather easy to calculate the frequencies of mutations in the two oncoPrints. Then actually you can put them together by adding two barplot annotations, like:

```r
oncoPrint(...) + oncoPrint(...) + rowAnnotation(bar1 = anno_barplot(freq_table1), bar2 = anno_barplot(freq_table2))
```

For the scales on the top annotations, set a same `ylim`:

```r
oncoPrint(..., top_annotation = HeatmapAnnotation(cbar = anno_oncoprint_barplot(ylim = ...)))
```
in the two oncoPrints.

**Comment by kotliary** [comment]
Thank you for the help. I was able to make it. It required quite an effort. It would be great if this can be a feature. 

Maybe in the future the `anno_oncoprint_barplot()` function can work independently of oncoPront heatmap accepting the mutation matrix directly.

Thanks again. I think the issues can be closed.

**Comment by YingYa** [comment]
> Then you can do oncoPrint + oncoPrint:
> 
> ```r
> oncoPrint(mat[, 1:86],
>     alter_fun = alter_fun, col = col,
>     remove_empty_columns = TRUE) +
> oncoPrint(mat[, 87:172],
>     alter_fun = alter_fun, col = col,
>     remove_empty_columns = TRUE)
> ```
> 
> ![image](https://user-images.githubusercontent.com/449218/95377502-eefb2680-08e2-11eb-9910-495e0424fbac.png)
> 
> If you don't like it, you can always construct the barplot annotation by `anno_barplot()` and attach them to the oncoPrint.

I ran oncoPrint + oncoPrint, but the rows order are not the same between these two oncoPrints.

oncoPrint(mat1, alter_fun = alter_fun, col = col, column_title = heatmap_title, 
            heatmap_legend_param = heatmap_legend_param, 
            bottom_annotation=HeatmapAnnotation(df=ha_bottom, col=col_bottom, na_col="white")) +
oncoPrint(mat2, alter_fun = alter_fun, col = col, column_title = heatmap_title, 
            heatmap_legend_param = heatmap_legend_param, 
            bottom_annotation=HeatmapAnnotation(df=ha_bottom, col=col_bottom, na_col="white"))


![image](https://user-images.githubusercontent.com/4224226/226260324-9e8393a0-5fb2-4e88-9c05-4b2672c1bc42.png)

**Comment by YingYa** [comment]
> Then you can do oncoPrint + oncoPrint:
> 
> ```r
> oncoPrint(mat[, 1:86],
>     alter_fun = alter_fun, col = col,
>     remove_empty_columns = TRUE) +
> oncoPrint(mat[, 87:172],
>     alter_fun = alter_fun, col = col,
>     remove_empty_columns = TRUE)
> ```
> 
> ![image](https://user-images.githubusercontent.com/449218/95377502-eefb2680-08e2-11eb-9910-495e0424fbac.png)
> 
> If you don't like it, you can always construct the barplot annotation by `anno_barplot()` and attach them to the oncoPrint.

I ran oncoPrint + oncoPrint, but the rows order are not the same between these two oncoPrints.
oncoPrint(mat1, alter_fun = alter_fun, col = col, column_title = heatmap_title, 
            heatmap_legend_param = heatmap_legend_param, 
            bottom_annotation=HeatmapAnnotation(df=ha_bottom, col=col_bottom, na_col="white")) +
oncoPrint(mat2, alter_fun = alter_fun, col = col, column_title = heatmap_title, 
            heatmap_legend_param = heatmap_legend_param, 
            bottom_annotation=HeatmapAnnotation(df=ha_bottom, col=col_bottom, na_col="white"))

**Comment by wanghongke1122** [comment]
> Thank you for the help. I was able to make it. It required quite an effort. It would be great if this can be a feature.
> 
> Maybe in the future the `anno_oncoprint_barplot()` function can work independently of oncoPront heatmap accepting the mutation matrix directly.
> 
> Thanks again. I think the issues can be closed.

May I ask how you finally implemented it? Could you share the code?

**Comment by wanghongke1122** [comment]
> Thank you for the help. I was able to make it. It required quite an effort. It would be great if this can be a feature.
> 
> Maybe in the future the `anno_oncoprint_barplot()` function can work independently of oncoPront heatmap accepting the mutation matrix directly.
> 
> Thanks again. I think the issues can be closed.

May I ask how you finally implemented it? Could you share the code? @kotliary
