### ISSUE TITLE
Length of simple annotations differ.

### ISSUE THREAD

**Issue by Chandrima-04** [jokergoo/ComplexHeatmap#589]
I am using ComplexHeatmap v 3.1.1. There are multiple issues I would like to mention:
* anno_block is not getting recognized
```Error in anno_block(gp = gpar(fill = 2:4), labels = c("group1", "group2", : could not find function "anno_block"```
* while using heatmap_annotation, multiple annotation is giving errors which I did not see before when using the functionality. when both the columns have same length
```The current one is length of simple annotations differ.```

**Comment by jokergoo** [comment]
Hi, do you mean the version 2.1.1? The current development version is only 2.5.5.

https://github.com/jokergoo/ComplexHeatmap/blob/eeb04ed968b79b34e0afe33f8c6d23de035abd74/DESCRIPTION#L4

Can you try the recent versions, i.e. 2.5.*? You can find it on Github or bioc devel branch.
