### ISSUE TITLE
how to add the color bar annotation of left on row_km cluster? 

### ISSUE THREAD

**Issue by honghh2018** [jokergoo/ComplexHeatmap#590]
Hi @jokergoo ,
    I want to add the color bar annotation for row_km just like below showing,
    
![image](https://user-images.githubusercontent.com/41668708/93975311-de5a9480-fda9-11ea-8439-28f3475da8df.png)
     how can i plot this picture using the Heatmap function?
     Would you mind give me some tips for this draw?
     Bests,
     hanhuihong

**Comment by jokergoo** [comment]
Hi, you can use the `anno_block()` function:

https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html#block-annotation
