### ISSUE TITLE
`ComplexHeatmap::pheatmap()` cannot produce top annotations when called from within `do.call`.

### ISSUE THREAD

**Issue by dtm2451** [jokergoo/ComplexHeatmap#596]
Some of the logic within `HeatmapAnnotation()`'s system call check code breaks down when it is called within `do.call(pheatmap, ...)`

```
library(ComplexHeatmap)

mat <- matrix(rpois(30, 20), ncol=5)
rownames(mat) <- paste0("gene", 1:6)
colnames(mat) <- paste0("samp", 1:5)

annotation_col <- data.frame(score = 1:5,
                             row.names = colnames(mat))

# Direct call works
pheatmap(mat, annotation_col = annotation_col)

# indirect call with do.call
do.call(pheatmap, list(mat, annotation_col = annotation_col))
> Error in as.character(scl[[1]]) : 
    cannot coerce type 'closure' to vector of type 'character'
```

The error comes from this line,
https://github.com/jokergoo/ComplexHeatmap/blob/a5cd974897746990d16843724d71822ccd771feb/R/HeatmapAnnotation-class.R#L161 and results from `scl[[1]]` being the function definition itself, rather than its symbolic name. Thus `as.character()` fails.

I'm not sure of the best solution here, but it may help that `is.symbol(scl[[1]])` evaluates to TRUE for direct calls but FALSE for indirect calls through `do.call`.

**Comment by dtm2451** [comment]
Additionally, I can't seem to specify `color` using colorRamp2().

Documentation in the table of [here](https://jokergoo.github.io/2020/05/06/translate-from-pheatmap-to-complexheatmap/) suggests I should be able to.

```
ComplexHeatmap::pheatmap(mat, color = circlize::colorRamp2(c(-10,20,30), c("blue", "white", "red")))
> Error in colors[order(breaks)] : 
    object of type 'closure' is not subsettable
```

I can attempt to PR a fix and add to #597, but maybe we can discuss implementation? I see you have code for an implementation of `breaks` even though you suggest that the input not be used... I definitely think that can be merged with `breaks` + (vector) `color` inputs into a (colorRamp2) `color` input, but if you do want to leave that logic to the user that's also totally valid in my opinion!

Also gotta say thanks for putting together this pheatmap translation!!!! I'm quite excited by how it gives me the ability to add in ComplexHeatmap compatibility for dittoSeq without adjusting the look of the output very much, and with relatively low effort for me and and minimal extra learning dittoSeq's for users!

**Comment by jokergoo** [comment]
1. Yes, thanks for finding the problem! I always use `do.call("pheatmap", list(mat, annotation_col = annotation_col))`, so I forgot the scenario where the first argument for `do.call()` is a function. Now it is fixed.

**Comment by jokergoo** [comment]
2. the validation of `color` and `breaks` were not very proper. I will improve it.

**Comment by jokergoo** [comment]
Now the logic for setting colors are:

1. if `color` is a color mapping function generated by `colorRamp2()`, the breaks are specified in `colorRamp2()`, so `breaks` in `pheatmap()` is ignored,
2. if `color` is a vector:
    - if `breaks` is not set, break values are automatically inferred from the matrix;
    - if `breaks` is set,
        + if `breaks` has the same length as `color`, simply use `colorRamp2(breaks, colors)`;
        + if `breaks` has the length equal to `length(color)+1`, the breaks are treated as internals, so that `color[1]` is mapped to `c(breaks[1], breaks[2])`, ...
        + else the colors are interpolated from the minimal to the maximal of `breaks`, with a warning message

**Comment by dtm2451** [comment]
Awesome, thanks!!  Looking forward to having this folded in before next week's Bioconductor release =).

All my tests pass now except for one, but I think it's on my side.  I'll close this issue once I verify that.

**Comment by dtm2451** [comment]
Looks like the issue is replicable without any dittoSeq code.

The issue is a `stop` call which happens whenever there are numeric annotations for BOTH the rows and columns.  Putting multiple numeric annotations for rows only OR columns only works fine, but once there are numeric annotations for both, I get the error below.

Reproducible example based off the example [in your translation page](https://jokergoo.github.io/2020/05/06/translate-from-pheatmap-to-complexheatmap/):
```
library(ComplexHeatmap)

# Make the matrix
test = matrix(rnorm(200), 20, 10)
test[1:10, seq(1, 10, 2)] = test[1:10, seq(1, 10, 2)] + 3
test[11:20, seq(2, 10, 2)] = test[11:20, seq(2, 10, 2)] + 2
test[15:20, seq(2, 10, 2)] = test[15:20, seq(2, 10, 2)] + 4
colnames(test) = paste("Test", 1:10, sep = "")
rownames(test) = paste("Gene", 1:20, sep = "")

# Build annotations
annotation_col = data.frame(
    CellType = factor(rep(c("CT1", "CT2"), 5)), 
    Time = 1:5
)
rownames(annotation_col) = paste("Test", 1:10, sep = "")

annotation_row = data.frame(
    GeneClass = factor(rep(c("Path1", "Path2", "Path3"), c(10, 4, 6))), 
## ADDED: numeric annot
    Time2 = 1:20
)
rownames(annotation_row) = paste("Gene", 1:20, sep = "")

ann_colors = list(
    Time = c("white", "firebrick"),
    Time2 = c("white", "firebrick"),
    CellType = c(CT1 = "#1B9E77", CT2 = "#D95F02"),
    GeneClass = c(Path1 = "#7570B3", Path2 = "#E7298A", Path3 = "#66A61E")
)

pheatmap(test, annotation_col = annotation_col, annotation_row = annotation_row, 
         annotation_colors = ann_colors)
```

```
Error: elements in `col` should be named vectors.

4. stop(x, call. = FALSE) at utils.R#460
3. stop_wrap("elements in `col` should be named vectors.") at HeatmapAnnotation-class.R#285
2. HeatmapAnnotation(df = annotation_col[, ncol(annotation_col):1, 
       drop = FALSE], col = annotation_colors, show_legend = annotation_legend, 
       show_annotation_name = annotation_names_col, gp = gpar(col = border_color), 
       annotation_name_gp = gpar(fontsize = 10, fontface = "bold"),  ... at pheatmap_translate.R#267
1. pheatmap(test, annotation_col = annotation_col, annotation_row = annotation_row, 
       annotation_colors = ann_colors)
```
Quick links for ya: [2](https://github.com/jokergoo/ComplexHeatmap/blob/e795accfed43bc4e689905b22234a6a299cc4925/R/pheatmap_translate.R#L267), [3](https://github.com/jokergoo/ComplexHeatmap/blob/e795accfed43bc4e689905b22234a6a299cc4925/R/HeatmapAnnotation-class.R#L285), [4](https://github.com/jokergoo/ComplexHeatmap/blob/e795accfed43bc4e689905b22234a6a299cc4925/R/utils.R#L460)

**Comment by jokergoo** [comment]
Ah... it is because I thought `annotation_colors` is only set for rows or columns, while not set them at the same time. I will check it! 

Thanks!

**Comment by dtm2451** [comment]
New fix looks good, and annotations now work as I would expect!

Going back to the `breaks` issue though, apologies as I hadn't checked explicitly and my workaround code (that I'd like to remove fully) was hiding an issue:

The case of giving `breaks` and `color` where the length of `breaks` is one longer than that of `color` still doesn't seem to work. It gives a bunch of warnings and an incomplete coloring interpretation.

```
library(ComplexHeatmap)
library(RColorBrewer)

mat <- matrix(rpois(30, 20), ncol=5)
rownames(mat) <- paste0("gene", 1:6)
colnames(mat) <- paste0("samp", 1:5)

colors <- colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(8)

breaks_length_equal <- seq(-10, 30, length.out = 8)
breaks_length_plus_one <- seq(-10, 30, length.out = 9)

# Same length breaks = GOOD
pheatmap(mat, annotation_col = annotation_col, color = colors,
         breaks = breaks_length_equal)

# Color length + 1 length breaks = warnings with incomplete color interpretation
pheatmap(mat, annotation_col = annotation_col, color = colors,
         breaks = breaks_length_plus_one)

# When warnings() wrapped, gives:
Warning messages:
1: In x >= df$start :
  longer object length is not a multiple of shorter object length Error in cat("1: In x >= df$start :\n  longer object length is not a multiple of shorter object length",  : 
  argument 2 (type 'S4') cannot be handled by 'cat'
```

**Comment by jokergoo** [comment]
Yes, that was a bug. Now it is fixed. Thanks!

```r
pheatmap(mat, color = colors,breaks = breaks_length_plus_one, display_numbers = TRUE)
```

![image](https://user-images.githubusercontent.com/449218/95502765-9beca680-09aa-11eb-9384-6591bfa9c55b.png)

**Comment by dtm2451** [comment]
Great!  And now the one last bit that I have workaround code for (and this isn't a bug per se, just a difference between `CH::` vs `pheatmap::` `pheatmap()` behavior) is that when `pheatmap::pheatmap()` `scale`s data, the default `breaks` are centered on zero.  As in they span from `-1*max(abs(scaled_mat))` to `max(abs(scaled_mat))`.

You could add this in to equilibrate the behavior even more.

If helpful, my code for doing this, after scaling has been performed, is:
```
limit <- max(abs(range(mat)))
breaks <- seq(-1*limit, limit, length.out = length(color))
```

**Comment by jokergoo** [comment]
How about this?

![image](https://user-images.githubusercontent.com/449218/95556848-40ef9980-0a14-11eb-905e-c2ed7d079fe8.png)

**Comment by dtm2451** [comment]
That looks right, but the implementation isn't the same.  I think you are adjusting the range of the color scale whereas pheatmap::pheatmap actually adjusts the color mappings.

pheatmap
![image](https://user-images.githubusercontent.com/38870347/95613785-5667c200-0a1a-11eb-9129-f6e78754596b.png)

ComplexHeatmap
![image](https://user-images.githubusercontent.com/38870347/95613848-697a9200-0a1a-11eb-8e09-b55e7ea93dab.png)

**Comment by dtm2451** [comment]
Here's my full code, which is performed right before the `do.call(*::pheatmap, args)` in https://github.com/dtm2451/dittoSeq/pull/60.

```
# This function takes in a list of args formatted for pheatmap::pheatmap that
# are to be passed on to ComplexHeatmap, and adjusts the breaks input to ensure
# colors will match.
#
# Also adjusts the mat and scale arguments only to not duplicate the scaling
# calculation. (scaling is run here to determine proper breaks.)
#
# Overall, adjusts inputs to help equalize differences between default outputs.
.extra_adjustments_for_complex <- function(args) {
    
    if (args$scale != "none" && identical(args$breaks[1], NA)) {
        
        # Perform scaling
        if (args$scale == "row") {
            if (any(is.na(args$mat))) {
                args$mat <- (args$mat - apply(args$mat, 1, function(x) mean(x, na.rm = TRUE))) /
                    apply(args$mat, 1, function(x) sd(x, na.rm = TRUE))
            } else {
                args$mat <- t(scale(t(args$mat)))
            }
        }
        
        if (args$scale == "column") {
            if (any(is.na(args$mat))) {
                args$mat <- t((t(args$mat) - apply(args$mat, 2, function(x) mean(x, na.rm = TRUE))) /
                    apply(args$mat, 2, function(x) sd(x, na.rm = TRUE)))
            } else {
                args$mat <- scale(args$mat)
            }
        }
        
        args$scale <- "none"
        
        # Set breaks to be bimodal, centered on zero
        limit <- max(abs(range(args$mat)))
        args$breaks <- seq(
                -1*limit,
                limit,
                length.out = length(args$color))
    }
    
    args
}
```

An adjustment of `breaks` -- when not provided by the user, post-scaling, but prior to color picking -- should be all that's needed for this last equilibration of ComplexHeatmap::pheatmap and pheatmap::pheatmap outputs!

I know you have pretty similar scaling code already cuz I based those bits off yours =p, so this breaks bit could probably fold in right around there.

**Comment by jokergoo** [comment]
Yes, you are absolutely right. The color mapping was not changed!

**Comment by jokergoo** [comment]
Emm, but there is something I don't feel good when `breaks` and `scale` are both set, because setting `scale` will internally and invisibly change the value of `breaks`. Then we need to ask, when users set both `breaks` and `scale`, does `breaks` correspond to the scaled matrix or unscaled matrix? I think `breaks` should always be consistent with the input matrix.

**Comment by jokergoo** [comment]
OK, if `scale` is set and `breaks` is not set, as you did, I will make the color mapping symmetric to zero.

**Comment by dtm2451** [comment]
Fantastic!  Thank you.

I'll keep an eye out for when this all gets pushed to Bioconductor. I imagine you have other things in the works, but do you think that will happen before the upcoming [release cycle](https://bioconductor.org/developers/release-schedule/)?

re: the 'unrelated comment', I totally agree that if breaks is set, an adjustment like this would be inappropriate, and I also agree that any adjustment compared to what the user requests should probably come with a message.  pheatmap::pheatmap seems to take the breaks as post-scaling values, but FWIW, I think you've done enough work to absorb in pheatmap::pheatmap logic as-given already, and that at some point your own design ideas and goals can definitely take precedence.  So again, thank you for obliging this last non-essential change!

**Comment by jokergoo** [comment]
Also thank you for pointing out all these. I don't actually use pheatmap so I don't have the chance to discover so many issues.

I just pushed to the bioc devel branch with version 2.5.6.

**Comment by dtm2451** [comment]
Collaborative science is the best science haha.  I've merged pushed mine as well =).
