### ISSUE TITLE
"read.xlsx" WARNING

### ISSUE THREAD

**Issue by Natalinha** [jokergoo/ComplexHeatmap#598]
Hi every time I run read.xlsx this error shows up on my console.  Not sure what to do.

**FROM CONSOLE:** 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.poi.util.SAXHelper (file:/Library/Frameworks/R.framework/Versions/3.6/Resources/library/xlsxjars/java/poi-ooxml-3.10.1-20140818.jar) to method com.sun.org.apache.xerces.internal.util.SecurityManager.setEntityExpansionLimit(int)
WARNING: Please consider reporting this to the maintainers of org.apache.poi.util.SAXHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by jokergoo** [comment]
Hi, this is not a ComplexHeatmap related issue. 

Maybe you can try other packages that read Excel files such as [readxl](https://readxl.tidyverse.org/index.html)?
