### ISSUE TITLE
Saving the plot into the work directory

### ISSUE THREAD

**Issue by saifsikdar** [jokergoo/ComplexHeatmap#599]
Hi @jokergoo , 

I have generated a heatmap using ComplexHeatmap package. However, I cannot save it using the ggsave() of the ggplot2 package png() works but it makes the plot blurred and incomplete. Can you please suggest how to save a plot generated from ComplexHeatmap package into work directory?

here's the code I used:
`library(ggplot2)`
`library(ComplexHeatmap)`
```
**# this code generate plot in R environment**
ht_list = Heatmap(exp_groups, name = "B-H corrected\n significant genes", 
        cluster_columns = FALSE,
        clustering_distance_rows = "pearson",
        heatmap_legend_param = list(
        direction = "horizontal"),
        row_names_gp = gpar(fontsize = 10),
        column_names_gp = gpar(fontsize = 10),
        width = unit(4, "cm"), height = unit(18, "cm")
        )
draw(ht_list, heatmap_legend_side = "top") 

 **# Problem: This code does not save the plot in work directory**
draw(ht_list, heatmap_legend_side = "top")
ggsave(filename = "heatmap_all_BHcorrected.jpg", width = 4, height =18)

**# Problem: Using png(). It works but save blurred and incomplete graph**
p  <- draw(ht_list, heatmap_legend_side = "top")
png("heatmap_all_BHcorrected.jpg")
print(p)
```
Can you please suggest how to solve this or any alternative option for saving ComplexHeatmap generated graphs in working directory?

Thank you.

**Comment by jokergoo** [comment]
`ggsave()` only works with ggplot2 plots? I don't know whether you can use it for other plots.

Can you save the plot in pdf format? I think maybe the png has too low resolution with the default parameters (You can check the `res` argument of `png()` function).

**Comment by saifsikdar** [comment]
Can you please suggest what works best for saving ComplexHeatmap plots? I would like to save it as .png or .jpg format in my working directory.

**Comment by jokergoo** [comment]
```r
png(...)
# heatmap made here
dev.off()
```

For a heatmap with higher resolution, 

```r
ratio = 2 # some value > 1
# w and h are the width and height with the default resolution
png(..., width = w*ratio, height = h*ratio, res = 72*ratio)
# heatmap made here
dev.off()
```
