### ISSUE TITLE
normalizeToMatrix for methylation data

### ISSUE THREAD

**Issue by dktanwar** [jokergoo/ComplexHeatmap#600]
Hi @jokergoo 

I have a question about Figure 4 B from https://www.biorxiv.org/content/10.1101/2020.08.20.259374v1.full

![image](https://user-images.githubusercontent.com/8986859/95567826-bdd63f80-0a23-11eb-863e-484dae89584b.png)

Is there a better way to visualize the methylation signal?

This is how the methylation `normalizeToMatrix` was used:

```r
normalizeToMatrix(x, tss_mm10,
      extend = 2500,
      value_column = "meth",
      include_target = TRUE,
      smooth = TRUE,
      mean_mode = "absolute",
      background = NA
    )
```

**Comment by jokergoo** [comment]
What do you mean by "a better way to visualize the methylation signal"? I think the visualization of methylation signals in the plot is already very good.

**Comment by dktanwar** [comment]
Sorry for not being clear. What I wanted to check with you is the way `normalizeToMatrix` run on methylation data was ok. In case you have other suggestions for this...

**Comment by jokergoo** [comment]
normally, I set the following parameters as you did here:

```r
smooth = TRUE,
mean_mode = "absolute",
```

This will give a nice heatmap for methylation signals.

**Comment by dktanwar** [comment]
Thank you!
