### ISSUE TITLE
Multiple annotations

### ISSUE THREAD

**Issue by santiiiiiii** [jokergoo/ComplexHeatmap#601]
Hi I am trying to make three sets of annotations on my heatmap: Diagnosis, Respiratory_Status and hsCRP. They all work individually but I can't get them to appear all together. 

I have used the following code:

```r
anno_df = data.frame(Diagnosis = factor(DGEList_0_24$targets$Group_facet,levels = c("Controls", "Screening: asymptomatic","Screening: symptomatic", "Mild (no oxygen)","Moderate (low flow oxygen)", "Severe (assisted ventilation)")), 
hsCRP=as.numeric(manifest_select$hsCRP_mg_l),
Respiratory_Status=factor(manifest_select$resp, levels =c("no O2","low flow O2","vent","ECMO")))

ha_24 = HeatmapAnnotation(df = anno_df,
col = list(Diagnosis = c("Mild (no oxygen)" = "blue", "Moderate (low flow oxygen)" = "orange",     "Severe (assisted ventilation)" = "red","Screening: symptomatic"="lightblue","Screening: asymptomatic"="cyan","Controls"="green"),
hsCRP=colorRamp2(c(0,400), c("white", "red")), 
Respiratory_Status= c("no O2"="blue","low flow O2"="orange","vent"="red","ECMO"="darkred")))
```

When I run: 

```r
Heatmap(data_subset_norm_24, 
name = "Z-normalised", 
        col = col_fun,
        top_annotation= ha_24,
        show_row_names=FALSE,show_column_names = FALSE,
        column_title = "Disease severity at 0-24 days post symptom onset", 
        column_title_gp = gpar(fontsize = 12,face="bold"),
        column_km  = 6,
        row_km  = 3,
        cluster_columns=TRUE,
        clustering_distance_rows = "euclidean",
        clustering_method_rows = "ward.D",
        row_dend_reorder = TRUE)
```

The following error appears: Error in opt$get(calling_ns, read.only = READ.ONLY, enforce_visible = TRUE) : 
  attempt to apply non-function

Thank you

**Comment by jokergoo** [comment]
Can you also attach the objects of `data_subset_norm_24` and `ha_24` so that I can have a test? I haven't seen this type of error.

**Comment by santiiiiiii** [comment]
Thanks for replying. I can't seem to attach the robjects. I get the following error on github: "We don't support that file type". May I email them to you?

**Comment by jokergoo** [comment]
Can you zip it? I think github supports .zip files.

**Comment by santiiiiiii** [comment]
[ha_24.rds.zip](https://github.com/jokergoo/ComplexHeatmap/files/5356780/ha_24.rds.zip)
[data_subset_norm_24.rds.zip](https://github.com/jokergoo/ComplexHeatmap/files/5356782/data_subset_norm_24.rds.zip)

**Comment by santiiiiiii** [comment]
Thank you

**Comment by jokergoo** [comment]
Emmm. I don't have this error. Following is the plot that was successfully generated:

![image](https://user-images.githubusercontent.com/449218/95848109-e7f26f00-0d4d-11eb-8190-1c4b8b465425.png)

What is your `sessionInfo()`?

**Comment by jokergoo** [comment]
Maybe try to install the newest versions of all my packages:

```r
library(devtools)
install_github("jokergoo/ComplexHeatmap")
install_github("jokergoo/circlize")
install_github("jokergoo/GlobalOptions")
```

Probably some inconsistency between the different versions.

**Comment by santiiiiiii** [comment]
Thank you very much for your help. It worked!

**Comment by santiiiiiii** [comment]
I think it is just my R. All working now, when I re-booted. Thank you

**Comment by jokergoo** [comment]
This kind of error is mainly because you installed a package that was under using in your R session. Yes, just restart your R session.
