### ISSUE TITLE
Problem in merging two maf files or objects

### ISSUE THREAD

**Issue by beginner984** [jokergoo/ComplexHeatmap#602]
Hello 

I try to merge two maf files or object but I get this error

```
merge_mafs(lamlr,lamlp)
Error in as.list.default(X) :
no method for coercing this S4 class to a vector

merge_mafs(res1,pre)
Error in if (verbose) { : argument is not interpretable as logical
In addition: Warning message:
In if (verbose) { :
the condition has length > 1 and only the first element will be used
```

This is the address of my two files

https://www.dropbox.com/s/t1dzeqlvsmpoqkq/res1.rds?dl=0

https://www.dropbox.com/s/b5l6er7alucws03/pre.rds?dl=0

Thank you so much

**Comment by jokergoo** [comment]
Sorry, I cannot help you with this problem. The function `merge_mafs()` is not from ComplexHeatmap package. Maybe you can go to the correct package repo and look for help there.
