### ISSUE TITLE
Is it possible to have column names both on top and bottom?

### ISSUE THREAD

**Issue by CodeInTheSkies** [jokergoo/ComplexHeatmap#605]
I was hoping that by doing `column_names_side=c("bottom, "top")`, I can get the command to draw the column names both on top as well as bottom.  Is this actually possible?

Thank you for this really excellent package!!

**Comment by jokergoo** [comment]
No, you can only have one title for the plot, but the other title can be added by some tricks:

```r

m = matrix(rnorm(100), 10)

ht = Heatmap(m, name = "mat", column_title = "Title 1")

draw(ht, padding = unit(c(20, 2, 2, 2), "mm"))

decorate_heatmap_body("mat", {
	grid.text("Title 2", y = unit(-5, "mm"), just = "top",
		gp = gpar(fontsize = 14))
})
```

![image](https://user-images.githubusercontent.com/449218/96037024-950bdb00-0e65-11eb-93a6-0484171791c4.png)

**Comment by CodeInTheSkies** [comment]
Thanks!  I actually meant the column labels rather than the column title.
Is that also achievable?

**Comment by jokergoo** [comment]
Ah, sorry I read too fast :)

Then it is easier. You can use `anno_text()` to construct both top and bottom annotations:

```r
Heatmap(matrix(rnorm(100), 10),
	top_annotation = HeatmapAnnotation(name1 = anno_text(letters[1:10])),
	bottom_annotation = HeatmapAnnotation(name2 = anno_text(LETTERS[1:10])))
```

![image](https://user-images.githubusercontent.com/449218/96096607-4fd0c300-0ed0-11eb-95c4-aa63c6dc674b.png)

**Comment by CodeInTheSkies** [comment]
Fantastic!! Thank you very much.

**Comment by CodeInTheSkies** [comment]
Hi @jokergoo ,

I asked this question in 2020, and you said we can do this using anno_text() at that time.

I need this feature again now for another vertically long heatmap I have created with one bottom column annotation.  I wish to add the column labels also at the top in addition to the ones that occur at the bottom.  

Given there have been many updates to the package, is there another easier standard parameter that you have added to duplicate the column labels both at the top and the bottom of a heatmap?

Thanks.
