### ISSUE TITLE
separate cell/box annotation

### ISSUE THREAD

**Issue by MichaelPeibo** [jokergoo/ComplexHeatmap#607]
Hi @jokergoo 
I am using ComplexHeatmap to produce a heatmap, when I do row annotation, I got this plot:
![image](https://user-images.githubusercontent.com/32219336/96201321-dc41bb00-0f8e-11eb-9c83-6e1c708052ae.png)

Is there any way to produce row annotation in separate cell/box rather than merged one? like plot below:
![image](https://user-images.githubusercontent.com/32219336/96201390-098e6900-0f8f-11eb-87b8-628655949904.png)

Thanks! It is a really cool package!

**Comment by jokergoo** [comment]
Hi, you can set `row_split`/`column_split` argument.

https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#heatmap-split

**Comment by MichaelPeibo** [comment]
Hi @jokergoo , thanks for reply.
I have tried `row_split`/`column_split`, but it split heatmap as slices.
I want to split annotation of **each row** , like each cell/box by each row. Any argument like that?

**Comment by jokergoo** [comment]
It also split the annotations accordingly. Maybe you can attach some code here?

**Comment by MichaelPeibo** [comment]
I figureed this out by using pheatmap(no offence). I didn't find exact expression---I want to add a border on boxed annotation, like this below:
![image](https://user-images.githubusercontent.com/32219336/96331040-a2ef7500-108c-11eb-8286-35f199b69847.png)
Thanks for developing this great heatmap package.
