### ISSUE TITLE
column names and annotation row names manually ordered

### ISSUE THREAD

**Issue by EleonoraSperandio** [jokergoo/ComplexHeatmap#608]
Hi, I would like to draw attention on the following question. During the realization of different heatmaps in which the columns are patients and the gene rows, I needed to add an annotation that reflected the patient's belonging to a group, defined in a dataframe where the rows are the patients. I therefore realized that the mapping between the patients in the expression matrix (columns) and the patients in the dataframe with the characteristics to be noted (rows) does not take place automatically (matching colnames (mat) and rownames (df)) but must be performed by hand, that is, the order of the columns of the expression matrix must be equal to the order of the rows of the dataframe. In fact, in the event that the patient order is different and is not manually corrected, display errors are incurred.
I would therefore like to ask if this mechanism is intentional, and if so, the motivation for this choice, thanks.
I attach sample code and related view.

```r
mat <- matrix(rexp(50, .1), ncol = 10)
colnames(mat) <- letters[1:10]

df_ordered <- data.frame(ordered = c("YES","YES","NO","YES","NO","NO","NO","NO","YES","NO"), row.names = letters[1:10])
set.seed(42)
rows <- sample(nrow(df_ordered))
df_not_ordered <- data.frame(not_ordered = df_ordered[rows, ], row.names = rownames(df_ordered)[rows])

ha_ordered <- HeatmapAnnotation(df = df_ordered,
                                col = list(ordered = c("YES"="red", "NO"="blue")))
ha_not_ordered <- HeatmapAnnotation(df = df_not_ordered,
                                    col = list(not_ordered = c("YES"="red", "NO"="blue")))
draw(Heatmap(mat, cluster_rows = F, cluster_columns = F, column_names_rot = 0,
             top_annotation = ha_ordered, bottom_annotation = ha_not_ordered,show_heatmap_legend = F))
```

![complex_heatmap_issue](https://user-images.githubusercontent.com/72985410/96272324-3d3cb380-0fce-11eb-865e-1dae844e7fa9.png)

**Comment by jokergoo** [comment]
The order of column annotations should always be the same as the matrix columns. Let's say the column annotation is encoded as a vector `anno`, then the `anno[1]` should correspond to the first column of the matrix and the some for other elements. The order of column names will be automatically adjusted according to the clustering on matrix columns.
