### ISSUE TITLE
how to add error bars on barplots

### ISSUE THREAD

**Issue by fedshyvana** [jokergoo/ComplexHeatmap#609]
Hi, thanks so much for this wonderful tool! I want to add error bars to barplot annotations. e.g. if I do:
```
left_annot = anno_barplot(data.matrix(some_values))
```
suppose some_values is N x 1
is there an easy way to pass additional values (e.g. in the form of N x 2 matrix or two separate N x 1 vector) representing the lower/upper error bar ranges for each bar? Thanks a lot!

Max

**Comment by jokergoo** [comment]
No, currently it cannot do that.
