### ISSUE TITLE
Error in make_cluster(object, "column") : object 'slice_od' not found

### ISSUE THREAD

**Issue by eleozzr** [jokergoo/ComplexHeatmap#611]
The following code can be run in Ubuntu and Centos, but cannot be run in Mac (macOS Catalina version 10.15.6). I tried different versions of ComplexHeatmap, all versions failed. 

```r
library(ComplexHeatmap)
set.seed(123)
mat = matrix(rnorm(100), 10)
rownames(mat) = paste0("R", 1:10)
colnames(mat) = paste0("C", 1:10)
column_ha = HeatmapAnnotation(foo1 = runif(10), bar1 = anno_barplot(runif(10)))
row_ha = rowAnnotation(foo2 = runif(10), bar2 = anno_barplot(runif(10)))

col_fun = circlize::colorRamp2(seq(min(mat), max(mat),length=200), colorRampPalette(c("blue", "white", "red"))(200))


p=Heatmap(mat, 
        name = " ", 
        cluster_rows = F,
        use_raster = T,
        cluster_columns = F,
        top_annotation = column_ha, 
        right_annotation = row_ha,
        col=col_fun,
        row_gap = unit(1,"cm"),
        row_labels = rep("",length=nrow(mat)),
        column_split=c(1,1,1,2,2,2,3,3,4,4),
        column_title = "%s")
 pdf("aa.pdf",width=5,height=5)
 draw(p)
 dev.off()
```
It will throw an error `Error in make_cluster(object, "column") : object 'slice_od' not found`.

But when I set `cluster_rows=T` and `cluster_columns=T`, this error doesn't show again.

**Comment by jokergoo** [comment]
Thanks, I also saw this error. I will fix it soon!

**Comment by jokergoo** [comment]
Done, you can update from Github.

**Comment by eleozzr** [comment]
Thanks. Everything goes well now.

**Comment by eleozzr** [comment]
> Done, you can update from Github.

 But I am curious why the same code successfully runs in Linux but failed in Mac?

**Comment by jokergoo** [comment]
I don't know either :) It should fail everywhere. The error is due to when `column_split` was set, I assumed `cluster_columns` were also set.

**Comment by eleozzr** [comment]
Does not matter. But I am glad that you fixed this issue now.
