### ISSUE TITLE
Different legend shape in oncoPrint

### ISSUE THREAD

**Issue by fantastycrane** [jokergoo/ComplexHeatmap#613]
Hi, @jokergoo 

I was trying to label germline mutation as tringle while other mutations are labeled with grid in oncoPrint legend by adjusting type and pch in heatmap_legend_param.  It didn't work. Could you help take a look and kindly telling me what went wrong in my code? Thanks.

```r
heatmap_legend_param = list(title="", at = c('Splice_Site', 'Missense_Mutation', 'Frame_Shift_Ins', 'Frame_Shift_Del', 'In_Frame_Ins', 'In_Frame_Del', 'Nonsense_Mutation', 'Nonstop_Mutation', 'deletion', 'amplification', 'Translation_Start_Site', 'Germline'), labels = c('Splice Site', 'Missense Mutation', 'Frame Shift Ins', 'Frame Shift Del', 'In Frame Ins', 'In Frame Del', 'Nonsense Mutation', 'Nonstop Mutation', 'Deletion', 'Amplification', 'Translation Start Site', 'Germline'), nrow = 2, type = "point", pch = c(rep(15, 11), 17))

plot.all <- oncoPrint(mutation.data.split,
          alter_fun = alter_fun, col = col,
          row_order = gene.list,
          heatmap_legend_param = heatmap_legend_param)
draw(plot.all, row_sub_title_side = "left", heatmap_legend_side = "bottom")
```

**Comment by jokergoo** [comment]
Please also attach the code and the data how you set `mutation.data.split` and `alter_fun`.

**Comment by fantastycrane** [comment]
library(dplyr)
library(ComplexHeatmap)
col <- c(RColorBrewer::brewer.pal(11, "Paired"), "black")
names(col) = c('Splice_Site', 'Missense_Mutation', 'Frame_Shift_Ins', 'Frame_Shift_Del', 'In_Frame_Ins', 'In_Frame_Del', 'Nonsense_Mutation', 'Nonstop_Mutation', 'deletion', 'amplification', 'Translation_Start_Site', 'Germline')
alter_fun = function(x, y, w, h, v) {
  n=sum(v) # how many alterations for current gene in current sample
  if (length(v) == 1) { names(v) = unique(mutation.data.pca$Mutation_Type) }
  vg<-NA
  if ( ("Germline" %in% names(v)) & (v["Germline"])) {
    n=n-1
    vg<-"Y"
    vgs<-v[which(names(v)=="Germline")]
    v<-v[-which(names(v)=="Germline")]
  }
  h=h*0.9
  if (n == 0) grid.rect(x, y, w*0.9, h, gp = gpar(fill = "#CCCCCC", col = NA))
  if(n) grid.rect(x, y - h*0.5 + 1:n/n*h, w*0.9, 1/n*h, gp = gpar(fill = col[names(which(v))], col = NA), just = "top")
  if (!is.na(vg)) {grid.points(x, y, pch = 17,unit(2,"mm"))}
}
heatmap_legend_param = list(title="", type="points", pch=c(rep(15, 11), 17), at = c('Splice_Site', 'Missense_Mutation', 'Frame_Shift_Ins', 'Frame_Shift_Del', 'In_Frame_Ins', 'In_Frame_Del', 'Nonsense_Mutation', 'Nonstop_Mutation', 'deletion', 'amplification', 'Translation_Start_Site', 'Germline'), labels = c('Splice Site', 'Missense Mutation', 'Frame Shift Ins', 'Frame Shift Del', 'In Frame Ins', 'In Frame Del', 'Nonsense Mutation', 'Nonstop Mutation', 'Deletion', 'Amplification', 'Translation Start Site', 'Germline'), nrow = 2)

snv.stat <- mutation.data %>% group_by(Tumor_Sample_Barcode, Hugo_Symbol) %>% summarise(Freq = n())
snv.stat <- snv.stat %>% group_by(Hugo_Symbol) %>% summarise(Freq = n())
gene.list <- snv.stat[order(snv.stat$Freq, decreasing = T),]$Hugo_Symbol
mutation.data.split <- list()
for (i in unique(mutation.data$Variant_Classification)) {
  tmp <- subset(mutation.data, Variant_Classification == i)
  tmp <- tmp %>% group_by(Tumor_Sample_Barcode, Hugo_Symbol) %>% summarise(Count = n())
  tmp$Count <- rep(1, nrow(tmp))
  tmp <- dcast(tmp, Hugo_Symbol ~ Tumor_Sample_Barcode)
  tmp[is.na(tmp)] = 0
  for (k in setdiff(sample.list, colnames(tmp))) {
    tmp[,k] = rep(0, nrow(tmp))
  }
  rownames(tmp) <- tmp[,1]; tmp <- tmp[,-1]
  for (j in setdiff(gene.list, rownames(tmp))) {
    tmp[j,] = rep(0, ncol(tmp))
  }
  tmp <- tmp[match(gene.list, rownames(tmp)),]
  tmp <- tmp[,sample.list]
  tmp.matrix <- as.matrix(tmp)

  mutation.data.split[[i]] = tmp.matrix
}

plot.all <- oncoPrint(mutation.data.split,
          alter_fun = alter_fun, col = col,
          row_order = gene.list,
          heatmap_legend_param = heatmap_legend_param)
draw(plot.all, row_sub_title_side = "left", heatmap_legend_side = "bottom")

[mutation.txt](https://github.com/jokergoo/ComplexHeatmap/files/5414769/mutation.txt)

Code and data are attached as above.

**Comment by jokergoo** [comment]
I cannot rerun your code because I cannot get some variables, e.g. `sample.list`.

Anyway, can you install and try the newest version from GitHub? I made some improvement on the oncoPrint legends. With this version, you don't need to specify `heatmap_legend_param` any more.

Have a try!
