### ISSUE TITLE
Unexpected vertical white lines appear on the heatmap

### ISSUE THREAD

**Issue by zenghh1226** [jokergoo/ComplexHeatmap#619]
Dear jokergoo and other contributors of complexheatmap:
       Thanks for creating this powerful tools. I am trying to draw heatmap of single cell RNA-seq data with about 20000+ cells and 100+ genes. I save the plot as pdf and get many unexpected vertical white lines on the heatmap. It seems that smaller size of pdf will have more white lines. I can not figure out what happens.
`#top_anno <- HeatmapAnnotation(
top_anno <- HeatmapAnnotation(cluster = anno_block(height=unit(15, "mm"),gp = gpar(fill = col,col="white",show_name=FALSE,gap=unit(0, "mm")))) # 
#
mark_gene <- c("IL6ST", "LYZ","SA1008","IL7R","GNLY","PRF1","GZMH" ,"CD8A","CD8A","LRRN3","NELL2",
               "KLRB1","KLRG1","IGHM","MS4A1","FOXP3","FCGR3A","MS4A7","IFIT3","CD1C","MKI67","TYMS","IRF8","ITM2C","IGKC","IGKC","IGLC2")
gene_pos <- which(rownames(mat) %in% mark_gene)
row_anno <-  rowAnnotation(mark_gene = anno_mark(at = gene_pos,labels = mark_gene,labels_gp = gpar(fontsize =50)))
#draw heatmap
pdf("Heatmap_top10_marker_5.pdf",width =40,height =30)
Heatmap(mat,col = colorRamp2(c(-2,0,4), c("#d61ad4","#030003","#f1f40f")),
        cluster_rows = FALSE,   
        cluster_columns = FALSE,
        show_column_names = FALSE,
        show_row_names = FALSE,
        column_split = cluster_info,
        top_annotation = top_anno,
        right_annotation = row_anno,
        column_title = NULL,column_gap = unit(0,"mm"),
        heatmap_legend_param = list(title_gp=gpar(fontsize =10),legend_height =unit(5, "cm"), legend_width =unit(2, "cm"),
                                    title = "Scale",title_position = "leftcenter-rot"
        ))
dev.off()
`
![image](https://user-images.githubusercontent.com/67954435/97249067-15571680-183e-11eb-9640-f821c6174522.png)

**Comment by jokergoo** [comment]
Hi, can you update the package for GitHub to the newest version? I think I've fixed that bug.

**Comment by zenghh1226** [comment]
Thank you very much! I am updating the package and then try again.
