### ISSUE TITLE
anno_mark still not working with split

### ISSUE THREAD

**Issue by zezhuo** [jokergoo/ComplexHeatmap#620]
`anno_mark()` works when the rows are split. Try following code:

```
m = matrix(rnorm(1000), nrow = 100)
ha = rowAnnotation(foo = anno_mark(at = c(1:4, 20, 60, 97:100), labels = month.name[1:10]))
Heatmap(m, name = "mat", cluster_rows = FALSE, right_annotation = ha, row_km = 2)
```
![image](https://user-images.githubusercontent.com/449218/51735208-0babe800-2087-11e9-80df-5962f5407299.png)

_Originally posted by @jokergoo in https://github.com/jokergoo/ComplexHeatmap/issues/196#issuecomment-457500881_

**Comment by zezhuo** [comment]
![plot_zoom_png](https://user-images.githubusercontent.com/48099632/97262797-91605700-185c-11eb-88e9-fde287c7b718.png)
![Rplot](https://user-images.githubusercontent.com/48099632/97262799-91f8ed80-185c-11eb-8bfe-b631a9375546.png)

**Comment by zezhuo** [comment]
I want to convert the Heatmap object into a grob, so that I can organized the plots well. To do so I write the annotation function as follow to generate a compact Heatmap object. However, when the Heatmap grob generated by `grid.grabExpr(draw(hm, merge_legend = TRUE)) `do not print the anno_mark correctly using pdf device. Any suggestion for my case? Thanks!

```
anno3 = AnnotationFunction(
  fun = function(index, k, n) {
    cn <- levels(mnnCT7$cluster)[k]
    grid.rect(x = 0, width = unit(2, "mm"), 
              gp = gpar(fill = unname(col.CT7[cn]), col = NA), 
              just = "left")
    go.term <- go.tb %>% filter(cluster.name == cn) %>% pull(term_name) %>% paste(collapse = "\n")
    grid.text(go.term, x = unit(4, "mm"), just = "left", 
              gp = gpar(fontsize = 8, lineheight = 1, col = unname(col.CT7.new[cn])))
   },
  which = "row",
  width = max_text_width(go.tb$term_name)*(8/11) + unit(4, "mm")
)
```

**Comment by jokergoo** [comment]
`anno_mark()` is affected by the absolute size of the graphics device. For example,  you made a plot with `anno_mark()` in an interactive device, if you change the size of the device by dragging the graphic window, the positions of the links will be wrong, and you must regenerate the plot.

I think the key thing is you need to manually calculate the width and height when you use `grid.grabExpr()`. `grid.grabExpr()` internally opens a pdf device and the size of that pdf device affects the positions of `anno_mark()`.

Maybe you can check this blog post: https://jokergoo.github.io/2020/07/14/integrate-complexheatmap-with-cowplot-package/. It demonstrated `anno_link()`, but it is basically the same as `anno_mark()`.

**Comment by zezhuo** [comment]
Hi @jokergoo,

Thanks for the advice! `F1c <- grid.grabExpr(draw(hm, merge_legend = TRUE), height = 21/1.5/12*3.5)` works well.

By the way, how can I move the annotation name for the anno3 above on the top. For the AnnotaionFunction, only show_name variable is available. annotation_name_side is no available. Thanks!

Regards,
Nelson

**Comment by zh542370159** [comment]
If you want to convert a ComplextHeatmap containing the anno_mark annotation to a grob:

- **When you plot one heatmap with `row_split` parameter, the following code will work in the current graphics device as @jokergoo mentioned:**
```
 ht <- Heatmap(...)
 height <- convertHeight(unit(1, "npc"), "inch", valueOnly = TRUE)
 width <- convertWidth(unit(1, "npc"), "inch", valueOnly = TRUE)
 gTree <- grid.grabExpr(
    {draw(ht)},
    height = height,
    width = width
  )
 p <- plot_grid(gTree)
```

- **However, the anno_mark cannot be aligned correctly in the heatmap when zooming in/out in the rstudio. Setting a fixed height and width for the heatmap will solve this problem.**

1. **Function to fix the panel in grob object:**

 ```
library(ggplot2)
 library(gtable)
 library(grid)
panel_fix <- function(p = NULL, grob = NULL,
                      width = NULL, height = NULL, margin = 1, units = "cm",
                      filename = NULL) {
  if (is.null(p) & is.null(grob)) {
    stop("'p' or 'grob' must be provided with at least one.")
  }
  if (is.null(width) & is.null(height)) {
    stop("'width' or 'height' must be provided with at least one.")
  }
  if (is.null(grob)) {
    grob <- ggplotGrob(p)
  }

  panels <- grep("panel", grob[["layout"]][["name"]])
  panel_index_h <- sort(unique(grob[["layout"]][["t"]][panels]))
  panel_index_w <- sort(unique(grob[["layout"]][["l"]][panels]))
  nw <- length(panel_index_w)
  nh <- length(panel_index_h)
  raw_w <- as.numeric(grob[["widths"]][panel_index_w])
  raw_h <- as.numeric(grob[["heights"]][panel_index_h])
  raw_aspect <- raw_h / raw_w
  if (is.null(width)) {
    width <- height / raw_aspect
  }
  if (is.null(height)) {
    height <- width * raw_aspect
  }
  if (!length(width) %in% c(1, length(raw_aspect)) | !length(height) %in% c(1, length(raw_aspect))) {
    stop("The length of 'width' and 'height' must be 1 or the length of panels.")
  }
  if (length(width) == 1) {
    width <- rep(width, nw)
  }
  if (length(height) == 1) {
    height <- rep(height, nh)
  }
  grob[["widths"]][panel_index_w] <- unit(width, units = units)
  grob[["heights"]][panel_index_h] <- unit(height, units = units)
  grob <- gtable_add_padding(grob, unit(margin, units = units))
  plot_width <- convertWidth(sum(grob[["widths"]]), unitTo = units, valueOnly = TRUE)
  plot_height <- convertHeight(sum(grob[["heights"]]), unitTo = units, valueOnly = TRUE)

  if (!is.null(filename)) {
    ggsave(filename = filename, plot = grob, units = units, width = plot_width, height = plot_height)
  }
  attr(grob, "size") <- list(units = units, width = plot_width, height = plot_height)
  return(grob)
}
```

2. **Then you can easily fix the heatmap height and width by converting it to grob  just like before:**

```
 gTree <- grid.grabExpr(
    {draw(ht)},
    height = height,
    width = width
  )
  p_fix <- panel_fix(plot_grid(gTree), width = width, height = height, units = units)
  p <- plot_grid(p_fix)

```

- **Note: if the current size of the graphics device is too small, the color mapping of the heatmap will be wrong. So it is recommended to set the minimum height and width:**
```
 height <- max(convertHeight(unit(1, "npc"), "inch", valueOnly = TRUE), 7)
 width <- max(convertWidth(unit(1, "npc"), "inch", valueOnly = TRUE), 7)
```

**Comment by Tommaso12** [comment]
Hello, I am not sure if  my problem fits to the post but I give it the try.

In the heatmap below the row_annotations are not correctly mapping to the row splits. i.e. the annotations "Slfn4", "Slfn1", "Gm4951", "Cxcl10", "Cxcl9" should all map together the upper box. Also the others row annotations are messed up. 
I actually got back this message:
It seems you are using RStudio IDE. `anno_mark()` needs to work with the physical size of the graphics
device. It only generates correct plot in the figure panel, while in the zoomed plot (by clicking the
icon 'Zoom') or in the exported plot (by clicking the icon 'Export'), the connection to heatmap
rows/columns might be wrong. You can directly use e.g. pdf() to save the plot into a file.
Use `ht_opt$message = FALSE` to turn off this message.

my code:

`#heatmap (excluding nc_nc; z-score; showing all replicates)

degs.grouped <- read_tsv(file.path(results_dir, "degs.grouped.txt"))
goi_class_tb_filt <- degs.grouped %>% filter(gene_class != "nc_nc") %>% arrange(gene_class)
goi_class_tb_filt <- goi_class_tb_filt %>% filter(gene_class != "dn_up") %>% arrange(gene_class)
goi_class_tb_filt <- goi_class_tb_filt %>% filter(gene_class != "up_dn") %>% arrange(gene_class)

#split rows based on groups in gene_class
goi <- goi_class_tb_filt %>% pull(GeneSymbol)
goi_cls <- goi_class_tb_filt %>% pull(gene_class)
gene_class_up <- c("up_nc", "up_up", "nc_up")
gene_class_dn <- c("dn_nc", "dn_dn", "nc_dn")
goi_cls <- factor(goi_cls, levels=c(gene_class_up, gene_class_dn))

exp_mat_sort <- exp_mat[goi,]

exp_mat_sort_scaled <- t(apply(exp_mat_sort, 1, scale))
colnames(exp_mat_sort_scaled) <- colnames(exp_mat_sort)

#split columns based on time_point + treatment

sample_cls <- metadata.samples %>% as_tibble() %>% slice(-c(4:6)) %>% rowwise() %>% 
  mutate(ID2 = paste0(Treatment, "_", Time_Point)) %>%
  pull(ID2)

sample_cls <- factor(sample_cls, levels = c("UT_0h", "LAL_6h", "LAL_16h", "IMQ_6h", "IMQ_16h"))

goi <- exp_mat_sort_scaled %>%
  as.data.frame() %>%
  rownames_to_column(var = "GeneSymbol") %>%
  arrange(GeneSymbol)

goi_cls <- goi %>% 
          inner_join(goi_class_tb_filt, by = "GeneSymbol") %>%  
          arrange(GeneSymbol) %>%
          pull(gene_class)

goi_cls <- factor(goi_cls, levels=c(gene_class_up, gene_class_dn))

#genes annotations

w <- goi %>% column_to_rownames(var = "GeneSymbol") 

genes_highlight <- c("Slfn4", "Slfn1", "Gm4951", "Cxcl10", "Cxcl9",
                     "Fam107a", "Oprd1", "Aebp1", "Saa3", "Trim43b",
                     "Neurl1a", "Sprr2d", "D330045A20Rik", "Ripor3", "Tnfrsf19",
                     "Hpgd", "Abca6", "Ltb4r1", "Sept4", "Dkk3",
                     "Cd209a", "Drc7", "Trim16", "Plxna2", "Trpa1",
                     "Cldn10", "Stfa2", "Wnt9a", "Dlg2", "Gdf9")

x <- as.vector(which(rownames(w) %in% genes_highlight))

ha = rowAnnotation(foo = anno_mark(at = x, labels = genes_highlight, 
                                   labels_gp = gpar(fontsize = 7, fontface = "bold")))

#kinetic groups bars annotations

goi_class_tb_filt <- goi_class_tb_filt %>% arrange(GeneSymbol)

kgs_col <- list(kinetic_groups = c("up_nc" = "#1b7837", "up_up" = "#7fbf7b", "nc_up" = "#d9f0d3", 
                                   "dn_nc" = "#762a83", "dn_dn" = "#af8dc3", "nc_dn" = "#e7d4e8"),
                T6hvsT0h = c("up" = "red", "dn" = "blue", "nc" = "grey69"),
                T16hvsT6h = c("up" = "red", "dn" = "blue", "nc" = "grey69"))


kgs <- rowAnnotation(kinetic_groups = goi_class_tb_filt$gene_class,
                     T6hvsT0h = goi_class_tb_filt$gene_class_6h,
                     T16hvsT6h = goi_class_tb_filt$gene_class_16h_vs_6h,
                     col = kgs_col,
                     annotation_legend_param = list(kinetic_groups = list(title="Kinetic Groups"),
                                                    T6hvsT0h = list (title = "6hvs0h"),
                                                    T16hvsT6h = list (title = "16hvs6h")))


#gns <-  list(gene_numbers = c("up_nc" = paste0("n=", "1474"), 
                          #"up_up" = paste0("n=", "111"), 
                          #"nc_up" = paste0("n=", "282"), 
                          #"dn_nc" = paste0("n=", "1535"), 
                          #"dn_dn" = paste0("n=", "117"), 
                          #"nc_dn" = paste0("n=", "202")))


hm.df <- goi %>%
  #as.data.frame() %>%
  column_to_rownames(var = "GeneSymbol") %>%
  select(1:3, 7:18) %>% 
  as.matrix()

HM.degs <- Heatmap(hm.df,
              #width = ncol(hm.df)*unit(4, "mm"), 
              #height = nrow(hm.df)*unit(0.1, "mm"),            
              heatmap_legend_param = list(title = "z-score"),
              col = colorRamp2(c(-2, 0, 2), c("blue", "whitesmoke", "red")),
              show_row_names = FALSE, 
              row_split = goi_cls,
              row_title = NULL,
              row_gap = unit(2, "mm"),
              row_names_gp = grid::gpar(fontsize = 0.3),
              show_row_dend = FALSE,
              column_gap = unit(2, "mm"),
              column_split = sample_cls,
              column_title = NULL,
              cluster_columns = FALSE,
              cluster_column_slices = FALSE,
              show_column_names = FALSE,
              border = TRUE,
              use_raster = FALSE,
              right_annotation = ha,
              left_annotation = kgs
)
HM.degs
out_path <- paste0(plots_dir, "/HMs/", "HM.degs.pdf")
pdf(out_path, width = 5, height = 15)
draw(HM.degs, padding = unit(c(2, 2, 2, 2), "mm"))
dev.off()`
[HM.degs.pdf](https://github.com/jokergoo/ComplexHeatmap/files/9753392/HM.degs.pdf)

Could you help me? Thank you a lot!

**Comment by Tommaso12** [comment]
@jokergoo thank you for your reply. I manged to fix the problem in the meantime. Cheers!
