### ISSUE TITLE
vertical white lines

### ISSUE THREAD

**Issue by ccshao** [jokergoo/ComplexHeatmap#621]
Hello, 

When saving the heatmap to pdf/png files, the plots show vertical white lines, more in png files.
Input is a large matrix, 113 genes by 10154 cells. 

Here is the codes for a pdf file, `draw` makes no difference.
```
pdf("net_heatmap.pdf", height = 10)
draw(
ComplexHeatmap::Heatmap(mtx,
                        name                      = "mat",
                        col                       = colfn,
                        top_annotation            = colanno,
                        show_column_name          = FALSE,
                        clustering_method_rows    = "ward.D2",
                        clustering_method_columns = "ward.D2",
                        row_names_gp              = grid::gpar(fontsize = 4))
)
dev.off()

```
Googled it but I don't get a clear answer. Any suggestions? Many thanks!

Saved pdf file
![Screenshot_2020-10-27_10-32-46](https://user-images.githubusercontent.com/4980631/97284030-d5456300-1840-11eb-840d-4318e9569fe0.png)

Saved png file

![Screenshot_2020-10-27_10-32-58](https://user-images.githubusercontent.com/4980631/97284044-da0a1700-1840-11eb-8bfb-a3bbd34bb532.png)

**Comment by jokergoo** [comment]
Hi, can you update the package for GitHub to the newest version? I think I've fixed that bug (I hope!).

**Comment by ccshao** [comment]
Thanks, the lastest version solved the issue. 

By the way, with magick package, the saved figure was blurry. An example is shown below.
![Screenshot_2020-10-28_14-16-35](https://user-images.githubusercontent.com/4980631/97442089-c1c1f700-1929-11eb-8c32-2844ccf029f4.png)

**Comment by mmfalco** [comment]
Hi @jokergoo, I am using the l am trying to replicate the output plot from[ inferCNV package](https://github.com/broadinstitute/inferCNV/wiki) using a recent version of your package (2.7.6.1004).I'm trying to get som plot like this:
![infercnv](https://user-images.githubusercontent.com/12033098/108248731-e6521100-715c-11eb-9ae3-d4c79bade64c.png)

I'm having some white lines but in the row annotation color bars of the upper heatmap. In my case (sorry but I can't share the plot) there are ~7000 rows in the upper heatmap,so it's probable it is due to a raster problem, but even specifying the argument `raster_device = "CairoPNG"` there are some white lines appearing in the plot.
Any suggestion?
Thanks in advance

**Comment by jokergoo** [comment]
@mmfalco What version of ComplexHeatmap are you using?

**Comment by mmfalco** [comment]
ComplexHeatmap_2.7.6.1004

**Comment by ATpoint** [comment]
Same issue here, what worked for me was to install the `magick` package.

**Comment by prinkessbambi** [comment]
@ATpoint Hi, I have the same problem but with the oncoprint() function. I've installed magick 2.7.3, but I don't see an improvement. Do you have any tips? Did you use something specific from the magick package?

**Comment by ATpoint** [comment]
@prinkessbambi I have no additional advise, sorry. It really just was installing that packing, restarting the session and done.

**Comment by avishai987** [comment]
For me, `use_raster = F`  in Heatmap function solved it.

**Comment by w2felix** [comment]
I have the same issue for Oncoprints, 

I tried to follow all of your suggestions, but 
`use_raster = TRUE, raster_by_magick = TRUE`
did not help and also turning rastering of produced the same white lines: 
`use_raster = F`

No issues with the top annotation, just the main heatmap produces these white lines:
![image](https://github.com/user-attachments/assets/8d00f1af-30cd-4693-80ff-aee1afd0bb00)

```
col = c(`>100 TPM` ="green")
alter_fun = list(
    background = alter_graphic("rect", fill = "lightgrey"),   
    `>100 TPM` = alter_graphic("rect", width = 1, horiz_margin = unit(0, "pt"), fill = col[">100 TPM"])
)
[...]
oncoPrint(oncoprint_data,
      alter_fun = alter_fun,
      col = col,
      row_order = 1:nrow(oncoprint_data), 
      column_order = ordered_entries$patient_id,
      right_annotation = NULL,
      row_names_side = "left",
      pct_side = "right",
      use_raster = TRUE)
```

**Comment by w2felix** [comment]
I have the same issue for Oncoprints, 

I tried to follow all of your suggestions, but 
`use_raster = TRUE, raster_by_magick = TRUE`
did not help and also turning rastering of produced the same white lines: 
`use_raster = F`

No issues with the top annotation, just the main heatmap produces these white lines:
![image](https://github.com/user-attachments/assets/8d00f1af-30cd-4693-80ff-aee1afd0bb00)

```
col = c(`>100 TPM` ="green")
alter_fun = list(
    background = alter_graphic("rect", fill = "lightgrey"),   
    `>100 TPM` = alter_graphic("rect", width = 1, horiz_margin = unit(0, "pt"), fill = col[">100 TPM"])
)
[...]
oncoPrint(oncoprint_data,
      alter_fun = alter_fun,
      col = col,
      row_order = 1:nrow(oncoprint_data), 
      column_order = ordered_entries$patient_id,
      right_annotation = NULL,
      row_names_side = "left",
      pct_side = "right",
      use_raster = TRUE)
```
