### ISSUE TITLE
row_km split membership access

### ISSUE THREAD

**Issue by vkartha** [jokergoo/ComplexHeatmap#622]
Hi, thanks for making such a wonderful package. I was wondering if there is a way to obtain the km split membership (similar to how you can fetch this in pheatmap), using the main Heatmap function. For example, if I have used parameter row_km = 5, I'd like to be able to get a vector of memberships (row_km groupings) for each row feature,  saying it belongs to clusters 1-5, for downstream annotation. Is this possible using the stored Heatmap output?

**Comment by jokergoo** [comment]
Do as follows:

```r
ht = Heatmap(..., row_km = 5)
ht = draw(ht)
row_order(ht) # this returns a list of 5
```

**Comment by jokergoo** [comment]
The clustering from k-means has randomness. You need to either set the same random seed:

```r
set.seed(123)
Heatmap(...)
```

or first generate the clustering result from k-means:

```r
km = kmeans(...)$cluster
Heatmap(..., row_split = km)
```
