### ISSUE TITLE
Only 7 combinations made with make_comb_mat using 4 GRanges objects

### ISSUE THREAD

**Issue by AntonioAhn** [jokergoo/ComplexHeatmap#625]
Hi jokergoo,

Thanks so much for ComplexHeatmap. I'm really loving the make_comb_mat function, and its use with GRanges objects in order to find the sum widths of overlap. 

Currently, I'm having trouble with making a comb_mat with 4 GRange objects. I'm expecting there to be  15 different combinations however I am only getting 7. I'm wondering what may be the problem. My 4 GRange objects can be downloaded at:  [https://www.dropbox.com/s/pij8g5sa1nwn0t1/example_dataset.RData?dl=0](url)

The code i've been using is 

```r
DMSO_lt <- list(DMSO_1_Genrich, DMSO_2_Genrich, DMSO_1_macs2, DMSO_1_macs2)
names(DMSO_lt) <- c("DMSO_1_Genrich", "DMSO_2_Genrich", "DMSO_1_macs2", "DMSO_2_macs2")

DMSO_comb_mat = make_comb_mat(DMSO_lt)

UpSet(DMSO_comb_mat, comb_order = order(comb_size(DMSO_comb_mat), decreasing = TRUE), 
left_annotation = rowAnnotation(
	"Set size" = anno_barplot(set_size(DMSO_comb_mat), 
		border = FALSE, 
		gp = gpar(fill = "black"), 
		width = unit(2, "cm")
	)), right_annotation = NULL)
```

**Comment by jokergoo** [comment]
Because for some combinations, they have zero intersection (with combination size zero):

![image](https://user-images.githubusercontent.com/449218/97689423-d58d6a80-1a9b-11eb-8035-5cba867b4b4c.png)

E.g.  there is no `DMSO_1_macs2` specific regions:

```
> setdiff(DMSO_1_macs2, c(DMSO_2_Genrich, DMSO_1_macs2, DMSO_1_Genrich))
GRanges object with 0 ranges and 0 metadata columns:
   seqnames    ranges strand
      <Rle> <IRanges>  <Rle>
  -------
  seqinfo: 213 sequences from an unspecified genome; no seqlengths
```

**Comment by AntonioAhn** [comment]
Hi Jokergoo ! 

Sorry about that. A very silly mistake of mine. 

I had mistakenly used "DMSO_1_macs2" twice ... 
`DMSO_lt <- list(DMSO_1_Genrich, DMSO_2_Genrich, DMSO_1_macs2, DMSO_1_macs2)`
Should be 
`DMSO_lt <- list(DMSO_1_Genrich, DMSO_2_Genrich, DMSO_1_macs2, DMSO_2_macs2)`

it works great now. Thanks for the quick response and help! Love your work! 

Kind regards,
Antonio
