### ISSUE TITLE
Re-using split dendrograms OR subsetting matrix

### ISSUE THREAD

**Issue by jdhogan** [jokergoo/ComplexHeatmap#628]
Hello,

I have quite a unique problem, and I'm not sure what the best method may be for handling it. What I would like to do is generate a **split** Heatmap that clusters on a **subset** of columns in the data matrix, while simultaneously showing **all** of the columns. I have figured out how to save a dendrogram of the distance of just a subset of the columns and apply it to a full heatmap, and I have easily figured out how to split a dendrogram that clustered on all of the columns. Is there an easy way to do what I'm asking? Here is some code for reference:

```
# set seed for reproducibility
set.seed(12345)

# generate fake matrix
m <- matrix(runif(50), nrow=10, ncol=5)

# set column and row names
colnames(m) <- c('col1', 'col2', 'col3', 'col4', 'col5')
rownames(m) <- c('row1', 'row2', 'row3', 'row4', 'row5',
                 'row6', 'row7', 'row8', 'row9', 'row10')

# get classes for split
classes <- c(rep('classA', 5), rep('classB', 5))

# show full ComplexHeatmap, split by class
Heatmap(m, row_split=classes)

# show ComplexHeatmap, split by class, just col1 and col2
Heatmap(m[,c('col1', 'col2')], row_split=classes)

# get dendrogram just for col1 and col2
de <- dendsort::dendsort(hclust(dist(m[,c('col1', 'col2')])))

# plot Heatmap on all data, with de as row dendrogram AND split by class
Heatmap(m, cluster_rows=de, row_split=classes)
```

Any help would be greatly appreciated!

JD

**Comment by jokergoo** [comment]
Maybe you can check `cluster_within_group()` function?

**Comment by jdhogan** [comment]
Excellent! Thanks so much :)
