### ISSUE TITLE
continuous legend label position

### ISSUE THREAD

**Issue by nfancy** [jokergoo/ComplexHeatmap#630]
Hi, 
Thanks for this great package. 

I noticed for the continuous legend the maximum value comes on top and the lowest value comes at the bottom if the direction is vertical. Is there any way to reverse this? for example 0 on top and 1 at bottom? like the one here. This is done by ggplot2.

![image](https://user-images.githubusercontent.com/50167573/97791582-df15f000-1bcb-11eb-97bc-344b96e68633.png)

Thanks in advance.
Nurun

**Comment by jokergoo** [comment]
Good suggestion! I will support it.

**Comment by jokergoo** [comment]
Done, now you can set in `heatmap_legend_param` like:

```r
Heatmap(..., heatmap_legend_param = list(at = c(1, 0.75, 0.5, 0.25, 0)))
```

<img src='https://user-images.githubusercontent.com/449218/97805082-2d6ed180-1c54-11eb-9253-982b55caa033.png' width=150 />

**Comment by nfancy** [comment]
Wow! That's awesome man! so quick to implement. Thanks again.
