### ISSUE TITLE
Adding legend list with graphics

### ISSUE THREAD

**Issue by JPVW** [jokergoo/ComplexHeatmap#635]
Hi,

I'm trying to add a legend for the grid.points that are depected in my Oncoprint, however only my colours are showing. If I test my alter_fun they are there. 

I tried the piece of code from your manual to add them via graphics option of legend, however I get an error:

lgd = Legend(labels = c("clonal_MUT_pathogenic", "clonal_MUT_unknown_pathogenicity", "subclonal_MUT_unknown_pathogenicity",
                        "clonal_INDEL_unknown_pathogenicity"),
             graphics = list(
               function(x,y,w,h) grid.points(x,y, pch=24,gp = gpar(col ="black", fill= "black", cex = 0.5)), 
               function(x,y,w,h) grid.points(x,y, pch=24, gp = gpar(col="yellow", fill = "black", cex = 0.5)),
               function(x,y,w,h) grid.points(x,y, pch=24, gp = gpar(col ="black", fill="yellow", cex = 0.5)),
               function(x,y,w,h) grid.points(x,y, pch=22, gp=gpar(col="yellow", fill="black", cex = 0.5))
             ))

Error in Legend(labels = c("clonal_MUT_pathogenic", "clonal_MUT_unknown_pathogenicity",  : 
  unused argument (graphics = list(function(x, y, w, h) grid.points(x, y, pch = 24, gp = gpar(col = "black", fill = "black", cex = 0.5)), function(x, y, w, h) grid.points(x, y, pch = 24, gp = gpar(col = "yellow", fill = "black", cex = 0.5)), function(x, y, w, h) grid.points(x, y, pch = 24, gp = gpar(col = "black", fill = "yellow", cex = 0.5)), function(x, y, w, h) grid.points(x, y, pch = 22, gp = gpar(col = "yellow", fill = "black", cex = 0.5))))

![heatmap_cheers_test](https://user-images.githubusercontent.com/53212525/98289809-0b08eb00-1fa9-11eb-9f02-463cb26f8e06.png)

alter_fun = list(
  background = function(x,y,w,h)
    grid.rect(x,y,w-unit(2,"pt"), h-unit(2,"pt"),
              gp=gpar(fill="#CCCCCC", col = NA)),
  AMP = function(x,y,w,h)
    grid.rect(x,y,w-unit(2,"pt"), h-unit(2,"pt"),
              gp=gpar(fill = "#f24141", col = "white")),
  DEL = function(x,y,w,h)
    grid.rect(x,y,w-unit(2,"pt"), h-unit(2,"pt"),
              gp=gpar(fill = "#00eaff", col = "white")),
  HOMDEL = function(x,y,w,h)
    grid.rect(x,y,w-unit(2,"pt"), h-unit(2,"pt"),
              gp=gpar(fill = "#0000ff", col = "white")),
  clonal_MUT_pathogenic= function(x,y,w,h)
    grid.points(x,y, pch=24,gp = gpar(col ="black", fill= "black", cex = 0.5)),
  clonal_MUT_unknown_pathogenicity= function(x,y,w,h)
    grid.points(x,y, pch=24, gp = gpar(col="yellow", fill = "black", cex = 0.5)),
  subclonal_MUT_unknown_pathogenicity = function(x,y,w,h)
    grid.points(x,y, pch=24, gp = gpar(col ="black", fill="yellow", cex = 0.5)),
  clonal_INDEL_unknown_pathogenicity =function(x,y,w,h)
    grid.points(x,y, pch=22, gp=gpar(col="yellow", fill="black", cex = 0.5))
)
![alter_fun](https://user-images.githubusercontent.com/53212525/98290046-5ae7b200-1fa9-11eb-9589-cba36dde6b69.png)

Do you have any insights that could help me resolve this error?

Thanks in advance!

**Comment by jokergoo** [comment]
Hi, I guess the version of your ComplexHeatmap is too low. To use `graphics` argument, it needs to be >= 2.6.0.

Also, with the new version of ComplexHeatmap, the legends for oncoprints are improved where all the graphics you defined in `alter_fun` are drawn in the legends automatically. Have a try!

**Comment by JPVW** [comment]
Hi,

Figured it out with legend list however your solution is much easier :') I got it to work! 

Thanks for the fast reply
