### ISSUE TITLE
ordering columns in a vertical heatmaplist

### ISSUE THREAD

**Issue by Thor90DK** [jokergoo/ComplexHeatmap#636]
Hi,

Thanks for a great package! 

I have a vertical heatmaplist with 3 heatmaps. They contain a matrix for the same individuals but from 3 different sites. The dendrogram orders the 3 individual heatmaps a bit different from each other. I want to show them vertically for direct comparison between individuals and not taking into account the dendrogram. But when I do the vertical heatmaplist I get the message below. How can I come around this? I have tried multiple things. My column names are Donor1, Donor2, Donor3

Warning messages:
1: Column names of heatmap 2 is not consistent as the main heatmap (1) 
2: Column names of heatmap 3 is not consistent as the main heatmap (1)

**Comment by Thor90DK** [comment]
I have tried 
co_1 <- column_order(mymainheatmap)
Heatmap(....,column_order = co_1,...

**Comment by jokergoo** [comment]
Please also attach a runnable example.

**Comment by Thor90DK** [comment]
> ht_list = ht_v %v% ht_c %v%  ht_e
Warning messages:
1: Heatmap/annotation names are duplicated: Relative abundance 
2: Heatmap/annotation names are duplicated: Relative abundance, Relative abundance 
> column_order(ht_list)
 [1] 23  7 19  9 13 40  4 25 18 15 26 46 45 37 28 14  6 31 27 10  8 30 29 38 51  1 17 11 36 22 32 49 44 21 24  5 41 39 33 20
[41] 48 47 50 52 53  3 43 35  2 12 16 34 42
Warning messages:
1: Column names of heatmap 2 is not consistent as the main heatmap (1) 
2: Column names of heatmap 3 is not consistent as the main heatmap (1) 
> draw(ht_list, merge_legends = TRUE)
Warning messages:
1: Column names of heatmap 2 is not consistent as the main heatmap (1) 
2: Column names of heatmap 3 is not consistent as the main heatmap (1)

**Comment by jokergoo** [comment]
Hi, a "runnable example" means some variables and code that I can directly rerun on my computer and reproduce your error.

**Comment by Thor90DK** [comment]
Sorry, I am new to this... I actually solved it by applying the same hclust to all heatmaps in cluster_columns=

**Comment by jokergoo** [comment]
OK, then according to what you described, I think to use the vertical alignment of the heatmaps, you need to make sure the column order of all the three matrices are the same. E.g.

```r
Heatmap(m1) %v% Heatmap(m2) %v% Heatmap(m3)
```

The column order of `m1`, `m2` and `m3` should be all the same.
