### ISSUE TITLE
make_comb_mat errors if there are rows that are all 0.

### ISSUE THREAD

**Issue by drtconway** [jokergoo/ComplexHeatmap#637]
Hi ComplexHeatmap

Thanks for a great package.

I've am running under R 4.0.2.

I have a big `data.table` of variant allele frequencies, with columns corresponding to the locus, sample name, and VAF.

My code does the following to build a table of Boolean values to pass in to make an `UpSet` plot.
```r
nms <- all.snvs[, unique(nm)]
snv.matrix <- dcast(all.snvs[, .(chr, pos, ref, alt, present = (vaf > 0.5))], chr + pos + ref + alt ~ nm, value.var="present")
snv.matrix <- snv.matrix[,5:dim(snv.matrix)[2]]
comb.mat <- make_comb_mat(snv.matrix)
```

When I run this, I get the following error:
```
Error in if (k) { : argument is not interpretable as logical
```

After a bit of hunting around, I see it's coming from `UpSet.R` line 54. I presume the error would be fixed by changing the line to
```r
if (k > 0) {
```

I have managed to work around the problem by filtering the rows to remove rows of all 0s.
```r
snv.matrix <- snv.matrix[rowSums(snv.matrix)>0]
```

**Comment by jokergoo** [comment]
For this line:

```r
snv.matrix <- snv.matrix[rowSums(snv.matrix)>0]
```

are you sure `snv.matrix` is a matrix? 

Can you send me the variable `snv.matrix`?

**Comment by drtconway** [comment]
You're quite right. It's a data.table, not a matrix, but the behaviour is as I described.

Hmm. Github won't let me attach a .rds file. Or .R files. You'll need to rename `x.txt` -> `x.rds`, `tryMe.txt` -> `tryMe.R`, and `thisWorks.txt` -> `thisWorks.R`.

[x.txt](https://github.com/jokergoo/ComplexHeatmap/files/5513854/x.txt)
[tryMe.txt](https://github.com/jokergoo/ComplexHeatmap/files/5513865/tryMe.txt)
[thisWorks.txt](https://github.com/jokergoo/ComplexHeatmap/files/5513866/thisWorks.txt)

```
$ Rscript tryMe.R 
Loading required package: grid
========================================
ComplexHeatmap version 2.4.3
Bioconductor page: http://bioconductor.org/packages/ComplexHeatmap/
Github page: https://github.com/jokergoo/ComplexHeatmap
Documentation: http://jokergoo.github.io/ComplexHeatmap-reference

If you use it in published research, please cite:
Gu, Z. Complex heatmaps reveal patterns and correlations in multidimensional 
  genomic data. Bioinformatics 2016.

This message can be suppressed by:
  suppressPackageStartupMessages(library(ComplexHeatmap))
========================================

Error in if (k) { : argument is not interpretable as logical
Calls: make_comb_mat -> make_comb_mat_from_matrix
Execution halted
$ Rscript thisWorks.R
Rscript thisWorks.R
Loading required package: grid
========================================
ComplexHeatmap version 2.4.3
Bioconductor page: http://bioconductor.org/packages/ComplexHeatmap/
Github page: https://github.com/jokergoo/ComplexHeatmap
Documentation: http://jokergoo.github.io/ComplexHeatmap-reference

If you use it in published research, please cite:
Gu, Z. Complex heatmaps reveal patterns and correlations in multidimensional 
  genomic data. Bioinformatics 2016.

This message can be suppressed by:
  suppressPackageStartupMessages(library(ComplexHeatmap))
========================================

$
```

**Comment by jokergoo** [comment]
I think the problem is you have NA values in the object:

```r
> x[c(49525, 52076, 66627), ]
   PRJ190318 PRJ190319 PRJ190320 PRJ190559 PRJ190560
1:        NA     FALSE        NA     FALSE        NA
2:     FALSE     FALSE        NA        NA        NA
3:     FALSE        NA        NA     FALSE        NA
```

Now I have updated the package and it automatically converts all NA to FALSE, with printing a warning message.

**Comment by drtconway** [comment]
Ah. I guess I had better check why they occur. :) 

Yes, good to issue a warning.

Cheers.
