### ISSUE TITLE
make_layout for single heatmap does not have heatmap_legend_side

### ISSUE THREAD

**Issue by idavydov** [jokergoo/ComplexHeatmap#641]
This goes in the direction of replacing `draw()` with `make_layout()` for future use of the plots (see #587).

It seems that `make_layout()` for a single `Heatmap` is missing many useful arguments.

```r
> ComplexHeatmap::make_layout(ComplexHeatmap::Heatmap(1:10), heatmap_legend_side="bottom")
Error in .local(object, ...) : 
  unused argument (heatmap_legend_side = "bottom")
```

This however works. I assume because now it's a list of heatmaps.

```r
ComplexHeatmap::make_layout(ComplexHeatmap::Heatmap(1:10)+NULL, heatmap_legend_side="bottom")
```

**Comment by jokergoo** [comment]
`heatmap_legend_side` is part of `draw,HeatmapList` method and is passed to `make_layout,Heatmaplist` method, so you need to add a `NULL`.
