### ISSUE TITLE
selectively change font face or size for row labels

### ISSUE THREAD

**Issue by CodeInTheSkies** [jokergoo/ComplexHeatmap#643]
Hi Zuguang,

I know it is possible to selectively name rows or change color of row labels, but is it possible to selectively have bold face or larger font size for some of the row labels?

Many thanks!

P.S.:  Sorry that I posted a different version of this question earlier, but later found out that some of those options are already available.  Hence, the edit.

**Comment by jokergoo** [comment]
Yes, you just set `fontface` and `fontsize` as a vector with the `row_names_gp` argument.

**Comment by CodeInTheSkies** [comment]
Thank you!  That worked!
