### ISSUE TITLE
Title of rownames in Heatmap

### ISSUE THREAD

**Issue by EplisonG** [jokergoo/ComplexHeatmap#645]
Hi,
Could I ask a question about how to position the "row title"? I get the heatmap with Heatmap( ) function. but the "row title" is on the left of "row names". Could I re-position the "row title" and make it above the "row names"? for example, the default format of "row title" and "row names" is:

  | Van. | C2
-- | -- | --
City Company | NY | C3
  | TOR | C4

However, the format I hope to use is:

City | Company
-- | --
  |  
Van. | C2
NY | C3
TOR | C4

I was thinking to add a "rowAnnotation (text = anno_text('City Company',.... )", but the location was difficult to adjust. It was not on the top of "row names". Could anyone kindly give some suggestions or comments? Thank you.

**Comment by jokergoo** [comment]
Currently there is no support for annotation titles, but you can manually add it by `decorate_annotation()`:

```r
ht = Heatmap(mat) + 
	rowAnnotation(foo = anno_text(letters[1:10])) +
	rowAnnotation(bar = anno_text(LETTERS[1:10]))

draw(ht, gap = unit(c(5, 8), "mm"))
decorate_annotation("foo", {
	grid.text("title1", y = unit(1, "npc") + unit(2, "mm"), just = "bottom")
})

decorate_annotation("bar", {
	grid.text("title2", y = unit(1, "npc") + unit(2, "mm"), just = "bottom")
})
```


![image](https://user-images.githubusercontent.com/449218/99870468-6820b580-2bd3-11eb-9dd9-9209ec246f2c.png)

**Comment by EplisonG** [comment]
> Currently there is no support for annotation titles, but you can manually add it by `decorate_annotation()`:
> 
> ```r
> ht = Heatmap(mat) + 
> 	rowAnnotation(foo = anno_text(letters[1:10])) +
> 	rowAnnotation(bar = anno_text(LETTERS[1:10]))
> 
> draw(ht, gap = unit(c(5, 8), "mm"))
> decorate_annotation("foo", {
> 	grid.text("title1", y = unit(1, "npc") + unit(2, "mm"), just = "bottom")
> })
> 
> decorate_annotation("bar", {
> 	grid.text("title2", y = unit(1, "npc") + unit(2, "mm"), just = "bottom")
> })
> ```
> 
> ![image](https://user-images.githubusercontent.com/449218/99870468-6820b580-2bd3-11eb-9dd9-9209ec246f2c.png)

Thank you so much for your kind and detailed reply. It's really helpful. I will try to use decorate_annotation( ) function.
