### ISSUE TITLE
Using many colors in annotation bar using dataframe column

### ISSUE THREAD

**Issue by asgarhussain** [jokergoo/ComplexHeatmap#646]
Hi,
I have 48 variables for column annotation. I use following code to generate the color with respect to the each variable. Since "Set3" have only 12 colors, I have to use other palette  also. Is there any way to solve this ?

cell_type_col = structure( brewer.pal(length(unique(df_compact_cells$Celltype)) , "Set3"), 
                      names = unique(df_compact_cells$Celltype) )

**Comment by jokergoo** [comment]
There are many color palette packages such as **Polychrome** which you can check out.
