### ISSUE TITLE
How to show the heatmap in jupyter notebook

### ISSUE THREAD

**Issue by thu1911** [jokergoo/ComplexHeatmap#647]
Hi, thank you for developing this wonderful visualization tool.  I'm using it in a jupyter notebook with an R kernel. The command is like
```
Heatmap(...)
```
However, in jupyter notebook, nothing is shown. If I set a pdf target, I can get the output properly :
```
pdf(...)
Heatmap(...)
dev.off()
```

How can I show the output in a jupyter notebook?

**Comment by jokergoo** [comment]
OK, since I never used a jupyter notebook, I haven't tested with it. No worries, I will test on it and find a solution.

**Comment by thu1911** [comment]
Thank you so much!

**Comment by jokergoo** [comment]
How did you use it with Jupyter notebook? I can see the plot:

![image](https://user-images.githubusercontent.com/449218/100537508-80bf4a00-3229-11eb-9e9e-dea22471eeda.png)

**Comment by thu1911** [comment]
Thank you for your help! I re-start a new notebook and follow your code, I can also get the output. But in my original notebook, I can not. Maybe my data is too large (~10000 * 1000) to gain enough storage for showing images in the original notebook, where I have generated lots of figures before. Maybe that is the reason?

**Comment by jokergoo** [comment]
That might be the reason. Clustering 10000x1000 matrix needs very long runtime.
