### ISSUE TITLE
OncoPrint - Draw top n genes

### ISSUE THREAD

**Issue by talipzengin** [jokergoo/ComplexHeatmap#648]
Hi,
I have 2318 CNV genes and when I used OncoPrint, it draws all genes and their frequencies. But this number is too high to show, I want to draw top 100 genes with their original frequencies in the matrix. I could not find an option as in `oncoplot` command of _maftools_ package, to filter top n genes to draw. Is there a way to do this?
Thanks in advance.

The codes I run:

```
library(ComplexHeatmap)

col = c("Del" = "blue", "Amp" = "red")
alter_fun = function(x, y, w, h, v) {
  # background
  grid.rect(x, y, w-unit(2, "mm"), h-unit(1, "mm"), gp = gpar(fill = "#CCCCCC", col = NA))
  # graphics for alterations
  if(v["Del"]) grid.rect(x, y, w-unit(2, "mm"), h-unit(1, "mm"), gp = gpar(fill = col["Del"], col = NA))
  if(v["Amp"])    grid.rect(x, y, w-unit(2, "mm"), h-unit(1, "mm"), gp = gpar(fill = col["Amp"], col = NA))
}
column_title = "OncoPrint for Significant CNV Genes"
heatmap_legend_param = list(title = "Alternations", at = c("Del", "Amp"), 
                            labels = c("Deletion", "Amplification"))

Del_genes <- cnv_results[cnv_results$Aberration=="Del",]$GeneSymbol
mat1 <- t(as.matrix(cnv_gene_matrix[,Del_genes]))

ht1 = oncoPrint(mat1,
          alter_fun = alter_fun, col = col, 
          remove_empty_columns = TRUE, remove_empty_rows = TRUE,
          pct_side = "right", row_names_side = "left",
          column_title = column_title, heatmap_legend_param = heatmap_legend_param,
          use_raster=TRUE)

tiff(file = "CNV_oncoprint_Del.tif", width = 15, height = 20, units = 'in', res = 600, compression = 'lzw')
draw(ht1)
dev.off()
```

The result plot is:

![LUAD_high_CNV_oncoprint_Del](https://user-images.githubusercontent.com/22471614/101181480-fa0dd100-365d-11eb-9c3e-be270247e3b6.jpeg)

**Comment by jokergoo** [comment]
How would you define the "top_n" genes? If they are the genes with the most numbers of mutations among samples, it is easy with:

```r
top_index = order(apply(mat, function(x) sum(x != "")), decreasing = TRUE)[1:100]
mat2 = mat[top_index, ]
oncoPrint(mat2, ...)
```

**Comment by talipzengin** [comment]
I interest in both specific genes and the genes with the highest frequency among cohort. We need a new matrix to filter; I understand now. 
Thanks very much.

I added margin argument because your code gives "Error in match.fun(FUN)". The last version of the command is below for the people to filter genes with the highest frequency:

```
top_index = order(apply(mat1, 1, function(x) sum(x != "")), decreasing = TRUE)[1:100]
mat2 = mat1[top_index, ]
oncoPrint(mat2, ...)
```

> we can specify the margin to be either 1 (apply the function to the rows of the matrix) or 2 (apply the function to the columns of the matrix).

**Comment by jokergoo** [comment]
Ah, yes, that was a mistake :)

**Comment by HiraDatascience** [comment]
Hello I am facing problem in plotting the top 30 most frequently present alterations by using this code. top_index = order(apply(mat1, 1, function(x) sum(x != "")), decreasing = TRUE)[1:30]
mat2 = mat1[top_index, ]
oncoPrint(mat2, ...)

It gives plot of only "MUT". and that also is not top 30. How can we plot top 30 highly mutated alterations .
