### ISSUE TITLE
anno_mark() plotting bug when using left_annotation in a heatmap

### ISSUE THREAD

**Issue by semmrich** [jokergoo/ComplexHeatmap#649]
Hi,
There is an issue with plotting the marks/links and labels as `left_annotation`  when using `anno_mark()`:

```
m = matrix(rnorm(1000), nrow = 100)
rownames(m) = 1:100
ha = rowAnnotation(foo = anno_mark(at = c(1:4, 20, 60, 97:100), labels = month.name[1:10]))
Heatmap(m, name = "mat", cluster_rows = FALSE, right_annotation = ha, show_row_names=FALSE)
Heatmap(m, name = "mat", cluster_rows = FALSE, left_annotation = ha, show_row_names=FALSE)
```
Is it possible to realign as in `right_annotation`? Thanks and Kudo's to a great package,
Stephan

**Comment by jokergoo** [comment]
You need to add `side = "left"` in `anno_mark()` if it is put on the left of the heatmap.

**Comment by semmrich** [comment]
Works perfect, Thank You very much for your help!
