### ISSUE TITLE
How can I control the space between rows (gene) of oncoprint?

### ISSUE THREAD

**Issue by hongenxu** [jokergoo/ComplexHeatmap#65]
Hi, 

I am new to complexHeatmap. How can I control the space between each row? I want a larger space between each row to make the figure clear. And How can I control the size (width and height) of bar  of oncoprint? Sorry if it's a stupid question. 

Best regards,
Hongen

**Comment by jokergoo** [comment]
No, absolutely not.

You cannot increase the gap between rows, but you can increase the height of the whole plot and add more paddings for each row to simulate adding gaps between rows. In following example:

```
oncoPrint(mat_list,
    alter_fun = list(
        snv = function(x, y, w, h) grid.rect(x, y, w*0.9, h*0.9, gp = gpar(fill = col["snv"], col = NA)),
        indel = function(x, y, w, h) grid.rect(x, y, w*0.9, h*0.4, gp = gpar(fill = col["indel"], col = NA))
    ), col = col)
```

`h` is the height of each row, in `grid.rect()`, if  you set height of the rectangles which represent mutations to something like `0.9*h` (the fourth argument in `grid.rect()`), it means the visible rectangles have 80% height as the rows.

To control the height of column barplots, set `annotation_height` in `top_annotation = HeatmapAnnotation(column_bar = anno_oncoprint_barplot(), annotation_height = unit(2, "cm"))`; to control the width of row barplots, set `row_barplot_width`

**Comment by hongenxu** [comment]
thanks for your help

**Comment by yaotianran** [comment]
(For other people brought by google)

**Comment by yaotianran** [comment]
(For other people brought by google)

You can't set the gap between rows. But you can draw white lines between rows so that it looks like there's space between.
For  ComplexHeatmap::Heatmap

`white.lne <- function(j, i, x, y, w, h, fill) {
   grid.lines(x = c(x - w/2, x + w / 2), y = c(y + h / 2, y + h / 2), gp = gpar(col = 'white', lwd = 1))
}` 

and the set cell_fun = white.line
