### ISSUE TITLE
Decoration functions and grid.grabExpr

### ISSUE THREAD

**Issue by funnell** [jokergoo/ComplexHeatmap#650]
Is it possible to run heatmap decoration functions on a heatmap that is "grabbed" by grid.grabExpr?

Thanks!

**Comment by jokergoo** [comment]
I don't know. `decorate_*()` function basically looks for the viewport first, then go to that viewport to add graphics. If the viewport is still there after you draw the grabbed image, then maybe you can use `decorate_*()` here.

But normally I put decoration function within `grid.grabExpr()`.

```r
grid.grabExpr({
    draw(Heatmap(...))
    decorate*(...)
})
```

**Comment by funnell** [comment]
That did the trick thanks!!
