### ISSUE TITLE
ComplexHeatmap::pheatmap

### ISSUE THREAD

**Issue by l-magnificence** [jokergoo/ComplexHeatmap#651]
It seems to be a error to draw a matrix with more than 2000 columns.
when  I run:
pheatmap(pheatmap_data,show_colnames = F,cluster_rows=T,cluster_cols = F)

it report:
`use_raster` is automatically set to TRUE for a matrix with more than 2000 columns You can control `use_raster`
argument by explicitly setting TRUE/FALSE to it.
Set `ht_opt$message = FALSE` to turn off this message.

and picture was no color
![image](https://user-images.githubusercontent.com/68798288/101272682-5b9e7e80-37c9-11eb-8195-fc147527019a.png)

**Comment by jokergoo** [comment]
It is because `pheatmap()` draws borders. With many rows and columns, the heatmap is mainly occupied by borders (maybe different PDF viewer has different visual style). Also in `ComplexHeatmap::pheatmap()` with raster turned on, the borders affect more to the plot. Try to set `border_color = NA`.

**Comment by jokergoo** [comment]
I better add a warning message there, if the number of rows/columns are too big.

**Comment by l-magnificence** [comment]
Thank you for solution, it do great!
