### ISSUE TITLE
Issue installing ComplexHeatmap in R > 4.0

### ISSUE THREAD

**Issue by PallaviSurana1** [jokergoo/ComplexHeatmap#653]
Please provide example datasets and the code you use. It will help me to understand your problem and help you!

### installation
> library(devtools)
install_github("jokergoo/ComplexHeatmap")

### error
ERROR: lazy loading failed for package ‘ComplexHeatmap’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/ComplexHeatmap’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/ComplexHeatmap’
Error: Failed to install 'ComplexHeatmap' from GitHub:
  (converted from warning) installation of package '/var/folders/ft/8_cz3ctn1xb1cr22c1lc7dlh0000gp/T//RtmpFhultv/file15f4f18739e20/ComplexHeatmap_2.7.1.1009.tar.gz' had non-zero exit status

### installation
> if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
BiocManager::install("ComplexHeatmap")

### error
Error: package or namespace load failed for 'ComplexHeatmap':
 .onLoad failed in loadNamespace() for 'Cairo', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so, 6): Library not loaded: /opt/X11/lib/libXrender.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so
  Reason: image not found
In addition: Warning message:
package 'ComplexHeatmap' was built under R version 4.0.3

**Comment by jokergoo** [comment]
Can you first remove the Cairo package by `remove.packages("Cairo")` and try again?

**Comment by PallaviSurana1** [comment]
Hi, i tried removing  "Cairo" and re-installing it. Still gives me the following error:

Error: package or namespace load failed for 'ComplexHeatmap':
 .onLoad failed in loadNamespace() for 'Cairo', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so, 6): Library not loaded: /opt/X11/lib/libXrender.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so
  Reason: image not found
In addition: Warning message:
package 'ComplexHeatmap' was built under R version 4.0.3

**Comment by jokergoo** [comment]
Can you first restart R, then `install.packages("Cairo")`?

**Comment by jokergoo** [comment]
Maybe this reason?

https://support.bioconductor.org/p/p133999/#p134005

**Comment by PallaviSurana1** [comment]
It works Thank you!

Regards,
Pallavi Surana
Website <http://pallavisurana1.github.io>
