### ISSUE TITLE
Using a pre-generated dendrogram

### ISSUE THREAD

**Issue by RaphMet** [jokergoo/ComplexHeatmap#658]
Hi, thanks a lot for developping these wonderful tools (circplot and cplxHeatmap) and their really nicely documented reference books.

I was wondering whether it was possible to include in the graphs a pre-generated dendrogram aside of the heatmap, that would not reorder the rows of the heatmap? 
This question comes from the fact that I wanted to draw heatmaps with many other annotations (annopoint, bars etc) using matrices having already their own phylogeny (data matrices are ordered following these phylogenies). I join an example of some of the generated panels. From there I would like to add the corresponding row dendrogram on the left side of the 3 heatmaps. 
But if i include the dendrogram data (row_dend) using 
`Heatmap(main_mtrix, name = "main", cluster_rows=row_dend, row_dend_side = "left",...`
this reorders all the heatmaps and therefore nothing corresponds anymore to the dendrogram...
I tried to include the `main_heatmap= "main" in the draw(htmap_list...)` command but this does not work.
I also tried to include either (or both)` row_order = NULL` or `row_dend_reorder = NULL`,.. in this line but this didn't work either
Is there an easy solution using some parameters I've not seen yet? Another annotation type panel? 
Thanks a lot

![Sans titre](https://user-images.githubusercontent.com/76062630/102248927-13d2d200-3f02-11eb-9c5c-bad9bdcaec7a.png)

**Comment by jokergoo** [comment]
I think you can use the original matrix (the one that has not been reordered) plus your dendrogram. When making the heatmap, the matrix will be automatically reordered according to the dendrogram.

```
ht_list = Heatmap(...) + Heatmap(...) + Heamtap(..., name = "main", cluster_rows = your_dend)
draw(ht_list, main_heatmap = "main")
```
