### ISSUE TITLE
Breaks in Color Scales are Wrong

### ISSUE THREAD

**Issue by toobiwankenobi** [jokergoo/ComplexHeatmap#659]
Hi Zuguang!

I've noticed a weird behavior when you indicate a color vector for the heatmap. Somehow, a vector ranging from -3 to 3 gets displayed from -4 to 4. The colors are correctly interpolated but the range is "wrongly" displayed. For other ranges, it works perfectly fine. Do you have an explanation for this? Is this an intended behavior? If yes, I think this could be misleading because people tend to check the min/max range of the coloring and then assume that the brightest color corresponds to the min/max value from the color scale bar. 

```R 
Heatmap(mat)
```

![image](https://user-images.githubusercontent.com/38858452/102385010-9e343800-3fcd-11eb-8fe7-35161af4b2fc.png)

```R 
Heatmap(mat,
        col = colorRamp2(seq(-3, 3, length = 3), c("blue", "#EEEEEE", "red")))
```

![image](https://user-images.githubusercontent.com/38858452/102385079-b310cb80-3fcd-11eb-9328-9f9a9d300674.png)

```R 
Heatmap(mat,
        col = colorRamp2(seq(-5, 5, length = 3), c("blue", "#EEEEEE", "red")))
```

![image](https://user-images.githubusercontent.com/38858452/102385119-befc8d80-3fcd-11eb-93f3-116137a1fa82.png)

```R
sessionInfo()
...
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS
ComplexHeatmap_2.4.3
circlize_0.4.10
...
```

**Comment by jokergoo** [comment]
When you specify:

```
Heatmap(mat,
        col = colorRamp2(seq(-3, 3, length = 3), c("blue", "#EEEEEE", "red")))
```

it does not mean -3, 0, 3 should be the breaks on the legend (although you can manually control it). The color mapping function only defines the colors, while the default break values on the legends are calculated from the input matrix with 3 to 5 break values. In your code, you see 4 and -4 are the border of the legend, actually, all values between 3\~4 are mapped to red and all the values between -3\~-4 are mapped to blue.

If you want to exactly control the break values on the legend, you can set `heatmap_legend_param` argument:

```r
Heatmap(..., heatmap_legend_param = list(at = c(-3, 0, 3)))
```

**Comment by XiaoyuLi-smu** [comment]
I have a similiar question. While setting the col parameter with colorRamp2 for Heatmap function, the non-integer legend breaks I set would be adjusted to integers. I've checked the colorRamp2 function, and I found it mapped the matrix value linearly to the colors within the range of breaks I set. So I would like to know how the transform happens and would like the breaks be shown as I set.
Heatmap(mat,
        cluster_rows = F,
        cluster_columns = F,
        show_column_names = F,
        show_row_names = F,
        column_title = NULL,
        column_split = cluster_info,
        col =  colorRamp2(seq(-0.2555696,4.601095, length = 3), 
                          c("blue", "#EEEEEE", "red")))
![image](https://user-images.githubusercontent.com/37774987/103281308-769d9080-4a0d-11eb-887f-62a8c31ae12c.png)
Heatmap(mat,
        cluster_rows = F,
        cluster_columns = F,
        show_column_names = F,
        show_row_names = F,
        column_title = NULL,
        column_split = cluster_info,
        col =  colorRamp2(seq(-0.21,4.1, length = 3), 
                          c("blue", "#EEEEEE", "red")))
![image](https://user-images.githubusercontent.com/37774987/103281369-97fe7c80-4a0d-11eb-9462-b829cf81be55.png)
Heatmap(mat,
        cluster_rows = F,
        cluster_columns = F,
        show_column_names = F,
        show_row_names = F,
        column_title = NULL,
        column_split = cluster_info,
        col =  colorRamp2(seq(-0.26,4.1, length = 3), 
                          c("blue", "#EEEEEE", "red")))
![image](https://user-images.githubusercontent.com/37774987/103281462-c67c5780-4a0d-11eb-9152-6a427bfe1ba3.png)

**Comment by jokergoo** [comment]
As I said before, `colorRamp2()` only defines the color mapping, while not the breaks on the legend. The breaks on the legend are calculated to fit 1. number of breaks is around 3~5, 2. covers all values in the matrix, 3. as integers. It is calculated here:

https://github.com/jokergoo/ComplexHeatmap/blob/3612bf570cee691f7437c7e547bfb00f85b36f1a/R/ColorMapping-class.R#L105-L115

**Comment by toobiwankenobi** [comment]
> When you specify:
> 
> ```
> Heatmap(mat,
>         col = colorRamp2(seq(-3, 3, length = 3), c("blue", "#EEEEEE", "red")))
> ```
> 
> it does not mean -3, 0, 3 should be the breaks on the legend (although you can manually control it). The color mapping function only defines the colors, while the default break values on the legends are calculated from the input matrix with 3 to 5 break values. In your code, you see 4 and -4 are the border of the legend, actually, all values between 3~4 are mapped to red and all the values between -3~-4 are mapped to blue.
> 
> If you want to exactly control the break values on the legend, you can set `heatmap_legend_param` argument:
> 
> ```r
> Heatmap(..., heatmap_legend_param = list(at = c(-3, 0, 3)))
> ```

Thank you, that was the thing I was looking for!
