### ISSUE TITLE
`HeatmapAnnotation` error: length of simple annotations differ. 

### ISSUE THREAD

**Issue by msquatrito** [jokergoo/ComplexHeatmap#66]
Hi,
I've recently updated to the latest bioconductor ComplexHeatmap version (V 1.6.0) . Some of the code that was working before it's now giving me an error: 

**Error in HeatmapAnnotation(an, show_annotation_name = TRUE) : 
  length of simple annotations differ.**

In my code I can remove the arg `show_annotation_name = TRUE` to fix it, but I loose the annotation name. I've tried the code that you have in the [vignette](https://github.com/jokergoo/ComplexHeatmap/blob/68749d3b202043dfd61abac73749e8f81be46135/vignettes/s4.heatmap_annotation.Rmd#add-annotation-names) but it's giving me a similar error.

I don't think it's related to the argument `show_annotation_name = TRUE` because it doesn't work even if I set it  `= FALSE`.

Any suggestion on how to fix it?

Thanks

Massimo

**Comment by msquatrito** [comment]
Never mind, I thought the Bioconductor version was updated. I guess I was confused by the the version numbers (Biconductor 1.6.0 and Github 1.13.1). Re-installing the  Github version fixed the issue. 

Are you planning to update the Bioconductor version anytime soon?

**Comment by jokergoo** [comment]
Bioconductor has its own rule for releasing packages. There are two branches for version controlling the packages, one is release branch which is updated twice a year and a development branch which can be updated by developers anytime. When you use `biocLite()` with default settings to install bioconductor packages, it always refers to the current release branch, which is stable but not very up-to-date. I think Bioconductor just released the newest version last month in which ComplexHeatmap package was bumped to 1.12.0. I always developed on Github, so here is always the newest version.
