### ISSUE TITLE
Non-random colors

### ISSUE THREAD

**Issue by ATpoint** [jokergoo/ComplexHeatmap#661]
Hello, first of all thank you for putting together this awesome and versatile package. I only want to add a minor suggestion towards the color for the annotations. From what I get it is currently random if not explicitely defined, often ending up like below, I think it should be a default color palette that achieves good separation between groups rather than shades of the same color if one is unlucky. I know one can define it explicitely, just this kind of randomness is a bit unfortunate. Thank you!

<img width="667" alt="Screenshot 2021-01-06 at 18 34 52" src="https://user-images.githubusercontent.com/21218078/103801699-652c3800-504e-11eb-8023-c4cd46c136af.png">

**Comment by jokergoo** [comment]
Thanks for your suggestion!

In your example, there is only one annotation and it is easy to assign a default palette for it. The thing is if I add a new feature, I need to make it general, which means, I also need to consider the scenarios where there are many annotations with no color pre-set.

Or I can improve a nicer random color generation method, but indeed, this needs to be improved!

**Comment by jokergoo** [comment]
https://cran.r-project.org/web/packages/Polychrome/index.html

**Comment by jokergoo** [comment]
I have improved the random color calculation a little bit. It is not very perfect, but it won't generate all dark colors...

You can update circlize package from GitHub.

**Comment by nirshahaf** [comment]
Hi, sorry for bursting in, but somehow despite following previous examples, I keep getting the random color mapping in my row annotations, eg:
```
		vip_colors = c("wheat1","wheat2","wheat4") 
		names (vip_colors) = sort (unique (vip_levels$VIP))
		HA = rowAnnotation (
			df=vip_levels,
			col=list (vip_levels=vip_colors),
			width=unit(4,"mm")
		)

```
> > HA
> A HeatmapAnnotation object with 1 annotation
>   name: heatmap_annotation_47 
>   position: row 
>   items: 2305 
>   width: 5mm 
>   height: 1npc 
>   this object is subsetable
>   18.6487666666667mm extension on the bottom 
>  name annotation_type color_mapping width
>  VIP_level discrete vector        random   5mm

Any clue? 

Sorry again for getting a bit out of context here...

**Comment by jokergoo** [comment]
Chane this line:

```r
			col=list(vip_levels=vip_colors),
```

to

```r
			col=list(VIP=vip_colors),
```

The "variable name" in `df` (which is `vip_levels`) is `VIP`, so you should assign the same name to `col`.

**Comment by nirshahaf** [comment]
It works perfectly, thanks!
