### ISSUE TITLE
Changing legend color and lable

### ISSUE THREAD

**Issue by beginner984** [jokergoo/ComplexHeatmap#662]
With this code I have this complexheatmap

    left_annotation = rowAnnotation(Peak = anno_text(left_anno$Peak),
                                    Percentage = anno_barplot(left_anno$Percentage_altered_nr,
                                                              gp = gpar(fill = "gold"),
                                                              axis_param = list(direction = "reverse"),
                                                              width = unit(20, "mm"),ylim = c(0, 70))
    
    right_annotation = rowAnnotation(Percentage = anno_barplot(right_anno$Percentage_altered_r,
                                                              gp = gpar(fill = "gold"),
                                                              width = unit(20, "mm"),ylim = c(0, 60)
                                                              ))

    Heatmap(mat, border = T, show_column_names = F,
            rect_gp = gpar(col = "white", lwd = 1),
            column_split = response$response, 
            col = col_fun,
            show_column_dend = F,
            show_row_dend = F,
            left_annotation = left_annotation,
            right_annotation = right_annotation,name = "CNV")

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/cylyo.png

This is my R object

https://www.dropbox.com/s/tsiv0fqvqo46hnn/NEW_data%20%281%29.RData?dl=0

1- The problem is, in the blocks the colors are discret but in the legend you are seeing `1 0 -1 -2` . How I can change the so in the legend I have `red` as `Amp`, `blue` as `Del` and `grey` as `Netral` please?

2- How I can make the genes here italic?

**Comment by jokergoo** [comment]
How about:

```r
Heatmap(mat, border = T, show_column_names = F,
        rect_gp = gpar(col = "white", lwd = 1),
        column_split = response$response, 
        col = c("-2" = "blue", "0" = "grey", "1" = "red"),
        heatmap_legend_param = list(at = c("-2", "0", "1"), labels = c("Del", "Netral", "Amp")),
        show_column_dend = F,
        show_row_dend = F,
        left_annotation = left_annotation,
        right_annotation = right_annotation,name = "CNV",
        row_names_gp = gpar("fontface" = "italic")
)
```

![image](https://user-images.githubusercontent.com/449218/104135354-16550a00-5390-11eb-82e4-c13d23ef7727.png)

**Comment by jokergoo** [comment]
You can check the 5th figure in Section https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#colors

**Comment by beginner984** [comment]
Thank you very much

Is there any way to place genes next to peak like what I done mannually in pain?

![Picture1](https://user-images.githubusercontent.com/43682980/104135896-98423480-538a-11eb-95b0-5835e00292a5.png)

**Comment by jokergoo** [comment]
row_names_side = 'left'

**Comment by beginner984** [comment]
Thank you very much I really could not find that by googling unless I must change whole of my data format which was not feasible

That gave me like this

![Figure4B_another_visualization](https://user-images.githubusercontent.com/43682980/104139443-64bfd400-53a3-11eb-8f9e-94b23135a0ce.png)

Is this possible to put some distance between genes and peak to be readable more?

**Comment by jokergoo** [comment]
The simplest solution is to add space after your row names:

```r
rownames(mat) = paste0(rownames(mat), "    ")
```

**Comment by beginner984** [comment]
Thank you so much

Now the plot is great

![Figure4B](https://user-images.githubusercontent.com/43682980/104497432-3ecc4680-55d2-11eb-8234-21543753e131.png)

**Comment by jokergoo** [comment]
Set the `levels` for `column_split`:

```
Heatmap(...,
    column_split = factor(response$response, levels = c("Reponders", "Non-responders")),
    ...
)
```

**Comment by beginner984** [comment]
Thank you so much

I get this error
```

> Heatmap(mat, border = T, show_column_names = F,
+         rect_gp = gpar(col = "white", lwd = 1),
+         column_split = response$response, 
+         col = c("-2" = "blue", "0" = "grey", "1" = "red"),
+         heatmap_legend_param = list(at = c("-2", "0", "1"), labels = c("Del", "Netral", "Amp")),
+         show_column_dend = F,
+         show_row_dend = F,
+         left_annotation = left_annotation,
+         right_annotation = right_annotation,name = "CNV",
+         row_names_gp = gpar("fontface" = "italic"),row_names_side = 'left', column_split = factor(response$response, levels = c("Reponders", "Non-responders")))
Error in Heatmap(mat, border = T, show_column_names = F, rect_gp = gpar(col = "white",  : 
  formal argument "column_split" matched by multiple actual arguments
```

**Comment by jokergoo** [comment]
delete the third line.

**Comment by beginner984** [comment]
Sorry I think the splitting gone

```
> Heatmap(mat, border = T, show_column_names = F,
+         rect_gp = gpar(col = "white", lwd = 1),
+         col = c("-2" = "blue", "0" = "grey", "1" = "red"),
+         heatmap_legend_param = list(at = c("1", "0", "-2"), labels = c("Amplification", "Neutral", "Deletion")),
+         show_column_dend = F,
+         show_row_dend = F,
+         left_annotation = left_annotation,
+         right_annotation = right_annotation,name = "CNV",
+         row_names_gp = gpar("fontface" = "italic"),row_names_side = 'left')
Warning message:
The input is a data frame, convert it to the matrix. 
>

```
![Rplot](https://user-images.githubusercontent.com/43682980/104514515-4814dd80-55e9-11eb-8ac7-8520cb804948.png)

**Comment by jokergoo** [comment]
That was my typo:

```r
    column_split = factor(response$response, levels = c("Responders", "Non-responders")),
```

**Comment by beginner984** [comment]
Sorry you kindly helped me in changing the order of groups of this plot
![MicrosoftTeams-image](https://user-images.githubusercontent.com/43682980/107522402-964adb80-6bab-11eb-9253-c297817ef42c.png)


so that, Responders come in the left and Non-responders come in the right

But I noticed that the percentage column is not right so that by changing the order of the groups, percentage column remains the same so Responders have percentage column of Non-responders

How I can edit that

This is the code

```
rownames(mat) = paste0(rownames(mat), "    ")


Heatmap(mat, border = T, show_column_names = F,
                   rect_gp = gpar(col = "white", lwd = 1),
                   col = c("-2" = "blue", "0" = "grey", "1" = "red"),
                   heatmap_legend_param = list(at = c("1", "0", "-2"), labels = c("Amplification", "Neutral", "Deletion")),
                   show_column_dend = F,
                   show_row_dend = F,
                   left_annotation = left_annotation,
                   right_annotation = right_annotation,name = "CNV",
                   row_names_gp = gpar("fontface" = "italic"),row_names_side = 'left', column_split = factor(response$response, levels = c("Responders", "Non-responders")))
```

And this is the data

https://www.dropbox.com/s/tsiv0fqvqo46hnn/NEW_data%20%281%29.RData?dl=0

Thank you so much for any help
