### ISSUE TITLE
Making SNV dataframe with wide-format from SNV long-format data

### ISSUE THREAD

**Issue by TnakaNY** [jokergoo/ComplexHeatmap#663]
Hi,

I am trying to make input dataframe for oncoprint from a file like maf (long-format with some duplicates, i.e., some sample have MUT and AMP in same gene).

I tried "pivot_wider()" in R, but it made a dataframe with some list element.  Oncoprint seems to need an annotation like "AMP;MUT". 

![image](https://user-images.githubusercontent.com/40367441/104249300-2aa11180-5439-11eb-9814-56aa2bf71e4b.png)

How do you exchange these mixed-up dataframe (mixture of NULL element, list-type element, single character element etc) to appropriate data format for ComplexHeatmap-Oncoprint function? 

I tried "str_c", but not worked well because not all element was list-type data, I guess. 

This may not be right place to ask my question, but if anyone gives me suggestion(s), it will be great help for me.

Thanks

**Comment by jokergoo** [comment]
just wrap e.g. `c("3'UTR", "Nonsense_Mutation")` into a string, `3'UTR,Nonsense_Mutation`, and later define graphics for `3'UTR` and `Nonsense_Mutation`. For `NULL`, just set it to `""`.

```r
alter_fun = list(
    "3'UTR" = function...,
    "Nonsense_Mutation" = ...
)
```

The default code `AMP;MUT` is just an example. It can be any text.

**Comment by TnakaNY** [comment]
Thank you for prompt reply.
My question was how to wrap c("A","B") into a string in dataframe.  
How do I apply str_c(dataframe, sep=";") to dataframe. Some element of dataframe are null or non-list datatype, so str_c failed.

**Comment by jokergoo** [comment]
This is a data preprocessing issue, however If you can provide part of your data object, I am happy to help.

**Comment by TnakaNY** [comment]
Sorry for posting a issue like mine. Thank you for your kindness.

Here is very simple example file. 
In R, I loaded read.delm, then, pivot_wider() for wide-format, then tried to use stc_c to wrap, but failed.

[SNVdata_example.txt](https://github.com/jokergoo/ComplexHeatmap/files/5804746/SNVdata_example.txt)

**Comment by jokergoo** [comment]
In your file there is no value like `c("3'UTR", "Nonsense_Mutation")`. Can you save your R object as a .rds/.RData file and send it to me?

**Comment by TnakaNY** [comment]
I see. Here is rds data. As Github did not allow me to attach .rds file type directly, I zipped it.
[SNV_example.zip](https://github.com/jokergoo/ComplexHeatmap/files/5809588/SNV_example.zip)

**Comment by jokergoo** [comment]
I don't use tidyverse, but it can be easily done by:

```r
mat = apply(mat, 2, function(x) {
	sapply(x, paste, collapse = ",")
})
mat
     gene     CRC02P                    CRC06P             
[1,] "LIN28A" "3'UTR"                   ""                 
[2,] "PRKAA2" "3'UTR"                   ""                 
[3,] "FLG2"   "Missense_Mutation"       "Missense_Mutation"
[4,] "SHE"    "3'UTR,Nonsense_Mutation" ""                 
[5,] "KCNN3"  "Missense_Mutation"       "3'UTR"            
[6,] "FCER1A" "Missense_Mutation"       "" 
```

**Comment by TnakaNY** [comment]
Thank you very much for prompt reply and great help!!

**Comment by TnakaNY** [comment]
Hi,
Sorry for disturbing you , again, but I got a different result.

![image](https://user-images.githubusercontent.com/40367441/104487096-a6ff3600-559a-11eb-9471-2603a886c063.png)

**Comment by jokergoo** [comment]
```
t1 = readRDS(...)
t1 = apply(t1, 2, function(x) {
	sapply(x, paste, collapse = ",")
})
```

**Comment by TnakaNY** [comment]
Now, I see. I misstyped t1 for x in sapply.
Thank you!
