### ISSUE TITLE
Specifying "just" argument for anno_block labels

### ISSUE THREAD

**Issue by mp8** [jokergoo/ComplexHeatmap#664]
I could not find a way to justify the labels in the anno_block annotation (unlike anno_text which accepts just/locate arguments). Following is a minimal reproducible example and I was trying to align block labels to bottom, as of now labels are centered.

```
library(ComplexHeatmap)
mat = matrix(rnorm(100), 10)
top_lbls = c(rep("May",2), rep("June",3), rep("September",5))

Heatmap(mat, name = "mat1", cluster_rows = F, cluster_columns = F, show_column_names = F,show_row_names = F, column_title = NULL,
        column_split = top_lbls, 
        top_annotation = HeatmapAnnotation(
          test = anno_block(labels     = unique(top_lbls),
                            labels_rot = 90,
                            labels_gp  = gpar(just = c("right","bottom")), #this does not seem to change anything
                            height     = max_text_width(top_lbls)*1.5
                            )))

```
![image](https://user-images.githubusercontent.com/9068967/105063292-91ca5180-5a49-11eb-9e8b-3efc71763194.png)

And thank you so much for this great package. I never knew so much customization is possible. 

Regards,
Madhur

**Comment by jokergoo** [comment]
Yeah, I forgot to add those options. I will add them soon!

**Comment by jokergoo** [comment]
Hi, I have added two new argument `labels_offset` and `labels_just` in `anno_block()`. You can update it from GitHub.

```r
Heatmap(matrix(rnorm(100), 10), 
    top_annotation = HeatmapAnnotation(foo = anno_block(gp = gpar(fill = 2:4),
        labels = c("group1", "group2", "group3"), labels_gp = gpar(col = "white"),
        labels_rot = 90, labels_offset = unit(0, "npc"), labels_just = "left")),
    column_km = 3,
    left_annotation = rowAnnotation(foo = anno_block(gp = gpar(fill = 2:4),
        labels = c("group1", "group2", "group3"), labels_gp = gpar(col = "white"),
        labels_rot = 0, labels_offset = unit(1, "npc"), labels_just = "right")),
    row_km = 3)
```

![image](https://user-images.githubusercontent.com/449218/105473738-bae32000-5c9d-11eb-94ae-e8b1f7caa42f.png)

**Comment by mp8** [comment]
Thank you so much. This is awesome.
