### ISSUE TITLE
can `add_points` define multiple lines in `anno_lines()`?

### ISSUE THREAD

**Issue by blueskypie** [jokergoo/ComplexHeatmap#666]
if there are three lines in `anno_lines()`, can I set `add_points=c(T,T,F)`?

Thanks,

**Comment by jokergoo** [comment]
Good suggestion! I will add it later.

Now you can set `pch = c(1, 1, NA)`:

```r
m =matrix(rnorm(100), 10)

m2 = matrix(rnorm(10*3), ncol = 3)

Heatmap(m, top_annotation = HeatmapAnnotation(foo = anno_lines(m2, 
	add_points = TRUE, pch = c(1, 2, NA), height = unit(4, "cm"))))
```

![image](https://user-images.githubusercontent.com/449218/105471860-7f475680-5c9b-11eb-8e8b-f80c0b0af201.png)
