### ISSUE TITLE
create custom legend

### ISSUE THREAD

**Issue by blueskypie** [jokergoo/ComplexHeatmap#668]
I'd like to create a custom legend like this:
```
lgd2 = Legend(title='    cytokines', labels = gt_render(c(
"<span style='color:red'>**P**</span>rogression", 
"<span style='color:blue'>**D**</span>evelopment", 
"<span style='color:green'>**Sy**</span>mptom",
"<span style='color:tan2'>**Su**</span>rvival"
)))
```
The problem is that it does not align with other legends, see the attached figure.

Thanks you so much for the help!
![Capture](https://user-images.githubusercontent.com/16052330/105622331-b5412380-5dde-11eb-8ae4-4696c1dd9f38.JPG)

**Comment by jokergoo** [comment]
If you update the package from GitHub, you can do as follows:

```r
m = matrix(rnorm(100), 10)
ht = Heatmap(m)

library(gridtext)

gb = richtext_grob(
	paste("<span style='color:red;'>a</span>aaaaaa", 
		"<span style='color:blue;'>b</span>bbbbbb", 
		"<span style='color:green;'>c</span>ccccc",
		sep = "<br>"),
	halign = 0,
	x = 0,
	y = 0,
	hjust = 0, vjust = 0
)


lgd = Legend(title = "title", grob = gb)
draw(ht, heatmap_legend_list = lgd)
```

![image](https://user-images.githubusercontent.com/449218/105625269-222cdb80-5e28-11eb-9e92-16a38b9c9b82.png)

**Comment by blueskypie** [comment]
Thank you so much for the quick help! I noticed that the doc of `Legend()` has not been updated yet.

**Comment by jokergoo** [comment]
Thanks! Now it is updated. I also fixed a bug due to a typo.
