### ISSUE TITLE
legend position

### ISSUE THREAD

**Issue by blueskypie** [jokergoo/ComplexHeatmap#669]
is there a way to put the legend at any coordinate in the figure?

Thanks,

**Comment by jokergoo** [comment]
Legend are grob objects. You can construct a single legend by `Legend()` and arrange multiple legends by `packLegend()`. Later the legend can be put at any place in the plot by `draw(lgd, x, y, ...)`.

See https://jokergoo.github.io/ComplexHeatmap-reference/book/legends.html

Note if you do this way, the space for the legends is not calculated anymore, which means, you need to manually arrange the white space for legends.

```r
m = matrix(rnorm(100), 10)
Heatmap(m)

lgd = Legend(title = "foo", at = letters[1:4], legend_gp = gpar(fill = 1:4))

draw(lgd, x = unit(0.5, "npc"), y = unit(0.5, "npc"))
```

![image](https://user-images.githubusercontent.com/449218/105624586-2acee300-5e23-11eb-83e6-39eff1295e77.png)

**Comment by blueskypie** [comment]
How to get the automatically generated legend objects by `Heatmap()` and `HeatmapAnnotation()`? so they can be included in `packLegend()` along with those legend object specifically defined by `Legend()`.

Here is my code, where lgd1 and lgd2 are two objects defined by `Legend()`, named as _WK24.PC_ and _cytokines_.
![Capture](https://user-images.githubusercontent.com/16052330/105640844-54513400-5e4e-11eb-8bda-9a1a8106f33c.JPG)
_TD2TI_ and _Hgb.RESP_ are two auto-generated legends for row annotation. _log10 BL/mean_ is the auto-generated legend for the heatmap body.

 I'd like to move all the legends to a coordinate. But if I add `x = unit(0.5, "npc"), y = unit(0.5, "npc")`, it doesn't work for `draw,Heatmap-method`
```
cRe=Heatmap(...)
draw(cRe, annotation_legend_list = list(lgd1,lgd2), merge_legend = TRUE)
```

**Comment by jokergoo** [comment]
Then you need to manually construct all legends. It will be something like:

```r
lgd = packLegend(
    Legend(title = "TD2TI", at = c("FALSE", "TRUE"), legend_gp = gpar(fill = c("red", "greem"))),
   ... # same for other discrete legend,
    Legend(title = "log10\nBL/mean", col_fun = your_col_fun, ...),
   ... # other legends
)
```

and remember to turn off all the default legends:

```r
Heatmap(..., top_annotation = HeatmapAnnotation(..., show_legend = FALSE), show_heatmap_legend = FALSE)
draw(lgd, x, y, ...)
```
