### ISSUE TITLE
how does rowAnnotation() maps to the rows of heatmap body?

### ISSUE THREAD

**Issue by blueskypie** [jokergoo/ComplexHeatmap#670]
Here is my understanding using the following as an example. I'm wondering if it's correct?
```R
ra = rowAnnotation(PC = anno_lines(df1),...)
Heatmap(mat1, right_annotation = ra,...)
```

The vector or data.frame in `rowAnnotation()` should have `names` or `rownames` which contains the rownames of the heatmap body; that is `nrow(df1)==nrow(mat1)` and `all(rownames(df1) %in% rownames(mat1))`

If `Heatmap(cluster_row=T)`, the rows in `df1` are automatically mapped to the rows of the heatmap body.

However, if `Heatmap(cluster_row=F)`, the rows of `df1` need to be preset to the order of the rows of the mat1, i.e.
```R
df1=df1[rownames(mat1),]
ra = rowAnnotation(PC = anno_lines(df1),...)
Heatmap(mat1, right_annotation = ra, cluster_row=F, ...)
```

**Comment by jokergoo** [comment]
You just need to make sure row order of `df1` is the same as row order in `mat1`. When making heatmap, the order of `df1` is automatically adjusted according to the reordering of `mat1`.

**Comment by blueskypie** [comment]
I see! So `df1` doesn't even need to have `rownames`. I think this could potentially lead to bugs; if one forgets to set the rows of `mat1` and `df1` in the same order, s/he could be looking at a beautiful heatmap and is not aware the annotation is messed up.

I wonder if the following way might be safer:
1. the rows of `mat1` and `df1` don't have to be in the same order; but they both need to have row names.
2. In the `Heatmap`, check `nrow(mat1)==nrow(df1) & all(rownames(df1) %in% rownames(mat1))`
3. The mapping of rows of `df1` to the reordering of `mat1` is via row names, not indices.

**Comment by jokergoo** [comment]
I still think the order of annotations must have the same order as the matrix for following reasons:

1. not all analysis produce annotation table with rownames, even if it has row names, it is not 100% that they match to the main matrix.
2. I think it is important to make everything has consistent order in an analysis.

But your suggestion is helpful when e.g. `rownames(df)` is just a shuffle of `rownames(mat)`. In this case, I can first look at the row names and adjust both if the order is different, and I will print a warning message (I have this thought sometime before, but I think I forgot to implement it).

**Comment by jokergoo** [comment]
Ah, I think it is already implemented, but only for the heatmap-like annotation. I will check other annotation graphics.

**Comment by blueskypie** [comment]
One way to remind users to align the rows of `df1` and `mat1` before `Heatmap` is to add a new parameter `rowsAligned=NULL`; then force users to set `rowsAligned=T` if any of the four annotation is set. for example,  inside `Heatmap`
```r
if(!all(is.null(top_annotation,bottom_annotation,left_annotation,right_annotation))){
  stopifnot(rowsAligned)
}
```

**Comment by mortunco** [comment]
Hi guys, 
Forgive my ignorance but it was pretty painful to find this information. Is it possible we could annotation matrixes should be in the same order with input matrix for Heatmap function. 

Thank you for the valuable discussion.

**Comment by jokergoo** [comment]
If the annotation matrix is put on columns of the heatmap, the "rows of the annotation matrix" should be in the same order as the "columns of the input heatmap matrix". Here I emphasize "input" because the heatmap matrix is what you put in `Heatmap()` and no clustering has been applied on it yet. The ordering of the heatmap and its annotation are adjusted simultaneously.
