### ISSUE TITLE
can't draw picture

### ISSUE THREAD

**Issue by frusticolus** [jokergoo/ComplexHeatmap#671]
I installed it by:
`library(devtools)`
`install_github("jokergoo/ComplexHeatmap")`

I used the example in https://jokergoo.github.io/ComplexHeatmap-reference/book/oncoprint.html, some unexpected error has occurred. 

Running info: Rstudio Version 1.1.463  MacOS 

```
library(ComplexHeatmap)
mat = read.table(textConnection(
  "s1,s2,s3
  g1,snv;indel,snv,indel
  g2,,snv;indel,snv
  g3,snv,,indel;snv"), row.names = 1, header = TRUE, 
  sep = ",", stringsAsFactors = FALSE)
mat = as.matrix(mat)
col = c(snv = "red", indel = "blue")
oncoPrint(mat,
          alter_fun = list(
            snv = function(x, y, w, h) grid.rect(x, y, w*0.9, h*0.9, 
                                                 gp = gpar(fill = col["snv"], col = NA)),
            indel = function(x, y, w, h) grid.rect(x, y, w*0.9, h*0.4, 
                                                   gp = gpar(fill = col["indel"], col = NA))
          ), col = col)
```

![image](https://user-images.githubusercontent.com/25920847/105683086-33f8a680-5f2e-11eb-9004-fe659cd4afae.png)

Also, I can't get the picture. I excluded the install problem of the complexHeatmap package by getting a single heatmap successfully. I wonder it could be Rstudio problem, but I failed to get the picture in Rscript running way.

**Comment by jokergoo** [comment]
What is your R version? I have never seen this error. Can you print the output from `sessionInfo()`?

**Comment by frusticolus** [comment]
![image](https://user-images.githubusercontent.com/25920847/105955731-afcf2c00-60b1-11eb-8add-e51b006b3374.png)

This is `sessionInfo()` , avoid picture can't be loaded.

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1    yaml_2.2.1 
```

**Comment by jokergoo** [comment]
Have you loaded ComplexHeatmap? There is no complexHeatmap in your session info.

**Comment by frusticolus** [comment]
sorry for that , after i loaded the package, this shows :
![image](https://user-images.githubusercontent.com/25920847/105981005-8a9de600-60d0-11eb-9a01-a79456d81c7b.png)
![image](https://user-images.githubusercontent.com/25920847/105981042-92f62100-60d0-11eb-9eae-be4d47a6126b.png)

**Comment by jokergoo** [comment]
OK, I think maybe you need to use R 4.0. There are some changes from R 4.0 which are not compatible with R 3.*

**Comment by jokergoo** [comment]
Ah, I can also reproduce your error with R 3.5.1, but it works fine with R 4.0. I will look into this problem and try to fix it with the lower R versions.

**Comment by jokergoo** [comment]
Now I have fixed this problem. It is because under R 3.5.*, `grid.grabExpr()` won't go back to the current device. You can rerun your code without updating R to 4.0.

**Comment by frusticolus** [comment]
Thank you very much,  brilliant work!
