### ISSUE TITLE
ht_shiny() doesn't exist

### ISSUE THREAD

**Issue by themasterpg** [jokergoo/ComplexHeatmap#672]
Hello, I'm using this packet with shiny and I would make the heatmap interactive. I saw on a very good guide that there is a function called `ht_shiny()` that can make this, but I can't find inside the packet. Even using `ComplexHeatmap::ht_shiny()` doesn't work.
My version is the last one (2.7.5.1001). Has it been removed?

**Comment by jokergoo** [comment]
It is in another package **InteractiveComplexHeatmap**.

You can install it by:

```r
library(devtools)
install_github("jokergoo/InteractiveComplexHeatmap")
```

**Comment by themasterpg** [comment]
Thank you! I didn't find this package in the guide that I read.

**Comment by jokergoo** [comment]
Maybe that was from an old post. Recently I moved all the code into a separate package.
