### ISSUE TITLE
Persistent random colors in sidebar annotations

### ISSUE THREAD

**Issue by nirshahaf** [jokergoo/ComplexHeatmap#674]
Hi, 
Thanks for putting out this awesome package!

For some reason I keep getting the random colour mappings in my row annotations, e.g.:

		vip_colors = c("wheat1","wheat2","wheat4") 
		names (vip_colors) = sort (unique (vip_levels$VIP))
		HA = rowAnnotation (
			df=vip_levels,
			col=list (vip_levels=vip_colors),
			width=unit(4,"mm")
		)

        HA
        A HeatmapAnnotation object with 1 annotation
        name: heatmap_annotation_47
        position: row
        items: 2305
        width: 5mm
        height: 1npc
        this object is subsetable
        18.6487666666667mm extension on the bottom
        name annotation_type color_mapping width
        VIP_level discrete vector random 5mm

Any clue?

**Comment by jokergoo** [comment]
Change to:

```r
HA = rowAnnotation (
		df=vip_levels,
		col=list (VIP=vip_colors),
		width=unit(4,"mm")
	)
```

**Comment by nirshahaf** [comment]
It works nicely, thanks!

Maybe the function documentation can be a bit more elaborate in this point (i.e. heatmap annotation colors)?
