### ISSUE TITLE
How can I label heatmap with significance stars stored in another matrix

### ISSUE THREAD

**Issue by jiajinlongkang** [jokergoo/ComplexHeatmap#675]
I am trying to generate a heatmap like this:
![image](https://user-images.githubusercontent.com/60410820/106180475-5545d680-616a-11eb-9585-f5e05af40929.png)
Basically I now have a matrix1 that contains the values used to construct the heatmap. I also have a matrix2 that contains the significance label for each cell of matrix1 (i.e. those stars). My question is how can I add these significance labels from matrix2 onto the heatmap generated from matrix1. Can you provide sample codes?

Thank you for your help!

**Comment by jokergoo** [comment]
Use `cell_fun`:

```r
Heatmap(mat1, cell_fun = function(j, i, x, y, w, h, fill) {
    if(mat2[i, j] < 0.001) {
        grid.text("***", x, y)
    } else if(mat2[i, j] < 0.01) {
        grid.text("**", x, y)
    }
    ....
})
```

**Comment by jiajinlongkang** [comment]
Thank you for your help! A follow up on this problem. I still have the two matrices as described above. But now I want to draw a heatmap with colors representing values in matrix1 and circle size representing significance in matrix2. Can you provide sample codes? Really appreciate your help!

The plot should looks like this:
![image](https://user-images.githubusercontent.com/60410820/108086012-edd1c700-7043-11eb-9c15-e2e8edcbf2af.png)

**Comment by jokergoo** [comment]
You can check the plot in this section:

https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#cell-fun

**Comment by crazyhottommy** [comment]
Hi Zuguang, I tried the code for adding * to the grid, and it works, but the * is on the top of the grid not in the center of each grid. I tried using text for the values, and they are in the center. 
<img width="572" alt="Screen Shot 2021-04-15 at 11 56 35 AM" src="https://user-images.githubusercontent.com/4106146/114900236-ae282100-9de1-11eb-93de-b26d49f2cd11.png">
<img width="572" alt="Screen Shot 2021-04-15 at 11 56 35 AM" src="https://user-images.githubusercontent.com/4106146/114900256-b2ecd500-9de1-11eb-88af-53cd454bb94e.png">

**Comment by jokergoo** [comment]
Hi @crazyhottommy , I think the symbol "*" is not vertically centered. You might need to try other similar symbols. See https://stackoverflow.com/questions/34899402/how-to-vertically-centre-align-star-in-label-or-button.

If you cannot see these Unicode symbols on your computer (like mine, don't what happened with my new computer :)), you need to manually adjust the vertical position of "*":

```r
m = matrix(rnorm(400), 20)
Heatmap(m, layer_fun = function(j, i, x, y, w, h, f) {
	gb = textGrob("*")
	gb_w = convertWidth(grobWidth(gb), "mm")
	gb_h = convertHeight(grobHeight(gb), "mm")
	grid.rect(x, y, width = gb_w, height = gb_h)
	grid.text("*", x, y - gb_h*0.5 + gb_w*0.4)
})
```

In this example, an offset of `- gb_h*0.5 + gb_w*0.4` should be enough. 

![image](https://user-images.githubusercontent.com/449218/114997854-9794cf00-9ea0-11eb-8a02-3af904683eb0.png)

**Comment by crazyhottommy** [comment]
Great! thanks a lot for your help!
