### ISSUE TITLE
Save complexheatmap 

### ISSUE THREAD

**Issue by giorgiolivi** [jokergoo/ComplexHeatmap#676]
Hi , 
I would like export the complexheatmap in text,
or csv for further analysis.
Which is the best way?
Thanks a lot in advance!
G
![Screen Shot 2021-01-30 at 14 50 00](https://user-images.githubusercontent.com/77282827/106359418-9674ec80-630a-11eb-8245-5f9ad5acd5ef.png)

**Comment by jokergoo** [comment]
I think what you want is to save a reordered table where the order is the same as in the heatmap, right?

You can get the new orders by:

```
ht = Heatmap(mat, ...)
ht = draw(ht) ## this draws the heatmap
row_order = row_order(ht)
column_order = column_order(ht)

# since you applied splitting on rows, `row_order` is a list, thus you need to unlist it
row_order = unlist(row_order)

# reorder `mat`
mat2 = mat[row_order, column_order]
write.csv(mat2, ...)
```

**Comment by giorgiolivi** [comment]
ABSOLUTELY THANKS A LOT,
IT'S WORKS!
G
