### ISSUE TITLE
Annotation labels do not accept expression for super and subscript

### ISSUE THREAD

**Issue by marshelma** [jokergoo/ComplexHeatmap#678]
Please provide example datasets and the code you use. It will help me to understand your problem and help you!

```r
rptr21ht.topha = HeatmapAnnotation(
  Cell_line =rptr21clone_sum$Cell.line,
  annotation_legend_param = list(Cell_line=list(title="Cell line",labels=c("Parental",expression("IDH1^R132H"))))
)

Heatmap(rptr2clone_fraction_matrix,name= "uniqe read",
            cluster_columns = F,
            cluster_rows = F,
            show_row_names = T,
            show_column_names = F,
            row_title = "unique clone size",
            column_title = "post-treatment tumor samples",
            top_annotation = rptr21ht.topha,
            width=4,
            column_split = c(rep("A",3),rep("B",3),rep("C",3),rep("D",3),rep("E",3),rep("F",3),rep("G",3),rep("H",3))
            #col=pal_material("light-green")(10)[c(1,10)]
)
```

return

Error in aperm.default(X, c(s.call, s.ans)) : 
  unimplemented type 'expression' in 'aperm'

**Comment by slagtermaarten** [comment]
I'm having the same problem: I used to successfully use a vector of expressions as labels in calls to `Legend` but now, with version ComplexHeatmap 2.5.3, this gets me this error message - the code works fine without expressions:

```
Error in aperm.default(X, c(s.call, s.ans)): unimplemented type 'expression' in 'aperm'
```

**Comment by jokergoo** [comment]
@marshelma @slagtermaarten , I guess both of you were making a discrete legend?

**Comment by jokergoo** [comment]
Now it also works with `expression()`.  Please have a try.

Note @marshelma , you should specify as `labels = expression(Parental, IDH1^R132H)`. 

```r
...
	at = 1:3,
	labels = expression(a^2, b^2, c^2),
	legend_gp = gpar(fill = 2:4),
...
```
![image](https://user-images.githubusercontent.com/449218/107372997-55d55a00-6ae6-11eb-984f-3dd397821818.png)

**Comment by marshelma** [comment]
> @marshelma @slagtermaarten , I guess both of you were making a discrete legend?
> 
> One solution is to use `gt_render()` to render the text with **gridtext** package. I think it might be more flexible than using `expression()`.
> 
> ```
> ...
> labels = gt_render(c("Parental", "IDH1^R132H")),
> ...
> ```
> 
> ![image](https://user-images.githubusercontent.com/449218/107368586-05a7c900-6ae1-11eb-9a1f-5f852be4d85d.png)
> 
> I will also check why `expression()` does not work for discrete legends.

Yes. It is for discrete legends.

**Comment by marshelma** [comment]
> Now it also works with `expression()`. Please have a try.
> 
> Note @marshelma , you should specify as `labels = expression(Parental, IDH1^R132H)`.
> 
> ```r
> ...
> 	at = 1:3,
> 	labels = expression(a^2, b^2, c^2),
> 	legend_gp = gpar(fill = 2:4),
> ...
> ```
> 
> ![image](https://user-images.githubusercontent.com/449218/107372997-55d55a00-6ae6-11eb-984f-3dd397821818.png)

I still have the same error coming out after change the code to 'labels = expression(Parental, IDH1^R132H)'. Or should I update the package first then try?

**Comment by marshelma** [comment]
> gt_render(c("Parental", "IDH1^R132H"))

The gt_render() works. Thank you so much!

Best

**Comment by jokergoo** [comment]
Yes, you need to update the package from GitHub to use `expression()`.

**Comment by jokergoo** [comment]
Now it is fixed:

```r
> m = matrix(rnorm(100), 10)
> ha = HeatmapAnnotation(x = 1:10, annotation_label = expression(a^2))
> Heatmap(m, top_annotation=ha)
```

![image](https://user-images.githubusercontent.com/449218/140798440-2138b398-1f52-4f62-a94a-085ba321e561.png)

**Comment by pedro-aza** [comment]
Can you please give an example of gt_render with subscript? 
gt_render(c("Parental", "IDH1[R132H]")) doesn`t work

**Comment by qinghezeng** [comment]
Just for info, `gt_render(c("Parental", "IDH1<sup>R132H</sup>"))` is working for me instead of `gt_render(c("Parental", "IDH1^R132H"))`
