### ISSUE TITLE
Problem with UpsetPlot object: Error in if (set_on_rows) { : argument is of length zero

### ISSUE THREAD

**Issue by hartmannmark** [jokergoo/ComplexHeatmap#684]
I've got an upsetplot object called `upset` that is flawlessly working for my collaborator. But when I load it on my local machine I get an error message:

`> upset
A combination matrix with 5 sets and 30 combinations.
  ranges of combination set size: c(1, 68).
  mode for the combination size: .
Error in if (set_on_rows) { : argument is of length zero`

The same is true when I try to plot it:

`> UpSet(upset)
Error in if (set_on_rows) { : argument is of length zero`

Or if I try to subset it:

`> extract_comb(upset,'11111')
Error in if (set_on_rows) { : argument is of length zero`

My collaborator works with R version 3.5.1 and ComplexHeatmap version 2.5.4.
I thought this might be the reason since I work in R version 3.6.3 and ComplexHeatmap version 2.2.2. Strangely I am not able to update my ComplexHeatmap version whatever I try. So obviously I have two problems here...

Any ideas? I appreciate any comment on this!

**Comment by jokergoo** [comment]
The two versions you mentioned are old. Maybe that was a bug in these versions. Have you tried with the newest version? You can always install it from Github:

```r
library(devtools)
install_github("jokergoo/ComplexHeatmap")
```

**Comment by hartmannmark** [comment]
Thanks for the quick reply. I have tried to install as mentioned but unfortunately it gives another error:

> library(devtools)
> install_github("jokergoo/ComplexHeatmap")
Downloading GitHub repo jokergoo/ComplexHeatmap@HEAD
✓  checking for file ‘/private/var/folders/_5/kmm010t94fjc4_s81xszq4k80000gp/T/RtmpU6bIOi/remotes390a776216c9/jokergoo-ComplexHeatmap-c7865b7/DESCRIPTION’ ...
─  preparing ‘ComplexHeatmap’: (394ms)
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts (430ms)
─  checking for empty or unneeded directories
─  building ‘ComplexHeatmap_2.7.6.1009.tar.gz’
   
* installing *source* package ‘ComplexHeatmap’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: .onLoad failed in loadNamespace() for 'Cairo', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Cairo/libs/Cairo.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Cairo/libs/Cairo.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Cairo/libs/Cairo.so
  Reason: image not found
Execution halted
ERROR: lazy loading failed for package ‘ComplexHeatmap’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ComplexHeatmap’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ComplexHeatmap’
Error: Failed to install 'ComplexHeatmap' from GitHub:
  (converted from warning) installation of package '/var/folders/_5/kmm010t94fjc4_s81xszq4k80000gp/T//RtmpU6bIOi/file390a48c6235a/ComplexHeatmap_2.7.6.1009.tar.gz' had non-zero exit status
>

**Comment by jokergoo** [comment]
That was the problem of Cairo package.

If I remember correctly, you need to install XQuartz.

see https://support.bioconductor.org/p/p133999/#p134005 or https://izziswift.com/include-cairo-r-on-a-mac/

**Comment by hartmannmark** [comment]
This worked! Thanks!

**Comment by hartmannmark** [comment]
Unfortunately I've been too fast.

The installation of the newest version did indeed work.

However, the main problem remains. Still I cannot use the object shared with me:

`> library(ComplexHeatmap)
> #Load object
> upset <- readRDS("UpsetPlot.rds")
> #Plot
> UpSet(upset)
Error in if (set_on_rows) { : argument is of length zero
> #Extract subsets
extract_comb(upset,'11111')
Error in if (set_on_rows) { : argument is of length zero`

**Comment by jokergoo** [comment]
I think the file `UpsetPlot.rds` was generated with the old version. You should also generate it with the new version.
