### ISSUE TITLE
Unable to load the package

### ISSUE THREAD

**Issue by kchen96** [jokergoo/ComplexHeatmap#685]
I installed the package from Bioconductor but wasn't able to load the package. I am using R version 4.0.3. I did: 

`BiocManager::install("ComplexHeatmap")
library(ComplexHeatmap)
`

And I got this error message: 

`Error: package or namespace load failed for ‘ComplexHeatmap’:
 .onLoad failed in loadNamespace() for 'Cairo', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so, 6): Library not loaded: /opt/X11/lib/libXrender.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so
  Reason: image not found`

**Comment by bersbersbers** [comment]
Your installation of R seems to be missing the cairo library. This is listed as one of the imports at https://www.bioconductor.org/packages/release/bioc/html/ComplexHeatmap.html. You may need to provide more information on your environment, such as did you compile R yourself, or did you install it as a package?

**Comment by jokergoo** [comment]
Maybe this link help:

https://support.bioconductor.org/p/p133999/#p134005

**Comment by kchen96** [comment]
Thank you, Zuguang! I will give a try later.

---------------------------
Kirsten Chen

PhD Candidate, Biomedical Sciences/Systems Biology
University of California, San Francisco
kirstenxchen@gmail.com<mailto:kirstenxchen@gmail.com> | 919-536-8885

**Comment by EmilyB17** [comment]
FYI, I am getting the same error although I have used the ComplexHeatmap package before... Is this related to upgrading to R 4.0?

**Comment by jokergoo** [comment]
I think it is related to the update of Cairo package or libcairo library.

**Comment by EmilyB17** [comment]
Well my current issue is that I can't load the ComplexHeatmap package... getting the same error message as the first post above: 
> require(Cairo)
Loading required package: Cairo
Error: package or namespace load failed for ‘Cairo’:
 .onLoad failed in loadNamespace() for 'Cairo', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so, 6): Library not loaded: /opt/X11/lib/libXrender.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so
  Reason: image not found
Warning message:
package ‘Cairo’ was built under R version 4.0.2

**Comment by EmilyB17** [comment]
Whoops - this one

> require(ComplexHeatmap)
Loading required package: ComplexHeatmap
Error: package or namespace load failed for ‘ComplexHeatmap’:
 .onLoad failed in loadNamespace() for 'Cairo', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so, 6): Library not loaded: /opt/X11/lib/libXrender.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Cairo/libs/Cairo.so
  Reason: image not found
Warning message:
package ‘ComplexHeatmap’ was built under R version 4.0.3

**Comment by jokergoo** [comment]
Then I think you just simply install a new version of XQuartz and restart your R session.

https://izziswift.com/include-cairo-r-on-a-mac/

**Comment by EmilyB17** [comment]
Okay, that worked! Up and running. Thanks for the fast reply! :)

**Comment by myshu2017-03-14** [comment]
Hi,
I re-install the packages using below code:
>library(devtools)
install_github("jokergoo/ComplexHeatmap")

But when I set `fontfamily="serif"`, only the row and column fonts have changed，not the rest.
![image](https://user-images.githubusercontent.com/26398036/167778782-b6eb863a-64d7-4312-8094-16e43d5b1e2e.png)

The test code:
```
library("ComplexHeatmap")
test = matrix(rnorm(200), 20, 10)
test[1:10, seq(1, 10, 2)] = test[1:10, seq(1, 10, 2)] + 3
test[11:20, seq(2, 10, 2)] = test[11:20, seq(2, 10, 2)] + 2
test[15:20, seq(2, 10, 2)] = test[15:20, seq(2, 10, 2)] + 4
colnames(test) = paste("Test", 1:10, sep = "")
rownames(test) = paste("Gene", 1:20, sep = "")

annotation_col = data.frame(
  CellType = factor(rep(c("CT1", "CT2"), 5)),
  Time = 1:5
)
rownames(annotation_col) = paste("Test", 1:10, sep = "")

annotation_row = data.frame(
  GeneClass = factor(rep(c("Path1", "Path2", "Path3"), c(10, 4, 6)))
)
rownames(annotation_row) = paste("Gene", 1:20, sep = "")
# Specify colors
ann_colors = list(
  Time = c("white", "firebrick"),
  CellType = c(CT1 = "#1B9E77", CT2 = "#D95F02"),
  GeneClass = c(Path1 = "#7570B3", Path2 = "#E7298A", Path3 = "#66A61E")
)
pheatmap(test,
        annotation_col = annotation_col, # 列分组
        annotation_row = annotation_row,  # 行分组
        annotation_colors = ann_colors,  # 指定样本分组颜色， list格式
        color = colorRampPalette(c("#0000FF", "#FFFCC8", "#FF0000"))(100), # 热图色卡颜色
        border_color = NA,  # cell有无边框，或指定颜色
        cellwidth =NA, cellheight = NA, # cell大小
        cluster_rows = TRUE,  # 显示行聚类
        cluster_cols = TRUE,  # 显示列聚类
        legend = TRUE, #是否显示色标图例
        main = "jsd diversity distance", # 图标题
        fontsize = 10, #图字体大小
        fontsize_row = 8,  # 行字体大小
        fontsize_col = 10,  # 列字体大小
        display_numbers = FALSE, number_format = "%.1f", number_color="Black", fontsize_number=4,  # cell中是否显示数值；格式设置
        # display_numbers = matrix(ifelse(test > 5, "*", ""), nrow(test))
        angle_col = "90",  # options (0, 45, 90, 270 and 315)  # 调整列文字角度
        # show_rownames = TRUE, show_colnames = TRUE
        annotation_legend = TRUE,
        fontfamily = "serif"
)
```
