### ISSUE TITLE
Dendrogram reordering not working on R3.5

### ISSUE THREAD

**Issue by bersbersbers** [jokergoo/ComplexHeatmap#686]
Inspired by the example at
https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#reorder-dendrograms

```
m2 = matrix(1:100, nr = 10, byrow = TRUE)
ComplexHeatmap::Heatmap(m2, name = "mat", row_dend_reorder = TRUE, column_title = "apply reordering")
```

gives me this on R3.5.0:

![image](https://user-images.githubusercontent.com/12128514/107752539-2eb59d00-6d1f-11eb-8e0f-7475e9fe04ff.png)

It works fine on R4.0.3 and R4.0.0:

![image](https://user-images.githubusercontent.com/12128514/107752622-4bea6b80-6d1f-11eb-870c-bde8702e6ecb.png)

**Comment by jokergoo** [comment]
What are the two ComplexHeatmap versions? Maybe they are from different versions?

The legend looks also different.

**Comment by bersbersbers** [comment]
Oh, thank you!

- I had noticed the different legends, too, but I had attributed that to different defaults in R3.5 and R4 (that's probably nonsense, but that kind of things happened in MATLAB). 

- Also, my first impulse was to say that the versions of ComplexHeatmap must be identical because I had simply issued `BiocManager::install("ComplexHeatmap")` in both R versions. But it seems it was installing ComplexHeatmap 2.6.2 in R4.0.3 and ComplexHeatmap 1.20.0 in R3.5, according to `packageVersion("ComplexHeatmap")` - which makes sense as the Bioconductor versions are different
```
Bioconductor version 3.8 (BiocManager 1.30.10), R 3.5.0 (2018-04-23)
Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.3 (2020-10-10)
```
and Bioconductor 3.8 contains only ComplexHeatmap 1.20.0:
https://www.bioconductor.org/packages/3.8/bioc/html/ComplexHeatmap.html

Also, Bioconductor 3.9 already requires R>=3.6.0.

What I had misinterpreted was that Bioconductor lists ComplexHeatmap as requiring R >= 3.1.2. However, there is no way to install the current version through Bioconductor. `biocLite("ComplexHeatmap")` uses Bioconductor 3.7 with ComplexHeatmap 1.18.1.

For now, I used `devtools::install_github("jokergoo/ComplexHeatmap")` and that solved the problem, but I'm sure I will update to R4.0.3 soon. (`devtools::install_github("https://github.com/jokergoo/ComplexHeatmap/tree/RELEASE_3_12")` did not work due to depency conflicts with the installed Bioconductor 3.8.)

**Comment by jokergoo** [comment]
Yes, I think this indeed confuses people. `BiocManager::install("ComplexHeatmap")` only installs the package versions that correspond to the "current bioconductor version".

Now ComplexHeatmaps depends on two bioconductor core packages, S4vectors and IRanges. These two packages have more strict requirement on the R version (the current one is R >= 4.0), which means, you must work on R 4.* to use all other packages.
