### ISSUE TITLE
Another issue installing in R 4.0, cairo.h?

### ISSUE THREAD

**Issue by mr-september** [jokergoo/ComplexHeatmap#687]
I have seen [this issue](https://github.com/jokergoo/ComplexHeatmap/issues/685), which is specific to Macs (I am on Linux - Ubuntu 20.04), and also [this issue](https://github.com/jokergoo/ComplexHeatmap/issues/514), only to end up with
`Warning in install.packages :
  package ‘GetOptLong’ is not available (for R version 4.0.2)`.

My original error:
```
configure: error: Cannot find cairo.h! Please install cairo (http://www.cairographics.org/) and/or set CAIRO_CFLAGS/LIBS correspondingly.
ERROR: configuration failed for package ‘Cairo’
* removing ‘/home/name/R/x86_64-pc-linux-gnu-library/4.0/Cairo’
```

Update: Turns out `GetOptLong` has been renamed to `GetoptLong`, this is solved/installed, but still getting same error when trying to install `ComplexHeatmap` or `Cairo`.

**Comment by jokergoo** [comment]
Did you manually type `install.packages("GetOptLong")` (with the capitalized O) or other ways? I think I never used `GetOptLong`.

How about re-install cairo C library on your system? I think you can see enough information from http://www.cairographics.org/.
