### ISSUE TITLE
oncoPrint with only one mutation type

### ISSUE THREAD

**Issue by pigraul** [jokergoo/ComplexHeatmap#689]
Hi,
My input data has only one type. When I use oncoPrint, it gives the error:

All mutation types: Missense_Mutation
Error in if (v["Missense_Mutation"]) grid.rect(x, y - h * 0.5 + 0.99:n/n *  : 
  missing value where TRUE/FALSE needed
Calls: <Anonymous> ... draw_heatmap_body -> .local -> cell_fun -> af -> alter_fun
Execution halted

I try the script with multi mutation types data, it works well.  How can I draw the only one type data with oncoPrint?

Best,
raulee

**Comment by jokergoo** [comment]
It is because the names in the vector `v` were lost when the length of `v` is one.

Now it is fixed. Please update it from GitHub.

Thanks!
