### ISSUE TITLE
mystery color mapping for viridis color with 2 breaks

### ISSUE THREAD

**Issue by ccshao** [jokergoo/ComplexHeatmap#690]
The `col` gives interesting results with viridis color if only two breaks provided
The example codes

```
set.seed(123)
nr1 = 4; nr2 = 8; nr3 = 6; nr = nr1 + nr2 + nr3
nc1 = 6; nc2 = 8; nc3 = 10; nc = nc1 + nc2 + nc3
mat = cbind(rbind(matrix(rnorm(nr1*nc1, mean = 1,   sd = 0.5), nr = nr1),
          matrix(rnorm(nr2*nc1, mean = 0,   sd = 0.5), nr = nr2),
          matrix(rnorm(nr3*nc1, mean = 0,   sd = 0.5), nr = nr3)),
    rbind(matrix(rnorm(nr1*nc2, mean = 0,   sd = 0.5), nr = nr1),
          matrix(rnorm(nr2*nc2, mean = 1,   sd = 0.5), nr = nr2),
          matrix(rnorm(nr3*nc2, mean = 0,   sd = 0.5), nr = nr3)),
    rbind(matrix(rnorm(nr1*nc3, mean = 0.5, sd = 0.5), nr = nr1),
          matrix(rnorm(nr2*nc3, mean = 0.5, sd = 0.5), nr = nr2),
          matrix(rnorm(nr3*nc3, mean = 1,   sd = 0.5), nr = nr3))
   )
mat = mat[sample(nr, nr), sample(nc, nc)] # random shuffle rows and columns
rownames(mat) = paste0("row", seq_len(nr))
colnames(mat) = paste0("column", seq_len(nc))

# good
col_fun = colorRamp2(c(-1, 0, 1), viridis(3))
Heatmap(mat, col = col_fun)

# strange color used here
col_fun = colorRamp2(c(-1, 1), viridis(2))
Heatmap(mat, col = col_fun)

#- now blue and red are used.
col_fun = colorRamp2(c(-1, 1), c("blue", "red"))
Heatmap(mat, col = col_fun)
```

The heatmap with strange color attached, it should be something like yellow and darkblue.

![Screenshot_2021-02-19_12-23-10](https://user-images.githubusercontent.com/4980631/108498627-6dae9a00-72ad-11eb-94c1-39f42b1bece5.png)

**Comment by jokergoo** [comment]
It is because the colors are interpolated differently.

In the left which is based on three colors, values are interpolated in two intervals which are [yellow, blue] and [blue, purple], while in the right which is based on two colors, values are all interpolated in one interval [yellow, purple].

If you look closely, in the two legends, values at 1 and -1 have the same colors.

![image](https://user-images.githubusercontent.com/449218/108536007-399e9d80-72dc-11eb-8ac1-a598ec64a6d9.png)

**Comment by ccshao** [comment]
Cool!

**Comment by sparsepix** [comment]
Is it somehow possible to use the full viridis scale for ComplexHeatmap? When I put `viridis` in the function call as `col = viridis ` I get an error to provide breaks. I can work around by specifying `col_fun = circlize::colorRamp2(c(-1, 0, 2), viridis(3))` according to how the color function is specified in the vignette, but it gives me not the exact same mapping as the full scale would.
