### ISSUE TITLE
Vjust / Centering for cell label text?

### ISSUE THREAD

**Issue by vkartha** [jokergoo/ComplexHeatmap#691]
Hi, thank you so much for adding some neat functionalities to this package. Is there any way to shift text within a cell, when adding within cell heatmap labels? When using the cell_fun() function example from the package tutorial to add text labels within the cells, I wanted to add a simple asterisk for a subset of cells, but because it is by default used as a superscript, they end up getting vertically misaligned (see below).

![image](https://user-images.githubusercontent.com/9615730/108563578-a65f6b00-72cf-11eb-8b3f-0e68ade2eaad.png)

I am wondering if you can specify in the graphical params to center the test somehow?

Thanks in advance!

**Comment by jokergoo** [comment]
Can you give me a runnable example?

I guess you can directly use **gridtext** package to draw superscript:

```r
m = matrix(rnorm(100), 10)

library(grid)
library(gridtext)
library(glue)
Heatmap(m, cell_fun = function(j, i, x, y, w, h, fill) {
	gb = richtext_grob(glue("<i>m</i><sup>{i},{j}</sup>"), x = x, y = y)
	grid.draw(gb)
})
```

![image](https://user-images.githubusercontent.com/449218/108589832-9e9bd700-7360-11eb-8778-b6de12adc103.png)
