### ISSUE TITLE
ggplot annotation legend

### ISSUE THREAD

**Issue by RAEjarq** [jokergoo/ComplexHeatmap#692]
Hello,

I have produced a heatmap with a related dotplot showing gene expression
![Rplot](https://user-images.githubusercontent.com/74206443/108729091-78299780-752a-11eb-9ae6-cc6897bd7a1d.png)
Could you please help me adding  the dotplot legend?
![Rplot01](https://user-images.githubusercontent.com/74206443/108729748-21708d80-752b-11eb-9509-c47f403038a3.png)

The code I am using is the following:
g <- ggplot + 
        theme_void() +
        theme(legend.position = "none")

ha <-HeatmapAnnotation(ggplot = anno_empty(height = unit(1, "cm")))

interaction %>% 
        t() %>% 
        Heatmap(., 
                col=RColorBrewer::brewer.pal(name = "Blues", n = 9),
                name = "interaction",
                cluster_rows = FALSE,
                row_names_side = "left",
                cluster_columns = F,
                column_names_side = c("top"),
                column_title_side = c("top"),
                border="black",
                bottom_annotation = ha)

decorate_annotation("ggplot", {
        vp = current.viewport()$name
        print(g, vp = vp)
        
})

Thanks a lot for your help!

**Comment by jokergoo** [comment]
Maybe you can check this link: https://jokergoo.github.io/ComplexHeatmap-reference/book/legends.html#add-customized-legends
