### ISSUE TITLE
cluster_column_slices to TRUE will not work if  cluster_columns is FALSE

### ISSUE THREAD

**Issue by crazyhottommy** [jokergoo/ComplexHeatmap#694]
Hi Zuguang,
I want to only cluster the column slices but not the columns within each slice
I tried:
```r
set.seed(123)
nr1 = 4; nr2 = 8; nr3 = 6; nr = nr1 + nr2 + nr3
nc1 = 6; nc2 = 8; nc3 = 10; nc = nc1 + nc2 + nc3
mat = cbind(rbind(matrix(rnorm(nr1*nc1, mean = 1,   sd = 0.5), nr = nr1),
          matrix(rnorm(nr2*nc1, mean = 0,   sd = 0.5), nr = nr2),
          matrix(rnorm(nr3*nc1, mean = 0,   sd = 0.5), nr = nr3)),
    rbind(matrix(rnorm(nr1*nc2, mean = 0,   sd = 0.5), nr = nr1),
          matrix(rnorm(nr2*nc2, mean = 1,   sd = 0.5), nr = nr2),
          matrix(rnorm(nr3*nc2, mean = 0,   sd = 0.5), nr = nr3)),
    rbind(matrix(rnorm(nr1*nc3, mean = 0.5, sd = 0.5), nr = nr1),
          matrix(rnorm(nr2*nc3, mean = 0.5, sd = 0.5), nr = nr2),
          matrix(rnorm(nr3*nc3, mean = 1,   sd = 0.5), nr = nr3))
   )
mat = mat[sample(nr, nr), sample(nc, nc)] # random shuffle rows and columns
rownames(mat) = paste0("row", seq_len(nr))
colnames(mat) = paste0("column", seq_len(nc))


Heatmap(mat, name = "mat", row_split = rep(c("A", "B"), 9), column_split = rep(c("C", "D", "E", "F"), 6), cluster_columns = FALSE, cluster_column_slices = TRUE)
```

ComplexHeatmap       * 2.6.2    2020-11-12 [1] Bioconductor

But it did not cluster the slices either.

**Comment by jokergoo** [comment]
I guess this is what you want:

```r
column_split = rep(c("C", "D", "E", "F"), 6)
dend = cluster_within_group(mat, column_split)

Heatmap(mat, name = "mat", row_split = rep(c("A", "B"), 9), 
	cluster_columns = dend, column_split = 4, cluster_column_slices = TRUE)
```

![image](https://user-images.githubusercontent.com/449218/109139912-544d9800-775c-11eb-9259-c8bcdcb56821.png)

**Comment by crazyhottommy** [comment]
this works! but the resulting column slice label becomes the number. how do I get the original C,D,E,F labels?

**Comment by crazyhottommy** [comment]
Hi Zuguang,
I've read the tutorial in bookdown again, and I did not find a straightforward way to do it. Can you advise? Always appreciate your help!

**Comment by jokergoo** [comment]
OK, I would say, this is a rare use case... But no problem, it sounds reasonable and for your case, it is useful, I will implement it soon. There won't be too much work. Basically it is very similar as `cluster_within_group()`.

**Comment by jokergoo** [comment]
Hi Tommy,

1. the for slice labels, you can always modify with `column_title` argument:

```r
Heatmap(..., column_split = 4, column_title = c("C", "D", "E", "F"))
```

2. I have added a new function `cluster_between_groups()` which only clusters between groups, while inside each group, the order is unchanged. In the following example, notice the column names which are the original orders.

```r
m = matrix(rnorm(120), nc = 12)
colnames(m) = 1:12
fa = rep(c("a", "b", "c"), times = c(2, 4, 6))
dend1 = cluster_between_groups(m, fa)
dend2 = cluster_within_group(m, fa)
Heatmap(m, cluster_columns = dend1, column_split = 3) + 
Heatmap(m, cluster_columns = dend2, column_split = 3)
```

![image](https://user-images.githubusercontent.com/449218/109945249-59b85e80-7cd7-11eb-897d-20c650a0b9c4.png)

Please update from GitHub.

**Comment by crazyhottommy** [comment]
This is fantastic! 
Re "column_title", I know I can change it manually. But after clustering, I do not know which labels should be added especially when I have more slices, unlike this dummy example.

**Comment by jokergoo** [comment]
OK, I see. Now the class labels are kept if the dendrograms are generated by `cluster_between_groups()` or `cluster_within_group()`. Same code as before:

![image](https://user-images.githubusercontent.com/449218/110015437-251ec400-7d24-11eb-80bc-10561d1f883a.png)

**Comment by crazyhottommy** [comment]
Great! closing now.
