### ISSUE TITLE
Should complexHeatmap report waring when duplicated row names appears in the matrix

### ISSUE THREAD

**Issue by shangguandong1996** [jokergoo/ComplexHeatmap#695]
Hi, Dr Gu

I am wondering whether complexHeatmap should report warning when duplicated row names appears in the matrix. I find in the manul, there is a sentence
> The second advantage is row_labels or column_labels allows duplicated labels, **while duplicated row names or column names are not allowed in the matrix.**

But actually, I can plot heatmap successfully even duplicated row names appears in the matrix

```{r}
library(ComplexHeatmap)

# This is the test data from your manual
set.seed(123)
nr1 = 4; nr2 = 8; nr3 = 6; nr = nr1 + nr2 + nr3
nc1 = 6; nc2 = 8; nc3 = 10; nc = nc1 + nc2 + nc3
mat = cbind(rbind(matrix(rnorm(nr1*nc1, mean = 1,   sd = 0.5), nr = nr1),
                  matrix(rnorm(nr2*nc1, mean = 0,   sd = 0.5), nr = nr2),
                  matrix(rnorm(nr3*nc1, mean = 0,   sd = 0.5), nr = nr3)),
            rbind(matrix(rnorm(nr1*nc2, mean = 0,   sd = 0.5), nr = nr1),
                  matrix(rnorm(nr2*nc2, mean = 1,   sd = 0.5), nr = nr2),
                  matrix(rnorm(nr3*nc2, mean = 0,   sd = 0.5), nr = nr3)),
            rbind(matrix(rnorm(nr1*nc3, mean = 0.5, sd = 0.5), nr = nr1),
                  matrix(rnorm(nr2*nc3, mean = 0.5, sd = 0.5), nr = nr2),
                  matrix(rnorm(nr3*nc3, mean = 1,   sd = 0.5), nr = nr3))
)
mat = mat[sample(nr, nr), sample(nc, nc)] # random shuffle rows and columns
rownames(mat) = paste0("row", seq_len(nr))
colnames(mat) = paste0("column", seq_len(nc))

# duplicated rownames with different content
mat_2 <- mat
rownames(mat_2)[2] <- "row1"
Heatmap(mat_2)

# duplicated rownames with same content
mat_3 <- rbind(mat, mat[1, ])
rownames(mat_3)[19] <- "row1"

Heatmap(mat_3)

```

Happly New Year :)
Guandong Shang

**Comment by jokergoo** [comment]
Ah, I think that was my mistake. It is the data frame that does not allow duplicated row names. I will change the text in the manual. 

I don't think we need to print any warning because it is user's duty for the cleanness of the row names. On the other hand, maybe duplicated row names are what they expect, e.g. mapping gene symbols to ensemble IDs will results in same gene symbols for different genes.

**Comment by shangguandong1996** [comment]
Thanks for your reply, Dr Gu. I get it :)
