### ISSUE TITLE
Plotting histograms with densityHeatmap

### ISSUE THREAD

**Issue by psyguy** [jokergoo/ComplexHeatmap#696]
Hello, and thanks for this wonderful package!

I want to plot densities of discrete-valued variables, thus would like to plot the histograms as heatmaps. Here's an MWE:

``` R
library(tidyverse)
library(ComplexHeatmap)

# making the dataframe
set.seed(2021)
m <- data.frame(a = rbinom(1000,5,0.1),
                b = rbinom(1000,5,0.9),
                c = rbinom(1000,5,0.7),
                d = rbinom(1000,5,0.4))

# plotting with densityHeatmap
densityHeatmap(m, show_quantiles = FALSE)`
```
These are what I get:

![image](https://user-images.githubusercontent.com/8527082/109209334-b41f5f80-77ab-11eb-967c-5e497a4f8148.png)

However, I would like to get something like this:

![image](https://user-images.githubusercontent.com/8527082/109216112-63603480-77b4-11eb-8d3a-5e2dea4bac24.png)

Which can be made with `geom_tile`. Here's a very dirty way of doing it:

``` R
h <- apply(m, 2, function(x) hist(x, breaks = seq(-.5,5.5,1))$density) %>%
  cbind(x=0:5,.) %>% 
  as.data.frame() %>% 
  gather("group", "value",2:5)

ggplot(hh, aes(group, x, fill = value)) +
  geom_tile()
```

Is it possible to make such histogram heatmaps with the current version? Would it be in an update to te package?

Cheers.

**Comment by jokergoo** [comment]
Well, that **is** what a "density" heatmap looks like.

If you plot the normal density plot for the four columns:

```r
par(mfrow = c(2, 2))
plot(density(m$a))
plot(density(m$b))
plot(density(m$c))
plot(density(m$d))
```

![image](https://user-images.githubusercontent.com/449218/109220572-66a9ef00-77b9-11eb-9bcf-bc19297b0e77.png)

Actually it fits the density heatmap.

For your case, I think you need to first calculate the count for each level using `table()` and convert to a count matrix:

```r

tbl = lapply(m, table)

m2 = matrix(0, nrow = 6, ncol = 4)
rownames(m2) = 0:5
colnames(m2) = names(m)
m2[names(tbl[[1]]), 1] = tbl[[1]]
m2[names(tbl[[2]]), 2] = tbl[[2]]
m2[names(tbl[[3]]), 3] = tbl[[3]]
m2[names(tbl[[4]]), 4] = tbl[[4]]
```

Then use `Heatmap()` to visualize it:

```r
Heatmap(m2, cluster_rows = FALSE, cluster_columns = FALSE)
```

![image](https://user-images.githubusercontent.com/449218/109222886-2eef7700-77ba-11eb-97b7-672da8b68564.png)

**Comment by psyguy** [comment]
Thanks for the quick response, @jokergoo!

You are absolutely right about the density being a smooth function.

The solution with `table` works, thanks for it.

Though, it would be great if something like `histogramHeatmap` was added to the package as well. Doing it by counting manually would be tedious if the distributions are not bounded (here we knew the range of possible values), and playing with `binwidth`, `breaks`, etc. (as the base `hist()`, as well as ggplot's `geom_freqpoly` offer) would be even harder.

**Comment by jokergoo** [comment]
Emm.. That sounds like a good idea!

I will think about it. Thanks!

**Comment by jokergoo** [comment]
Now I added a new function `frequencyHeatmap()`:

![image](https://user-images.githubusercontent.com/449218/112276553-2be48b00-8c81-11eb-82cd-9a5080994d93.png)

And a 3D version:

![image](https://user-images.githubusercontent.com/449218/112276642-43237880-8c81-11eb-96c5-6bf3b2ec4c50.png)

**Comment by psyguy** [comment]
Nice, thank you! It is not yet committed though, right?

**Comment by jokergoo** [comment]
Just pushed to GitHub several minutes ago.

**Comment by psyguy** [comment]
Thanks, installed the new version and tried it out.

I can point out one tweak: allowing plotting (column-wise) _probabilities_ instead of frequencies. (The same option exists in `hist` arguments: `freq = NULL, probability = !freq`)

It does make a difference if some columns have `NA` values. For instance, if one widens a long dataframe/matrix with unequal group sizes, there will be `NA` in columns with fewer observations (discussed [here](https://stackoverflow.com/q/31700020/2275986)).

**Comment by jokergoo** [comment]
Thanks!

Now I added a new argument `stat` for which the value can be one of `count`, `density` and `proportion`. 

For the problem of `NA`, I think `hist()` which is internally used can automatically handle it, so we don't need to worry about it.

**Comment by psyguy** [comment]
Great!

I tried different `stat`s but it seems `proportion` and `density` give the exact same outputs. How are they different?

(My remark about `NA`s was to signify why density might be preferred to counts. And both `hist` and `frequencyHeatmap` handle `NA`s well.)

**Comment by jokergoo** [comment]
They give the same plot because the bin size is always the same in `frequencyHeatmap()`, so `density = a*proportion` where `a` is a fold change factor. You can see the difference in the values in legend.
