### ISSUE TITLE
Add annotation label for anno_text

### ISSUE THREAD

**Issue by merckey** [jokergoo/ComplexHeatmap#697]
Thank you for this awesome package!

I want to add annotation labels for the `foo` and `bar` using `annotation_label`. It works for the `mat` bar, but not for `anno_text`.
Could you provide some suggestions?

Thanks!

```
m = matrix(rnorm(100), 10)
Heatmap(m) + rowAnnotation(foo= anno_text(paste0("foo", 1:10)), bar= anno_text(paste0("bar", 10:1)),
                           mat = 1:10,
                           annotation_name_side="top",
                           annotation_label=c("FOO","BAR","MAT"))
```

**Comment by jokergoo** [comment]
I think the label for text annotation is not drawn. Why do you need a label for text annotation? Can you give me an example. If it is reasonable, I will add it back.
