### ISSUE TITLE
Changing the default background color

### ISSUE THREAD

**Issue by junghoon-shin** [jokergoo/ComplexHeatmap#698]
It seems that currently the default background colors of all heatmap components are set to "white." Is there a simple way to change all of these to another color, for example, "transparent" so that I can save it as a transparent png file? I tried below, but it didn't work as I intended.

```
library(ComplexHeatmap)

mat = matrix(rnorm(100), nrow = 10, dimnames = list(letters[1:10], letters[1:10]))

png(filename = "test.png", bg = "transparent")
Heatmap(mat)
dev.off()
```

**Comment by jokergoo** [comment]
OK, now it is supported. You need to update from GitHub:


```r
ht = Heatmap(mat)
draw(ht, background = "transparent")
```

**Comment by junghoon-shin** [comment]
Thank you very much! It works like a charm. There is one thing I'd like to notify you, though I'm not sure if this is intended or not.

```
library(ComplexHeatmap)

mat = matrix(rnorm(100), nrow = 10, dimnames = list(letters[1:10], letters[1:10]))

ht = Heatmap(mat)

png(filename = "blueht1.png", bg = "transparent")
blueht = draw(ht, background = "blue")
dev.off()

png(filename = "blueht2.png", bg = "transparent")
blueht
dev.off()
```

After running the above, the first png file (blueht1.png) has a blue background as expected, but the second one (blueht2.png) still has a white background. I guess the background color is not stored in the HeatmapList object, but it confused me at first. Anyway, thanks for the quick update!

**Comment by jokergoo** [comment]
Yes, you are right!

Now it is fixed.
