### ISSUE TITLE
row_order / column_order use character indices

### ISSUE THREAD

**Issue by rmflight** [jokergoo/ComplexHeatmap#7]
`row_order` and `column_order` should be allowed to be character indices if the `rownames` and `colnames` of the matrix are not `NULL` so that reordering can be done using character vectors, which is very useful.

**Comment by jokergoo** [comment]
Yes, you are right, I will support this. Thanks!

**Comment by jokergoo** [comment]
From version 1.2.2, `row_order` and `column_order` can be set as characters.

**Comment by rmflight** [comment]
I will check it out!
