### ISSUE TITLE
How can I change the grid width and height for a character matrix?

### ISSUE THREAD

**Issue by crazyhottommy** [jokergoo/ComplexHeatmap#70]
Hi Zuguang,

I want to plot a character matrix

```r
mat_letters = matrix(sample(letters[1:4], 100, replace = TRUE), 10)
Heatmap(mat_letters)
```

what if I want to change the width and height for each grid? If I use the `cell_fun`

```r
cell_fun = function(j, i, x, y, width, height, fill) {
        grid.rect(x = x, y = y, width = width * 0.6, height = height, gp = gpar(col = "grey", fill = NA))
        }
Heatmap(mat_letters, rect_gp = gpar(type = "none"), cell_fun = cell_fun, col = 1:4)
```
each grid becomes thinner, but there is space between grids.

I can get around by specifying the `x = x*0.6`, but now there is a space between the heatmap body and the legend. Also I do not know how to map the colors to different characters with `fill` inside the `cell_fun`.

Thanks very much!
Tommy

**Comment by jokergoo** [comment]
Hi Tommy,

in `cell_fun`, `width` and `height` is the width and height of the cell and `fill` is the color for the current cell which is defined by `col` argument (no matter it is a vector of colors or a color mapping function), so following code:

```{r}
Heatmap(mat, col, cell_fun = function(j, i, x, y, width, height, fill) {
    grid.rect(x, y, width, height, gp = gpar(col = NA, fill = fill)
})
```

is identical to 

```{r}
Heatmap(mat, col)
```

In your case, if you want to add spaces around each cell, you can change the width and height like:

```{r}
cell_fun = function(j, i, x, y, width, height, fill) {
	grid.rect(x = x, y = y, width = width * 0.6, height = height*0.6, 
		gp = gpar(col = "grey", fill = fill))
}
Heatmap(mat_letters, rect_gp = gpar(type = "none"), cell_fun = cell_fun, col = 1:4)
```

In following I made three heatmaps which are 1. no spaces around cells; 2. there are spaces and 3. the cell is always square:

```{r}
ht1 = Heatmap(mat_letters, col = 1:4)

cell_fun = function(j, i, x, y, width, height, fill) {
	grid.rect(x = x, y = y, width = width * 0.6, height = height*0.6, 
		gp = gpar(col = "grey", fill = fill))
}
ht2 = Heatmap(mat_letters, rect_gp = gpar(type = "none"), cell_fun = cell_fun, col = 1:4)

ht1 + ht2

cell_fun2 = function(j, i, x, y, width, height, fill) {
	s = min(unit.c(convertWidth(width, "cm"), convertHeight(height, "cm")))
	grid.rect(x = x, y = y, width = s * 0.8, height = s*0.8, 
		gp = gpar(col = "grey", fill = fill))
}
ht3 = Heatmap(mat_letters, rect_gp = gpar(type = "none"), cell_fun = cell_fun2, col = 1:4)

ht1 + ht2 + ht3
```

<img width="916" alt="screen shot 2017-01-05 at 16 58 47" src="https://cloud.githubusercontent.com/assets/449218/21687108/458cacb2-d368-11e6-8e62-0d7be3db8664.png">

**Comment by crazyhottommy** [comment]
Thanks! this is very helpful! I am learning some basics of grid packages as well.

**Comment by gowthamee** [comment]
Hi,
I have a follow up question about setting "width" and "height" using "cell_fun".

I tried your previous suggestions, but I just could not get the heatmap to look the way it does when using "width" and "height" arguments in pheatmap function.  

The code I used is given below:

``cell_fun2 = function(j, i, x, y, width, height, fill) {
      s = min(unit(c(convertWidth(1, "cm"), convertHeight(1.5, "cm"))))
      grid.rect(x = x, y = y, width = s * 0.8, height = s*0.8, 
                gp = gpar(col = "grey", fill = fill))
    } ``
    
  ``  cell_fun = function(j, i, x, y, width, height, fill) {
      grid.rect(my.matrix[i, j], x = 1, y = 1, width = 2, height = 2)
    } ``

`` heat1 <- Heatmap(as.matrix(my.matrix), 
                      col = inferno(100),
                    border = TRUE,  
                    rect_gp = gpar(col = "black", lty = 1, lwd = 2),
                      name = "log2FC",
                      cell_fun = cell_fun,
                      cluster_columns = FALSE,
                      cluster_rows = FALSE,
                      #row_dend_gp = gpar(col = c("#440154FF", "#22A884FF", "#433E85FF", "#2BB07FFF")),
                      show_row_dend = TRUE,
                      row_dend_side = "left",
                      row_dend_width = unit(2, "cm"),
                      show_row_names = TRUE,
                      row_names_gp = gpar(fontsize = 5.5, fontface = "bold"),
                      column_names_side = "top",
                      column_names_gp = gpar(fontsize= 10, fontface = "bold", 
                                             col = c(rep("#440154FF", 4), rep("#440154FF", 4))),
                      column_names_rot = 360,
                      km = 4,
                      gap = unit(3, "mm"),
                      #combined_name_fun = NULL,
                      show_heatmap_legend = TRUE) ``

My goal is to create hundreds of heatmap in a loop, and save it individually as a .png file, without having to adjust the width and height using the png function (example given below):

`` png(file = paste(saveFolder, "/Grouped_Term_Figs", "/", names(term_names)[n], "/",t_name, "_line_pie.png", sep = ""),
        width =  6 * 400,
        height = 7 * 400,
        res = 400)
    print(heat1)
    dev.off()``

Do you have other suggestions, perhaps ? Thanks !!!

**Comment by jokergoo** [comment]
In `cell_fun`, `width` and `height` only control the size of every small grid in the heatmap.

What is your aim:

1. you have matrices with different rows/columns and you want to make the size of the heatmap grid the same for all heamtaps (assume one matrix has 5 rows and the second matrix has 10 rows, do you want the second heatmap have double height as the first heatmap)?

2. just to set the width/height of the whole heatmap?

**Comment by gowthamee** [comment]
Hi, 
Yes-The goal is what you have stated in 1.
Different number of rows for different matrices/heat map, albeit the column numbers are the same.

**Comment by jokergoo** [comment]
Or you can set the png with large size and control the height of the heatmap by:

```r
Heatmap(mat, ..., heatmap_height = unit(1, "cm")*nrow(mat))
```

`heatmap_height` controls the height of the heatmap body (without column names, dendrograms). Of course for small heatmap, there will be large white areas in the png file.

**Comment by gowthamee** [comment]
Thanks for the detailed information. I will try it in a short while and follow up if I run into trouble. Again, thank you so much for taking the time.

**Comment by sapirl** [comment]
> In `cell_fun`, `width` and `height` only control the size of every small grid in the heatmap.
> 
> What is your aim:
> 
> 1. you have matrices with different rows/columns and you want to make the size of the heatmap grid the same for all heamtaps (assume one matrix has 5 rows and the second matrix has 10 rows, do you want the second heatmap have double height as the first heatmap)?
> 2. just to set the width/height of the whole heatmap?

Hey,
My goal is to set the heatmap height as you mentioned in option number 2.
How would you suggest to tackle this? Is there an option to solve it without using cell fun?

**Comment by jokergoo** [comment]
@sapirl , then can you directly set `height` and `width` argument in `Heatmap()` function?
