### ISSUE TITLE
How do I control each heatmap height when I have 2 heatmap vertically?

### ISSUE THREAD

**Issue by TnakaNY** [jokergoo/ComplexHeatmap#700]
Please provide example datasets and the code you use. It will help me to understand your problem and help you!
I have two heatmap. Upper one (h1) has 400 rows and lower one (h2) has 10 rows.
When I make combined heatmap using "ht-list= h1 %v% h2, draw(ht-list)", lower heatmap is too small to see.

How do I control each heatmap height when I plot two heatmap that size is totally different? 

![Testheatmap](https://user-images.githubusercontent.com/40367441/109866694-9468bb00-7c33-11eb-9485-23d9446a5ae8.PNG)

**Comment by jokergoo** [comment]
You can set `height` argument in both heatmaps:

```r
Heatmap(..., height = unit(8, "cm")) %v% Heatmap(..., height = unit(4, "cm"))
```

**Comment by TnakaNY** [comment]
Thanks!
