### ISSUE TITLE
Reverse the direction of annotation

### ISSUE THREAD

**Issue by Yuqing66** [jokergoo/ComplexHeatmap#702]
Hi, I tried to reverse the direction of a boxplot annotation using the parameter provided in the barplot annotation part of the reference book.

leftAnn <- rowAnnotation(gene1 = anno_barplot(number.vector), axis_param = list(direction = "reverse"))
Error: axis_param: annotations should be vector/data frame (only `df`)/matrix/functions.

Could you please help with this? Thank you.

**Comment by jokergoo** [comment]
```r
leftAnn <- rowAnnotation(gene1 = anno_barplot(number.vector, axis_param = list(direction = "reverse")))
```

`axis_param` should be inside `anno_barplot()`.
