### ISSUE TITLE
ht_pos_on_device / Shiny brush engine not available in new version

### ISSUE THREAD

**Issue by lwarode** [jokergoo/ComplexHeatmap#703]
Hi, I wondered why the current version of `ComplexHeatmap` doesn't support `ht_pos_on_device` and `get_pos_from_brush`anymore. I used them in a prior version and found it very useful since it was a nice way to implement the brush engine from Shiny. The usage is demonstrated by this [example](https://jokergoo.github.io/2020/05/15/interactive-complexheatmap/)

**Comment by jokergoo** [comment]
Hi, that post was written long time ago. Now all these functions are moved to a new package InteractiveComplexHeatmap (https://github.com/jokergoo/InteractiveComplexHeatmap) with more mature functionalities.

**Comment by lwarode** [comment]
Thanks for the answer. I am aware of InteractiveComplexHeatmap, however, for our project purpose, ComplexHeatmap seems to be the better option since it allows more customization and general flexibility. Are there other ways to implement the Shiny brush engine when using ComplexHeatmap(s)? Thanks in advance.

**Comment by jokergoo** [comment]
InteractiveComplexHeatmap is just a complement package for ComplexHeatmap. The two functions `ht_pos_on_device` and `get_pos_from_brush` are renamed to `htPosOnDevice` and `getPosFromBrush` in InteractiveComplexHeatmap. Of course now you need to load both packages:

```r
library(ComplexHeatmap)
library(InteractiveComplexHeatmap)
```

**Comment by lwarode** [comment]
Hi, I think you meant `htPositionsOnDevice` not `htPosOnDevice` (using `InteractiveComplexHeatmap` 0.99.10.1002). However, I cannot find `getPosFromBrush` or a similar function. Is the [reference](https://jokergoo.github.io/InteractiveComplexHeatmap/reference/index.html) up to date? Thanks in advance!

**Comment by jokergoo** [comment]
Ah, sorry, you are right.

The first function is called `htPositionsOnDevice()` and `get_pos_from_brush()` (this has not been renamed!) is not exported and you need to access it by `InteractiveComplexHeatmap:::get_pos_from_brush()`.

**Comment by lwarode** [comment]
Thanks for the answer. I can confirm that `InteractiveComplexHeatmap:::get_pos_from_brush()` works
