### ISSUE TITLE
decorate_annotation slice for columns split

### ISSUE THREAD

**Issue by andrewjkwok** [jokergoo/ComplexHeatmap#707]
Hi,

I am creating heatmaps with this lovely package and enjoy using the column_split / row_split functions to highlight differences. 

When I split the columns with "column_split = n" within the Heatmap function, my HeatmapAnnotation splits accordingly which is great. However, when I then try to decorate that annotation e.g. adding a dotted line across a specific height for my anno_barplots, the line is only added to the left most annotation. Changing the "slice" argument doesn't help. 

Is the "slice" argument the correct one to be looking for, or am I missing something else?

Many thanks in advance.

**Comment by jokergoo** [comment]
Can you also add an example here? Maybe it is a bug :)

**Comment by jokergoo** [comment]
What is your version of ComplexHeatmap? Maybe you need to install a newer version (better from GitHub). I have an impression that I saw this bug and I have fixed it in recent versions.

```r
m = matrix(rnorm(100), 10)
Heatmap(m, column_split = 3, top_annotation = HeatmapAnnotation(foo = 1:10))

for(i in 1:3) {
	decorate_annotation("foo", slice = i, {
		grid.rect(gp = gpar(col = i))
	})
}
```

![image](https://user-images.githubusercontent.com/449218/111185287-1bae1b00-85b2-11eb-8f96-c04502ddffae.png)

**Comment by ahwanpandey** [comment]
Hello,

I have just installed the latest version from github. i was wondering if there is any way to add the decorations to all the slices without doing it for each "slice"? My decorations here are the dotted lines in the barplots. This is just an example but there could be figures with many more slices/splits.

![image](https://user-images.githubusercontent.com/8450532/120731175-62af0b00-c526-11eb-80a1-c0df9faabd93.png)

Thanks,
Ahwan

**Comment by ahwanpandey** [comment]
Ah I suppose I could just do a for loop :)

```
for(slice_ in number_of_slices){
  decorate_annotation("sample_alteration_count", slice = slice_,{
    for(at in c(5,10,15)) {
      grid.lines(unit(c(0, 1), "npc"), c(at, at), default.units = "native", gp = gpar(col = "#00000040", lty = 2))
    }
  })
}
```

**Comment by jokergoo** [comment]
Yes, you need to put it in a for loop.
