### ISSUE TITLE
Manualy Change Row Order

### ISSUE THREAD

**Issue by pthom010** [jokergoo/ComplexHeatmap#708]
Is it possible to manually change the order of your clusters when you use `split`?  I have a data frame that looks like this:

```
 Class Score 
Jeff Biology 100
Kenneth Chemistry 99
Katherine Math 97
Joy English 98
```

I would like to make a heatmap where I split rows by the Class column and have them be presented in a specific order in the heatmap.

**Comment by jokergoo** [comment]
You can set `split` as a factor and its `levels` controls its order.
