### ISSUE TITLE
How can I change the fontsize of row names in Oncoprint 

### ISSUE THREAD

**Issue by 1988liszt** [jokergoo/ComplexHeatmap#71]
Hi,

Could you tell me how to change the fontsize of row names in Oncoprint ? Thanks!

Best regards,
Liszt

**Comment by jokergoo** [comment]
To change the font size of row names, try:

```
oncoPrint(..., row_names_gp = gpar(fontsize = 12))
```

**Comment by 1988liszt** [comment]
Thanks!
