### ISSUE TITLE
Show NA Category in Automatic Legends

### ISSUE THREAD

**Issue by DarioS** [jokergoo/ComplexHeatmap#711]
If I create a `HeatmapAnnotation` and incorporate it via `bottom_annotation`, how can I tweak the legend to also show the NA? Could this be an additional useful example for Chapter 5 of the user guide?

**Comment by jokergoo** [comment]
If the value is `NA`, this means it is not available and I think it is no need to put it on legend. If `NA` means something to you, then you set `NA` to a string `"NA"` and treat it as a norma factor in your annotation data.
