### ISSUE TITLE
Combine information from two matrix

### ISSUE THREAD

**Issue by fgualdr** [jokergoo/ComplexHeatmap#712]
Hi,
I am trying to combine informations coming from two matrix (with same size and elements).
Basically I would like to represent -log10(value) with colours while fold changes with bubble of different sizes.
I am using cell_fun where I specify the colour using one matrix and the fold using the other.
It seems that if I allow clustering this produce an issue as I won't have the two matrix to correspond anymore.
I don't know how to solve as I need the clustering and these two informations combined.
Thanks

**Comment by jokergoo** [comment]
Can you also attached example dataset and code?

**Comment by V-JJ** [comment]
Hello @jokergoo !

I have a similar problem. 

1) I'd like to plot two different distances on the same heatmap (that is, one distances on the upper triangular part of a matrix and the other on the lower triangular part of a matrix). The main issue is that must change the parameters that define the color scale of each distance separately.

2) I tried to create two complementary heatmaps (with part of the matrix information removed) and use the subsetting options that you explain in the tutorials. However, I couldn't overlap them. 

Any help or advice would be helpful,


Thanks in advance
V.

Test data for the code below: 
[Dml-Chr1.df.txt](https://github.com/jokergoo/ComplexHeatmap/files/6377679/Dml-Chr1.df.txt)

Now I'm stuck at this point
![plot_zoom_png](https://user-images.githubusercontent.com/50242639/116095981-2bd51200-a6a9-11eb-9673-c06348e8d0c1.png)

And I'd like to get something similar to that (https://stackoverflow.com/questions/56958346/create-a-single-heatmap-based-on-two-symmetric-matrices-in-r) but with my data
![plot_zoom_png2](https://user-images.githubusercontent.com/50242639/116096749-d4837180-a6a9-11eb-8589-94132b0bcb18.png)


Code used to generate the above ComplexHeatmaps

```
library(ComplexHeatmap)
library(circlize)
library(pheatmap)
### 1 # Input file
matrix_i <- "Dml-Chr1.df.txt"
read_data <- read.csv(matrix_i,header=TRUE,sep="\t",dec=".",check.names = FALSE,stringsAsFactors = FALSE)
filename <- gsub(".df.txt","",matrix_i)


chrm_i <- paste(c(Family_name,"Dm-Chr"),collapse = "") #### Prepare new short names for each gene
chrm <- gsub(chrm_i,"",filename)
newname_for_each_gene <- paste(chrm,collapse = "") 


rownames(read_data) <- read_data[,1] #### row/column names
col_names <- colnames(read_data)


read_as_df <- data.frame(read_data,check.names = FALSE) #### Preparing the matrix
read_as_df <- read_as_df[-c(1)] # Remove one useless column

Matrix_for_Hmap <- as.matrix(read_as_df)

### 2.1 # DIST1 - parameters
breaks_vector_dist1 <- c(0, 0.09, 0.1, 0.2, 0.5, 1, 2, 5, 10, 100) #
Llabels1 = c("0","<0.1","0.1-0.2","0.2-0.5","0.5-1","1-2","2-5","5-10",">10",">100")
Colors1 <- colorRamp2(breaks = breaks_vector_dist1, 
                      colors = c("red2", "orange","gold","green","forestgreen","cyan","blue","darkgrey","pink","black"))

### 2.2 # DIST2 - parameters
breaks_vector_dist2 <- c(0, 0.199, 0.4, 0.6, 0.8, 1, 2, 3.99, 4) #
Llabels2 = c("0","<0.2","0.2-0.4","0.4-0.6","0.6-0.8","0.8-1","1-2","2-4",">4")
Colors2 <- colorRamp2(breaks = breaks_vector_dist2, 
                                        colors = c("red2", "orange","gold","green","forestgreen","cyan","blue","darkgrey","pink"))

### Function to plot a ComplexHeatmap
generate_CHeatmap <- function(matrix_i, name_i, breaks_i, colors_i, labels_i) {
  heatmap_i  = Heatmap(matrix_i,
          name = name_i, 
          row_names_side = "left",
          row_names_gp = gpar(fontsize = 10),
          column_names_gp = gpar(fontsize = 10),
          cluster_rows = FALSE,
          cluster_columns = FALSE,
          col = colors_i, # change that if you use hundred_kb / ten_kb / hundred_kb scale
          # row_order = 
          # column_order =
          heatmap_legend_param = list(at = breaks_i,
                                      color_bar = "discrete",
                                      legend_height = 10,
                                      grid_height = unit(0.5,"cm"),
                                      grid_width = unit(0.5, "cm"),
                                      labels_gp = gpar(fontsize = 10),
                                      labels = labels_i))
  return(heatmap_i)
}
### A) Heatmap generated with # 2.1 # parameters (color and scale) for the whole matrix
A_HeatMap <- generate_CHeatmap(Matrix_for_Hmap,"Test1",breaks_vector_dist1,Colors1,Llabels1)
A_HeatMap

########## Triangular matrices 
Matrix_for_Hmap_lower <- as.matrix(read_as_df) 
Matrix_for_Hmap_upper <- as.matrix(read_as_df)

Matrix_for_Hmap_lower[upper.tri(Matrix_for_Hmap_lower,diag=TRUE)] <- NA # delete upper matrix 
Matrix_for_Hmap_upper[lower.tri(Matrix_for_Hmap_upper)] <- NA # delete lower matrix 

### B) Plot both matrices separately
B1_HeatMap <- generate_CHeatmap(Matrix_for_Hmap_lower,"Dist1",breaks_vector_dist1,Colors1,Llabels1) 
B2_HeatMap <- generate_CHeatmap(Matrix_for_Hmap_upper,"Dist2",breaks_vector_dist2,Colors2,Llabels2)

C_HeatMap <- B1_HeatMap + B2_HeatMap
C_HeatMap

```

**Comment by jokergoo** [comment]
Hi, let me answer you with a simpler example.

In the following example, `mat1` and `mat2` are the two matrices you want to combine. Here in the examples, for easiness, they are not symmetric, but it does not matter. We only use the upper triangle matrix of `mat1` and lower triangle matrix of `mat2`.

Here `mat1` and `mat2` are all in characters, although `mat1` correspond to numeric information. Also we defined the colors for the two matrices, in `col1` and `col2` where `col1` contains bright colors and `col2` contains dark colors.

```r
mat1 = matrix(as.character(sample(10, 100, replace = TRUE)), 10)
mat2 = matrix(sample(letters[1:10], 100, replace = TRUE), 10)

col1 = structure(rand_color(10, luminosity = "bright"), names = 1:10)
col2 = structure(rand_color(10, luminosity = "dark"), names = letters[1:10])
```

To merge the two matrices, we need to set `rect_gp = gpar(type = "none")` which means we do not draw anything from the input matrix, and we define a `cell_fun` which is responsible to drawing the combined matrix.

In the following example, whether the first argument is `mat1` or `mat2` is not important, since it is not used for plotting, The only thing is the dimension should be the same as the combined matrix (actually, the dimension names are used).

Also note, for argument `col`, we combind `col1` and `col2` so that a combined legend will be drawn.

```r
Heatmap(mat1, col = c(col1, col2), cluster_rows = FALSE, cluster_columns = FALSE,
	rect_gp = gpar(type = "none"),
	cell_fun = function(j, i, x, y, w, h, fill) {
		if(i == j) { # diagonal
			grid.rect(x, y, w, h, gp = gpar(fill = "red", col = NA))
		} else if(i > j) { # lower triangle
			grid.rect(x, y, w, h, gp = gpar(fill = col2[mat2[i, j]], col = NA))
		} else { # upper triangle
			grid.rect(x, y, w, h, gp = gpar(fill = col1[mat1[i, j]], col = NA))
		}
	})
```

![image](https://user-images.githubusercontent.com/449218/116234422-deb27800-a75c-11eb-819a-30bc17bbaefb.png)

**Comment by V-JJ** [comment]
Great! Thank you very much. I got it

**Comment by xianweiw** [comment]
Hi Dear Jokergoo,
Thank you for providing the valuable comments.
If col1 and col2 are defined as follows: col1=colorRamp2(c(0,12,22),c("white","#FF3333","red"))
col2=colorRamp2(c(0,20,37),c("white","#99CCFF","dodgerblue")). How do i modify the codes that you provided in heatmap()? Thank you so much.
