### ISSUE TITLE
Error for pheatmap annotations when invoked by do.call

### ISSUE THREAD

**Issue by dtm2451** [jokergoo/ComplexHeatmap#723]
Hey there!

Looks like some recent change may have broken `ComplexHeatmap::pheatmap` annotations, at least when invoked via `do.call`.

I saw the same issue with both the Bioc-devel & GitHub versions of the package.

Repro-ex:

```
set.seed(42)
nsamples <- 10

mat <- matrix(rpois(20*nsamples, 20), ncol=nsamples)
colnames(mat) <- paste0("sample", seq_len(ncol(mat)))
rownames(mat) <- paste0("gene", seq_len(nrow(mat)))

annot <- data.frame(
  labs = sample(c("A","B","C","D"), size = ncol(mat), replace = TRUE),
  row.names = colnames(mat)
)

# Works for both pheatmap:: and ComplexHeatmap::, with & without annotations:
pheatmap::pheatmap(mat = mat)
pheatmap::pheatmap(mat = mat, annotation_col = annot)
ComplexHeatmap::pheatmap(mat = mat)
ComplexHeatmap::pheatmap(mat = mat, annotation_col = annot)

# Fails for ComplexHeatmap::, with annotations, when requested with do.call:
ins <- list(mat = mat, annotation_col = annot)
do.call(pheatmap::pheatmap, ins[1]) # good
do.call(pheatmap::pheatmap, ins) # good
do.call(ComplexHeatmap::pheatmap, ins[1]) # good
do.call(ComplexHeatmap::pheatmap, ins) # ERROR
```

Error message:
```
Error in sum(l_simple_anno) : invalid 'type' (list) of argument
```

In case this helps, running with `debug` on narrows it down to lines:
```
ht_param$top_annotation = HeatmapAnnotation(df = annotation_col[, 
    ncol(annotation_col):1, drop = FALSE], col = annotation_colors, 
    show_legend = annotation_legend, show_annotation_name = annotation_names_col, 
    gp = gpar(col = border_color), annotation_name_gp = gpar(fontsize = 10, 
        fontface = "bold"), simple_anno_size = unit(10, "bigpts"), 
    gap = unit(2, "bigpts"))
```

**Comment by jokergoo** [comment]
Thanks for reporting. Yes, I haven't tested extensively with `do.call()`.

Current solution is to use the function as a string in `do.call()`:

```r
do.call("pheatmap", ins, envir = asNamespace("ComplexHeatmap"))
```

I will fix the bug when using function as a variable.

**Comment by jokergoo** [comment]
Now `do.call(ComplexHeatmap::pheatmap, ins)` should also work. Please update from GitHub.

**Comment by dtm2451** [comment]
Thanks!  Confirming this works now with GitHub version.

**Comment by dtm2451** [comment]
Just wondering if this will soon make it into Bioc-devel as I have updates to my ComplexHeatmap-reliant package that I want to roll out, but this error blocks dittoSeq's BBS builds.

I can alternatively switch to using `do.call("pheatmap", ins, envir = asNamespace("ComplexHeatmap"))` I suppose... do you expect this calling method to be more reliable long-term?  (Would it be possible to add a unit-test for these do.call methods?)

**Comment by jokergoo** [comment]
Sorry I thought this issue was closed. 

Yes, thanks for your suggestion. I have added it in the tests.

The changes have been updated on the devel branch so your package should pass the bioc build.
