### ISSUE TITLE
Heatmap grid, keeping uniform legends next to each

### ISSUE THREAD

**Issue by vkartha** [jokergoo/ComplexHeatmap#724]
Hi,
     Thank you again for such an amazingly useful package! I was trying to assemble a grid of heatmaps (2 rows, multiple columns) where I wanted the legend to appear directly under each one (or beside it), rather than get collected all at once and shown together on the right / bottom (example of desired output shown below). 
  
  
![image](https://user-images.githubusercontent.com/9615730/115252938-ebe6bb80-a0f9-11eb-9f38-3bd000447b2d.png)

 I know ComplexHeatmap requires heatmap lists to be either all horizontal or all vertical, so for now I manually assemble them to my liking. The issue I'm having doing this in general is that the legend sizes are not the same (given different scales and data ranges across the heatmaps), and I don't see an option for assembling heatmap lists where we can keep the legend next to each heatmap, instead of all together on a particular side. 

Any suggestions for fewer manual edits downstream would be greatly appreciated!

**Comment by jokergoo** [comment]
Maybe you can use cowplot package to arrange these 4 heatmaps:

```r
ht1 = Heatmap(..., heatmap_legend_param = list(direction = "horizontal"))
p1 = grid.grabExpr(draw(ht1, heatmap_legend_side = "bottom"))
...
plot_grid(p1, p2, p3, p4, nrow = 2)
```
