### ISSUE TITLE
The pdf format draw empty components in barplot

### ISSUE THREAD

**Issue by ZWanBing** [jokergoo/ComplexHeatmap#728]
![image](https://user-images.githubusercontent.com/33241734/116205285-2a225180-a770-11eb-9609-fa471d0e92cc.png)
![image](https://user-images.githubusercontent.com/33241734/116205447-5d64e080-a770-11eb-9651-345f5f9d2cd2.png)
I have found that oncoprint barplot annotation will draw empty components as very thin lines on the top of bars when I print out the figure to **PDF** format.
Could you fix this or figure out that it may be my own bug?

**Comment by jokergoo** [comment]
Please provide me example code and data.

**Comment by ZWanBing** [comment]
@jokergoo 
```
library(openxlsx)
library(ComplexHeatmap)
col<-setNames(c("#E8947D", "#3A5180", "#199880", "#4DB0C7" ,"#D84C37",
                "#e75545", "#55bed6", "#25a38a"),
              nm = c("missense_mutation","amplification" ,"frameshift_mutation",
                     "stopgain" ,"germline" ,"splicing", "deletion" ,"TSS"))

alter_fun = list(
  background = function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), 
              gp = gpar(fill = "#D4D7DC", col = NA))
  },
  deletion = function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h*0.5, 
              gp = gpar(fill = col["deletion"], col = NA))
  },
  amplification = function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h*0.5, 
              gp = gpar(fill = col["amplification"], col = NA))
  },
  frameshift_mutation= function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), 
              gp = gpar(fill = col["frameshift_mutation"], col = NA))
  },
  missense_mutation= function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), 
              gp = gpar(fill = col["missense_mutation"], col = NA))
  },
  splicing= function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), 
              gp = gpar(fill = col["splicing"], col = NA))
  },
  stopgain= function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), 
              gp = gpar(fill = col["stopgain"], col = NA))
  },
  TSS= function(x, y, w, h) {
    grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), 
              gp = gpar(fill = col["TSS"], col = NA))
  },
  germline = function(x, y, w, h) {
    grid.points(x, y, pch = 17,unit(2,"mm"), 
                gp = gpar(col = col["germline"]))
  }  
)
dat<-read.xlsx("mutation_mat_demo.xlsx",rowNames = TRUE)
ot<-oncoPrint(dat,
              alter_fun = alter_fun,
              col = col,
              row_names_side = "left",
              show_column_names = TRUE,
              pct_side = "right")
draw(ot)
pdf("test.pdf",width = 8,height = 5)
draw(ot)
dev.off()

png("test.png",width = 30,height = 15,
       units = "cm",res=300)
draw(ot)
dev.off()
```
[test.pdf](https://github.com/jokergoo/ComplexHeatmap/files/6457186/test.pdf)
[mutation_mat_demo.xlsx](https://github.com/jokergoo/ComplexHeatmap/files/6457188/mutation_mat_demo.xlsx)
![test](https://user-images.githubusercontent.com/33241734/117774092-b43be100-b26b-11eb-99f6-3269f651e722.png)

you can see the lines should not show on the PDF plot.

**Comment by jokergoo** [comment]
Hi, I think it is not a bug. These bars have height of zero. It is a matter of PDF viewer how to render zero height bars. The following screenshot is from pdf.js. You can see the zero height bars are not drawn.

![image](https://user-images.githubusercontent.com/449218/117788134-66ad7d00-b247-11eb-9c01-db6887ded8b7.png)

To improve it in ComplexHeatmap, I can actually NOT draw the rectangles if they have zero height.

**Comment by ZWanBing** [comment]
![image](https://user-images.githubusercontent.com/33241734/117792170-9f684900-b27d-11eb-897a-e4fce4d09f91.png)
Yes, you are right!
Adobe PDF reader and edge, chrome browser all show zero height bars 😭
What a upset thing for me.
