### ISSUE TITLE
anno_points for different size

### ISSUE THREAD

**Issue by mv911119** [jokergoo/ComplexHeatmap#729]
Hi,

I have read that the anno_point() needs a unit for a size in all points in annotation.
However I want to have different sizes for points in different row in row_ha.
I kinda know I should use new annotation functions for this function. But I am really lost in creating this function for different size.

Could you please help me?

Best,
MV

**Comment by mv911119** [comment]
![image](https://user-images.githubusercontent.com/36156558/116212653-55437b80-a745-11eb-9539-b2311515582a.png)
My goal in ggplot.

**Comment by jokergoo** [comment]
I think you can directly use a heatmap instead of an annotation for this dot plot:

```r
ht_dot = Heatmap(m, col, rect_gp = gpar(type = "none"),
    cell_fun = function(j, i, x, y, w, h, fill) {
    	grid.points(x, y, size = ..., gp = gpar(col[m[i, j]]))
    }
)
```

then append to your main heatmap

```r
ht + ht_dot
```

**Comment by mv911119** [comment]
This is the most brilliant idea I have ever heard today.
Thanks a lot!

**Comment by naveedishaque** [comment]
Hello Bioinformagician!

I was going to ask the same question. I think it would be great to have a section in the ComplexHeatmap book describing how one can add dot plots that make use of both size and color (e.g. significance and log2FC).

Nav

**Comment by jokergoo** [comment]
@naveedishaque as you wish, no problem!
