### ISSUE TITLE
OncoPrint for 300 genes

### ISSUE THREAD

**Issue by 1988liszt** [jokergoo/ComplexHeatmap#73]
Hi,

I need to make a OncoPrint for 300 genes, but it shows :

Error in oncoPrint(mat, get_type = function(x) strsplit(x, ";")[[1]],  : 
  You should define shape function for: unknown

When I draw OncoPrint for 100 genes, it still work fine. I don't know how to solve this problem, could you help me?  Thanks!

Liszt

**Comment by crazyhottommy** [comment]
Your mutation was annotated with unknown function.
you have to specify what color to represent the unknown.
```r
alter_fun = list(
    background = function(x, y, w, h) {
        grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), gp = gpar(fill = "#CCCCCC", col = NA))
    },
    Missense_Mutation = function(x, y, w, h) {
        grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), gp = gpar(fill = "#008000", col = NA))
    },
    Nonsense_Mutation = function(x, y, w, h) {
        grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), gp = gpar(fill = "red", col = NA))
    },
    Splice_Site = function(x, y, w, h) {
        grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), gp = gpar(fill = "orange", col = NA))
    },
    Multi_Hit = function(x, y, w, h) {
        grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), gp = gpar(fill = "black", col = NA))
    },
    UNKNOWN = function(x, y, w, h) {
        grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), gp = gpar(fill = "gray90", col = NA))
    }
)

## color for barplot

col_bar = c("Splice_Site" = "orange", "Nonsense_Mutation" = "red", 
            "Missense_Mutation" = "#008000", "Multi_Hit" = "black", "UNKNOWN" = "gray90")


oncoPrint(onco_mat, get_type = function(x) strsplit(x, ";")[[1]],
    alter_fun = alter_fun, col = col_bar, 
    column_title = "OncoPrint for mutated genes",
    heatmap_legend_param = list(title = "Alternations", at = c("Splice_Site", "Nonsense_Mutation", "Missense_Mutation", "Multi_Hit", "UNKNOWN"), 
        labels = c("Splice site", "Nonsense mutation", "Missense mutation", "Multi-hit", "Unknown"),
        nrow = 1, title_position = "leftcenter"),
    show_column_names = TRUE,
    row_names_gp = gpar(fontsize = 10),
    pct_gp = gpar(fontsize = 10))

```

Tommy

**Comment by 1988liszt** [comment]
Hi，

Thanks! I solved the previous problem, but there are some new problems. I found when the number of gene more than around 200, it didn't draw all genes and their mutation information in the result. For example，I didn't found the “frameshift_insertion” in the annotation. Besides, it show many blank cells in the picture.  Last, coulg you tell me how to hide the percent of genes that have alterations. I use "show_pct = F", but it also hide the percent of samples that have alterations. Thanks!

![1](https://cloud.githubusercontent.com/assets/25049637/22133025/b601d1b6-def8-11e6-8653-e5e22b3968bc.jpeg)

**Comment by jokergoo** [comment]
`show_pct` controls whether to plot the text which you marked with red rectangle. What do you mean by "the percent of genes that have alterations"? Do you mean the barplots on the top? If so, just set `top_annotation = NULL` in `oncoPrint()`.

**Comment by 1988liszt** [comment]
Hi, I set show_pct=F, the top annotation will also be delected. Is there any way to keep the top annotation and delete the pct? Thanks!
![99pi3_aji r9 _ jex j58s](https://cloud.githubusercontent.com/assets/25049637/22179083/1f8900f0-e084-11e6-8587-80d6adce35fc.png)

**Comment by jokergoo** [comment]
According to your plot, the top barplot annotation is still there. Do you mean the axis labels are gone? You can increase the left space for the whole plot by:

```
ht = oncoPrint(...)
draw(ht, padding = unit(c(2, 10, 2, 2), "mm"))
```
