### ISSUE TITLE
heatmap label positions when combining anno_mark and column_split or row_split

### ISSUE THREAD

**Issue by jeslipp** [jokergoo/ComplexHeatmap#730]
First of all, thank you for your excellent package!

I noticed that when combining `anno_mark` with `column_split` or `row_split` the annotated features are not in the correct place. Is there a way to make this work properly that I might have missed?

Thank you for your time!

**Comment by jokergoo** [comment]
What is your ComplexHeatmap version? It should work under current version (to be safe, GitHub version).

**Comment by jeslipp** [comment]
I was using 2.4.3 in RStudio. Based on the messages in the newest version (2.7.10.9002) it looks like I need to use `pdf()` to make `anno_mark()` work. 

Thank you!
