### ISSUE TITLE
ComplexHeatmap::pheatmap

### ISSUE THREAD

**Issue by shexiaolu** [jokergoo/ComplexHeatmap#732]
hi! there is a question when i use the pheatmap() function in the Complexpheatmap. From your reference book,it should be version 2.5.2 so that i can use pheatmap().But when i updated the package ,it is still can not use the function .i need some help to solve this problem.Below is the code:
`library(ComplexHeatmap)
> packageVersion('ComplexHeatmap')
[1] ‘2.7.11’
> ComplexHeatmap::pheatmap
Error: 'pheatmap' is not an exported object from 'namespace:ComplexHeatmap'`

hope for your reply !

**Comment by jokergoo** [comment]
Strange. Maybe you forgot to unload ComplexHeatmap before updating it. Can you try to restart your R session?

**Comment by shexiaolu** [comment]
Thanks!! It works!!!
