### ISSUE TITLE
column_dend subsetting returns inconsistent branches

### ISSUE THREAD

**Issue by antass** [jokergoo/ComplexHeatmap#733]
I have a clustered heatmap `expr_hm`.  When I inspect dendrogram I want to extract leaves from., I get different branch compositions each time I run the function. I am expecting branch 3 to have 9 members, and yet I get 7 members the first time I run the function:

    > column_dend(expr_hm)$`3` %>% labels
    [1] "C_840113-002_post_AG881_FF" "C_840117-011_post_AG881_FF" "C_840149-005_post_AG120_FF" "C_840139-002_post_AG881_FF"
    [5] "C_840113-006_post_AG881_FF" "C_840149-006_post_AG120_FF" "C_840117-002_post_AG881_FF"

    > column_dend(expr_hm)

    $`3`
    'dendrogram' with 2 branches and 9 members total, at height 7.767023 
    
    $`1`
    'dendrogram' with 2 branches and 11 members total, at height 4.880324 
    
    $`2`
    'dendrogram' with 2 branches and 21 members total, at height 7.874246 
    
    > column_dend(expr_hm)$`3` %>% labels
    [1] "C_840117-011_post_AG881_FF"   "C_840149-005_post_AG120_FF"   "C_840139-002_post_AG881_FF"   "C_840113-006_post_AG881_FF"  
    [5] "C_840149-006_post_AG120_FF"   "C_840117-002_post_AG881_FF"   "C_840113-002_post_AG881_FF"   "C_840104-002_post_AG881_FF"  
    [9] "C_840149-003_post_AG120_FFPE"

Another angle:

    > column_dend(expr_hm)[[1]]
    'dendrogram' with 2 branches and 9 members total, at height 7.767023 
    > column_dend(expr_hm)[[1]]
    'dendrogram' with 2 branches and 9 members total, at height 7.767023 
    > column_dend(expr_hm)[[1]]
    'dendrogram' with 2 branches and 7 members total, at height 7.767023 
    > column_dend(expr_hm)[[1]]
    'dendrogram' with 2 branches and 9 members total, at height 7.767023 
    > column_dend(expr_hm)[[1]]
    'dendrogram' with 2 branches and 9 members total, at height 7.767023 
    > column_dend(expr_hm)[[1]]
    'dendrogram' with 2 branches and 9 members total, at height 7.767023 
    > column_dend(expr_hm)[[1]]
    'dendrogram' with 2 branches and 9 members total, at height 7.767023 
    > column_dend(expr_hm)[[1]]
    'dendrogram' with 2 branches and 7 members total, at height 7.767023

**Comment by jokergoo** [comment]
Please also attach the full code and better your dataset.
