### ISSUE TITLE
row_dend_reorder = FALSE, not reordering to original row position

### ISSUE THREAD

**Issue by ddh8602** [jokergoo/ComplexHeatmap#734]
Hello I am executing the following code, I only want to show the dendrogram for rows but without reordering them, I set cluster_columns = FALSE, row_dend_reorder = FALSE, but the order of rows is still different that from the original matrix. Am I doing something wrong or is it even possible to do what I am intending to do ? I appreciate the help.

Heatmap(rgi1, name = "coverage", column_title = "RGI", column_title_gp = gpar(fill = "gray", col = "white", fontsize = 4), col = col_fun, rect_gp = gpar(col = "white", lwd = 1), cluster_columns = FALSE, row_dend_reorder = FALSE, row_names_side = "right", width = unit(2.5, "cm"), column_names_side = "top", row_names_gp = gpar(fontsize = 2), column_names_gp = gpar(fontsize = 2, fontface = "italic"), cell_fun = function(j, i, x, y, width, height, fill) {if(rgi_id[i, j] > 0)grid.text(sprintf("%.1f", rgi_id[i, j]), x, y, gp = gpar(fontsize = 2))})

**Comment by jokergoo** [comment]
> but the order of rows is still different that from the original matrix. 

What do you mean by this? When you do row clustering, the row orders of course change. What kind of ordering do you expect? Maybe it is better that you also attach the plot here.

**Comment by ddh8602** [comment]
Yes you are right, I am sorry, I got confused, I must be spending to many nights on this project. My intention was to conserve the samples (rows) original positions but implementing a dendrogram showing the relationships between them, but now that I think about it, that would be wrong. 

Anyways I was able to make a very nice plot showing resistance genes and relationship between isolates for my project thanks to this package and you guys. 

You can erase this issue if you want as it is not a real issue anymore. Thanks.
