### ISSUE TITLE
The rowAnnotation issue with  setting row_cluster = T

### ISSUE THREAD

**Issue by Tangwenjie34** [jokergoo/ComplexHeatmap#736]
Hi Dr. @jokergoo ,
     I am going to draw  a heatmap like below picture with a row annotation and the row cluster using complexheatmap. 
![image](https://user-images.githubusercontent.com/83932955/117952100-67c5d380-b347-11eb-92ed-5e0ef03a73e4.png)
     But the parameter was so many that i could not determine which parameter that i should set.
     The Heatmap i draw like below:
![image](https://user-images.githubusercontent.com/83932955/117952730-03efda80-b348-11eb-85b5-89451e86d69b.png)

     The code lying below:
     ht_tumor = Heatmap(as.matrix(n),
                   cluster_rows = T,
                   cluster_columns = F,
                   show_column_names = F,
                   show_row_names = F,
                   gap = 2,
                   column_split = new_cluster,
                   heatmap_legend_param = list(
                     title = "Modified Expression",
                     title_position = "leftcenter-rot", #
                     at=c(-0.86,1.15), #
                     legend_height = unit(2, "cm") 
                   ),
                   top_annotation = top_color,
                   #left_annotation = left_color,
                   row_title = "Observations (Cells)",
                   row_title_side = c("right"),
                   column_title = "Genomic Region",
                   column_title_side = c("bottom"))

draw(ht_tumor, heatmap_legend_side = "left") 
    So, how should i do for this plot?
     Any advice would be appreciated.
     Best,
     hanhuihong

**Comment by jokergoo** [comment]
As what you have already done, define a `left_annotation`. Did you have any problem with using `left_annotation`?

**Comment by Tangwenjie34** [comment]
@jokergoo 
It would be complaint about below error if i set the left_annotation.
draw(ht_tumor, heatmap_legend_side = "left") 
error: Length of `labels` should be as same as number of slices. 
And the picture like below:
![image](https://user-images.githubusercontent.com/83932955/118385964-39e1d700-b646-11eb-98e6-bde5658b4369.png)
The  left_annotation information lying below:
> left_color
A HeatmapAnnotation object with 1 annotation
  name: heatmap_annotation_7 
  position: row 
  items: unknown 
  width: 7.78623888888889mm 
  height: 1npc 
  this object is subsetable

    name annotation_type color_mapping              width
 cluster    anno_block()               7.78623888888889mm

i constrct the left_annotation using below data and method:
color_row <- get_group_color_palette()(length(unique(pred.sample$copykat.pred)))
>color_row 
[1] "#8DD3C7" "#FFED6F"
type_cls<-factor(pred.sample$copykat.pred,levels = c('diploid','aneuploid'))
>type_cls
![image](https://user-images.githubusercontent.com/83932955/118386071-3733b180-b647-11eb-8053-5ffbba92c5a1.png)

left_color <- HeatmapAnnotation(
  cluster = anno_block(gp = gpar(fill = color_row), 
                       labels = levels(type_cls), 
                       labels_gp = gpar(cex = 0.9, col = "black")),which = 'row')

The matrix's rowname like below to draw heatmap.
![image](https://user-images.githubusercontent.com/83932955/118386097-6ba76d80-b647-11eb-8065-6b6cf8862cff.png)

And what wrong for this case?
Any adivce would be appreciated
Best,
hanhuihong

**Comment by jokergoo** [comment]
As the error message tells

> error: Length of labels should be as same as number of slices.

```r
left_color <- HeatmapAnnotation(
cluster = anno_block(gp = gpar(fill = color_row),
labels = levels(type_cls),
labels_gp = gpar(cex = 0.9, col = "black")),which = 'row')
```

length of `levels(type_cls)` should be the same as the number of row slices so that each row cluster can have a label to correspond.

**Comment by Tangwenjie34** [comment]
Thanks the advices.  As you said above, it was confused that how can i defined the row slice on this current matrix. because the heatmap can defintely cluster into two clusters. Base on this condition, how  the  left_color  can be construct ? the cells on the matrix row clearly distinguish into two clusters that include tumor and normal cells. As i set the slice, how can i make it? if the template that you can demonstrate, it would be fine to me.
Best works,
hanhuihong

**Comment by jokergoo** [comment]
You did clustering on rows, then you will know how many clusters you can have by looking at the shape of the row dendrogram, right?

**Comment by Tangwenjie34** [comment]
Hi @jokergoo, As the row dendrogram in this case, we can see that it was two slice of clusters. However, the rowname was cell barcodes not the two clusters label-diploid and aneuploid. so i am confused about the relation of correspondence?
under this circumstance, how can i make  the cell barcode and the label mentioned above a  correspondence?
Hope you kindly help to solve it.
Best,
hanhuihong

**Comment by Tangwenjie34** [comment]
Hi @jokergoo, As the row dendrogram in this case, we can see that it was two slice of clusters. However, the rowname was cell barcodes not the two clusters label-diploid and aneuploid. so i am confused about the relation of correspondence?
under this circumstance, how can i make  the cell barcode and the label mentioned above a  correspondence?
Hope you kindly help to solve it.
Best,
hanhuihong

**Comment by honghh2018** [comment]
Can anyone hear this ?
