### ISSUE TITLE
Row size in upset plot

### ISSUE THREAD

**Issue by asumann** [jokergoo/ComplexHeatmap#742]
I am not sure if it is directly related to ComplexHeatmap, but it is much appreciated if you can help. I use ```UpSet``` function. Row heights are too large in the plot, how can I adjsut it?

```
col_size = comb_size(deg_matrix)
row_size = set_size(deg_matrix)

upset_deg_genes <- UpSet(deg_matrix,
                         top_annotation = upset_top_annotation(
                           deg_matrix,
                           height = unit(5, "cm")
                         ),
                         right_annotation = upset_right_annotation(
                           deg_matrix,
                           width = unit(4, "cm")))

upset_deg_genes = draw(upset_deg_genes,padding = unit(c(1, 1, 1, 1), "cm"))  # 1cm margin on each side


col_od = column_order(upset_deg_genes)
row_od = row_order(upset_deg_genes)

decorate_annotation("intersection_size", {
  grid.text(col_size[col_od], 
            seq_len(length(col_size)), 
            unit(col_size[col_od], "native") + unit(1, "mm"), 
            default.units = "native", just = "bottom",
            gp = gpar(fontsize = 7))
})
```

[Rplot03.pdf](https://github.com/jokergoo/ComplexHeatmap/files/6484768/Rplot03.pdf)

**Comment by jokergoo** [comment]
You have set 5cm to the height of the top annotation. You can reduce this value.

**Comment by asumann** [comment]
Reducing the value makes the graph move up, doesn't affect the height of rows.
Height is set to 2 cm below.
[Rplot04.pdf](https://github.com/jokergoo/ComplexHeatmap/files/6487910/Rplot04.pdf)

**Comment by jokergoo** [comment]
Sorry, you mean the height of the "body"?

Then you can directly control it with the height of the figure. The height of the body is figure_height - barplot_height.

**Comment by jokergoo** [comment]
Or you can set `height` argument in `UpSet()` function:

```r
UpSet(..., height = unit(5, "mm")*4)
```

**Comment by asumann** [comment]
Yess, this works perfect!
