### ISSUE TITLE
Horizontal heatmap list align returning unmatched rows

### ISSUE THREAD

**Issue by vkartha** [jokergoo/ComplexHeatmap#743]
Hi, thank you for continuing to build on a very useful and powerful package! I recently ran into this issue when trying to align (horizontally) two heatmaps that have identical rows (and rownames). 

The main (first) heatmap is row-clustered, and the second uses the same entries as the ordering of the first, but is not clustered. When I plot these two separately, they appear to be in the correct order, however, when I try to align the two (using `ht_list <- ht1 + ht2` ; `draw(ht_list)`), the rows are jumbled for the second heatmap, and I get the following warning:

Warning message:
Row names of heatmap 2 is not consistent as the main heatmap (1) 

My assumption was that the second heatmap will always take the ordering of the first, regardless of whether and how you specify clustering the second heatmap?

For some reason I am unable to get the ordering to match, and if I try using the suggestion for "initializing" each heatmap separately using `draw`, then assembling them the same way as described above, I get this error:

Error: index out of bounds ("unit" subsetting)

**Comment by vkartha** [comment]
Hi, apologies, I only later realized this was because, even though the row (features) were the same in both input matrices, I was custom sorting the second (and I read another issue thread where you suggest to not do this because ComplexHeatmap expects the same input features when aligning two heatmaps, since it does the re-ordering internally. I think that was the issue? Looks like it works when I alphabetically sort the rownames (input) to the two heatmaps being made, and then assemble so that the second heatmap (right side) is clustered according to the first (left side)

**Comment by jokergoo** [comment]
You need always make sure the original row orders of the two matrices are the same (before clustering). Later in the heatmap list, the two matrices are reordered simultaneously.
