### ISSUE TITLE
Color row in Upset plot

### ISSUE THREAD

**Issue by asumann** [jokergoo/ComplexHeatmap#747]
Hi,
How can I color certain row in the upset plot? I have 4 comparisons, 1 is distinct from the other three. I want to make the separation obvious by putting a different color for this distinct array.

Thanks in advance.

**Comment by jokergoo** [comment]
Can you give me an example? Now it is only possible to set individual colors by columns because the lines that connect combination dots are vertical.

**Comment by asumann** [comment]
Something like [this](https://krassowski.github.io/complex-upset/articles/Examples_R.html#counts):
<img width="646" alt="Screen Shot 2021-06-01 at 2 18 14 PM" src="https://user-images.githubusercontent.com/40871058/120314780-43c13680-c2e4-11eb-8506-eb2720741a94.png">

**Comment by jokergoo** [comment]
Yes, you can set `bg_col`.

```r
UpSet(m, comb_col = "#0000FF", bg_col = c("#F0F0FF", "#FFF0F0"), bg_pt_col = "#CCCCFF")
```

![image](https://user-images.githubusercontent.com/449218/127844550-99dce882-0e3a-4d69-ad8e-45aac2e324d4.png)

**Comment by ibmbalu** [comment]
Hello,
Is it possible to have (only) the dots formatted in different colors instead of `bg_col`,? the connecting line could be in one colour as it is.
 I have gone through the reference but couldn't find any possible documentation.
Thanks in advance.
