### ISSUE TITLE
 takes forever to plot

### ISSUE THREAD

**Issue by JillFeng123** [jokergoo/ComplexHeatmap#749]
Hi,
My matrix is about 600*20. I tried both putting Heatmap(...) in my RScript and running it on the command line and directly running it on Console. It's been running for an hour and no plot has come out yet. Is this normal? I have 1 NA value (named "wt") on every row. I don't think this is the problem here because I don't see an error message. 
Thank you! Any advice would be appreciated.

**Comment by JillFeng123** [comment]
Here's my code:

library("ComplexHeatmap")

filename <- "LibC R1 + -.txt"

lib <- read.table(filename, sep="\t", quote="", na.string = "wt",header=TRUE)

head(lib)

dim(lib)

lib_matrix <- as.matrix(lib[ ,c(2:21)])

lib_matrix

class(lib)

class(lib_matrix)

save column for single amino acid locations for annotation
aminoacid_location <- data.frame(location = lib$X2.5.5)

aminoacid_location

Heatmap(lib_matrix, cluster_columns = FALSE)

**Comment by JillFeng123** [comment]
Here's my session info:
sessionInfo() R version 4.1.0 (2021-05-18) Platform: x86_64-apple-darwin17.0 (64-bit) Running under: macOS Big Sur 10.16

Matrix products: default LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale: [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages: [1] grid stats graphics grDevices utils datasets methods base

other attached packages: [1] ComplexHeatmap_2.8.0

loaded via a namespace (and not attached): [1] circlize_0.4.12 IRanges_2.26.0 matrixStats_0.58.0 codetools_0.2-18
[5] png_0.1-7 digest_0.6.27 foreach_1.5.1 crayon_1.4.1
[9] stats4_4.1.0 GlobalOptions_0.1.2 doParallel_1.0.16 S4Vectors_0.30.0
[13] GetoptLong_1.0.5 RColorBrewer_1.1-2 rjson_0.2.20 Cairo_1.5-12.2
[17] iterators_1.0.13 tools_4.1.0 parallel_4.1.0 compiler_4.1.0
[21] clue_0.3-59 colorspace_2.0-1 BiocGenerics_0.38.0 cluster_2.1.2
[25] BiocManager_1.30.15 shape_1.4.6

**Comment by jokergoo** [comment]
Please also send me the file so that I can test on it.

**Comment by JillFeng123** [comment]
> Please also send me the file so that I can test on it.

I have sent my file to you at jokergoo@gmail.com. Thank you for helping out!

**Comment by jokergoo** [comment]
You matrix is character. That is why drawing the heatmap is very slow:

```r
> str(lib_matrix)
 chr [1:601, 1:20] "0.439290442" "0.385187035" "-0.063188298" ...
 - attr(*, "dimnames")=List of 2
  ..$ : NULL
  ..$ : chr [1:20] "M" "L" "I" "V" ...
```

A quick check on your matrix shows there are characters like "qs" which make the columns as character. You can remove them and  convert the matrix into numeric:

```r
lib_matrix <- lib[ ,c(2:21)]
lib_matrix = lapply(lib_matrix, as.numeric)
lib_matrix = do.call(cbind, lib_matrix)
Heatmap(lib_matrix)
```

![image](https://user-images.githubusercontent.com/449218/120676823-b7a34080-c496-11eb-8e95-3f014abe018e.png)

**Comment by JillFeng123** [comment]
Thank you! That solved my problem

**Comment by JillFeng123** [comment]
Thank you! That solved my problem
