### ISSUE TITLE
Heatmap name not accepting expression or call

### ISSUE THREAD

**Issue by staemmlord** [jokergoo/ComplexHeatmap#75]
Hey there, 
While playing around with this package, I tried to get a subscript into the legend title.
Here is an MWE:

`
library(ComplexHeatmap)

mat <- matrix(1:9, 3, 3)
Heat<-Heatmap(mat,name=expression("log"[2]))

lgd = Legend(at = c("class1", "class2"), title = expression("log"[2]), type = "points", legend_gp = gpar(col = 2:3))
`

As you can see handing and expression over to name parameter of Heatmap() is not allowed because of the S4 Slot restriction. Creating the Legend and passing it to title does not work because  of a comparison.

Same applies to the second common way to use subscripts bquote(paste("log"[2])).

Is there a way to hack this into the matrix legend title? Or may this be a feature for the future?

Anyway: Thank you very much for this awesome Package!

**Comment by jokergoo** [comment]
Hi, thanks for this suggestion!

I have updated the package and now it is supported.  

Please note the heatmap names can only be pure text but you can modify the legend title 
by setting `heatmap_legend_param` option:

```{r}
mat <- matrix(1:9, 3, 3)
Heatmap(mat, heatmap_legend_param = list(title = expression("log"[2](x))))
```

<img width="394" alt="screen shot 2017-02-15 at 20 47 36" src="https://cloud.githubusercontent.com/assets/449218/22992529/42fc425a-f3c0-11e6-9e84-b9056cd776af.png">

Also row/column titles supports expression/call text as well now.

**Comment by flde** [comment]
Hello, is it also way to use expression with the rownames? I know how to do it in ggplot but can't find a option to rename the rows in Heatmap. That would be awesome...

**Comment by jokergoo** [comment]
You can use the argument `row_labels` to set complicated labels. See the last plot in this section:

https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#dimension-names

Also you can use the `gt_render()` function to construct even more complicated labels (https://jokergoo.github.io/ComplexHeatmap-reference/book/integrate-with-other-packages.html#gridtext-dimnames).

**Comment by flde** [comment]
Many thanks @jokergoo, that helped a lot!
