### ISSUE TITLE
How to remove white spaces in the expanded legend of ComplexHeatmap?

### ISSUE THREAD

**Issue by rrchai** [jokergoo/ComplexHeatmap#751]
I tried to make a custom legend using `ComplexHeatmap`. The purpose is to make a legend that has the same height of heatmap. I use `ComplexHeatmap::height()` to get the height of heatmap is `1npc`. The codes I used to make the legend: 

```
library(ComplexHeatmap)
library(circlize)
cols_fun <- colorRamp2(c(0, 100), c("white", "#1b3f61"))

lg <- Legend(col_fun = cols_fun, 
             title = "", legend_height = unit(1, "npc"),
             at = c(0, 20, 40, 60, 80, 100))
draw(lg)
```

However, there are white spaces in the legend if I increase the height:

<img width="100" alt="Screen Shot 2021-06-09 at 10 03 51 AM" src="https://user-images.githubusercontent.com/73901500/121371210-63231980-c90b-11eb-9ab9-97d26623ce97.png">

How to resolve it or is there a better way to make annotation legend to the same height as heatmap?

Thank you!

**Comment by jokergoo** [comment]
Thanks for reporting. I can reproduce it on my laptop. I have never tested this long legend, but I will definitely have a look!

**Comment by jokergoo** [comment]
This bug has been fixed.

![image](https://user-images.githubusercontent.com/449218/127914985-a287f5c4-4033-49b2-9b28-45edcc06422a.png)
