### ISSUE TITLE
What is the best way to add title of anno_text?

### ISSUE THREAD

**Issue by rrchai** [jokergoo/ComplexHeatmap#753]
Hi,

I used `anno_text` and `anno_block` to add annotation bar, but I notice there is no title/group names coming with the bar, like normal annotation. 

```
p <- round(sample(1:100, 10),2) *100
ha <-  rowAnnotation(Frequency  = anno_text(as.character(p), 
                                   rot = 0, 
                                   location = 0.5, 
                                   just = "center",
                                   gp = gpar(fill = ifelse(p > 50, "black", "white")
                                            col = ifelse(p > 50, "white", "black"), 
                                            border = "black")
                                   ))
```

For now, I need to add manually by checking the position of text each time i change total width of figure. Below code works for rowAnnotation with slice, but not for columnAnno or without slices. I believe there is better way to do it

```
decorate_annotation("Frequency", {
        grid.text("Frequency", y = -max_text_width("Frequency", gp = gpar(fontsize = 10))/1.5, rot =90)
      }, slice=4) # max slice
```

I would like to wrap up some codes to a function. That is why I need to auto add name to the bar. Is it possible to auto detect the scale of bar and auto add name of `anno_text` in the right position (at the beginning or end of the bar) regardless of heatmap scale or slices?

**Comment by jokergoo** [comment]
You can add `show_name = TRUE` in `anno_text()`.

```r
m = matrix(rnorm(100), 10)

ha = rowAnnotation(months = anno_text(month.name[1:10], show_name = TRUE),
  foo = 1:10,
  show_annotation_name = TRUE)

Heatmap(m) + ha
```

![image](https://user-images.githubusercontent.com/449218/127845573-5098afdf-887f-45de-b8b4-b31a7bd93fa9.png)

**Comment by jokergoo** [comment]
I've also added it in the ComplexHeatmap book.
