### ISSUE TITLE
Split rows by factor

### ISSUE THREAD

**Issue by JoKPro** [jokergoo/ComplexHeatmap#754]
Please provide example datasets and the code you use. It will help me to understand your problem and help you!
Hello,

I want to make gene expression heat map of selected genes in rows and samples in columns. 
This is the metadata table for the genes:

[new-marker-table-groups.txt](https://github.com/jokergoo/ComplexHeatmap/files/6643776/new-marker-table-groups.txt)

Now I would like to split the rows according to the groups in this table, but looking through the manual I couldn't find a way to do this with rows_split.

**Comment by jokergoo** [comment]
set `row_split = df$Group` (`df` is the data frame of your table).
