### ISSUE TITLE
Independent dendrograms for  rows  on a list of two heatmaps

### ISSUE THREAD

**Issue by JoseBSL** [jokergoo/ComplexHeatmap#756]
I have two heatmaps side by side  as done in the example of section four of the vignete https://jokergoo.github.io/ComplexHeatmap-reference/book/a-list-of-heatmaps.html 

The datasets are different and thus the clustering by column and rows are different too. I have two independent dendrograms per column but shared dendrogram by rows. Is there an option to have also independent dendrograms by rows for each of these two heatmaps? When I plot them separately I get the desired output but I would like to combine them in a panel. "auto_adjust = FALSE" helps me to have row numbers for both but I cannot find the option that allows me to have also independent dendrograms for rows too.

```
ht_list <- h_pol+h_plan
draw(ht_list, auto_adjust = FALSE)
```

**Comment by jokergoo** [comment]
Then they are actually "two heatmap figures". You can simply combine them with e.g. cowplot package.

```r
p1 = grid.grabExpr(draw(Heatmap(...)))
p2 = grid.grabExpr(draw(Heatmap(...)))

library(cowplot)
plot_grid(p1, p2)
```

**Comment by JoseBSL** [comment]
Thanks!! I tried cowplot before but not with grid.grabExpr. This does the job :)
