### ISSUE TITLE
extract_comb does not return anything

### ISSUE THREAD

**Issue by kmavrommatis** [jokergoo/ComplexHeatmap#757]
Hi,
I have a comb matrix comprised of 7 GRanges objects.
Making the matrix and plotting it works, but when It try to extract the names of the combinations using 

```
comb_elements = lapply(comb_name(m), function(nm) extract_comb(m, nm))
```
I get a list of NULL values.

single commands like 

```
 extract_comb( m , "1000100")
```

do not return anything.
ComplexHeatmap version is 2.6.2 running on R 4.0.0

Any advice on how to address this problem?
Thanks in advance for your help

**Comment by kmavrommatis** [comment]
Answering my question:
It appears that the combination matrix considers that GRanges objects as CompressedGRangesList. I had to convert the GRanges objects to a list  i.e.

```
as.list( c(  b$granges_list, d$granges_list  )) -> a
ComplexHeatmap::make_comb_mat(  a ) -> nm
```

**Comment by jokergoo** [comment]
OK, I will have a look. Maybe this is something due to new version of Bioconductor GenomicRanges package?

**Comment by jokergoo** [comment]
The problem is `GRangesList` object was not considered. Now it is supported.
