### ISSUE TITLE
increase space beetween annotation and heatmap

### ISSUE THREAD

**Issue by ShinyFabio** [jokergoo/ComplexHeatmap#758]
Hi I have an heatmap like this:
![Screenshot (54)](https://user-images.githubusercontent.com/78078351/122190448-1d79ca00-ce92-11eb-8094-803e994578fd.png)
 I want to increase the space beetween the left annotation and the heatmap. I already use the `HeatmapAnnotation()` function to draw the annotation and I saw that there is a parameter called `annotation_legend_param` but I didn't find the value to change.

**Comment by jokergoo** [comment]
If you type `ht_opt`, you will see there is a global option `ROW_ANNO_PADDING` that controls the space between row annotations and heatmaps. You can set as:

```r
ht_opt$ROW_ANNO_PADDING = unit(1, "cm")
```

before you make the heatmap.

**Comment by ShinyFabio** [comment]
Wow thanks it works like a charm! I got mad searching in the guide for an option like this. Maybe I was searching in the wrong chapters if is there.
