### ISSUE TITLE
HeatmapAnnotation: Color issue

### ISSUE THREAD

**Issue by kin182** [jokergoo/ComplexHeatmap#76]
Hi there,

I am new to ComplexHeatmap and I just encountered an issue with the color in HeatmapAnnotation that I could not figure out.

`res_color <- ( brewer.pal( 5, "Greens" ))`
`names(res.color) <- c("AC", "BC", "CC", "DC")`
`iv_color <- brewer.pal( 5, "Blues" )`
`names(iv_color) <- c("IV100", "IV200", "IV300", "IV400")`
`heatmap_color <- colorRampPalette(c("blue", "white", "yellow"))`

`df <- data.frame(Res=Data$Res,
IV=Data$IV)`

`ha <- HeatmapAnnotation(df=df, col = list(Heatmap=heatmap_color,
Res=res_color, IV=iv_color))`

I got an error `Error in HeatmapAnnotation(df = df, : elements in "col" should be named vectors.`

Then, I changed to 

`ha <- HeatmapAnnotation(df=df, col = list(type=c(Heatmap=heatmap_colors,
Res=res_color, IV=iv_color)))`

It got through, but I got a warning this time

`Warning message: In HeatmapAnnotation(df = df, : Following are defined in "col" while have no corresponding annotations:
type`

But the colors of the heatmap produced were not the ones that I defined. They were totally random.

Please let me know what I am missing here. Thanks!

**Comment by jokergoo** [comment]
Is `df$Heatmap` a vector containing continuous values?

You need to use `colorRamp2()` instead of `colorRampPalette()` to generate a color mapping function.

**Comment by kin182** [comment]
It worked! Thanks so much!
