### ISSUE TITLE
Correlation Matrix - Strange sample disposition

### ISSUE THREAD

**Issue by lucolotto** [jokergoo/ComplexHeatmap#762]
Hi there,
I am trying to create a correlation matrix for my gene expression data. I have used the code you kindly provided in our vignette. However I have added a few aesthetics modifications (such as passing the `column_split` and `row_split` parameters for improving the readability of the plot). I would like to plot a triangular correlation matrix (I don't want redundancy in the plot) so that half of the plot has the data, while the other half is white space. My "problem" arises when I introduce `column_split` and `row_split` because I obtain a strange graph (see picture). Can you help me figuring out why, instead of having as output a nice triangular matrix I have this weirdly shaped graph?

The code I am using it the following:

```
set.seed(123)
nr1 = 4; nr2 = 8; nr3 = 6; nr = nr1 + nr2 + nr3
nc1 = 6; nc2 = 8; nc3 = 10; nc = nc1 + nc2 + nc3
mat = cbind(rbind(matrix(rnorm(nr1*nc1, mean = 1,   sd = 0.5), nr = nr1),
                  matrix(rnorm(nr2*nc1, mean = 0,   sd = 0.5), nr = nr2),
                  matrix(rnorm(nr3*nc1, mean = 0,   sd = 0.5), nr = nr3)),
            rbind(matrix(rnorm(nr1*nc2, mean = 0,   sd = 0.5), nr = nr1),
                  matrix(rnorm(nr2*nc2, mean = 1,   sd = 0.5), nr = nr2),
                  matrix(rnorm(nr3*nc2, mean = 0,   sd = 0.5), nr = nr3)),
            rbind(matrix(rnorm(nr1*nc3, mean = 0.5, sd = 0.5), nr = nr1),
                  matrix(rnorm(nr2*nc3, mean = 0.5, sd = 0.5), nr = nr2),
                  matrix(rnorm(nr3*nc3, mean = 1,   sd = 0.5), nr = nr3))
)
rownames(mat) = paste0("gene_", seq_len(nr))
colnames(mat) = c(paste0("CTRL1_rep", c(1:6)), paste0("CTRL2_rep", c(1:6)), paste0("Treatment1_rep",c(1:6)), paste0("Treatment2_rep",c(1:6)))
cor_mat = cor(mat)
od = hclust(dist(cor_mat))$order
cor_mat = cor_mat[od, od]
row_groups = sub("_rep[[:digit:]]+","",rownames(cor_mat))
column_groups = sub("_rep[[:digit:]]+","",colnames(cor_mat))
nm = rownames(cor_mat)
col_fun = colorRamp2(c(max(cor_mat), (max(cor_mat)+min(cor_mat))/2, min(cor_mat)), c("#D17050", "grey", "#97BFDF"))

Heatmap(cor_mat, name = "correlation", col = col_fun, rect_gp = gpar(type = "none"),
        cluster_rows = FALSE, cluster_columns = FALSE,
        show_row_names = FALSE, show_column_names = TRUE,
        column_split = column_groups, row_split = row_groups,
        column_dend_reorder=FALSE,
        cell_fun = function(j, i, x, y, width, height, fill) {
          if(i == j) { #Labels along diagonal
            grid.text(nm[i], x = x, y = y, just="left") 
          } else if(i > j) {
            grid.rect(x = x, y = y, width = width, height = height, 
                      gp = gpar(col = "white", fill = NA))
            grid.rect(x=x, y=y, width = width, height = height, 
                      gp = gpar(fill = col_fun(cor_mat[i, j]), col = NA))
            grid.text(sprintf("%.2f", cor_mat[i, j]), x, y, gp = gpar(fontsize = 10))
          }
        },
        heatmap_legend_param = list(title = "Correlation"))

```
which results in this ("ugly") correlation matrix:
[Rplot01.pdf](https://github.com/jokergoo/ComplexHeatmap/files/6686171/Rplot01.pdf)

**Comment by lucolotto** [comment]
Can anyone help me figuring out why, when I introduce the `column_split = column_groups, row_split = row_groups` parameters, the `cell_fun` seems to stop working properly?

**Comment by jokergoo** [comment]
Sorry for the late reply. 

The reason here is you set `row_split` and `column_split` which change the ordering of the matrix. In the code, there is `if(i > j)` which means the order of the matrix should have exactly the same order as in the heatmap. You need to apply a second ordering to the variable `row_groups` or `column_groups`. Check the following code:

```r
## this is the second ordering
od2 = order(row_groups)
cor_mat = cor_mat[od2, od2]
row_groups = row_groups[od2]
column_groups = column_groups[od2]
nm = rownames(cor_mat)

Heatmap(cor_mat, name = "correlation", col = col_fun, rect_gp = gpar(type = "none"),
        cluster_rows = FALSE, cluster_columns = FALSE,
        show_row_names = FALSE, show_column_names = TRUE,
        column_split = column_groups, row_split = row_groups,
        cluster_row_slices = FALSE, cluster_column_slices = FALSE,
        column_dend_reorder=FALSE,
        cell_fun = function(j, i, x, y, width, height, fill) {
          if(i == j) { #Labels along diagonal
            grid.text(nm[i], x = x, y = y, just="left") 
          } else if(i > j) {
            grid.rect(x = x, y = y, width = width, height = height, 
                      gp = gpar(col = "white", fill = NA))
            grid.rect(x=x, y=y, width = width, height = height, 
                      gp = gpar(fill = col_fun(cor_mat[i, j]), col = NA))
            grid.text(sprintf("%.2f", cor_mat[i, j]), x, y, gp = gpar(fontsize = 10))
          }
        },
        heatmap_legend_param = list(title = "Correlation"))
```

![image](https://user-images.githubusercontent.com/449218/124267931-2d073d00-db39-11eb-9d77-e7d48b4709e2.png)

**Comment by lucolotto** [comment]
Thanks man, that is amazing! 
I was wondering two more things. 
1. As you can see from your image, the last name at the bottom right corner ("Treatment2_rep...") is cancelled cause it goes outside the margins of the plot. How do I fix it? 
2. Also if I wanted to rotate the row labels along the diagonal (I have seen I have to specify `rot=` inside `grid.text( )`) but I have seen that the name of the top left sample is "cancelled" by the name of the `column_split` parameter ("CTRL1"). Can I move the names of the `column_split` further up in the plot?

Thanks again
Luca

**Comment by jokergoo** [comment]
You can use `draw()` function to add more controls:

```r
ht = Heatmap(...)
draw(ht, padding = unit(c(1, 1, 1, 1), "cm"))
```

This means to add 1cm on the four sides of the plot. The order of the four values is bottom, left, top, right.

**Comment by lucolotto** [comment]
Thanks! I tried but it is not working for me.... even if I set `padding = unit(c(13, 13, 13, 13), "cm")` (which is an exaggeration on purpose) the plot is always the same....

**Comment by jokergoo** [comment]
Can you first close the plot and regenerate it? It should work:

![image](https://user-images.githubusercontent.com/449218/124285441-35b63e00-db4e-11eb-8cff-cd9953d08207.png)

**Comment by lucolotto** [comment]
It works now! 
Thanks a lot
Luca
