### ISSUE TITLE
UpSet - bg_col on transposed matrix does not work

### ISSUE THREAD

**Issue by mcarrara-bioinfo** [jokergoo/ComplexHeatmap#765]
Hello,
It appears to me that the bg_col option of the UpSet function, only works if the matrix is not transposed

`a <- data.frame(a = c(0,1,1), b = c(0,0,1))`
`m <- make_comb_mat(a)`
`UpSet(m, bg_col = "green")`
`UpSet(t(m), bg_col = "green")`

Is there something I am missing?

**Comment by jokergoo** [comment]
That was a bug. I haven't checked the scenario when the matrix is transposed. Now it is fixed. You can install the version from GitHub.

![image](https://user-images.githubusercontent.com/449218/124263277-54f3a200-db33-11eb-910b-e2a61f0a1563.png)
