### ISSUE TITLE
UpSet - rotate set names

### ISSUE THREAD

**Issue by mcarrara-bioinfo** [jokergoo/ComplexHeatmap#766]
Hello,

I am working with the Upset function and I am working with a transposed table, in order to have the sets as a top annotation and the intersections as a right annotation.
When I do this, however, the set name below the plot are vertical. I would like to rotate those 45/90 degrees so that they are more readable, but all examples I found deal with rotating labels and axis titles.
Is there a dedicated
 option (or even a workaround) for this?

`a <- data.frame(a = c(0,1,1), b = c(0,0,1))`
`m <- make_comb_mat(a)`
`UpSet(t(m))`
![Screenshot 2021-06-30 at 15 43 36](https://user-images.githubusercontent.com/19552826/123971737-99a7fd80-d9ba-11eb-9d11-62bd0d0af5d9.png)

Desired (changes highlighted in red)
![Screenshot 2021-06-30 at 15 43 36a](https://user-images.githubusercontent.com/19552826/123971818-a75d8300-d9ba-11eb-970b-971c56694f7d.png)

**Comment by jokergoo** [comment]
You can set:

```r
UpSet(t(m), column_names_rot = 0)
```
