### ISSUE TITLE
adding mark annotation

### ISSUE THREAD

**Issue by 2961461560** [jokergoo/ComplexHeatmap#767]
Hi, When I tried to add mark annotation with ComplexHeatmap, I find a bug(may be the wrong paraments I given).

```
row_ha1 = HeatmapAnnotation(df = colorbars[,c(1,3,2)], which = 'row')
mark_ha2 = rowAnnotation(foo = anno_mark(at = marks.rownum, labels = marks.new[,2],labels_gp = gpar(col = "black", fontsize = 20)))
Heatmap(data.atac.scale, border=F, cluster_rows = F, cluster_columns = F, col=rev(brewer.pal(n = 11, name ='RdBu')), show_row_names = F, column_names_rot = 45, column_names_gp = gpar(fontsize = 30),left_annotation =row_ha1,right_annotation = mark_ha2)
```
figure performed the comand above
![image](https://user-images.githubusercontent.com/34473055/124060513-c6fab700-da5f-11eb-91e8-9af2728236c2.png)

but I want to split rows, and then the order of mark annotation become wrong
```
Heatmap(data.atac.scale, border=F, cluster_rows = F, cluster_columns = F, col=rev(brewer.pal(n = 11, name ='RdBu')), show_row_names = F, column_names_rot = 45, column_names_gp = gpar(fontsize = 30),
row_split=data.frame(rep(c('M1','M2','M3','M4','M5'),c(2977,3736,2737,2594,4547))),row_gap = unit(5, "mm"),
left_annotation = row_ha1,right_annotation = mark_ha2)
```
![image](https://user-images.githubusercontent.com/34473055/124060604-fad5dc80-da5f-11eb-9f34-049fc51dede8.png)

who can help me solve this problem? thank you!

**Comment by jokergoo** [comment]
How do you tell "the order is wrong"? The row orders of the two plots are actually different. The first one is based on the complete set of rows and the second is based on individual row-groups.

If you want to validate it, you can use **InteractiveComplexHeatmap** package:

```r
library(InteractiveComplexHeatmap)
library(ComplexHeatmap)

Heatmap(data.atac.scale, border=F, cluster_rows = F, cluster_columns = F, col=rev(brewer.pal(n = 11, name ='RdBu')), show_row_names = F, column_names_rot = 45, column_names_gp = gpar(fontsize = 30),
row_split=data.frame(rep(c('M1','M2','M3','M4','M5'),c(2977,3736,2737,2594,4547))),row_gap = unit(5, "mm"),
left_annotation = row_ha1,right_annotation = mark_ha2)

htShiny()
```

**Comment by 2961461560** [comment]
Hi, I am so sorry to reply late. my results above are not show the bug clearly, so I  tried to use the guide example and commands to perform again.
```
m = matrix(rnorm(1000), nrow = 100)
rownames(m) = 1:100
ha = rowAnnotation(foo = anno_mark(at = c(1:4, 20, 60, 97:100), labels = month.name[1:10]))
Heatmap(m, name = "mat", cluster_rows = FALSE, right_annotation = ha,row_names_side = "left", row_names_gp = gpar(fontsize = 10))
```
the figure before split rows: 
![image](https://user-images.githubusercontent.com/34473055/124379101-96c54980-dce7-11eb-9516-675e48dc12f1.png)


```
Heatmap(m, name = "mat", cluster_rows = FALSE, right_annotation = ha,row_split=data.frame(rep(c('M1','M2','M3','M4','M5'),c(20,20,20,20,20))),row_gap = unit(5, "mm"),row_names_side = "left", row_names_gp = gpar(fontsize = 10))
```
the figure after split rows:
![image](https://user-images.githubusercontent.com/34473055/124379172-00455800-dce8-11eb-8d9a-882b91ca3ca3.png)

we can see from the figures above, the mark become wrong in the second figure. @jokergoo

**Comment by jokergoo** [comment]
Hi, I think you need to update the ComplexHeatmap. With the newest version, I works fine:

```r
fig2 <- Heatmap(m, name = "mat", cluster_rows = FALSE, right_annotation = ha,row_split=data.frame(rep(c('M1','M2','M3','M4','M5'),c(20,20,20,20,20))),row_gap = unit(5, "mm"),row_names_side = "left", row_names_gp = gpar(fontsize = 10))
```

![image](https://user-images.githubusercontent.com/449218/124431262-7097bc00-dd70-11eb-9cc7-4c67ff550c61.png)

**Comment by 2961461560** [comment]
ok, thank you @jokergoo
