### ISSUE TITLE
grid.grabExpr() captures wrong position of legend

### ISSUE THREAD

**Issue by jokergoo** [jokergoo/ComplexHeatmap#768]
![image](https://user-images.githubusercontent.com/449218/124604561-57276a80-de6b-11eb-94f8-8daae409169e.png)

**Comment by robertleafwagner** [comment]
setting wrap = TRUE in grid.grabExpr() appears to fix this

**Comment by jokergoo** [comment]
Thanks a lot for your reply! It fixes this problem.

However, the thing is in R 4.0.0 (or maybe earlier), there is no such problem but it only occurs in R 4.1.0. The function definitions of `grid.grabExpr()` are the same in the two versions, but maybe it changes in some internal functions. I need to look deeper.

But anyway, thanks again!
