### ISSUE TITLE
not clustering multiple top annotation rows 

### ISSUE THREAD

**Issue by anu-bioinfo** [jokergoo/ComplexHeatmap#77]
Hey,

I want to make a heatmap for gene expression with three top annotation rows, as shown in the first figure.

![eofolhajaajicdln](https://cloud.githubusercontent.com/assets/23100272/23505823/99c5242c-ff45-11e6-811a-95aece503182.png)
Following is my code:

    rld <- rlogTransformation(dds, blind=TRUE)
    mat<-as.matrix(assay(rld)[select,])
    row.names(mat)<-res[select,]$symbol
    mat_scaled <- t(apply(mat, 1, scale)
    colnames(mat_scaled)<-colnames(mat)
    time <- sub(".*_(0h|14w)_.*","\\1",Files)
    ha <- HeatmapAnnotation(df = data.frame(time = time,treat=sam$Treatment,resp=sam$R_NR))
    Heatmap(mat_scaled, name = "expression", km = 5, col = colorRamp2(c(-2, 0, 2), c("green", "white",   "red")),top_annotation=ha, top_annotation_height = unit(4, "mm"),cluster_columns=FALSE, show_column_names = TRUE)

The annotation table looks like this:

    Name   time treatment R_NR
    D5247      0h      VDZ       R
    E02874      0h     IFX       R
    E02877     14w     IFX      NR
    E02894      0h     IFX       R
    E02897     14w     VDZ     NR
    where VDZ is Vedolizumab and IFX is Infliximab

But I get the following plot, where the top annotation rows (apart from the first ) are clustered differently from the first figure.  
![temp1](https://cloud.githubusercontent.com/assets/23100272/23507247/59102b0a-ff4c-11e6-9a38-4c30609fb4ee.jpeg)

Can you please help me out here ? 

Thanks and Regards,

Anupam

**Comment by jokergoo** [comment]
How do you get the column order in the first heatmap? If you already have the column order (assuming it is stored in variable `column_order`),  you can assign it as:

```
Heatmap(..., column_order = column_order, cluster_columns = FALSE)
```

then there will be no column clustering.
