### ISSUE TITLE
two types of NA data

### ISSUE THREAD

**Issue by JillFeng123** [jokergoo/ComplexHeatmap#778]
Hi,
I have NA values in my dataset that I'd like to set gray, but I also have 1 wild type value for each row that I'd like to set black. Is it possible to set two types of NA values or specify colors for specific values? Thanks.

**Comment by jokergoo** [comment]
I think there are multiple ways. First question, how do you differentiate the "real NA" and "wild type NA"?

Let's say you encode the real NA as "NA" and wild type NA as "-1" (I assume all your values are positive), then, you can draw "-1" to black with `cell_fun`:

```r
Heatmap(mat, ..., na_col = "grey", 
    cell_fun = function(j, i, x, y, w, h, fill) {
        if(mat[i, j] == -1) grid.rect(x, y, w, h, gp = gpar(fill = "black"))
})
```

**Comment by JillFeng123** [comment]
Thank you. When I tried to do it your way, I encountered the following error: 
"Error_ in if (hc_matrix[i, j] == -5000) grid.rect(x, y, w, h,  : 
  missing value where TRUE/FALSE needed"
Does the function parse through all values of the matrix and throws an error when it sees an NA value? Please advise how to get around this error.

**Comment by jokergoo** [comment]
Then

```r
Heatmap(mat, ..., na_col = "grey", 
    cell_fun = function(j, i, x, y, w, h, fill) {
        if(!is.na(mat[i, j])) {
            if(mat[i, j] == -1) grid.rect(x, y, w, h, gp = gpar(fill = "black"))
        }
})
```

**Comment by JillFeng123** [comment]
Thank you!
