### ISSUE TITLE
Help in using vector indices in heatmap annotation colors

### ISSUE THREAD

**Issue by ssvbio** [jokergoo/ComplexHeatmap#780]
I am trying to reproduce this tutorial: https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html after I had problem with one of the heatmap drawing functions.

R version: 4.1.0, R studio Version 1.4.1717 ClusterProfiler:4.0.2  OS: Mint Uma

**Code that works**

```
ha = HeatmapAnnotation(bar = sample(letters[1:3], 10, replace = TRUE),
    col = list(bar = c("a" = "red", "b" = "green", "c" = "blue")))

draw(ha)

```

**Code that doesn't work**

```
lets=c("a',"b","c")
lets[1] prints "a"
ha = HeatmapAnnotation(bar = sample(letters[1:3], 10, replace = TRUE),
                       col = list(bar = c(lets[1] = "red", lets[2] = "green", lets[3] = "blue")))

```

Error

```
Error: unexpected '=' in:
"ha = HeatmapAnnotation(bar = sample(letters[1:3], 10, replace = TRUE),
                       col = list(bar = c(lets[1] ="
```
Is there a way to use vector indexing in assigning colors?

**Comment by jokergoo** [comment]
The expression `c(lets[1] = "red", lets[2] = "green", lets[3] = "blue")` is invalid. You can use `structure(c("red", "green", "blue"), names = lets)` instead.

**Comment by ssvbio** [comment]
Thank you for correction. I am closing the issue.
