### ISSUE TITLE
"partial argument match" warnings

### ISSUE THREAD

**Issue by bersbersbers** [jokergoo/ComplexHeatmap#781]
With
```r
options(showWarnCalls = TRUE)
options(
  warnPartialMatchArgs = TRUE,
  warnPartialMatchAttr = TRUE,
  warnPartialMatchDollar = TRUE,
)
```
I get these warnings:
```
3: In seq.default(at[i], at[i + 1], length = round((at[i + 1] - at[i])/(at[k] -  :
  partial argument match of 'length' to 'length.out'
Calls: <Anonymous> ... vertical_continuous_legend_body -> unlist -> lapply -> FUN -> seq
4: In seq.default(at[i], at[i + 1], length = round((at[i + 1] - at[i])/(at[k] -  :
  partial argument match of 'length' to 'length.out'
Calls: <Anonymous> ... vertical_continuous_legend_body -> unlist -> lapply -> FUN -> seq
5: In seq.default(at[i], at[i + 1], length = round((at[i + 1] - at[i])/(at[k] -  :
  partial argument match of 'length' to 'length.out'
Calls: <Anonymous> ... vertical_continuous_legend_body -> unlist -> lapply -> FUN -> seq
6: In seq.default(0, 1, length = length(colors) + 1) :
  partial argument match of 'length' to 'length.out'
Calls: <Anonymous> ... .local -> Legend -> vertical_continuous_legend_body -> seq
7: In seq.default(at[i], at[i + 1], length = round((at[i + 1] - at[i])/(at[k] -  :
  partial argument match of 'length' to 'length.out'
Calls: <Anonymous> ... vertical_continuous_legend_body -> unlist -> lapply -> FUN -> seq
8: In seq.default(at[i], at[i + 1], length = round((at[i + 1] - at[i])/(at[k] -  :
  partial argument match of 'length' to 'length.out'
Calls: <Anonymous> ... vertical_continuous_legend_body -> unlist -> lapply -> FUN -> seq
9: In seq.default(at[i], at[i + 1], length = round((at[i + 1] - at[i])/(at[k] -  :
  partial argument match of 'length' to 'length.out'
Calls: <Anonymous> ... vertical_continuous_legend_body -> unlist -> lapply -> FUN -> seq
10: In seq.default(0, 1, length = length(colors) + 1) :
  partial argument match of 'length' to 'length.out'
Calls: <Anonymous> ... .local -> Legend -> vertical_continuous_legend_body -> seq
```

These seem to be related to
https://github.com/jokergoo/ComplexHeatmap/blob/7e066ad5c86ec5ba3b75f01ec6b72caa7510e743/R/grid.Legend.R#L755-L758
and
https://github.com/jokergoo/ComplexHeatmap/blob/7e066ad5c86ec5ba3b75f01ec6b72caa7510e743/R/grid.Legend.R#L762
and
https://github.com/jokergoo/ComplexHeatmap/blob/7e066ad5c86ec5ba3b75f01ec6b72caa7510e743/R/grid.Legend.R#L961-L964
and
https://github.com/jokergoo/ComplexHeatmap/blob/7e066ad5c86ec5ba3b75f01ec6b72caa7510e743/R/grid.Legend.R#L968

**Comment by jokergoo** [comment]
Thank you!! I don't know why `R CMD check` does not warn it any more, but I will change it!

**Comment by bersbersbers** [comment]
I guess this is because these warnings do not appear on a fresh R installation, you have to enable the above options to eat the warnings. But thanks already for fixing them :)

**Comment by bersbersbers** [comment]
Here's a few more:
- https://github.com/jokergoo/ComplexHeatmap/blob/5c6415bac06a728fb2ff994c44384f124354b8fc/R/AnnotationFunction-function.R#L1052
- https://github.com/jokergoo/ComplexHeatmap/blob/5c6415bac06a728fb2ff994c44384f124354b8fc/R/AnnotationFunction-function.R#L1075
- https://github.com/jokergoo/ComplexHeatmap/blob/5c6415bac06a728fb2ff994c44384f124354b8fc/R/AnnotationFunction-function.R#L1110
- https://github.com/jokergoo/ComplexHeatmap/blob/5c6415bac06a728fb2ff994c44384f124354b8fc/R/AnnotationFunction-function.R#L1133
- https://github.com/jokergoo/ComplexHeatmap/blob/5c6415bac06a728fb2ff994c44384f124354b8fc/R/AnnotationFunction-function.R#L1268
- https://github.com/jokergoo/ComplexHeatmap/blob/5c6415bac06a728fb2ff994c44384f124354b8fc/R/AnnotationFunction-function.R#L1798
- https://github.com/jokergoo/ComplexHeatmap/blob/5c6415bac06a728fb2ff994c44384f124354b8fc/R/AnnotationFunction-function.R#L2095

**Comment by jokergoo** [comment]
Thanks!
