### ISSUE TITLE
dendextend::color_branches() does not work

### ISSUE THREAD

**Issue by blueskypie** [jokergoo/ComplexHeatmap#785]
The row dendrogram disappeared!

``` R
library(dendextend)
library(ComplexHeatmap)
mat=matrix(rnorm(100),10)
dend = hclust(dist(mat))
dend = color_branches(dend, k = 2)
Heatmap(mat, name = "mat", cluster_rows = dend)
sessionInfo()
```
```
R version 4.0.3
other attached packages:
[1] ComplexHeatmap_2.9.3 dendextend_1.15.1
```
![image](https://user-images.githubusercontent.com/16052330/128098559-80ca141a-93ff-4006-81d3-f45c433a3244.png)

**Comment by jokergoo** [comment]
```r
dend = hclust(dist(mat))
dend = as.dendrogram(dend). ## <<-- here
dend = color_branches(dend, k = 2)
Heatmap(mat, name = "mat", cluster_rows = dend)
```

`dend` needs to be a `dendrogram` object.

**Comment by blueskypie** [comment]
Thank you so much for the quick response! Could you update the [relevant code](https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#spilt-by-dendrogram) in the document?

**Comment by jokergoo** [comment]
Maybe it worked for the old versions, but it is always safe to explicitly convert to `dendrogram` object. 

Yes, I will update it. Thanks!

**Comment by blueskypie** [comment]
Yes, it did work for the old version! Thanks!
