### ISSUE TITLE
Is there a way to change show_annotation_name property for existing HeatmapAnnotation object?

### ISSUE THREAD

**Issue by kotliary** [jokergoo/ComplexHeatmap#786]
Here is a simple example:
```
m = matrix(rnorm(100), 10)
foo = runif(10)
bar = sample(c("f", "m"), 10, replace = TRUE)
ha = HeatmapAnnotation(foo = foo, bar = bar, show_annotation_name = F)
ha2 = HeatmapAnnotation(foo = foo, bar = bar, show_annotation_name = T)
hm = Heatmap(m, name = "mat", top_annotation = ha)
hm2 = Heatmap(m^2, name = "mat2", top_annotation = ha2)
draw(hm + hm2)
```
So, instead of creating `ha` and `ha2` separately I'd like to make just `ha`, and then for the second heatmap change its `show_annotation_name` property to TRUE. Is it possible?

**Comment by jokergoo** [comment]
I will think about it.

Currently you can only do it manually.

**Comment by kotliary** [comment]
Thank you for the response.
Manually - do you mean by creating a new HeatmapAnnotation object from scratch (duplicating the code)?

I'm also thinking that it would be nice to be able to edit the HeatmapAnnotation object in general - add a new annotation to the list, change axis parameters, etc. I'm dealing with two Heatmaps that has the same samples as columns and share most of annotations that are pretty complex. Currently I have to copy-paste the whole HeatmapAnnotation code.

**Comment by jokergoo** [comment]
Yes, I mean you need to create the HeatmapAnnotation object twice.

Of course you can edit the HeatmapAnnotation object. The parameter is stored in :

```r
ha = HeatmapAnnotation(foo = 1:10)
ha@anno_list[["foo"]]@name_param
```

In your case, it will be:

```r
ha2 = ha1 = HeatmapAnnotation(foo = 1:10)
ha1@anno_list[["foo"]]@name_param = FALSE

Heatmap(m1, top_annotation = ha1) + Heatmap(m2, top_annotation = ha2)
```

**Comment by kotliary** [comment]
Yes, this is exactly what I want. Thanks!
