### ISSUE TITLE
Error in x[[1]] : subscript out of bounds

### ISSUE THREAD

**Issue by MilouArts** [jokergoo/ComplexHeatmap#787]
I updated R/Rstudio and installed the latest version of this package, and I'm getting this error:

Error in x[[1]] : subscript out of bounds

It already appears when using the basic Heatmap(map):

> Heatmap(mat)
An object of class "Heatmap"
Slot "name":
[1] "matrix_3"

Slot "matrix":
          column1     column2    column3     column4    column5     column6    column7
row1   0.90474160 -0.35229823  0.5016096  1.26769942  0.8251229  0.16215217 -0.2869867
row2   0.90882972  0.79157121  1.0726316  0.01299521  0.1391978  0.46833693  1.2814948
row3   0.28074668  0.02987497  0.7052595  1.21514235  0.1747267  0.20949120 -0.6423579
row4   0.02729558  0.75810969  0.5333504 -0.49637424 -0.5261114  0.56724357  0.8127096
row5  -0.32552445  1.03264652  1.1249573  0.66695147  0.4490584  1.04236865  2.6205200
row6   0.58403269 -0.47373731  0.5452483  0.86824798 -0.1976372 -0.03565404 -0.3203530
row7   0.39510341  1.14911380  0.2112660  0.41004688  1.2596089  1.63159259  0.8137806
row8   2.19872624  0.55492407  0.7680064  0.79316174  0.6826259 -0.28719434 -0.2205816
row9   1.02709051 -0.12804610  0.4557174  0.36717419  0.2767214  0.22575203 -0.5120644
row10  0.68908389  1.31828484  1.5012414  1.00747159  0.6886940  0.82517481  1.4884867
row11  1.00556459  0.35379418  1.4126899 -0.32157448  0.9855792 -0.65850807 -0.3615330
row12  0.39047481  0.05882330  0.3280414 -0.33373755  0.8421547 -0.48092832  0.0528381
row13  1.08419194 -0.24527872  1.2992544  0.69301328  0.9248215  0.72227543 -0.4248522
row14  1.18921195 -0.35860908  1.0722379  0.72236082  1.3782032 -0.39076824  0.3089929
row15  1.81678421 -0.18182865  1.2550663  0.95352949  1.3353480 -0.09146269 -0.6181366
row16  0.26948083  1.18448226 -0.1754513  0.55831864  0.3996095  0.90141205  0.4754115
row17  0.92846151  1.25843102  1.4334259  0.28636036 -0.1820187  0.88186022  1.5263557
row18  1.70838668  0.89230975  0.5104918  0.05339621  0.9328897  1.55496014  0.3699224
          column8    column9    column10   column11    column12    column13    column14
row1   0.68032622 -0.1629658  0.82545373  0.7821773 -0.49625358 -0.08952580 -0.35520328
row2   0.38998256 -0.3473535  1.35089217  1.1183375  2.05005447  1.37702689 -0.77437640
row3  -0.31395304  0.2175907 -0.29730863  0.4322058 -0.25803192 -0.56865181 -0.51321045
row4  -0.01427338  1.0844780  0.24266617  0.8783874  1.38452112  0.83765704  0.10797078
row5   0.75823530 -0.2333277  1.34395839  0.8517620  0.85980233  1.99860669 -0.50928769
row6   1.05534136  0.7771690  0.45949830  0.2550648 -0.02778098 -0.21124842  0.01669142
row7  -0.04168453 -0.1039586  0.86890126  1.5187870  0.35648476  0.75035399  0.29230687
row8   0.49675193 -0.1102433 -0.20716997  1.2380666  0.05962262 -0.39431099  1.09366650
row9   1.89345657  1.1799069  0.30398216  1.1500993  0.15057668  0.56566861  0.76360430
row10  0.12665926 -0.6326982  0.21392792  1.1505880  1.39386942  1.10722265  0.06192712
row11  0.27419848  0.1658910 -0.23812345  1.6892851  0.12184371 -0.25109936  0.76630531
row12  1.20038573  0.6565736 -0.19011326  0.2394413 -0.80894135  0.02061646  1.24892524
row13  0.72207943  1.6120409 -0.28767348  0.5235772  0.25970360 -1.02662361  1.35067795
row14 -0.30012979  0.5744038 -0.02701406  1.1730518  0.83784847  0.95118091  0.12844185
row15  0.11936587  0.5484195 -0.39430142  1.2281182  0.61623794  0.74803033 -0.11785018
row16  0.68430114 -0.5615543  0.73454674  0.1992466  0.49581170  0.55231832 -0.25116173
row17 -0.02143523  0.6039810  0.19923191 -0.3633652  1.16610129  1.04729176  0.18981974
row18 -0.11288549 -0.2014424  0.26912221  0.3239768  0.94027370  0.34459923 -0.16660369
         column15    column16    column17    column18    column19    column20     column21
row1   0.10726941  0.96322199 -0.39245223 -0.18780144  1.08736320  0.71321986 -0.185330016
row2   0.98296637  0.23854381 -0.53589561  1.30035441  0.14237891  0.44716433  0.447562831
row3  -0.04515980  0.82272880 -0.02251386  0.24272999  1.09511516  0.58526119  0.192640201
row4   0.45200187  0.81648036  0.02650211  0.40725996 -0.02625664  0.95569565  0.344320127
row5   0.77081733 -0.09421702 -1.15458444  1.27159703  0.60599022  0.83041015 -0.190235501
row6  -0.32597495  0.54460361  0.89101254  0.36997376  0.81537706  1.27379053  1.857532493
row7   2.06422595  0.84187276  0.15176432  0.37436432  0.12365552 -0.12932431  0.439066744
row8   0.44232525  0.61292754 -0.12334594 -0.05048744  0.99284629  0.67647718  0.090651740
row9   0.03898042  0.98126398  0.63555439 -0.72194658 -0.26645100 -0.37826370  0.367469383
row10  0.62933195  0.46958902  0.22410489  0.69441704  0.03073065  1.34221785  0.410790541
row11 -0.50779629  1.42286577 -0.17377130 -0.67992035  0.10485938 -0.07882317 -0.069445681
row12  0.92193100  0.30561007  0.46608815 -0.73032004  1.04039975  1.64653949  1.064643868
row13  0.11769329  0.92250650  0.48699778  0.95455178  0.44318005  0.43342452  1.230458103
row14 -0.36926385  0.41567429 -0.83397097 -0.28093818  0.47249148  1.75195030  0.322188274
row15  0.97764698  0.36965856 -0.47580928 -0.33238472  1.01727553  1.44212541  0.002882093
row16  1.15524037  0.50364505  1.02504234  1.65620649  0.66558959  1.10905431 -0.030955855
row17  1.01889420  1.16775881  0.46113373  2.09940517  0.28142023  0.61871514  0.276958827
row18  1.21826174  1.00877932 -0.24551558  0.86742747 -0.50710525 -0.16938714 -0.152981332
         column22   column23   column24
row1  -0.14238650  0.6407669  1.3266288
row2  -0.31251963  0.7057150  0.8120937
row3   0.51278568  1.6361334  1.1339175
row4   0.07668656  1.7857291  0.5280084
row5  -0.14753574  1.0123366  0.2140750
row6   0.88491126  0.5670193  0.5372756
row7  -0.84334666  0.4834819  0.9795027
row8   0.50286926  1.8897515  0.7305954
row9   1.03525420  1.3204231  0.5123375
row10  0.41889352 -0.7329491  1.3355274
row11 -0.35460038  1.1432122  1.1136460
row12  0.71976218  0.5590723  0.5874014
row13  1.77935416  0.6105097  0.7140834
row14 -0.61035886  0.7748307  0.9386457
row15 -0.34400431  1.0631579  1.2461143
row16  0.62690746  0.8255966 -0.3766187
row17 -0.56906847  0.3973504  0.4740090
row18  0.21323211  0.6368832  0.5496638

Slot "matrix_param":
$row_km
[1] 1

$row_km_repeats
[1] 1

$row_gap
[1] 1mm

$column_km
[1] 1

$column_km_repeats
[1] 1

$column_gap
[1] 1mm

$jitter
[1] FALSE

$gp
$col
[1] NA

$lineheight
[1] 0.9

$border
[1] NA

$border_gp
$col
[1] "black"

$width
[1] 24null

$height
[1] 18null

Slot "matrix_color_mapping":
Continuous color mapping:
name: matrix_3 
default breaks:
[1] -2 -1  0  1  2

colors:
[1] "#1D0AFFFF" "#AC85FAFF" "#EEEEEEFF" "#FF977CFF" "#FF1406FF"

Slot "matrix_legend_param":
$title
[1] "matrix_3"

Slot "row_title":
character(0)

Slot "row_title_param":
$rot
[1] 90

$side
[1] "left"

$gp
$fontsize
[1] 13.2

$lineheight
[1] 0.9

$just
[1] 0.5 0.0

Slot "column_title":
character(0)

Slot "column_title_param":
$rot
[1] 0

$side
[1] "top"

$gp
$fontsize
[1] 13.2

$lineheight
[1] 0.9

$just
[1] 0.5 0.0

Slot "row_dend_list":
Error in x[[1]] : subscript out of bounds

**Comment by jokergoo** [comment]
How about restart your R session?
