### ISSUE TITLE
Is there way to output split column information as a matrix?

### ISSUE THREAD

**Issue by Yale73** [jokergoo/ComplexHeatmap#789]
Hi ComplexHeatmap team,

Thanks for such a powerful package and I really enjoy using it. I just curious whether I can output the split column information.  Take an example. Like the following heatmap, I split the column into 20 and I want to output an excel/csv file with each column (11), genes within the column (11), the clustering coefficient, etc.
![image](https://user-images.githubusercontent.com/50378244/128931149-0de83910-a101-46cf-b32c-b07584e3db08.png)

Thanks,
Yale

**Comment by jokergoo** [comment]
You can get this information by:

```r
ht = Heatmap(...)
ht = draw(ht)
```

Then the grouping information can be retrieved by:

```r
column_order(ht)
```

This is a list of 20 vectors where each vector contains the column indices.
