### ISSUE TITLE
I can't install ComplexHeatmap

### ISSUE THREAD

**Issue by Shalomvivy** [jokergoo/ComplexHeatmap#792]
> install.packages("ComplexHeatmap")
Warning in install.packages :
  package ‘ComplexHeatmap’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

> if (!requireNamespace("BiocManager", quietly=TRUE))
+   install.packages("BiocManager")
> BiocManager::install("ComplexHeatmap") #This code ran lowly and still didn't work
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for
details

replacement repositories:
    CRAN: https://mirrors.sjtug.sjtu.edu.cn/cran/

Warning: unable to access index for repository https://bioconductor.org/packages/3.13/books/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.13/books/src/contrib/PACKAGES'
Bioconductor version 3.13 (BiocManager 1.30.16), R 4.1.0 (2021-05-18)
Installing package(s) 'BiocVersion', 'ComplexHeatmap'
还安装相依关系‘BiocGenerics’, ‘S4Vectors’, ‘clue’, ‘Cairo’, ‘IRanges’

trying URL 'https://bioconductor.org/packages/3.13/bioc/bin/windows/contrib/4.1/BiocGenerics_0.38.0.zip'
Content type 'application/zip' length 796381 bytes (777 KB)
downloaded 777 KB

trying URL 'https://bioconductor.org/packages/3.13/bioc/bin/windows/contrib/4.1/S4Vectors_0.30.0.zip'
Content type 'application/zip' length 2448942 bytes (2.3 MB)
downloaded 44 KB

trying URL 'https://mirrors.sjtug.sjtu.edu.cn/cran/bin/windows/contrib/4.1/clue_0.3-59.zip'
Content type 'application/zip' length 1147247 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://mirrors.sjtug.sjtu.edu.cn/cran/bin/windows/contrib/4.1/Cairo_1.5-12.2.zip'
Content type 'application/zip' length 1041048 bytes (1016 KB)
downloaded 1016 KB

trying URL 'https://bioconductor.org/packages/3.13/bioc/bin/windows/contrib/4.1/IRanges_2.26.0.zip'
Content type 'application/zip' length 2662291 bytes (2.5 MB)
downloaded 836 KB

trying URL 'https://bioconductor.org/packages/3.13/bioc/bin/windows/contrib/4.1/BiocVersion_3.13.1.zip'
Content type 'application/zip' length 9399 bytes
downloaded 9399 bytes

trying URL 'https://bioconductor.org/packages/3.13/bioc/bin/windows/contrib/4.1/ComplexHeatmap_2.8.0.zip'
Content type 'application/zip' length 3287609 bytes (3.1 MB)
downloaded 684 KB

package ‘BiocGenerics’ successfully unpacked and MD5 sums checked
Error in read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) : 
  cannot open the connection
In addition: Warning messages:
1: In file(con, "r") : InternetOpenUrl failed: '操作超时'
2: In readRDS(dest) : lzma decoding result 10
3: In .inet_warning(msg) :
  unable to access index for repository https://bioconductor.org/packages/3.13/data/experiment/bin/windows/contrib/4.1:
  cannot open URL 'https://bioconductor.org/packages/3.13/data/experiment/bin/windows/contrib/4.1/PACKAGES'
4: In .inet_warning(msg) :
  downloaded length 45056 != reported length 2448942
5: In .inet_warning(msg) :
  downloaded length 856064 != reported length 2662291
6: In .inet_warning(msg) :
  downloaded length 700416 != reported length 3287609
7: In .inet_warning(msg) : error 1 in extracting from zip file
8: In .inet_warning(msg) :
  cannot open compressed file 'S4Vectors/DESCRIPTION', probable reason 'No such file or directory'

I used to intalled successfully, but after I update my R version, I tried to install ComplexHeatmap several times but I can't.
I need your help! I'll be very appreciated if you can help me !

**Comment by jokergoo** [comment]
Can you restart your R session? Or you can first remove the **S4Vectors** package and reinstall it?

You can also install ComplexHeatmap by `devtools::install_github("jokergoo/ComplexHeatmap")`.

**Comment by Shalomvivy** [comment]
> 
> 
> Can you restart your R session? Or you can first remove the **S4Vectors** package and reinstall it?
> 
> You can also install ComplexHeatmap by `devtools::install_github("jokergoo/ComplexHeatmap")`.

Sorry to bother you again. I reinstalled R session but still didn't help. When I used`devtools::install_github("jokergoo/ComplexHeatmap")`, there was a new error.
> devtools::install_github("jokergoo/ComplexHeatmap")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for 91.240.163.66. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2021-08-18 00:12:34 UTC

  To increase your GitHub API rate limit
  - Use `usethis::browse_github_pat()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.

**Comment by Shalomvivy** [comment]
I think maybe the package ‘ComplexHeatmap’ is not available for this version of R?  For my friend can't install it, too .

**Comment by jokergoo** [comment]
Have you seen the message

```
Use usethis::browse_github_pat() to create a Personal Access Token.
Use usethis::edit_r_environ() and add the token as GITHUB_PAT
```

You can run these two commands. It will lead you to set up github tokens.

**Comment by Shalomvivy** [comment]
> 
> 
> Have you seen the message
> 
> ```
> Use usethis::browse_github_pat() to create a Personal Access Token.
> Use usethis::edit_r_environ() and add the token as GITHUB_PAT
> ```
> 
> You can run these two commands. It will lead you to set up github tokens.

Yes, I did. But still didn't work. I'm sorry to interrupt you.

**Comment by jokergoo** [comment]
How did you update your R session? If you also have problems with installing other packages. I would suggest to completely uninstall R and re-install everything.

**Comment by Shalomvivy** [comment]
> 
> 
> How did you update your R session? If you also have problems with installing other packages. I would suggest to completely uninstall R and re-install everything.

Thank you for your advice. I updated my R session by https://cran.r-project.org，and didn't have problems with installing other packages. Thank you again for your time.
