### ISSUE TITLE
Different colors applied to a part of text in row labels

### ISSUE THREAD

**Issue by kotliary** [jokergoo/ComplexHeatmap#793]
Here is a simple example:
```
m = matrix(rnorm(25), 5)
rownames(m) = paste0("black", 1:5, ", red", 1:5, ", blue", 1:5)
hm = Heatmap(m)
draw(hm)
```
I'd like to have all "reds" in red color, all "blues" in blue color, and the rest in black.
I wonder if it's possible to do. Maybe with some HTML markups?

**Comment by kotliary** [comment]
Something like [this ](https://blog.revolutionanalytics.com/2009/01/multicolor-text-in-r.html)maybe?

**Comment by jokergoo** [comment]
Yes, you can use `gt_render()` which internally renders the text by **gridtext** package. See more details in https://jokergoo.github.io/ComplexHeatmap-reference/book/integrate-with-other-packages.html#gridtext-dimnames.

```r
m = matrix(rnorm(25), 5)
row_labels = glue::glue("black{1:5}, <span style='color:red'>red</span>{1:5}, <span style='color:blue'>blue</span>{1:5}")
Heatmap(m, row_labels = gt_render(row_labels))
```

![image](https://user-images.githubusercontent.com/449218/129784692-ee91e418-97e2-4068-b0bd-8684c34ac1f3.png)

**Comment by kotliary** [comment]
Cool! Thanks a lot! I'll try it.
