### ISSUE TITLE
Horizontal legend is not showing expression()

### ISSUE THREAD

**Issue by jmw86069** [jokergoo/ComplexHeatmap#796]
I am using ComplexHeatmap version 2.9.3 and was trying to make a horizontal legend with a mathematical `expression()`

The following from the bookdown docs, vertical works fine:

```R
col_fun = circlize::colorRamp2(c(0, 0.5, 1), c("blue", "white", "red"))
lgd = Legend(col_fun = col_fun,
   title = expression(hat(beta) == (X^t * X)^{-1} * X^t * y),
   at = c(0, 0.25, 0.5, 0.75, 1),
   labels = expression(alpha, beta, gamma, delta, epsilon))
plot(NULL, xlim=c(0, 1), ylim=c(0, 1))
draw(lgd)
```
<img width="95" alt="image" src="https://user-images.githubusercontent.com/93830/130626512-d5f88760-2f24-480e-9dde-caa166480dae.png">

The same with `direction="horizontal"` prints the words and not the math symbols:

```R
col_fun = circlize::colorRamp2(c(0, 0.5, 1), c("blue", "white", "red"))
lgd = Legend(col_fun = col_fun,
   title = expression(hat(beta) == (X^t * X)^{-1} * X^t * y),
   at = c(0, 0.25, 0.5, 0.75, 1),
   direction = "horizontal",
   labels = expression(alpha, beta, gamma, delta, epsilon))
plot(NULL, xlim=c(0, 1), ylim=c(0, 1))
draw(lgd)
```
<img width="248" alt="image" src="https://user-images.githubusercontent.com/93830/130626557-bec9c52f-353c-4d5c-bdb0-196f2ad74485.png">

It's a small thing, and I will use a vertical legend for the time being. No worries!

If I haven't said it enough, this package is a joy to use! The capabilities are really clever, and well-designed.

**Comment by jokergoo** [comment]
Sorry, horizontal legends were less tested, so there might be problems. Now it is fixed. I just accidentally converted all legend labels to characters.

![image](https://user-images.githubusercontent.com/449218/133985990-91528614-e433-4f8f-b7c5-d2e30059efd7.png)

You can update from GitHub.
