### ISSUE TITLE
How to sorted the columns of oncoprint based on the same alteration type.

### ISSUE THREAD

**Issue by lincj1994** [jokergoo/ComplexHeatmap#798]
![image](https://user-images.githubusercontent.com/60967283/131314907-28af5fd3-e48c-4537-8f31-cfb98f815241.png)

HI. In the help page of oncoPrint, it goes that by default the columns are sorted to show the mutual exclusivity of alterations. I dont know how to draw the oncoprint to cluster the same alteration types. Something below was what I wanted. Thank you.
![image](https://user-images.githubusercontent.com/60967283/131315058-6279d312-5f55-4aa5-848a-37f42acad24c.png)
![image](https://user-images.githubusercontent.com/60967283/131315071-d6126f9d-c7e9-418e-b7c3-42a4a77a2a6b.png)

**Comment by jokergoo** [comment]
You need to first calculate the column order by a certain method, then assign it to the `column_order` argument.
