### ISSUE TITLE
How to get a oncoplot with sorted by sample-type and column_order of one type are automatically adjusted?

### ISSUE THREAD

**Issue by wangjiangyuan** [jokergoo/ComplexHeatmap#799]
HI,
I want to get a oncoplot sorted by sample-type and oncoplot column_order of one type are automatically adjusted. How to get the oncoplot? Thanks
Like this oncoplot

![image](https://user-images.githubusercontent.com/48577567/132117726-bec308e0-f17f-4465-a7f6-01413833b184.png)

**Comment by jokergoo** [comment]
```r
oncoPrint(..., column_order = order(sample_type))
```
