### ISSUE TITLE
Reorder built-in hclust

### ISSUE THREAD

**Issue by schelhorn** [jokergoo/ComplexHeatmap#8]
I would like to use the built-in `hclust` via the `clustering_distance_rows`, `clustering_method_rows` parameters as well as declaring custom clustering via `split`. This works fine in the current release, however it seems I cannot make changes to the built-in hierarchical clustering this way (since I cannot supply an externally computed `hclust`  as well as supplying `split`, because  `ComplexHeatmap::Heatmap` interprets these as conflicting clusterings rather than the instruction to apply the built-in `hclust` to the externally supplied clusters as I intended. I would not care much if I had not an important requirement for the hclust: I would like to reorder the branches (while preserving the clustering) so that similar items keep nearby, as done by [`gclus::reorder.hclust`](http://www.inside-r.org/packages/cran/gclus/docs/reorder.hclust). Is there any way you could allow to (1) either modify the built-in `hclust` (while preserving `split` clusterings), or (2) add the reordering functionality to `ComplexHeatmap::Heatmap` directly?

**Comment by jokergoo** [comment]
That is a nice suggestion! I will support it in the next version. Thanks!

**Comment by schelhorn** [comment]
That seems to do the trick (replacing the prior part in `Heatmap-class.R`, starting line 649):

```R
                } else {
                    if(is.numeric(mat)) {
                        require(gclus)
                        hclust_d = get_dist(submat, distance)
                        c = hclust(hclust_d, method = method)
                        c = gclus::reorder.hclust(c, hclust_d)
                        row_hclust_list[[i]] = c
                        row_order_list[[i]] = row_order_list[[i]][ get_hclust_order(row_hclust_list[[i]]) ]
                    }
                }
```

**Comment by jokergoo** [comment]
Thanks a lot for the suggestion. I used a little bit different solution. Actually there are two ways:

1. if you only want to re-order rows based on a `hclust` object but don't want to draw the tree, you can set the order through `row_order` option in `Heatmap()`. Then you can split the rows in the normal way.

```{r}
hc = hclust(dist(mat))
Heatmap(mat, cluster_rows = FALSE, row_order = hc$order, split = ...)
```

2. if you also want to keep the tree, is this case, `split` can only be set as a single number indicating how many sub-trees that are cut from the big tree.

```{r}
Heatmap(mat, cluster_rows = hc, split = 2)
```
So in the following two figures, the second heatmap are splitted into two halves:

![download1](https://cloud.githubusercontent.com/assets/449218/8541890/ac5f54e4-2491-11e5-8fac-5ef9bdf70cd4.png)
![download2](https://cloud.githubusercontent.com/assets/449218/8541898/b1676166-2491-11e5-8632-6bc591788429.png)

This new feature are supported from version 1.2.2.

**Comment by schelhorn** [comment]
Thanks, that's excellent and also more flexible than my solution.
