### ISSUE TITLE
Legend odd behavior

### ISSUE THREAD

**Issue by sarpiens** [jokergoo/ComplexHeatmap#801]
Hello, I have detected an odd behavior trying to custom my legends:

When I add more than six points in a continuous legends the final color changes,the lowest point color (zero, in this case) with a dark blue disappears:

#Color Function for Heatmap
`col3=circlize::colorRamp2(c(0,0.001,0.005,0.01,0.05,0.1,0.2,0.4,0.8,1), c(rev(RColorBrewer::brewer.pal(n = 10, name = "RdYlBu"))))`

#Legend with 6 points
`lgd1=Legend(col_fun = col3,title="Average Relative Abundance",at=c(0,0.01,0.05,0.1,0.2,0.4),legend_width = unit(8, "cm"),direction = "horizontal")`
`draw(lgd1)`

![legend_6points](https://user-images.githubusercontent.com/49655743/132485904-6e7d7d9b-2eb5-439f-b292-b4927ea3091c.png)

#Legend with 7 points
`lgd1=Legend(col_fun = col3,title="Average Relative Abundance",at=c(0,0.01,0.05,0.1,0.2,0.4,0.8),legend_width = unit(8, "cm"),direction = "horizontal")`
`draw(lgd1)`

![legend_7points](https://user-images.githubusercontent.com/49655743/132485953-316c6395-5db4-4a45-9a1a-367c0346f476.png)

I have tried to make it bigger, but that doesn't help either. In fact, I see another odd behavior, white stripes appear:

#Legend with 7 points bigger

`lgd1=Legend(col_fun = col3,title="Average Relative Abundance",at=c(0,0.01,0.05,0.1,0.2,0.4,0.8),legend_width = unit(18, "cm"),direction = "horizontal")`
`draw(lgd1)`

![legend_7points_bigger](https://user-images.githubusercontent.com/49655743/132486578-741ecd12-69f3-436b-b316-3257c5f24733.png)

The same happens if I do this in a ComplexHeatmap.

There is any way to avoid this behavior, keep the color ramp as in the 6 points example, but add more points?

Ps: I'm using ComplexHeatmap 2.6.2.

**Comment by jokergoo** [comment]
Yes, that was a bug also reported by someone else. Can you try a newer version from Github? I think it should be fixed (I only tested the vertical legend, not sure about the horizontal legend. It would be great if you can have a try).

**Comment by jokergoo** [comment]
There was a small problem for horizontal legends. Now it is fixed.

![image](https://user-images.githubusercontent.com/449218/135241700-c99f3d15-08dc-4c18-ab32-6c6bcab37b20.png)
