### ISSUE TITLE
Legend missplacement when using ComplexHeatmap as grob

### ISSUE THREAD

**Issue by eggrandio** [jokergoo/ComplexHeatmap#805]
I would like to use ComplexHeatmap as part of a multipanel figure with ggarrange so I capture it as a grob. However, when I plot the grob object (even outside of the multipanel figure), the legend appears further from the heatmap, and falls outside of the plot area. It is not dependent on the data or the plot device so here I am showing an example:
```
discrete_mat = matrix(sample(1:4, 100, replace = TRUE), 10, 10)
colors = structure(1:4, names = c("1", "2", "3", "4")) # black, red, green, blue
HM = Heatmap(discrete_mat, name = "mat", col = colors,
    column_title = "a discrete numeric matrix")
HM_gb = grid.grabExpr(draw(HM))
```
Then:
```
HM
```
![image](https://user-images.githubusercontent.com/49569940/133514128-21ba752f-fa35-45ba-84fa-9e274f5ecb4a.png)
And the grob object with the shifted legend:
```
as.ggplot(HM_gb)
```
![image](https://user-images.githubusercontent.com/49569940/133514213-cd617e38-06e1-4d5b-8ad0-4ee4afbdf2b7.png)

I have tried setting height and width when capturing the grob as recommended in the [manual](https://jokergoo.github.io/ComplexHeatmap-reference/book/integrate-with-other-packages.html#cowplot) but I get the same results:
```
w = 3
h = 3
HM_gb2 = grid.grabExpr(draw(HM), width = w, height = h)

ggsave(as.ggplot(HM_gb2),
       filename = "./output/test.png",
       width = w, height = h)
```
![test](https://user-images.githubusercontent.com/49569940/133514960-ecb6414d-d003-492b-b342-2afdf4370c65.png)

**Comment by jokergoo** [comment]
What is your ComplexHeatmap version? That was a bug and I think I have fixed it in the newer versions. Maybe you can try the version from GitHub?

**Comment by eggrandio** [comment]
Hi, updating to the last version on Github fixed the problem.

`as.ggplot()` comes from ` ggplotify`. (https://cran.r-project.org/web/packages/ggplotify/ggplotify.pdf)
