### ISSUE TITLE
Highlight column/row names with circle or box

### ISSUE THREAD

**Issue by wenbostar** [jokergoo/ComplexHeatmap#806]
Is that possible to add a circle or add background color to a selected row name like below? I want to highlight some row/column names using in a way like this.
![image](https://user-images.githubusercontent.com/5302110/133559249-1e5723e8-3fd2-481d-be13-25e61df9f5d3.png)

**Comment by jokergoo** [comment]
You can use `gt_render()` function to style the text, see explanation at https://jokergoo.github.io/ComplexHeatmap-reference/book/integrate-with-other-packages.html#gridtext-dimnames

**Comment by wenbostar** [comment]
Thank you, gt_render works very nicely.
