### ISSUE TITLE
Width of grid in legend

### ISSUE THREAD

**Issue by wenbostar** [jokergoo/ComplexHeatmap#807]
Is that possible to make the width of grid for both heatmap legend and annotation legend the same? For example, mat1 and bar1 as shown below:

![image](https://user-images.githubusercontent.com/5302110/133649018-a3d1df10-8ea1-4aa1-aa38-47e6053d04f1.png)

I tried to set grid_width the same for both heatmap legend and annotation legend, but the width is still not the same in the plot.

**Comment by jokergoo** [comment]
It is because discrete legends have white borders. Now you can set `border = "asis"` to set the border the same color as the corresponding legend grid:


```r
lgd1 = Legend(at = 1:6, legend_gp = gpar(fill = 1:6), border = "asis", title = "legend1")
lgd2 = Legend(col_fun = col_fun, title = "legend2", at = c(0, 0.25, 0.5, 0.75, 1))
lgd3 = Legend(labels = month.name[1:3], legend_gp = gpar(fill = 7:9), border = "black", title = "legend3")

pd = packLegend(lgd1, lgd2, lgd3)
# which is same as 
pd = packLegend(list = list(lgd1, lgd2, lgd3))
grid.newpage()
grid.draw(pd)
```


![image](https://user-images.githubusercontent.com/449218/133998095-eaccfd05-5146-4dff-829a-c4bb480cc786.png)

**Comment by MjelleLab** [comment]
Hi, is it possible to adjust the line-width of the border of the legend? @jokergoo 
This one: border = "black"
