### ISSUE TITLE
anno_link not working on large heatmaps

### ISSUE THREAD

**Issue by nachocab** [jokergoo/ComplexHeatmap#81]
Hi Zuguang,

I am in love with your heatmap library.

Something I've noticed is that the `anno_link` is not working on big matrices. Here is a reproducible example. Let me know if I did something wrong, or if it's a bug (you can see that the labels don't match the row names):

```r
  set.seed(123)
  mat <- cbind(rbind(matrix(rnorm(24, -1), ncol = 4), matrix(rnorm(360, 1), ncol = 4)),
              rbind(matrix(rnorm(24, 1), ncol = 4), matrix(rnorm(360, -1), ncol = 4)))
  rownames(mat) <- paste0("R", 1:nrow(mat))
  colnames(mat) <- paste0("C", 1:ncol(mat))

  indexes <- which(rownames(mat) %in% c("R4", "R6", "R5", "R11", "R69", "R51"))
  labels <- rownames(mat)[indexes]
  Heatmap(mat) + rowAnnotation(
      link = row_anno_link(at = indexes, labels = labels),
      width = unit(1, "cm") + max_text_width(labels)
    )
```
![image](https://cloud.githubusercontent.com/assets/27538/24522224/d5d8796e-155c-11e7-9756-c1e9bdce911e.png)

**Comment by jokergoo** [comment]
Hi,

This is a bug. I modified this function several times and I think I messed it up last time when I modified it.

It has been fixed and you can update the package by `devtools::install_github("jokergoo/ComplexHeatmap")`

Thanks for reporting this bug!

![heatmap](https://cloud.githubusercontent.com/assets/449218/24546872/787dc998-160d-11e7-9482-7a38f9c8763a.png)

**Comment by nachocab** [comment]
Awesome, thanks for the great work on this package!
