### ISSUE TITLE
grid.boxplot() alternative for barplots?

### ISSUE THREAD

**Issue by Kdreval** [jokergoo/ComplexHeatmap#810]
Hi @jokergoo !
Thank you for this amazing and very useful package!
I was going through the documentation and was not sure whether this functionality exists already or if it is something that is possible to add.
Basically, I want to show annotation on the right as a bar graph, which shows mutation counts for each group of column split. Similar to what `grid.boxplot` can do, I am looking for a way to display multiple barplots for every single row. It is similar to what is described here: https://jokergoo.github.io/ComplexHeatmap-reference/book/more-examples.html#add-multiple-boxplots-for-single-row, with the exception to have an option for bar graphs.
I am aware of the stacked barplots option and use it heavily elsewhere, but this is not what I am looking for in this case.

**Comment by jokergoo** [comment]
No, there is no such function yet, but actually it is not difficult to implement one.

According to the example in the link in your quesion where it defines `anno_multiple_boxplot()`:


```r
anno_multiple_boxplot = function(index) {
    nr = length(index)
    pushViewport(viewport(xscale = rg, yscale = c(0.5, nr + 0.5)))
    for(i in seq_along(index)) {
        grid.rect(y = nr-i+1, height = 1, default.units = "native")
        grid.boxplot(m1[ index[i], ], pos = nr-i+1 + 0.2, box_width = 0.3, 
            gp = gpar(fill = "red"), direction = "horizontal")
        grid.boxplot(m2[ index[i], ], pos = nr-i+1 - 0.2, box_width = 0.3, 
            gp = gpar(fill = "green"), direction = "horizontal")
    }
    grid.xaxis()
    popViewport()
}
```

We can do similar things that now we draw rectanges instead of boxes:

```r
m = matrix(rnorm(100), 10)
# m2 is a nxk matrix where k is the number of bars per row, assume the values are all positive
m2 = cbind(runif(10), runif(10))
rg = c(0, max(m2))
anno_multiple_barplot = function(index) {
    nr = length(index)
    pushViewport(viewport(xscale = rg, yscale = c(0, nr)))
    nbar = ncol(m2)
    for(i in seq_along(index)) {  # for each row in the heatmap
        
        for(j in 1:nbar) {
        	grid.rect(x = 0, y = nr-i + (j-0.5)/nbar, width = m2[i, j], height = 1/nbar*0.8, just = c("left"),
        		default.unit = "native", gp = gpar(fill = j, col = "white"))
        }
        grid.rect(y = nr-i+0.5, height = 1, default.units = "native", gp = gpar(fill = NA)) # border

    }
    grid.xaxis()
    popViewport()
}

Heatmap(m, right_annotation = rowAnnotation(foo = anno_multiple_barplot, width = unit(4, "cm")))
```


![image](https://user-images.githubusercontent.com/449218/134469859-79cd61bf-c51e-47f4-9d28-778550e8e5f8.png)

If you want a legend for the bars, you need to manually define a legend:

```r
lgd = Legend(...)
draw(Heatmap(...), heatmap_legend_list = list(lgd))
```

**Comment by Kdreval** [comment]
Thank you so much! It worked well. I have modified it slightly to provide a vector of values to plot `all_sums` and custom colors `my_oncoplot_colours`. This is the way I used:
```
anno_multiple_barplot = function(index) {
  nr = length(index)
  pushViewport(viewport(xscale = c(0,1), yscale = c(0, nr)))
  nbar = ncol(all_sums)
  for(i in seq_along(index)) {  # for each row in the heatmap
    for(j in 1:nbar) {
      grid.rect(x = 0, y = nr-i + (j-0.5)/nbar, width = all_sums[i, j], height = 1/nbar*0.8, just = c("left"),
                default.unit = "native", gp = gpar(fill = my_oncoplot_colours[i, j], col = "white"))
    }
    grid.rect(y = nr-i+0.5, height = 1, default.units = "native", gp = gpar(fill = NA)) # border
    
  }
  grid.xaxis(main=FALSE)
  popViewport()
}
```

I noticed it doesn't work well with `remove_empty_rows = TRUE` in the `oncoPrint` call, and the annotation is placed too close to the heatmap. I solved the latter by placing an empty annotation on the right:

```
          right_annotation = rowAnnotation(foo = anno_empty(border = FALSE, width = unit(0.1, "cm")),
                                            feature_abundance = anno_multiple_barplot, width = unit(4, "cm"),
                                           show_annotation_name = c(feature_abundance = FALSE,
                                                                    foo = FALSE)),
```
I am not sure if there is a better way to specify the heatmap/annotation gap?
This is my end result, which gives exactly what I needed:
![image](https://user-images.githubusercontent.com/47579823/134595525-3b1ba547-af9c-48eb-820d-33e630ad41ab.png)

**Comment by jokergoo** [comment]
Yes, this solution is not a general one. 

Since `anno_barplot()` already has a `stack` mode for bars, I think it would be easy to also support the "besides" mode. I will support it in `anno_barplot()` soon.

**Comment by jokergoo** [comment]
Now I have added a new argument `beside` in `anno_barplot()` and you can also use it in `anno_oncoprint_barplot()`. See the following example for oncoprint:

```r
oncoPrint(mat,
    alter_fun = list(
        snv = function(x, y, w, h) grid.rect(x, y, w*0.9, h*0.9, 
            gp = gpar(fill = col["snv"], col = NA)),
        indel = function(x, y, w, h) grid.rect(x, y, w*0.9, h*0.4, 
            gp = gpar(fill = col["indel"], col = NA))
    ), col = col,
    top_annotation = HeatmapAnnotation(foo = anno_oncoprint_barplot(beside = TRUE)),
    right_annotation = rowAnnotation(bar = anno_oncoprint_barplot(beside = TRUE)))
```

![image](https://user-images.githubusercontent.com/449218/135075411-9a12978f-9d91-43e6-a846-8f072bfad04e.png)

**Comment by Kdreval** [comment]
Thank you so much! Closing this issue as resolved!
