### ISSUE TITLE
Cannot set width and height inside a function

### ISSUE THREAD

**Issue by Zepeng-Mu** [jokergoo/ComplexHeatmap#813]
Hi, I have a custom function outputting a heatmap, following the instruction from the documentation I'm using `draw()` to plot the function at the end of the function.

But I noticed that I cannot set `width` and `height` in `Heatmap` function inside RStudio. The heatmap basically occupies the whole canvas. I think if I directly save the plot to a file, the width and height can be set. I can also set width and height when directly calling `Heatmap` function.

I'm wondering whether there is a way to set the width and height when called inside a function and show that properly in RStudio plot pane?

Thanks so much!

**Comment by jokergoo** [comment]
How did you do that? It works fine on my laptop:

![image](https://user-images.githubusercontent.com/449218/134467671-4fb52528-eb68-4b95-9c0b-68a6cb36a514.png)

**Comment by Zepeng-Mu** [comment]
Sorry I was not clear enough. I can set width and height as what you did here. But I cannot do this when I call Heatmap within a function, and use draw() to plot the heatmap from **within that function**.

**Comment by jokergoo** [comment]
Do you mean this?

```
foo = function() {
    m = matrix(rnorm(100), 10)
    ht = Heatmap(m, width = unit(6, "cm"), height = unit(6, "cm"))
    draw(ht)
    ....
}
foo()

**Comment by Zepeng-Mu** [comment]
Yes, exactly.

**Comment by jokergoo** [comment]
But that also works fine on my side. Can you show me your full code and screenshot?

![image](https://user-images.githubusercontent.com/449218/134627228-a173c443-8aae-4040-ab50-32bd4386ce74.png)

**Comment by Zepeng-Mu** [comment]
Actually I tried again on my code and it's working for me now. I'm closing this issue for now.
Sorry about this!!
