### ISSUE TITLE
adjust shape size to fill heatmap cells using cell_fun

### ISSUE THREAD

**Issue by anabbi** [jokergoo/ComplexHeatmap#814]
Hello,

I have two matrices with the same dimensions and orders. One holds fold change data and the other hold FDR. I would like to plot a heatmap for fold change and add X to those cells with FDR > 0.1.

```
col_fun= colorRamp2(c(-1, 0, 1), c("blue", "white", "red"))  
pathways_hm = Heatmap(fc_mat, #this is fold change matrix
                      name = "Log2 FC",   
                      show_row_names = FALSE,
                      show_column_names = FALSE,     
                      cluster_columns = FALSE,
                      cluster_rows = TRUE,
                      show_column_dend = FALSE,
                      col = col_fun,
                      column_names_gp = gpar(fontsize = 10),
                      row_names_gp = gpar(fontsize = 10),
                      column_title_gp = gpar(fontsize = 10),
                      column_title = NULL,
                      row_title = NULL,
                      cell_fun = function(j, i, x, y, width, height, fill){
                         if(fdr_mat[i, j] > 0.1)  #if FDR >0.1, add shape 7
                             grid.points(x, y, pch = 7,
                                       gp = gpar(fontsize = 10))
                          } )


```

![heatmap_pathways_MSigDB_temp](https://user-images.githubusercontent.com/32966525/134721706-11e8205f-713c-4657-a23f-4c8b8c862824.jpg)

How can I adjust the shape to the cell size?

Thanks

**Comment by jokergoo** [comment]
The size of the point is controlled by the `size` argument.

```
grid.points(..., size = unit(5, "mm"))
```

**Comment by anabbi** [comment]
That would make the square shape bigger. How can I fit it to rectangular cells? Is there a way to specify width and height for shapes?

**Comment by jokergoo** [comment]
Can you manually adjust the value of `size`?

The thing is here, as in your case, the value in `size` does not exactly the same as the length of the "rectangle" because it is actually a "symbol" under **grid**. You can find more discussion here:

https://twitter.com/jokergoo_gu/status/1372898493153615876

One solution for your case is to implement `cell_fun` or `layer_fun` to draw one square plus two diagnol lines:

```r
m = matrix(rnorm(100), 10)
Heatmap(m, cell_fun = function(j, i, x, y, w, h, fill) {
	width = convertWidth(w, "cm")
	height = convertHeight(h, "cm")
	size = min(width, height) * 0.9
	grid.rect(x, y, width = size, height = size, gp = gpar(col = "black", fill = NA))
	grid.segments(x - 0.5*size, y - 0.5*size, x + 0.5*size, y + 0.5*size, gp = gpar(col = "black"))
	grid.segments(x - 0.5*size, y + 0.5*size, x + 0.5*size, y - 0.5*size, gp = gpar(col = "black"))
})
```

![image](https://user-images.githubusercontent.com/449218/134939685-868c5846-9eb6-46f2-ac93-1799451259a8.png)
