### ISSUE TITLE
cowplot without x11 on cluster

### ISSUE THREAD

**Issue by rbutleriii** [jokergoo/ComplexHeatmap#815]
Similar to #735, I am trying to plot two heatmaps using `cowplot`. However, I am on a cluster and the node does not have x11 configured, so I need a way around using x11 as the temporary device.
```
p1 = grid.grabExpr(draw(Heatmap(mat2, cluster_columns=F, cluster_rows=F, col=col_fun)))
p2 = grid.grabExpr(draw(Heatmap(pmat, cluster_columns=F, cluster_rows=F, col=col_fun)))
ggsave(file=paste(today, nameset, "Goal-2.pdf", sep="_"), plot=plot_grid(p1, p2), 
       device=cairo_pdf)
```
delivers the familiar:
```
Error in .External2(C_X11, d$display, d$width, d$height, d$pointsize,  :
  unable to start device X11
In addition: Warning message:
In (function (display = "", width, height, pointsize, gamma, bg,  :
  unable to open connection to X11 display ''
```
However, when trying to specify a device:
```
p1 = grid.grabExpr(draw(Heatmap(mat2, cluster_columns=F, cluster_rows=F, col=col_fun)), device=cairo_pdf)
# p2 = grid.grabExpr(draw(Heatmap(pmat, cluster_columns=F, cluster_rows=F, col=col_fun)), device=cairo_pdf)
# ggsave(file=paste(today, nameset, "Goal-2.pdf", sep="_"), plot=plot_grid(p1, p2), 
       # device=cairo_pdf)
```
I get this:
```
Error in device(width, height) : invalid 'filename' argument
> traceback()
2: device(width, height)
1: grid.grabExpr(draw(Heatmap(mat2, cluster_columns = F, cluster_rows = F,
       col = col_fun)), device = cairo_pdf)
```

**Comment by jokergoo** [comment]
I haven't seen this error. For using `cairo_pdf`, I think you can modify to :

```r
p1 = grid.grabExpr(draw(Heatmap(mat2, cluster_columns=F, cluster_rows=F, col=col_fun)), 
    device=function(w, h) cairo_pdf("foo.pdf", w, h))
```

**Comment by bersbersbers** [comment]
For the record, two comments:
1. I can reproduce the problem independent of `ComplexHeatmap`:
    ```r
    grid::grid.grabExpr(plot(x=1, y=1))
    ```
2. This does not fix it:
    ```r
    grid::grid.grabExpr(plot(x=1, y=1), device=function(w, h) cairo_pdf("foo.pdf", w, h))
    ```

Both issue
> Error in .External2(C_X11, d$display, d$width, d$height, d$pointsize,  : 
  unable to start device X11cairo
In addition: Warning message:
In (function (display = "", width, height, pointsize, gamma, bg,  :
  unable to open connection to X11 display ''

@rbutleriii, have you been able to find a solution for using `grid::grid.grabExpr` without X11?

**Comment by bersbersbers** [comment]
For me, the issue was an incorrectly set `DISPLAY` variable set (or, in other words, my X server had crashed). I wonder why `grid::grid.grabExpr` uses X11 anway, and have not found a way to override that from within `R` - however, unsetting `DISPLAY` outside `R` worked (or restarting the X11 server).
