### ISSUE TITLE
fixed size for splitted heatmap.

### ISSUE THREAD

**Issue by a00101** [jokergoo/ComplexHeatmap#816]
Thank you for the nice tool.

the number of my data is very skewed.
normal = 30, tumor = 400.

I used km=2 with heatmap but the sizes of heatmaps is very indistinguishable.

Can i fix size of heatmaps from splitted with km?

Thank you in advance.

**Comment by jokergoo** [comment]
Yes, for the "normal" heatmap, you can set the `width` argument:

```r
Heatmap(normal, width = unit(6, "cm"), ...) + Heatmap(tumor, ...)
```

**Comment by a00101** [comment]
@jokergoo 
Thank you for nice comment.
but I have one larget heatmap and splitted with km option.
No two heatmaps (normal, tumor)

The below code is for resizing the entire heatmap, and the size of the splitted heatmap (with different number of columns) is still different.

`Heatmap(df_mtc, name = "Relative abundance", cluster_rows = F, cluster_columns = T,
                       col = col_fun, border = T,
                       show_row_names = F, show_column_names = F, column_split = df_annot$New_Diagnosis,
                       heatmap_width = unit(10, "cm"), heatmap_height = unit(26, "cm"))`

Many thanks.

**Comment by jokergoo** [comment]
If you want to set different widths for normal and tumor, you need to split into two matrices and make two heatmaps.

**Comment by a00101** [comment]
Thanks :)
