### ISSUE TITLE
How to control the color of NA of a continuous variable (for example, age)?

### ISSUE THREAD

**Issue by lincj1994** [jokergoo/ComplexHeatmap#818]
Hi. I used colorRamp2 to create the color scale for continuous variables. However, if the variable contains NAs, oncoPrint will assign grey to NAs. I dont know how to control the color of NA of a continuous variable if I want the NA to be assigned white.

**Comment by jokergoo** [comment]
How about setting `na_col` argument?

**Comment by jokergoo** [comment]
Then in `HeatmapAnnotation()` function, there is also a `na_col` argument.

**Comment by gurpreet-bioinfo** [comment]
Hi @jokergoo I am using v2.12.1 of the package and `na_col` argument does not work with both Heatmap() and pheatmap()!  :(
