### ISSUE TITLE
multicore/multithread support ?

### ISSUE THREAD

**Issue by akhst7** [jokergoo/ComplexHeatmap#819]
HI,

Can ComplexHeatmap support Parallelization  ?

**Comment by jokergoo** [comment]
No, which part do you feel slow? The clustering step?

**Comment by akhst7** [comment]
@jokergoo 

So my data is fairly big.

```
dim(tmp)
[1] 95908  2007
```
Generating the heat map of this takes more than 1hr.   Seurat's `DoHeatmap `(ggplot2 based ?)  is faster.  It takes about 20-30min to draw the heat map of the same size.

**Comment by jokergoo** [comment]
I have no idea of why it runs so slow. 

On my laptop, it is actually not that slow. On a matrix with 95908x2007 and without doing clustering, it only needs 8 mins to generate the heatmap.

```
> m = matrix(runif(95908*2007), ncol = 2007)
> system.time(draw(Heatmap(m, cluster_rows = FALSE, cluster_columns = FALSE)))
`use_raster` is automatically set to TRUE for a matrix with more than
2000 rows. You can control `use_raster` argument by explicitly setting
TRUE/FALSE to it.

Set `ht_opt$message = FALSE` to turn off this message.

   user  system elapsed
418.847  49.847 482.511
>
> 482/60
[1] 8.033333
```

**Comment by jokergoo** [comment]
You have non-numeric values in your data. 

```r
> table(sapply(m, class))

character    factor   numeric
        1         4      2002
```

Also, your input is a data frame, you need to convert it to a matrix.

**Comment by jokergoo** [comment]
Sorry for the late reply. There was a network issue on my laptop. 

You can see it takes around 10min to generate your heatmap:

```r
> m = readRDS("matrix.RDS")
dim(m)^M> dim(m)
[1] 95908  2000
> str(m)
 num [1:95908, 1:2000] 15.53 -2.45 -2.4 -1.16 -1.83 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:95908] "6" "5" "23" "36" ...
  ..$ : chr [1:2000] "Cd74" "S100a9" "S100a8" "Fabp4" ...
> system.time(draw(Heatmap(m, cluster_rows = FALSE, cluster_columns = FALSE)))
   user  system elapsed
478.371  71.692 577.464
> 577.464/60
[1] 9.6244
```

![image](https://user-images.githubusercontent.com/449218/140760382-1fbcae6f-edf9-4b2b-b143-ee33218f37e5.png)

**Comment by akhst7** [comment]
I think I figured this out.  I was running HeatMap in the RStudio and the a bottleneck appears to be a rendering of the heat map  in the Rstudio.  I started R in the terminal and fired HeatMap and it took less than 8miin.  

```
> mbm
Unit: seconds
                                                            expr      min
 draw(Heatmap(m, cluster_rows = FALSE, cluster_columns = FALSE)) 442.1426
       lq     mean   median       uq      max neval
 442.1426 442.1426 442.1426 442.1426 442.1426     1
```
I checked CPU usage during HeatMap and it was only using 100% CPU (equivalent of single core).  I still wish ComplexHeatmap can support multi-CPU and threads.
