### ISSUE TITLE
How to make continuous legend symmetric?

### ISSUE THREAD

**Issue by nachocab** [jokergoo/ComplexHeatmap#82]
I'm trying to have a symmetric continuous legend (say, from -3 to 3) with white in the center (at 0). I've tried setting `at = pretty(c(-3, 3))`, which kind of works but the white is not at the center. Here is a reproducible example:

```
mat <- matrix(rnorm(100) + 1, nrow = 10)
Heatmap(mat,
  heatmap_legend_param = list(
    at = pretty(c(-3, 3)),
    color_bar = "continuous")
)
```
![image](https://cloud.githubusercontent.com/assets/27538/24669146/45094470-1937-11e7-97f8-9ed1573205ff.png)

**Comment by nachocab** [comment]
Ok, never mind. I guess I can just do this:

```
mat <- matrix(rnorm(100) + 1, nrow = 10)
Heatmap(mat,
  col = circlize::colorRamp2(c(-3, 0, 3), c("Darkblue", "white", "red")),
  heatmap_legend_param = list(
    color_bar = "continuous"
  )
)
```
![image](https://cloud.githubusercontent.com/assets/27538/24669271/d094f750-1937-11e7-848b-58e58960319a.png)

**Comment by nachocab** [comment]
Ok, I thought I understood it, but I don't. Here is a more elaborate example. I don't understand why the default version gives me colors from -10 to 5. When I check out the `matrix_color_mapping` and use that for my `col`, I still don't get the same colors.

```
set.seed(123)
mat <- cbind(
  rbind(
    matrix(rnorm(360, -4), ncol = 4), 
    matrix(rnorm(60, 1), ncol = 4)
  ),
  rbind(
    matrix(rnorm(360, 2), ncol = 4), 
    matrix(rnorm(60, -1), ncol = 4)
  )
)

max_mat <- max(abs(mat))
Heatmap(mat,
  name = "my colors",
  col = circlize::colorRamp2(c(-4, 0, 4), c("blue", "white", "red")),
  heatmap_legend_param = list(
    color_bar = "continuous"
  )
) + 
Heatmap(mat,
  name = "default",
  heatmap_legend_param = list(
    color_bar = "continuous"
  )
)
```
![image](https://cloud.githubusercontent.com/assets/27538/24669832/db62302e-1939-11e7-8475-6b5074b591a9.png)

**Comment by jokergoo** [comment]
The default color mapping function for the matrix is based on the maximum value and minimal value in the matrix (i.e. red for maximum value, blue for minimal value, white for the middle), that why in the default legend, you see the range is larger than the first heatmap.

On the other hand, when you've defined a color mapping, such as:

```
colorRamp2(c(-4, 0, 4), c("blue", "white", "red"))
```

values higher than 4 will all have the same red and values lower than -4 have the same blue.

**Comment by nachocab** [comment]
Ok, that makes sense. However, I still can't seem to replicate the default behavior using a custom color ramp. I'm just curious at this point

```
a <- Heatmap(mat,
  name = "my colors",
  col = circlize::colorRamp2(c(min(mat), 0, max(mat)), c("blue", "white", "red")),
  heatmap_legend_param = list(color_bar = "continuous")
)
b <- Heatmap(mat,
  name = "default",
  heatmap_legend_param = list(
    color_bar = "continuous"
  )
)
a + b
a@matrix_color_mapping
b@matrix_color_mapping
```
![image](https://cloud.githubusercontent.com/assets/27538/24720958/ce83b1b0-1a0c-11e7-9abc-a198f20bc905.png)

**Comment by jokergoo** [comment]
I have checked the source code for the default color mapping and the rules are as follows:

1. if the matrix is character, random color is assigned to each unique character
2. if the matrix is numeric, and the number of unique values is less than 100, "blue-white-red" is mapped to c(min, (min+max)/2, max).
3. if the matrix is numeric and the number of unique values are larger than 100, "bule-white-red" is mapped to c(quantile_0.01, (q0.01 + q0.99), quantile_0.99).

which means, when the numeric matrix is huge, colors are only mapped to 1th and 99th quantile of the matrix so that heatmap is not affected by outliers.

Now you can see the color mapping for the two heatmaps are identical.

```
> col_fun = colorRamp2(seq(quantile(mat, 0.01), quantile(mat, 0.99), length = 3), 
+ c("blue", "#EEEEEE", "red"))
> a <- Heatmap(mat,
+   name = "my colors",
+   col = col_fun,
+   heatmap_legend_param = list(color_bar = "continuous")
+ )
> b <- Heatmap(mat,
+   name = "default",
+   
+   heatmap_legend_param = list(
+     color_bar = "continuous"
+   )
+ )
> a@matrix_color_mapping
Continuous color mapping:
name: my colors 
default breaks:
[1] -10  -5   0   5

colors:
[1] "#0000FFFF" "#5F37FEFF" "#FDCEC2FF" "#FF0000FF"

> b@matrix_color_mapping
Continuous color mapping:
name: default 
default breaks:
[1] -10  -5   0   5

colors:
[1] "#0000FFFF" "#5F37FEFF" "#FDCEC2FF" "#FF0000FF"
```

**Comment by nachocab** [comment]
Wow, that's awesome. Thank you so much for sharing, it would have taken me a while to figure that out. Let me know if there is something in this project that you need help with. I'd love to contribute, even if it's just improving the documentation.

**Comment by sqjin** [comment]
I'm trying to have a symmetric continuous legend from -3 to 3.  However, the code "colorRamp2(c(-3, 0, 3), c("blue", "white", "red"))" only generates colormap ranging from -4 to 4.  Do you have any suggestions to address this issue? Thanks!

**Comment by jokergoo** [comment]
The color mapping generated by `colorRamp2()`is indeed from -3 to 3 with blue-white-red schema. The break values on the legend are calculated according to the values in the matrix, which means, if there are some values larger than 3 or smaller than -3, the break values are extended to -4 and 4 to cover most of them.

To exactly control the break values on the legend, you can set `heatmap_legend_param` argument in `Heatmap()` function:

```r
Heatmap(..., heatmap_legend_param = list(at = c(-3, 0, 3))
```

**Comment by sqjin** [comment]
@jokergoo Thanks so much!
