### ISSUE TITLE
Long column names getting cutoff in jupyter R

### ISSUE THREAD

**Issue by hiraksarkar** [jokergoo/ComplexHeatmap#825]
Please provide example datasets and the code you use. It will help me to understand your problem and help you!

I have already seen the issue referred in #17 but changing the `column_names_max_height` is not working in my situation,
with the following code I am still getting the column names truncated. I am using R jupyter. 

```
options(repr.plot.height=10, repr.plot.width=2, res=100 )
df <- data.frame(A_very_long_column_title_1 = rnorm(10), Another_very_long_column_title_2 = rnorm(10))
Heatmap(as.matrix(df),column_names_max_height=unit(100, "cm"))
```

![image](https://user-images.githubusercontent.com/9473877/136717705-864510df-29d8-435f-98a7-5cd709ac7e0c.png)

**Comment by jokergoo** [comment]
One meter height :)

OK, I will check it on jupyter notebook.

**Comment by jokergoo** [comment]
To be honest, I don't know how to fix this problem. It works fine on my local Jupyter lab:

![image](https://user-images.githubusercontent.com/449218/140901946-4a6adf36-305d-4c1c-87ab-ce2387948ae2.png)

but it has the same problem if using https://hub.gke2.mybinder.org/

![image](https://user-images.githubusercontent.com/449218/140902357-324e45fd-2f51-43ee-9194-282387066970.png)
