### ISSUE TITLE
Heatmap annotation is wrong when  specified row_split by sets of number from hclust

### ISSUE THREAD

**Issue by KoHaku55** [jokergoo/ComplexHeatmap#826]
Hi,
I created a heatmap with `rowAnnotation`. The heatmap cluster was run by hclust, I added the hclust in `cluster_row` argument. 
To separate clusters, I add a number (in this case 16) in `row_split`. It works well. 

But ! I want to reorder the cluster and merge some clusters together, so I used` cutree` to get the subcluster. z
The cluster number from the `cutree` is not the same as shown in the heatmap. 
For example, in `cutree` GeneA is in cluster number 1 but the heatmap showed number 5.  
**Do you have any solution how to match this ?**  (I already did by eyes) 

After I merge some clusters together and define the new set of cluster numbers. 
(I reduced 16 to 6 clusters and gave their new number)  I used this new obj in `row_split` . 
**If I add `cluster_row_slices =T` , the row annotation is correct but the heatmap cluster is not order 1 2 3 4 5 6 . 
If I add `cluster_row_slices =F`, the cluster order is 1 2 3 4 5 6 as I want. But the row annotation is wrong!** 

**Could you please help me how to fix this ?** 
Thank you in advance

**Comment by jokergoo** [comment]
If I understand correctly, you can first do "cutree analysis" to obtain a categorical variable before making the heatmap, than assign this variable to `row_split`.

```r
hc = hclust(dist(m))
cl = cutree(hc) ## or other analysis where you try to adjust the classifications
Heatmap(..., row_split = cl)
```
