### ISSUE TITLE
trend annotation of clusters

### ISSUE THREAD

**Issue by ebioman** [jokergoo/ComplexHeatmap#83]
Hello
I would like to put a trend curve for each cluster next to the heatmap of a differential gene expression analysis.
E.g. if we have a 3 timepoints (aka 3 columns) and a few thousand genes separated into 3 cluster. One could have a trend such as this:

 - cluster1: low,low, high
 - cluster2: low,high,low
 - cluster3: high,low,low

Now I would to put next to each cluster a plot with the mean of each values at the 3 time-points:

    __/
    _/\_
    /\__

Can you think about a way to do that ?
Thanks

**Comment by jokergoo** [comment]
You can define a row annotation function. The function accepts one argument
which is the index of matrix that belong to current row group (and has been ordered
by clustering if row clustering has been performed). If there are more than one
row groups, the function is applied to each row group, and `index` corresponds to
row index in "current" row group.

You can have a look of following example code.

```{r}
mat = matrix(rnorm(400), 40)
ht_list = Heatmap(mat, km = 3) + rowAnnotation(trend = function(index) {
	sub_mat = mat[index, ]
	y = colMeans(sub_mat)
	x = seq_len(ncol(sub_mat))
	pushViewport(viewport(xscale = c(0.5, ncol(sub_mat) + 0.5),
		                  yscale = range(y)))
	grid.rect()
	grid.lines(x, y, default.units = "native")
	grid.yaxis(gp = gpar(fontsize = 8))
	upViewport()
}, width = unit(4, "cm"))
draw(ht_list, gap = unit(1, "cm"))
```

![test](https://cloud.githubusercontent.com/assets/449218/24920843/070d753a-1ee9-11e7-9435-87f8f67703ea.png)

**Comment by ebioman** [comment]
That looks exactly as what I was looking for, thanks! Indeed I suspected that the index and subsequently the ht_list would be the way to go but had trouble to wrap my head around the syntax easily.
Cheers
