### ISSUE TITLE
layer_fun of ht1 is replaced by ht2 during Vertical concatenation

### ISSUE THREAD

**Issue by liuzhenyu-yyy** [jokergoo/ComplexHeatmap#831]
ht1 and ht2 are different heatmaps with different layer function and same number of columns.

if we run
```
ht <- ht1 %v% ht2
```

it seems that the layer_fun of ht1 is replaced by that of ht2 in ht. How could fix that?

thanks

**Comment by jokergoo** [comment]
Can you give me an example? It works fine on my side:

```r
m = matrix(rnorm(100), 10)

ht1 = Heatmap(m, layer_fun = function(j, i, x, y, w, h, f) {
    grid.text("A", x, y)
})


ht2 = Heatmap(m, layer_fun = function(j, i, x, y, w, h, f) {
    grid.text("B", x, y)
})

ht1 %v% ht2
```
![image](https://user-images.githubusercontent.com/449218/140742442-eac15a9b-0770-45b3-b455-4beddb62f070.png)
