### ISSUE TITLE
Is there a trick to set legend to bottom outside of draw?

### ISSUE THREAD

**Issue by bersbersbers** [jokergoo/ComplexHeatmap#833]
Based on these pieces of code

https://github.com/jokergoo/ComplexHeatmap/blob/5fd49ed1675c8c77964b4674d24c5401c43acfc4/R/HeatmapList-class.R#L509

https://github.com/jokergoo/ComplexHeatmap/blob/5fd49ed1675c8c77964b4674d24c5401c43acfc4/R/HeatmapList-class.R#L721

I had hoped that I could do something like this to place the legend at the bottom:

```r
ComplexHeatmap::draw(ComplexHeatmap::Heatmap(1, heatmap_legend_param = list(side = "bottom")))
```

The reason for this is that I am writing a function which passes the heatmap to some other code which then draws the heatmap later. I wonder if there is a way for me to change `heatmap_legend_param` (and similarly, `annotation_legend_parm`) for the `draw` method to pick them up.

**Comment by jokergoo** [comment]
In this way you proposed, it only controls the legend for a single heatmap. As you know, ComplexHeatmap actually draws a list of heatmaps and legends for all heatmaps/annotations are finally grouped. So that is why the legends are processed after the heatmaps are drawn.
```r
ComplexHeatmap::draw(ComplexHeatmap::Heatmap(1, heatmap_legend_param = list(side = "bottom")))
```
