### ISSUE TITLE
Setting a default color schema

### ISSUE THREAD

**Issue by w2felix** [jokergoo/ComplexHeatmap#834]
Hi,
thank you for your great package!
I was wondering, whether it is possible to change the default color schema “blue-white-red” to a manually defined palette? That would be amazing, as we try to standardize our reports.
Same for the heatmap annotation colors.
I know, I can change them manually for each plot, but would be cool to change them generally.

Would be even amazing to use the colors defined with the "thematic" package.

Thank you so much,
best
Felix

**Comment by jokergoo** [comment]
Yes, now you can globally control the color schema by `ht_opt$COLOR` option:

```r
ht_opt$COLOR = rainbow(7) # a vector of colors
m = matrix(rnorm(100), 10)
Heatmap(m)
```

![image](https://user-images.githubusercontent.com/449218/140741721-91fb5f27-64d1-4fa2-8bd1-67671dac865b.png)
