### ISSUE TITLE
Oncoprint custom alter_fun returning unique mutations rather than the number

### ISSUE THREAD

**Issue by ashishjain1988** [jokergoo/ComplexHeatmap#836]
I am trying to use the custom alter_fun as suggested in the manual

```r
oncoPrint(mat,
    alter_fun = function(x, y, w, h, v) {
        n = sum(v) 
        h = h*0.9
        if(n) grid.rect(x, y - h*0.5 + 1:n/n*h, w*0.9, 1/n*h, 
            gp = gpar(fill = col[names(which(v))], col = NA), just = "top")
    }, col = col)
```

in my data for one of the genes, I have 2 SNV and one Amplification in the same patient. In the final oncoplot, the cell fills 50% with SNV color and 50% with Amplification color instead of the 66.66% SNV and 33.33% Amplification color. When I looked into it more carefully, I found that the argument `v` in the `alter_fun` is giving the unique mutation type (TRUE/FALSE) instead of the count. 

Is it possible to change that to count instead of the unique mutation type in the Oncoprint function?

**Comment by jokergoo** [comment]
Em... I think the barplot mainly shows the patient-level statistics, ie, how many patients have this mutation, while not how many mutations the patients have...

Let's say only one patient has 1000 SNVs for a specific gene while other patients do not have, I would say, corhort-wisely, this mutation is not important.

Also from the aspect of plotting, how will you draw two snvs in the heatmap grid? What if three snvs or four snvs?

**Comment by ashishjain1988** [comment]
Thank you for the response. As I mentioned in the comment, I was thinking of plotting the different mutations for a patient in a gene, based on the proportions. So, let's say for a patient, gene X has 2 SNVs and 1 CNV. Now I want to color the heatmap cell based on those proportions (66.66% SNV and 33.33% CNV). But in the current code, the color of the cell is based on distinct mutations, not the proportions. Is there a way to color the cell based on the proportions of each mutation in a gene?

**Comment by jokergoo** [comment]
No, currently `oncoPront()` cannot do that. You need to manually customize the heatmap by using the `cell_fun`/`layer_fun` argument in `Heatmap()`.

**Comment by ashishjain1988** [comment]
Thank you for the suggestion!
