### ISSUE TITLE
Column tick gaps

### ISSUE THREAD

**Issue by brianpenghe** [jokergoo/ComplexHeatmap#837]
I opened this issue
https://github.com/GreenleafLab/ArchR/discussions/1138#discussion-3664744

But the author asked me to repost it here.
Basically I want to decrease the gap size between column labels. Is it doable?
![image](https://user-images.githubusercontent.com/4110443/140432557-b73bae14-3cac-4c34-bfaf-0ab5e96611db.png)

Thanks

**Comment by jokergoo** [comment]
How did you generate the plot? In Rstudio? Did you click the "Export" or "Zoom" button in the figure panel?

The positions of labels (generated by `anno_link()`) depend on the physical size of the figure region. As you can see in Rstudio, the sizes of the "figure panel" and the size of the "exported figure panel"/"zoomed figure panel" are different. Thus, it one place it looks fine, but in another place, it will look wrong. There should be message to inform you how to process with it.

I suggest you directly save the plot into a file.

```r
pdf(...) or png(...)
Heatmap(...)
dev.off()
```

In this way, the labels can be correct spacing between each other.

**Comment by brianpenghe** [comment]
I was running ArchR package on Jupyter Notebook.  
```
heatmapEM <- plotEnrichHeatmap(enrichMotifs, n = 7, transpose = TRUE)
options(repr.plot.width = 20, repr.plot.height = 10)
ComplexHeatmap::draw(heatmapEM, heatmap_legend_side = "bot", annotation_legend_side = "bot")
```
Is there anyway for me to make labels tighter?

**Comment by brianpenghe** [comment]
> How did you generate the plot? In Rstudio? Did you click the "Export" or "Zoom" button in the figure panel?
> 
> The positions of labels (generated by `anno_link()`) depend on the physical size of the figure region. As you can see in Rstudio, the sizes of the "figure panel" and the size of the "exported figure panel"/"zoomed figure panel" are different. Thus, it one place it looks fine, but in another place, it will look wrong. There should be message to inform you how to process with it.
> 
> I suggest you directly save the plot into a file.
> 
> ```r
> pdf(...) or png(...)
> Heatmap(...)
> dev.off()
> ```
> 
> In this way, the labels can be correct spacing between each other.

Indeed it changed a bit. Thank for the suggestion
