### ISSUE TITLE
Bivariate color scale and legend

### ISSUE THREAD

**Issue by jmw86069** [jokergoo/ComplexHeatmap#839]
Opening an issue to see if it is already on your radar. :) 

I recently encountered a scenario that needs a bivariate color scale, sometimes called "biscale".

R package "pals" has some Brewer bivariate color scales, see blog post:
https://nowosad.github.io/post/cbc-bp2/
Some visual examples:
<img width="577" alt="image" src="https://user-images.githubusercontent.com/93830/140543311-7a35eab6-386e-4f67-bd0b-06e99964139f.png">

Also the R package "biscale":https://cran.r-project.org/web/packages/biscale/vignettes/biscale.html

If you're interested, another cool blog is here, the animated GIF in step (5).
https://www.joshuastevens.net/cartography/make-a-bivariate-choropleth-map/

ComplexHeatmap is pretty awesome - I can implement a bivariate color scale with a custom `cell_fun` that colorizes each cell using a bivariate color function. That's really nice. What I can't do (yet) is create a matching color legend.

I also really love using `ComplexHeatmap::Legend()` - the configuration options, labeling, sizing, it's all great.
My ideal would be for `Legend()` to handle bivariate color scales.
I think I would have to specify the 2-dimensional color matrix, because there are different ways the colors are defined.

Omg did I just figure out that the color legend is its own mini-heatmap? Hahaha. Wow. It's recursive.

Which would you do for color legend? (or something else)
1. make a few vertical color legends, and place them beside each other
2. make a mini heatmap with fixed size

Is this is a use case you think is on your roadmap?
If it helps, my data has -log10(P-values) for intensity, and positive and negative z-scores for direction.

**Comment by jmw86069** [comment]
I tried option #1 above, legend list is shown below:
<img width="130" alt="image" src="https://user-images.githubusercontent.com/93830/140580895-02835d76-de73-43f5-8f18-12eb671aff65.png">

I couldn't figure a way to put labels along the bottom.
It works best with the overall legend title on the left side, so that all legends have the same top border.
If there were an option for `title_position="bottom-rot"` I think I could put labels at the bottom.

I did make a custom `colorRampBiscale()` and it mainly just calls `circlize::colorRamp2()` twice, it works well.

**Comment by jokergoo** [comment]
Thanks for this great idea! Actually, it is already on my to-do list #812 .

I wish I can have some free time working on it some time next month! (this month I am doing paper revisions and I am afraid I will not have too much free time.)

Basically, as you've wrote already, I will write a new function that do 2D color mapping, and also I need to look for example datasets to show this new feature.

**Comment by jmw86069** [comment]
Ooh sorry I missed #812 I thought I remembered you posting something about it previously, my mistake.

I'd be happy to post example data to help show the feature, and send what I put together for the 2D color mapping. You can decide whether it fits your needs, all good. No worries about timelines, good luck with paper revisions!

For the 2D color function `colorRampBiscale()` I took the easy route, supplied a 2D matrix of colors, and breaks along each axis. The interpolation was straightforward in two-pass - once along x-axis breakpoints using custom y-value. Then use output, for each x breakpoint with custom y-value, interpolate again with custom x-value. Two calls to `circlize::colorRamp2()` per cell.

One issue I hit with related custom heatmap cell colors, it may not work for `use_raster=TRUE` - I'm not sure if it seems to adjust numbers before calling the color function. I haven't traced it, I just turned rasterization off.
