### ISSUE TITLE
Accessing params after draw()

### ISSUE THREAD

**Issue by ATpoint** [jokergoo/ComplexHeatmap#841]
Hello,

usually when we make a heatmap with `hm <- Heatmap(mat)` we can later change params based on the `hm` variable such as the gp fontsize (default 12) to e.g. 5 like:

`hm@row_names_param$gp$fontsize <- 5`

I have the situation that I stored heatmaps as variables after running `draw()` like 
`hm_drawn <- draw(hm)` and now cannot find a way to alter params as above. The `@row_names_param$gp$fontsize` slot is not even present anymore in `hm_drawn` afaiks. Is there a way to change these types of params after `draw()` has been run without going back to the original data and rerunning `Heatmap()`?

**Comment by jokergoo** [comment]
It is now in 

```r
hm_drawn@ht_list[[1]]@row_names_param$gp$fontsize <- 5
```

because now `hm_drawn` is a `HeatmapList` object.

**Comment by ATpoint** [comment]
Thanks for the fast reply. I tried that without success though, see this example:

```
set.seed(123)
nr1 = 4; nr2 = 8; nr3 = 6; nr = nr1 + nr2 + nr3
nc1 = 6; nc2 = 8; nc3 = 10; nc = nc1 + nc2 + nc3
mat = cbind(rbind(matrix(rnorm(nr1*nc1, mean = 1,   sd = 0.5), nr = nr1),
                  matrix(rnorm(nr2*nc1, mean = 0,   sd = 0.5), nr = nr2),
                  matrix(rnorm(nr3*nc1, mean = 0,   sd = 0.5), nr = nr3)),
            rbind(matrix(rnorm(nr1*nc2, mean = 0,   sd = 0.5), nr = nr1),
                  matrix(rnorm(nr2*nc2, mean = 1,   sd = 0.5), nr = nr2),
                  matrix(rnorm(nr3*nc2, mean = 0,   sd = 0.5), nr = nr3)),
            rbind(matrix(rnorm(nr1*nc3, mean = 0.5, sd = 0.5), nr = nr1),
                  matrix(rnorm(nr2*nc3, mean = 0.5, sd = 0.5), nr = nr2),
                  matrix(rnorm(nr3*nc3, mean = 1,   sd = 0.5), nr = nr3))
)
mat = mat[sample(nr, nr), sample(nc, nc)] # random shuffle rows and columns
rownames(mat) = paste0("row", seq_len(nr))
colnames(mat) = paste0("column", seq_len(nc))

#/ this works, fontsize will be reduced to 5:
hm0 <- Heatmap(mat)
hm0
hm0@row_names_param$gp$fontsize <- 5
hm0

#/ this has no effect, looks the same as if I did not do any changes to fontsize:
hm <- draw(Heatmap(mat))
hm@ht_list[[1]]@row_names_param$gp$fontsize <- 5
hm
```

Package version 2.6.2

**Comment by jokergoo** [comment]
Yes, you are right. You cannot modify configurations for a already `draw`n() heatmap. The reason is `Heatmap()` is actually a constructor function and it does not do plotting. So configurations can be modified there. When `draw()` is applied, all configurations are fixed, and you cannot modify them anymore.

**Comment by ATpoint** [comment]
That is unfortunate, thanks for the reply though. Would this something that in principle could be added / allowed in future versions or is it incompatible with how the functions work under the hood?

**Comment by jokergoo** [comment]
Why do you want to modify the object returned by `draw()` while not the one directly from `Heatmap()`?
