### ISSUE TITLE
How set a axis break for a boxplot annotation?

### ISSUE THREAD

**Issue by lincj1994** [jokergoo/ComplexHeatmap#843]
![image](https://user-images.githubusercontent.com/60967283/141712542-81f47e72-19ec-4ee7-aa22-1a3d6732b6a4.png)
Hi. I have added a boxplot annotation to a oncoprint but the variable had extreme value. I dont know how to set a break for y axis.

**Comment by yaotianran** [comment]
Read the ComplexHeatmap manual [points-annotation section](https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html#points-annotation)

**Comment by lincj1994** [comment]
Thanks for your reply. What I want is a axis break like this.
![image](https://user-images.githubusercontent.com/60967283/141728559-73119d1c-b797-4dff-be84-ffc4729ac076.png)

**Comment by jokergoo** [comment]
No, currently it does not support that.
