### ISSUE TITLE
How to remove the border of each stacked bar in anno_barplot.

### ISSUE THREAD

**Issue by lincj1994** [jokergoo/ComplexHeatmap#844]
![image](https://user-images.githubusercontent.com/60967283/142976827-4362fe00-6d91-49c2-b614-f76bce5d04e0.png)
Hi. I want to draw a stacked bar plot using anno_barplot and I dont know how to remove the inner border of the stacked bar plot. My data has too many observations and the bar will be dark if the inner border is kept.
![image](https://user-images.githubusercontent.com/60967283/142976962-eac7b6bb-e7ca-4eb3-b15c-3926d698f40a.png)

**Comment by jokergoo** [comment]
in `anno_barplot()`:

```r
anno_barplot(..., gp = gpar(col = NA, ...))
```
