### ISSUE TITLE
Automatic scaling 

### ISSUE THREAD

**Issue by FrederickClasen** [jokergoo/ComplexHeatmap#845]
Hi, when using Heatmap my data is automatically scaled and I cannot seem to find any function to remove the scaling. Is there an easy way to do this.

**Comment by jokergoo** [comment]
What do you mean "automatically scaled"? Can you give an example?

**Comment by FrederickClasen** [comment]
The range of the input matrix is [-1,0.5] and the scale on the heatmap is [-2,2] so I assume that there is some sort of normalisation (or scaling) that automatically takes place?

**Comment by jokergoo** [comment]
No, there is no scaling on the matrix. It just automatically generates a color mapping based on your matrix.

Since the range is [-1, 0.5], by default it will generate a color mapping centric to zero.

You can always manually adjust it by self-defining a color mapping function, e.g.:

```
col_fun = circlize::colorRamp2(c(-1, 0.5), c("green", "red"))
```
