### ISSUE TITLE
A problem about Legend function

### ISSUE THREAD

**Issue by chuiqin** [jokergoo/ComplexHeatmap#849]
When I run this code, it is ok.
```
col_fun = colorRamp2(c(0, 0.5, 1), c("blue", "white", "red"))
lgd = Legend(col_fun = col_fun, title = "foo")
draw(lgd)
```
![image](https://user-images.githubusercontent.com/65839548/143807021-99d81eb6-f953-416c-8c4c-e1fd22f52d61.png)

When I run this code, it confuse me.
```
col_fun = colorRamp2(c(-2.1637203, -0.8934335, 2.1857818), c("blue", "white", "red"))
lgd = Legend(col_fun = col_fun, title = "foo")
draw(lgd)
``` 
![image](https://user-images.githubusercontent.com/65839548/143807581-025cd065-a6fd-430c-8049-5d286bb63ef2.png)

Why does the second legend start at -4 instead of -2.1637203 or -3?

```
col_fun = colorRamp2(c(-1.1637203, -0.8934335, 1.1857818), c("blue", "white", "red"))
lgd = Legend(col_fun = col_fun, title = "foo")
draw(lgd)
```
![image](https://user-images.githubusercontent.com/65839548/143808073-db6c345b-6d8f-4c22-80ef-f4823ce31904.png)
And the third legend startes at -2.

```
col_fun = colorRamp2(c(-3.1637203, -0.8934335, 3.1857818), c("blue", "white", "red"))
lgd = Legend(col_fun = col_fun, title = "foo")
draw(lgd)
```
![image](https://user-images.githubusercontent.com/65839548/143808266-ffe4301a-44f7-4198-9c97-f9499dffde47.png)

And the third legend startes at -4.

```
col_fun = colorRamp2(c(-4.1637203, -0.8934335, 4.1857818), c("blue", "white", "red"))
lgd = Legend(col_fun = col_fun, title = "foo")
draw(lgd)
```
![image](https://user-images.githubusercontent.com/65839548/143808445-19b388c7-537e-48ac-b3fa-c715ef5b20c3.png)

And the forth legend startes at -4.

```
col_fun = colorRamp2(c(-5.1637203, -0.8934335, 5.1857818), c("blue", "white", "red"))
lgd = Legend(col_fun = col_fun, title = "foo")
draw(lgd)
```
![image](https://user-images.githubusercontent.com/65839548/143808539-a21e650a-c8e2-40b2-8551-c912081b2734.png)
But the fifth legend startes at -10.
How do I use this function in order to show the precise range? Thank you!

**Comment by jokergoo** [comment]
For this code:

```
col_fun = colorRamp2(c(-2.1637203, -0.8934335, 2.1857818), c("blue", "white", "red"))
lgd = Legend(col_fun = col_fun, title = "foo")
draw(lgd)
```

values of `c(-2.1637203, -0.8934335, 2.1857818)` only define the color mapping, but not the breaks on legend. As you can imagine, the breaks on legend should be as integers as possible, for easy reading.

If you want to exactly control the breaks on legend, you can set `at` argument in `Legend()`:

```r
lgd = Legend(col_fun = col_fun, title = "foo", at = c(-2.1637203, -0.8934335, 2.1857818))
```

![image](https://user-images.githubusercontent.com/449218/143845912-9ef5369f-9b4d-40ce-b223-0805e95e4a39.png)
