### ISSUE TITLE
How to layout the figure legends

### ISSUE THREAD

**Issue by ShixiangWang** [jokergoo/ComplexHeatmap#850]
Please provide example datasets and the code you use. It will help me to understand your problem and help you!

The following gives a minimal example.

```
m = matrix(sample(c("", "AMP", "DEL"), 100, prob = c(0.8, 0.1, 0.1), replace = TRUE), nrow = 10)
rownames(m) = paste0("A", 1:10)
colnames(m) = paste0("B", 1:10)
oncoPrint(m,
          top_annotation = HeatmapAnnotation(cbar = anno_oncoprint_barplot(), 
                                             g = c("A", "A", "A", "B", "B", "B", "C", "C", "C", "D")))
```

What I wanna do is move the group `g` to the column of `Alteration`, so the plot is more tight. I read and search documents and questions on internet, and could not find anything talking this.

![image](https://user-images.githubusercontent.com/25057508/144172684-cb7b8c7d-54f0-4e12-81c8-30cc13c499f2.png)

Best,

Shixiang

**Comment by jokergoo** [comment]
```r
ht = oncoPrint(m,
          top_annotation = HeatmapAnnotation(cbar = anno_oncoprint_barplot(), 
                                             g = c("A", "A", "A", "B", "B", "B", "C", "C", "C", "D")))
draw(ht, merge_legends = TRUE)
```

**Comment by ShixiangWang** [comment]
@jokergoo Thanks for this simple while elegant solution.
