### ISSUE TITLE
Displaying large matrix (>4000 genes)

### ISSUE THREAD

**Issue by ryanhchung** [jokergoo/ComplexHeatmap#851]
Hello,

I have a large gene expression matrix with 4,920 rows and 27 columns.

When I tried visualization with Heatmap() function in Rstudio, I figured out that many genes were removed and only a few  (maybe less than 2000?) genes have been displayed.

After I figured out the warning 
"`use_raster` is automatically set to TRUE for a matrix with more than 2000 rows. You can control `use_raster` argument by explicitly setting TRUE/FALSE to it.", I tried 'use_raster=FALSE' to show more rows but still not displaying all gene rows.

Is there any way to display all gene rows?

I'm currently using ComplexHeatmap v2.6.2.

Thank you!

**Comment by jokergoo** [comment]
Hi, there is no gene removed. It is just a way to optimize the heatmap.
