### ISSUE TITLE
Combining both vertical and horizontal heatmap lists   - Error: The heatmap list should only be all horizontal or vertical.

### ISSUE THREAD

**Issue by jespermaag** [jokergoo/ComplexHeatmap#852]
Is there a way to combine many vertical heatmap lists toghether horziontally? 
 
 For example, I have 2 different heatmaps that consists of multiple vertical heatmaps each.
 
##  pseudo code 
 ```
 ht_a <- a1 %v% a2 %v% a3
 ht_b <- b1 %v% b2 %v% b3 
 ```
 I want to combine them horizontally 
 ```
 ht_a + ht_b 
 
```
I get the following error:
 > Error: The heatmap list should only be all horizontal or vertical.
 
 
##  Runnable example below
 ```
 set.seed(123)
mat1 = matrix(rnorm(80, 2), 8, 10)
mat1 = rbind(mat1, matrix(rnorm(40, -2), 4, 10))
rownames(mat1) = paste0("R", 1:12)
colnames(mat1) = paste0("C", 1:10)

mat2 = matrix(runif(60, max = 3, min = 1), 6, 10)
mat2 = rbind(mat2, matrix(runif(60, max = 2, min = 0), 6, 10))
rownames(mat2) = paste0("R", 1:12)
colnames(mat2) = paste0("C", 1:10)


mat1t = t(mat1)
mat2t = t(mat2)
col_rnorm = circlize::colorRamp2(c(-3, 0, 3), c("green", "white", "red"))
col_runif = circlize::colorRamp2(c(0, 3), c("white", "orange"))
ht1 = Heatmap(mat1t, name = "rnorm", col = col_rnorm, row_title = "rnorm")
ht2 = Heatmap(mat2t, name = "runif", col = col_runif, row_title = "runif")
ht_list = ht1 %v% ht2 
ht_list_2 = ht1 %v% ht2 


ht_list + ht_list_2
```

> Error: The heatmap list should only be all horizontal or vertical.

Regards,
Jesper

**Comment by jokergoo** [comment]
Hi, you cannot use both the horizontal heatmap list and the vertical heatmap list. But if you construct the heatmap vertically, actually you can change the "horizontal heatmap" as heatmap-like annotations:

For your example, it would be

```
Heatmap(..., right_annotation = HeatmapAnnotatioin(foo = mat1)) %v%
Heatmap(..., right_annotation = HeatmapAnnotatioin(bar = mat2))
```

Note, you need to manually adjust the width of `foo` and `bar`.
