### ISSUE TITLE
Removing labels

### ISSUE THREAD

**Issue by amkhasawneh** [jokergoo/ComplexHeatmap#853]
Hello, Zuguang!

Thank you very much for all the effort you put into the beautiful ComplexHeatmap package.
I am trying to make a gene expression heat map, and I would like to remove the names of the individual genes, as they clutter the plot. How can I do that?

Here's the call for the heatmap:

`Heatmap(as.matrix(ND), name = "New Cases", left_annotation = annotation.ND, col = colorRamp2(c(1,40000), c("green", "red")))
`

Thanks!
![ND heatmap](https://user-images.githubusercontent.com/57086613/144978053-74ce2bda-aca2-4460-92b3-d9636788ee36.jpeg)

**Comment by jokergoo** [comment]
You can set `show_column_names = FALSE` in `Heatmap()`.

**Comment by amkhasawneh** [comment]
> You can set `show_column_names = FALSE` in `Heatmap()`.

Thank you very much! It worked perfectly.
I apologize for any inconvenience; I couldn't find that in the book/documentation.
