### ISSUE TITLE
Dodge label position

### ISSUE THREAD

**Issue by asaksager** [jokergoo/ComplexHeatmap#855]
Hi

I have a heatmap where I have labelled my columns. However, I have too many labels to make them in a readable size without them overlapping eachother. 
Is it possible to "dodge" the position of the labels, as it is in ggplots? 

In ggplot: 
scale_x_discrete(guide = guide_axis(n.dodge=3))

**Comment by jokergoo** [comment]
Maybe you are looking for this: https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html#mark-annotation ?

It has been tested for row labels, but less tested for column labels. If you see bugs, please tell me.
