### ISSUE TITLE
Draw over a heatmap

### ISSUE THREAD

**Issue by yashcrux** [jokergoo/ComplexHeatmap#857]
Hi Gu

I currently have a matrix and I have plotted a heatmap with it. Now I want to draw a line over the heat map connecting the means of each of the columns of the matrix.

Is it possible to do something like that? if yes can you help me in some way?

**Comment by jokergoo** [comment]
Is it like what `heatmap.2()` does? You can do in the ComplexHeatmap way:

```r
m = matrix(rnorm(100), 10)
ComplexHeatmap:::heatmap.2(m, tracecol = TRUE)
```

![image](https://user-images.githubusercontent.com/449218/152320964-ee2297b3-febf-4d68-9a1c-8b61b3893710.png)

Note here `ComplexHeatmap:::heatmap.2()` is implemented by ComplexHeatmap, and it has the same set of arguments and the same illustration as the original `heatmap.2()`.

You can add more heatmaps and annotations:

```r
ComplexHeatmap:::heatmap.2(m, tracecol = TRUE) + rowAnnotation(foo = 1:10) + Heatmap(m)
```

![image](https://user-images.githubusercontent.com/449218/152321270-04ef3bca-00fc-4b63-a8af-666b9bfc3749.png)

If you want to add the trace lines by your own, actually you need to define a `layer_fun` which draws graphics on top of the heatmap. The following code is what I defined for `ComplexHeatmap:::heatmap.2()`:

```r
layer_fun = function(j, i, x, y, w, h, fill) {
    ind_mat = restore_matrix(j, i, x, y)

    min = min(m)
    max = max(m)
    ind = ind_mat[1, ]
    grid.segments(x[ind], unit(0, "npc"), x[ind], unit(1, "npc"), gp = gpar(col = "black", lty = 2))
    for(ki in seq_len(ncol(ind_mat))) {
        ind = ind_mat[, ki]
        offset = (m[i[ind], j[ind[1]]] - min)/(max - min)*w[ind]
        pos_x = rep(x[ind] - w[ind]*0.5 + offset, each = 2)
        pos_y = rep(y[ind] + h[ind]*0.5, each = 2)
        pos_y[seq_along(pos_y) %% 2 == 0] = y[ind] - h[ind]*0.5
        grid.lines(pos_x, pos_y, gp = gpar(col = "black"))
    }
}
```

```r
Heatmap(m, layer_fun = layer_fun)
```

![image](https://user-images.githubusercontent.com/449218/152322055-e6dba77a-92db-4dfe-ab70-b4741e1730b6.png)
