### ISSUE TITLE
Text annotation for oncoprint

### ISSUE THREAD

**Issue by annamarialara** [jokergoo/ComplexHeatmap#860]
Hi, I am trying to add a text annotation to my oncoprint. It seems the order of this text annotation is randomly shuffled, please see an example below.

Even though the months names should be in the order of the year, the annotation is not in the same order as input.
If I force oncprint to keep the order of the original matrix with 

row_order = rownames(oncoprint2)

Then the annotation is in the original order. However, I would like to keep the automatic reordering of oncoprint and then match my annotation with that row order. I tried preparing an annotation matrix where the rownames would be the same as for the oncoprint matrix but this would also result in a shuffled annotation.

Is it possible to extract the row order form the oncoprint so I can reorder my annotation and then plot again?

Hope below code and picture is sufficient to illustrate the problem even if not entirely reproducible.

```
>month_name=c(month.name,month.name[1:6])
>month_name
 [1] "January"   "February"  "March"     "April"     "May"       "June"      "July"      "August"    "September" "October"   "November"  "December" 
[13] "January"   "February"  "March"     "April"     "May"       "June"   

ht=oncoPrint(oncoprint2, get_type = function(x) strsplit(x, ";")[[1]],  
            left_annotation =rowAnnotation(foo = anno_text(month_name)),
             alter_fun = alter_fun, 
             remove_empty_columns = FALSE,
             remove_empty_rows = FALSE,
             col = col,
             pct_gp = gpar(fontsize = 7), 
             row_names_gp = gpar(fontsize = 8),
             column_title = "",
             row_names_side = "left",
             pct_side = "right", 
             show_column_names = F)
draw(ht)
```

![Oncoprint PDX models DDR BM example (1)](https://user-images.githubusercontent.com/26789889/149133737-fe444ce8-f102-4780-b5f2-d34d54ffc7da.png)

**Comment by jokergoo** [comment]
In your plot, the rows of oncoprint are consistent to the text annotation, isn't it? E.g. `gene 2` for `February`, `gene 9` for `September`?
