### ISSUE TITLE
anno_empty: annotation_name and fill with gradient

### ISSUE THREAD

**Issue by mdidish** [jokergoo/ComplexHeatmap#861]
Dear,
First thank you for this great package.

I have two question :

1/ I failed to display column annotation name when I use `anno_empty`, is there a solution?

```
ha = HeatmapAnnotation(risk = anno_empty(border = TRUE),
                       annotation_name_side = "right")
```

2/ is it possible to fill this empty annotation with a unique gradient? (to represent a gradual increase in risk from the left column to the right column)

Best,
Marc

**Comment by jokergoo** [comment]
1. Now I add a new argument `show_name` in `anno_empty()`. Please update from GitHub.

```r
m = matrix(rnorm(100), 10)
ha = HeatmapAnnotation(
	foo = anno_empty(border = TRUE, show_name = TRUE),
	bar = anno_points(1:10))
Heatmap(m, top_annotation = ha)
```

![image](https://user-images.githubusercontent.com/449218/152319226-74f8542c-b175-4707-928e-fa39392b9c17.png)

2. Maybe you can simply add a heatmap-like annotation:

```r

library(circlize)
ha = HeatmapAnnotation(
	foo = 1:10, 
	col = list(foo = colorRamp2(c(1, 10), c("white", "red")))
)
Heatmap(m, top_annotation = ha, cluster_columns = FALSE)
```

![image](https://user-images.githubusercontent.com/449218/152319532-d5ec233d-9517-4278-9d16-fa980d6829c2.png)

**Comment by mdidish** [comment]
Ok thank you for your response.
