### ISSUE TITLE
Column order preservation using `anno_boxplot()` with `UpSet`

### ISSUE THREAD

**Issue by BarryDigby** [jokergoo/ComplexHeatmap#862]
Hi Zuguang Gu :D

Quick query regarding my upset plot which makes a boxplot from a 'handmade' data frame - not directly derived from the `m` object:

```R
library(ComplexHeatmap)

load("/data/issue.RData")

RT <- data.frame("Segemehl" = c(294,373), "DCC" = c(276, 1018), "CIRIquant" = c(165, 176), "find_circ" = c(462, 283), "MapSplice" = c(1510, 876), "circRNA_finder" = c(116, 296), "CIRCexplorer2" = c(116, 297))

ss = set_size(m)
cs = comb_size(m)


ht = UpSet(m, 
           set_order = order(ss),
           comb_order = order(comb_degree(m), -cs),
           right_annotation = NULL,
           show_row_names = T,
           bottom_annotation = HeatmapAnnotation(Run_time = anno_boxplot(RT), height = unit(5, "cm"))
)

ht = draw(ht)
```
![image](https://user-images.githubusercontent.com/58001749/149518455-1301a3fe-0444-4d64-be21-e6822c2ed5cf.png)

```R
RT
```
```console
> RT
  Segemehl  DCC CIRIquant find_circ MapSplice circRNA_finder CIRCexplorer2
1      294  276       165       462      1510            116           116
2      373 1018       176       283       876            296           297
```

Using `Mapsplice` as my sanity check, I noticed that the boxplot values do not align correctly with the dataframe `RT` from which they came. 

Intuitively, I thought I could 'stick' the boxplot to the `ht` object _post-hoc_ like so: `ht %v% HeatmapAnnotation(Run_time = anno_boxplot(RT), height = unit(5, "cm"))` but that produced the exact same plot. 

Any pointers would be greatly appreciated - the `m` object is attached if needed. 

[issue.RData.tar.gz](https://github.com/jokergoo/ComplexHeatmap/files/7870527/issue.RData.tar.gz)

**Comment by jokergoo** [comment]
`RT` always corresponds to `m` and reordering by `set_order` and `comb_order` will apply to both simultaneously. So, you need to make sure `RT` is correctly aligned to `m`:

```r

RT  = RT[rownames(m)]

UpSet(m, 
           set_order = order(ss),
           comb_order = order(comb_degree(m), -cs),
           right_annotation = NULL,
           show_row_names = T,
           bottom_annotation = HeatmapAnnotation(Run_time = anno_boxplot(RT), 
           	labels = anno_text(names(RT)), height = unit(c(8), "cm"))
)
```
![image](https://user-images.githubusercontent.com/449218/152331457-52f69727-d1d7-4db6-a386-30b17ede547f.png)

**Comment by BarryDigby** [comment]
Thank you very much (:
