### ISSUE TITLE
Draw border on one axis only, e.g. rows

### ISSUE THREAD

**Issue by RodrigoGM** [jokergoo/ComplexHeatmap#866]
Hi all,
Is there a way to apply borders only on a single dimension ?   I have a square matrix, with co-clustering frequencies from a consensus clustering.  The clusters need to be symmetrical, hence, I'm passing the order as a split.  However, `border = TRUE` adds lines on both dimensions, and the matrix looks very busy.  The assembled plot will show only the lower diagonal, and bordering only the rows will work well. 

Thank you,

Here is my code,

```
hx <- Heatmap(ccp.mat,
              col = ccClustCol,
              row_split = order.ccp,
              row_gap = unit(0, "mm"),
              column_split = order.ccp,
              column_gap = unit(0, "mm"),
              border = TRUE,
              row_title = tt,
              show_heatmap_legend = FALSE)
```

**Comment by jokergoo** [comment]
What do you mean by "bordering only the rows"? I guess your heatmap looks like this (only the heatmap)? Can you describe in more details?

![image](https://user-images.githubusercontent.com/449218/152605979-42353da7-7572-4ceb-9e97-ba01234067f9.png)

**Comment by RodrigoGM** [comment]
Hi! yes my heat map looks like that.   Is there a way to have border exclusively on horizontal (i.e. horizontal lines only), not through both x and y; where the clusters are squared out.  The goal is to emphasize one axis and downplay the other to avoid crowding the plot e.g. as is towards the right side of the heatmap.

Thank you again,

**Comment by jokergoo** [comment]
Then how about just setting `row_km`/`row_split`?

```r
Heatmap(m, row_km = 2, gap = unit(0, "mm"), 
    border_gp = gpar(col = "black", lwd = 2), 
    show_row_dend = F, show_column_dend = F)
```

<img width="642" alt="image" src="https://user-images.githubusercontent.com/449218/158352186-fdcc248b-61ed-4153-9be5-65045577eb2e.png">

**Comment by jokergoo** [comment]
In this case, I think the most convenient way is to use `decorate_heatmap_body()` to add lines manually:

```r
m = cor(mtcars)
row_km = kmeans(m, centers = 4)$cluster

Heatmap(m, name = "mat", row_split = row_km, gap = unit(0, "mm"))
# go to each row slice and draw borders
for(i_slice in seq_along(unique(row_km))) {
	decorate_heatmap_body("mat", row_slice = i_slice, {
		grid.rect(gp = gpar(fill = "transparent", lwd = 2))
	})
}
```

<img width="920" alt="image" src="https://user-images.githubusercontent.com/449218/158550861-d10534c2-b3f9-4b30-aba9-359ab02aeaf2.png">
