### ISSUE TITLE
No reproductibility of clusters created during multiple iterations of Heatmap

### ISSUE THREAD

**Issue by Evan-SF** [jokergoo/ComplexHeatmap#867]
Hello,
Thank you very much for this incredible package. I'm posting this issue after many tries because I observe a problem of reproducitibilty in my results. 
In fact, each time I ran the code to generate a heatmap with the parameters row_km & column_km, I don't obtain the same clusters. 
This is problematic because I'm extracting samples from my clusters within the heatmap and I make some new plots with it, but i never obtain the same results...

I tried with or without draw function but the problem still occures. 

Here is 3 heatmaps I generated with the same code with the same data (on Jupyter Notebook)

![image](https://user-images.githubusercontent.com/56911733/152687610-e056f74c-c73d-4fda-88cc-bfd0582b4d0b.png)
![image](https://user-images.githubusercontent.com/56911733/152688183-9dd549a4-6548-4177-992c-69c1e5ffc598.png)
![image](https://user-images.githubusercontent.com/56911733/152687779-8e71c16a-6d5f-4129-9191-8d6d6556e894.png)

Here is the code to generate the heatmap 
`HT_V2 <- draw(Heatmap(t(scale(DATA_V2[9:37])), row_km = 2, column_km = 3, col = col_fun,
                      bottom_annotation = bottom_annot, top_annotation = top_annot, 
                      column_names_rot = 45))`

The code to extract samples from the clusters :
```
order_col = column_order(HT_V2)

CLUSTER_1_V2 = order_col$`1`
CLUSTER_2_V2 = order_col$`2`
CLUSTER_3_V2 = order_col$`3`
# CLUSTER_4_V2 = order_col$`4`
# CLUSTER_5_V2 = order_col$`4`

# Creating "Cluster" annotation column in the raw data for further analysis
DATA_V2$CLUSTER <- "EMPTY"
DATA_V2[CLUSTER_1_V2,]$CLUSTER <- "C1"
DATA_V2[CLUSTER_2_V2,]$CLUSTER <- "C2"
DATA_V2[CLUSTER_3_V2,]$CLUSTER <- "C3"
# DATA_V2[CLUSTER_4_V2,]$CLUSTER <- "C4"
# DATA_V2[CLUSTER_5_V2,]$CLUSTER <- "C5"

paste('Number of patients per Cluster')
table(DATA_V2$CLUSTER)

paste("Patients from Cluster 1")
DATA_V2[CLUSTER_1_V2,]$Numero

paste("Patients from Cluster 2")
DATA_V2[CLUSTER_2_V2,]$Numero

paste("Patients from Cluster 3")
DATA_V2[CLUSTER_3_V2,]$Numero
```

And informations about the working environment :
```
sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
[3] LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] corrplot_0.90              cowplot_1.1.1             
 [3] ggridges_0.5.3             ComplexHeatmap_2.11.1     
 [5] circlize_0.4.13            repr_1.1.3                
 [7] survminer_0.4.9            ggpubr_0.4.0              
 [9] survival_3.2-13            PerformanceAnalytics_2.0.4
[11] xts_0.12.1                 zoo_1.8-9                 
[13] RColorBrewer_1.1-2         forcats_0.5.1             
[15] stringr_1.4.0              dplyr_1.0.7               
[17] purrr_0.3.4                readr_2.0.2               
[19] tidyr_1.1.4                tibble_3.1.6              
[21] tidyverse_1.3.1            factoextra_1.0.7          
[23] ggplot2_3.3.5              pheatmap_1.0.12 
```

Have you any ideas to resolve the problem ? Maybe I'm doing something wrong ? Should I use column_split/row_split in place of row_km/column_km ?

Thank you,
Evan

**Comment by jokergoo** [comment]
Because you turned on kmeans clustering as it depends on random initializations. You need to set the random seed:

```r
# always run these two lines together
set.seed(123)
draw(Heatmap(t(scale(DATA_V2[9:37])), row_km = 2, column_km = 3, col = col_fun, bottom_annotation = bottom_annot, top_annotation = top_annot, column_names_rot = 45))
```

**Comment by Evan-SF** [comment]
> Because you turned on kmeans clustering as it depends on random initializations. You need to set the random seed:
> 
> ```r
> # always run these two lines together
> set.seed(123)
> draw(Heatmap(t(scale(DATA_V2[9:37])), row_km = 2, column_km = 3, col = col_fun, bottom_annotation = bottom_annot, top_annotation = top_annot, column_names_rot = 45))
> ```

Thank you very much !
I understand better thank to your answer and these explanations in your documentation : 
https://www.bioconductor.org/packages/release/bioc/vignettes/ComplexHeatmap/inst/doc/most_probably_asked_questions.html#toc_13
and 
https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#split-by-kmeans-clustering

Which number does I need to set in set.seed() ? As the number influence the results, how does I know which one is the "best" ? A higher number is not related  to a better clustering, it's just a way to retrieve the same results if I understand well ?

After reading the documentation, I should also use row_km_repeats  & column_km_repeats to be sure to obtain the "best" consensus clustering with kmeans and normally I should obtain the exact same clustering most of the time with rare exceptions ?

Thank you,
Evan

**Comment by jokergoo** [comment]
Then that is a problem of how to select a proper k-means clustering results while not a heatmap problem.

The number for `set.seed()` is not important. The thing is if specifying the same random seed, k-means always returns the same results.

`row_km_repeats` and `column_km_repeats` apply k-means clustering several times and find the "consensus clustering results". It can somehow reduce the randomness of k-means but cannot completely get rid of it.

**Comment by Evan-SF** [comment]
> Then that is a problem of how to select a proper k-means clustering results while not a heatmap problem.
> 
> The number for `set.seed()` is not important. The thing is if specifying the same random seed, k-means always returns the same results.
> 
> `row_km_repeats` and `column_km_repeats` apply k-means clustering several times and find the "consensus clustering results". It can somehow reduce the randomness of k-means but cannot completely get rid of it.

Thank you very much for your answer. Do you have some clustering methods to advice except kmeans that I could try in my case and plot later my clusters into complexheatmap ?

**Comment by jokergoo** [comment]
You can check this link: https://stackoverflow.com/questions/15376075/cluster-analysis-in-r-determine-the-optimal-number-of-clusters

You can perform k-means before making the heatmap. Once you have the classification, you can assign it to the `row_split`/`column_split` arguments.
