### ISSUE TITLE
k means clusters not labeled when using row_title

### ISSUE THREAD

**Issue by Alex-Nesta** [jokergoo/ComplexHeatmap#868]
Please provide example datasets and the code you use. It will help me to understand your problem and help you!

Hi, I am trying to split the rows of my heatmap using kmeans clustering, and then investigate those clusters. In all of the examples in the documentation, simply splitting the command row_km clusters the rows and numbers them in the heatmap.

I am getting the clusters, but not the cluster labels. 

my clusters look like this:
![image](https://user-images.githubusercontent.com/41696068/153622404-201dbf92-79d6-4f01-a2e5-6eee1ac9c665.png)

Your clusters look like this:
![image](https://user-images.githubusercontent.com/41696068/153622526-c6f0f4e8-15ca-4b0d-b635-d9dfee40661e.png)

Heatmap(mat, 
        name = "RBP LOG_FC", #title of legend
        column_title = "RBPs", 
        #row_title = "Splice Events",  ## TOGGLE THIS AND YOU WILL LOSE THE CLUSTER ANNOTATION
        row_km = 3,        
        show_column_names = FALSE,
        show_row_names = FALSE,
        left_annotation = ha)

I discovered this is due to using row_title. Is this by design? I think it should be possible to have cluster labels and a general overall row title.

Best,
Alex

**Comment by jokergoo** [comment]
You can do:

```r
ht = Heatmap(mat,
  name = "RBP LOG_FC", #title of legend
  column_title = "RBPs",
  row_km = 3,
  show_column_names = FALSE,
  show_row_names = FALSE,
  left_annotation = ha)
draw(ht, row_title = "Splice Events") # now this is a heatmap list level row title
```
