### ISSUE TITLE
Annotation borders categorical variable

### ISSUE THREAD

**Issue by ND91** [jokergoo/ComplexHeatmap#870]
I am trying to generate a figure consisting of only metadata annotations. Some of these annotations are categorical (such as the biological sex). If I plot them now, the borders are drawn outside of the samples that have the same sex. 

![test](https://user-images.githubusercontent.com/7780335/154957050-e6b20b32-84d5-4ae8-877d-07d4f50a2aa7.png)

Would it be possible to have borders per sample/entry. Like this?

![test](https://user-images.githubusercontent.com/7780335/154957312-4563a3cc-c03f-417e-a463-5b91fbb65f5b.png)

I have played around with `gpar`, but have had little success with it. Below you can find my R code:

```{r}
test_df <- data.frame(SampleID = paste0("P", 1:20),
                      Sex = c(rep(c("Male"), 3), rep("Female", 3), rep("Male", 6), rep("Female", 8)))

test <- HeatmapAnnotation(patientID = anno_text(x = gt_render(test_df$SampleID, 
                                                              align_widths = TRUE), 
                                                just = "left", 
                                                location = 0.25),
                          Sex = test_df$Sex,
                          annotation_name_side = "left", 
                          gp = gpar(col = "black", border = "black"),
                          border = T,
                          col = list(Sex = c("Male" = "#66ccff", 
                                             "Female" = "#ff66cc")))

plot(test)
```

**Comment by jokergoo** [comment]
I think I over-optimized this functionality. It should support the second scenario where all single cell has border. I will fix it soon.

**Comment by jokergoo** [comment]
If you install the current version from GitHub, this problem will be fixed:

```r
test_df <- data.frame(SampleID = paste0("P", 1:20),
                      Sex = c(rep(c("Male"), 3), rep("Female", 3), rep("Male", 6), rep("Female", 8)))

test <- HeatmapAnnotation(patientID = anno_text(x = gt_render(test_df$SampleID, 
                                                              align_widths = TRUE), 
                                                just = "left", 
                                                location = 0.25),
                          Sex = test_df$Sex,
                          annotation_name_side = "left", 
                          gp = gpar(col = "black"),
                          col = list(Sex = c("Male" = "#66ccff", 
                                             "Female" = "#ff66cc")))
plot(test)
```
<img width="919" alt="image" src="https://user-images.githubusercontent.com/449218/155121785-8bf78292-a1f8-46cc-9ee9-8247d2098296.png">

Note, you only set `gp = gpar(col = "black")` and no need to set `border = TRUE`.

**Comment by ND91** [comment]
Much appreciated! This solves this particular issue. Thanks for the prompt fix!
