### ISSUE TITLE
Is there anyway to squeeze the heatmap so that long row names can fit? 

### ISSUE THREAD

**Issue by ahdee** [jokergoo/ComplexHeatmap#873]
Hi, 
I have this issue where sometimes the row names are very long. I tried adjusting the output width to be wider but all that achieve is stretching out the heatmap and the long row names just gets cutoff. 
Here is an example. 

```
mat <- matrix(stats::runif(100, 3, 14), nrow = 10, ncol = 20,
              dimnames = list(paste0("Row____________________________________ looooonnnnnng", 1:10), paste0("Col", 1:20)))



Heatmap(  mat ) 
```
so as you can see, even though I strech the width out all it did was expand the heatmap. Is there way to compress the heatmap so that the row names will fit? 

thanks in advance. Also best heatmap package for R. 

![jxOj5sz 1](https://user-images.githubusercontent.com/9808122/155252478-0143b3a8-c3fd-4b2d-b51e-a5d634dd2be9.png)

**Comment by jokergoo** [comment]
There is an argument `row_names_max_width` with which you can control the exact width of row names. See the 7th plot in this section: https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#dimension-names

**Comment by ahdee** [comment]
@jokergoo perfect thank you. A follow-up question. Is there a way to place `annotation_legend_side` right below the main legend. As of now it is placed to the right of it, however because the heatmap is already squished it ends up taking more room. Than you.

**Comment by jokergoo** [comment]
Then you can set:

```r
draw(ht, merge_legend = TRUE)
```

**Comment by ahdee** [comment]
dude, you thought of so many scenarios, thank you for such a great package.
