### ISSUE TITLE
Remove annotation label, block according to row annotations and colors are not corresponding

### ISSUE THREAD

**Issue by qducarmon** [jokergoo/ComplexHeatmap#877]
Dear,

First of all, thanks for building this great package. 
I have 3 questions: 
 - How do I remove annotation labels? More specifically, I would like to remove the text "amr_row_annotations" from the row_annotations on the bottom of the figure as can be seen below. 
![image](https://user-images.githubusercontent.com/69851249/156574250-ae0549ff-e4c8-4ff5-a216-8dc3e2f11e1c.png)

- How can I block the heatmap based on antibiotic resistance? So that blocks are created for each unique antibiotic (combination) as shown now in the legend of amr_row_annotations? At the same time, I would like to keep the gene names on alphabetical order within each block.

- Lastly, as you can see from the code below, I define the colors for the rowannotations in amr_row_annotations_heatmap. However, the colors are simply not displayed, even though I define them in the same way as I did my column color annotations, which work perfectly fine. The data frame looks like this:
![image](https://user-images.githubusercontent.com/69851249/156574970-c494c5c0-36ff-4b93-8669-52d50ef6b573.png)

```
## Here I define the colors, which should show in the right_annotation below, but for some reason it does not? 

amr_row_annotations_heatmap <- rowAnnotation(df = amr_row_annotations, col = list(Subclass = c("Beta-Lactam"="#A6CEE3", "Vancomycin"="#62A3CB", "Quinolone"="#1F78B4", "Streptomycin"="#68AB9F", "Macrolide"="#B2DF8A", "Tetracycline"="#72BF5B", "Streptothricin"="#33A02C", "Amikacin/Kanamycin"="#979C62", "Lincosamide/Macrolide/Streptogramin"="#FB9A99", "Rifampin"="#EF595A", "Chloramphenicol"="#E31A1C", "Amikacin/Gentamicin/Kanamycin/Tobramycin"="#F06C45", "Aminoglycoside"="#FDBF6F", "Rifaximin"="#FE9F37", "Trimethoprim"="#FF7F00")))

Heatmap(amr_presence_absence_mat, name = "Count", heatmap_legend_param = list(at = c(0, 1, 2), labels = c("0", "1", "2")),
        col = col_presence_absence, cluster_rows = FALSE, show_row_dend = FALSE, top_annotation = heatmap_annotations, show_column_names = FALSE, right_annotation = amr_row_annotations_heatmap, row_order = sort(rownames(amr_presence_absence_mat)))
```

With regard to version numers, I use Complexheatmap v2.6.2 and R 4.0.4 and see further info below.

Thanks a lot for your help in advance,
Quinten

sessioninfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default
attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] RColorBrewer_1.1-2   circlize_0.4.12      ComplexHeatmap_2.6.2 ggnewscale_0.4.6     readxl_1.3.1         treeio_1.14.4       
 [7] ggtree_2.4.1         forcats_0.5.1        stringr_1.4.0        dplyr_1.0.5          purrr_0.3.4          readr_1.4.0         
[13] tidyr_1.1.3          tibble_3.1.0         ggplot2_3.3.3        tidyverse_1.3.0

**Comment by jokergoo** [comment]
1. set `show_annotation_name = FALSE` in `HeatmapAnnotation()`/`rowAnnotation()`.
2. Let's assume the variable is called "amr_row_annotations" and the matrix is `m`, you can do:

```r
amr_row_annotations = factor(amr_row_annotations, levels = sort(unique(amr_row_annotations)))
row_order = order(amr_row_annotations, rownames(m))
Heatmap(m, ..., row_order = row_order)
```
3. Is `amr_row_annotations` in your code a data frame and "Subclass" is its column name? I would suggest to directly use `amr_row_annotations` as a vector because you only have one annotation on rows:

```r
col = c(...)
amr_row_annotations_heatmap <- rowAnnotation(amr = amr_row_annotations, col = list(amr = col))
```

Here `amr` can be any name, but it should match to the name set in `col`.

**Comment by qducarmon** [comment]
Thanks, this clarifies everything!
