### ISSUE TITLE
Selecting a part of heatmap

### ISSUE THREAD

**Issue by beginner984** [jokergoo/ComplexHeatmap#878]
Sorry this is not an issue with your amazing software rather I need help

I have created a heatmap in which I am interested in capturing `miRNAs` (rows) in a certain block of the heatmap
![Untitled](https://user-images.githubusercontent.com/43682980/156793408-244fce76-1372-4c8f-9f7d-183d7bfc3828.jpg)

I thought to count the rows and extract the interesting miRNAs by looking at heatmap but I am certain this is not the right way to do that. The other way is obtaining the name of miRNAs manually which is a pain and error prone.

```
> library(ComplexHeatmap)

> ht = Heatmap(My_matrix of scale values) 
> ht[1:35,1:5]

```
Please help me to capture the wanted part of a heatmap

Thank you so much in advance

**Comment by jokergoo** [comment]
With another package **InteractiveComplexHeatmap**, it will be very easy to obtain these rows. All you need is:

```
library(ComplexHeatmap)
library(InteractiveComplexHeatmap)

Heatmap(My_matrix of scale values)
htShiny()
```

`htShiny()` opens a Shiny app and you can interactively work with your heatmap.

I suggest you to update both **ComplexHeatmap** and **InteractiveComplexHeatmap** to the newest versions from GitHub.

**Comment by beginner984** [comment]
Thanks a lot

I get this error 

![0DDAFC74-732E-493B-B914-5D348F99A4B9](https://user-images.githubusercontent.com/43682980/157231665-a5cdc0e8-e348-4870-b56f-d987ab45499c.jpeg)
