### ISSUE TITLE
have two heatmap aligned vertically

### ISSUE THREAD

**Issue by LuyiTian** [jokergoo/ComplexHeatmap#88]
Hi. thanks for creating this wonderful package, it saves me a lot of times. Is it possible to put two heatmaps in the same column instead of the same row?

**Comment by jokergoo** [comment]
I am sorry it is not supported yet.

**Comment by LuyiTian** [comment]
<img width="47" alt="row_cluster_name" src="https://cloud.githubusercontent.com/assets/3377891/25462287/6b4d61c8-2b31-11e7-85ac-0f3ea7696087.png">

Thank you. Another quick question. do you know how to remove the text in each row clusters？ as the number of cluster increases they huddled together and that is really annoying.

**Comment by jokergoo** [comment]
Currently you can set `combined_name_fun = NULL` in `Heatmap(...)`.

**Comment by anabbi** [comment]
Hi there

I have a similar question. Is it now supported to have oncoprints and heatmaps aligned in one column?


thanks

Arash

**Comment by jokergoo** [comment]
Hi, I am working the new version of the package which will support adding heatmaps by columns. Then it will be simple as just doing:

```{r}
Heatmap(...) %v% oncoPrint(...)
```
