### ISSUE TITLE
bold, italic

### ISSUE THREAD

**Issue by byeongchangsim** [jokergoo/ComplexHeatmap#881]
Hi guys
I have one question. Is there any way to use both bold and italic when using the labels_row command?

If you have any good ideas, please suggest them.

My problem is not using bold and italic for some names of rows, but using both methods to convert row names. Just like the Gene name in the photo below

Thank you.
![image](https://user-images.githubusercontent.com/79529451/157647348-63432a74-26b6-421e-833a-07ee50e12602.png)

@jokergoo 
@PeteHaitch 
@dtenenba 
@apeltzer 
@vobencha

**Comment by bersbersbers** [comment]
I used `ComplexHeatmap::Heatmap(..., row_labels = ComplexHeatmap::gt_render(paste0("*", rownames(df_data), "*"))` today.

**Comment by byeongchangsim** [comment]
> 오늘 사용 `ComplexHeatmap::Heatmap(..., row_labels = ComplexHeatmap::gt_render(paste0("*", rownames(df_data), "*"))`했습니다.
> 
> (죄송합니다, 귀하의 질문을 잘못 읽었습니다.)



> 오늘 사용 `ComplexHeatmap::Heatmap(..., row_labels = ComplexHeatmap::gt_render(paste0("*", rownames(df_data), "*"))`했습니다.
> 
> (죄송합니다, 귀하의 질문을 잘못 읽었습니다.)

**Comment by byeongchangsim** [comment]
> I used `ComplexHeatmap::Heatmap(..., row_labels = ComplexHeatmap::gt_render(paste0("*", rownames(df_data), "*"))` today.
> 
> (Sorry, misread your question.)

Thanks for your reply.

But the code you write is simply
It was confirmed by putting bold and italic in the " * " part.

Then because of the paste
Output as boldGennameitalic.

If there is a better way please tell me

thank you.

@bersbersbers

**Comment by byeongchangsim** [comment]
hello

I have one question. Do you know how to use Heatmap(), theme() and
annotate() functions together among your ComplexHeatmap functions?

Thank you
byeong chang sim

2022년 3월 10일 (목) 오후 8:47, bersbersbers ***@***.***>님이 작성:
