### ISSUE TITLE
Split heatmap by range of rows or columns

### ISSUE THREAD

**Issue by a-a-k** [jokergoo/ComplexHeatmap#884]
How can I achieve this? I don't need to cluster my data at all, but I can't apply splitting without clustering.

P.S. _BTW, are there any docs to describe objects and their properties? For example, I just stuck on the error `Length or ncol of 'column_split' should be same as ncol of 'matrix'` and can't find any definition of `column_split` restrictions._

**Comment by jokergoo** [comment]
Can you provide more information regarding your question? What do you mean by "range of columns"? 

Basically, the variable you set to `column_split` is a categorical variable and its length should be the same as number of columns of your matrix.

**Comment by a-a-k** [comment]
Thank you for your reply!

I have a dataset need to split by rows and columns using indexes. Say, I have 24 columns and want them to split for 3 slices without any logic except their order. First slice for 1,2,3,4,5,6,7,8 columns, second - for 9,10,11,12,13,14,15,16, and so on. Same for rows.

What about `column_split ` - my matrix is 14x24, what number should I set? And, I still didn't get this, what does that parameter exactly mean?

**Comment by jokergoo** [comment]
Then you need to construct a "split variable" which looks like:

```
column_split = rep("group1", 24)
column_split[9:16] = "group2"
column_split[17:24] = "group3"
```

Then assign to the `column_split` argument in `Heatmap()`:

```r
Heatmap(..., column_split = column_split)
```

Then the 24 columns will be split into group 1 (indices 1..8), group 2(indices 9..16) and group 3(indices 17..24)

**Comment by a-a-k** [comment]
Big thanks, that works!
