### ISSUE TITLE
anno_mark one-to-many

### ISSUE THREAD

**Issue by gdagstn** [jokergoo/ComplexHeatmap#889]
Hi, 

I am looking for a way to use the `anno_mark` annotation with a one-to-many approach, e.g. when data points in the rows are made of several components and we want to show that information.

This is what I could come up so far (toy example):

```
d = seq_len(length(LETTERS))

splitby = split(d, ceiling(seq_along(d)/3))

letters_chunks = lapply(splitby, function(x) LETTERS[x])

m = matrix(rnorm(length(letters_chunks) * 10), nrow = length(letters_chunks))

ha = rowAnnotation(foo = anno_mark(at = seq_len(10), labels = lapply(letters_chunks, function(x) paste0(x, collapse = "\n"))))

Heatmap(m, cluster_columns = FALSE, cluster_rows = FALSE, right_annotation = ha)
```
![toy_annomark](https://user-images.githubusercontent.com/21171362/159205464-afde8b4c-dc87-4e75-b8a1-df7a4561bdd3.png)

But this works well only if each chunk is equally sized. 

The other option is to use `paste0(x, collapse = ", ")` in the annotation, but it can get pretty long. 

Is there a way to optimize the annotation label placement so they don't overlap, or any other trick I'm missing? 
I just started using this great library and I'm sure I haven't used it to its full potential. 

Thanks!

**Comment by gdagstn** [comment]
Actually I think I found a solution:

```
library(stringr)

# random inputs
gen_random_string <- function(n){
  random_string = paste0(LETTERS[sample(seq_len(length(LETTERS)), size = n)], collapse = "")
  return(random_string)
}

m = matrix(rnorm(70), nrow = 7)

# generate 7 random sets of labels, each set with a random number of labels each with a random length:
labels_list <- lapply(1:7, function(x) {
  n_items = sample(seq_len(10), size = 1)
  random_strings = unlist(lapply(seq_len(n_items), function(y) {
    string_len = sample(seq_len(8), size = 1)
    return(gen_random_string(string_len))
    }))
})

# Wrap the string to a width of 10 characters and then break line 
labels_list = lapply(labels_list, function(x) 
  paste0(strwrap(paste0(x, collapse = ", "), width = 10), collapse = "\n"))

# Padding is (maximum number of lines in the wrapped labels)/2 to account for worst case
line_pad = max(unlist(lapply(labels_list, function(x) str_count(x, "\n"))))/2


# Create annotation
ha = rowAnnotation(foo = anno_mark(side = "right",
                                   at = seq_len(7), 
                                   labels_gp = gpar(cex = 0.6),
                                   padding = unit(line_pad, "lines"),
                                   link_width = unit(10, "mm"),
                                   labels = labels_list))
# Create heatmap
hm = Heatmap(m,
             cluster_columns = FALSE, 
             cluster_rows = FALSE, 
             right_annotation = ha)

draw(hm, padding = unit(c(0.2,0.1,0.2,.1), "npc"))
```
![toyexample_2](https://user-images.githubusercontent.com/21171362/159214476-bdb8f31a-b4e7-4ceb-9531-ea470ab919a4.png)

However it still required a lot of fiddling with the padding in `draw()` and the `cex` for the labels. 

Is there a way to make sure the annotations are always visible and don't overlap with each other? I thought the padding lines would take care of that, but in some attempts they still overlap.

**Comment by jokergoo** [comment]
I think I will support it in the future (also the many-to-one scenario).

Currently, there is another solution for your case, although it might look a little bit different. You can use the new annotation function `anno_text_box()`:

```r
require(circlize)
mat = matrix(rnorm(100*10), nrow = 100)

split = sample(letters[1:10], 100, replace = TRUE)
text = lapply(unique(split), function(x) {
	data.frame(month.name, col = rand_color(12, friendly = TRUE), fontsize = runif(12, 6, 14))
})
names(text) = unique(split)

Heatmap(mat, cluster_rows = FALSE, row_split = split,
    right_annotation = rowAnnotation(wc = anno_text_box(split, text))
)
```

<img width="920" alt="image" src="https://user-images.githubusercontent.com/449218/159230465-e91f8533-881f-4e93-a3e2-de2a08dd23b9.png">

In `anno_text_box()`, `split` is a list of indices and `text` is a list of text corresponding each group of indices in `split`.

**Comment by gdagstn** [comment]
Thanks! I realized I was using the Bioconductor version and it didn't have `anno_text_box()`. I must confess that for now I prefer the way `anno_link()` looks, so I'll be looking forward to your next implementations.
Thanks again!
