### ISSUE TITLE
Row order when using row_anno_link

### ISSUE THREAD

**Issue by dolevrahat** [jokergoo/ComplexHeatmap#89]
Hello 

I am trying to use row_anno_link to annotate some rows of a Heatmap using the following code:

`ht1 = Heatmap(mat, name = "ht1")`
`ha = rowAnnotation(link=row_anno_link(at=1:nrow(mat),
labels=rownames(mat)),width = unit(2, "cm")+max_text_width(rownames(mat)))`
`draw(ht1+ha,heatmap_legend_side='bottom')`

But I get this plot, in which the order of the rows in the heatmap and in the annotation do not match:
![ht1](https://cloud.githubusercontent.com/assets/12991095/25434626/ade4795a-2a95-11e7-9daa-bdd6b4899f8b.png)

I tried resolving this by suppressing clustering and using row_order as suggested [here](https://github.com/jokergoo/ComplexHeatmap/issues/77):

`roword<-row_order(ht1)`
`ht2<-Heatmap(mat, row_order = unlist(roword),cluster_rows = FALSE)`
`hb = rowAnnotation(link=row_anno_link(at=1:nrow(mat),`
`labels=rownames(mat)[unlist(roword)]),`
`width = unit(2, "cm")+max_text_width(rownames(mat)))`

But this didn't solve the problem either:
![ht2](https://cloud.githubusercontent.com/assets/12991095/25434951/00dd9bfe-2a97-11e7-84a6-d91b59793fe7.png)

I will appreciate your help with this

Best regards and thanks in advance
Dolev

**Comment by jokergoo** [comment]
Hi Dolev,

This was a bug and has been fixed. See #81 

You can update the package from github

```
devtools::install_github("jokergoo/ComplexHeatmap")
```

Cheers,
Zuguang

**Comment by dolevrahat** [comment]
Oops, should have looked around more carefully. My bad.
And of course, thanks for all your wonderful work!. This package practically changed my life!

**Comment by jokergoo** [comment]
No problem. Glad it helps!

**Comment by SarahQi** [comment]
Hello,

Your package is great and I am trying to use row_anno_link(),
 
ha<-rowAnnotation(link=row_anno_link(at=1, labels=rownames(heatmapdata)[1]),width = unit(2, "cm"))+max_text_width(rownames(heatmapdata))

but i always get
![image](https://user-images.githubusercontent.com/80929092/157578501-8e072d45-4f80-493c-9d21-2a57f9b6b257.png)

What do you think might be the problem here?

Thanks in advance,
Sarah

**Comment by jokergoo** [comment]
Please use `anno_link()` directly. I think I removed `row_anno_link()` for some reason (that I've already forgotten :) )

**Comment by SarahQi** [comment]
Thanks, I’ve figured how to use it!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
