### ISSUE TITLE
strange behaviour in cell_fun

### ISSUE THREAD

**Issue by ShinyFabio** [jokergoo/ComplexHeatmap#892]
Hi jokergoo,
I found a strange behaviour when use cell_fun with multiple heatmaps. Here's my code. Basically I take my dataframe and I generate an heatmap for each column. Everything works, except that the cell_fun renders the same number for each heatmap.

```
ht_list = NULL
colors =  RColorBrewer::brewer.pal(8, "Dark2")[-3]
index_color = 1

for(k in colnames(data)){
  
  data_filt = data[k]
  
  #color scale and unit legend
  if(k %in% c("Vitality", "Cytotoxicity")){
    color_scale = circlize::colorRamp2(c(0, 100), c("white", "blue"))
    unit_legend = paste0("%",k)
  }else{
    color_scale = circlize::colorRamp2(c(0, max(data[,k])), c("white", colors[index_color]))
    index_color = index_color+1
    unit_legend = k
  }
  
  #values inside cells
  if(add_values == TRUE){
    cell_values = function(j, i, x, y, width, height, fill) {
      if(abs(as.matrix(data_filt)[i, j]) >= thresh_values){
        grid::grid.text(sprintf("%.0f", as.matrix(data_filt)[i, j]), x, y, gp = grid::gpar(fontsize = 10))
      }
    }
  }else{
    cell_values = NULL
  }
  
  ht_list = ht_list + ComplexHeatmap::Heatmap(as.matrix(data_filt), rect_gp = grid::gpar(col = "white", lwd = 1),
                                              name = k, column_title = k, 
                                              cluster_rows = F, col = color_scale,
                                              cell_fun = cell_values
  )
  
}

ComplexHeatmap::draw(ht_list, padding = grid::unit(c(2,2,2,15), "mm"), ht_gap = grid::unit(1, "cm"))

```

![complexheatmap](https://user-images.githubusercontent.com/78078351/159887615-f936393c-3f5f-481a-ad8c-11d2646970ed.png)

Here's my data. The first column is the rownames (that's why there isn't the colname).

[datatest.txt](https://github.com/jokergoo/ComplexHeatmap/files/8340287/datatest.txt)

Thank you in advance.

**Comment by jokergoo** [comment]
This is something I need to improve. The main reason is there are some variables are "global" to `cell_fun` and they are only looked for when `draw()` is executed. As you can see, your `draw()` is executed outside the `for` loop, and the value of `data_filt` is the last column of `data`.

Currently, you fixed this problem by setting:

```r
cell_values = local({
    data_fit = data_fit
    thresh_values = thresh_values
    function(j, i, x, y, width, height, fill) {
      if(abs(as.matrix(data_filt)[i, j]) >= thresh_values){
        grid::grid.text(sprintf("%.0f", as.matrix(data_filt)[i, j]), x, y, gp = grid::gpar(fontsize = 10))
      }
    }
})
```

where `data_fit` and `thresh_values` are reassigned in a local environment. In this case, each `cell_fun` is defined in different environment and it can be associated to the corrected `data_fit`.

In the future versions, I will use the **globals** package to automatically recognize those "global variables" and save them in the local environment.

**Comment by ShinyFabio** [comment]
It works, thank you very much!

**Comment by jokergoo** [comment]
Just for your information, in the newest version, the "global variables" out of `cell_fun` are automatically captured and saved locally, so you don't need to manually save them any more.

Your original code without using `local()` should work.

**Comment by vkartha** [comment]
@jokergoo  Sorry, seem to be running into the same issue , i.e. each individual heatmap (stored as list entry within loop) produces output as expected when plotted separately later on, but when I try to plot side by side (e.g. h1 + h2), it only uses the last heatmap's values (when using the same cell_fun but on each individual matrix per iteration within loop). This is with v2.10.0

**Comment by vkartha** [comment]
I was able to resolve this only using your local() suggestion above, which worked!
