### ISSUE TITLE
Create HeatmapList from list of Heatmaps

### ISSUE THREAD

**Issue by eggrandio** [jokergoo/ComplexHeatmap#894]
I have created a list of `Heatmap` objects through `mapply` and I would like to plot them together to compare them. I have several lists of heatmaps so I would like to do it programatically.
```
> ht_list_from_mapply %>% class
[1] "list"
> ht_list_from_mapply[1] %>% class
[1] "list"
> ht_list_from_mapply[[1]] %>% class
[1] "Heatmap"
attr(,"package")
[1] "ComplexHeatmap"
```
If I do this I get a HeatmalList object:
```
> ht_list = ht_list_from_mapply[[1]] + ht_list_from_mapply[[2]]
> ht_list %>% class
[1] "HeatmapList"
attr(,"package")
[1] "ComplexHeatmap"
```
But this does not work:
```
> ht_list = HeatmapList(ht_list_from_mapply)
Error in initialize(value, ...) : 
  cannot use object of class “list” in new():  class “HeatmapList” does not extend that class
```
Is there an easy way to convert a list of Heatmaps to HeatmapList ? I have tried `unlist`, `c`, but they do not work.

I can make it through a loop, but I was wondering if there was a more straightforward way of constructing a HeatmapList
```
ht_list = NULL

for(i in seq_along(ht_list_from_mapply)){
  ht_list = ht_list + ht_list_from_mapply[[i]]
}

ht_list %>% class
[1] "HeatmapList"
attr(,"package")
[1] "ComplexHeatmap"
```

**Comment by jokergoo** [comment]
You can first run the following commands:

```r
setAs("list", "HeatmapList", function(from) {
	ht_list = NULL
	for(i in seq_along(from)) {
		ht_list = ht_list + from[[i]]
	}
	ht_list
})
```

Then you can use `as(ht_list_from_mapply, "HeatmapList")` to convert to the `HeatmapList` object.

**Comment by jokergoo** [comment]
Now I have included that piece of code in ComplexHeatmap. You can directly update the package from GitHub and use `as()`.
