### ISSUE TITLE
Attempt to get HeatmapAnnotation to block annotate based on two binary discrete conditions: second condition out of order

### ISSUE THREAD

**Issue by jarcosh** [jokergoo/ComplexHeatmap#895]
Good afternoon, 

first off thanks for the very complete documentation that allowed me to get this far even with my rusty R skills and no experience so far using R for heatmaps.

I'm attempting to use ComplexHeatmap to reproduce output similar to 

![image](https://user-images.githubusercontent.com/80825033/160163237-71122d53-e6a5-4df3-92f4-7180aab6c4d0.png)

and then keep working from there, taking advantage of the greater flexibility your library offers.

My data originally is just a csv file with a first column as sample label, two more columns for two conditions with two discrete options and the rest being just the estimated relative concentrations of several compounds, which is what I hope the heatmap illustrates.

Initially I simply do
```
FullData<-read.csv("data_Combined.csv", header = TRUE, sep = ";")
DataMinusConditions <- FullData[, 4:13]
```
This to remove the first three columns that label samples and give the two conditions, and leave a number only dataframe that can be converted to matrix with no issue.
```
matdof = t(DataMinusConditions)
matdof = log(matdof)
```
this to rotate the data correctly respect to default orientation (compounds on the right not on top) and avoid outliers making the heatmap look like a blob of two colors only.

Finally, initially I was a bit confused with the legend tutorial in the documentation, so I followed the examples from the "Practical Guide to Cluster Analysis in R" book, noticed the library has been updated since the book was written, and finally used this to give the heatmap the groups by giving it the non-numeric columns of the original dataframe as vectors:

```
ha <- HeatmapAnnotation(celltype = FullData$cell.type, condition = FullData$condition, col=col)
Heatmap(matdof, rect_gp = gpar(col = "black"), top_annotation=ha)
```

The output was then this:

![image](https://user-images.githubusercontent.com/80825033/160165915-657368f8-fc92-4701-9705-1105a617a0e9.png)
Now I noticed that the two celltypes are all grouped together just fine, but for 'condition' with options Hypo and Norm the order of the columns is mixed up. Initially I said fair enough, ComplexHeatmaps doesn't automatically order my data, I will change the order manually. but even when
````
> FullData[,2:3]
   condition cell.type
1       Hypo      PCAF
2       Hypo      PCAF
3       Hypo      PCAF
4       Hypo      PCAF
5       Norm      PCAF
6       Norm      PCAF
7       Norm      PCAF
8       Norm      PCAF
9       Hypo      WMPY
10      Hypo      WMPY
11      Hypo      WMPY
12      Hypo      WMPY
13      Hypo      WMPY
14      Norm      WMPY
15      Norm      WMPY
16      Norm      WMPY
17      Norm      WMPY
18      Norm      WMPY
````
the heatmap still gets the order of the samples just fine for celltype but not for condition

![image](https://user-images.githubusercontent.com/80825033/160167277-80a3bafc-f490-4bf1-959a-dbcd1b2bcaad.png)

Hopefully the explanation was clear enough with code examples and purpose, but if it was not I could provide data .csv if my boss gives permission. I assume this is not an error in the library but something simple I must be misunderstanding, but I can't figure out with the documentation what.

Thanks in advance

**Comment by jokergoo** [comment]
You need to turn off clustering on columns. In the first heatmap you provided, I believe there was no column clustering.

You can set `cluster_columns = FALSE` in `Heatmap()`.

**Comment by jarcosh** [comment]
Thanks, that must have indeed been my mistake not noting that section of the documentation, instead just seeing different ways to cluster the columns under that argument.
