### ISSUE TITLE
size limit on 'grid_width' for the legend

### ISSUE THREAD

**Issue by coffeebond** [jokergoo/ComplexHeatmap#896]
Hi, I'm not sure if this is an issue of the package or something I have missed, but when I try to control the width of a vertical legend body (continuous) using "grid_width, the size doesn't change as I expect. Here is a figure I try to make:

[heatmap.pdf](https://github.com/jokergoo/ComplexHeatmap/files/8358269/heatmap.pdf)

I used `grid_width = unit(0.1, "inch")` for all three legends, but only the width of the discrete legend (legend 3) is set at the correct size. My guess one possible issue could be the white tick bar inside the legend prevented the size setting for the width of the legend. If so, is there a way to change the size of the tick bar?

Thanks!

**Comment by jokergoo** [comment]
It is because there are white borders. See https://github.com/jokergoo/ComplexHeatmap/issues/807#issuecomment-922860566

**Comment by coffeebond** [comment]
Thank you. This is helpful. I was using an older version and there wasn't such an option. Now I've updated and it has been solved.

Related to my question, is there a way to change the length of the bar of the breaks inside the legend?

**Comment by jokergoo** [comment]
Currently no, but as you suggested, I will add it in the future.

**Comment by coffeebond** [comment]
Great. Thank you.
