### ISSUE TITLE
Not a validObject(): no slot of name "subsetable"

### ISSUE THREAD

**Issue by ShinyFabio** [jokergoo/ComplexHeatmap#897]
Hi jokergoo,
I'm working on a new project and I make some complexheatmaps. However when I open the R project and I load the library `{ComplexHeatmap}`, I get these warnings:

```
Warning messages:
1: Not a validObject(): no slot of name "subsetable" for this object of class "HeatmapAnnotation" 
2: Not a validObject(): no slot of name "subsetable" for this object of class "SingleAnnotation" 
3: Not a validObject(): no slot of name "subsetable" for this object of class "AnnotationFunction" 
4: Not a validObject(): no slot of name "subsetable" for this object of class "HeatmapAnnotation" 
5: Not a validObject(): no slot of name "subsetable" for this object of class "SingleAnnotation" 
6: Not a validObject(): no slot of name "subsetable" for this object of class "AnnotationFunction" 
```

The problem appears only when I load the package inside this R project and only the first time I load it. In other R project I don't have it. Do you know why I have these warnings? I don't even understand what do they mean.

I have the latest version of R (4.1.3) and ComplexHeatmap (2.10.0).

**Comment by jokergoo** [comment]
Sorry, you need to update the package from GitHub and regenerate all your heatmap objects. The slot name has been changed to `subsettable` in recent versions.

Or you can just use an older version of ComplexHeatmap, e.g. < 2.8.0 or maybe ealier.

**Comment by ShinyFabio** [comment]
Ok good so wasn't my fault. Is it only an internal change or do I need to modify something in the code?

**Comment by jokergoo** [comment]
No, you don't need to do anything.

**Comment by ShinyFabio** [comment]
Ok good. So to prevent this warning I have to install the package from GitHub instead of Bioconductor, am I right?

**Comment by jokergoo** [comment]
Do you only use ComplexHeatmap or also other packages, e.g. EnrichedHeatmap?

**Comment by ShinyFabio** [comment]
Also InteractiveComplexHeatmap, in fact I wanted also to ask you which is the best way to install them. For now, I added both in the description file under biocViews (but sometimes I have some errors and so I have to install them manually).

**Comment by jokergoo** [comment]
Ah, then you need to install both from GitHub. Bioc release branch is a little old for these two packages.

**Comment by ShinyFabio** [comment]
Ok so in Description file I can write:
```
Remotes: 
  jokergoo/ComplexHeatmap,
  jokergoo/InteractiveComplexHeatmap
```
Correct?

**Comment by jokergoo** [comment]
Will you submit your package to Bioconductor? If so, you can simply specify the version requirement as:

```
ComplexHeatmap (>= 2.11.0), InteractiveComplexHeatmap (>= 1.3.0)
```

If not,  you have to wait until May (I guess this is the next Bioconductor release)

If you submit to CRAN, you also have to wait because CRAN tests packages with Bioc release branch.

If you just put the package on GitHub, I think it is OK just to specify them in `Remotes`.

**Comment by ShinyFabio** [comment]
For now I'll just put the package on GitHub. Thank you a lot, I didn't know these things. I'm still newbie in the package deployment process.

**Comment by ShinyFabio** [comment]
I'm sorry to bother you, but I have installed the packages from GitHub and I'm still having the same warnings. I have them even If I simply load the ComplexHeatmap package (now 2.11.1 version). The problem seems to be worse: with the bioconductor version I had those warnings only with my last project. Now with the GitHub version I have them also with another project. 

To be clear, if I open a new R project (so completely empty) the problem disappears.

**Comment by jokergoo** [comment]
Have you also updated InteractiveComplexHeatmap package? and restarted your R session?

**Comment by ShinyFabio** [comment]
Yes. It seems it's something related also to the R project somehow. I made the test (simply opening the project and attached the complexheatmap package) with three projects, let's call them A,B,C.
Project A (the newest): warnings both with bioconductor and github versions
Project B (less new): warnings only with github version
Project C (old): no issues.

Cleaning all the objects from the workspace didn't help. I also removed the function that draws the heatmap from my package but no changes. Maybe is it something corrupted in these R Projects? What does those warnings means? Maybe I can try to isolate the problem.

**Comment by jokergoo** [comment]
```
Warning messages:
1: Not a validObject(): no slot of name "subsetable" for this object of class "HeatmapAnnotation" 
2: Not a validObject(): no slot of name "subsetable" for this object of class "SingleAnnotation" 
3: Not a validObject(): no slot of name "subsetable" for this object of class "AnnotationFunction" 
4: Not a validObject(): no slot of name "subsetable" for this object of class "HeatmapAnnotation" 
5: Not a validObject(): no slot of name "subsetable" for this object of class "SingleAnnotation" 
6: Not a validObject(): no slot of name "subsetable" for this object of class "AnnotationFunction" 
```

This means some objects were generated with ComplexHeatmap where the slot name was defined as `subsetable` and the version under use defines the slot as `subsettable`.

**Comment by joey0214** [comment]
Hi, I still have this error ( 'subsetable' is not a slot in class "AnnotationFunction") when using the function "EnrichedHeatmap"

EnrichedHeatmap 1.24.0 
ComplexHeatmap 2.13.2 

is using an older version of ComplexHeatmap, e.g. < 2.8.0 the only solution?

Best regards,
Joey

**Comment by joey0214** [comment]
> Have you restarted your R session? [@joey0214](https://github.com/joey0214)

yes, both restarted R session and rstudio, but still not works
