### ISSUE TITLE
Space between a legend and the main panel

### ISSUE THREAD

**Issue by wenbostar** [jokergoo/ComplexHeatmap#899]
Is there a way to move the legend a bit closer to the border of the main panel as shown below?

<img width="305" alt="image" src="https://user-images.githubusercontent.com/5302110/162072463-70ad2d36-0abd-48dc-b964-bb8ec6016a07.png">

**Comment by wenbostar** [comment]
I just found this could be adjusted ht_opt$HEATMAP_LEGEND_PADDING.

**Comment by jokergoo** [comment]
Yes :)
