### ISSUE TITLE
Greek symbols in titles?

### ISSUE THREAD

**Issue by kcha** [jokergoo/ComplexHeatmap#9]
It is possible to plot greek symbols in titles (as well as legend titles)? Using `expression()` doesn't seem to work:

```
library(ComplexHeatmap)
mat = matrix(rnorm(100), 10)
Heatmap(mat, column_title = expression(beta))

Error in column_title == "" : comparison is not allowed for expressions
In addition: Warning message:
In is.na(column_title) :
  is.na() applied to non-(list or vector) of type 'expression'
```

Thanks

**Comment by jokergoo** [comment]
I just updated the package on Github. Now you can set expression in row title, column title and heatmap legend title:

```r
mat = matrix(rnorm(100), 10)
Heatmap(mat, column_title = expression(beta), row_title = expression(alpha), heatmap_legend_title = expression(theta))
```
![rplot001](https://cloud.githubusercontent.com/assets/449218/8661198/45d0b9e6-29b6-11e5-8bba-00c266696a9d.png)

However, setting annotation legend title as an expression is not straightforward, you can modify the slot in the `HeatmapAnnotation` object:

```r
ha = HeatmapAnnotation(data.frame(type = rep(letters[1:2], 5)))
ha@anno_list[[1]]@color_mapping@legend_title = expression(alpha)
Heatmap(mat, top_annotation = ha)
```

**Comment by kcha** [comment]
The update seems to work perfectly. Thanks for your great work!
