### ISSUE TITLE
How to combine the dendrogram tree and heatmap with right order

### ISSUE THREAD

**Issue by Feng-Zhang** [jokergoo/ComplexHeatmap#904]
For some reasons, I want to custom plot [cnv heatmap](https://github.com/broadinstitute/inferCNV/wiki/images/infercnv.png) created by plot_cnv function from [infercnv package](https://github.com/broadinstitute/infercnv).
Due to the complex source code of plot_cnv function, I want to plot the cnv heatmap using ComplexHeatmap.
Actually, infercnv outputs the dendrogram tree, but the order between dendrogram and matrix row is different. I have struggle days for combining the dendrogram and heatmap.

How can we merge them together with right order. Here, I give a example for illustartion.

```{r}
rm(list=ls());options(stringsAsFactors=FALSE)
library(ComplexHeatmap)
library(circlize)
set.seed(123)
nr1 = 4; nr2 = 8; nr3 = 6; nr = nr1 + nr2 + nr3
nc1 = 6; nc2 = 8; nc3 = 10; nc = nc1 + nc2 + nc3
mat = cbind(rbind(matrix(rnorm(nr1*nc1, mean = 1,   sd = 0.5), nr = nr1),
                  matrix(rnorm(nr2*nc1, mean = 0,   sd = 0.5), nr = nr2),
                  matrix(rnorm(nr3*nc1, mean = 0,   sd = 0.5), nr = nr3)),
            rbind(matrix(rnorm(nr1*nc2, mean = 0,   sd = 0.5), nr = nr1),
                  matrix(rnorm(nr2*nc2, mean = 1,   sd = 0.5), nr = nr2),
                  matrix(rnorm(nr3*nc2, mean = 0,   sd = 0.5), nr = nr3)),
            rbind(matrix(rnorm(nr1*nc3, mean = 0.5, sd = 0.5), nr = nr1),
                  matrix(rnorm(nr2*nc3, mean = 0.5, sd = 0.5), nr = nr2),
                  matrix(rnorm(nr3*nc3, mean = 1,   sd = 0.5), nr = nr3))
)
mat = mat[sample(nr, nr), sample(nc, nc)] # random shuffle rows and columns
rownames(mat) = paste0("row", seq_len(nr))
colnames(mat) = paste0("column", seq_len(nc))
dend = as.dendrogram(hclust(dist(mat)))
plot(dend)

mat2 <- mat[sample(1:nrow(mat)),]
```

Similarly, we only have dend and mat2 variable, and can get the heatmap using :
```{r}
Heatmap(mat2, cluster_rows = dend,row_split = 2)
```
![image](https://user-images.githubusercontent.com/7855694/163536474-c54e6346-7f82-4967-adb1-1c95a0ee6ad0.png)
![image](https://user-images.githubusercontent.com/7855694/163536601-8538dc68-fc8c-4a2e-bd93-4685abf3f8e9.png)

However, the row order of heatmap is not right, which is different with `plot(dend)`. How can we get heatmap with right order like this below without the mat variable.
```{r}
Heatmap(mat, name = "mat", cluster_rows = dend,row_split = 2)
```
![image](https://user-images.githubusercontent.com/7855694/163536748-21453000-1b19-4079-bfcf-7322fbaca353.png)

Thank you in advance.

**Comment by jokergoo** [comment]
For the first plot where the matrix is `mat2`, `mat2` is a permutation of the original `mat`, then of course the labels of `mat2` is different from the labels in `dend` (what I mean is the dendrogram is identical but the labels are different).

**Comment by Feng-Zhang** [comment]
> For the first plot where the matrix is `mat2`, `mat2` is a permutation of the original `mat`, then of course the labels of `mat2` is different from the labels in `dend` (what I mean is the dendrogram is identical but the labels are different).

What I can get are the mat2 and dend, how can I plot the dendrogram and heatmap together? Maybe I can re-order the matrix to keep same label with dend, and use the `cluster_rows = FALSE,row_order =labels(dend)` parameters. However, how can I plot the dend?

By the way, the infercnv acturally output the matrix and dendrogram file. But I was failed to load the dendrogram file due to the [multiple tree issue](https://github.com/broadinstitute/infercnv/issues/411). That is why the labels between dend and mat2 is different because I manually merge the dendrogram tree. Sorry for asking a question which is not related to the ComplexHeatmap package here.

**Comment by jokergoo** [comment]
If you can provide me the dendrogram from **infercnv**, as well as the matrix, I can help you with that.

**Comment by Feng-Zhang** [comment]
> If you can provide me the dendrogram from **infercnv**, as well as the matrix, I can help you with that.

Thank your for your help.  Please find the dendrogram file and the matrix file below. 
[infercnv.observations_dendrogram.txt](https://github.com/jokergoo/ComplexHeatmap/files/8693207/infercnv.observations_dendrogram.txt)
[infercnv.observations.txt](https://github.com/jokergoo/ComplexHeatmap/files/8693209/infercnv.observations.txt)

**Comment by jokergoo** [comment]
```r
mat = read.table("~/Downloads/infercnv.observations.txt", check.names = FALSE)

library(ape)
tree = read.tree("~/Downloads/infercnv.observations_dendrogram.txt")
t = tree[[1]]
t = as.dendrogram(as.hclust(t))

mat2 = mat[sample(nrow(mat), 10), labels(t)]

Heatmap(mat2, cluster_columns = t)
```

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/449218/171118930-57244c3a-2606-489f-a20c-6b3c5ed24a05.png">
