### ISSUE TITLE
Annot mark on the column split cluster

### ISSUE THREAD

**Issue by hiraksarkar** [jokergoo/ComplexHeatmap#905]
Hi,
I want to add anno_mark to the column clusters, for example given the following code, 
```
m = matrix(rnorm(12000), nc = 100)
colnames(m) = 1:100
fa = rep(c("a", "b", "c"), times = c(2, 48, 50))
fa_col = c("a" = 2, "b" = 48, "c" = 50)
dend1 = cluster_between_groups(m, fa)
Heatmap(m, cluster_columns = dend1, column_split = 3,
    show_column_names = FALSE, 
    show_row_dend = FALSE,
    row_title = "cluster_between_groups",
    top_annotation = HeatmapAnnotation(foo = fa, col = list(foo = fa_col)))
```   
![image](https://user-images.githubusercontent.com/9473877/164053827-a2a1715f-2663-4d23-85cd-57efa1664e9c.png)

I want the following figure , 
![image](https://user-images.githubusercontent.com/9473877/164054445-f37a621c-dcab-4706-9b72-81e5f8bf8fd4.png)

I know that this could be done by `anno_mark`, but not skilled enough to do it. Any help would be great. 

Best,
Hirak

**Comment by jokergoo** [comment]
You can just define a bottom annotation with `anno_mark()`:

```r
Heatmap(m, cluster_columns = dend1, column_split = 3,
    show_column_names = FALSE, 
    show_row_dend = FALSE,
    row_title = "cluster_between_groups",
    top_annotation = HeatmapAnnotation(foo = fa, col = list(foo = fa_col)),
    bottom_annotation = HeatmapAnnotation(mark = anno_mark(at = 1, labels = "a", side = "bottom")))
```

<img width="917" alt="image" src="https://user-images.githubusercontent.com/449218/164245628-26acad87-bbc3-48d6-837d-193fa1dd47ab.png">

Or set multiple markers:

```r
Heatmap(m, cluster_columns = dend1, column_split = 3,
    show_column_names = FALSE, 
    show_row_dend = FALSE,
    row_title = "cluster_between_groups",
    top_annotation = HeatmapAnnotation(foo = fa, col = list(foo = fa_col)),
    bottom_annotation = HeatmapAnnotation(mark = anno_mark(at = 1:2, labels = c("a", "b"), side = "bottom")))
```

<img width="915" alt="image" src="https://user-images.githubusercontent.com/449218/164245761-47527f86-24f6-48a3-8ea2-94c5af6788b8.png">

**Comment by hiraksarkar** [comment]
Hi @jokergoo ,

That's very helpful thanks!. While this is a great solution, just wondering if it's possible anno_mark on the clusters themselves rather than by column index.
