### ISSUE TITLE
How to keep the annotation color unchanged (without specifying the annotation color) when I replot heatmap?

### ISSUE THREAD

**Issue by YonghuiDong** [jokergoo/ComplexHeatmap#906]
I am using `ComplexHeatmap` in my shiny app to produce heatmap. Unlike [pheatmap](https://github.com/raivokolde/pheatmap/issues/85) , the heatmap is perfectly rendered in shiny and it is compabible with other interactive plots generated with `plotly`.  Thank a lot.

I am wondering if there is a way to keep the annotation color unchanged (without specifying the annotation color) upon the reactive events in Shiny?

A simple example describing my need is as following:
```
library(ComplexHeatmap)
test = matrix(rnorm(200), 20, 10)
test[1:10, seq(1, 10, 2)] = test[1:10, seq(1, 10, 2)] + 3
test[11:20, seq(2, 10, 2)] = test[11:20, seq(2, 10, 2)] + 2
test[15:20, seq(2, 10, 2)] = test[15:20, seq(2, 10, 2)] + 4
colnames(test) = paste("Test", 1:10, sep = "")
rownames(test) = paste("Gene", 1:20, sep = "")
annotation_col = data.frame(
  CellType = factor(rep(c("CT1", "CT2"), 5)), 
  Time = 1:5
)
rownames(annotation_col) = paste("Test", 1:10, sep = "")
annotation_row = data.frame(
  GeneClass = factor(rep(c("Path1", "Path2", "Path3"), c(10, 4, 6)))
)
rownames(annotation_row) = paste("Gene", 1:20, sep = "")
pheatmap(test, annotation_col = annotation_col, annotation_row = annotation_row)
```
When I re-run the above code, the annotation color changes accordingly.

Thanks a lot.

Dong

**Comment by malcook** [comment]
FWIW: I too have wished for the same outside of Shiny context when replotting a heatmap.  It is unsettling when the colors change apparently for no reason.

**Comment by jokergoo** [comment]
Because if you do not set the colors explicitly, random colors will be used (the ComplexHeatmap version of pheatmap). You can either set colors by `annotation_colors` argument or add a fixed random seed before you run `pheatmap()`:

```r
set.seed(123)
pheatmap(...)
```
