### ISSUE TITLE
rasterize annotations

### ISSUE THREAD

**Issue by z5ouyang** [jokergoo/ComplexHeatmap#907]
Thanks for this amazing tool! This might not be an issue, just a function request: Add rasterization for the annotation bar. When there are many (10k) rows with annotations, the file size is large although the heatmap itself is rasterized.
Thanks!

**Comment by jmw86069** [comment]
+1 this request.
I also noticed with many rows, the annotation bar is not rasterized, so the colors can be overlapping in some outputs.

I worked around it by creating a second heatmap with the annotation data, and used rasterization on that heatmap. Then I added the heatmaps together for the final figure. It worked well but took a bit more effort to put together, mapping colors and all.

I agree not urgent but “nice to have.” :)

**Comment by jokergoo** [comment]
OK, added to my to-do list. This request is general (should be applied to all types of annotation graphics) and it might take long to implement.

**Comment by malcook** [comment]
@jokergoo - I just came here to request the same and found it already requested and done.  

It worked perfectly for me after taking the update.  Thanks so much!

**Comment by malcook** [comment]
@jokergoo thanks for the clarification.  I had assumed incorrectly from seeing the issue closed.  

FWIW: In case you are unaware of the approach to selectively rasterizing ggplot layers provided by [ggrastr](https://cran.r-project.org/web/packages/ggrastr/vignettes/Raster_geoms.html) -  I have recently had great success with it on other plot types.

Thanks for CH!
