### ISSUE TITLE
non-numeric argument to binary operator

### ISSUE THREAD

**Issue by ATVincent** [jokergoo/ComplexHeatmap#91]
Hello,

I found that is impossible to plot two heatmaps using an Rscript. The following code works well in Rstudio, but gave me an error when executed as a script (Error in ht1 + ht2 : non-numeric argument to binary operator):

``` r
library(ComplexHeatmap)
library(circlize)

mat1 = matrix(rnorm(80, 2), 8, 10)
mat1 = rbind(mat1, matrix(rnorm(40, -2), 4, 10))
rownames(mat1) = paste0("R", 1:12)
colnames(mat1) = paste0("C", 1:10)

mat2 = matrix(rnorm(60, 2), 6, 10)
mat2 = rbind(mat2, matrix(rnorm(60, -2), 6, 10))
rownames(mat2) = paste0("R", 1:12)
colnames(mat2) = paste0("C", 1:10)

ht1 = Heatmap(mat1, name = "ht1")
ht2 = Heatmap(mat2, name = "ht2")

draw(ht1+ht2)
```
Is there a way to bypass this issue?

Thank you!

**Comment by jokergoo** [comment]
Hi, that's something I need to check.

It seems it relates to the R versions. I tried with R-3.1.2 and everything is fine, but if with R-3.3.1, I have same error as yours.

Currently I have no clue to solve this problem. If you are urgent to use it by Rscript, you can change to

```
draw("+.AdditiveUnit"(ht1, ht2))
```

**Comment by jokergoo** [comment]
You can also put `library(methods)` as the first line in your R script.

**Comment by antony03** [comment]
thank you!

**Comment by LimperScience** [comment]
I am similarly having the same problem and wanted to follow up and see whether there is a solution to this now?

**Comment by jokergoo** [comment]
What is your session info? It seems it only relates to old versions.

**Comment by LimperScience** [comment]
I am new to rstudio ... but when I try to combined my two heatmaps made via
pheatmap:

heatmap_middle + heatmap_young

I get the following error:

Error in heatmap_middle + heatmap_young :
  non-numeric argument to binary operator

**Comment by jokergoo** [comment]
No worries :)

Can you provide your full set of code? Is the `pheatmap()` function from pheatmap package or ComplexHeatmap package?
