### ISSUE TITLE
how to transform the cell into square

### ISSUE THREAD

**Issue by ryrl9703** [jokergoo/ComplexHeatmap#910]
Hello, I want to change the shape of the cell in the heatmap like this, how should I do in complexHeatmap
![微信图片_20220426180007](https://user-images.githubusercontent.com/87462884/165275549-13d2bece-12ef-4714-bd85-5807e8d657e7.png)

**Comment by jokergoo** [comment]
You can set `width` and `height` arguments in "snpc" units:

```{r}
m  = matrix(rnorm(200), nrow = 10)

Heatmap(m, width = unit(0.8, "snpc"), height = unit(0.4, "snpc"))
```

<img width="895" alt="image" src="https://user-images.githubusercontent.com/449218/167487711-4ae13df2-1eb0-47a7-901b-c7f38d146001.png">

PS: just found a bug where legend is aligned to the right of the whole plot, which causes that when "snpc" is set for `width`, white gap may be between the heatmap and legends. I will fix that.

**Comment by ryrl9703** [comment]
> You can set `width` and `height` arguments in "snpc" units:
> 
> ```
> m  = matrix(rnorm(200), nrow = 10)
> 
> Heatmap(m, width = unit(0.8, "snpc"), height = unit(0.4, "snpc"))
> ```
> 
> <img alt="image" width="895" src="https://user-images.githubusercontent.com/449218/167487711-4ae13df2-1eb0-47a7-901b-c7f38d146001.png">
> 
> PS: just found a bug where legend is aligned to the right of the whole plot, which causes that when "snpc" is set for `width`, white gap may be between the heatmap and legends. I will fix that.

Thanks for your reply, this has solved the problem that has been bothering me for a long time
