### ISSUE TITLE
Error trying to run HeatmapAnnotation()

### ISSUE THREAD

**Issue by Pio82** [jokergoo/ComplexHeatmap#913]
I'm attempting to run a block for HeatmapAnnotation.  I'm getting the error: 

 "Error in col2rgb(colors, alpha = TRUE : invalid RGB specification"
 I've copied the code below:

ha_column = HeatmapAnnotation(df = df,
col = list(Diagnosis = c("Uterine endometrial" =     "#DDCC77F",  "Ovarian endometrioid" = "#0F7554", "Ovarian mucinous" = "#44AA99",                                                          "Colorectal mucinous" = "#882255",
"Pancreas mucinous" = "#AA4499",
"Stomach mucinous" = "#D695D0"),

Tumor.Normal = c("N" = "grey", "T" = "black"),

study = c("cgid" = "#332288", "tcga" = "#BD9AF7")))

I'm running rstudio 2022.02.2 Build 485 with R 4.2 on an Apple Mac Pro running macOS Monterey version 12.3.1.

Please advise what the problem might be.  Many thanks in advance.

**Comment by RamRS** [comment]
Cross-posted and solved on Bioinfo SE: https://bioinformatics.stackexchange.com/q/19022/650

**Comment by jokergoo** [comment]
The color code `"#DDCC77F"` should be either `"#DDCC77FF"` or `"#DDCC77"`.
