### ISSUE TITLE
More option to split the heatmap

### ISSUE THREAD

**Issue by chiwwong** [jokergoo/ComplexHeatmap#915]
I am trying to replot the TOM plots from `WGCNA `where they used dynamic treecut and they have the hanging dendrogram, which I am not sure if either the default distant or clustering function can be used to do the same job. An example of such a plot can be found in [Figure 1 of this link](https://horvath.genetics.ucla.edu/html/CoexpressionNetwork/Rpackages/WGCNA/Tutorials/FemaleLiver-05-Visualization.pdf). While 

Thus, I was supplying the heatmap with both row and column dendrograms, but I cannot split the heatmap by cluster labels. I encountered the following error message:

> Error: When `cluster_rows` is a dendrogram, `row_split` can only be a single number. 

I was using the code with something similar to this:

```
Heatmap(plotTOM, # here is the input mat
        cluster_rows = hang.dendrogram(as.dendrogram(net$dendrograms[[1]])), 
        cluster_columns = hang.dendrogram(as.dendrogram(net$dendrograms[[1]])), 
        show_row_names = FALSE, 
        show_column_names = FALSE, 
        top_annotation = HeatmapAnnotation(cluster = anno_simple(factor(net$colors), na_col = "white")), 
        left_annotation = rowAnnotation(cluster = anno_simple(factor(net$colors), na_col = "white")),
        row_split = as.character(net$colors), 
        column_split = as.character(net$colors))
```

The main intention is to _add a rectangle to bracket each cluster_ as described similarly in 2.9.2 in your vignette. I am also open to other solutions that can bypass the split, as I am going to reduce the split gap to 0 at the end. 

The following code does work, but it did not preserve the order from the dendrogram/ hcluster for the whole heatmap,

```
Heatmap(plotTOM,
        column_order = net$dendrograms[[1]]$order,
        row_order = net$dendrograms[[1]]$order,
        # cluster_rows = hang.dendrogram(as.dendrogram()), 
        # cluster_columns = hang.dendrogram(as.dendrogram(net$dendrograms[[1]])), 
        show_row_names = FALSE, 
        show_column_names = FALSE, 
        top_annotation = HeatmapAnnotation(cluster = anno_simple(factor(net$colors), na_col = "white")), 
        left_annotation = rowAnnotation(cluster = anno_simple(factor(net$colors), na_col = "white")),
        row_split = as.character(net$colors), 
        column_split = as.character(net$colors))
```

Please let me know if you need more detailed code, and I can try to produce a minimal reproducible example.

Thanks!

**Comment by jokergoo** [comment]
That is because if you specify the dendrogram for `cluster_rows`, you can only split `split_rows` as a number where internally `cutree()` will be applied.

In your case, dynamic tree cut is a very specific method and ComplexHeatmap does not support it.

I have a similar case as yours where the dendrogram split is not the "standard cutree". The main idea is to draw the vertical lines and horizontal lines manually to simulate they are split. You can check the source code from below:

https://github.com/jokergoo/simplifyEnrichment/blob/756b5fa69b6db825300f902f0762acb91db844e1/R/binary_cut.R#L556-L564
