### ISSUE TITLE
merge several anno_density into one

### ISSUE THREAD

**Issue by loganylchen** [jokergoo/ComplexHeatmap#919]
Hi @jokergoo,

I have encountered some questions when I wanted to use ComplexHeatmap to visualize my data.
I will show the figure first then describe my question:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/25150929/167616509-ba50ae9d-7f12-43e6-8a08-7e5978f1d28a.png">

As I wanted to compare the densities of different sample classes, if I visualized the densities like the figure shown above, it was not easy to compare them, even if the difference is obvious. 

I am wondering if I could merge the three density annotations into one and use different colors to distinguish different classes. 
I saw some of visualizing functions in R using `hue="class_label_column"` to do this.

Here are attached my codes to repeat the example above:
```R
options(repr.plot.width =10, repr.plot.height =6)
m = as.matrix(cbind(matrix(rnorm(100), 10),matrix(rnorm(100)+4, 10),matrix(rnorm(100)+12, 10)))
ha = HeatmapAnnotation(boxanno = anno_boxplot(m, height = unit(2, "cm"), 
    box_width = 0.9, outline = FALSE))
ha2 = rowAnnotation(
    classA = anno_density(m[,1:10], which = "row",joyplot_scale = 2, 
                            gp = gpar(fill = "#CCCCCC80")),
    classB = anno_density(m[,11:20], which = "row",joyplot_scale = 2, 
                            gp = gpar(fill = "#CCC99C80")),
    classC = anno_density(m[,21:30], which = "row",joyplot_scale = 2,
                            gp = gpar(fill = "#CC99CC80"))      
                            )
Heatmap(m,column_split=c(rep('A',10), rep('B',10), rep('C',10)),top_annotation=ha,right_annotation=ha2,cluster_column_slices = FALSE)

```

Best,
Logan

**Comment by jokergoo** [comment]
Very nice suggestion! I will put it into my to-do list.

**Comment by loganylchen** [comment]
Thanks~

**Comment by loganylchen** [comment]
@jokergoo May I ask another question?

If I could set the xlim for the  anno_density, if so how to set?

**Comment by jokergoo** [comment]
It is not supported yet. I will add it later today.

**Comment by loganylchen** [comment]
Hi @jokergoo,

Thanks for your consideration. I think the parameter `max_density` does help me in the following manipulation of the heatmap. I could easily merge them through adobe illustrator.   

Again, really nice visualization package.

Best,
Logan
