### ISSUE TITLE
rotate split names for heatmap lists (row_sub_title_rot)

### ISSUE THREAD

**Issue by jantusan** [jokergoo/ComplexHeatmap#920]
Hello, I am plotting a list of heatmaps with splitting, and I wonder if the labels for the split slices could be rotated to horizontal as in [a single heatmap](https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#titles-for-splitting) with `row_title_rot = 0`. I tried `row_sub_title_rot = 0` as an equivalent to `row_sub_title_side` but that parameter doesn't seem to exist. 

Is there another way to rotate the text?

**Comment by jokergoo** [comment]
`row_title_rot = 0` should work. What is your version of ComplexHeatmap?

**Comment by jantusan** [comment]
I am using the latest version, `v2.11.2`. 

`row_title_rot = 0` works when drawing a single heatmap, but gives an error when drawing a heatmap list:
```
draw(ht_list, split = …, row_sub_title_side = "left", main_heatmap = …, row_title_rot = 0)
```
gives me:
```
Error in .local(object, ...) : unused argument (row_title_rot = 0)
```
