### ISSUE TITLE
Missing secondary class alteration

### ISSUE THREAD

**Issue by sridhar0605** [jokergoo/ComplexHeatmap#923]
Please provide example datasets and the code you use. It will help me to understand your problem and help you!
Hi @jokergoo , 
Thanks for developing Complexheatmap. 

Could you please confirm if you can replicate this tutorial https://jokergoo.github.io/ComplexHeatmap-reference/book/oncoprint.html#complex-alteration-types
I could not generate the secondary class (intronic, exonic) legends as seen in  alterations in the final image.
Using
`ComplexHeatmap       * 2.2.0    2019-10-29 [1] Bioconductor  `

Thank you
Sridhar

**Comment by jokergoo** [comment]
2.2.0 is too old, please update the package.
