### ISSUE TITLE
Squeeze dendrogram except main branches 

### ISSUE THREAD

**Issue by elpavlos** [jokergoo/ComplexHeatmap#925]
Hi,
I was wondering if there is a way to keep main branches of the dendrogram big enough in order to be visible in the final plot but squeeze the rest of the dendrogram to gain some space. I use the following code to create the Heatmap and I would like to have something similar to the attached figure where the branches corresponding to the clusters are bigger.  

```r
Heatmap(as.matrix(df), name = " ", top_annotation = ha, rect_gp = gpar(col = "white", lwd = 2),

heatmap_legend_param = list(at = c(-4, -2, 0, 2, 4), title = "Z scores", legend_height = unit(8, "cm"), grid_width = unit(0.5, "cm"), labels_gp = gpar(fontsize = 16), title_gp = gpar(fontsize = 18, fontface = "bold")),

cluster_columns = TRUE, column_dend_reorder = FALSE, clustering_distance_columns = "euclidean",  show_column_names = FALSE,

cluster_rows = TRUE, row_dend_reorder = TRUE, 

column_names_side = "bottom", row_names_side = "left",

row_split = 3,  column_split = 3, 

column_title = c("A", "B", "C"), column_title_gp = gpar(fontsize = 18, fontface = "bold"),
border = TRUE, 
row_title = NULL, #column_title = NULL,
row_names_gp = grid::gpar(fontsize = 16), #column_names_gp = grid::gpar(fontsize = 8),

column_dend_height = unit(0.5, "cm"), row_dend_width = unit(0.5, "cm"), 
row_gap = unit(4, "mm"), column_gap = unit(4, "mm")
)
```

![abg9873-F1](https://user-images.githubusercontent.com/12587086/169769182-b96e48ab-ed83-42df-9962-3c8f1fc71ded.jpg)

Thanks!

**Comment by jokergoo** [comment]
How about using `cluster_within_group()`? See the last plot in this section:

https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#clustering-methods

**Comment by elpavlos** [comment]
You mean I have to apply the HC method before running the `Heatmap()` and then use its results (e.g. grouping123) within `Heatmap()` with arguments `cluster_columns=FALSE` and `cluster_within_group=grouping123` instead of `cluster_columns=TRUE`?

There is no way to use as group in `cluster_within_group` the HC results of `Heatmap()` itself?

**Comment by elpavlos** [comment]
Nice! 
I did it as follows:

`distance_mat_Cols <- dist(as.matrix(t(df)), method = 'euclidean')`
`Hierar_cl_Cols <- hclust(distance_mat, method = "complete")`
`fitCols <- cutree(Hierar_cl_Cols, k = 3)`

`distance_mat_Rows <- dist(as.matrix((df)), method = 'euclidean')`
`Hierar_cl_Rows <- hclust(distance_mat_Rows, method = "complete")`
`fitRows <- cutree(Hierar_cl_Rows, k = 3)`

`Heatmap(`
`as.matrix(df),`
`clustering_distance_columns = "euclidean",`
`cluster_columns = cluster_within_group(df, fitCols), column_dend_reorder = FALSE`,
`cluster_rows = cluster_within_group(t(df), fitRows), row_dend_reorder = TRUE`,
`row_split = 3,column_split = 3, column_title = c("A", "B", "C"),`
`column_dend_height = unit(1.5, "cm"), row_dend_width = unit(1.5, "cm")`
`)`

Thanks for your time and for the nice work on ComplexHetamap!
