### ISSUE TITLE
Missing data in oncoPrint

### ISSUE THREAD

**Issue by kotliary** [jokergoo/ComplexHeatmap#931]
It took me a while to figure out how to deal with missing values in my data (gene not sequenced, or the quality of the sequencing doesn't allow to make a conclusion if there is alteration or not). You need to convert NA to a character string, define the graphics in alt_fun, and make sure there is no color for that "alteration type" in the color vector that you pass to the col argument to exclude it from the top and right bar plots. 

I think it would be great if oncoPrint can deal with NAs by default with some default alt_fun (with ability to customize it). Or at least add a section to the tutorial. 

#373

**Comment by prinkessbambi** [comment]
Hi, I think I've got a related problem. In my oncoprint, "NA" is blank (or white) and "wt" is beige (background in alter_fun). However, "NA" variables are counted as alterations and are factored into the percent signs that are displayed on an oncoprint. Does your solution address this?

**Comment by kotliary** [comment]
Remove the color for 'wt' from the color vector in the `col` argument.

**Comment by prinkessbambi** [comment]
Unfortunately this did not work, but that's ok!

**Comment by kotliary** [comment]
Check [7.1.4 Complex alteration types](https://jokergoo.github.io/ComplexHeatmap-reference/book/oncoprint.html#complex-alteration-types) in the ComplexHeatmap book. It provides an example how to exclude certain alterations (in this case, intronic and exonic markers) from the barplots.

**Comment by prinkessbambi** [comment]
Unfortunately, this only removes the alterations from the barplot itself, not from the percentages calculation itself

**Comment by kotliary** [comment]
Ah, you are talking about parcentages on the left side. I usually just remove them with `show_pct = FALSE`.

**Comment by kotliary** [comment]
By the way, you can show fractions instead of counts on the row (or column) barplot:
`right_annotation = rowAnnotation(row_barplot = anno_oncoprint_barplot(show_fraction = TRUE)`

**Comment by prinkessbambi** [comment]
Unfortunately, I've gotten the error, "unused argument (pct_include = c("snv", "indel"))". Before I ran your snippet of code, I ran install_github("jokergoo/ComplexHeatmap", force = T). This should update to the latest version that would have the new argument, "pct_inside", right?

**Comment by keremw** [comment]
This is great. Thank you very much. Now the only problem that stayed is how to reorder the genes according to the correct calculated percentage and not according to the inclusion of the NA.
