### ISSUE TITLE
`rowAnnotation` for world cloud does not align after using `repr.plot.height`

### ISSUE THREAD

**Issue by hassanfa** [jokergoo/ComplexHeatmap#933]
Working with the example for word cloud, I noticed adding: `options(repr.plot.width=15, repr.plot.height=15)` to adjust the size in Jupyter Notebook, `rowAnnotation` does not align well.

I can save it just fine, but it is a hassle not to being to adjust it the size within Jupyter.

Example:

```R
require(circlize)
mat = matrix(rnorm(100*10), nrow = 100)

split = sample(letters[1:10], 100, replace = TRUE)

text = lapply(unique(split), function(x) {
    data.frame(month.name, col = rand_color(12, friendly = TRUE), fontsize = runif(12, 6, 14))
})

names(text) = unique(split)

# Adjust size:
options(repr.plot.width=15, repr.plot.height=15)

Heatmap(mat, cluster_columns = FALSE, cluster_rows = FALSE, row_split = split,
    right_annotation = rowAnnotation(wc = anno_text_box(split, text))
)
```

output:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/1086877/171007449-205321ae-ad48-4155-83cb-5dae22acb204.png">

**Comment by jokergoo** [comment]
I don't work with Jupyter notebook, so I don't know what is going on there.

But what I can tell you is that the calculation of positions of the word clouds (the grey rectangles) depend on the size of the "graphics device".

I just installed Jupyter, let's see whether I can fix this problem.

**Comment by jokergoo** [comment]
I think internally, `Heatmap()` still detects the graphics device size as 7x7. If you do like follows, the annotation is corrected aligned.

<img width="843" alt="image" src="https://user-images.githubusercontent.com/449218/171147242-e75630f8-9b5b-4522-9fd9-538c4228ee34.png">

Let's see whether I can detect the current environment is Jupyter.

**Comment by jokergoo** [comment]
Do you know how does `options(repr.plot.width=15, repr.plot.height=15)` work? Even when I change the values for these two options, the device size is still the default:

<img width="577" alt="image" src="https://user-images.githubusercontent.com/449218/171147894-124fea3d-248f-4278-b74b-24398c7dafda.png">

**Comment by jokergoo** [comment]
A temporary solution is to use the following function:

```r
make_heatmap_jupyter = function(ht) {
	width = getOption("repr.plot.width")
	height = getOption("repr.plot.height")

	p = grid.grabExpr(draw(ht), width = width, height = height)
	grid.draw(p)
}
```

Here `ht` is your heatmap/heatmap list object:

<img width="518" alt="image" src="https://user-images.githubusercontent.com/449218/171154990-f3489ce9-73fe-415e-9dd1-d0f994bfcd3b.png">

<img width="757" alt="image" src="https://user-images.githubusercontent.com/449218/171155122-1f2e4af2-8b18-4547-a189-6447ef00b773.png">

**Comment by jokergoo** [comment]
Now it is supported to automatically recognize Jupyter environment. Please update from GitHub.

<img width="727" alt="image" src="https://user-images.githubusercontent.com/449218/171165037-6833faaa-afcc-47c0-8867-c528624aca57.png">

<img width="685" alt="image" src="https://user-images.githubusercontent.com/449218/171165206-edea7ecd-b5a1-4287-964d-2a2d10306eee.png">

**Comment by hassanfa** [comment]
Thank you for looking into this and for the quick fix. Interesting that they were managed separately. `repr` package makes all sorts of objects available, device and display size are among many. Comes handy trying to access various objects, not just plotting, and manipulate them. Maybe I should have looked into to access it via `repr`.

I'll install the latest version and try it out. Shall I close this issue, or would you like to keep it open?
