### ISSUE TITLE
Tile Heatmaps with different number of rows

### ISSUE THREAD

**Issue by christopher-holt** [jokergoo/ComplexHeatmap#937]
Is there a way to make a tiled heatmap where the heatmaps have different numbers of rows? The matrices also have differing number of columns so vertical heatmaps are not an option. I am using the ComplexHeatmap::draw function to draw a precompiled list of Heatmaps

This is the error I am getting:
Error: `nrow` of all heatmaps should be the same for horizontal heatmap list.

**Comment by jokergoo** [comment]
Then you can use other packages to combine heatmaps, such as cowplot or pathwork.

**Comment by christopher-holt** [comment]
Thank you!
