### ISSUE TITLE
How to add a custom HeatmapAnnotation to rows in the oncoprint() funciton?

### ISSUE THREAD

**Issue by mpschr** [jokergoo/ComplexHeatmap#95]
Hi,

I am trying to add a custom HeatmapAnnotation analogous to the `top_annotation = HeatmapAnnotation()` but I did not find any solution. Is it possible at all?

Best,
mpschr

**Comment by mpschr** [comment]
Ok, nevermind I just found it!

```oncoprint(...) + HeatmapAnnotation(...., which='rows')```

**Comment by jokergoo** [comment]
or you can use

```
oncoPrint(...) + rowAnnotation(...)
```

They are identical.

**Comment by mpschr** [comment]
Ok, thanks!
