### ISSUE TITLE
rowAnnotations and legend colors do not match

### ISSUE THREAD

**Issue by sbamin** [jokergoo/ComplexHeatmap#97]
Hi,

I am making a heatmap primarily for categorical data with a few columns of continuous data where columns are metadata and rows are samples. I read through your documentation (thanks for details) and find that while using `rowAnnotation` object with `Heatmap`, color labels for legends and in rowAnnotations do not match. 

Please see if you can debug with following example data.

Thanks,
Samir

1. [example_data.zip](https://github.com/jokergoo/ComplexHeatmap/files/1024452/example_data.zip)
2. [sample_heatmap.pdf](https://github.com/jokergoo/ComplexHeatmap/files/1024453/sample_heatmap.pdf)

![sample_heatmap](https://cloud.githubusercontent.com/assets/12156027/26387524/620708bc-401c-11e7-946c-a94d73a633d0.png)

**Comment by jokergoo** [comment]
Hi Samir,

In  your code, you turned off the legends for the first two heatmaps and set the width of the row annotation to zero, which means, the legends on the plot actually correspond to the invisible row annotations. You will see it by modifying the row annotation to:

```{r}
ha_row <- rowAnnotation(df = example_annot,
                        col = row_annot_col,
                        annotation_legend_param = list(
                          col2 = list(ncol = length(levels(example_annot$col2))), 
                          col4 = list(ncol = length(levels(example_annot$col4))),
                          col5 = list(ncol = 3, title = "custom_title_col5", 
                                      title_position = "topcenter"),
                          col3 = list(ncol = length(levels(example_annot$col3)))),
                        width = unit(40, "mm"),
                        show_annotation_name = TRUE,
                        na_col = "black")
```

but still there is a bug that the legend labels are wrong when putting it in multiple columns (the `col5` legend). I will fix it and will let you know.

![snapshot7](https://cloud.githubusercontent.com/assets/449218/26394742/380152f0-406e-11e7-9ed2-39246d3f3bab.png)

**Comment by sbamin** [comment]
Thanks for quick reply. I ran following code and get what I needed. col6 and col7 width are too big but will fix it. Since ht2 was rowAnnotation data frame and I needed custom colors instead of default ones, I can now do `ht1 + ha_row` to map continuous data (col6, col7) to categorical data. I think legends are plotted correctly if `ncol x nrow` equals length of levels for that col (col5). I changed `ncol=2` for `col5` in `ha_row`, and now it is showing the way I need it! Perhaps, `NA` is creating issue when length of levels does not equal to ncol x nrow.

You may close this issue. However, bug fix will be a good for fixing legends for multiple columns when length of level is an odd number.

```r
## add row annotations
ha_row <- rowAnnotation(df = example_annot,
                        col = row_annot_col,
                        annotation_legend_param = list(
                          col2 = list(ncol = length(levels(example_annot$col2))), 
                          col4 = list(ncol = length(levels(example_annot$col4))),
                          col5 = list(ncol = 2, title = "custom_title_col5", 
                                      title_position = "topcenter"),
                          col3 = list(ncol = length(levels(example_annot$col3)))),
                        width = unit(40, "mm"),
                        show_annotation_name = TRUE,
                        na_col = "black")

## heatmap with custom colored annotations

ht1 <- Heatmap(matrix = example_mat,
               cluster_rows = FALSE, 
               cluster_columns = FALSE, 
               show_row_names = FALSE,
               show_heatmap_legend = FALSE,
               na_col = 'black')

ht1 + ha_row
```
![sample_image](https://cloud.githubusercontent.com/assets/12156027/26408100/e1b55494-406a-11e7-909e-14221b670fe8.png)
